import type { FilterGroup, JsonBlock } from '../types';
import type { RepeatRule } from '../scheduling/types';
export type ActionValue = unknown;
export type ValueOperation = 'set' | 'add' | 'remove' | 'clear' | 'toggle';
export type ActionStep = {
  id: string;
  type: 'set' | 'create' | 'edit' | 'insert' | 'notify' | 'reminder' | 'variable' | 'open' | 'trash';
  target?: string;
  databaseId?: string;
  templateId?: string;
  title?: ActionValue;
  values?: Record<string, ActionValue>;
  operations?: Record<string, ValueOperation>;
  filters?: FilterGroup;
  filterFormula?: string;
  blocks?: JsonBlock[];
  position?: 'start' | 'end' | 'beforeButton' | 'afterButton';
  text?: ActionValue;
  at?: ActionValue;
  name?: string;
  value?: ActionValue;
  mode?: 'full' | 'side' | 'center';
};
export type ButtonConfig = { label?: string; confirmation?: string; actions: ActionStep[] };
export type AutomationTrigger = { id: string; type: 'created' | 'property'; propertyId?: string };
export type DatabaseAutomation = {
  id: string;
  name: string;
  enabled: boolean;
  disabledReason?: string;
  triggers: AutomationTrigger[];
  triggerMode?: 'any' | 'all';
  filters?: FilterGroup;
  viewId?: string;
  actions: ActionStep[];
  schedule?: RepeatRule;
};
export type ActionRun = {
  id: string;
  at: number;
  kind: 'button' | 'automation';
  name: string;
  ownerId: string;
  sourceId: string;
  status: 'success' | 'error';
  error?: string;
  steps?: { id: string; type: string; result: unknown }[];
  scheduledFor?: string;
};
export type ActionEffect = { type: 'open'; pageId: string; mode?: 'full' | 'side' | 'center' };
