import {translate as uiText,useI18n,interfaceLocale,interfaceLanguage} from '../i18n'
import {ENGINE_DEFINITIONS,assertEngineWorkspace} from '../../../shared/engines'
import {managementRoles,isSupervisor,rolePolicy,type ManagementRole} from '../../../shared/roles'
import {ManagementPanel} from '../components/ManagementPanel'
import {ModelSelect} from '../components/ModelSelect'
import {AppSelect} from '../components/AppSelect'
import {RemoteConnectionFields} from './RemoteConnectionFields'
import {EmployeeFolderPicker} from './EmployeeFolderPicker'
import { useEffect,useState } from 'react'
import {api} from '../api'
import { SELECTABLE_AVATARS,currentAvatar, AVATAR_LABELS, SPRITE_COLORS, ROOM_THEMES, roomDesign, employeeDirectoryName, type RoomDesign } from '../../../shared/office'
import {canBindNativeSession,type Engine,type EmployeeKind,type RoomLayout,type StoredSession,type TeamSettings } from '../../../shared/types'
import type {PluginDescriptor} from '../../../shared/plugins'
import { Mascot } from './Mascot'
import { initialBounds, DEFAULT_POLYGON, MIN_ROOM_HEIGHT, type RoomBounds } from '../../../shared/canvas'
import { PolygonEditor } from './PolygonEditor'
import { EngineMark } from '../components/EngineMark'

const THEMES = ['苔绿', '海蓝', '玫瑰', '琥珀', '暮紫', '岩灰']
export type EmployeeFields = Partial<StoredSession> & { title: string; engine: Engine; group: string; teamRoot?:string; directoryMode?:'default'|'bind' }
export function EmployeeForm({ employee, template, groups, roots = {}, settings={}, onSave,onBound }: {
  employee?: StoredSession;template?:Partial<StoredSession>; groups: string[]; roots?: Record<string,string>; settings?:Record<string,TeamSettings>;onSave: (fields: EmployeeFields) => Promise<boolean>;onBound?:(card:StoredSession)=>Promise<void>|void
}) {
  useI18n()

  const templateAvatar=SELECTABLE_AVATARS.find(avatar=>avatar===currentAvatar(template?.avatar??'fireball'))??'fireball'
  const [fields, setFields] = useState<EmployeeFields>({ title: '', engine: template?.engine??'codex',kind:template?.kind??'worker', group: template?.group&&groups.includes(template.group)?template.group:groups[0]??'', avatar: templateAvatar, accessory:template?.accessory??'none', color:templateAvatar===currentAvatar(template?.avatar??'fireball')?(template?.color??SPRITE_COLORS[templateAvatar]):SPRITE_COLORS[templateAvatar],role:template?.role??'',model:template?.model,effort:template?.effort,permissionMode:template?.permissionMode,thinking:template?.thinking,planMode:template?.planMode,fastMode:template?.fastMode,workEnvironment:template?.workEnvironment,managementRole:template?.managementRole??'employee',...employee,...(employee&&!roots[employee.group]?{cwd:settings[employee.group]?.mode==='work'?employeeDirectoryName(employee.title):'.'}:{}) })
  const [saving, setSaving] = useState(false)
  const [folder,setFolder]=useState(''),[error,setError]=useState('')
  const localWorkspace=settings[fields.group]?.mode==='cloud'&&fields.workEnvironment==='local'
  const workspaceRoot=localWorkspace?folder:roots[fields.group]??folder
  const [directoryMode,setDirectoryMode]=useState<'default'|'bind'>(employee?.directoryMode??template?.directoryMode??'default')
  useEffect(()=>{
    if(employee||!fields.group||groups.includes(fields.group))return
    setFields(previous=>({...previous,group:'',cwd:'',remote:undefined}));setDirectoryMode('default')
  },[groups,fields.group,employee])
  const [pickerOpen,setPickerOpen]=useState(false)
  const [engineCheck,setEngineCheck]=useState<{state:'idle'|'checking'|'ready'|'error';message:string}>({state:'idle',message:''})
  const [nativeSessions,setNativeSessions]=useState<{id:string;cwd:string;preview:string}[]>([]),[nativeId,setNativeId]=useState(''),[nativeBusy,setNativeBusy]=useState(false)
  const report=(error:unknown)=>setError(String((error as Error).message||error).replace(/^Error invoking remote method '[^']+': Error: /,''))
  useEffect(()=>{let active=true;if(localWorkspace&&employee?.group===fields.group&&employee.localWorkspaceRoot){setFolder(employee.localWorkspaceRoot);return}if(!localWorkspace&&roots[fields.group]){setFolder(roots[fields.group]);return}setFolder('');if(fields.group)void api.call<{path:string}>('workspace.suggest',{team:fields.group,workEnvironment:fields.workEnvironment}).then(result=>{if(active)setFolder(result.path)}).catch(report);return()=>{active=false}},[fields.group,fields.workEnvironment,roots[fields.group]])
  useEffect(()=>setPickerOpen(false),[fields.group])
  useEffect(()=>{
    if(fields.kind!=='cloud-native-worker'||employee&&fields.engine===employee.engine){setEngineCheck({state:'ready',message:''});return}
    if(settings[fields.group]?.mode!=='cloud'){setEngineCheck({state:'error',message:'请先选择已绑定主机的云端 Team'});return}
    try{assertEngineWorkspace(fields.engine,'cloud',fields.kind)}catch(error){setEngineCheck({state:'error',message:(error as Error).message});return}
    let active=true;setEngineCheck({state:'checking',message:'正在检查云端 Coding Agent…'})
    void api.call<{version:string;authentication:string}>('engine.remote-check',{team:fields.group,engine:fields.engine}).then(result=>{if(active)setEngineCheck({state:'ready',message:`${result.version} · 认证 ${result.authentication}`})}).catch(error=>{if(active)setEngineCheck({state:'error',message:(error as Error).message})})
    return()=>{active=false}
  },[fields.kind,fields.group,fields.engine,employee?.engine,settings[fields.group]?.hostId])
  const patch = (next: Partial<EmployeeFields>) => setFields((prev) => ({ ...prev, ...next }))
  const work=settings[fields.group]?.mode==='work'
  const teamCloud=settings[fields.group]?.mode==='cloud'
  const cloud=teamCloud&&!localWorkspace
  const engineWorkspaceError=(engine:Engine)=>{try{assertEngineWorkspace(engine,work?'work':cloud?'cloud':'build',fields.kind??'worker');return ''}catch(error){return (error as Error).message}}
  const binding=!employee&&!cloud&&!roots[fields.group]
  const choose=async()=>{try{const result=await api.call<{path:string|null}>('workspace.choose',{path:fields.cwd||workspaceRoot});if(result.path){patch({cwd:result.path});setDirectoryMode('bind');setError('')}}catch(e){report(e)}}
  return <form className="employee-form" onSubmit={async (e) => { e.preventDefault();if(!employee&&!groups.includes(fields.group)){setError('请选择当前视图中仍然存在的 Team');return} setSaving(true);setError('');try { const saved=await onSave(employee?{title:fields.title,engine:fields.engine,group:employee.group,avatar:fields.avatar,accessory:fields.accessory,color:fields.color,role:fields.role}:{...fields,managementRole:cloud?'employee':fields.managementRole??'employee',accessMode:'trusted',remote:undefined,...(binding?{teamRoot:folder.trim()}:{}),directoryMode,cwd:directoryMode==='default'?undefined:fields.cwd?.trim()});if(!saved)setError('保存未完成，请检查目录配置。') } catch(error){report(error)} finally { setSaving(false) } }}>
    <div className="employee-preview"><div className="preview-halo" /><Mascot kind={fields.avatar} accessory={fields.accessory} color={fields.color} /><span>{fields.title || uiText("Your next teammate")}</span><small>{fields.kind==='cloud-native-worker'?uiText("Cloud Native Worker"):uiText("Local Worker")}  {uiText("· Coding Agent")}</small></div>
    <div className="form-section"><div className="field-heading">{uiText("Choose your companion")} <span>{SELECTABLE_AVATARS.length}  {uiText("companions · Customize their colors")}</span></div>
      <div className="avatar-options">{SELECTABLE_AVATARS.map((avatar) => <button type="button" key={avatar} className={currentAvatar(fields.avatar??'fireball') === avatar ? 'selected' : ''} onClick={() => patch({ avatar,color:SPRITE_COLORS[avatar],accessory:'none' })} aria-label={uiText("Choose {0}",[AVATAR_LABELS[avatar]])}><Mascot compact kind={avatar} accessory="none" color={currentAvatar(fields.avatar??'fireball')===avatar?fields.color:SPRITE_COLORS[avatar]} /><span className="avatar-label">{AVATAR_LABELS[avatar]}</span></button>)}</div>
    </div>
    <div className="form-row"><label>{uiText("Employee name")}<input name="title" required value={fields.title} onChange={(e) => patch({ title: e.target.value })} placeholder={uiText("e.g. Codey")} />{employee&&<small className="name-lock-note">{uiText("Only changes the display name; the working folder keeps its original name")}</small>}</label><label>{uiText("Execution location")}<AppSelect name="kind" disabled={!!employee} value={fields.kind??'worker'} onChange={e=>{const kind=e.target.value as EmployeeKind;patch({kind,managementRole:kind==='cloud-native-worker'?'employee':fields.managementRole,workEnvironment:kind==='cloud-native-worker'?'team':fields.workEnvironment,model:undefined,group:kind==='cloud-native-worker'&&settings[fields.group]?.mode!=='cloud'?'':fields.group,cwd:''});setDirectoryMode('default')}}><option value="worker">{uiText("Local Worker · Runs on the Core host")}</option><option value="cloud-native-worker">{uiText("Cloud Native Worker · Runs on the cloud host")}</option></AppSelect></label></div>
    <div className="form-row"><label>{uiText("Team membership")}<AppSelect name="group" disabled={!!employee} value={fields.group} onChange={(e) => {patch({ group: e.target.value,managementRole:settings[e.target.value]?.mode==='cloud'&&fields.workEnvironment!=='local'?'employee':fields.managementRole,workEnvironment:settings[e.target.value]?.mode==='work'?'team':fields.workEnvironment, cwd: '',remote:undefined,...(fields.kind==='cloud-native-worker'?{model:undefined}:{}) });setDirectoryMode('default')}}><option value="" disabled>{uiText("Choose Team")}</option>{groups.filter(g=>fields.kind!=='cloud-native-worker'||settings[g]?.mode==='cloud').map((g) => <option key={g} value={g}>{g}{roots[g] ? '' : uiText("(Configure the directory below)")}</option>)}</AppSelect></label></div>
    {teamCloud&&fields.kind!=='cloud-native-worker'&&<label>{uiText("Work environment")}<AppSelect name="workEnvironment" disabled={!!employee} value={fields.workEnvironment??'team'} onChange={event=>{const workEnvironment=event.target.value as 'team'|'local';patch({workEnvironment,managementRole:workEnvironment==='team'?'employee':fields.managementRole,cwd:''});setDirectoryMode('default')}}><option value="team">{uiText("Team cloud workspace")}</option><option value="local">{uiText("Core local workspace · Supports management roles")}</option></AppSelect><small>{uiText("Management roles use the Core host’s workspace. Managers control their own Team; Governors manage across Teams; Secretaries manage the app and plugins.")}</small></label>}
    {employee?<ManagementPanel employee={employee} cloud={settings[employee.group]?.mode==='cloud'&&employee.workEnvironment!=='local'}/>:<div className="form-row"><label>{uiText("Role")}<AppSelect name="managementRole" value={fields.managementRole??'employee'} onChange={event=>{const managementRole=event.target.value as ManagementRole;patch({managementRole,...(isSupervisor(managementRole)&&teamCloud?{workEnvironment:'local' as const,cwd:''}:{})});if(isSupervisor(managementRole)&&teamCloud)setDirectoryMode('default')}}>{managementRoles().map(role=><option key={role.value} value={role.value} disabled={role.requiresLocal&&fields.kind==='cloud-native-worker'}>{uiText(role.label)}</option>)}</AppSelect><small>{uiText(rolePolicy(fields.managementRole).description)}</small></label></div>}
    <button type="button" className="text-button" onClick={()=>void api.call('view.open',{kind:'settings'})}>{uiText("Engine detection, installation and configuration")}</button>
    {employee?<div className="employee-engine-fixed"><EngineMark engine={employee.engine} size={22}/><span>{ENGINE_DEFINITIONS[employee.engine].label}<small>{uiText("The engine is fixed at creation. To change it, delete the employee and create a new one.")}</small></span></div>:<div className="engine-choices">{(['codex', 'claude', 'cline', 'pi'] as const).map((engine) => <button type="button" key={engine} data-engine={engine} disabled={!!engineWorkspaceError(engine)} title={engineWorkspaceError(engine)||undefined} className={engine === fields.engine ? 'selected' : ''} onClick={() => patch({ engine,model:undefined,thinking:false })}><EngineMark engine={engine} size={22} /><span>{ENGINE_DEFINITIONS[engine].label}<small>{engine==='cline'||engine==='pi'?uiText("DeepSeek Flash · Thinking off · Local / Tunnel cloud"):engine === 'codex' ? uiText("Choose a model to begin") : (fields.kind==='cloud-native-worker'?uiText('Use Claude Agent on the cloud host'):uiText('Use your Claude configuration'))}</small></span></button>)}</div>}
    {!employee&&engineWorkspaceError(fields.engine)&&<p className="employee-form-error" role="alert">{engineWorkspaceError(fields.engine)}</p>}
    {!employee&&<label>{uiText("Execution permissions")}<AppSelect name="permissionMode" value={fields.permissionMode??'default'} onChange={e=>patch({permissionMode:e.target.value as StoredSession['permissionMode']})}><option value="default">{uiText("Ask · Approve when needed")}</option><option value="acceptEdits">{uiText("Workspace write · Workspace edits")}</option><option value="bypassPermissions">{uiText("Full access · Trust the host account")}</option></AppSelect><small>{uiText("Management authority and engine file-execution permissions are independent.")}</small></label>}
    {!employee&&<ModelSelect engine={fields.engine} kind={fields.kind} team={fields.kind==='cloud-native-worker'?fields.group:undefined} value={fields.model} onChange={model=>patch({model:model||undefined})}/>}
    {fields.kind==='cloud-native-worker'&&<p className={`native-engine-check ${engineCheck.state}`} role="status">{engineCheck.message}</p>}
    {employee?.kind==='cloud-native-worker'&&<section className="native-session-bind"><strong>{uiText("Remote native session")}</strong>{(employee.threadId||employee.claudeSessionId)&&<p>{uiText("Linked")} {employee.engine==='codex'?'Codex':'Claude Agent'}  {uiText("Conversations")} <code>{employee.threadId??employee.claudeSessionId}</code>{employee.nativeOwnership==='external'?uiText(" · 外部会话，移除员工不会删除远端原件"):''}</p>}{canBindNativeSession(employee)&&<><p>{uiText("Start a new conversation, or bind an existing session on this cloud host in the same working directory.")}</p><button type="button" className="btn" disabled={nativeBusy||fields.engine!==employee.engine} onClick={async()=>{setNativeBusy(true);try{const result=await api.call<{sessions:{id:string;cwd:string;preview:string}[]}>('engine.remote-sessions',{team:fields.group,engine:employee.engine});setNativeSessions(result.sessions.filter(value=>value.cwd===employee.cwd&&value.id!==(employee.threadId??employee.claudeSessionId)));setError('')}catch(error){report(error)}finally{setNativeBusy(false)}}}>{nativeBusy?uiText("Reading sessions…"):uiText("Read existing sessions")}</button>{!!nativeSessions.length&&<><AppSelect name="nativeSession" value={nativeId} onChange={e=>setNativeId(e.target.value)}><option value="" disabled>{uiText("Choose a session in the same directory")}</option>{nativeSessions.map(value=><option key={value.id} value={value.id}>{value.preview||value.id}</option>)}</AppSelect><button type="button" className="btn" disabled={!nativeId||nativeBusy} onClick={async()=>{setNativeBusy(true);try{const result=await api.call<{card:StoredSession}>('card.native-bind',{id:employee.id,sessionId:nativeId});await onBound?.(result.card);setError('')}catch(error){report(error)}finally{setNativeBusy(false)}}}>{uiText("Bind selected session")}</button></>}{!nativeBusy&&nativeSessions.length===0&&<small>{uiText("Only sessions in the current working directory are shown.")}</small>}</>}</section>}
    <div className="workspace-contract"><span>{cloud?uiText("Cloud host"):work?'WORK':'BUILD'}  {uiText("· TEAM root directory")}</span><code>{workspaceRoot||uiText("Choose a Team first")}</code>{cloud&&<small className="cloud-inheritance">{uiText("Host:")}{settings[fields.group]?.remote?.host}  {uiText("· Inherited from the Team; no separate connection configuration needed")}</small>}
      {employee?<label>{uiText("Fixed working directory")}<code className="default-employee-path">{employee.cwd}</code><small>{uiText("Team and working folder are fixed after creation. Renaming the employee does not rename the folder.")}</small></label>:<><div className="directory-mode-options" role="group" aria-label={uiText("Employee directory mode")}>{(['default','bind'] as const).map(mode=><button type="button" key={mode} data-directory-mode={mode} aria-pressed={directoryMode===mode} className={directoryMode===mode?'selected':''} onClick={()=>{setDirectoryMode(mode);setPickerOpen(mode==='bind'&&(cloud||work));if(mode==='bind'){patch({cwd:''});if(!cloud&&!work)void choose()}setError('')}}>{mode==='default'?uiText("Create automatically"):uiText("Bind an existing folder")}</button>)}</div>
      {directoryMode==='default'?<label>{uiText("Default working directory")}<code className="default-employee-path" data-default-cwd>{`${workspaceRoot}/${fields.title.trim()||'填写员工名字后自动生成'}`}</code><small>{uiText("Creates a folder with the employee’s name on save, preserving Chinese characters, spaces and case.")}</small></label>:<><label>{cloud?uiText("Bind cloud folder"):uiText("Bind Core-host folder")}<div className="folder-input"><input name="cwd" required readOnly value={fields.cwd??''} placeholder={uiText("Use the button on the right to choose an existing folder")}/><button type="button" onClick={()=>cloud||work?setPickerOpen(true):void choose()}>{cloud||work?uiText("Browse folders"):uiText("Choose working directory")}</button></div></label>{pickerOpen&&fields.group&&roots[fields.group]&&<EmployeeFolderPicker team={fields.group} cloud={cloud} windows={cloud&&settings[fields.group]?.remote?.os==='windows'} selected={fields.cwd??''} onSelect={cwd=>{patch({cwd});setError('')}} onClose={()=>setPickerOpen(false)}/>}</>}
      <small>{cloud?uiText("The directory must be inside the cloud Team root; nested folders are supported. Saving creates or checks it over SSH."):work?uiText("Scope: a subfolder of the plugin workspace above, including nested folders. Root folders, parents and external links cannot be bound."):uiText("Created under the Team project directory by default; an existing Core-host working folder can also be bound.")}</small></>}</div>
    {error&&<p className="employee-form-error" role="alert">{error}</p>}
    <div className="form-footer"><button className="btn primary save-employee" disabled={saving || (!employee&&!!engineWorkspaceError(fields.engine)) || !groups.includes(fields.group) || (localWorkspace&&!workspaceRoot) || (binding&&!folder.trim()) || (!employee&&directoryMode==='bind'&&!fields.cwd?.trim()) || (fields.kind==='cloud-native-worker'&&engineCheck.state!=='ready')}>{saving ? uiText("Saving…") : employee ? uiText("Save changes") : uiText("Welcome to the team")} <span>↗</span></button></div>
  </form>
}

export function TeamForm({ name, index, layout, root = '', settings={mode:'build'}, template, plugins=[], employeeCount=0, onSave, onRemove }: {
  name?: string; index: number; layout?: RoomLayout; root?: string;settings?:TeamSettings;template?:{settings:TeamSettings;design?:Partial<RoomDesign>;bounds?:RoomBounds};plugins?:PluginDescriptor[];employeeCount?:number;
  onSave: (name: string, root: string, design: RoomDesign, bounds: RoomBounds,settings:TeamSettings) => Promise<boolean>; onRemove?: () => Promise<void>
}) {
  useI18n()

  const [title, setTitle] = useState(name === '' ? '自由工位' : name ?? '')
  useEffect(()=>setTitle(name === '' ? '自由工位' : name ?? ''),[name])
  const [design, setDesign] = useState(roomDesign(index, layout?.design??template?.design))
  const [bounds, setBounds] = useState(()=>({...initialBounds(index,layout),...(name===undefined&&template?.bounds?{width:template.bounds.width,height:template.bounds.height,shape:template.bounds.shape,arrangement:template.bounds.arrangement,points:template.bounds.points}:{})}))
  const [folder,setFolder]=useState(root)
  const [config,setConfig]=useState<TeamSettings>(name===undefined?template?.settings??settings:settings)
  const directoryMode=config.directoryMode??'default'
  const [suggested,setSuggested]=useState(''),[deleting,setDeleting]=useState(false)
  const [saving, setSaving] = useState(false)
  const [removing, setRemoving] = useState(false)
  const [folderError,setFolderError]=useState('')
  useEffect(()=>{let active=true;setFolderError('');if(name!==undefined){setFolder(root);return}if(config.mode==='cloud'){setFolder(config.directory??config.remote?.directory??'');return}void api.call<{path:string}>('workspace.suggest',{team:title||'未命名项目',...config}).then(result=>{if(active){setSuggested(result.path);if(config.mode==='work')setFolder(result.path);else if(directoryMode==='default')setFolder(result.path)}}).catch(error=>{if(active){setFolder('');setFolderError((error as Error).message)}});return()=>{active=false}},[title,config.mode,config.pluginId,config.directory,config.remote?.directory,directoryMode,root,name])
  return <form className="team-form" onSubmit={async (e) => { e.preventDefault(); setSaving(true); try { await onSave(name === '' ? '' : title, folder.trim(), design, bounds,{...config,directoryMode}) } catch(error){setFolderError((error as Error).message)} finally { setSaving(false) } }}>
    <div className={`sign-preview theme-${design.theme}`}><i /><span>{title || uiText("New team")}<small>{design.subtitle}</small></span><b>01</b></div>
    <label>{uiText("Team name")}<input name="team-name" required readOnly={name===''} value={title} onChange={(e) => setTitle(e.target.value)} placeholder={uiText("e.g. Engineering")} /><small className="name-lock-note">{name===undefined?uiText("The default folder uses the Team name at creation."):uiText("Renaming changes only the Team name. Existing folders and employee working directories stay unchanged.")}</small></label>
    <div className="field-heading team-section-heading">{uiText("Work mode")} <span>{name===undefined?uiText("Employees inherit the Team’s execution environment"):uiText("Fixed at creation")}</span></div>
    {name===undefined?<>
    <div className="team-mode-options" role="group" aria-label={uiText("Team type")}>{(['work','build'] as const).map(mode=><button type="button" key={mode} data-mode={mode} aria-pressed={mode==='work'?config.mode==='work':config.mode!=='work'} className={(mode==='work'?config.mode==='work':config.mode!=='work')?'selected':''} onClick={()=>setConfig(mode==='work'?{mode,pluginId:config.pluginId??plugins[0]?.id,directoryMode:'default'}:config.mode==='cloud'?config:{mode:'build',directoryMode})}><strong>{mode==='work'?uiText("Work · Plugin"):uiText("Build · Project")}</strong><span>{mode==='work'?uiText("Work inside a plugin workspace"):uiText("Local or SSH cloud project")}</span></button>)}</div>
    {config.mode!=='work'&&<div className="directory-mode-options team-environment-options" role="group" aria-label={uiText("Build work environment")}><button type="button" data-environment="local" aria-pressed={config.mode==='build'} onClick={()=>setConfig({mode:'build',directoryMode})}><span>{uiText("Local")}</span><span className="environment-selection-mark" aria-hidden="true">{uiText("✓ Selected")}</span></button><button type="button" data-mode="cloud" aria-pressed={config.mode==='cloud'} onClick={()=>setConfig({mode:'cloud',hostId:config.hostId,directory:config.directory,remote:config.remote})}><span>{uiText("SSH cloud host")}</span><span className="environment-selection-mark" aria-hidden="true">{uiText("✓ Selected")}</span></button></div>}
    {config.mode==='cloud'&&<RemoteConnectionFields value={config} onChange={next=>{setConfig(next);setFolderError('')}}/>}
    {config.mode==='work'&&<label>{uiText("Work plugin")}<AppSelect name="team-plugin" required value={config.pluginId??''} onChange={e=>setConfig({mode:'work',pluginId:e.target.value,directoryMode:'default'})}><option value="" disabled>{uiText("Choose an integrated plugin")}</option>{plugins.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</AppSelect>{!plugins.length&&<small>{uiText("Install a plugin through the CLI first, or choose Build mode.")}</small>}</label>}
    {config.mode==='work'&&<label>{uiText("Fixed plugin working directory")}<input name="team-root" readOnly value={folder} /><small>{uiText("Automatically located inside the selected plugin’s workspaces folder. The Team directory cannot be changed manually; employees can create or bind subfolders within it.")}</small></label>}
    {config.mode==='build'&&<><div className="directory-mode-options" role="group" aria-label={uiText("Team directory mode")}>{(['default','bind'] as const).map(mode=><button type="button" key={mode} data-team-directory-mode={mode} aria-pressed={directoryMode===mode} className={directoryMode===mode?'selected':''} onClick={()=>{setConfig({...config,directoryMode:mode});setFolder(mode==='bind'?(name!==undefined?root:''):suggested);setFolderError('')}}>{mode==='default'?uiText("Create automatically"):uiText("Bind an existing folder")}</button>)}</div>
    <label>{directoryMode==='default'?uiText("Create working directory automatically"):uiText("Bind Core-host folder")}<div className="folder-input"><input name="team-root" required readOnly={directoryMode==='default'} value={folder} onChange={e=>{setFolder(e.target.value);setFolderError('')}} placeholder={uiText("Choose an existing physical folder")}/>{directoryMode==='bind'&&<button type="button" onClick={async()=>{try{const chosen=await api.call<{path:string|null}>('workspace.choose',{path:folder||suggested});if(chosen.path)setFolder(chosen.path);setFolderError('')}catch(e){setFolderError((e as Error).message)}}}>{uiText("Choose Team directory")}</button>}</div></label>
    </>}
    </>:<div className="workspace-contract"><span>{config.mode==='work'?uiText("Plugin"):config.mode==='cloud'?uiText("Cloud"):uiText("Local")}  {uiText("· Fixed Team directory")}</span><code>{root}</code><small>{uiText("Work mode and folder are fixed after creation; the Team name can be changed.")}</small></div>}
    {folderError&&<p className="employee-form-error" role="alert">{folderError}</p>}
    <p className="workspace-note">{config.mode==='cloud'?uiText("Cloud accounts are managed by the Cloud Hosts plugin. A Team binds only a host and directory; renaming the Team does not change the remote directory."):config.mode==='work'?uiText("The Team uses a fixed plugin workspace. Renaming does not move it. Employees may create or bind subfolders within this scope."):directoryMode==='bind'?uiText("Uses the existing folder without moving or clearing files. Renaming the Team does not affect the binding."):uiText("Creates a project folder with the initial Team name by default. Renaming the Team does not rename the folder.")}</p>
    <label>{uiText("Team motto")}<input name="subtitle" value={design.subtitle} onChange={(e) => setDesign({ ...design, subtitle: e.target.value })} /></label>
    <fieldset className="appearance-settings"><legend>{uiText("Team background and decoration")}</legend>
    <div className="form-section"><div className="field-heading">{uiText("Space palette")}</div><div className="theme-options">{ROOM_THEMES.map((theme, i) => <button type="button" key={theme} className={`theme-${theme} ${design.theme === theme ? 'selected' : ''}`} onClick={() => setDesign({ ...design, theme })}><i />{THEMES[i]}</button>)}</div></div>
    <div className="room-background-options"><label>{uiText("Background color")}<div className="room-color-picker"><input type="color" aria-label={uiText("Team background color")} value={design.background||'#e5edf5'} onChange={e=>setDesign({...design,background:e.target.value})}/><code>{design.background||uiText("Follow theme")}</code><button type="button" onClick={()=>setDesign({...design,background:''})}>{uiText("Follow theme")}</button></div></label><label>{uiText("Background texture")}<AppSelect name="pattern" value={design.pattern} onChange={e=>setDesign({...design,pattern:e.target.value as RoomDesign['pattern']})}><option value="boards">{uiText("Wood flooring")}</option><option value="grid">{uiText("Tile grid")}</option><option value="dots">{uiText("Dots")}</option><option value="plain">{uiText("Solid color")}</option></AppSelect></label></div>
    <label className="scenery-toggle"><input type="checkbox" name="scenery" checked={design.scenery} onChange={e=>setDesign({...design,scenery:e.target.checked})}/>{uiText("Show walls and decorations")}</label>
    <div className="form-row"><label>{uiText("Walls")}<AppSelect name="wall" value={design.wall} onChange={(e) => setDesign({ ...design, wall: e.target.value as RoomDesign['wall'] })}><option value="windows">{uiText("Floor-to-ceiling window · City sunset")}</option><option value="panels">{uiText("Wood panels · Warm tones")}</option><option value="brick">{uiText("Vintage brick · Studio")}</option></AppSelect></label><label>{uiText("Desks")}<AppSelect name="desk" value={design.desk} onChange={(e) => setDesign({ ...design, desk: e.target.value as RoomDesign['desk'] })}><option value="walnut">{uiText("Walnut")}</option><option value="oak">{uiText("Light oak")}</option><option value="cloud">{uiText("Cloud white")}</option></AppSelect></label></div>
    <div className="form-section"><div className="field-heading">{uiText("Individual decorations")}</div><div className="decoration-options">{([['plants','绿植'],['shelf','书架'],['lamp','吊灯'],['art','海报']] as const).map(([key, label]) => <label key={key}><input type="checkbox" name={key} checked={design[key]} onChange={(e) => setDesign({ ...design, [key]: e.target.checked })} /><span>{label}</span></label>)}</div></div>
    </fieldset>
    <div className="form-row"><label>{uiText("Outline shape")}<AppSelect name="shape" value={bounds.shape} onChange={e=>setBounds({...bounds,shape:e.target.value as RoomBounds['shape']})}><option value="rounded">{uiText("Rounded rectangle")}</option><option value="ellipse">{uiText("Oval island")}</option><option value="hexagon">{uiText("Hexagon")}</option><option value="custom">{uiText("Custom polygon")}</option></AppSelect></label><label>{uiText("Employee layout")}<AppSelect name="arrangement" value={bounds.arrangement} onChange={e=>setBounds({...bounds,arrangement:e.target.value as RoomBounds['arrangement']})}><option value="grid">{uiText("Automatic rows")}</option><option value="circle">{uiText("Around the table")}</option><option value="free">{uiText("Free placement")}</option></AppSelect></label></div>
    {bounds.shape==='custom' && <PolygonEditor points={bounds.points??DEFAULT_POLYGON} onChange={points=>setBounds({...bounds,points})} />}
    <div className="form-row position-row">{(['width','height'] as const).map(key=><label key={key}>{key==='width'?uiText("Space width"):uiText("Space height")}<input type="number" name={key} min={key==='width'?360:MIN_ROOM_HEIGHT} step="any" value={bounds[key]} onChange={e=>setBounds({...bounds,[key]:+e.target.value})} /></label>)}</div>
    <small className="workspace-note">{uiText("Employees keep their original size, and moving them does not change the Team border. Drag any edge to resize; drag the team sign to move the Team.")}</small>
    {removing&&<p className="workspace-note">{uiText("This will remove the Team, its")} {employeeCount}  {uiText("employees and all their local and native Codex / Claude Agent conversations. Working folders and files will be kept.")}</p>}
    <div className="form-footer">{onRemove && <button type="button" className="text-danger" disabled={deleting||saving} onClick={async () => { if (!removing) { setRemoving(true); return } setDeleting(true);try{await onRemove()}finally{setDeleting(false)} }}>{deleting?uiText("Cleaning up conversations…"):removing ? uiText("Confirm removal of Team and all conversations") : uiText("Remove Team")}</button>}<button className="btn primary save-team" disabled={saving||deleting||!folder||!!folderError||(config.mode==='cloud'&&!config.hostId)}>{saving ? uiText("Saving…") : name === undefined ? uiText("Create Team") : uiText("Save workspace")} <span>↗</span></button></div>
  </form>
}
