// Real UI + temporary authenticated Core. Publications and media are local deterministic fixtures.
import fs from 'node:fs'
import path from 'node:path'
import net from 'node:net'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {x as untar} from 'tar'
import {chromium,_electron as electron,expect} from '@playwright/test'
import {fixtureCore} from './fixtures/headless-core.mjs'
const native=process.argv.includes('--desktop'),require=createRequire(import.meta.url),probe=net.createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve))
const f=await fixtureCore(native?{}:{AGENTS_COMPANY_WEB:'1',AGENTS_COMPANY_WEB_PORT:String(port)}),out=path.join(f.root,'artifacts/channels-ui'),mode=native?'desktop':'web';fs.mkdirSync(out,{recursive:true});let browser,app,page
try{
 if(native){await f.stop();const env={...f.env,AGENTS_COMPANY_HIDDEN:'1',AGENTS_COMPANY_WIDTH:'1440',AGENTS_COMPANY_HEIGHT:'1000'};delete env.ELECTRON_RUN_AS_NODE;app=await electron.launch({executablePath:process.env.AGENTS_COMPANY_TEST_APP||require('electron'),args:process.env.AGENTS_COMPANY_TEST_APP?[]:[f.root],env});page=await app.firstWindow()}
 else{browser=await chromium.launch({headless:true,...(process.platform==='darwin'?{channel:'chrome'}:{})});page=await browser.newPage({viewport:{width:1440,height:1000}});await page.goto('http://127.0.0.1:'+port);await page.locator('.web-login input').fill(fs.readFileSync(path.join(f.env.AGENTS_COMPANY_HOME,'control.token'),'utf8').trim());await page.getByRole('button',{name:'Enter workspace',exact:true}).click()}
 page.setDefaultTimeout(15000);const errors=[],fontRequests=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.resourceType()==='font')fontRequests.push(request.url())});await expect(page.locator('.infinite-canvas')).toBeVisible()
 const call=(cmd,args={})=>page.evaluate(([cmd,args])=>window.agents.call(cmd,args),[cmd,args]),rpc=async(cmd,args={})=>{const result=await f.request(null,cmd,args);assert.ok(result.ok,result.error);return result.data}
 const pick=async(scope,label,option)=>{await scope.getByRole('button',{name:label,exact:true}).click();await page.getByRole('listbox',{name:label,exact:true}).getByRole('option',{name:option,exact:true}).click()}
 await call('settings.set',{language:'en',theme:'violet'});await f.cli('group','add','Newsroom');const employee=await f.create('Aster','Newsroom'),group=await call('chat.create',{name:'Planning circle',members:[employee.id]})
 const sources={};for(const [plugin,locator,name] of [['telegram','local_news_fixture','Field notes'],['x','localresearch','Research writer'],['youtube','https://www.youtube.com/@LocalVideoFixture','Video desk']])sources[plugin]=await call('channel.source-add',{plugin,locator,name})
 let destination;const publishedAt=Date.now()-60000,bytes=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=360;const x=c.getContext('2d');x.fillStyle='#d9c9ef';x.fillRect(0,0,640,360);x.fillStyle='#6c51a6';x.fillRect(44,42,92,4);x.font='bold 36px sans-serif';x.fillText('A small field guide',44,105);x.font='20px sans-serif';x.fillText('Clear ideas. Original context.',44,145);x.fillStyle='#f8f6fb';x.fillRect(44,188,552,126);x.fillStyle='#89a88d';x.fillRect(70,250,60,40);x.fillRect(151,225,60,65);x.fillRect(232,207,60,83);x.fillStyle='#9f85cb';x.fillRect(345,217,225,9);x.fillRect(345,246,180,9);x.fillRect(345,275,202,9);return c.toDataURL('image/png').split(',')[1]}),'base64')
 const posts={};for(const [plugin,source] of Object.entries(sources)){const externalId='ui-'+plugin,asset=await call('channel.media-put',{sourceId:source.id,externalId,publishedAt,mediaKey:'photo',name:'Reading palette.png',mimeType:'image/png',data:bytes.toString('base64')}),result=await call('channel.publish',{sourceId:source.id,externalId,publishedAt,title:plugin==='x'?'The useful details deserve to stay':plugin==='telegram'?'A quieter way to follow the news':'Three ideas from the studio',body:'A complete article, collected into one place.\n\n**Keep the original context.** Save useful details, organize the authors you follow, and return when you have time.\n\n- Read with fewer interruptions\n- Keep images with the story\n- Bring related conversations together'+(plugin==='x'?'\n\nInline $E=mc^2$ stays with the original article.\n\n$$\n\\int_0^1 x^2\\,dx = \\frac{1}{3}\n$$':''),authorName:source.name,url:'https://example.invalid/'+plugin,mediaIds:[asset.media.id]});posts[plugin]={...result,asset:asset.media,source}}
 const imageOnlyArgs={sourceId:sources.telegram.id,externalId:'ui-image-only',publishedAt:publishedAt+1},imageOnlyMedia=await call('channel.media-put',{...imageOnlyArgs,mediaKey:'photo',name:'Image without caption.png',mimeType:'image/png',data:bytes.toString('base64')}),imageOnly=await call('channel.publish',{...imageOnlyArgs,title:'',body:'',mediaIds:[imageOnlyMedia.media.id]}),titleOnly=await call('channel.publish',{sourceId:sources.youtube.id,externalId:'ui-title-only',publishedAt:publishedAt+1,title:'A video without a description',body:'',url:'https://example.invalid/title-only'})
 await call('channel.save',{id:posts.telegram.id,saved:true})
 await page.getByRole('button',{name:'Messages',exact:true}).click();const tabs=page.locator('.message-category-tabs [role=tab]'),row=id=>page.locator('.channel-news-card[data-news-id="'+id+'"]'),open=async id=>{await page.locator('.message-contact[data-channel="'+id+'"]').click()}
 await expect(tabs).toHaveCount(1);await expect(tabs.first()).toHaveText('All');await expect(page.getByRole('button',{name:'Message Aster',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Open group Planning circle',exact:true})).toBeVisible();for(const source of Object.values(sources))await expect(page.locator('.message-contact[data-channel="'+source.channelId+'"]').first()).toBeVisible()
 await open(sources.telegram.channelId);await expect(row(imageOnly.id)).toBeVisible();await row(imageOnly.id).locator('.channel-news-images').scrollIntoViewIfNeeded();await expect(row(imageOnly.id).locator('.channel-news-images img')).toBeVisible();await expect(row(imageOnly.id).locator('.channel-news-body')).toHaveCount(0);await open(sources.youtube.channelId);await expect(row(titleOnly.id)).toContainText('A video without a description');await expect(row(titleOnly.id).locator('.channel-news-body')).toHaveCount(0);
 await open(sources.x.channelId);await expect(row(posts.x.id)).toBeVisible();await row(posts.x.id).locator('.channel-news-images').scrollIntoViewIfNeeded();await expect(row(posts.x.id).locator('.channel-news-images img')).toBeVisible();await expect(row(posts.x.id).locator('.katex')).toHaveCount(2);const mathFonts=await page.evaluate(async()=>{await document.fonts.ready;await document.fonts.load('16px KaTeX_Main');return {checked:document.fonts.check('16px KaTeX_Main'),loaded:[...document.fonts].some(font=>font.family.replace(/["']/g,'')==='KaTeX_Main'&&font.status==='loaded')}});assert.deepEqual(mathFonts,{checked:true,loaded:true});await row(posts.x.id).getByRole('button',{name:'Save article',exact:true}).click();await expect(row(posts.x.id).getByRole('button',{name:'Saved',exact:true})).toHaveAttribute('aria-pressed','true');assert.equal((await call('channel.post',{id:posts.x.id})).saved,true)
 await row(posts.x.id).getByRole('button',{name:'Preview Reading palette.png',exact:true}).click();const viewer=page.locator('.message-image-dialog');await expect(viewer).toBeVisible();await expect(viewer.locator('img').first()).toBeVisible()
 if(!native){const pending=page.waitForEvent('download');await viewer.getByRole('link',{name:'Download image',exact:true}).click();const download=await pending;assert.equal(download.suggestedFilename(),'Reading palette.png');assert.deepEqual(fs.readFileSync(await download.path()),bytes)}
 await page.keyboard.press('Escape');await expect(viewer).toHaveCount(0)
 let archive;if(native){archive=path.join(f.temp,'article.tar.gz');await app.evaluate(({dialog},target)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:target})},archive);await row(posts.x.id).getByRole('button',{name:'Download article and images',exact:true}).click();await expect.poll(()=>fs.existsSync(archive)).toBe(true)}else{const pending=page.waitForEvent('download');await row(posts.x.id).getByRole('button',{name:'Download article and images',exact:true}).click();const download=await pending;assert.match(download.suggestedFilename(),/\.tar\.gz$/);archive=await download.path()}
 const extracted=path.join(f.temp,'ui-export');fs.mkdirSync(extracted);await untar({file:archive,cwd:extracted});assert.match(fs.readFileSync(path.join(extracted,'story.md'),'utf8'),/original context/);assert.deepEqual(fs.readFileSync(path.join(extracted,'images','01-Reading palette.png')),bytes)
 await page.getByRole('button',{name:'Saved messages',exact:true}).click();const library=page.locator('.message-library');await expect(library).toBeVisible();await expect(library.locator('[data-news-id="'+posts.x.id+'"]')).toBeVisible();await page.getByRole('button',{name:'Close message library',exact:true}).click()
 await page.locator('#message-folder-add').click();const folder=page.locator('.conversation-folder-editor');await folder.locator('input[name=conversation-folder-name]').fill('Reading and planning');for(const title of ['Aster','Planning circle','Field notes','X'])await folder.getByRole('checkbox',{name:'Include '+title,exact:true}).check();await folder.getByRole('button',{name:'Create category',exact:true}).click();await expect(folder).toHaveCount(0);await expect(tabs).toHaveCount(2);assert.deepEqual((await call('messenger.state')).folders[0].conversations.sort(),['employee:'+employee.id,'group:'+group.id,'channel:'+sources.telegram.channelId,'channel:'+sources.x.channelId].sort());await expect(page.locator('.message-contact[data-channel="'+sources.youtube.channelId+'"]').first()).toHaveCount(0)
 await page.locator('#message-folder-all').click();await open(sources.x.channelId);await page.screenshot({animations:'disabled',path:path.join(out,mode+'-news-en.png')})
 const actionOverlap=await row(posts.x.id).evaluate(card=>{const bar=card.querySelector('.message-actions').getBoundingClientRect();return [...card.querySelectorAll(':scope > header,:scope > h2,:scope > .channel-news-body,:scope > footer')].filter(node=>{const text=node.getBoundingClientRect();return Math.min(bar.right,text.right)-Math.max(bar.left,text.left)>1&&Math.min(bar.bottom,text.bottom)-Math.max(bar.top,text.top)>1}).map(node=>node.className||node.tagName)});assert.deepEqual(actionOverlap,[],'actual App article toolbar must not cover publisher, headline, body or footer');
 await row(posts.x.id).getByRole('button',{name:'Manage author Research writer',exact:true}).click();const management=page.locator('.channel-sources-dialog'),sourceEditor=management.locator('.channel-source-editor');await expect(sourceEditor).toBeVisible()
 await management.getByRole('button',{name:'New channel',exact:true}).click();await management.getByLabel('Channel name',{exact:true}).fill('Reading room');await management.getByRole('button',{name:'Create channel',exact:true}).click();await expect(management.locator('.channel-create-form')).toHaveCount(0);destination=(await call('channel.list')).find(channel=>channel.name==='Reading room');assert.ok(destination)
 await pick(sourceEditor,'Move author to channel','Reading room');await sourceEditor.getByRole('button',{name:'Move author',exact:true}).click();await expect.poll(async()=>(await call('channel.post',{id:posts.x.id})).channelId).toBe(destination.id);assert.equal((await call('channel.post',{id:posts.x.id})).saved,true)
 await management.getByRole('button',{name:'Close channel management',exact:true}).click();await expect(management).toHaveCount(0);await open(destination.id);await expect(row(posts.x.id)).toBeVisible()
 await page.getByRole('button',{name:'Manage channels and authors',exact:true}).click()
 for(const [plugin,locator] of [['x','@addednews'],['youtube','https://www.youtube.com/@AddedVideoFixture']]){await management.getByRole('button',{name:'Follow an author',exact:true}).click();const form=management.locator('.channel-add-form');await pick(form,'Platform',plugin==='x'?'X':'YouTube');const invalid=plugin==='x'?'https://x.com/localresearch/status/123':'https://www.youtube.com/watch?v=fixture',revision=(await call('channel.collector-config')).revision;await form.getByLabel('Author URL or handle',{exact:true}).fill(invalid);await form.getByRole('button',{name:'Follow author',exact:true}).click();await expect(management.getByRole('alert')).toContainText('author handle');await expect(form.getByLabel('Author URL or handle',{exact:true})).toHaveValue(invalid);assert.equal((await call('channel.collector-config')).revision,revision,'invalid single-post URLs never enter authoritative configuration');await form.getByLabel('Author URL or handle',{exact:true}).fill(locator);await pick(form,'Channel','Default '+(plugin==='x'?'X':'YouTube')+' channel');await form.getByRole('button',{name:'Follow author',exact:true}).click();await expect(form).toHaveCount(0);const added=(await call('channel.sources')).find(source=>source.locator===locator);assert.ok(added);assert.equal(added.channelId,sources[plugin].channelId)}
 await management.getByRole('button',{name:'Manage author Research writer',exact:true}).click();await sourceEditor.getByRole('button',{name:'Unfollow Research writer',exact:true}).click();await expect(sourceEditor.getByRole('button',{name:'Follow Research writer',exact:true})).toBeEnabled();assert.equal((await call('channel.sources',{includeDisabled:true})).find(source=>source.id===sources.x.id).enabled,false);assert.equal((await call('channel.post',{id:posts.x.id})).saved,true);await management.getByRole('button',{name:'Close channel management',exact:true}).click()
 await page.getByRole('button',{name:'Saved messages',exact:true}).click();await expect(library.locator('[data-news-id="'+posts.x.id+'"]')).toBeVisible();await library.locator('[data-news-id="'+posts.x.id+'"]').getByRole('button',{name:'Go to channel',exact:true}).click();await expect(library).toHaveCount(0);await expect(page.locator('.channel-conversation .message-person')).toContainText('Reading room');await expect(row(posts.x.id)).toBeVisible()
 if(!native){
  await page.getByRole('button',{name:'Saved messages',exact:true}).click();const stale=library.locator('[data-news-id="'+posts.x.id+'"]');await expect(stale).toBeVisible();let releaseSearch;const searchGate=new Promise(resolve=>releaseSearch=resolve)
  await page.route('**/api/rpc',async route=>{if(route.request().postDataJSON().cmd==='messenger.search')await searchGate;await route.continue()})
  try{await rpc('channel.source-update',{id:sources.x.id,patch:{channelId:sources.telegram.channelId}});await stale.getByRole('button',{name:'Go to channel',exact:true}).click();await expect(library).toHaveCount(0);await expect(page.locator('.channel-conversation .message-person')).toContainText('Field notes');await expect(row(posts.x.id)).toBeVisible()}finally{releaseSearch();await page.unroute('**/api/rpc')}
  await rpc('channel.source-update',{id:sources.x.id,patch:{channelId:destination.id}})
 }
 if(!native){
  const desk=await rpc('channel.create',{name:'Pagination desk'}),source=await rpc('channel.source-add',{plugin:'x',locator:'pagefixture',channelId:desk.id}),journal=[],base=Date.now()-600000
  for(let i=0;i<60;i++)journal.push(await rpc('channel.publish',{sourceId:source.id,externalId:'journal-'+i,publishedAt:base-i*1000,title:'Journal note '+String(i+1).padStart(2,'0'),body:'A deterministic local article for continuous reading.'}))
  await open(desk.id);const cards=page.locator('.channel-conversation [data-news-id]');await expect(cards).toHaveCount(24);await page.getByRole('button',{name:'Load earlier articles',exact:true}).click();await expect(cards).toHaveCount(48);const loaded=await cards.evaluateAll(elements=>elements.map(element=>element.getAttribute('data-news-id')))
  const arrived=await rpc('channel.publish',{sourceId:source.id,externalId:'arrived-during-reading',publishedAt:Date.now()-1000,title:'One new article arrives',body:'The articles already loaded must remain available.'});await expect(row(arrived.id)).toBeVisible();await expect.poll(async()=>{const ids=await cards.evaluateAll(elements=>elements.map(element=>element.getAttribute('data-news-id')));return loaded.every(id=>ids.includes(id))&&new Set(ids).size===ids.length}).toBe(true)
  for(const post of journal.slice(0,45))await rpc('channel.save',{id:post.id,saved:true});await page.getByRole('button',{name:'Saved messages',exact:true}).click();const savedCards=library.locator('[data-news-id]');await expect(savedCards).toHaveCount(40);await library.getByRole('button',{name:'Load more messages',exact:true}).click();await expect(savedCards).toHaveCount(47);const retained=await savedCards.evaluateAll(elements=>elements.map(element=>element.getAttribute('data-news-id')))
  await rpc('channel.save',{id:journal[59].id,saved:true});await expect(library.locator('[data-news-id="'+journal[59].id+'"]')).toBeVisible();await expect.poll(async()=>{const ids=await savedCards.evaluateAll(elements=>elements.map(element=>element.getAttribute('data-news-id')));return retained.every(id=>ids.includes(id))&&ids.length===48}).toBe(true);await page.getByRole('button',{name:'Close message library',exact:true}).click()
 }
 await open(sources.youtube.channelId);await row(posts.youtube.id).getByRole('button',{name:'Article actions',exact:true}).click();await page.getByRole('menuitem',{name:'Delete article',exact:true}).click();await expect(row(posts.youtube.id)).toHaveCount(0);assert.equal((await rpc('channel.posts',{sourceId:sources.youtube.id})).total,1);assert.equal((await f.request(null,'channel.post',{id:posts.youtube.id})).ok,false)
 const category=tabs.filter({hasText:'Reading and planning'});await category.click();await category.click();await page.getByRole('menuitem',{name:'Delete category',exact:true}).click();await expect(tabs).toHaveCount(1);assert.equal((await call('chat.get',{id:group.id})).name,'Planning circle');assert.equal((await call('channel.post',{id:posts.x.id})).saved,true)
 await open(destination.id)
 await call('settings.set',{language:'zh-CN',theme:'blue'});await expect(tabs.first()).toHaveText('全部');await expect(row(posts.x.id)).toBeVisible()
 if(native)await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(720,900));else await page.setViewportSize({width:390,height:844})
 const width=await page.evaluate(()=>innerWidth),bounds=await row(posts.x.id).boundingBox();assert.ok(bounds&&bounds.x>=0&&bounds.x+bounds.width<=width+1);assert.equal(await row(posts.x.id).evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);await page.screenshot({animations:'disabled',path:path.join(out,mode+'-news-zh-compact.png')})
 await page.getByRole('button',{name:'管理频道与博主',exact:true}).click();await expect(management).toContainText('频道与博主');await expect(management).not.toContainText('Not following');await management.getByRole('button',{name:'关注博主',exact:true}).click();await expect(management.getByLabel('博主链接或用户名',{exact:true})).toBeVisible();const dialogBounds=await management.boundingBox();assert.ok(dialogBounds&&dialogBounds.x>=0&&dialogBounds.x+dialogBounds.width<=width+1);assert.equal(await management.evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);await page.screenshot({animations:'disabled',path:path.join(out,mode+'-authors-zh-compact.png')});await page.getByRole('button',{name:'关闭频道管理',exact:true}).click();await expect(management).toHaveCount(0)
 assert.deepEqual(errors,[]);assert.ok(fontRequests.every(url=>url.startsWith('file:')||url.startsWith('data:')||new URL(url).origin===new URL(page.url()).origin),'math fonts use only bundled/local assets');assert.deepEqual(await call('terminal.list'),[]);assert.deepEqual((await call('session.transcript',{employee:employee.id})).items,[],'channel reading and organization never dispatch employee work');if(native)assert.ok(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(win=>!win.isVisible())))
 fs.writeFileSync(path.join(out,mode+'-verification.json'),JSON.stringify({passed:true,application:native?(process.env.AGENTS_COMPANY_TEST_APP??'source Electron'):'Web',platform:native?'hidden Electron on macOS':'headless Chromium on macOS',checks:['mixed same-list conversations','only All fixed category','image-only and title-only publications without invented body text','inline and display math with loaded local KaTeX_Main font','saved local news and global saved library','original image preview/download','self-contained article/image export','mixed category create/delete preserves conversations','author click routes saved articles and unfollows without deletion','follow new X/YouTube into default aggregate channels with retained invalid-URL draft and unchanged config','article deletion',...(!native?['stale saved item resolves current source route, including Telegram destination','new publications retain all 48 previously loaded feed articles','saved events retain and refresh all previously loaded library pages']:[]),'bilingual wide/narrow bounds','no native tasks or external source calls']},null,2));console.log('PASS channels '+mode+': same-list news, mixed folders, retained local media, saved library, downloads, and bilingual layout')
}catch(error){await page?.screenshot({animations:'disabled',path:path.join(out,mode+'-failure.png')}).catch(()=>{});throw error}finally{await app?.close();await browser?.close();await f.close()}
