import {createReady,readyEmployee,acceptedMessage} from './fixtures/ui-contracts.mjs'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {_electron as electron,expect} from '@playwright/test'
const root=path.resolve(import.meta.dirname,'..'),require=createRequire(import.meta.url),temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'ac-messenger-parity-'))),control=path.join(temp,'fixture'),out=path.join(root,'artifacts/message-parity')
fs.mkdirSync(control);fs.writeFileSync(path.join(control,'release-all'),'');fs.mkdirSync(out,{recursive:true})
const env={...process.env,AGENTS_COMPANY_HOME:path.join(temp,'state'),AGENTS_COMPANY_PROJECTS:path.join(temp,'projects'),AGENTS_COMPANY_WORKSPACES:path.join(temp,'work'),AGENTS_COMPANY_HIDDEN:'1',AGENTS_COMPANY_WIDTH:'1440',AGENTS_COMPANY_HEIGHT:'1000',CODEX_BIN:path.join(root,'test/fixtures/initialization-codex.cjs'),CODEX_HOME:path.join(temp,'codex'),AC_INIT_FIXTURE:control}
for(const key of Object.keys(env))if(key.startsWith('AGENTS_COMPANY_TOKEN')||['ELECTRON_RUN_AS_NODE','AGENTS_COMPANY_EMPLOYEE','AGENTS_COMPANY_SOCKET','AGENTS_COMPANY_PORT','AGENTS_COMPANY_URL','AGENTS_COMPANY_CLIENT','AGENTS_COMPANY_WEB_URL'].includes(key))delete env[key]
const app=await electron.launch({executablePath:process.env.AGENTS_COMPANY_TEST_APP||require('electron'),args:process.env.AGENTS_COMPANY_TEST_APP?[]:[root],env}),page=await app.firstWindow(),errors=[]
page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message))
const call=(cmd,args={})=>page.evaluate(([cmd,args])=>window.agents.call(cmd,args),[cmd,args]),state=()=>call('messenger.state')
const listScope=async name=>{await page.getByRole('button',{name:'Conversation list options',exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click()}
const action=async(name,item)=>{const menu=page.getByRole('button',{name:'Actions for '+name,exact:true});await menu.locator('..').hover();await menu.click();await page.getByRole('menuitem',{name:item,exact:true}).click()}
try{
 await page.locator('.infinite-canvas').waitFor();await call('settings.set',{theme:'white'});await call('group.add',{name:'Product Studio'});await call('group.add',{name:'Engineering'})
 const people=[];for(const [title,group,avatar] of [['Aster','Product Studio','fate-saber-chibi'],['Rowan','Engineering','byte'],['Nova','Product Studio','fate-gilgamesh-chibi'],['Mira','Engineering','marmalade']])people.push(await createReady(call,{title,group,avatar,engine:'codex',model:'gpt-6-luna'}))
 const [a,b]=people,ref='employee:'+a.id
 fs.writeFileSync(path.join(control,a.id+'.reply.txt'),'The design review is ready.\n\n**Thoughtful details make the difference.**\n\nI brought the notes together so we can decide what matters next.\n\n- Clear priorities for the next release\n- A lighter, more focused workspace\n- Small moments that make collaboration easier\n\nReference: https://example.org/design\n\nLet’s start with the conversation experience.')
 await call('session.send',{employee:a.id,text:'Let’s make this a space we love working in.'});await expect.poll(async()=>(await call('session.status',{employee:a.id}))[0].busy).toBe(false)
 const before=(await call('session.transcript',{id:a.id})).items
 const group=await call('chat.create',{name:'Design circle',members:people.map(person=>person.id)})
 await call('chat.update',{id:group.id,members:[]});
 for(let i=0;i<105;i++)await call('chat.post',{kind:'message',id:group.id,text:i===0?'ORIGINAL_BRIEF: Start with the user’s needs.':`Design note ${i}: a detail worth discussing.`,clientMessageId:'design-'+i})
 await call('chat.update',{id:group.id,members:people.map(person=>person.id)});
 await page.getByRole('button',{name:'Messages',exact:true}).click();await expect(page.locator('.message-contact')).toHaveCount(5)
 await action('Aster','Pin conversation');await expect(page.locator('.message-contact').first()).toHaveAttribute('data-employee',a.id)
 await action('Aster','Add to favorites');await listScope('Favorites');await expect(page.locator('.message-contact')).toHaveCount(1)
 await listScope('Back to inbox');await action('Rowan','Archive conversation');await expect(page.getByRole('button',{name:'Message Rowan',exact:true})).toHaveCount(0)
 await listScope('Archived');await expect(page.locator('.message-contact')).toHaveCount(1);await action('Rowan','Move to inbox');await expect(page.locator('.message-archive-entry,.message-archive-heading')).toHaveCount(0);await expect(page.locator('.message-contact')).toHaveCount(5)
 await page.getByRole('button',{name:'Select conversations',exact:true}).click();await page.getByRole('button',{name:'Message Rowan',exact:true}).click();await page.getByRole('button',{name:'Message Nova',exact:true}).click();await expect(page.locator('.message-bulk-actions')).toContainText('2 selected');await page.getByRole('button',{name:'Pin selected conversations'}).click();await expect.poll(async()=>Object.values((await state()).conversations).filter(value=>value.pinned).length).toBe(3)
 await page.getByRole('button',{name:'Message Aster',exact:true}).click();const composer=page.locator('.composer textarea'),assistant=page.locator('.turn.assistant').last();await expect(assistant).toContainText('Thoughtful details')
 await assistant.hover();await assistant.getByRole('button',{name:'Save message',exact:true}).click();await expect(assistant.getByRole('button',{name:'Unsave message'})).toHaveAttribute('aria-pressed','true')
 await assistant.getByRole('button',{name:'More message actions'}).click();await page.getByRole('menuitemradio',{name:'React ❤️',exact:true}).click();await expect(assistant.locator('.message-reaction')).toContainText('❤️')
 await assistant.hover();await assistant.getByRole('button',{name:'More message actions'}).click();await page.getByRole('menuitem',{name:'Pin message',exact:true}).click();await expect(assistant.locator('.message-annotations')).toContainText('Pinned');await expect(page.locator('.message-pin-strip')).toContainText('Thoughtful details');await page.getByRole('button',{name:'Go to pinned message',exact:true}).click();await expect(assistant).toHaveAttribute('data-message-jump','true')
 await page.getByRole('button',{name:'Saved messages',exact:true}).click();await expect(page.locator('.message-library')).toContainText('Thoughtful details');await expect(page.locator('.message-library [role=status]')).toHaveText('1 message');await page.screenshot({animations:'disabled',path:path.join(out,'saved-message-library.png')})
 await page.locator('.message-result-open').click();await expect(page.locator('[data-message-jump=true]')).toContainText('Thoughtful details');await expect(page.locator('.message-library')).toHaveCount(0)
 await assistant.click({button:'right'});await expect(page.getByRole('menu',{name:'Message options'})).toBeVisible();await page.getByRole('menuitem',{name:'Hide for me'}).click();await expect(page.locator('.message-hidden')).toContainText('Message hidden for you');assert.deepEqual((await call('session.transcript',{id:a.id})).items,before);await page.getByRole('button',{name:'Show message',exact:true}).click();await expect(assistant).toContainText('Thoughtful details')
 await assistant.hover();await assistant.getByRole('button',{name:'More message actions'}).click();await page.getByRole('menuitem',{name:'Select message',exact:true}).click();await page.locator('.turn.user').getByRole('checkbox',{name:'Select this message',exact:true}).check();await expect(page.getByRole('toolbar',{name:'Selected message actions'})).toContainText('2 selected')
 await page.getByRole('button',{name:'Save selected messages'}).click();await expect.poll(async()=>(await call('messenger.search',{conversation:ref,filter:'saved'})).total).toBe(2)
 await assistant.hover();await assistant.getByRole('button',{name:'More message actions'}).click();await page.getByRole('menuitem',{name:'Select message',exact:true}).click();await page.locator('.turn.user').getByRole('checkbox',{name:'Select this message',exact:true}).check();await page.getByRole('button',{name:'Forward selected messages'}).click()
 const forwarding=page.getByRole('dialog',{name:'Forward messages'});await forwarding.getByRole('textbox',{name:'Find forwarding destination'}).fill('Rowan');await forwarding.getByRole('button',{name:/^Rowan/}).click();await forwarding.getByRole('textbox',{name:'Forwarding note'}).fill('Please review these two messages.');await forwarding.getByRole('button',{name:'Forward',exact:true}).click();await expect(page.locator('.message-thread-header')).toContainText('Rowan');await expect(page.locator('.transcript')).toContainText('Please review these two messages.');await expect(page.locator('.transcript')).toContainText('Forwarded from Aster')
 await page.getByRole('button',{name:'Message Aster',exact:true}).click();await expect(assistant).toContainText('Thoughtful details')
 await composer.fill('design');await composer.selectText();await page.getByRole('button',{name:'Bold',exact:true}).click();await expect(composer).toHaveValue('**design**')
 await page.getByRole('button',{name:'Insert emoji',exact:true}).click();await page.getByRole('textbox',{name:'Search emoji',exact:true}).fill('Launch');await page.getByRole('button',{name:/^Insert rocket 🚀$/i}).click();await expect(composer).toBeFocused()
 assert.ok((await composer.inputValue()).includes('🚀'));await composer.fill('')
 await composer.fill('A draft worth keeping\n保留第二行。');await page.getByRole('button',{name:'Message Rowan',exact:true}).click();await expect.poll(async()=>(await state()).drafts[ref]?.text).toBe('A draft worth keeping\n保留第二行。')
 await page.reload();await expect(page.locator('.message-view')).toBeVisible();await page.getByRole('button',{name:'Message Aster',exact:true}).click();await expect(composer).toHaveValue('A draft worth keeping\n保留第二行。')
 await composer.fill('');await page.getByRole('button',{name:'Message Rowan',exact:true}).click();await expect.poll(async()=>(await state()).drafts[ref]).toBe(undefined)
 // Full history search goes beyond the 100-message viewport and returns to the exact original.
 await page.getByRole('textbox',{name:'Search conversations'}).fill('ORIGINAL_BRIEF');await page.locator('.message-search-history').click();await expect(page.locator('.message-result-open')).toContainText('Start with the user’s needs.');await page.locator('.message-result-open').click();await expect(page.locator('.group-conversation [data-message-jump=true]')).toContainText('ORIGINAL_BRIEF')
 await page.getByRole('button',{name:'Clear search',exact:true}).click();await page.getByRole('textbox',{name:'Group message'}).fill('Keep this group draft');await page.getByRole('button',{name:'Company Views',exact:true}).click();await page.getByRole('button',{name:'Messages',exact:true}).click();await page.getByRole('button',{name:'Open group Design circle',exact:true}).click();await expect(page.getByRole('textbox',{name:'Group message'})).toHaveValue('Keep this group draft');await page.reload();await expect(page.getByRole('textbox',{name:'Group message'})).toHaveValue('Keep this group draft')
 await page.getByRole('button',{name:'Message Aster',exact:true}).click();await expect(assistant).toContainText('Thoughtful details');await page.mouse.move(450,100);await page.screenshot({animations:'disabled',path:path.join(out,'messenger-desktop.png')})
 await page.getByRole('button',{name:'Employee details',exact:true}).click();await page.locator('.employee-profile-page').getByRole('tab',{name:'Messages',exact:true}).click();await page.locator('.profile-content-links').getByRole('button',{name:'Links',exact:true}).click();await expect(page.locator('.message-library')).toContainText('https://example.org/design')
 await page.getByRole('button',{name:'Close message library'}).click();const sourceId=await assistant.getAttribute('data-chat-item');await composer.fill('A linked reply from the desktop.');await assistant.hover();await assistant.getByRole('button',{name:'Reply to message',exact:true}).click();await expect(page.getByLabel('Reply preview')).toContainText('Thoughtful details');await expect(composer).toHaveValue('A linked reply from the desktop.');await composer.press('Enter')
 await expect.poll(async()=>(await call('session.status',{employee:a.id}))[0].busy).toBe(false);await acceptedMessage(call,a.id,'A linked reply from the desktop.');const linked=(await call('session.transcript',{id:a.id})).items.find(item=>item.text==='A linked reply from the desktop.');assert.equal(linked.reply.id,sourceId);assert.ok(linked.createdAt>0)
 const linkedRow=page.locator(`[data-chat-item="${linked.id}"]`);await linkedRow.getByRole('button',{name:'Go to original message'}).click();await expect(page.locator(`[data-chat-item="${sourceId}"]`)).toHaveAttribute('data-message-jump','true');await page.getByRole('button',{name:'Back to reply',exact:true}).click();await expect(linkedRow).toHaveAttribute('data-message-jump','true');await page.reload();await page.getByRole('button',{name:'Message Aster',exact:true}).click();await expect(linkedRow.locator('.message-reply-link')).toContainText('Thoughtful details')
 await composer.fill('A precise desktop quote.');const selectedSource=page.locator(`[data-chat-item="${sourceId}"] .markdown strong`).first(),selectedText=await selectedSource.textContent();await selectedSource.scrollIntoViewIfNeeded();await selectedSource.evaluate(el=>{const range=document.createRange();range.selectNodeContents(el);getSelection().removeAllRanges();getSelection().addRange(range)});await page.getByRole('button',{name:'Quote selected text',exact:true}).click();await expect(page.getByLabel('Reply preview')).toContainText(selectedText);await composer.press('Enter');await expect.poll(async()=>(await call('session.status',{employee:a.id}))[0].busy).toBe(false);await acceptedMessage(call,a.id,'A precise desktop quote.');const precise=(await call('session.transcript',{id:a.id})).items.find(item=>item.text==='A precise desktop quote.');assert.equal(precise.reply.quote.text,selectedText);await page.locator(`[data-chat-item="${precise.id}"]`).getByRole('button',{name:'Go to original message'}).click();await expect(page.locator(`[data-chat-item="${sourceId}"]`)).toHaveAttribute('data-quote-highlighted','true');assert.equal(await page.evaluate(()=>[...CSS.highlights.get('agents-message-quote')][0].toString()),selectedText)
 await page.locator(`[data-chat-item="${sourceId}"]`).click({button:'right'});await page.getByRole('menuitem',{name:'Reply in another conversation',exact:true}).click();const replyDialog=page.getByRole('dialog',{name:'Reply in another conversation'});await replyDialog.getByRole('textbox',{name:'Find reply destination'}).fill('Rowan');await replyDialog.locator('.message-forward-contacts>button').filter({hasText:'Rowan'}).click();await replyDialog.getByRole('button',{name:'Continue reply',exact:true}).click();await expect(replyDialog).toHaveCount(0);await expect(page.locator('.message-thread-header')).toContainText('Rowan');await expect(page.getByLabel('Reply preview')).toContainText('Aster');await composer.fill('A cross-conversation desktop reply.');await composer.press('Enter');await expect.poll(async()=>(await call('session.status',{employee:b.id}))[0].busy).toBe(false);await acceptedMessage(call,b.id,'A cross-conversation desktop reply.');const cross=(await call('session.transcript',{id:b.id})).items.find(item=>item.text==='A cross-conversation desktop reply.');assert.equal(cross.reply.conversation,'employee:'+a.id);await page.locator(`[data-chat-item="${cross.id}"]`).getByRole('button',{name:'Go to original message'}).click();await expect(page.locator('.message-thread-header')).toContainText('Aster');await page.getByRole('button',{name:'Back to reply',exact:true}).click();await expect(page.locator('.message-thread-header')).toContainText('Rowan')
 assert.deepEqual(await call('terminal.list'),[]);assert.deepEqual(errors,[]);assert.ok(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(window=>!window.isVisible())))
 console.log('PASS Messenger UI: pin/favorite/archive/restore, bulk selection, saved/reaction/pinned/context actions, hide/restore without history changes, exact original navigation across unloaded group history, persistent direct/group drafts through reload, scoped links panel, hidden windows and no automatic terminals')
}catch(error){await page.screenshot({animations:'disabled',path:path.join(out,'failure.png')}).catch(()=>{});throw error}finally{await app.close();fs.rmSync(temp,{recursive:true,force:true,maxRetries:10,retryDelay:100})}
