import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {spawn,execFile} from 'node:child_process'
import {promisify} from 'node:util'
import assert from 'node:assert/strict'
const run=promisify(execFile),project=path.resolve(import.meta.dirname,'..'),temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'ac-modes-'))),home=path.join(temp,'state'),work=path.join(temp,'work','mini-notion-workspace','Planning'),build=path.join(temp,'projects','Build project')
fs.mkdirSync(work,{recursive:true});fs.mkdirSync(build,{recursive:true})
const env={...process.env,AGENTS_COMPANY_HOME:home,AGENTS_COMPANY_WORKSPACES:path.join(temp,'work'),AGENTS_COMPANY_PROJECTS:path.join(temp,'projects')},server=spawn(process.execPath,['bin/agents','serve'],{cwd:project,env,stdio:['ignore','pipe','pipe']}),done=new Promise(r=>server.once('exit',r))
let log='';server.stderr.on('data',d=>log+=d)
const cli=async(...args)=>{const reply=JSON.parse((await run(process.execPath,['bin/agents',...args,'--json'],{cwd:project,env,timeout:20000,maxBuffer:8<<20})).stdout);assert.ok(reply.ok,reply.error);return reply.data}
const plugin=(employee,method,params={})=>cli('plugin','call','mininotion',method,'--employee',employee.id,'--params',JSON.stringify(params))
let checks=0;const ok=(value,label)=>{assert.ok(value,label);checks++;console.log('PASS '+label)}
try{
  for(let i=0;i<100&&!fs.existsSync(path.join(home,'agents.sock'));i++)await new Promise(r=>setTimeout(r,50))
  await assert.rejects(()=>cli('group','add','Invalid','--root',work,'--mode','work'))
  await assert.rejects(()=>cli('group','add','Invalid','--root',work,'--mode','work','--plugin','missing'))
  ok(!(await cli('group','list')).includes('Invalid'),'Work requires an installed plugin before creating the Team')
  await cli('group','add','Build project','--root',build,'--mode','build')
  const builder=await cli('card','create','--title','Builder','--group','Build project','--cwd','.','--directory-mode','bind'),builder2=await cli('card','create','--title','Reviewer','--group','Build project','--cwd','.','--directory-mode','bind')
  ok(builder.cwd===build&&builder2.cwd===build&&!fs.existsSync(path.join(build,'AGENTS.md'))&&!fs.existsSync(path.join(build,'.agents-company')),'Build is an ordinary shared folder without plugin injection')
  await assert.rejects(()=>cli('plugin','call','mininotion','fs.list','--team','Build project'))
  await cli('workspace','mkdir','src','--team','Build project')
  await cli('workspace','write','src/index.ts','--team','Build project','--content','export const value = 1')
  const file=await cli('workspace','read','src/index.ts','--team','Build project')
  await assert.rejects(()=>cli('workspace','write','src/index.ts','--team','Build project','--content','stale','--hash','wrong'))
  await cli('workspace','move','src/index.ts','--to','src/main.ts','--team','Build project')
  const removed=await cli('workspace','trash','src/main.ts','--team','Build project');await cli('workspace','restore','--id',removed.id,'--team','Build project')
  ok((await cli('workspace','read','src/main.ts','--team','Build project')).content===file.content,'Build file CRUD and conflict protection operate on real project files')
  await cli('group','add','Planning','--mode','work','--plugin','mininotion')
  const hire=async(title,cwd)=>cli('card','create','--title',title,'--group','Planning','--cwd',cwd)
  const owner=await hire('Owner','studio'),manager=await hire('Manager','studio/department'),worker=await hire('Writer','studio/department/writer'),other=await hire('Other','studio/other')
  await assert.rejects(()=>hire('Duplicate','studio/department/writer'))
  ok(owner.cwd===path.join(work,'studio')&&worker.cwd.startsWith(manager.cwd+'/'),'Work supports parent ownership and nested staff directories, with one employee per exact folder')
  const guide=fs.readFileSync(path.join(worker.cwd,'AGENTS.md'),'utf8'),index=JSON.parse(fs.readFileSync(path.join(worker.cwd,'.agents-company/workspace.json')))
  ok(guide.includes(worker.cwd)&&index.workspace===worker.cwd&&index.teamRoot===work&&index.plugins.length===1,'each employee gets selected-plugin docs and a launcher bound to its own folder')
  await plugin(worker,'fs.write',{path:'plan.md',content:'# Nested plan'})
  ok((await plugin(manager,'fs.read',{path:'writer/plan.md'})).content==='# Nested plan'&&(await plugin(owner,'fs.read',{path:'department/writer/plan.md'})).content==='# Nested plan','parent employees can read descendant workspaces')
  for(const [employee,file] of [[worker,'../manager.md'],[other,'../department/writer/plan.md'],[worker,path.join(other.cwd,'secret.md')]])await assert.rejects(()=>plugin(employee,'fs.write',{path:file,content:'denied'}))
  fs.symlinkSync(other.cwd,path.join(worker.cwd,'outside'))
  await assert.rejects(()=>plugin(worker,'fs.read',{path:'outside/secret.md'}))
  ok(!fs.existsSync(path.join(other.cwd,'secret.md')),'plugin APIs reject parents, siblings, absolute escapes and outward symlinks')
  const page=await plugin(worker,'page.create',{title:'Nested native note',color:'green'})
  await plugin(worker,'block.append',{pageId:page.id,text:'Shared through files'})
  ok((await plugin(owner,'page.get',{pageId:page.id})).title==='Nested native note','Team-root renderer discovers native documents created in nested workspaces')
  await plugin(manager,'page.update',{pageId:page.id,title:'Parent reviewed'})
  ok((await plugin(worker,'page.get',{pageId:page.id})).title==='Parent reviewed','parent API updates synchronize back to the child workspace')
  const projectPage=await plugin(owner,'page.create',{title:'Team project',color:'blue'})
  const nestedPage=await plugin(worker,'page.create',{parentId:page.id,title:'Nested child note',color:'white'})
  await plugin(owner,'page.move',{pageId:nestedPage.id,parentId:projectPage.id})
  ok((await plugin(worker,'page.get',{pageId:nestedPage.id})).title==='Nested child note','a document remains usable when its logical parent is outside the employee folder')
  await plugin(worker,'page.update',{pageId:nestedPage.id,title:'Child edited'})
  ok((await plugin(owner,'page.get',{pageId:nestedPage.id})).parentId===projectPage.id,'editing a child document preserves the parent Team notebook structure')
  const asset=await plugin(worker,'fs.asset-upload',{name:'pixel.png',contentBase64:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII='})
  const view=await cli('plugin','view','mininotion','--employee',owner.id)
  ok((await fetch(new URL('data/asset/'+asset.slice('asset://local/'.length),new URL('.',view.url)))).status===200,'parent renderer resolves attachments owned by nested workspaces')
  await cli('plugin','close',view.id)
  const live=await cli('session','open',worker.id)
  await assert.rejects(()=>cli('config','permission',live.sessionId,'bypassPermissions'))
  const shim=path.join(worker.cwd,'.agents-company/bin/mininotion')
  const output=await run(shim,['api','fs.write','--data','{"path":"from-cli.md","content":"SCOPED"}'],{cwd:worker.cwd,env,timeout:15000})
  ok(JSON.parse(output.stdout).content==='SCOPED'&&fs.existsSync(path.join(worker.cwd,'from-cli.md')),'prepared CLI mailbox executes inside the employee scope')
  await assert.rejects(()=>run(shim,['--workspace',work,'fs','list'],{cwd:worker.cwd,env}))
  ok(true,'Work cannot escalate to Full access or override a bound launcher workspace')
  await cli('session','close',live.sessionId)
  await assert.rejects(()=>cli('group','rename','Planning','Studio'))
  ok((await cli('session','list')).teamSettings.Planning.pluginId==='mininotion','Team name is locked while its mode and plugin binding remain intact')
  await assert.rejects(()=>cli('group','configure','Planning','--mode','build'))
  ok(fs.existsSync(shim),'mode changes cannot silently reassign existing employee files')
  console.log(`PASS=${checks} FAIL=0 — no model calls`)
}catch(error){console.error(log.slice(-6000));throw error}finally{server.kill('SIGTERM');await done;fs.rmSync(temp,{recursive:true,force:true})}
