const $=s=>document.querySelector(s),token=location.pathname.split('/')[1],escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
let hosts=[],selected=null,editing=false,dirty=false,loading=false,view='overview',cleanup=()=>{},renderVersion=0
let messageTimer
const message=(text,kind='info')=>{clearTimeout(messageTimer);const node=$('#message');node.textContent=text;node.dataset.kind=kind;if(text&&kind!=='error')messageTimer=setTimeout(()=>{node.textContent=''},5000)}
window.cloudClients={};window.cloudClientReady={}
const assets=new Map()
function loadClient(name){
 if(!assets.has(name))assets.set(name,new Promise((resolve,reject)=>{
  const styles=name==='terminal'?new Promise((ready,failed)=>{const css=document.createElement('link');css.rel='stylesheet';css.href='./terminal.bundle.css';css.onload=ready;css.onerror=()=>{css.remove();failed(Error('终端样式加载失败，请重新选择此页面'))};document.head.append(css)}):Promise.resolve()
  styles.catch(reject)
  const script=document.createElement('script');script.src='./'+name+'.bundle.js'
  script.onload=()=>Promise.all([styles,window.cloudClientReady[name]]).then(()=>resolve(window.cloudClients[name]),reject)
  script.onerror=()=>{assets.delete(name);script.remove();reject(Error('工作台加载失败，请重新选择此页面'))};document.head.append(script)
 }))
 return assets.get(name).catch(error=>{assets.delete(name);throw error})
}
async function rpc(method,params={},options={}){const reply=await fetch('./rpc',{...options,method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})}).then(r=>r.json());if(reply.error)throw Error(reply.error.message);return reply.result}
function label(host){return host.os==='windows'?'Windows':host.os==='macos'?'macOS':host.distribution||'Linux'}
let loadingHosts,lastList=''
async function load(){
 if(loadingHosts)return loadingHosts
 loadingHosts=(async()=>{const previous=JSON.stringify(hosts.find(h=>h.id===selected)),previousId=selected;hosts=await rpc('hosts.list');if(selected&&!hosts.some(h=>h.id===selected))selected=null;selected??=hosts[0]?.id??null;renderList();if(!editing&&(previousId!==selected||view==='overview'&&previous!==JSON.stringify(hosts.find(h=>h.id===selected))||!$('#detail').children.length))renderDetail()})()
 try{await loadingHosts}finally{loadingHosts=null}
}
function renderList(){
 const query=$('#search').value.trim().toLowerCase(),filtered=hosts.filter(h=>(h.name+' '+h.host+' '+label(h)).toLowerCase().includes(query))
 const signature=JSON.stringify([selected,query,hosts]);if(signature===lastList)return;lastList=signature
 $('#count').textContent=hosts.length;$('#online-count').textContent=hosts.filter(h=>h.status?.connected).length
 $('#hosts').innerHTML=filtered.length?filtered.map(h=>`<button class="host-card ${selected===h.id?'selected':''}" data-id="${escape(h.id)}" aria-pressed="${selected===h.id}" title="${escape(h.name)}"><span class="server-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="4" y="3" width="16" height="7" rx="2"/><rect x="4" y="14" width="16" height="7" rx="2"/><path d="M8 6.5h1m-1 11h1m4-11h4m-4 11h4"/></svg></span><span><strong>${escape(h.name)}</strong><small>${escape(label(h))} · ${escape(h.vm?'VM':h.host)}</small></span><i class="lamp ${h.status?.connected?'online':h.status?'offline':''}" title="${h.status?.connected?'上次检查可连接':h.status?'上次检查未连接':'尚未检查'}"></i></button>`).join(''):'<p class="list-empty">'+(query?'没有匹配的主机':'尚未添加主机')+'</p>'
}
$('#hosts').onclick=event=>{const button=event.target.closest('[data-id]');if(!button)return;if(dirty){message('请先保存或取消当前编辑');return}if(!editing&&selected===button.dataset.id)return;selected=button.dataset.id;editing=false;message('');renderList();renderDetail()}
function renderOverview(){const h=hosts.find(h=>h.id===selected);if(!h){$('#panel').innerHTML='<div class="empty"><span aria-hidden="true">⌁</span><h2>连接你的第一台主机</h2><p>集中管理连接，在终端或远程桌面中工作。</p><button class="primary" id="first-add">添加第一台主机</button></div>';$('#first-add').onclick=()=>form();return}
 const active=()=>selected===h.id&&!editing&&view==='overview'
 $('#panel').innerHTML=`<div class="detail-heading"><div><span class="eyebrow">${escape(label(h))} / SSH</span><h2>${escape(h.name)}</h2><p>${escape(h.host)} <span class="tag">端口 ${h.port||22}</span></p></div><button id="edit">编辑主机</button></div><div class="status-card"><i class="lamp ${h.status?.connected?'online':h.status?'offline':''}"></i><div><strong>${h.status?.connected?'连接正常':h.status?'暂时无法连接':'等待连接检查'}</strong><p>${escape(h.status?.error||h.status?.environment?.distributionName||'状态来自上次 SSH 检查')}${h.status?.checkedAt?'<br>最后检测：'+escape(new Date(h.status.checkedAt).toLocaleString()):''}</p></div><button id="fingerprints">查看指纹</button><button id="check">测试连接</button></div><div id="host-keys"></div>${h.vm?`<div class="status-card"><div><strong>虚拟机 · ${escape(h.vm.name)}</strong><p>宿主：${escape(hosts.find(p=>p.id===h.vm.hypervisorId)?.name||h.vm.hypervisorId)} · 电源：${escape(h.vm.state)} · 管理入口：${escape(h.vm.access)}<br>${escape(h.vm.projectDirectory)}<br>${escape(h.vm.notes||'')}</p></div></div>`:''}<div class="facts"><div><span>默认浏览目录</span><code>${escape(h.defaultDirectory)}</code></div><div><span>认证方式</span><strong>${h.hasPassword?'已保存密码':h.identityFile?'指定 SSH 私钥':'现有 SSH 密钥 / 配置'}</strong></div><div><span>密码</span><div class="secret"><input id="password-view" type="password" readonly value="${h.hasPassword?'••••••••':''}" placeholder="未保存密码"><button id="reveal" ${h.hasPassword?'':'disabled'}>查看</button></div></div><div><span>桌面连接</span><strong>${h.desktop?escape(h.desktop.protocol.toUpperCase())+' · '+(h.desktop.viaHostId?'SSH 通道':'直接连接'):'未配置'}</strong></div></div><div class="detail-footer"><div><p>连接配置由所有绑定团队共享。</p><details class="host-meta"><summary>主机 ID</summary><code>${escape(h.id)}</code></details></div><button class="danger" id="remove">删除主机</button></div>`
 $('#fingerprints').onclick=async()=>{try{message('正在读取服务器指纹…');const keys=await rpc('hosts.fingerprints',{id:h.id});if(!active())return;$('#host-keys').innerHTML='<p>请与云主机提供方给出的指纹核对，确认一致后再信任。</p>'+keys.map(key=>`<div><code>${escape(key.algorithm)} ${escape(key.fingerprint)}</code><button data-fingerprint="${escape(key.fingerprint)}">信任此指纹</button></div>`).join('');$('#host-keys').querySelectorAll('button').forEach(b=>b.onclick=async()=>{try{await rpc('hosts.trust',{id:h.id,fingerprint:b.dataset.fingerprint});await load();message('已记录确认过的指纹')}catch(e){message(e.message,'error')}});message('')}catch(e){message(e.message,'error')}}
 $('#edit').onclick=()=>form(h);$('#check').onclick=async()=>{try{message('正在检测…');await rpc('hosts.check',{id:h.id});await load();message('检测完成')}catch(e){message(e.message,'error')}}
 $('#reveal').onclick=async()=>{try{const input=$('#password-view');if(input.type==='text'){input.type='password';input.value='••••••••';$('#reveal').textContent='查看';return}const credentials=await rpc('hosts.credentials',{id:h.id,files:false});if(!active()||input!==$('#password-view'))return;input.value=credentials.password;input.type='text';$('#reveal').textContent='隐藏'}catch(e){message(e.message,'error')}}
 $('#remove').onclick=async()=>{if($('#remove').dataset.confirm!=='1'){$('#remove').dataset.confirm='1';$('#remove').textContent='确认删除';return}try{await rpc('hosts.remove',{id:h.id});selected=null;await load();message('主机已移除')}catch(e){message(e.message,'error')}}
}
function form(h={}){cleanup();renderVersion++;editing=true;dirty=false;$('#detail').classList.remove('workbench');message('');const field=(name,title,placeholder='',type='text')=>`<label>${title}<input name="${name}" type="${type}" value="${escape(h[name]??'')}" placeholder="${escape(placeholder)}" ${['name','host','defaultDirectory'].includes(name)?'required':''}></label>`
 $('#detail').innerHTML=`<form><div class="detail-heading"><div><span class="eyebrow">CONNECTION PROFILE</span><h2>${h.id?'编辑云主机':'新建云主机'}</h2></div><button type="button" id="cancel">取消</button></div><div class="form-grid">${field('name','主机名称','例如 GPU Server')}${field('host','SSH 账号与地址','user@203.0.113.10 或已配置的 SSH 别名')}</div><label>操作系统</label><div class="os-picker">${[['linux','Linux'],['windows','Windows'],['macos','macOS']].map(([value,text])=>`<label><input type="radio" name="os" value="${value}" ${(h.os||'linux')===value?'checked':''}><span>${text}</span></label>`).join('')}</div><div class="form-grid">${field('defaultDirectory','默认浏览目录','/home/user 或 C:\\Users\\user')}${field('port','SSH 端口','22','number')}</div><label>登录密码<input name="password" type="password" autocomplete="new-password" placeholder="${h.hasPassword?'留空保留现有密码':'可选，留空使用 SSH 密钥或已有配置'}"></label>${h.hasPassword?'<label class="checkbox"><input type="checkbox" name="clearPassword">删除保存的密码，改用密钥认证</label>':''}<details><summary>SSH 密钥与高级设置</summary><div class="form-grid">${field('identityFile','私钥路径','~/.ssh/id_ed25519')}${field('sshConfig','SSH 配置路径','~/.ssh/config')}${field('knownHosts','known_hosts 路径','~/.ssh/known_hosts')}${field('jump','跳板机','user@jump-host')}${field('distribution','Linux 发行版','kali / ubuntu / debian')}</div></details><details id="desktop-config"><summary>远程桌面 · RDP / VNC</summary><div class="form-grid"><label>桌面协议<select name="desktopProtocol"><option value="">未配置</option><option value="rdp" ${h.desktop?.protocol==='rdp'?'selected':''}>RDP · 原生客户端</option><option value="vnc" ${h.desktop?.protocol==='vnc'?'selected':''}>VNC · 内嵌画面</option></select></label><label>连接通道<select name="desktopVia"><option value="">直接连接</option>${hosts.filter(x=>!x.vm||x.vm.access==='ssh').map(x=>`<option value="${escape(x.id)}" ${h.desktop?.viaHostId===x.id?'selected':''}>SSH · ${escape(x.name)}</option>`).join('')}</select></label><label>桌面服务地址<input name="desktopAddress" value="${escape(h.desktop?.address||'127.0.0.1')}" placeholder="从连接通道看见的主机地址"></label><label>桌面端口<input name="desktopPort" type="number" min="1" max="65535" value="${h.desktop?.port||3389}"></label><label>桌面用户名<input name="desktopUsername" value="${escape(h.desktop?.username||'')}" autocomplete="off"></label><label>VNC 画质<select name="desktopQuality">${[['balanced','均衡'],['fast','流畅'],['sharp','清晰']].map(([v,t])=>`<option value="${v}" ${(h.desktop?.quality||'balanced')===v?'selected':''}>${t}</option>`).join('')}</select></label></div><p class="hint">SSH 通道推荐用于非公网桌面服务。地址相对于 SSH 通道主机；连接本机桌面服务使用 127.0.0.1。远端须已启用 RDP 或 VNC，桌面密码在连接时输入。</p></details><p class="hint">工作目录只作为默认起点，创建 Team 时可以选择该账号可访问的其他现有目录。保持 SSH 主机指纹验证，不自动接受未知主机。</p><footer><button class="primary" type="submit">保存主机</button></footer></form>`
 const el=$('form');el.elements.name.focus({preventScroll:true});el.elements.desktopProtocol.onchange=()=>{el.elements.desktopPort.value=el.elements.desktopProtocol.value==='vnc'?5900:3389;dirty=true};el.oninput=()=>{dirty=true};$('#cancel').onclick=()=>{editing=false;dirty=false;renderDetail()}
 el.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(el));data.desktop=data.desktopProtocol?{protocol:data.desktopProtocol,address:data.desktopAddress.trim(),port:Number(data.desktopPort),username:data.desktopUsername,quality:data.desktopQuality,...(data.desktopVia?{viaHostId:data.desktopVia}:{})}:null;for(const key of Object.keys(data))if(key.startsWith('desktop')&&key!=='desktop')delete data[key];data.port=data.port?Number(data.port):undefined;if(!data.password)delete data.password;if(data.clearPassword)data.password='';delete data.clearPassword;if(data.os!=='linux')data.distribution='';const submit=el.querySelector('[type=submit]'),cancel=$('#cancel');dirty=true;submit.disabled=true;cancel.disabled=true;$('#add').disabled=true;try{const result=await rpc(h.id?'hosts.update':'hosts.create',h.id?{id:h.id,patch:data}:data);selected=result.id;editing=false;dirty=false;await load();if($('#detail form'))renderDetail();message('主机已保存，可以在 Team 中绑定')}catch(error){message(error.message,'error')}finally{submit.disabled=false;cancel.disabled=false;$('#add').disabled=false}}
}
async function refresh(){if(loading)return;loading=true;$('#refresh').disabled=true;try{const results=await Promise.allSettled(hosts.map(h=>rpc('hosts.check',{id:h.id})));const failed=results.filter(r=>r.status==='rejected');await load();message(failed.length?failed.length+' 台主机检查失败':'连接状态已更新')}catch(e){message(e.message,'error')}finally{loading=false;$('#refresh').disabled=false}}
$('#search').oninput=renderList;$('#add').onclick=()=>{if(dirty){message('请先保存或取消当前编辑');return}form()};$('#refresh').onclick=refresh
window.addEventListener('message',event=>{if(event.source!==parent||event.data?.token!==token)return;if(event.data.type==='agents-plugin:flush')parent.postMessage({type:'agents-plugin:flushed',token,id:event.data.id,...(dirty?{error:'有未保存的云主机资料，请先保存或取消'}:{})},'*')})
load().then(()=>{$('#add').disabled=false;$('#refresh').disabled=false;parent.postMessage({type:'agents-plugin:ready',token},'*')}).catch(e=>message(e.message,'error'));setInterval(()=>{if(!editing&&!document.hidden)void load().catch(e=>message(e.message,'error'))},10000)

function renderDetail(){
 cleanup();cleanup=()=>{};const version=++renderVersion;editing=false
 const host=hosts.find(h=>h.id===selected)
 $('#detail').innerHTML=`<nav class="view-tabs" aria-label="主机工作台"><button data-view="overview" class="${view==='overview'?'active':''}">概览</button><button data-view="terminal" class="${view==='terminal'?'active':''}" ${host?'':'disabled'}>终端</button><button data-view="desktop" class="${view==='desktop'?'active':''}" ${host?'':'disabled'}>远程桌面</button></nav><div id="panel"></div>`
 $('#detail').classList.toggle('workbench',view!=='overview'&&!!host)
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(view===b.dataset.view&&!$('#panel .pane-loading'))return;view=b.dataset.view;message('');renderDetail()})
 if(!host||view==='overview'){renderOverview();return}
 const configure=()=>{form(host);$('#desktop-config').open=true;$('#desktop-config').scrollIntoView({block:'center'})}
 const target=view;$('#panel').innerHTML='<div class="pane-loading" role="status">正在准备'+(target==='terminal'?'终端':'桌面')+'…</div>'
 loadClient(target).then(pane=>{if(version!==renderVersion)return;cleanup=pane($('#panel'),host,rpc,message,configure,loadClient)}).catch(e=>{if(version===renderVersion){$('#panel').innerHTML='<div class="pane-loading">暂时无法加载，请重新选择此页面。</div>';message(e.message,'error')}})
}
window.addEventListener('beforeunload',()=>cleanup())

document.addEventListener('visibilitychange',()=>{if(document.hidden){const input=$('#password-view');if(input){input.type='password';input.value=hosts.find(h=>h.id===selected)?.hasPassword?'••••••••':'';if($('#reveal'))$('#reveal').textContent='查看'}}else if(!editing)void load().catch(e=>message(e.message,'error'))})
