import { CommandError } from './errors';

const topics: Record<string, string> = {
  "start": "你正在使用本地 CLI-first MiniNotion，不需要 Notion 云端 API 或独立 Agent。\n1. mininotion status：版本必须至少 1.21.0；fs.info 确认当前目录。\n2. mininotion guide pages / databases / delegation / verify 获取小份实操说明。\n3. 新建原生页面：mininotion page create --title '技术分析' --color white，保留返回的 id。\n4. 写富正文用 page.write-markdown；需要复杂原生块时先 block.validate。\n5. page.create --parent-id ID 创建任意深度子页面；每个页面有独立文件夹，每一层子页面自动创建下一层子文件夹；页面树与目录树完全一致。\n6. 数据库视图是 database.create + record.create + view.create，不是 Markdown 表格。\n7. fs.audit 确认 valid:true，再 page.audit ROOT_ID + fs.path --page-id ROOT_ID + view.render DATABASE_ID 验收，再报告真实 ID、目录和统计。\n插件 CLI 输出直接是领域 JSON；宿主 agents CLI --json 输出 {ok,data}。\n创建/修改不要加 | head 或吞掉错误；JSON 长文用 --data @request.json 或 stdin -，失败退出码非零。",
  "pages": "原生页面创建返回 {id,title,parentId,...}；所有新建 page/database/record 都传 color:white（或其他支持颜色）。\nmininotion page create --title '架构主页面' --color white\nmininotion page create --title 'Core 分析' --color white --parent-id ROOT_ID\nmininotion page create --title '鉴权路径' --color white --parent-id CHILD_ID\n绑定现有员工目录对应的页面（它在全局仍按所在目录层级显示）：mininotion api fs.bind --data '{\"path\":\".\",\"title\":\"知识库\"}'（返回 pageId）。\n富文本写入：mininotion api page.write-markdown --data @request.json\nrequest.json 为 {\"pageId\":\"返回的ID\",\"mode\":\"replace\",\"markdown\":\"## 架构\\n\\n正文\\n\\n|模块|职责|\\n|---|---|\\n|Core|共享服务|\"}\n默认 replace 仅替换正文，保留页面/子页面/数据库定义；append 在原文后追加。覆盖已有正文前先 page.read-markdown PAGE_ID 取得 hash，将它作为 expectedHash 提交。CONFLICT 时重新读取合并，不强行重试。\npage.read-markdown 是可读投影，特殊块/数据库配置不能经 Markdown 往返无损保存；编辑复杂原生块用 block.*。\n长篇已有 Markdown 文件：读取文件构造上述 JSON 后提交，勿只 fs.write xxx.md 就认为写入了原生页面。\nfs.path --page-id PAGE_ID 返回 absoluteDirectory、parentPageId、depth、mainPage。全局主页面只能是 mini-notion-workspace 的直接子文件夹；子页面保存在父目录/子目录/index.mininotion.json。改标题保持目录名；page.move 会实际移动整棵目录及原文件。",
  "blocks": "优先 page.write-markdown 转换标题、代码、列表和表格，无需自行实现解析器。\n原生块：mininotion schema block.append --compact 返回全部类型、字段和例子。\n先校验：mininotion api block.validate --data '{\"blocks\":[{\"type\":\"table\",\"content\":{\"type\":\"tableContent\",\"rows\":[{\"cells\":[\"模块\",\"职责\"]},{\"cells\":[\"Core\",\"共享后端\"]}]}}]}'\n成功返回 valid:true、normalized blocks；没有写任何页面。\n再写：mininotion api block.append --data '{\"pageId\":\"ID\",\"blocks\":[{\"type\":\"heading\",\"props\":{\"level\":2},\"content\":\"实现\"},{\"type\":\"callout\",\"props\":{\"emoji\":\"💡\",\"backgroundColor\":\"blue\"},\"content\":\"关键结论\"}]}'\n表格每行必须 {cells:[...]}；每个 cell 是字符串或行内内容数组 [{type:\"text\",text:\"值\",styles:{}}]，不能是单个 {type:\"text\",...}。\nchildren 递归表示块缩进，page.parentId 表示页面层级，两者不要混用。column 必须在 columnList 中。databaseView / syncedBlock / button 建议用对应的 database.embed / sync.create / button.create，避免手拼引用。",
  "databases": "所有视图与 GUI 共用真实记录。先创建数据库，再创建记录和视图，保存各自返回 ID。\nmininotion api database.create --data '{\"title\":\"技术模块索引\",\"parentId\":\"ROOT_ID\",\"color\":\"blue\",\"view\":\"table\"}'\nmininotion property list DATABASE_ID：确认实际属性 ID 和选项，不要猜字段。默认 status 常用值：未开始、进行中、已完成；使用返回的选项。\nmininotion api record.create --data '{\"databaseId\":\"DATABASE_ID\",\"title\":\"Core\",\"color\":\"white\",\"values\":{\"status\":\"已完成\"},\"blocks\":[{\"type\":\"paragraph\",\"content\":\"分析摘要与源码路径\"}]}'\nmininotion api view.create --data '{\"databaseId\":\"DATABASE_ID\",\"type\":\"board\",\"name\":\"按分析进度\",\"config\":{\"groupBy\":\"status\"}}'\nmininotion api view.create --data '{\"databaseId\":\"DATABASE_ID\",\"type\":\"gallery\",\"name\":\"模块卡片\"}'\nmininotion api view.create --data '{\"databaseId\":\"DATABASE_ID\",\"type\":\"list\",\"name\":\"阅读目录\"}'\n支持 table / board / gallery / list / calendar / timeline / chart / form / plan。\n日历和时间线需创建 date 属性并填写记录日期，不能只创建空视图。复杂配置先 schema view.update --compact（view fields）和 property.list。\n视图选择：view.select DATABASE_ID VIEW_ID；验收：view.list DATABASE_ID、record.list DATABASE_ID、view.render DATABASE_ID --view-id VIEW_ID。\n正文嵌入现有库：mininotion api database.embed --data '{\"pageId\":\"ROOT_ID\",\"databaseId\":\"DATABASE_ID\",\"view\":\"board\"}'。\n同一数据库多个视图保留相同记录，不复制数据库冒充视图。",
  "delegation": "子 Agent 是宿主注册员工，使用 agents card/session/management API，不能用插件 agent.* 或引擎隐藏 native subagent 代替。\n先 agents auth whoami --json 与 agents management topology --json。普通 Employee 没有雇佣/派发权限；由用户或本 Team Manager 派发。\n先 agents engine capabilities --engine claude --json；只选择 workspaceModes 含 work 的引擎。当前 Work 支持 Codex/Claude；Pi/Cline 的能力不含 work，不能只修改名字或静默降级权限。优先复用本 Team 已有支持 Work 的员工，用户有明确引擎约束时报告实际能力。\n路径安排：父目录 Manager 可看到子工作目录；兄弟员工通过自己的 CLI 无法读取 Manager 页面。两种有效流程：\nA. 创建员工并绑定主页面目录中的子文件夹，在其 cwd 用 fs.bind 创建该目录原生页、page.create 继续递归；父范围会索引它。\nB. 复用已在兄弟目录的分析员工，明确让它返回有源码证据的 Markdown/结构化结果，Manager 用自己 page.write-markdown 写入指定原生子页面。不要让它用错误 workspace 强行写父级。\nManager 示例：agents card create --title '模块分析' --group '本Team' --engine claude --model deepseek-flash --thinking off --directory-mode bind --cwd '/已存在且属于本Team的目录' --json\n派发：agents session send --employee EMPLOYEE_ID --text '只读分析指定源码，说明入口/调用链/状态/错误路径/测试及路径行号；返回可直接写入的技术分析。不要修改或运行被分析项目。' --json\n返回 messageId 仅代表接受。逐个 session status / session transcript / session follow 查询完成、error、busy；报告的代码/页面路径需实际读取。不要派发后直接宣称完成。\n需要更深时继续把目标子页面 ID 作为 parentId；新内容应有证据和实际纵向细节，不能用空标题凑深度。",
  "verify": "完成条件必须同时满足数据和界面：\nmininotion page audit ROOT_ID：返回 pageCount、maxDepth、emptyLeafPages、每页 characters/blocks、databases/views/recordCount。结构统计不证明分析事实正确，仍需查源码证据。\nmininotion page tree --parent-id ROOT_ID；page.get 和 page.read-markdown 抽查正文。\nmininotion fs path --page-id ROOT_ID；fs.sync 返回 errors 应为空；fs.audit 必须 valid:true，检查每一层目录的父子关系。\nmininotion view list DATABASE_ID / view.render DATABASE_ID --view-id VIEW_ID：确认记录出现在相应分组。\n用户侧 agents plugin open mininotion（1.19.0 安装版默认集合）或 --team TEAM；员工不可自行打开用户窗口。\n遇到“CLI 成功但看不见”先查安装版 plugin describe 的版本、plugin windows 的 workspace 和 fs.path。源码构建成功不表示安装版已更新；不要重建重复页面或写另一个个人库。\n最终说明根页面 ID、主目录、非空页面数、实际最大深度、数据库和视图、子任务员工/消息/完成证据；任何失败应如实报告。"
};
export function agentGuide(topic = 'start') {
  if (!Object.hasOwn(topics, topic)) throw new CommandError('INVALID_ARGUMENT', 'guide topic: ' + Object.keys(topics).join(' / '));
  return { topic, topics: Object.keys(topics), markdown: topics[topic] };
}
