import fs from 'node:fs'
import path from 'node:path'
import { requirePlugin, pluginFile } from './registry'
import type { TeamSettings } from '../../shared/types'

const BEGIN='<!-- agents-company:workspace:start -->',END='<!-- agents-company:workspace:end -->'
const quote=(text:string)=>`'${text.replace(/'/g,"'\\''")}'`
function safeWrite(root:string,file:string,content:string,executable=false) {
  if(fs.existsSync(file)&&fs.lstatSync(file).isSymbolicLink())throw new Error(`Cannot replace a documentation symlink: ${file}`)
  let parent=path.dirname(file)
  while(!fs.existsSync(parent))parent=path.dirname(parent)
  const actual=fs.realpathSync(parent)
  if(actual!==root&&!actual.startsWith(root+path.sep))throw new Error('Workspace documentation path points outside its root')
  fs.mkdirSync(path.dirname(file),{recursive:true})
  if(fs.existsSync(file)&&fs.readFileSync(file,'utf8')===content)return
  fs.writeFileSync(file,content,{mode:executable?0o755:0o644})
  if(executable)fs.chmodSync(file,0o755)
}
function instructions(root:string,block:string) {
  for(const name of ['AGENTS.md','CLAUDE.md']) {
    const file=path.join(root,name),existing=fs.existsSync(file)?fs.readFileSync(file,'utf8'):''
    const a=existing.indexOf(BEGIN),b=existing.indexOf(END)
    const next=a>=0&&b>=a?existing.slice(0,a)+block+existing.slice(b+END.length):block?existing.trimEnd()+(existing.trim()?'\n\n':'')+block+'\n':existing
    if(next!==existing)safeWrite(root,file,next)
  }
}
/** Each Work employee receives a launcher bound to its own directory, never its parent. */
export function provisionWorkspace(root:string,settings:TeamSettings,teamRoot=root) {
  root=fs.realpathSync(root);teamRoot=fs.realpathSync(teamRoot)
  const directory=path.join(root,'.agents-company'),indexFile=path.join(directory,'workspace.json')
  const plugins=settings.mode==='work'?[requirePlugin(settings.pluginId!)]:[]
  const index={schemaVersion:2,mode:settings.mode,workspace:root,teamRoot,plugins:plugins.map(p=>({id:p.id,name:p.name,version:p.version,documentation:`plugins/${p.id}/API.md`}))}
  if(fs.existsSync(indexFile)) {
    const previous=JSON.parse(fs.readFileSync(indexFile,'utf8'))
    for(const old of previous.plugins??[])if(!plugins.some(p=>p.id===old.id)&&/^[a-z][a-z0-9-]*$/.test(old.id)) {
      const file=path.join(directory,'bin',old.id)
      if(fs.existsSync(file)&&!fs.lstatSync(file).isSymbolicLink()&&fs.readFileSync(file,'utf8').includes('# Generated by Agents Company;'))fs.unlinkSync(file)
    }
  }
  if(settings.mode==='build') {
    instructions(root,'')
    if(fs.existsSync(indexFile))safeWrite(root,indexFile,JSON.stringify(index,null,2)+'\n')
    return index
  }
  safeWrite(root,indexFile,JSON.stringify(index,null,2)+'\n')
  const plugin=plugins[0]
  safeWrite(root,path.join(directory,'README.md'),`# Work workspace CLI guide\n\nPlugin: **${plugin.name}** (${plugin.version}).\n\n## Scope\n\nYour authorized workspace is \`${root}\` and its descendant folders.\nA parent-folder employee can operate its descendants; a child-folder employee cannot operate its parent or siblings. Plugin paths are relative to YOUR workspace.\n\n## Quick start\n\nRead [API.md](plugins/${plugin.id}/API.md) and [schema.json](plugins/${plugin.id}/schema.json).\nUse \`${path.join(directory,'bin',plugin.id)}\` if your shell resets PATH. The launcher already supplies --workspace; do not override its folder.\n\n## Files\n\nUse the plugin CLI/API for managed documents. User files stay in this directory. Existing AGENTS.md and CLAUDE.md content outside the managed block is retained.\n`)
  safeWrite(root,path.join(directory,'plugins',plugin.id,'API.md'),fs.readFileSync(pluginFile(plugin.directory,plugin.documentation),'utf8'))
  safeWrite(root,path.join(directory,'plugins',plugin.id,'schema.json'),fs.readFileSync(pluginFile(plugin.directory,plugin.schema),'utf8'))
  const cli=pluginFile(plugin.directory,plugin.cli)
  safeWrite(root,path.join(directory,'bin',plugin.id),`#!/bin/sh\n# Generated by Agents Company; this CLI is bound to the employee workspace.\nfor argument in "$@"; do\n  case "$argument" in --workspace|--workspace=*) echo 'This launcher is already bound to its authorized workspace.' >&2; exit 2 ;; esac\ndone\nexport AGENTS_WORKSPACE=${quote(root)}\nexport AGENTS_TEAM_ROOT=${quote(teamRoot)}\nexport AGENTS_COMPANY_PLUGIN_RPC=${quote(path.join(directory,'ipc',plugin.id))}\nexec env ELECTRON_RUN_AS_NODE=1 ${quote(process.execPath)} ${quote(cli)} --workspace ${quote(root)} "$@"\n`,true)
  instructions(root,`${BEGIN}\n## Work workspace tools\n\nRead [the workspace CLI guide](.agents-company/README.md) before working.\nYour authorized folder is \`${root}\`, including its descendants. Do not operate parent or sibling folders.\nUse \`${path.join(directory,'bin',plugin.id)}\`; it is already bound to this folder.\nUse the documented CLI/API instead of editing plugin-managed state.\n${END}`)
  return index
}
export function provisionEmployee(cwd:string,root:string,settings:TeamSettings) {if(settings.mode!=='work')return {mode:settings.mode,workspace:cwd,teamRoot:root,plugins:[]};return provisionWorkspace(cwd,settings,root)}
