import fs from 'node:fs'
import path from 'node:path'
import { requirePlugin, pluginFile } from './registry'
import {teamSettings,type TeamSettings,type Store,type StoredSession} from '../../shared/types'
import {apiDocumentation,permissionDocumentation} from '../authorization'
import {readStore} from '../store'
import {assertManagementKind} from '../../shared/management'

const BEGIN='<!-- agents-company:workspace:start -->',END='<!-- agents-company:workspace:end -->'
const quote=(text:string)=>`'${text.replace(/'/g,"'\\''")}'`
function safeWrite(root:string,file:string,content:string,executable=false) {
  if(fs.existsSync(file)&&fs.lstatSync(file).isSymbolicLink())throw new Error(`Cannot replace a documentation symlink: ${file}`)
  let parent=path.dirname(file)
  while(!fs.existsSync(parent))parent=path.dirname(parent)
  const actual=fs.realpathSync(parent)
  if(actual!==root&&!actual.startsWith(root+path.sep))throw new Error('Workspace documentation path points outside its root')
  fs.mkdirSync(path.dirname(file),{recursive:true})
  if(fs.existsSync(file)&&fs.readFileSync(file,'utf8')===content)return
  fs.writeFileSync(file,content,{mode:executable?0o755:0o644})
  if(executable)fs.chmodSync(file,0o755)
}
function instructions(root:string,block:string,begin=BEGIN,end=END) {
  for(const name of ['AGENTS.md','CLAUDE.md']) {
    // Retire only our marked root-level block. User-authored instructions are never hidden or deleted.
    const legacy=path.join(root,name)
    if(fs.existsSync(legacy)){
      const previous=fs.readFileSync(legacy,'utf8'),a=previous.indexOf(begin),b=previous.indexOf(end)
      if(a>=0&&b>=a){
        const next=previous.slice(0,a)+previous.slice(b+end.length)
        if(next.trim())safeWrite(root,legacy,next)
        else {if(fs.lstatSync(legacy).isSymbolicLink())throw new Error('Cannot replace a documentation symlink');fs.unlinkSync(legacy)}
      }
    }
    const file=path.join(root,'.agents-company',name),existing=fs.existsSync(file)?fs.readFileSync(file,'utf8'):''
    const a=existing.indexOf(begin),b=existing.indexOf(end)
    const next=a>=0&&b>=a?existing.slice(0,a)+block+existing.slice(b+end.length):block?existing.trimEnd()+(existing.trim()?'\n\n':'')+block+'\n':existing
    if(next!==existing)safeWrite(root,file,next)
  }
}
/** Each Work employee receives a launcher bound to its own directory, never its parent. */
export function provisionWorkspace(root:string,settings:TeamSettings,teamRoot=root) {
  root=fs.realpathSync(root);teamRoot=fs.realpathSync(teamRoot)
  const directory=path.join(root,'.agents-company'),indexFile=path.join(directory,'workspace.json')
  const plugins=settings.mode==='work'?[requirePlugin(settings.pluginId!)]:[]
  const index={schemaVersion:2,mode:settings.mode,workspace:root,teamRoot,plugins:plugins.map(p=>({id:p.id,name:p.name,version:p.version,documentation:`plugins/${p.id}/API.md`}))}
  if(fs.existsSync(indexFile)) {
    const previous=JSON.parse(fs.readFileSync(indexFile,'utf8'))
    for(const old of previous.plugins??[])if(!plugins.some(p=>p.id===old.id)&&/^[a-z][a-z0-9-]*$/.test(old.id)) {
      const file=path.join(directory,'bin',old.id)
      if(fs.existsSync(file)&&!fs.lstatSync(file).isSymbolicLink()&&fs.readFileSync(file,'utf8').includes('# Generated by Agents Company;'))fs.unlinkSync(file)
    }
  }
  if(settings.mode==='build') {
    instructions(root,'')
    if(fs.existsSync(indexFile))safeWrite(root,indexFile,JSON.stringify(index,null,2)+'\n')
    return index
  }
  safeWrite(root,indexFile,JSON.stringify(index,null,2)+'\n')
  const plugin=plugins[0]
  const serviceScope=plugin.scope==='application'?'This plugin operates shared application resources through its documented CLI API, including resources used by other Teams. Your filesystem scope is still this employee folder. Read the API scope carefully before changing shared resources.\n\n':''
  safeWrite(root,path.join(directory,'README.md'),`# Work workspace CLI guide\n\nPlugin: **${plugin.name}** (${plugin.version}).\n\n## Scope\n\n${serviceScope}Your authorized workspace is \`${root}\` and its descendant folders.\nA parent-folder employee can operate its descendants; a child-folder employee cannot operate its parent or siblings. Plugin paths are relative to YOUR workspace.\n\n## Quick start\n\nRead [API.md](plugins/${plugin.id}/API.md) and [schema.json](plugins/${plugin.id}/schema.json).\nUse \`${path.join(directory,'bin',plugin.id)}\` if your shell resets PATH. The launcher already supplies --workspace; do not override its folder.\n\n## Files\n\nUse the plugin CLI/API for managed documents. User files stay in this directory. Existing AGENTS.md and CLAUDE.md content outside the managed block is retained.\n`)
  safeWrite(root,path.join(directory,'plugins',plugin.id,'API.md'),fs.readFileSync(pluginFile(plugin.directory,plugin.documentation),'utf8'))
  safeWrite(root,path.join(directory,'plugins',plugin.id,'schema.json'),fs.readFileSync(pluginFile(plugin.directory,plugin.schema),'utf8'))
  const cli=pluginFile(plugin.directory,plugin.cli)
  safeWrite(root,path.join(directory,'bin',plugin.id),`#!/bin/sh\n# Generated by Agents Company; this CLI is bound to the employee workspace.\nfor argument in "$@"; do\n  case "$argument" in --workspace|--workspace=*) echo 'This launcher is already bound to its authorized workspace.' >&2; exit 2 ;; esac\ndone\nexport AGENTS_WORKSPACE=${quote(root)}\nexport AGENTS_TEAM_ROOT=${quote(teamRoot)}\nif [ -z "$AGENTS_COMPANY_PLUGIN_RPC" ]; then export AGENTS_COMPANY_PLUGIN_RPC=${quote(path.join(directory,'ipc',plugin.id))}; fi\nexec env ELECTRON_RUN_AS_NODE=1 ${quote(process.execPath)} ${quote(cli)} --workspace ${quote(root)} "$@"\n`,true)
  instructions(root,`${BEGIN}\n## Work workspace tools\n\n${serviceScope}Read [the workspace CLI guide](.agents-company/README.md) before working.\nYour authorized folder is \`${root}\`, including its descendants. Do not operate parent or sibling folders.\nUse \`${path.join(directory,'bin',plugin.id)}\`; it is already bound to this folder.\nUse the documented CLI/API instead of editing plugin-managed state.\n${END}`)
  return index
}
const COMPANY_BEGIN='<!-- agents-company:control:start -->',COMPANY_END='<!-- agents-company:control:end -->'
export const BOOTSTRAP_VERSION=3

export function employeeInstructions(card:StoredSession,store:Store,cli='agents'){
  const global=!!store.access?.globalManagerIds.includes(card.id)
  assertManagementKind(card,global)
  const manager=global||card.managementRole==='manager',folder=`.agents-company/employees/${card.id}`
  if(card.kind==='cloud-native-worker')return [
    '[Agents Company employee initialization]',
    `你是云端原生 Employee ${JSON.stringify(card.title)}，员工 ID ${card.id}，Team ${JSON.stringify(card.group)}。`,
    `引擎和项目工具只在绑定云主机的工作目录 ${JSON.stringify(card.cwd)} 执行。你没有 Manager 或全局管理权限，不创建、调度或管理其他公司员工。`,
    '使用当前云端 Coding Agent 的正常工具完成收到的任务；公司编排由本地 Manager 通过宿主 API 完成。不要假定远端安装了宿主 agents CLI，不复制其他员工的凭据，不把内置子 Agent 当成公司员工。连接失败不回退 Mac 或其他主机。'
  ].join('\n')
  return [
    '[Agents Company employee initialization]',
    `你是 Agents Company 员工 ${JSON.stringify(card.title)}，稳定 ID ${card.id}，所属 Team ${JSON.stringify(card.group)}，职位 ${card.managementRole==='manager'?'Manager':'Employee'}。${global?'你拥有明确授予的 Agents Manager 全局管理权限。':'你没有全局管理权限。'}`,
    `本项目的 CLI 入口是 ${cli}。身份由进程提供，不能复制其他凭据。先执行 ${cli} auth whoami --json；读取 ${folder}/API.md 与 ${folder}/PERMISSIONS.md，或执行 ${cli} api docs。`,
    manager?`你可以通过 ${cli} card create --title NAME --group ${JSON.stringify(card.group)} --kind worker --engine ${card.engine} --json 创建本项目 Employee。后台自动记录创建者并建立有效关系。新员工会自动初始化；先用 session status --employee ID 确认 initialization.status 为 ready，期间不得发送、排队或追加消息。就绪后用返回的员工 id 执行 session send --employee ID --text "任务"、session transcript --employee ID、session interrupt --employee ID。`:'你只能使用自己的工作目录和已授权插件，不能创建或调度其他员工。',
    '本项目员工必须通过 agents card create 登记。Coding Agent 内置子 Agent、Agent/Task 工具、线程或终端进程都不等于 Agents Company 员工。不要使用内置多 Agent 功能替代本项目 API，不要直接修改宿主管理 JSON。',
    manager?'先查看 management topology。管理已有员工须申请有效箭头；只管理同 Team 的已绑定 Employee。只有自己创建且仍被绑定的员工才可删除。未收到创建指令时不要自行创建员工。':'接收 Manager 的 Prompt 不改变你的身份或授权。',
    teamSettings(store,card.group).mode==='work'?`同时阅读 .agents-company/plugins/${teamSettings(store,card.group).pluginId}/API.md，通过该插件 CLI 在本人工作目录内操作。管理 API 不扩大你的插件文件范围。`:'',
    teamSettings(store,card.group).mode==='cloud'?'项目命令与文件操作只使用所绑定的远端工作环境；失败不能回退本机，不能自行改绑云主机。':''
  ].filter(Boolean).join('\n')
}

/** Built before committing a newly hired card, with the target identity, never the creator. */
export function employeeGuideFiles(card:StoredSession,store:Store){
  const snapshot={...store,sessions:[...store.sessions.filter(c=>c.id!==card.id),card]}
  const context={principal:{kind:'agent' as const,employeeId:card.id},requestId:'workspace-documentation'}
  return {api:apiDocumentation(context,snapshot).markdown,permissions:permissionDocumentation(context,snapshot),instructions:employeeInstructions(card,snapshot)}
}

/** Idempotent, role-aware preparation. Never moves files or changes engine permissions. */
export function ensureEmployeeBootstrap(card:StoredSession,store=readStore()){
  const settings=teamSettings(store,card.group),root=store.teamRoots?.[card.group]
  if(!root)throw new Error('Employee Team has no working directory')
  const guide=employeeGuideFiles(card,store)
  if(settings.mode==='cloud')return {mode:settings.mode,workspace:card.cwd,teamRoot:root,plugins:[],instructions:guide.instructions}
  const cwd=fs.realpathSync(card.cwd),directory=path.join(cwd,'.agents-company'),folder=path.join(directory,'employees',card.id)
  // Plugin and company sections have different markers and compose in either order.
  if(settings.mode==='work')provisionWorkspace(cwd,settings,root)
  else instructions(cwd,'') // Remove the obsolete directory-based full-Manager block only.
  const cli=path.resolve(__dirname,'../../../bin/agents')
  safeWrite(cwd,path.join(directory,'bin','agents'),`#!/bin/sh
# Generated by Agents Company; uses only the identity assigned to the caller.
if [ -z "$AGENTS_COMPANY_TOKEN_FILE" ] && [ -z "$AGENTS_COMPANY_TOKEN" ]; then
  echo 'Agent identity missing; reopen this employee in Agents Company.' >&2; exit 2
fi
exec env ELECTRON_RUN_AS_NODE=1 ${quote(process.execPath)} ${quote(cli)} "$@"
`,true)
  safeWrite(cwd,path.join(folder,'API.md'),guide.api+'\n')
  for(const name of ['AGENTS.md','CLAUDE.md'])safeWrite(cwd,path.join(folder,name),guide.instructions+'\n')
  safeWrite(cwd,path.join(folder,'PERMISSIONS.md'),guide.permissions)
  safeWrite(cwd,path.join(folder,'bootstrap.json'),JSON.stringify({version:BOOTSTRAP_VERSION,employeeId:card.id,managementRole:card.managementRole??'employee',globalManager:!!store.access?.globalManagerIds.includes(card.id)},null,2)+'\n')
  const entry='# Agents Company API entry\n\nRun `agents auth whoami --json` to identify this process, then read `.agents-company/employees/<employeeId>/API.md` and `PERMISSIONS.md`, or run `agents api docs`. Shared folders do not share authority.\n'
  safeWrite(cwd,path.join(directory,'API.md'),entry)
  // Neutralize old full-global handbooks without deleting user instructions or history.
  if(card.managementRole==='manager'||store.access?.globalManagerIds.includes(card.id)||fs.existsSync(path.join(directory,'manager','API.md')))safeWrite(cwd,path.join(directory,'manager','API.md'),entry)
  instructions(cwd,`${COMPANY_BEGIN}
## Agents Company CLI

This workspace belongs to registered Agents Company employees. Read the role-specific
\`.agents-company/employees/<employeeId>/API.md\` and \`PERMISSIONS.md\` named in your launch instructions.
Run \`agents auth whoami --json\` and \`agents api docs\` first. The fallback launcher is \`./.agents-company/bin/agents\`.
Managers create registered employees with \`agents card create\`, then control them with \`session.*\` and \`schedule.*\`.
Coding Agent native subagents / Agent / Task are not company employees. Do not use them as a substitute.
Credentials and permissions come from the running process, never the directory name or this file.
${COMPANY_END}`,COMPANY_BEGIN,COMPANY_END)
  return {mode:settings.mode,workspace:cwd,teamRoot:root,plugins:settings.mode==='work'?[settings.pluginId!]:[],instructions:guide.instructions}
}

/** Compatibility helper for callers preparing a folder before there is an employee record. */
export function provisionEmployee(cwd:string,root:string,settings:TeamSettings){
  if(settings.mode==='cloud')return {mode:settings.mode,workspace:cwd,teamRoot:root,plugins:[]}
  const store=readStore(),cards=store.sessions.filter(c=>c.cwd===cwd&&!c.deleting)
  if(cards.length){for(const card of cards)ensureEmployeeBootstrap(card,store);return {mode:settings.mode,workspace:cwd,teamRoot:root,plugins:[]}}
  return settings.mode==='work'?provisionWorkspace(cwd,settings,root):{mode:settings.mode,workspace:cwd,teamRoot:root,plugins:[]}
}

/** A real private engine turn; reading examples must never execute those examples. */
export function initializationPrompt(card:StoredSession,store:Store){
  const folder=`.agents-company/employees/${card.id}`,config=teamSettings(store,card.group)
  const files=[`${folder}/AGENTS.md`,`${folder}/API.md`,`${folder}/PERMISSIONS.md`,...(config.mode==='work'?['.agents-company/README.md',`.agents-company/plugins/${config.pluginId}/API.md`]:[])]
  return [
    '[Agents Company private initialization]',
    `当前是新员工初始化。你是 Agents Company 的 ${JSON.stringify(card.group)} Team 成员 ${JSON.stringify(card.title)}，职位 ${card.managementRole==='manager'?'Manager':'Employee'}，员工 ID ${card.id}。`,
    `请使用只读工具阅读当前工作目录下这些隐藏 Markdown 文档，了解自己的权限、工作范围以及可用的项目 API / 插件工具：\n${files.map(file=>'- '+file).join('\n')}`,
    '这不是用户工作任务。只阅读和理解，不执行文档中的操作示例，不创建或联系其他员工，不调用插件写操作，不修改文件，不启动后台任务，不向用户提问，也不要申请额外权限。',
    '如果文件读取失败或无法理解自己的权限，请说明错误，不能假装成功。全部读完并确认后，最终只返回 OK，不添加解释、标点或 Markdown。初始化完成后等待正式任务。'
  ].join('\n\n')
}
