import {useConversationListMotion} from './useConversationListMotion'
import {useEffect,useRef,useState} from 'react'
import {Icon} from '../components/Icon'
import {useDialogFocus} from '../office/useDialogFocus'
import {translate as uiText,useI18n} from '../i18n'
import {audioKey,useAudioPlayback} from './AudioPlayback'
import {mediaTime} from './mediaPresentation'
import {useSurfaceMotion} from './surfaceMotion'

function AudioQueue({onClose}:{onClose:()=>void}){
 useI18n();const player=useAudioPlayback()!,surface=useSurfaceMotion<HTMLDivElement>('panel'),drag=useRef<number|null>(null)
 const list=useConversationListMotion(JSON.stringify(player.state.queue.map(audioKey)),'data-audio-key')
 useDialogFocus('.audio-queue-panel',true)
 useEffect(()=>{const outside=(event:PointerEvent)=>{if(!(event.target as Element).closest('.audio-queue-panel,[data-audio-queue-trigger]'))onClose()},key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();onClose()}};document.addEventListener('pointerdown',outside,true);window.addEventListener('keydown',key,true);return()=>{document.removeEventListener('pointerdown',outside,true);window.removeEventListener('keydown',key,true)}},[onClose])
 return <div ref={surface} className="audio-queue-panel" role="dialog" aria-label={uiText('Audio queue')}><header><div><h2>{uiText('Audio queue')} <span>{player.state.queue.length}</span></h2></div><button aria-label={uiText('Close audio queue')} onClick={onClose}><Icon name="close"/></button></header><div ref={list} className="audio-queue-list" role="list">{player.state.queue.map((item,index)=>{const key=audioKey(item),active=key===player.state.active;return <div key={key} data-audio-key={key} role="listitem" className={'audio-queue-item'+(active?' active':'')} draggable onDragStart={event=>{drag.current=index;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('application/x-agents-audio',String(index))}} onDragOver={event=>{if(drag.current!==null){event.preventDefault();event.dataTransfer.dropEffect='move'}}} onDrop={event=>{event.preventDefault();if(drag.current!==null)player.reorder(drag.current,index);drag.current=null}} onDragEnd={()=>{drag.current=null}}><span className="audio-queue-grip" aria-hidden="true"><Icon name="gripper"/></span><button className="audio-queue-track" aria-label={uiText('Play {0}',[item.name])} aria-current={active?'true':undefined} onClick={()=>player.choose(item)}><span className="audio-queue-mark"><Icon name={active&&player.state.playing?'unmute':'play'}/></span><span><strong>{item.name}</strong><small>{player.titleFor(item.conversation)}</small></span></button><div className="audio-queue-actions"><button disabled={index===0} aria-label={uiText('Move {0} earlier',[item.name])} onClick={()=>player.move(key,-1)}><Icon name="chevron-up"/></button><button disabled={index===player.state.queue.length-1} aria-label={uiText('Move {0} later',[item.name])} onClick={()=>player.move(key,1)}><Icon name="chevron-down"/></button><button aria-label={uiText('Remove {0} from queue',[item.name])} onClick={()=>player.remove(key)}><Icon name="close"/></button></div></div>})}</div><footer><label className="audio-queue-volume"><Icon name={player.state.muted?'mute':'unmute'}/><input type="range" min={0} max={1} step={.05} value={player.state.muted?0:player.state.volume} aria-label={uiText('Audio queue volume')} onChange={event=>player.volume(Number(event.target.value))}/></label><span>{uiText('Drag to reorder, or use the arrow buttons.')}</span><button onClick={()=>{player.stop();onClose()}}>{uiText('Clear audio queue')}</button></footer></div>
}
function ActiveDock(){
 useI18n();const player=useAudioPlayback()!,state=player.state,track=player.selected!,[queue,setQueue]=useState(false),surface=useSurfaceMotion<HTMLDivElement>('strip'),index=state.queue.findIndex(item=>audioKey(item)===state.active)
 return <div ref={surface} className="audio-dock" role="region" aria-label={uiText('Audio player')} onKeyDown={event=>{if(event.key==='Escape'){event.stopPropagation();setQueue(false)}}}>
  <div className="audio-dock-controls"><button aria-label={uiText('Previous audio')} disabled={index<=0&&state.repeat!=='all'&&state.current<=3} onClick={()=>player.step(-1)}><Icon name="chevron-left"/></button><button className="audio-dock-play" aria-label={uiText(state.playing?'Pause audio':'Resume audio')} onClick={player.toggle}><Icon name={state.loading?'loading':state.playing?'debug-pause':'play'}/></button><button aria-label={uiText('Next audio')} disabled={index===state.queue.length-1&&state.repeat!=='all'} onClick={()=>player.step(1)}><Icon name="chevron-right"/></button></div>
  <button className="audio-dock-source" aria-label={uiText('Go to playing message')} title={uiText('Go to playing message')} onClick={player.reveal}><strong>{track.name}</strong><span>{player.titleFor(track.conversation)}</span></button>
  <label className="audio-dock-progress" style={{'--audio-progress':(state.duration?state.current/state.duration*100:0)+'%'} as React.CSSProperties}><input type="range" min={0} max={state.duration||1} step={.1} value={Math.min(state.current,state.duration||1)} disabled={!state.duration} aria-label={uiText('Audio playback position')} onChange={event=>player.seek(Number(event.target.value))}/><output aria-label={uiText('Audio playback time')}>{mediaTime(state.current)} <span>/ {state.duration?mediaTime(state.duration):'—'}</span></output></label>
  <div className="audio-dock-actions"><button className="audio-dock-speed" aria-label={uiText('Playback speed {0}',[state.rate+'×'])} onClick={player.speed}>{state.rate}×</button><button className="audio-dock-repeat" aria-label={uiText(state.repeat==='off'?'Repeat off':state.repeat==='all'?'Repeat queue':'Repeat one')} aria-pressed={state.repeat!=='off'} onClick={player.repeat}><Icon name="sync"/>{state.repeat==='one'&&<small>1</small>}</button><button className="audio-dock-mute" aria-label={uiText(state.muted?'Unmute audio':'Mute audio')} onClick={player.mute}><Icon name={state.muted||state.volume===0?'mute':'unmute'}/></button><button data-audio-queue-trigger aria-label={uiText('Show audio queue')} aria-expanded={queue} onClick={()=>setQueue(!queue)}><Icon name="list-ordered"/><span>{state.queue.length}</span></button><button aria-label={uiText('Stop audio and clear queue')} onClick={player.stop}><Icon name="close"/></button></div>
  {state.error&&<div className="audio-dock-error" role="alert">{uiText(state.error)} <button onClick={player.retry}>{uiText('Retry playback')}</button></div>}
  {queue&&<AudioQueue onClose={()=>setQueue(false)}/>}
 </div>
}
export function AudioDock(){const player=useAudioPlayback();return player?.selected?<ActiveDock/>:null}
