import {useEffect,useRef,useState,type FormEvent} from 'react'
import type {ContractClient} from '../../Contract/protocol'
import type {WorkflowView,WorkflowFile} from '../../Contract/workflow'
import {deliveryZip} from './delivery.mjs'
import './style.css'

type Question={id:string;prompt:string;recommended:string}
const labels:Record<string,string>={running:'研究进行中',waiting:'等待你的意见',completed:'已完成',failed:'需要处理',cancelled:'已停止'}
const phases=[['scope','目标'],['plan','方案'],['direction','确认'],['research','搜证'],['focus','重点'],['review','审查'],['write','报告'],['complete','交付']]
const taskLabel:Record<string,string>={queued:'已准备',running:'执行中',approval:'等待审批',completed:'已完成',failed:'未完成'}
function Mark(){return <svg width="32" height="32" viewBox="0 0 32 32" fill="none" aria-hidden="true"><circle cx="14" cy="14" r="9" stroke="currentColor" strokeWidth="2"/><path d="m21 21 7 7M9 15l3-4 4 6 4-6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export default function Page({client}:{client:ContractClient}){
 const [job,setJob]=useState<WorkflowView|null>(null),[history,setHistory]=useState<WorkflowView[]>([]),[loading,setLoading]=useState(true),[topic,setTopic]=useState(''),[engines,setEngines]=useState<string[]>([]),[values,setValues]=useState<Record<string,string>>({}),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[catalogWarning,setCatalogWarning]=useState(''),[preview,setPreview]=useState(''),[confirmStop,setConfirmStop]=useState(false)
 const attempt=useRef<{body:string;key:string}|null>(null),alive=useRef(true)
 useEffect(()=>{alive.current=true;let current=true;void client.invoke<{jobs:WorkflowView[];errors?:{id:string;error:string}[]}>('workflow.list',{engineId:'deep-research'}).then(({jobs,errors})=>{if(!current)return;if(errors?.length)setCatalogWarning('有 '+errors.length+' 项工作流记录无法读取；原始数据已保留，其他研究仍可继续。记录：'+errors.map(e=>e.id).join('、'));setHistory(jobs);setJob(jobs.find(j=>j.status==='running'||j.status==='waiting')??jobs[0]??null)}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{alive.current=false;current=false}},[client])
 const refresh=async(id=job?.id)=>{if(!id)return;const next=await client.invoke<WorkflowView>('workflow.get',{id});if(alive.current){setJob(next);setHistory(old=>[next,...old.filter(j=>j.id!==id)].sort((a,b)=>b.createdAt-a.createdAt))}return next}
 useEffect(()=>{if(!job||['completed','failed','cancelled'].includes(job.status))return;let current=true,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const next=await client.invoke<WorkflowView>('workflow.get',{id:job.id});if(current){setJob(next);setError('')}}catch(e){if(current)setError((e as Error).message)}finally{if(current)timer=setTimeout(poll,900)}};timer=setTimeout(poll,600);return()=>{current=false;clearTimeout(timer)}},[job?.id,job?.status,client])
 useEffect(()=>{setValues({});setNote('');setPreview('');setConfirmStop(false)},[job?.id,job?.summary.phase])
 const keyFor=(operation:string,payload:unknown)=>{const body=JSON.stringify([operation,payload]);if(attempt.current?.body!==body)attempt.current={body,key:crypto.randomUUID()};return attempt.current.key}
 const operate=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await work()}catch(e){if(alive.current){setError((e as Error).message);await refresh().catch(()=>{})}}finally{if(alive.current)setBusy(false)}}
 const start=(event:FormEvent)=>{event.preventDefault();void operate(async()=>{if(engines.length===1)throw Error('请选择至少两种 Coding Agent，或者取消选择以自动匹配。');const input={topic:topic.trim(),...(engines.length?{engines:engines.map(engine=>({engine}))}:{})};const next=await client.invoke<WorkflowView>('workflow.start',{engineId:'deep-research',input,clientRequestId:keyFor('start',input)});setJob(next);setHistory(old=>[next,...old.filter(j=>j.id!==next.id)])})}
 const answer=(defaults=false)=>void operate(async()=>{if(!job)return;const payload={id:job.id,expectedRevision:job.revision,answer:{values:defaults?{}:values,note:defaults?'':note}};setJob(await client.invoke<WorkflowView>('workflow.respond',{...payload,clientRequestId:keyFor('answer',payload)}))})
 const resume=()=>void operate(async()=>{if(!job)return;const payload={id:job.id,expectedRevision:job.revision};setJob(await client.invoke<WorkflowView>('workflow.resume',{...payload,clientRequestId:keyFor('resume',payload)}))})
 const file=async(name:string)=>client.invoke<WorkflowFile&{content:string}>('workflow.file',{id:job!.id,name})
 const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
 const downloadOne=(name:string)=>void operate(async()=>{const result=await file(name);download(new Blob([result.content],{type:result.mediaType+';charset=utf-8'}),result.name)})
 const downloadAll=()=>void operate(async()=>{const files=await Promise.all(job!.files.map(f=>file(f.name)));download(new Blob([deliveryZip(files)],{type:'application/zip'}),'deep-research-'+job!.id.slice(-8)+'.zip')})
 const newTask=()=>{attempt.current=null;setJob(null);setTopic('');setError('');setPreview('')}
 const summary=job?.summary,questions:Question[]=summary?.questions??[],phaseIndex=phases.findIndex(([id])=>id===summary?.phase)
 return <div className="a-dr" data-research-status={job?.status??'new'}>
  <header className="a-dr-header"><div className="a-dr-brand"><span className="a-dr-logo"><Mark/></span><div><strong>deep-research</strong><small>多引擎 · 可追溯研究</small></div></div><div className="a-dr-head-actions">{job&&<button onClick={()=>void operate(async()=>{await refresh()})} disabled={busy} aria-label="刷新调研状态">刷新</button>}<button onClick={newTask} disabled={busy} className="a-dr-outline">新调研 <span aria-hidden="true">＋</span></button></div></header>
  {(error||catalogWarning)&&<div className="a-dr-error" role="alert">{error||catalogWarning}<button onClick={()=>{setError('');setCatalogWarning('')}} aria-label="关闭调研错误">×</button></div>}
  {loading?<div className="a-dr-empty" role="status">正在读取研究记录…</div>:!job?<main className="a-dr-intake"><div className="a-dr-eyebrow">FROM QUESTION TO EVIDENCE</div><h1>从一个问题开始。<br/><span>研究到可以判断。</span></h1><p>先确认你的目标，再让不同 Coding Agent 独立搜证、交叉审查。<br/>最后只交付报告与证据文件。</p><form onSubmit={start}><label htmlFor="research-topic">你想调研什么？</label><textarea id="research-topic" aria-label="调研任务" value={topic} onChange={e=>setTopic(e.target.value)} maxLength={4000} required placeholder="例如：调研面向个人开发者的本地 AI 编程工具，比较能力、成本、隐私与成熟度。" rows={4}/><div className="a-dr-intake-bottom"><span>三轮意见确认 · 至少两类引擎 · 最终文件交付</span><button className="a-dr-primary" disabled={busy||!topic.trim()} type="submit">{busy?'正在创建…':'开始调研'} <span aria-hidden="true">→</span></button></div><details className="a-dr-config"><summary>引擎选择 <span>默认自动匹配已就绪的两类</span></summary><div>{['codex','claude','cline','pi'].map(engine=><label key={engine}><input type="checkbox" checked={engines.includes(engine)} onChange={()=>setEngines(old=>old.includes(engine)?old.filter(e=>e!==engine):[...old,engine])}/>{engine==='claude'?'Claude':engine[0].toUpperCase()+engine.slice(1)}</label>)}</div><small>研究任务使用你已配置的模型。权限请求仍由 Infra 审批，不会自动安装软件或提高权限。</small></details></form><div className="a-dr-how"><article><b>01</b><strong>确认问题</strong><span>目标、边界与真正要做的决定</span></article><article><b>02</b><strong>独立搜证</strong><span>两条路线并行，主动寻找反证</span></article><article><b>03</b><strong>核验交付</strong><span>网页摘录、交叉审查与最终引用</span></article></div>{history.length>0&&<section className="a-dr-history"><h2>最近的调研</h2>{history.slice(0,8).map(item=><button key={item.id} onClick={()=>void operate(async()=>{await refresh(item.id)})}><span>{item.summary.title}</span><small>{labels[item.status]}</small></button>)}</section>}</main>:<main className="a-dr-project">
   <div className="a-dr-project-title"><div><div className="a-dr-eyebrow">RESEARCH WORKSPACE</div><h1>{summary?.title}</h1><p>{summary?.topic!==summary?.title?summary?.topic:'范围、证据、分歧与最终决策，保存在同一项研究中。'}</p></div><span className={'a-dr-status '+job.status}>{labels[job.status]}</span></div>
   <ol className="a-dr-phases" aria-label="调研流程">{phases.map(([id,label],i)=><li key={id} data-current={i===phaseIndex} data-done={i<phaseIndex}><span>{i<phaseIndex?'✓':i+1}</span>{label}</li>)}</ol>
   <div className="a-dr-workspace"><div className="a-dr-main">
    {job.status==='waiting'&&<section className="a-dr-card a-dr-questions"><div className="a-dr-section-heading"><div><small>YOUR INPUT / {summary?.round}</small><h2>{summary?.phase==='scope'?'先确认研究目标':summary?.phase==='direction'?'确认研究方案':'最后确认报告重点'}</h2></div><span>第 {summary?.round} 轮</span></div>{summary?.plan&&<div className="a-dr-plan"><p>{summary.plan.objective}</p>{summary.plan.tracks.map((track:string,i:number)=><p key={i}><b>路线 {i+1}</b> {track}</p>)}<details><summary>验收标准</summary>{summary.plan.successCriteria.map((criterion:string,i:number)=><p key={i}>{criterion}</p>)}</details></div>}{summary?.findings&&<div className="a-dr-plan"><strong>待核准的初步发现</strong>{summary.findings.slice(0,3).map((f:any,i:number)=><p key={i}>{f.statement} <small>{f.sourceIds.join(' · ')}</small></p>)}</div>}<form onSubmit={event=>{event.preventDefault();answer()}}>{questions.map(q=><label className="a-dr-question" key={q.id}><strong>{q.prompt}</strong><textarea aria-label={q.prompt} data-question={q.id} value={values[q.id]??''} placeholder={q.recommended} onChange={event=>setValues(old=>({...old,[q.id]:event.target.value}))} rows={3}/><small>留空采用建议：{q.recommended}</small></label>)}<label className="a-dr-question"><strong>其他意见 <span>可选</span></strong><textarea aria-label="其他调研意见" rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="希望增加、排除或特别关注的内容"/></label><div className="a-dr-form-actions"><button type="button" disabled={busy} onClick={()=>answer(true)}>全部采用建议</button><button type="submit" disabled={busy} className="a-dr-primary" aria-label="确认并继续">{busy?'正在提交…':'确认并继续'} <span aria-hidden="true">→</span></button></div></form></section>}
    {job.status==='running'&&<section className="a-dr-card a-dr-running" aria-live="polite"><span className="a-dr-pulse"/><div><small>CORE WORKFLOW</small><h2>{summary?.phaseLabel}</h2><p>不同研究员在各自原生会话中工作。可以离开本页；Core 会继续执行并保存进度。</p>{summary?.attention&&<div className="a-dr-attention"><p>{summary.attention.message}</p><button className="a-dr-outline" onClick={()=>void operate(async()=>{await client.invoke('view.open',{kind:'conversation',employee:summary.attention.employeeId})})}>前往 Infra 审批</button></div>}</div></section>}
    {job.status==='failed'&&<section className="a-dr-card a-dr-failure"><h2>研究停在需要处理的步骤</h2><p role="alert">{job.error}</p><p>已完成的步骤与证据仍保留。未通过审查的报告不会出现在下载区。</p><button className="a-dr-primary" onClick={resume} disabled={busy}>从检查点重试</button></section>}
    {job.status==='cancelled'&&<section className="a-dr-card"><h2>调研已停止</h2><p>未发布中间稿。研究记录保留；其他员工任务不会被中断。</p>{job.error&&<p role="alert">{job.error}</p>}<button onClick={newTask}>开始新的调研</button></section>}
    {job.status==='completed'&&<section className="a-dr-card a-dr-delivery"><div className="a-dr-section-heading"><div><small>FINAL DELIVERY</small><h2>研究完成，最终文件已就绪。</h2></div><span className="a-dr-check">✓</span></div><div className="a-dr-highlights">{(summary?.highlights??[]).map((line:string,i:number)=><p key={i}>{line}</p>)}</div><div className="a-dr-files">{job.files.map(f=><article key={f.name}><span className="a-dr-file-ext">{f.name.split('.').at(-1)?.toUpperCase()}</span><div><strong>{f.name}</strong><p>{f.description}</p><small>{Math.ceil(f.bytes/1024)} KB · SHA-256 已核验</small></div><button disabled={busy} onClick={()=>downloadOne(f.name)} aria-label={'下载 '+f.name}>下载 ↓</button></article>)}</div><div className="a-dr-form-actions"><button disabled={busy} onClick={()=>void operate(async()=>setPreview((await file('research-report.html')).content))}>预览可视化报告</button><button className="a-dr-primary" disabled={busy} onClick={downloadAll} aria-label="下载全部最终文件">下载全部最终文件 <span aria-hidden="true">↓</span></button></div></section>}
    {preview&&<section className="a-dr-preview"><header><strong>最终报告预览</strong><button onClick={()=>setPreview('')} aria-label="关闭最终报告预览">×</button></header><iframe title="深度调研最终报告" srcDoc={preview} sandbox="allow-scripts allow-popups allow-modals"/></section>}
    {(summary?.tasks??[]).length>0&&<details className="a-dr-card a-dr-execution"><summary>执行记录 <span>仅展示步骤与状态，不进入交付文件</span></summary>{summary!.tasks.map((task:any)=><div className="a-dr-task" key={task.id}><span className={'a-dr-task-dot '+task.status}/><span>{task.title}<small>{task.engine}</small></span><b>{taskLabel[task.status]??task.status}</b></div>)}</details>}
   </div><aside className="a-dr-aside"><section className="a-dr-card"><h2>研究团队</h2>{(summary?.workers??[]).length?summary!.workers.map((worker:any)=><div className="a-dr-worker" key={worker.id}><span>{worker.role==='lead'?'L':worker.role==='source'?'S':'C'}</span><div><strong>{worker.role==='lead'?'研究主编':worker.role==='source'?'证据研究员':worker.role==='specialist'?'专题研究员':'反证研究员'}</strong><small>{worker.engine} · 独立原生会话</small></div></div>):<p>确认目标后，自动匹配至少两类已就绪的 Coding Agent。</p>}<div className="a-dr-stats"><div><b>{summary?.sourceCount??0}</b><span>摘录已核验</span></div><div><b>{summary?.domainCount??0}</b><span>来源网站</span></div></div><p className="a-dr-caption">来源数量反映证据规模，不代表结论正确率。关键结论另经独立交叉审查。</p></section><section className="a-dr-card a-dr-output-note"><h3>交付边界</h3><p>交互式报告、可编辑正文、证据表。草稿、抓取缓存和执行日志留在研究内部。</p></section>{!['completed','cancelled'].includes(job.status)&&<div className="a-dr-stop">{confirmStop?<><p>停止此项调研？将仅取消它拥有的当前任务。</p><button onClick={()=>setConfirmStop(false)}>继续研究</button><button onClick={()=>void operate(async()=>{setJob(await client.invoke<WorkflowView>('workflow.cancel',{id:job.id}));setConfirmStop(false)})} disabled={busy}>确认停止</button></>:<button onClick={()=>setConfirmStop(true)}>停止调研</button>}</div>}{history.length>1&&<details className="a-dr-history"><summary>其他调研</summary>{history.filter(h=>h.id!==job.id).slice(0,7).map(h=><button key={h.id} onClick={()=>void operate(async()=>{await refresh(h.id)})}><span>{h.summary.title}</span><small>{labels[h.status]}</small></button>)}</details>}</aside></div>
  </main>}
 </div>
}
