import {useEffect,useRef,useState,type FormEvent} from 'react'
import type {ContractClient} from '../../Contract/protocol'
import type {WorkflowView,WorkflowFile,WorkflowRead} from '../../Contract/workflow'
import {deliveryZip} from './delivery.mjs'
import {ResearchOptions,ResearchMonitor,EvidenceExplorer,ReportPreview,initialConfig,policyInput,type ResearchConfig} from './Workspace'
import './style.css'
import './workspace.css'

type Question={id:string;prompt:string;recommended:string}
const labels:Record<string,string>={running:'研究进行中',waiting:'等待你的意见',paused:'已暂停',completed:'已完成',failed:'需要处理',cancelled:'已停止'}
const phases=[['scope','目标'],['plan','方案'],['direction','确认'],['research','搜证'],['focus','重点'],['review','审查'],['write','报告'],['complete','交付']]
const taskLabel:Record<string,string>={queued:'已准备',running:'执行中',approval:'等待审批',completed:'已完成',failed:'未完成',paused:'已暂停'}
function Mark(){return <svg width="32" height="32" viewBox="0 0 32 32" fill="none" aria-hidden="true"><circle cx="14" cy="14" r="9" stroke="currentColor" strokeWidth="2"/><path d="m21 21 7 7M9 15l3-4 4 6 4-6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export default function Page({client}:{client:ContractClient}){
 const [job,setJob]=useState<WorkflowView|null>(null),[history,setHistory]=useState<WorkflowView[]>([]),[loading,setLoading]=useState(true),[topic,setTopic]=useState(''),[engines,setEngines]=useState<string[]>([]),[values,setValues]=useState<Record<string,string>>({}),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[catalogWarning,setCatalogWarning]=useState(''),[preview,setPreview]=useState(''),[confirmStop,setConfirmStop]=useState(false)
 const [config,setConfig]=useState<ResearchConfig>(initialConfig),[models,setModels]=useState<Record<string,string>>({}),[planEdit,setPlanEdit]=useState<any>(null),[amendNote,setAmendNote]=useState(''),[historyQuery,setHistoryQuery]=useState(''),[syncError,setSyncError]=useState(''),[importing,setImporting]=useState(false),[amendConfig,setAmendConfig]=useState<ResearchConfig>(initialConfig)
 const operationLock=useRef(false),navigationEpoch=useRef(0),refreshSequence=useRef(0)
 const attempt=useRef<{body:string;key:string}|null>(null),alive=useRef(true)
 useEffect(()=>{alive.current=true;let current=true;const epoch=navigationEpoch.current;void client.invoke<{jobs:WorkflowView[];errors?:{id:string;error:string}[]}>('workflow.list',{engineId:'deep-research'}).then(({jobs,errors})=>{if(!current)return;if(errors?.length)setCatalogWarning('有 '+errors.length+' 项工作流记录无法读取；原始数据已保留，其他研究仍可继续。记录：'+errors.map(e=>e.id).join('、'));setHistory(jobs);if(navigationEpoch.current===epoch)setJob(jobs.find(j=>j.status==='running'||j.status==='waiting')??jobs[0]??null)}).catch(e=>{if(current)setError(e.message)}).finally(()=>{if(current)setLoading(false)});return()=>{alive.current=false;current=false}},[client])
 const refresh=async(id=job?.id)=>{if(!id)return;const epoch=navigationEpoch.current,sequence=++refreshSequence.current;const next=await client.invoke<WorkflowView>('workflow.get',{id});if(alive.current&&navigationEpoch.current===epoch&&refreshSequence.current===sequence){setJob(old=>old?.id===next.id&&old.revision>next.revision?old:next);setHistory(old=>{const prior=old.find(j=>j.id===id);return [prior&&prior.revision>next.revision?prior:next,...old.filter(j=>j.id!==id)].sort((a,b)=>b.createdAt-a.createdAt)})}return next}
 const revisionRef=useRef(0);revisionRef.current=job?.revision??0
 useEffect(()=>{
  if(!job||['completed','cancelled'].includes(job.status))return
  let current=true,timer:ReturnType<typeof setTimeout>,failures=0,inFlight=false,queued=false
  const schedule=(ms:number)=>{if(!current)return;clearTimeout(timer);timer=setTimeout(()=>void poll(),ms)}
  const poll=async()=>{
   if(inFlight){queued=true;return}
   inFlight=true
   try{
    const next=await client.invoke<WorkflowRead>('workflow.get',{id:job.id,ifRevision:revisionRef.current})
    if(current){failures=0;setSyncError('');if(!('unchanged' in next)){
     setJob(old=>old?.id===next.id&&next.revision>=old.revision?next:old)
     setHistory(old=>old.map(item=>item.id===next.id&&next.revision>=item.revision?next:item))
    }}
   }catch(e){if(current){failures++;setSyncError((e as Error).message)}}
   finally{inFlight=false;if(current){const soon=queued;queued=false;schedule(soon?120:Math.min(15000,5000*2**Math.min(failures,2)))}}
  }
  // Core checkpoints emit scoped workflow:changed events. The slower conditional
  // read is a fallback for disconnected transports, missed events and old clients.
  const unsubscribe=client.watchWorkflow?.(job.id,()=>{if(inFlight)queued=true;else schedule(120)})
  schedule(250);return()=>{current=false;clearTimeout(timer);unsubscribe?.()}
 },[job?.id,job?.status,client])
 useEffect(()=>{
  if(job?.status!=='paused')return
  const policy=job.summary.sourcePolicy??{}
  setAmendConfig({...initialConfig,depth:job.summary.depth??'standard',language:job.summary.language??'zh-CN',allowedDomains:(policy.allowedDomains??[]).join('\n'),preferredDomains:(policy.preferredDomains??[]).join('\n'),excludedDomains:(policy.excludedDomains??[]).join('\n'),seedUrls:(policy.seedUrls??[]).join('\n'),materials:[]})
 },[job?.id,job?.status,job?.summary.amendments?.length])
 useEffect(()=>{setValues({});setNote('');setPreview('');setConfirmStop(false);setAmendNote('');setPlanEdit(job?.summary.plan?structuredClone(job.summary.plan):null)},[job?.id,job?.summary.phase])
 const keyFor=(operation:string,payload:unknown)=>{const body=JSON.stringify([operation,payload]);if(attempt.current?.body!==body)attempt.current={body,key:crypto.randomUUID()};return attempt.current.key}
 const operate=async(work:()=>Promise<void>)=>{if(operationLock.current)return;operationLock.current=true;setBusy(true);setError('');try{await work()}catch(e){if(alive.current){setError((e as Error).message);await refresh().catch(()=>{})}}finally{operationLock.current=false;if(alive.current)setBusy(false)}}
 const start=(event:FormEvent)=>{event.preventDefault();void operate(async()=>{if(importing)throw Error('参考材料仍在读取，请读取完成后提交。');if(engines.length===1)throw Error('请选择至少两种 Coding Agent，或者取消选择以自动匹配。');const input={topic:topic.trim(),depth:config.depth,language:config.language,sourcePolicy:policyInput(config),materials:config.materials,...(engines.length?{engines:engines.map(engine=>({engine,...(models[engine]?.trim()?{model:models[engine].trim()}:{})}))}:{})};const next=await client.invoke<WorkflowView>('workflow.start',{engineId:'deep-research',input,clientRequestId:keyFor('start',input)});setJob(next);setHistory(old=>[next,...old.filter(j=>j.id!==next.id)])})}
 const answer=(defaults=false)=>void operate(async()=>{if(!job)return;const payload={id:job.id,expectedRevision:job.revision,answer:{values:defaults?{}:values,note:defaults?'':note,...(!defaults&&job.summary.phase==='direction'&&planEdit?{plan:planEdit}:{})}};setJob(await client.invoke<WorkflowView>('workflow.respond',{...payload,clientRequestId:keyFor('answer',payload)}))})
 const resume=()=>void operate(async()=>{if(!job)return;const payload={id:job.id,expectedRevision:job.revision};setJob(await client.invoke<WorkflowView>('workflow.resume',{...payload,clientRequestId:keyFor('resume',payload)}))})
 const pause=()=>void operate(async()=>{if(job)setJob(await client.invoke<WorkflowView>('workflow.pause',{id:job.id}))})
 const amend=()=>void operate(async()=>{if(!job)return;const payload={id:job.id,expectedRevision:job.revision,update:{note:amendNote.trim(),sourcePolicy:policyInput(amendConfig),depth:amendConfig.depth}};setJob(await client.invoke<WorkflowView>('workflow.amend',{...payload,clientRequestId:keyFor('amend',payload)}));setAmendNote('')})
 const openWorker=(employee:string)=>void operate(async()=>{await client.invoke('view.open',{kind:'conversation',employee})})
 const file=async(name:string)=>client.invoke<WorkflowFile&{content:string}>('workflow.file',{id:job!.id,name})
 const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
 const downloadOne=(name:string)=>void operate(async()=>{const result=await file(name);download(new Blob([result.content],{type:result.mediaType+';charset=utf-8'}),result.name)})
 const downloadAll=()=>void operate(async()=>{const files=await Promise.all(job!.files.map(f=>file(f.name)));download(new Blob([deliveryZip(files)],{type:'application/zip'}),'deep-research-'+job!.id.slice(-8)+'.zip')})
 const newTask=()=>{navigationEpoch.current++;refreshSequence.current++;attempt.current=null;setJob(null);setTopic('');setConfig({...initialConfig,materials:[]});setSyncError('');setError('');setPreview('')}
 const amendDirty=job?.status==='paused'&&(amendConfig.depth!==(job.summary.depth??'standard')||JSON.stringify(policyInput(amendConfig))!==JSON.stringify(job.summary.sourcePolicy??policyInput(initialConfig)))
 const summary=job?.summary,questions:Question[]=summary?.questions??[],phaseIndex=phases.findIndex(([id])=>id===summary?.phase)
 return <div className="a-dr" data-research-status={job?.status??'new'}>
  <header className="a-dr-header"><div className="a-dr-brand"><span className="a-dr-logo"><Mark/></span><div><strong>deep-research</strong><small>多引擎 · 可追溯研究</small></div></div><div className="a-dr-head-actions">{job&&<button onClick={()=>void operate(async()=>{await refresh()})} disabled={busy} aria-label="刷新调研状态">刷新</button>}<button onClick={newTask} disabled={busy||importing} className="a-dr-outline">新调研 <span aria-hidden="true">＋</span></button></div></header>
  {(error||catalogWarning)&&<div className="a-dr-error" role="alert">{error||catalogWarning}<button onClick={()=>{setError('');setCatalogWarning('')}} aria-label="关闭调研错误">×</button></div>}
  {syncError&&<div className="a-dr-sync-warning" role="status">状态同步暂时中断；保留最后一次确认的进度，正在重新连接。<details><summary>连接详情</summary>{syncError}</details></div>}
  {loading?<div className="a-dr-empty" role="status">正在读取研究记录…</div>:!job?<main className="a-dr-intake"><div className="a-dr-eyebrow">FROM QUESTION TO EVIDENCE</div><h1>从一个问题开始。<br/><span>研究到可以判断。</span></h1><p>先确认你的目标，再让不同 Coding Agent 独立搜证、交叉审查。<br/>最后只交付报告与证据文件。</p><form onSubmit={start}><label htmlFor="research-topic">你想调研什么？</label><textarea id="research-topic" aria-label="调研任务" value={topic} onChange={e=>setTopic(e.target.value)} maxLength={4000} required placeholder="例如：调研面向个人开发者的本地 AI 编程工具，比较能力、成本、隐私与成熟度。" rows={4}/><ResearchOptions value={config} onChange={setConfig} onError={setError} onBusyChange={setImporting} disabled={busy||importing}/><div className="a-dr-intake-bottom"><span>三轮意见确认 · 至少两类引擎 · 最终文件交付</span><button className="a-dr-primary" disabled={busy||importing||!topic.trim()} type="submit">{busy?'正在创建…':'开始调研'} <span aria-hidden="true">→</span></button></div><details className="a-dr-config"><summary>引擎选择 <span>默认自动匹配已就绪的两类</span></summary><div>{['codex','claude','cline','pi'].map(engine=><label key={engine}><input type="checkbox" checked={engines.includes(engine)} onChange={()=>setEngines(old=>old.includes(engine)?old.filter(e=>e!==engine):[...old,engine])}/>{engine==='claude'?'Claude':engine[0].toUpperCase()+engine.slice(1)}</label>)}</div>{engines.length>0&&<div className="a-dr-model-inputs">{engines.map(engine=><label key={engine}>{engine} 模型<input aria-label={engine+' 研究模型'} value={models[engine]??''} maxLength={160} onChange={e=>setModels(old=>({...old,[engine]:e.target.value}))} placeholder="留空使用已配置模型"/></label>)}</div>}<small>研究任务使用你已配置的模型。权限请求仍由 Infra 审批，不会自动安装软件或提高权限。</small></details></form><div className="a-dr-how"><article><b>01</b><strong>确认问题</strong><span>目标、边界与真正要做的决定</span></article><article><b>02</b><strong>独立搜证</strong><span>两条路线并行，主动寻找反证</span></article><article><b>03</b><strong>核验交付</strong><span>网页摘录、交叉审查与最终引用</span></article></div>{history.length>0&&<section className="a-dr-history"><h2>最近的调研</h2><input type="search" aria-label="搜索研究记录" placeholder="搜索研究标题" value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)}/>{history.filter(h=>String(h.summary.title).toLocaleLowerCase().includes(historyQuery.toLocaleLowerCase())).slice(0,12).map(item=><button key={item.id} onClick={()=>void operate(async()=>{await refresh(item.id)})}><span>{item.summary.title}</span><small>{labels[item.status]}</small></button>)}</section>}</main>:<main className="a-dr-project">
   <div className="a-dr-project-title"><div><div className="a-dr-eyebrow">RESEARCH WORKSPACE</div><h1>{summary?.title}</h1><p>{summary?.topic!==summary?.title?summary?.topic:'范围、证据、分歧与最终决策，保存在同一项研究中。'}</p></div><span className={'a-dr-status '+job.status}>{labels[job.status]}</span></div>
   <ol className="a-dr-phases" aria-label="调研流程">{phases.map(([id,label],i)=><li key={id} data-current={i===phaseIndex} data-done={i<phaseIndex}><span>{i<phaseIndex?'✓':i+1}</span>{label}</li>)}</ol>
   <ResearchMonitor job={job} onOpen={openWorker}/><div className="a-dr-workspace"><div className="a-dr-main">
    {job.status==='waiting'&&<section className="a-dr-card a-dr-questions"><div className="a-dr-section-heading"><div><small>YOUR INPUT / {summary?.round}</small><h2>{summary?.phase==='scope'?'先确认研究目标':summary?.phase==='direction'?'确认研究方案':'最后确认报告重点'}</h2></div><span>第 {summary?.round} 轮</span></div>{summary?.phase==='direction'&&summary.plan&&<div className="a-dr-plan"><p>{summary.plan.objective}</p>{summary.plan.tracks.map((track:string,i:number)=><p key={i}><b>路线 {i+1}</b> {track}</p>)}{planEdit&&<details className="a-dr-plan-editor"><summary>编辑研究方案</summary><label>研究目标<textarea aria-label="编辑研究目标" value={planEdit.objective} onChange={e=>setPlanEdit({...planEdit,objective:e.target.value})} maxLength={16000} rows={2}/></label>{planEdit.tracks.map((track:string,i:number)=><label key={i}>独立路线 {i+1}<textarea aria-label={'编辑研究路线 '+(i+1)} value={track} maxLength={2000} rows={2} onChange={e=>setPlanEdit({...planEdit,tracks:planEdit.tracks.map((t:string,j:number)=>i===j?e.target.value:t)})}/></label>)}<small>点击「确认并继续」提交编辑；「全部采用建议」保留原方案。</small></details>}<details><summary>验收标准</summary>{summary.plan.successCriteria.map((criterion:string,i:number)=><p key={i}>{criterion}</p>)}</details></div>}{summary?.phase==='focus'&&summary.findings?.length>0&&<div className="a-dr-plan"><strong>待核准的初步发现</strong>{summary.findings.slice(0,3).map((f:any,i:number)=><p key={i}>{f.statement} <small>{f.sourceIds.join(' · ')}</small></p>)}</div>}<form onSubmit={event=>{event.preventDefault();answer()}}>{questions.map(q=><label className="a-dr-question" key={q.id}><strong>{q.prompt}</strong><textarea aria-label={q.prompt} data-question={q.id} value={values[q.id]??''} placeholder={q.recommended} onChange={event=>setValues(old=>({...old,[q.id]:event.target.value}))} rows={3}/><small>留空采用建议：{q.recommended}</small></label>)}<label className="a-dr-question"><strong>其他意见 <span>可选</span></strong><textarea aria-label="其他调研意见" rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="希望增加、排除或特别关注的内容"/></label><div className="a-dr-form-actions"><button type="button" disabled={busy} onClick={()=>answer(true)}>全部采用建议</button><button type="submit" disabled={busy} className="a-dr-primary" aria-label="确认并继续">{busy?'正在提交…':'确认并继续'} <span aria-hidden="true">→</span></button></div></form></section>}
    {job.status==='running'&&<section className="a-dr-card a-dr-running" aria-live="polite"><span className="a-dr-pulse"/><div><small>CORE WORKFLOW</small><h2>{summary?.phaseLabel}</h2><p>不同研究员在各自原生会话中工作。可以离开本页；Core 会继续执行并保存进度。</p>{!!summary?.approvals?.length?<div className="a-dr-attention" role="status"><strong>{summary.approvals.length} 位研究员等待审批</strong><p>等待期间不占用执行时限；每个原生工具请求仍须单独批准。</p>{summary.approvals.map((approval:any)=><button key={approval.employeeId} className="a-dr-outline" onClick={()=>openWorker(approval.employeeId)}>{approval.title} · 前往审批</button>)}</div>:summary?.attention&&<div className="a-dr-attention"><p>{summary.attention.message}</p><button onClick={()=>openWorker(summary.attention.employeeId)}>前往 Infra 审批</button></div>}</div></section>}
    {job.status==='paused'&&<section className="a-dr-card a-dr-paused"><div className="a-dr-section-heading"><div><small>PAUSED / CHECKPOINT SAVED</small><h2>已暂停，可调整研究方向。</h2></div><span>Ⅱ</span></div><p>已核验的证据和员工身份保留。修订后重新制定方案并进行审查，不直接沿用旧报告结论。</p>{job.error&&<p role="alert">{job.error}</p>}{job.controlPending?<button className="a-dr-primary" disabled={busy} onClick={pause}>重新确认任务已停止</button>:<><label className="a-dr-question"><strong>补充或修改研究要求</strong><textarea aria-label="修订研究方向" value={amendNote} onChange={e=>setAmendNote(e.target.value)} rows={3} maxLength={6000} placeholder="例如：重点比较部署成本，加入反例，暂不讨论企业版。"/></label><ResearchOptions value={amendConfig} onChange={setAmendConfig} onError={setError} disabled={busy} allowMaterials={false}/>{amendDirty&&<p className="a-dr-unsaved">研究范围或深度已更改，请填写修订说明并保存。</p>}<div className="a-dr-form-actions"><button disabled={busy||!amendNote.trim()} onClick={amend}>保存修订</button><button className="a-dr-primary" disabled={busy||!!amendNote.trim()||amendDirty} onClick={resume}>继续研究</button></div><small>未保存的修订不会自动发送；继续研究可能产生已配置服务的模型费用。</small></>}</section>}
    {job.status==='failed'&&<section className="a-dr-card a-dr-failure"><h2>研究停在需要处理的步骤</h2><p role="alert">{job.error}</p><p>已完成的步骤与证据仍保留。未通过审查的报告不会出现在下载区。</p><button className="a-dr-primary" onClick={resume} disabled={busy}>从检查点重试</button></section>}
    {job.status==='cancelled'&&<section className="a-dr-card"><h2>调研已停止</h2><p>未发布中间稿。研究记录保留；其他员工任务不会被中断。</p>{job.error&&<p role="alert">{job.error}</p>}<button onClick={newTask}>开始新的调研</button></section>}
    {job.status==='completed'&&<section className="a-dr-card a-dr-delivery"><div className="a-dr-section-heading"><div><small>FINAL DELIVERY</small><h2>研究完成，最终文件已就绪。</h2></div><span className="a-dr-check">✓</span></div><div className="a-dr-highlights">{(summary?.highlights??[]).map((line:string,i:number)=><p key={i}>{line}</p>)}</div><div className="a-dr-files">{job.files.map(f=><article key={f.name}><span className="a-dr-file-ext">{f.name.split('.').at(-1)?.toUpperCase()}</span><div><strong>{f.name}</strong><p>{f.description}</p><small>{Math.ceil(f.bytes/1024)} KB · SHA-256 已核验</small></div><button disabled={busy} onClick={()=>downloadOne(f.name)} aria-label={'下载 '+f.name}>下载 ↓</button></article>)}</div><div className="a-dr-form-actions"><button disabled={busy} onClick={()=>void operate(async()=>setPreview((await file('research-report.html')).content))}>预览可视化报告</button><button className="a-dr-primary" disabled={busy} onClick={downloadAll} aria-label="下载全部最终文件">下载全部最终文件 <span aria-hidden="true">↓</span></button></div></section>}
    {preview&&<ReportPreview html={preview} onClose={()=>setPreview('')}/>}
    <EvidenceExplorer job={job}/>
    {(summary?.tasks??[]).length>0&&<details className="a-dr-card a-dr-execution"><summary>执行记录 <span>仅展示步骤与状态，不进入交付文件</span></summary>{summary!.tasks.map((task:any)=><div className="a-dr-task" key={task.id}><span className={'a-dr-task-dot '+task.status}/><span>{task.title}<small>{task.engine}</small></span><b>{taskLabel[task.status]??task.status}</b></div>)}</details>}
   </div><aside className="a-dr-aside"><section className="a-dr-card"><h2>研究团队</h2>{(summary?.workers??[]).length?summary!.workers.map((worker:any)=><div className="a-dr-worker" key={worker.id}><span>{worker.role==='lead'?'L':worker.role==='source'?'S':'C'}</span><div><strong>{worker.role==='lead'?'研究主编':worker.role==='source'?'证据研究员':worker.role==='specialist'?'专题研究员':'反证研究员'}</strong><small>{worker.engine} · 独立原生会话</small></div></div>):<p>确认目标后，自动匹配至少两类已就绪的 Coding Agent。</p>}<div className="a-dr-stats"><div><b>{summary?.sourceCount??0}</b><span>摘录已核验</span></div><div><b>{summary?.domainCount??0}</b><span>来源网站</span></div></div><p className="a-dr-caption">来源数量反映证据规模，不代表结论正确率。关键结论另经独立交叉审查。</p></section><section className="a-dr-card a-dr-output-note"><h3>交付边界</h3><p>交互式报告、可编辑正文、证据表。草稿、抓取缓存和执行日志留在研究内部。</p></section>{!['completed','cancelled'].includes(job.status)&&<div className="a-dr-stop">{job.status!=='paused'&&<button className="a-dr-pause-button" disabled={busy} onClick={pause}>暂停并调整</button>}{confirmStop?<><p>停止此项调研？将仅取消它拥有的当前任务。</p><button onClick={()=>setConfirmStop(false)}>继续研究</button><button onClick={()=>void operate(async()=>{setJob(await client.invoke<WorkflowView>('workflow.cancel',{id:job.id}));setConfirmStop(false)})} disabled={busy}>确认停止</button></>:<button onClick={()=>setConfirmStop(true)}>停止调研</button>}</div>}{history.length>1&&<details className="a-dr-history"><summary>其他调研</summary>{history.filter(h=>h.id!==job.id).slice(0,7).map(h=><button key={h.id} onClick={()=>void operate(async()=>{await refresh(h.id)})}><span>{h.summary.title}</span><small>{labels[h.status]}</small></button>)}</details>}</aside></div>
  </main>}
 </div>
}
