import {useMemo,useRef,useState,type PointerEvent} from 'react'
import {clone,round,slideSVG,inspectDeck,layoutSlide} from './scene.mjs'
import type {Deck,Slide,Element} from './types'

type Props={deck:Deck;onChange:(deck:Deck)=>void;disabled:boolean;slideId:string;onSlide:(id:string)=>void;onAI:(id:string,text:string)=>void;onSave:()=>void;dirty:boolean;onUndo:()=>void;onRedo:()=>void;canUndo:boolean;canRedo:boolean}
const uid=()=>crypto.randomUUID().replaceAll('-','').slice(0,14)
const number=(v:string,old:number)=>Number.isFinite(Number(v))?Number(v):old
export function Icon({name,size=18}:{name:string;size?:number}){
 const paths:Record<string,string>={slides:'M4 4h16v12H4z M9 20l3-4 3 4 M12 16v4',plus:'M12 5v14 M5 12h14',download:'M12 3v12 m-5-5 5 5 5-5 M5 16v5h14v-5',arrow:'M4 12h16 m-6-6 6 6-6 6',check:'m5 12 4 4L19 6',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',file:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 16h6',undo:'M9 6 4 11l5 5 M4 11h10a6 6 0 0 1 6 6',redo:'m15 6 5 5-5 5 M20 11h-10a6 6 0 0 0-6 6',copy:'M9 9h12v12H9z M3 15V3h12',trash:'M4 6h16 M9 6V3h6v3 M7 6l1 15h8l1-15 M10 10v7 M14 10v7',up:'m6 14 6-6 6 6',down:'m6 10 6 6 6-6',close:'m6 6 12 12 M18 6 6 18',image:'M3 3h18v18H3z m0 14 6-6 4 4 3-3 5 5 M15 7h.1',text:'M4 4h16 M12 4v16 M8 20h8',grid:'M3 3h18v18H3z M3 9h18 M3 15h18 M9 3v18 M15 3v18',shape:'M4 4h16v16H4z',chart:'M4 3v18h17 M8 17v-5 M13 17V7 M18 17v-8',lock:'M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3',eye:'M2 12c5-9 15-9 20 0-5 9-15 9-20 0z M9 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0',warning:'m12 3 10 18H2z M12 9v5 M12 17h.1'}
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]??paths.slides}/></svg>
}
export default function Editor({deck,onChange,disabled,slideId,onSlide,onAI,onSave,dirty,onUndo,onRedo,canUndo,canRedo}:Props){
 const slide=deck.slides.find(s=>s.id===slideId)??deck.slides[0],index=deck.slides.indexOf(slide),[elementId,setElementId]=useState(''),[tab,setTab]=useState<'object'|'notes'|'check'>('object'),[instruction,setInstruction]=useState(''),[localError,setLocalError]=useState(''),[dataText,setDataText]=useState(''),[dataKey,setDataKey]=useState(''),[dragPreview,setDragPreview]=useState<Deck|null>(null)
 const dragging=useRef<{startX:number;startY:number;deck:Deck;id:string;w:number;h:number;mode:'move'|'resize';target:HTMLElement}|null>(null),previewRef=useRef<Deck|null>(null),reorder=useRef<string|null>(null),viewport=useRef<HTMLDivElement>(null),imageInput=useRef<HTMLInputElement>(null)
 const shown=dragPreview??deck,current=shown.slides.find(s=>s.id===slide.id)??slide,element=current.elements.find(e=>e.id===elementId),quality=useMemo(()=>inspectDeck(deck),[deck]),pageIssues=quality.issues.filter((i:any)=>i.slideId===slide.id),svg=useMemo(()=>slideSVG(shown,current,{interactive:true}),[shown,current])
 const edit=(change:(next:Deck,s:Slide)=>void)=>{if(disabled)return;setLocalError('');const next=clone(deck);change(next,next.slides.find((s:Slide)=>s.id===slide.id)!);onChange(next)}
 const patch=(fields:Partial<Element>)=>edit((_next,s)=>{const e=s.elements.find(v=>v.id===elementId);if(!e||e.locked)return;Object.assign(e,fields);if(e.origin)for(const peer of s.elements)if(peer.id!==e.id&&peer.origin?.part===e.origin.part&&peer.origin?.shapeId===e.origin.shapeId)for(const k of ['x','y','w','h','rotation'] as const)if(k in fields)(peer as any)[k]=fields[k];if(fields.text&&e.role==='title')s.title=String(fields.text)})
 const moveSlide=(from:number,to:number)=>{if(disabled||to<0||to>=deck.slides.length)return;const next=clone(deck),[s]=next.slides.splice(from,1);next.slides.splice(to,0,s);onChange(next)}
 const addSlide=()=>{const next=clone(deck),s=layoutSlide({id:'s-'+uid(),layout:'statement',title:'新页面',subtitle:'在右侧编辑核心内容',body:[],notes:''},next,next.slides.length,next.slides.length+1);next.slides.splice(index+1,0,s);onChange(next);onSlide(s.id)}
 const duplicate=()=>{const next=clone(deck),s=clone(slide);s.id='s-'+uid();s.elements=s.elements.map((e:Element)=>({...e,id:uid()}));next.slides.splice(index+1,0,s);onChange(next);onSlide(s.id)}
 const addElement=(type:string)=>edit((d,s)=>{const base={id:'e-'+uid(),x:1,y:2,w:4,h:1.1};const value=type==='text'?{...base,type,text:'在此输入内容',fontSize:24,fontFamily:d.theme.font,color:d.theme.ink,lineHeight:1.22}:type==='shape'?{...base,type,shape:'roundRect',fill:d.theme.accent,stroke:'none'}:type==='table'?{...base,type,w:7,h:2.5,fontSize:16,header:true,headerFill:d.theme.accent,headerColor:'FFFFFF',color:d.theme.ink,fill:d.theme.paper,rows:[['列一','列二'],['内容','内容']]}:{...base,type:'chart',w:7,h:3.6,color:d.theme.ink,colors:[d.theme.accent,d.theme.secondary],chart:{type:'bar',categories:['待填写'],series:[{name:'用户数据',values:[0]}],unit:''}};s.elements.push(value as Element);setElementId(value.id);setTab('object');})
 const uploadImage=async(file:File)=>{setLocalError('');try{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>2*1024*1024)throw Error('图片支持PNG/JPEG/WebP/GIF，最大2MiB');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('图片读取失败'));reader.readAsDataURL(file)});edit((d,s)=>{const id='asset-'+uid();d.assets[id]={name:file.name,data};const e={id:'image-'+uid(),type:'image',assetId:id,x:1,y:2,w:4,h:3,fit:'contain'};s.elements.push(e as Element);setElementId(e.id);});}catch(e){setLocalError((e as Error).message)}}
 const beginDrag=(event:PointerEvent<HTMLDivElement>)=>{
  if(event.button!==0)return;const target=(event.target as HTMLElement).closest('[data-element-id]') as HTMLElement|null;if(!target)return;const id=target.getAttribute('data-element-id')??'',e=slide.elements.find(v=>v.id===id);setElementId(id);setTab('object');if(disabled||!e||e.locked||e.origin?.grouped)return;
  const svgElement=viewport.current?.querySelector('svg'),rect=svgElement?.getBoundingClientRect();if(!rect)return;event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);dragging.current={startX:event.clientX,startY:event.clientY,deck:clone(deck),id,w:rect.width,h:rect.height,mode:(event.target as HTMLElement).dataset?.resize?'resize':'move',target:event.currentTarget};
 }
 const drag=(event:PointerEvent<HTMLDivElement>)=>{const info=dragging.current;if(!info)return;const next=clone(info.deck),s=next.slides.find((v:Slide)=>v.id===slide.id)!,e=s.elements.find((v:Element)=>v.id===info.id)!,old=info.deck.slides.find(v=>v.id===slide.id)!.elements.find(v=>v.id===info.id)!,dx=(event.clientX-info.startX)/info.w*deck.width,dy=(event.clientY-info.startY)/info.h*deck.height,snap=(v:number)=>event.altKey?round(v):Math.round(v/.025)*.025;
  if(info.mode==='resize'){e.w=Math.max(.15,Math.min(deck.width-e.x,snap(old.w+dx)));e.h=Math.max(.15,Math.min(deck.height-e.y,snap(old.h+dy)));}else{e.x=Math.max(0,Math.min(deck.width-e.w,snap(old.x+dx)));e.y=Math.max(0,Math.min(deck.height-e.h,snap(old.y+dy)));}
  if(e.origin)for(const peer of s.elements)if(peer.id!==e.id&&peer.origin?.shapeId===e.origin.shapeId&&peer.origin?.part===e.origin.part)for(const k of ['x','y','w','h'])peer[k]=e[k];previewRef.current=next;setDragPreview(next)
 }
 const endDrag=()=>{if(dragging.current&&previewRef.current)onChange(previewRef.current);dragging.current=null;previewRef.current=null;setDragPreview(null)}
 const cancelDrag=()=>{dragging.current=null;previewRef.current=null;setDragPreview(null)}
 const chosen=(s:Slide)=>{cancelDrag();onSlide(s.id);setElementId('');setDataKey('');}
 const actionButton=(name:string,title:string,fn:()=>void,off=false)=><button type="button" title={title} aria-label={title} disabled={disabled||off} onClick={fn}><Icon name={name}/></button>
 return <div className="a-ppt-editor">
  <aside className="a-ppt-filmstrip"><header><span>幻灯片</span><b>{deck.slides.length}</b></header><div className="a-ppt-thumbs">{deck.slides.map((s,i)=><button type="button" className={'a-ppt-thumb '+(s.id===slide.id?'active':'')} key={s.id} aria-label={'选择第'+(i+1)+'页'} aria-current={s.id===slide.id} draggable={!disabled} onDragStart={()=>{reorder.current=s.id}} onDragOver={e=>{if(!disabled&&reorder.current)e.preventDefault()}} onDrop={e=>{e.preventDefault();if(reorder.current)moveSlide(deck.slides.findIndex(v=>v.id===reorder.current),i);reorder.current=null}} onClick={()=>chosen(s)}><span className="a-ppt-thumb-number">{String(i+1).padStart(2,'0')}</span><div dangerouslySetInnerHTML={{__html:slideSVG(deck,s)}}/><small>{s.title}</small></button>)}</div><footer>{actionButton('up','上移页面',()=>moveSlide(index,index-1),index===0)}{actionButton('down','下移页面',()=>moveSlide(index,index+1),index===deck.slides.length-1)}{deck.kind==='generated'&&actionButton('plus','添加页面',addSlide,deck.slides.length>=40)}</footer></aside>
  <main className="a-ppt-stage"><div className="a-ppt-toolbar"><div className="a-ppt-toolgroup">{actionButton('undo','撤销',onUndo,!canUndo)}{actionButton('redo','重做',onRedo,!canRedo)}<i/>{deck.kind==='generated'&&<>{actionButton('text','添加文本',()=>addElement('text'))}{actionButton('shape','添加形状',()=>addElement('shape'))}{actionButton('image','上传图片',()=>imageInput.current?.click())}{actionButton('grid','添加表格',()=>addElement('table'))}{actionButton('chart','添加图表',()=>addElement('chart'))}<input ref={imageInput} type="file" hidden accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void uploadImage(f)}}/></>}</div><div className="a-ppt-toolgroup"><span className="a-ppt-size">{deck.width>12?'16:9':deck.width===10?'4:3':`${deck.width.toFixed(1)} × ${deck.height.toFixed(1)}`}</span>{deck.kind==='generated'&&actionButton('copy','复制当前页',duplicate,deck.slides.length>=40)}{deck.kind==='generated'&&actionButton('trash','删除当前页',()=>{const next=clone(deck);next.slides.splice(index,1);onChange(next);onSlide(next.slides[Math.min(index,next.slides.length-1)].id)},deck.slides.length<=1)}</div></div>
   {localError&&<div className="a-ppt-inline-error" role="alert">{localError}<button onClick={()=>setLocalError('')}>×</button></div>}
   <div className="a-ppt-stage-scroll"><div className="a-ppt-canvas" ref={viewport} style={{aspectRatio:`${deck.width}/${deck.height}`}} tabIndex={0} aria-label="幻灯片编辑画布" onPointerDown={beginDrag} onPointerMove={drag} onPointerUp={endDrag} onPointerCancel={cancelDrag} onKeyDown={e=>{if(e.key==='Escape')cancelDrag();if(disabled||!element||element.locked||element.origin?.grouped)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const n=e.shiftKey?.25:.025;patch({x:round(Math.max(0,Math.min(deck.width-element.w,element.x+(e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0)))),y:round(Math.max(0,Math.min(deck.height-element.h,element.y+(e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0))))});}}}>
    <div className="a-ppt-svg" dangerouslySetInnerHTML={{__html:svg}}/>{element&&!element.locked&&<div data-element-id={element.id} className="a-ppt-selection" style={{left:element.x/deck.width*100+'%',top:element.y/deck.height*100+'%',width:element.w/deck.width*100+'%',height:element.h/deck.height*100+'%',transform:element.rotation?`rotate(${element.rotation}deg)`:undefined}}>{!disabled&&!element.origin?.grouped&&<span data-element-id={element.id} data-resize="true" className="a-ppt-resize"/>}</div>}
   </div><div className="a-ppt-canvas-caption"><span>第 {index+1} 页 / {deck.slides.length} · {current.elements.filter(e=>!e.locked).length} 个可编辑对象</span><span>{deck.kind==='native'?'模板原生对象保留 · 预览可能简化':'原生文字 / 图形 / 表格 / 图表'}</span></div></div>
   <div className="a-ppt-assistant"><div className="a-ppt-assistant-symbol"><Icon name="spark" size={21}/></div><form onSubmit={e=>{e.preventDefault();if(instruction.trim()&&!disabled){onAI(slide.id,instruction.trim());setInstruction('')}}}><label htmlFor="ppt-page-instruction">只修改这一页</label><div><input id="ppt-page-instruction" aria-label="当前页修改要求" value={instruction} maxLength={2000} disabled={disabled} onChange={e=>setInstruction(e.target.value)} placeholder="例如：保留事实，把这一页精简成三个重点"/><button className="a-ppt-primary" type="submit" disabled={disabled||!instruction.trim()}><Icon name="arrow"/> <span>交给设计师</span></button></div></form></div>
  </main>
  <aside className="a-ppt-inspector"><nav aria-label="编辑面板">{[['object','属性'],['notes','备注'],['check','检查']].map(([id,label])=><button type="button" key={id} className={tab===id?'active':''} onClick={()=>setTab(id as typeof tab)}>{label}{id==='check'&&quality.issues.length>0&&<b>{quality.issues.length}</b>}</button>)}</nav><div className="a-ppt-inspector-scroll">
   {tab==='notes'?<><div className="a-ppt-inspector-heading"><Icon name="file"/><h3>演讲者备注</h3></div><p className="a-ppt-help">备注会写入最终 PowerPoint。详细论证、来源和讲解可以放在这里。</p><textarea aria-label="演讲者备注" rows={18} value={slide.notes} disabled={disabled} onChange={e=>edit((_d,s)=>{s.notes=e.target.value})} maxLength={12000}/></>:tab==='check'?<><div className="a-ppt-inspector-heading"><Icon name={quality.passed?'check':'warning'}/><h3>{quality.passed?'结构检查通过':'有内容需要调整'}</h3></div><p className="a-ppt-help">检查范围：画布越界、文字容量、文本碰撞、表格与数据。模板复杂效果仍以 PowerPoint 中的原生对象为准。</p>{quality.issues.length?quality.issues.map((q:any,i:number)=><button className={'a-ppt-quality '+q.severity} key={i} onClick={()=>{onSlide(q.slideId);setElementId(q.elementId??'')}}><b>{q.severity==='error'?'需修复':'提示'} · 第{deck.slides.findIndex(s=>s.id===q.slideId)+1}页</b><span>{q.message}</span></button>):<div className="a-ppt-quality passed"><b>没有发现结构问题</b><span>内容准确性另由独立审校员检查。请在导出前确认关键事实。</span></div>}{(deck.template?.warnings??[]).map((w:string,i:number)=><p key={i} className="a-ppt-help">{w}</p>)}</>:<>
    <label className="a-ppt-field">页面标题<input aria-label="页面标题" value={slide.title} disabled={disabled} maxLength={120} onChange={e=>edit((_d,s)=>{s.title=e.target.value;const heading=s.elements.find(v=>v.type==='text'&&v.role==='title'&&!v.locked);if(heading)heading.text=e.target.value})}/></label><label className="a-ppt-field a-ppt-color">页面背景<input type="color" aria-label="页面背景颜色" value={'#'+slide.background} disabled={disabled} onChange={e=>edit((_d,s)=>{s.background=e.target.value.slice(1).toUpperCase()})}/></label>
    <div className="a-ppt-inspector-heading"><Icon name={element?.locked?'lock':'shape'}/><h3>{element?({text:'文本',shape:'形状',image:'图片',table:'原生表格',chart:'原生图表',preserved:'保留对象'}[element.type]):'选择一个对象'}</h3></div>
    {!element?<><p className="a-ppt-help">点击画布中的文字、图形或数据，也可以从下面选择。拖动调整位置；方向键微调。</p><div className="a-ppt-object-list">{slide.elements.filter(e=>!e.decorative&&!e.locked).map(e=><button key={e.id} onClick={()=>setElementId(e.id)}><Icon name={e.type==='text'?'text':e.type==='chart'?'chart':e.type==='table'?'grid':'shape'} size={14}/><span>{e.text?.slice(0,32)??e.type}</span></button>)}</div></>:element.locked?<p className="a-ppt-help">母版、复杂组合或嵌入对象在原文件中保留。此处只读，未转为不可编辑的整页截图。</p>:<>
     {element.type==='text'&&<><label className="a-ppt-field">文字<textarea aria-label="对象文字" rows={6} value={element.text} disabled={disabled} maxLength={12000} onChange={e=>patch({text:e.target.value})}/></label><div className="a-ppt-fields"><label>字号<input aria-label="字号" type="number" min="6" max="120" step="0.5" disabled={disabled} value={element.fontSize} onChange={e=>patch({fontSize:Math.min(120,Math.max(6,number(e.target.value,element.fontSize!)))})}/></label><label className="a-ppt-color">颜色<input type="color" aria-label="文字颜色" disabled={disabled} value={'#'+element.color} onChange={e=>patch({color:e.target.value.slice(1).toUpperCase()})}/></label></div><label className="a-ppt-field">字体<input aria-label="字体" disabled={disabled} value={element.fontFamily??deck.theme.font} maxLength={100} onChange={e=>patch({fontFamily:e.target.value})}/></label><div className="a-ppt-format"><button disabled={disabled} aria-label="粗体" aria-pressed={element.bold} className={element.bold?'active':''} onClick={()=>patch({bold:!element.bold})}><b>B</b></button><button disabled={disabled} aria-label="斜体" aria-pressed={element.italic} className={element.italic?'active':''} onClick={()=>patch({italic:!element.italic})}><i>I</i></button><select aria-label="文字对齐" value={element.align??'left'} disabled={disabled} onChange={e=>patch({align:e.target.value})}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></div></>}
     {element.type==='shape'&&<><label className="a-ppt-field a-ppt-color">填充<input type="color" aria-label="形状填充" value={'#'+(element.fill==='none'?'FFFFFF':element.fill)} disabled={disabled} onChange={e=>patch({fill:e.target.value.slice(1).toUpperCase()})}/></label>{!element.origin&&<label className="a-ppt-field">形状<select aria-label="形状类型" value={element.shape} disabled={disabled} onChange={e=>patch({shape:e.target.value})}><option value="rect">矩形</option><option value="roundRect">圆角矩形</option><option value="ellipse">椭圆</option><option value="triangle">三角形</option><option value="line">线条</option></select></label>}</>}
     {element.type==='table'&&<div className="a-ppt-data-grid"><p className="a-ppt-help">单元格保留为原生表格。修改后导出仍可逐格编辑。</p>{element.rows!.map((row,r)=><div key={r} style={{gridTemplateColumns:`repeat(${row.length},minmax(0,1fr))`}}>{row.map((value,c)=><textarea key={c} aria-label={`表格第${r+1}行第${c+1}列`} value={value} rows={2} disabled={disabled} onChange={ev=>{const rows=clone(element.rows!);rows[r][c]=ev.target.value;patch({rows})}}/>)}</div>)}</div>}
     {element.type==='chart'&&<><p className="a-ppt-help">数据写入 PPTX 内嵌工作簿。导入模板仅更改现有数值。</p>{element.chart!.series.map((series,j)=><div className="a-ppt-chart-series" key={j}><b>{series.name}</b>{series.values.map((n,i)=><label key={i}><span>{element.chart!.categories[i]}</span><input type="number" aria-label={`图表${j+1}系列${i+1}数值`} value={n} disabled={disabled} onChange={ev=>{const chart=clone(element.chart!);chart.series[j].values[i]=number(ev.target.value,n);patch({chart})}}/></label>)}</div>)}{!element.origin&&<details><summary>完整数据 JSON</summary><textarea aria-label="图表JSON" rows={8} disabled={disabled} value={dataKey===element.id?dataText:JSON.stringify(element.chart,null,2)} onChange={e=>{setDataKey(element.id);setDataText(e.target.value)}}/><button disabled={disabled} onClick={()=>{try{patch({chart:JSON.parse(dataKey===element.id?dataText:JSON.stringify(element.chart))});setDataKey('')}catch(e){setLocalError('图表JSON无效')}}}>应用数据</button></details>}</>}
     {element.type==='image'&&!element.origin&&<label className="a-ppt-field">图片适配<select aria-label="图片适配" value={element.fit??'contain'} disabled={disabled} onChange={e=>patch({fit:e.target.value})}><option value="contain">完整显示</option><option value="cover">裁剪填满</option></select></label>}
     <h4>位置与尺寸 <small>英寸</small></h4>{element.origin?.grouped?<p className="a-ppt-help">组合内位置保持原模板；文字可编辑。</p>:<div className="a-ppt-fields geometry">{(['x','y','w','h'] as const).map(k=><label key={k}>{({x:'X',y:'Y',w:'宽度',h:'高度'})[k]}<input aria-label={'对象'+k} type="number" step="0.025" value={element[k]} disabled={disabled} onChange={e=>patch({[k]:round(Math.max(0,number(e.target.value,element[k])))})}/></label>)}</div>}
     {!element.origin&&<button className="a-ppt-remove-object" disabled={disabled} onClick={()=>{edit((_d,s)=>{s.elements=s.elements.filter(e=>e.id!==elementId)});setElementId('')}}><Icon name="trash" size={15}/>删除对象</button>}
    </>}
   </>}
  </div><footer><span>{dirty?'有未保存修改':'文稿已同步'}</span><button className="a-ppt-primary" disabled={disabled||!dirty} onClick={onSave}>保存</button></footer></aside>
 </div>
}
