import {useEffect,useRef,useState,type FormEvent} from 'react'
import type {ContractClient} from '../../Contract/protocol'
import type {WorkflowView,WorkflowFile} from '../../Contract/workflow'
import Editor,{Icon} from './Editor'
import {STYLES,clone,validateDeck,inspectDeck,normalizeGenerated} from './scene.mjs'
import {readDraft,writeDraft,type Draft} from './drafts'
import type {Deck,Outline} from './types'
import './style.css'
import {prepareRevision} from './workflow.mjs'

const STATUS:Record<string,string>={running:'协作制作中',waiting:'等待确认',completed:'可编辑PPTX已就绪',failed:'需要处理',cancelled:'已停止'}
const STEPS=[['planning','叙事策划'],['writing','内容与设计'],['review','独立审校'],['edit','预览编辑'],['complete','PPTX交付']]
const ENGINE='PPT-maker'
const readBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('无法读取上传文件'));r.readAsDataURL(file)})
const hash=async(bytes:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as Uint8Array<ArrayBuffer>)),b=>b.toString(16).padStart(2,'0')).join('')
export default function Page({client}:{client:ContractClient}){
 const [job,setJob]=useState<WorkflowView|null>(null),[history,setHistory]=useState<WorkflowView[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [brief,setBrief]=useState(''),[audience,setAudience]=useState(''),[slideCount,setSlideCount]=useState(8),[style,setStyle]=useState('executive'),[ratio,setRatio]=useState('16:9'),[confirmOutline,setConfirmOutline]=useState(true),[engines,setEngines]=useState<string[]>([]),[template,setTemplate]=useState<{name:string;content:string}|null>(null),[materials,setMaterials]=useState<{name:string;content:string}[]>([])
 const [outline,setOutline]=useState<Outline|null>(null),[deck,setDeck]=useState<Deck|null>(null),[dirty,setDirty]=useState(false),[conflict,setConflict]=useState(false),[slideId,setSlideId]=useState(''),[undo,setUndo]=useState<Deck[]>([]),[redo,setRedo]=useState<Deck[]>([]),[exportDialog,setExportDialog]=useState(false),[consent,setConsent]=useState(false),[stopDialog,setStopDialog]=useState(false)
 const pendingDraft=useRef<Draft|null>(null)
 const flushDraft=()=>{if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null}const value=pendingDraft.current;pendingDraft.current=null;if(value)void writeDraft(value,value.id).catch(()=>{if(alive.current)setNotice('浏览器草稿保存失败，请点击保存提交Core。')})}
 const alive=useRef(true),jobRef=useRef<WorkflowView|null>(null),deckRef=useRef<Deck|null>(null),dirtyRef=useRef(false),baseRevision=useRef(0),request=useRef<{payload:string;key:string}|null>(null),selectedId=useRef<string|null>(null),draftTimer=useRef<ReturnType<typeof setTimeout>|null>(null),operation=useRef(false)
 const updateLocal=(value:Deck|null,isDirty=false)=>{deckRef.current=value;dirtyRef.current=isDirty;setDeck(value);setDirty(isDirty)}
 const applyJob=(next:WorkflowView)=>{jobRef.current=next;setJob(next);setHistory(old=>[next,...old.filter(j=>j.id!==next.id)].sort((a,b)=>b.createdAt-a.createdAt));if(next.summary.outline)setOutline(old=>jobRef.current?.id===next.id&&old?.slides.length?old:clone(next.summary.outline));
  if(next.summary.deck){const changed=baseRevision.current!==(next.summary.deckRevision??0);if(!deckRef.current||changed&&!dirtyRef.current){updateLocal(clone(next.summary.deck));baseRevision.current=next.summary.deckRevision??0;setSlideId(old=>next.summary.deck.slides.some((s:any)=>s.id===old)?old:next.summary.deck.slides[0].id);setUndo([]);setRedo([]);setConflict(false)}else if(changed&&dirtyRef.current)setConflict(true);}
 }
 const loadJob=async(id:string)=>{if(dirtyRef.current&&!window.confirm('本地修改尚未保存。离开当前文稿？草稿会保留在本浏览器。'))return;flushDraft();selectedId.current=id;updateLocal(null);baseRevision.current=0;setOutline(null);setError('');setNotice('');setConflict(false);setUndo([]);setRedo([]);const next=await client.invoke<WorkflowView>('workflow.get',{id});if(!alive.current||selectedId.current!==id)return;applyJob(next);if(next.status==='waiting'&&next.summary.phase==='edit')try{const saved=await readDraft(id);if(saved&&alive.current&&selectedId.current===id){validateDeck(saved.deck);updateLocal(saved.deck,true);baseRevision.current=saved.baseRevision;setConflict(saved.baseRevision!==next.summary.deckRevision);setNotice('已恢复本浏览器中尚未提交的编辑草稿。')}}catch(e){setNotice('浏览器草稿读取失败，请以Core中已保存的版本为准。')}}
 useEffect(()=>{alive.current=true;void client.invoke<{jobs:WorkflowView[]}>('workflow.list',{engineId:ENGINE}).then(({jobs})=>{if(alive.current)setHistory(jobs)}).catch(e=>{if(alive.current)setError(e.message)}).finally(()=>{if(alive.current)setLoading(false)});return()=>{alive.current=false;flushDraft()}},[client])
 useEffect(()=>{if(!job||!['running','waiting'].includes(job.status))return;let active=true,timer:ReturnType<typeof setTimeout>;const id=job.id,poll=async()=>{try{const next=await client.invoke<WorkflowView>('workflow.get',{id});if(active&&selectedId.current===id){if(next.revision!==jobRef.current?.revision)applyJob(next)}}catch(e){if(active)setError((e as Error).message)}finally{if(active)timer=setTimeout(poll,1200)}};timer=setTimeout(poll,600);return()=>{active=false;clearTimeout(timer)}},[job?.id,job?.status,client])
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[])
 const persist=(value:Deck)=>{const id=jobRef.current?.id;if(!id)return;pendingDraft.current={id,baseRevision:baseRevision.current,deck:clone(value),at:Date.now()};if(draftTimer.current)clearTimeout(draftTimer.current);draftTimer.current=setTimeout(flushDraft,450)}
 const changeDeck=(value:Deck)=>{try{normalizeGenerated(value);validateDeck(value);if(!deckRef.current)return;const previous=clone(deckRef.current!);setUndo(old=>[...old.slice(-24),previous]);setRedo([]);updateLocal(value,true);persist(value)}catch(e){setError((e as Error).message)}}
 const undoDeck=()=>{if(!undo.length||!deck)return;const value=undo.at(-1)!;setUndo(old=>old.slice(0,-1));setRedo(old=>[...old,clone(deck)]);updateLocal(value,true);persist(value)}
 const redoDeck=()=>{if(!redo.length||!deck)return;const value=redo.at(-1)!;setRedo(old=>old.slice(0,-1));setUndo(old=>[...old,clone(deck)]);updateLocal(value,true);persist(value)}
 const keyFor=(value:unknown)=>{const payload=JSON.stringify(value);if(request.current?.payload!==payload)request.current={payload,key:crypto.randomUUID()};return request.current.key}
 const operate=async(fn:()=>Promise<void>)=>{if(operation.current)return;operation.current=true;setBusy(true);setError('');try{await fn()}catch(e){if(alive.current)setError((e as Error).message)}finally{operation.current=false;if(alive.current)setBusy(false)}}
 const acceptSaved=async(next:WorkflowView)=>{pendingDraft.current=null;if(draftTimer.current){clearTimeout(draftTimer.current);draftTimer.current=null}updateLocal(null);baseRevision.current=0;setOutline(null);applyJob(next);setConflict(false);await writeDraft(null,next.id).catch(()=>{});request.current=null;}
 const answer=async(action:string,extra:Record<string,unknown>={})=>{const current=jobRef.current;if(!current)throw Error('尚未选择文稿');if(conflict)throw Error('Core文稿已经更新；本地草稿保留，请先处理版本冲突');const body={id:current.id,expectedRevision:current.revision,answer:{action,...(current.summary.phase==='edit'?{deckRevision:baseRevision.current,...(dirtyRef.current?{deck:deckRef.current}:{})}:{}),...extra}};const next=await client.invoke<WorkflowView>('workflow.respond',{...body,clientRequestId:keyFor(body)});await acceptSaved(next)}
 const start=(event:FormEvent)=>{event.preventDefault();void operate(async()=>{const input={brief:brief.trim(),audience:audience.trim(),slideCount,style,ratio,confirmOutline,...(template?{template}:{}),...(materials.length?{materials}:{}),...(engines.length?{engines:engines.map(engine=>({engine}))}:{})},body={engineId:ENGINE,input};const next=await client.invoke<WorkflowView>('workflow.start',{...body,clientRequestId:keyFor(body)});selectedId.current=next.id;updateLocal(null);setOutline(null);baseRevision.current=0;applyJob(next);request.current=null;setNotice('');})}
 const uploadTemplate=async(file:File)=>{if(!/\.(pptx|potx)$/i.test(file.name)||file.size>4*1024*1024)throw Error('请选择4MiB以内的 .pptx 或 .potx 模板；旧 .ppt、宏和加密文件不受支持');setTemplate({name:file.name,content:await readBase64(file)})}
 const uploadMaterials=async(files:File[])=>{const next=[...materials];for(const file of files){if(!/\.(txt|md|csv)$/i.test(file.name)||file.size>240000)throw Error('资料支持TXT、Markdown或CSV，每份不超过240KB');const content=await file.text();next.push({name:file.name,content});}if(next.length>8||next.reduce((n,m)=>n+m.content.length,0)>160000)throw Error('资料最多8份，合计16万个字符');setMaterials(next)}
 const download=async()=>{const current=jobRef.current;if(current?.status!=='completed'||current.files.length!==1)throw Error('最终PPTX尚未就绪');const metadata=current.files[0],f=await client.invoke<WorkflowFile&{content:string}>('workflow.file',{id:current.id,name:metadata.name});if(f.encoding!=='base64')throw Error('Infra尚未提供所需的二进制文件协议');const bytes=Uint8Array.from(atob(f.content),c=>c.charCodeAt(0));if(bytes.length!==f.bytes||await hash(bytes)!==f.sha256)throw Error('下载文件长度或SHA-256校验失败');const url=URL.createObjectURL(new Blob([bytes],{type:f.mediaType})),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
 const fork=()=>void operate(async()=>{if(!job)return;const body={engineId:ENGINE,input:await prepareRevision(client,job.id)},next=await client.invoke<WorkflowView>('workflow.start',{...body,clientRequestId:keyFor(body)});selectedId.current=next.id;updateLocal(null);baseRevision.current=0;setOutline(null);applyJob(next);request.current=null;setNotice('新修订已建立，上一版PPTX保持不变。')})
 const newDocument=()=>{if(operation.current)return;if(dirtyRef.current&&!window.confirm('当前修改尚未提交，离开并保留浏览器草稿？'))return;flushDraft();selectedId.current=null;jobRef.current=null;setJob(null);updateLocal(null);setOutline(null);setError('');setNotice('');setConflict(false);request.current=null;}
 const retry=()=>void operate(async()=>{if(!job)return;const body={id:job.id,expectedRevision:job.revision},next=await client.invoke<WorkflowView>('workflow.resume',{...body,clientRequestId:keyFor(body)});applyJob(next)})
 const quality=deck?inspectDeck(deck):null,editing=job?.status==='waiting'&&job.summary.phase==='edit',summary=job?.summary??{},exportNeedsConsent=!!quality?.warnings||!!summary?.review?.stale||summary?.review?.verdict==='revise'||dirty
 return <div className="a-ppt" data-ppt-status={job?.status??'new'}>
  <header className="a-ppt-header"><button className="a-ppt-brand" onClick={newDocument} aria-label="PPT-maker首页"><span><Icon name="slides" size={24}/></span><div><strong>PPT-maker</strong><small>AEXUS / PRESENTATION ENGINE</small></div></button><div className="a-ppt-header-right">{job&&<><span className={'a-ppt-status '+job.status}>{STATUS[job.status]}</span><button className="a-ppt-quiet" disabled={busy} onClick={newDocument}>新建</button>{job.status==='completed'?<><button className="a-ppt-outline-button" disabled={busy} onClick={fork}>创建修订</button><button className="a-ppt-primary" disabled={busy} onClick={()=>void operate(download)}><Icon name="download"/>下载 PPTX</button></>:editing?<><button className="a-ppt-outline-button" disabled={busy||conflict} onClick={()=>void operate(()=>answer('review'))}>重新审校</button><button className="a-ppt-primary" disabled={busy||conflict||!quality?.passed} onClick={()=>{setConsent(false);setExportDialog(true)}}><Icon name="download"/>导出 PPTX</button></>:null}</>}</div></header>
  {error&&<div className="a-ppt-error" role="alert"><Icon name="warning"/><span>{error}</span><button onClick={()=>setError('')} aria-label="关闭错误">×</button></div>}{notice&&<div className="a-ppt-notice" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  {conflict&&<div className="a-ppt-conflict" role="alert"><b>检测到另一处编辑，本地草稿已保留。</b><span>新版本不会覆盖你正在输入的内容。</span><button disabled={busy} onClick={()=>{if(window.confirm('丢弃本地未提交修改，载入Core最新版本？'))void operate(async()=>{await writeDraft(null,job!.id);updateLocal(null);baseRevision.current=0;const fresh=await client.invoke<WorkflowView>('workflow.get',{id:job!.id});applyJob(fresh);setConflict(false)})}}>载入最新版本</button></div>}
  {!job?<main className="a-ppt-home"><div className="a-ppt-hero"><div className="a-ppt-eyebrow">FROM AN IDEA TO AN EDITABLE DECK</div><h1>说出想法。<br/><em>把下一场演示，做清楚。</em></h1><p>策划、设计、审校分工协作。导入你的模板，或从需求开始。<br/>最后得到一份真正可编辑的 PowerPoint。</p></div><form className="a-ppt-intake" onSubmit={start}><label htmlFor="ppt-brief">这份演示，需要讲清楚什么？</label><textarea id="ppt-brief" aria-label="PPT制作需求" value={brief} onChange={e=>setBrief(e.target.value)} maxLength={6000} rows={4} placeholder="例如：为团队制作一份8页的项目方案，先讲问题，再讲解决方案与实施步骤。使用我上传的数据，不补造数字。"/><div className="a-ppt-upload-row"><label className={'a-ppt-upload '+(template?'loaded':'')}><Icon name="slides"/><div><strong>{template?template.name:'上传 PPT 模板'}</strong><small>{template?'保留母版、对象与原生结构':'PPTX / POTX · 最大4MiB'}</small></div><input type="file" aria-label="上传PPT模板" accept=".pptx,.potx" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void operate(()=>uploadTemplate(f))}}/>{template&&<button type="button" onClick={e=>{e.preventDefault();setTemplate(null)}} aria-label="移除模板">×</button>}</label><label className="a-ppt-upload"><Icon name="file"/><div><strong>补充原始资料</strong><small>TXT / MD / CSV · 可多选</small></div><input type="file" multiple aria-label="上传原始资料" accept=".txt,.md,.csv" onChange={e=>{const files=[...(e.target.files??[])];e.target.value='';if(files.length)void operate(()=>uploadMaterials(files))}}/></label></div>{materials.length>0&&<div className="a-ppt-materials">{materials.map((m,i)=><span key={i}><Icon name="file" size={13}/>{m.name}<button type="button" aria-label={'移除资料'+m.name} onClick={()=>setMaterials(old=>old.filter((_x,j)=>i!==j))}>×</button></span>)}</div>}
   <div className="a-ppt-options"><label>页数<input type="number" aria-label="PPT页数" min="3" max="24" value={slideCount} disabled={!!template} onChange={e=>setSlideCount(Number(e.target.value))}/></label><label>风格<select aria-label="PPT风格" value={style} disabled={!!template} onChange={e=>setStyle(e.target.value)}>{Object.entries(STYLES).map(([id,t])=><option key={id} value={id}>{t.name}</option>)}</select></label><label>比例<select aria-label="画布比例" value={ratio} disabled={!!template} onChange={e=>setRatio(e.target.value)}><option>16:9</option><option>4:3</option></select></label><button className="a-ppt-primary" type="submit" disabled={busy||!brief.trim()&&!template}>{busy?'正在准备…':template&&!brief.trim()?'导入并编辑':'开始制作'}<Icon name="arrow"/></button></div>
   <details className="a-ppt-advanced"><summary>受众与协作设置 <small>默认使用已配置引擎，三个角色独立协作</small></summary><label className="a-ppt-field">演示受众<input aria-label="演示受众" value={audience} maxLength={300} onChange={e=>setAudience(e.target.value)} placeholder="例如：项目评审委员会、客户、同学"/></label><div className="a-ppt-engine-choices">{['codex','claude','cline','pi'].map(id=><label key={id}><input type="checkbox" checked={engines.includes(id)} onChange={()=>setEngines(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>{id==='claude'?'Claude Code':id==='codex'?'Codex':id==='cline'?'Cline':'Pi'}</label>)}</div><label className="a-ppt-checkbox"><input type="checkbox" checked={confirmOutline} onChange={e=>setConfirmOutline(e.target.checked)}/>制作正文前确认大纲</label><p>生成和AI修改使用Infra里已有的模型配置。单纯导入、手动编辑和导出不调用模型。模板复杂效果保留在文件中，浏览器预览会说明限制。</p></details></form>
   <div className="a-ppt-feature-grid"><article><span>01 / STRUCTURE</span><h3>先组织观点</h3><p>给受众一条清晰的论证路径，大纲可先确认。</p></article><article><span>02 / COLLABORATE</span><h3>角色分工协作</h3><p>策划、设计、审校各自工作，只有需要时才运行。</p></article><article><span>03 / EDITABLE</span><h3>每一页都能继续改</h3><p>在画布调整文字与数据，最终交付原生PPTX。</p></article></div>
   <section className="a-ppt-recent"><header><h2>最近的演示</h2><small>{loading?'正在读取…':history.length+' 份文稿'}</small></header>{history.length?<div>{history.slice(0,12).map(h=><button key={h.id} onClick={()=>void operate(()=>loadJob(h.id))}><span className="a-ppt-recent-icon"><Icon name="slides" size={21}/></span><div><strong>{h.summary.title}</strong><small>{new Date(h.createdAt).toLocaleDateString()} · {h.summary.slideCount??'—'} 页</small></div><span className={'a-ppt-status '+h.status}>{STATUS[h.status]}</span></button>)}</div>:!loading&&<p>开始一次制作，文稿、修改和最终文件会保存在同一工作流中。</p>}</section>
  </main>:<>
   <div className="a-ppt-project-strip"><div><strong>{summary?.title}</strong><span>{summary?.audience} · {summary?.slideCount} 页{summary?.parentId?' · 新修订':''}</span></div><div className="a-ppt-progress">{STEPS.map(([id,label],i)=>{const phase=summary?.phase==='outline'?'planning':summary?.phase==='revising'?'writing':summary?.phase;const current=STEPS.findIndex(([x])=>x===phase);return <span key={id} className={phase===id?'active':current>i?'done':''}><b>{current>i?'✓':i+1}</b>{label}</span>})}</div></div>
   {deck?<><Editor deck={deck} onChange={changeDeck} disabled={busy||!editing||conflict} slideId={slideId} onSlide={setSlideId} onAI={(id,text)=>void operate(()=>answer('ai-edit',{slideId:id,instruction:text}))} onSave={()=>void operate(()=>answer('save'))} dirty={dirty} onUndo={undoDeck} onRedo={redoDeck} canUndo={!!undo.length} canRedo={!!redo.length}/>{summary?.review&&<details className="a-ppt-review"><summary><Icon name={summary.review.verdict==='pass'?'check':'warning'} size={16}/>独立审校：{summary.review.stale||dirty?'文稿已修改，可重新审校':summary.review.verdict==='pass'?'通过':'有待处理意见'}<span>{summary.review.summary}</span></summary>{summary.review.issues.map((r:any,i:number)=><p key={i}><b>{r.severity==='blocking'?'阻断':r.severity==='warning'?'提醒':'说明'}</b>{r.message}</p>)}</details>}</>:null}
   {job.status==='waiting'&&summary?.phase==='outline'&&outline&&<main className="a-ppt-outline-page"><div><span className="a-ppt-eyebrow">STORY BEFORE SLIDES</span><h1>先把叙事结构定下来。</h1><p>修改标题与本页目标，再交给内容和视觉角色并行制作。</p></div><label className="a-ppt-field">演示标题<input aria-label="大纲演示标题" value={outline.title} maxLength={100} onChange={e=>setOutline({...outline,title:e.target.value})}/></label><ol>{outline.slides.map((s,i)=><li key={s.id}><b>{String(i+1).padStart(2,'0')}</b><div><input aria-label={'大纲第'+(i+1)+'页标题'} value={s.title} maxLength={90} onChange={e=>setOutline({...outline,slides:outline.slides.map((p,j)=>i===j?{...p,title:e.target.value}:p)})}/><textarea aria-label={'大纲第'+(i+1)+'页目的'} value={s.purpose} maxLength={500} rows={2} onChange={e=>setOutline({...outline,slides:outline.slides.map((p,j)=>i===j?{...p,purpose:e.target.value}:p)})}/></div></li>)}</ol><button className="a-ppt-primary" disabled={busy} onClick={()=>void operate(()=>answer('approve-outline',{outline}))}>确认结构，开始制作<Icon name="arrow"/></button></main>}
   {job.status==='running'&&<section className={'a-ppt-running '+(deck?'compact':'')} aria-live="polite"><div className="a-ppt-spinner"/><div><h2>{summary?.phaseLabel??'准备制作'}</h2><p>可以离开此页面；任务由Core执行并保存检查点。</p></div>{summary?.attention&&<button onClick={()=>void operate(async()=>{await client.invoke('view.open',{kind:'conversation',employee:summary.attention.employeeId})})}>前往Infra审批</button>}</section>}
   {job.status==='failed'&&<section className="a-ppt-failure"><Icon name="warning" size={28}/><div><h2>制作停在需要处理的步骤</h2><p role="alert">{job.error}</p><p>已完成的工作与文稿保留。恢复不会重建员工或盲目重发尚未确认的请求。</p></div><button className="a-ppt-primary" disabled={busy} onClick={retry}>从检查点恢复</button></section>}
   {job.status==='cancelled'&&<section className="a-ppt-failure"><div><h2>制作已停止</h2><p>仅请求取消这项制作拥有的任务；其他引擎和员工继续工作。</p>{job.error&&<p>{job.error}</p>}</div><button onClick={newDocument}>新建演示</button></section>}
   {!deck&&summary?.workers?.length>0&&<section className="a-ppt-team">{summary.workers.map((w:any,i:number)=><article key={w.id}><span>{String(i+1).padStart(2,'0')}</span><h3>{w.label}</h3><small>{w.engine} · 独立员工会话</small><p>{(summary.tasks??[]).filter((t:any)=>t.employeeId===w.id).at(-1)?.status==='completed'?'本步骤已完成':(summary.tasks??[]).filter((t:any)=>t.employeeId===w.id).at(-1)?.status==='running'?'正在工作':'等待任务'}</p></article>)}</section>}
   {summary?.tasks?.length>0&&<details className="a-ppt-execution"><summary>协作记录 <span>任务状态保留在这里，不加入最终交付</span></summary>{summary.tasks.map((t:any)=><div key={t.id}><strong>{t.label}</strong><span>{t.engine}</span><b>{({prepared:'已准备',running:'执行中',approval:'等待审批',completed:'完成',failed:'需处理'} as Record<string,string>)[t.status]??t.status}</b></div>)}</details>}
   {!['completed','cancelled'].includes(job.status)&&<footer className="a-ppt-job-footer"><span>任务 {job.id.slice(-12)} · 仅通过 Contract 1.0 调用 Infra</span><button disabled={busy} onClick={()=>setStopDialog(true)}>停止这次制作</button></footer>}
  </>}
  {exportDialog&&<div className="a-ppt-modal-backdrop"><section className="a-ppt-modal" role="dialog" aria-modal="true" aria-labelledby="ppt-export-title"><button className="a-ppt-modal-close" aria-label="关闭导出确认" onClick={()=>setExportDialog(false)}>×</button><div className="a-ppt-modal-mark"><Icon name="download" size={30}/></div><h2 id="ppt-export-title">交付一份可编辑 PPTX</h2><p>将保存当前文稿，并核验原生对象、内嵌图表数据和文件关系。中间JSON、预览和日志不会加入下载区。</p>{exportNeedsConsent&&<label className="a-ppt-checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我已检查当前文稿与审校提示，接受已说明的模板预览限制。</label>}<footer><button onClick={()=>setExportDialog(false)}>继续编辑</button><button className="a-ppt-primary" disabled={busy||exportNeedsConsent&&!consent} onClick={()=>void operate(async()=>{await answer('export',{confirmReview:true,acceptWarnings:true});setExportDialog(false)})}>验证并生成 PPTX</button></footer></section></div>}
  {stopDialog&&<div className="a-ppt-modal-backdrop"><section className="a-ppt-modal" role="dialog" aria-modal="true"><h2>停止这次制作？</h2><p>会请求取消这份文稿拥有的当前任务。已保存内容保留，其他引擎任务不受影响。</p><footer><button onClick={()=>setStopDialog(false)}>继续制作</button><button className="a-ppt-primary" disabled={busy} onClick={()=>void operate(async()=>{const next=await client.invoke<WorkflowView>('workflow.cancel',{id:job!.id});applyJob(next);setStopDialog(false)})}>确认停止</button></footer></section></div>}
 </div>
}
