import {api} from '../api'
import {useState} from 'react'
import type {Approval} from '../../../shared/types'
export function AgentApproval({approval,respond}:{approval:Approval;respond:(decision:'allow'|'deny',answers?:Record<string,string[]>,form?:Record<string,unknown>)=>Promise<any>}){
  const [form,setForm]=useState(()=>JSON.stringify(Object.fromEntries(Object.entries(approval.schema?.properties??{}).filter(([,field]:[string,any])=>field.default!==undefined||field.type==='boolean').map(([key,field]:[string,any])=>[key,field.default??false]))))
  const [answers,setAnswers]=useState<Record<string,string[]>>({}),[error,setError]=useState(''),[sending,setSending]=useState(false)
  const fields=approval.schema?.properties as Record<string,any>|undefined
  const simple=fields&&!approval.allowNestedForm
  const values=(()=>{try{return JSON.parse(form)}catch{return {}}})()
  const setField=(key:string,value:unknown)=>setForm(JSON.stringify({...values,[key]:value}))
  const submit=async(decision:'allow'|'deny')=>{setSending(true);setError('');try{await respond(decision,answers,approval.schema&&decision==='allow'?JSON.parse(form):undefined)}catch(e){setError((e as Error).message)}finally{setSending(false)}}
  return <form className="approval" onSubmit={e=>{e.preventDefault();void submit('allow')}}><strong>{approval.title}</strong>
    {approval.url&&<p><button type="button" onClick={()=>void api.call('external.open',{url:approval.url}).catch(e=>setError(e.message))}>打开授权页面</button><small>{approval.url}</small></p>}
    {approval.schema?<>{simple?Object.entries(fields!).map(([key,field])=><label className="elicitation-field" key={key}>{field.title||key}{field.description&&<small>{field.description}</small>}{field.enum?<select aria-label={field.title||key} required={approval.schema?.required?.includes(key)} value={values[key]===undefined?'':JSON.stringify(values[key])} onChange={e=>setField(key,e.target.value?JSON.parse(e.target.value):undefined)}><option value="">请选择</option>{field.enum.map((value:any)=><option key={JSON.stringify(value)} value={JSON.stringify(value)}>{String(value)}</option>)}</select>:field.type==='boolean'?<input type="checkbox" checked={values[key]??false} onChange={e=>setField(key,e.target.checked)}/>:field.type==='array'?<textarea aria-label={field.title||key} value={(values[key]??[]).join('\n')} onChange={e=>setField(key,e.target.value.split('\n').filter(Boolean))}/>:<input aria-label={field.title||key} type={['number','integer'].includes(field.type)?'number':field.format==='password'||field.writeOnly?'password':'text'} min={field.minimum} max={field.maximum} step={field.type==='integer'?1:'any'} required={approval.schema?.required?.includes(key)} value={values[key]??''} onChange={e=>setField(key,['number','integer'].includes(field.type)?e.target.value===''?undefined:Number(e.target.value):e.target.value)}/>}</label>):<><p>按服务要求填写表单（JSON）。</p><details><summary>查看字段说明</summary><pre>{JSON.stringify(approval.schema,null,2)}</pre></details><textarea aria-label="MCP 表单" value={form} onChange={e=>setForm(e.target.value)}/></>}</>:approval.questions?.length?approval.questions.map(q=><fieldset key={q.id}><legend>{q.header} · {q.question}</legend>{q.options?.map(option=><label key={option.label}><input type={q.multiSelect?'checkbox':'radio'} name={q.id} checked={answers[q.id]?.includes(option.label)??false} onChange={e=>setAnswers(previous=>({...previous,[q.id]:q.multiSelect?e.target.checked?[...(previous[q.id]??[]),option.label]:(previous[q.id]??[]).filter(v=>v!==option.label):[option.label]}))}/>{option.label}{option.description&&<small> · {option.description}</small>}</label>)}{(q.isOther||!q.options?.length)&&<input aria-label={`回答 ${q.question}`} type={q.isSecret?'password':'text'} placeholder="输入回答" value={answers[q.id]?.filter(v=>!q.options?.some(o=>o.label===v)).join(', ')??''} onChange={e=>setAnswers(p=>({...p,[q.id]:[e.target.value]}))}/>}</fieldset>):<pre>{JSON.stringify(approval.input,null,2)}</pre>}
    {error&&<p role="alert">{error}</p>}<div className="btn-row"><button type="button" className="btn" disabled={sending} onClick={()=>void submit('deny')}>取消</button><button className="btn primary" disabled={sending}>{approval.questions?.length||approval.schema?'提交回答':approval.url?'已完成验证':'允许本次操作'}</button></div>
  </form>
}
