import {createPortal} from 'react-dom'
import {useCallback,useEffect,useMemo,useRef,useState,type DragEvent,type KeyboardEvent} from 'react'
import {useVirtualizer} from '@tanstack/react-virtual'
import type {AssetNode,AssetTree,AssetFilters,AssetLocation,AssetFacets} from '../../../shared/asset-schema'
import {ASSET_KINDS,assetTitle,assetNodeId} from '../../../shared/asset-presentation'
import type {FileLocation} from '../../../shared/transfers'
import {api} from '../api'
import {affectsMembers} from '../../../shared/store-changes'
import {Icon} from './Icon'
import {AppSelect} from './AppSelect'
import {FileWorkspace} from './FileWorkspace'
import {PanelDivider} from './PanelDivider'
import {MessageMenu} from './MessageMenu'
import {AssetGlyph,AssetHostBadge,assetError} from './AssetIdentity'
import {AssetInfoDialog} from './AssetInfo'
import {AssetGallery,clearAssetCovers} from './AssetGallery'
import {AssetActionDialog} from './AssetActionDialog'
import {useDialogFocus} from '../office/useDialogFocus'
import {revealFile,downloadFile} from '../file-actions'
import {flushPlugins} from '../plugins'
import {dragFile,dropFiles,hasFileDrop,copyFile,pasteFile} from '../file-transfers'
import {translate as t,useI18n} from '../i18n'
import '../styles/asset-browser.css'
import '../styles/asset-library.css'

type Children={entries:AssetNode[];total:number;nextOffset:number|null}
type Row={node:AssetNode;depth:number;more?:number}
const kinds:Record<string,string>={folder:'Folders',all:'All files',document:'Documents',image:'Images',audio:'Audio',video:'Video',code:'Code',archive:'Archives',other:'Other files'}
const roles:Record<string,string>={shared:'Shared files',team:'Team workspace',employee:'Personal workspace',member:'Member workspace',group:'Group workspace',channel:'Channel workspace',published:'Published attachments',exports:'Plan exports'}
const ownerLine=(node:AssetNode)=>[node.owner?.employeeName,node.owner?.team,node.owner?.conversationName,...(!node.owner?.employeeName&&!node.owner?.team&&!node.owner?.conversationName?[node.owner?.label]:[]),node.owner?.view].filter((value,index,all)=>value&&all.indexOf(value)===index).join(' · ')
const availableFinder=(node:AssetNode)=>api.mode!=='web'&&!!node.location&&node.storage!=='cloud'&&node.storage!=='remote'&&!(node.directory&&node.location.asset?.startsWith('published:channel:'))

function AssetPreview({value,onClose,onError}:{value:AssetLocation;onClose:()=>void;onError:(error:string)=>void}){
 useDialogFocus('.asset-workspace-overlay [role=dialog]',true)
 const close=()=>void flushPlugins().then(onClose).catch(error=>onError(error.message)),node=value.node,parent=value.parent
 return createPortal(<div className="asset-workspace-overlay" onKeyDown={event=>{if(event.key==='Escape'&&!event.defaultPrevented){event.preventDefault();event.stopPropagation();close()}}}><div className="panel-backdrop" onClick={close}/><section className="team-workspace" role="dialog" aria-modal="true" aria-label={t('Asset workspace')}>
  <header className="workspace-header"><button aria-label={t('Back to files')} title={t('Back to files')} onClick={close}><Icon name="arrow-left"/></button><div><strong>{assetTitle(value.workspace)}</strong><small>{ownerLine(node)||ownerLine(value.workspace)}</small></div><span className="asset-access-badge">{t(value.workspace.readOnly?'Read-only originals':node.owner?.conversation?'Shared workspace':'Workspace')}</span></header>
  <nav className="asset-location-trail" aria-label={t('Workspace location')}>{value.breadcrumbs.map(item=><span key={item.id}>{t(item.name)}</span>)}</nav>
  {node.document&&<p className="asset-location-note"><Icon name="cloud"/>{t('This file is stored in the cloud. Download it to the channel before editing.')}</p>}
  <FileWorkspace folderName={assetTitle(value.workspace)} flat={value.workspace.id.startsWith('published:channel:')} initialFileName={node.name} revealAvailable={api.mode!=='web'&&value.workspace.storage!=='remote'&&!value.workspace.id.startsWith('published:channel:')} readOnly={value.workspace.readOnly} key={parent.location?.asset+'/'+parent.location?.path+'/'+node.id} assetRoot={parent.location!.asset} initialFolder={parent.location!.path==='.'?'':parent.location!.path} initialFile={node.directory||node.document?'':node.location?.path??''}/>
 </section></div>,document.body)
}

/** One browser over canonical workspaces. Search filters, IDs and ownership are resolved by Core. */
export function AssetBrowser({onClose,width=320,onResize}:{onClose:()=>void;width?:number;onResize:(width:number|undefined)=>void}){
 useI18n()
 const [facets,setFacets]=useState<AssetFacets>({teams:[],employees:[],conversations:[]}),[tree,setTree]=useState<AssetTree>(),[branches,setBranches]=useState<Record<string,Children>>({}),[expanded,setExpanded]=useState(new Set(['root','company','messages','groups','channels'])),[mode,setMode]=useState<'files'|'assets'>('files')
 const [filters,setFilters]=useState<AssetFilters>({}),[filterOpen,setFilterOpen]=useState(false),[query,setQuery]=useState(''),[hidden,setHidden]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0)
 const [loading,setLoading]=useState(new Set<string>()),[branchErrors,setBranchErrors]=useState<Record<string,string>>({}),[open,setOpen]=useState<AssetLocation>(),[menu,setMenu]=useState<{node:AssetNode;x:number;y:number}>(),[busy,setBusy]=useState<string>(),[naming,setNaming]=useState<any>(),[namingBusy,setNamingBusy]=useState(false)
 const scroll=useRef<HTMLDivElement>(null),alive=useRef(true),generation=useRef(0),opening=useRef(0),branchRequests=useRef(new Map<string,number>())
 const scope=useMemo(()=>({view:filters.view,team:filters.team,employee:filters.employee,conversation:filters.conversation,host:filters.host}),[filters.view,filters.team,filters.employee,filters.conversation,filters.host]),scopeKey=JSON.stringify(scope)
 const previousScope=useRef(scopeKey),branchSnapshot=useRef(branches),expandedSnapshot=useRef(expanded);branchSnapshot.current=branches;expandedSnapshot.current=expanded
 const change=(patch:Partial<AssetFilters>)=>{setFilters(previous=>({...previous,...patch}));setNotice('')}
 const [selected,setSelected]=useState<AssetNode>(),[information,setInformation]=useState<AssetNode>(),[expandedLibrary,setExpandedLibrary]=useState(false),[galleryRoot,setGalleryRoot]=useState('root'),[action,setAction]=useState<{node:AssetNode;kind:'rename'|'trash'|'new-file'|'new-folder'}>(),[undo,setUndo]=useState<{asset:string;id:string;name:string}>()
 useDialogFocus('.asset-library-expanded',expandedLibrary)
 const select=(node:AssetNode)=>{setSelected(node);setNotice('')}
 const context=(node:AssetNode,point:{x:number;y:number})=>{select(node);setMenu({node,...point})}
 const changeMode=(value:'files'|'assets')=>{setMode(value);try{localStorage.setItem('avalon.file-layout',value)}catch{}}
 useEffect(()=>{try{if(localStorage.getItem('avalon.file-layout')==='assets')setMode('assets')}catch{}},[])
 useEffect(()=>{setSelected(undefined);setGalleryRoot('root')},[scopeKey])
 useEffect(()=>setSelected(undefined),[query])
 const refresh=useCallback(()=>{setError('');setRevision(value=>value+1)},[])
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;opening.current++}},[])
 useEffect(()=>{
  let active=true,timer:ReturnType<typeof setTimeout>|undefined;const token=++generation.current,changed=previousScope.current!==scopeKey;previousScope.current=scopeKey;branchRequests.current.clear();if(changed){setBranches({});setTree(undefined)}setBranchErrors({});setLoading(new Set());setError('')
  const read=async()=>{try{const next=await api.call<AssetTree>('assets.tree',scope);if(!active||token!==generation.current)return;setTree(next);setFacets(next.facets);if(!changed)for(const [id,data] of Object.entries(branchSnapshot.current))if(expandedSnapshot.current.has(id))void load({id} as AssetNode,0,Math.min(1000,Math.max(100,data.entries.length)));if(next.errors?.length)setError(next.errors.join('\n'));if(next.indexing)timer=setTimeout(()=>void read(),700)}catch(cause){if(active)setError((cause as Error).message)}}
  void read();return()=>{active=false;clearTimeout(timer)}
 },[scopeKey,revision])
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>|undefined;const off=api.onEvent(event=>{if(event.channel==='store:changed'&&affectsMembers(event.payload)||event.channel==='chat:changed'||event.channel==='channel:changed'&&event.payload.kind!=='reads'){clearTimeout(timer);timer=setTimeout(refresh,200)}});return()=>{off();clearTimeout(timer)}},[refresh])
 const load=useCallback(async(node:AssetNode,at=0,limit=100)=>{
  const token=generation.current,key=node.id;if(branchRequests.current.has(key))return;branchRequests.current.set(key,token);setLoading(previous=>new Set(previous).add(key));setBranchErrors(previous=>({...previous,[key]:''}))
  try{const next=await api.call<Children>('assets.children',{id:key,...scope,hidden,offset:at,limit});if(!alive.current||token!==generation.current)return;setBranches(previous=>({...previous,[key]:{...next,entries:at?[...new Map([...(previous[key]?.entries??[]),...next.entries].map(entry=>[entry.id,entry])).values()]:next.entries}}))}
  catch(cause){if(alive.current&&token===generation.current)setBranchErrors(previous=>({...previous,[key]:(cause as Error).message}))}
  finally{if(branchRequests.current.get(key)===token){branchRequests.current.delete(key);if(alive.current)setLoading(previous=>{const next=new Set(previous);next.delete(key);return next})}}
 },[scopeKey,hidden])
 const toggle=(node:AssetNode)=>{setExpanded(previous=>{const next=new Set(previous);next.has(node.id)?next.delete(node.id):next.add(node.id);return next})}
 useEffect(()=>{const visit=(node:AssetNode)=>{if(node.id.startsWith('company:')&&!node.location&&node.children?.length===1){visit(node.children[0]);return}if(!expanded.has(node.id))return;if(node.location&&!branches[node.id]&&!loading.has(node.id)&&!branchErrors[node.id])void load(node);for(const child of node.location?branches[node.id]?.entries??[]:node.children??[])visit(child)};if(tree)visit(tree)},[tree,expanded,branches,load,branchErrors])

 const rows=useMemo<Row[]>(()=>{if(mode==='assets')return [];const out:Row[]=[];const visit=(node:AssetNode,depth:number)=>{if(node.id.startsWith('company:')&&!node.location&&node.children?.length===1){visit(node.children[0],depth);return}out.push({node,depth});if(!expanded.has(node.id))return;for(const child of node.location?branches[node.id]?.entries??[]:node.children??[])visit(child,depth+1);const more=branches[node.id]?.nextOffset;if(more!==undefined&&more!==null)out.push({node,depth:depth+1,more})};for(const child of tree?.children??[])if(!filters.view||child.name===filters.view)visit(child,0);return out},[tree,branches,expanded,mode,filters.view])
 const virtual=useVirtualizer({count:rows.length,getScrollElement:()=>scroll.current,estimateSize:index=>rows[index]?.more!==undefined?38:rows[index]?.depth===0?45:58,overscan:8,getItemKey:index=>rows[index].node.id+(rows[index].more===undefined?'':':more')})
 useEffect(()=>{scroll.current?.scrollTo({top:0})},[scopeKey,mode,query])
 const locate=async(node:AssetNode)=>{const ticket=++opening.current;setBusy(node.id);setError('');setMenu(undefined);try{await flushPlugins();const value=await api.call<AssetLocation>('assets.locate',{id:node.id});if(alive.current&&ticket===opening.current){if(value.parent.location?.asset)setOpen(value);else toggle(value.node)}}catch(cause){if(alive.current&&ticket===opening.current)setError((cause as Error).message)}finally{if(alive.current&&ticket===opening.current)setBusy(undefined)}}
 const locationFor=async(node:AssetNode):Promise<FileLocation|undefined>=>{
  if(!node.document)return node.location
  let status=await api.call<any>('channel.file-download',node.document)
  while(alive.current&&['queued','running'].includes(status.state)){await new Promise(resolve=>setTimeout(resolve,350));if(!alive.current)return;status=await api.call('channel.file-status',node.document)}
  if(status.state!=='completed')throw Error(status.error??'Download failed')
  refresh();return {asset:node.owner!.conversation!,path:status.path}
 }
 const download=async(node:AssetNode)=>{setBusy(node.id);setMenu(undefined);setError('');try{const from=await locationFor(node);if(from&&alive.current)await downloadFile(from)}catch(cause){if(alive.current)setError((cause as Error).message)}finally{if(alive.current)setBusy(undefined)}}
 const choose=async(node:AssetNode)=>{if(!node.document){await locate(node);return}setBusy(node.id);try{const from=await locationFor(node);if(from?.asset&&alive.current)await locate({...node,id:assetNodeId(from.asset,from.path),document:undefined,location:from})}catch(cause){if(alive.current)setError((cause as Error).message)}finally{if(alive.current)setBusy(undefined)}}

 const drop=async(event:DragEvent,node:AssetNode)=>{if(node.readOnly||!node.directory||!node.location||!hasFileDrop(event.dataTransfer))return;event.preventDefault();try{await dropFiles(event.dataTransfer,node.location);refresh();setNotice(t('Files copied. Originals were kept.'))}catch(cause){setError((cause as Error).message)}}
 const keyboard=(event:KeyboardEvent,row:Row)=>{const node=row.node,at=rows.indexOf(row);if(event.key==='ContextMenu'||event.shiftKey&&event.key==='F10'){event.preventDefault();const box=event.currentTarget.getBoundingClientRect();context(node,{x:box.left+20,y:box.top+25});return}if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='i'){event.preventDefault();setInformation(node);return}if(event.key==='F2'&&!node.locked&&!node.readOnly){event.preventDefault();setAction({node,kind:'rename'});return}if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?rows.length-1:Math.max(0,Math.min(rows.length-1,at+(event.key==='ArrowDown'?1:-1)));select(rows[next].node);virtual.scrollToIndex(next);requestAnimationFrame(()=>scroll.current?.querySelector<HTMLButtonElement>('[data-asset-id="'+CSS.escape(rows[next].node.id)+'"]')?.focus());return}if(event.key==='ArrowRight'&&node.directory&&!expanded.has(node.id)){event.preventDefault();toggle(node)}else if(event.key==='ArrowLeft'&&node.directory&&expanded.has(node.id)){event.preventDefault();toggle(node)}else if(event.key==='Enter'){event.preventDefault();node.directory?toggle(node):void choose(node)}else if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='c'&&node.location&&(!node.locked||!node.directory)){event.preventDefault();copyFile(node.location);setNotice(t('File copied. Choose a folder and paste.'))}else if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='v'&&!node.readOnly&&node.directory&&node.location){event.preventDefault();void pasteFile(node.location).then(refresh).catch(error=>setError(error.message))}}
 const normalize=async(apply=false)=>{setNamingBusy(true);try{await flushPlugins();const next=await api.call<any>('assets.naming',apply?{id:naming.id,apply:true}:{});if(apply){setNaming(undefined);refresh()}else setNaming(next)}catch(cause){setError((cause as Error).message)}finally{setNamingBusy(false)}}
 const activeFilters=Object.entries(filters).filter(([key,value])=>value&&key!=='sort'&&value!=='all').length,scanning=tree?.indexing
 const employees=facets.employees.filter(employee=>!filters.team||employee.team===filters.team)??[]
 const content=<aside className={'shared-drawer asset-browser'+(expandedLibrary?' asset-library-expanded':'')} style={expandedLibrary?undefined:{width,flexBasis:width}} role={expandedLibrary?'dialog':undefined} aria-modal={expandedLibrary||undefined} onKeyDown={event=>{if(event.key==='Escape'&&!event.defaultPrevented&&!open&&!information&&!menu&&!action&&expandedLibrary){event.preventDefault();event.stopPropagation();setExpandedLibrary(false)}}} aria-label={t('Files and assets')}>
  {!expandedLibrary&&<PanelDivider axis="x" value={width} min={260} max={600} label={t('Resize files and assets')} onDraft={onResize} onCommit={value=>api.call('settings.set',{assetDrawerWidth:value}).finally(()=>onResize(undefined))}/>}
  <header><span className="asset-workbench-mark"><Icon name="files"/></span><div><strong>{t('Files and assets')}</strong><small>{t('Every workspace, one place')}</small></div><button aria-label={t(expandedLibrary?'Collapse file library':'Expand file library')} title={t(expandedLibrary?'Collapse file library':'Expand file library')} onClick={()=>setExpandedLibrary(!expandedLibrary)}><Icon name={expandedLibrary?'screen-normal':'screen-full'}/></button><button aria-label={t('Close shared transfer area')} onClick={onClose}><Icon name="close"/></button></header>
  <nav className="asset-view-tabs" aria-label={t('Asset view')}><button aria-pressed={mode==='files'} onClick={()=>changeMode('files')}><Icon name="list-tree"/>{t('Files')}</button><button aria-pressed={mode==='assets'} onClick={()=>changeMode('assets')}><svg className="asset-grid-symbol" viewBox="0 0 16 16" aria-hidden="true"><rect x="1" y="1" width="5" height="5" rx="1"/><rect x="10" y="1" width="5" height="5" rx="1"/><rect x="1" y="10" width="5" height="5" rx="1"/><rect x="10" y="10" width="5" height="5" rx="1"/></svg>{t('Assets')}</button><button aria-label={t('Refresh files')} title={t('Refresh')} onClick={()=>{void api.call('assets.search',{refresh:true,limit:1}).then(()=>{clearAssetCovers();refresh()}).catch(error=>setError(error.message))}}><Icon name={scanning?'loading':'refresh'}/></button></nav>
  <div className="asset-view-scopes" role="group" aria-label={t('Workspace view')}>{[['','All spaces'],['Company','Company'],['Messages','Messages'],['Plan','Plan']].map(([value,label])=><button key={value} aria-pressed={(filters.view??'')===value} onClick={()=>change({view:value as AssetFilters['view']||undefined})}>{t(label)}</button>)}</div>
  <div className="asset-search"><Icon name="search"/><input aria-label={t('Search assets')} value={query} onChange={event=>{setQuery(event.target.value);if(event.target.value)setMode('assets')}} placeholder={t('Search files, people or teams…')}/>{query&&<button aria-label={t('Clear search')} onClick={()=>setQuery('')}><Icon name="close"/></button>}<button aria-label={t('Filter workspaces')} title={t('Filter workspaces')} aria-expanded={filterOpen} data-active={!!activeFilters} onClick={()=>setFilterOpen(!filterOpen)}><Icon name="filter"/>{!!activeFilters&&<b>{activeFilters}</b>}</button></div>
  {filterOpen&&<div className="asset-filter-panel">
   <label>{t('Team')}<AppSelect aria-label={t('Filter by Team')} value={filters.team??''} onChange={event=>change({team:event.target.value||undefined,employee:undefined})}><option value="">{t('All teams')}</option>{facets.teams.map(team=><option key={team} value={team}>{team}</option>)}</AppSelect></label>
   <label>{t('Employee')}<AppSelect aria-label={t('Filter by employee')} value={filters.employee??''} onChange={event=>change({employee:event.target.value||undefined})}><option value="">{t('All employees')}</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{employee.name} · {employee.team}</option>)}</AppSelect></label>
   <label>{t('Storage host')}<AppSelect aria-label={t('Filter by host')} value={filters.host??''} onChange={event=>change({host:event.target.value||undefined})}><option value="">{t('All hosts')}</option>{facets.hosts?.map(host=><option key={host.id} value={host.id}>{host.kind==='local'?t('Core host'):host.name}</option>)}</AppSelect></label>
   <label>{t('Conversation')}<AppSelect aria-label={t('Filter by conversation')} value={filters.conversation??''} onChange={event=>change({conversation:event.target.value||undefined})}><option value="">{t('All groups and channels')}</option>{facets.conversations.map(conversation=><option key={conversation.id} value={conversation.id}>{conversation.name} · {t(conversation.kind==='group'?'Group':'Channel')}</option>)}</AppSelect></label>
   <div className="asset-filter-pair"><label>{t('File type')}<AppSelect aria-label={t('File type')} value={filters.kind??'all'} onChange={event=>{change({kind:event.target.value});setMode('assets')}}>{ASSET_KINDS.map(kind=><option key={kind} value={kind}>{t(kinds[kind])}</option>)}</AppSelect></label><label>{t('Storage')}<AppSelect aria-label={t('Storage')} value={filters.storage??''} onChange={event=>{change({storage:event.target.value as AssetFilters['storage']||undefined});setMode('assets')}}><option value="">{t('Any storage')}</option><option value="local">{t('Local')}</option><option value="remote">{t('Remote host')}</option><option value="cloud">{t('Cloud only')}</option></AppSelect></label></div>
   <footer><label><input type="checkbox" checked={hidden} onChange={event=>{setHidden(event.target.checked);refresh()}}/>{t('Show hidden files')}</label><button onClick={()=>{setFilters({});setQuery('')}}>{t('Clear filters')}</button></footer>
  </div>}
  <div className="asset-results-heading"><span>{mode==='files'?t('WORKSPACES'):t('FILES')}{activeFilters>0?' · '+activeFilters+' '+t('filters'):''}</span>{mode==='assets'&&<AppSelect aria-label={t('Sort files')} value={filters.sort??'name'} onChange={event=>change({sort:event.target.value as AssetFilters['sort']})}><option value="name">{t('Name')}</option><option value="modified">{t('Recently modified')}</option><option value="size">{t('Largest first')}</option></AppSelect>}</div>
  {error&&<div className="asset-error" role="alert"><Icon name="warning"/><span>{assetError(error)}</span><button onClick={refresh}>{t('Retry')}</button></div>}{notice&&<div className="asset-notice" role="status">{notice}<button aria-label={t('Close')} onClick={()=>setNotice('')}><Icon name="close"/></button></div>}
  {selected&&<div className="asset-selected-bar"><span>{assetTitle(selected)}</span><button aria-label={t('Get Info')} onClick={()=>setInformation(selected)}><Icon name="info"/>{t('Get Info')}</button></div>}
  {mode==='assets'?<AssetGallery initialRoot={galleryRoot} onFolder={node=>setGalleryRoot(node.id)} filters={filters} query={query} revision={revision} hidden={hidden} selected={selected?.id} onSelect={select} onOpen={node=>void choose(node)} onLocate={node=>void locate(node)} onContext={context} onDrop={drop} onInfo={setInformation} onClearSearch={()=>setQuery('')}/>:<>
  <div ref={scroll} className="asset-scroll" role="tree" aria-label={t('Company file tree')} aria-busy={!tree||!!tree.indexing}>
   {!rows.length&&<div className="asset-empty"><Icon name={scanning?'loading':'search'}/><strong>{t(scanning||!tree?'Loading files…':'No files match these filters')}</strong><p>{t('Choose another workspace or clear the filters. Your files stay in their original folders.')}</p>{(query||!!activeFilters)&&<button onClick={()=>{setFilters({});setQuery('')}}>{t('Clear filters')}</button>}</div>}
   <div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(item=>{const row=rows[item.index],node=row.node,title=assetTitle(node),failure=branchErrors[node.id];return <div key={item.key} data-selected={selected?.id===node.id||undefined} onContextMenu={event=>{event.preventDefault();event.stopPropagation();context(node,{x:event.clientX,y:event.clientY})}} className={'asset-row'+(row.depth===0?' asset-section-row':'')} style={{position:'absolute',top:0,left:0,width:'100%',height:item.size,transform:`translateY(${item.start}px)`}}>
    {row.more!==undefined?<button className="asset-more" style={{paddingLeft:row.depth*13+12}} disabled={loading.has(node.id)} onClick={()=>void load(node,row.more)}>{t('Load more')}</button>:<><button className="asset-entry" role="treeitem" aria-level={row.depth+1} aria-expanded={node.directory?expanded.has(node.id):undefined} data-asset-id={node.id} data-directory={node.directory} data-locked={node.locked} style={{paddingLeft:row.depth*13+10}} title={[title,ownerLine(node),node.host?.name].filter(Boolean).join(' · ')} onClick={()=>{select(node);if(node.directory)toggle(node)}} onDoubleClick={()=>!node.directory?void choose(node):node.location?void locate(node):undefined} onKeyDown={event=>keyboard(event,row)} draggable={!!node.location&&(!node.locked||!node.directory)} onDragStart={event=>node.location&&dragFile(event.dataTransfer,node.location)} onDragOver={event=>{if(!node.readOnly&&node.directory&&node.location&&hasFileDrop(event.dataTransfer)){event.preventDefault();event.dataTransfer.dropEffect='copy'}}} onDrop={event=>void drop(event,node)}>
     {<span className="asset-disclosure">{node.directory&&<Icon name={loading.has(node.id)?'loading':expanded.has(node.id)?'chevron-down':'chevron-right'}/>}</span>}<span className={'asset-file-icon kind-'+(node.kind??'folder')}><AssetGlyph node={node}/></span>
     <span className="asset-name"><strong>{node.owner?title:t(title)}</strong>{row.depth>0&&<small className="asset-subtitle"><span>{node.owner?.employeeName?[node.owner.team,t(roles[node.kind??'']??'Folder')].filter(Boolean).join(' · '):t(roles[node.kind??'']??(node.directory?'Folder':node.kind&&kinds[node.kind]||'File'))}</span><AssetHostBadge node={node}/></small>}</span>
     {node.directory&&<span className="asset-folder-count" title={t('Files in this workspace')}>{scanning?'…':node.fileCount??'0'}</span>}
    </button><div className="asset-file-actions">{node.location||node.document?<button disabled={busy===node.id} aria-label={t(node.directory?'Open folder: {0}':'Show in folder: {0}',[title])} title={t(node.directory?'Open folder':'Show in folder')} onClick={()=>void locate(node)}><Icon name={busy===node.id?'loading':'folder-opened'}/></button>:null}{(node.location||node.document)&&<button aria-label={t('Actions for {0}',[title])} aria-expanded={menu?.node.id===node.id} title={t('File actions')} onClick={event=>{const box=event.currentTarget.getBoundingClientRect();context(node,{x:box.right-230,y:box.bottom+4})}}><Icon name="ellipsis"/></button>}</div>{failure&&<button className="asset-branch-error" title={assetError(failure)} aria-label={t('Retry folder: {0}',[title])} onClick={()=>void load(node)}><Icon name="warning"/></button>}</>}
   </div>})}</div>
  </div></>}
  <footer><span>{scanning?t('Indexing…'):mode==='files'?t('Folders load when expanded'):t('Original files stay in their workspaces')}</span><button className="asset-folder-policy" disabled={namingBusy} aria-label={t('English folder names')} title={t('English folder names')} onClick={()=>void normalize()}><Icon name="symbol-string"/></button></footer>
  {menu&&<MessageMenu motion="file-menu" className="asset-context-menu" label={t('File actions')} anchor={menu} onClose={()=>setMenu(undefined)}>
   <button role="menuitem" onClick={()=>{const node=menu.node;setMenu(undefined);setInformation(node)}}><Icon name="info"/>{t('Get Info')}</button><hr/>
   <button role="menuitem" onClick={()=>void locate(menu.node)}><Icon name="folder-opened"/>{t(menu.node.directory?'Open folder':'Show in folder')}</button>
   {!menu.node.directory&&!menu.node.symlink&&<button role="menuitem" onClick={()=>void download(menu.node)}><Icon name="cloud-download"/>{t('Download file')}</button>}
   {menu.node.location&&<>{(!menu.node.directory||!menu.node.locked)&&<button role="menuitem" onClick={()=>{copyFile(menu.node.location!);setNotice(t('File copied. Choose a folder and paste.'));setMenu(undefined)}}><Icon name="copy"/>{t('Copy file')}</button>}</>}
   {menu.node.location&&!menu.node.readOnly&&<>{menu.node.directory&&<><button role="menuitem" onClick={()=>{const node=menu.node;setMenu(undefined);setAction({node,kind:'new-folder'})}}><Icon name="new-folder"/>{t('New folder')}</button><button role="menuitem" onClick={()=>{const node=menu.node;setMenu(undefined);setAction({node,kind:'new-file'})}}><Icon name="new-file"/>{t('New file')}</button><button role="menuitem" onClick={()=>{const node=menu.node;setMenu(undefined);void pasteFile(node.location!).then(refresh).catch(cause=>setError(cause.message))}}><Icon name="clippy"/>{t('Paste')}</button></>}{!menu.node.locked&&<><hr/><button role="menuitem" onClick={()=>{const node=menu.node;setMenu(undefined);setAction({node,kind:'rename'})}}><Icon name="edit"/>{t('Rename')}</button><button role="menuitem" className="danger" onClick={()=>{const node=menu.node;setMenu(undefined);setAction({node,kind:'trash'})}}><Icon name="trash"/>{t('Move to Trash')}</button></>}</>}
   {availableFinder(menu.node)&&<><hr/><button role="menuitem" onClick={()=>{const node=menu.node;setMenu(undefined);void revealFile(node.location).catch(error=>setError(error.message))}}><Icon name="desktop-download"/>{t('Open in Finder')}</button></>}
  </MessageMenu>}
  {undo&&<div className="asset-undo" role="status"><span>{t('Moved {0} to Trash',[undo.name])}</span><button onClick={()=>void api.call('assets.file',{id:undo.asset,operation:'restore',trashId:undo.id}).then(()=>{setUndo(undefined);refresh()}).catch(cause=>setError(cause.message))}>{t('Undo')}</button></div>}
  {information&&<AssetInfoDialog key={information.id} node={information} onClose={()=>setInformation(undefined)}/>}
  {action&&<AssetActionDialog {...action} onClose={()=>setAction(undefined)} onDone={result=>{if(action.kind==='trash')setUndo({asset:action.node.location!.asset!,id:result.id,name:assetTitle(action.node)});setAction(undefined);setSelected(undefined);refresh()}}/>}
  {naming&&<div className="asset-naming-review" role="region" aria-label={t('Directory migration preview')}><strong>{t('Directory migration preview')}</strong><p>{naming.local.length+naming.remote.reduce((n:number,item:any)=>n+item.renames.length,0)} {t('folders')} · {t('Files and employee identities are preserved.')}</p><div>{naming.local.slice(0,30).map((item:any)=><small key={item.from}>{item.from} → {item.to}</small>)}</div><button disabled={namingBusy} onClick={()=>void normalize(true)}>{t('Apply English names')}</button><button disabled={namingBusy} onClick={()=>setNaming(undefined)}>{t('Close')}</button></div>}
  {open?.parent.location?.asset&&<AssetPreview value={open} onClose={()=>{opening.current++;setOpen(undefined);refresh()}} onError={setError}/>}
 </aside>
 return expandedLibrary?createPortal(<div className="asset-library-shell"><div className="asset-library-backdrop" onClick={()=>setExpandedLibrary(false)}/>{content}</div>,document.body):content
}
