import {createPortal} from 'react-dom'
import {useEffect,useMemo,useRef,useState} from 'react'
import {useVirtualizer} from '@tanstack/react-virtual'
import type {AssetNode,AssetPage} from '../../../shared/asset-schema'
import {api} from '../api'
import {Icon} from './Icon'
import {FileWorkspace} from './FileWorkspace'
import {PanelDivider} from './PanelDivider'
import {revealFile,downloadFile} from '../file-actions'
import {flushPlugins} from '../plugins'
import {dragFile,dropFiles,hasFileDrop,copyFile,pasteFile} from '../file-transfers'
import {translate as uiText} from '../i18n'
import '../styles/asset-browser.css'

type Children={entries:AssetNode[];total:number;nextOffset:number|null}
type Row={node:AssetNode;depth:number;more?:number}
export function AssetBrowser({onClose,width=320,onResize}:{onClose:()=>void;width?:number;onResize:(width:number|undefined)=>void}){
 const [tree,setTree]=useState<AssetNode>(),[branches,setBranches]=useState<Record<string,Children>>({}),[expanded,setExpanded]=useState(new Set(['root','company'])),[mode,setMode]=useState<'files'|'assets'>('files'),[query,setQuery]=useState(''),[hidden,setHidden]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(new Set<string>()),[page,setPage]=useState<AssetPage>(),[offset,setOffset]=useState(0),[open,setOpen]=useState<AssetNode>()
 const [naming,setNaming]=useState<any>(),[namingBusy,setNamingBusy]=useState(false)
 const [revision,setRevision]=useState(0)
 const wasIndexing=useRef(false)
 const scroll=useRef<HTMLDivElement>(null),requestVersion=useRef(0)
 const refresh=async()=>{try{setError('');setTree(await api.call<AssetNode>('assets.tree'));setBranches({});setRevision(value=>value+1)}catch(error){setError((error as Error).message)}}
 useEffect(()=>{void refresh()},[])
 useEffect(()=>{if(!tree?.indexing)return;const timer=setTimeout(()=>void api.call<AssetNode>('assets.tree').then(setTree).catch(error=>setError(error.message)),700);return()=>clearTimeout(timer)},[tree])
 const load=async(node:AssetNode,offset=0)=>{setLoading(previous=>new Set(previous).add(node.id));try{const data=await api.call<Children>('assets.children',{id:node.id,hidden,offset,limit:500});setBranches(previous=>({...previous,[node.id]:{...data,entries:offset?[...(previous[node.id]?.entries??[]),...data.entries]:data.entries}}))}catch(error){setError((error as Error).message)}finally{setLoading(previous=>{const next=new Set(previous);next.delete(node.id);return next})}}
 const toggle=(node:AssetNode)=>{setExpanded(previous=>{const next=new Set(previous);next.has(node.id)?next.delete(node.id):next.add(node.id);return next});if(!expanded.has(node.id)&&node.location&&!branches[node.id])void load(node)}
 useEffect(()=>{const visit=(node:AssetNode)=>{if(node.location){if(expanded.has(node.id)&&!branches[node.id]&&!loading.has(node.id))void load(node);for(const child of branches[node.id]?.entries??[])visit(child)}else for(const child of node.children??[])visit(child)};if(tree)visit(tree)},[tree,expanded,branches,hidden])
 const rows=useMemo<Row[]>(()=>{
  if(mode==='assets')return (page?.entries??[]).map(node=>({node,depth:0}))
  const result:Row[]=[];const visit=(node:AssetNode,depth:number)=>{result.push({node,depth});if(!expanded.has(node.id))return;for(const child of node.location?branches[node.id]?.entries??[]:node.children??[])visit(child,depth+1);const more=branches[node.id]?.nextOffset;if(more!==undefined&&more!==null)result.push({node,depth:depth+1,more})};if(tree)visit(tree,0);return result
 },[tree,branches,expanded,mode,page])
 useEffect(()=>{if(wasIndexing.current&&!tree?.indexing)for(const row of rows)if(row.node.directory&&row.node.location&&expanded.has(row.node.id))void load(row.node);wasIndexing.current=!!tree?.indexing},[tree?.indexing])
 const virtual=useVirtualizer({count:rows.length,getScrollElement:()=>scroll.current,estimateSize:()=>mode==='assets'?64:30,overscan:12,getItemKey:index=>rows[index].node.id+(rows[index].more===undefined?'':':more')})
 useEffect(()=>{if(mode!=='assets')return;const version=++requestVersion.current;let active=true,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const data=await api.call<AssetPage>('assets.search',{query,offset,limit:100,hidden});if(active&&version===requestVersion.current){setPage(data);setError(data.errors.join('\n'));if(data.indexing)timer=setTimeout(()=>void poll(),700)}}catch(error){if(active)setError((error as Error).message)}};timer=setTimeout(()=>void poll(),160);return()=>{active=false;clearTimeout(timer)}},[mode,query,offset,hidden,revision])
 const normalize=async(apply=false)=>{setNamingBusy(true);try{await flushPlugins();const result=await api.call<any>('assets.naming',apply?{id:naming.id,apply:true}:{});if(apply){setNaming(undefined);await refresh()}else setNaming(result)}catch(error){setError((error as Error).message)}finally{setNamingBusy(false)}}
 const locationFor=async(node:AssetNode)=>{
  if(!node.document)return node.location
  let status=await api.call<any>('channel.file-download',node.document)
  while(['queued','running'].includes(status.state)){await new Promise(resolve=>setTimeout(resolve,300));status=await api.call('channel.file-status',node.document)}
  if(status.state!=='completed')throw Error(status.error??'Download failed')
  return {asset:node.owner!.conversation!,path:status.path}
 }
 const choose=async(node:AssetNode)=>{try{await flushPlugins();setError('');setOpen({...node,location:await locationFor(node)})}catch(error){setError((error as Error).message)}}
 const drop=async(event:React.DragEvent,node:AssetNode)=>{if(!node.directory||!node.location||!hasFileDrop(event.dataTransfer))return;event.preventDefault();try{await dropFiles(event.dataTransfer,node.location);await load(node);void refresh()}catch(error){setError((error as Error).message)}}
 const keyboard=(event:React.KeyboardEvent,row:Row)=>{const node=row.node;const at=rows.indexOf(row);if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?rows.length-1:Math.max(0,Math.min(rows.length-1,at+(event.key==='ArrowDown'?1:-1)));virtual.scrollToIndex(next);requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>('[data-asset-id="'+CSS.escape(rows[next].node.id)+'"]')?.focus());return}if(event.key==='ArrowRight'&&node.directory&&!expanded.has(node.id)){event.preventDefault();toggle(node)}else if(event.key==='ArrowLeft'&&node.directory&&expanded.has(node.id)){event.preventDefault();toggle(node)}else if(event.key==='Enter'){event.preventDefault();node.directory?toggle(node):void choose(node)}else if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='c'&&node.location&&(!node.locked||!node.directory)){event.preventDefault();copyFile(node.location)}else if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='v'&&node.directory&&node.location){event.preventDefault();void pasteFile(node.location).then(()=>load(node)).catch(error=>setError(error.message))}}
 return <aside className="shared-drawer asset-browser" style={{width,flexBasis:width}} aria-label={uiText('Files and assets')}>
  <PanelDivider axis="x" value={width} min={260} max={600} label={uiText('Resize files and assets')} onDraft={onResize} onCommit={value=>api.call('settings.set',{assetDrawerWidth:value}).finally(()=>onResize(undefined))}/>
  <header><div><strong>Anexus</strong><small>{uiText('Files and assets')}</small></div><button aria-label={uiText('Close shared transfer area')} onClick={onClose}><Icon name="close"/></button></header>
  <nav className="asset-view-tabs" aria-label={uiText('Asset view')}><button aria-pressed={mode==='files'} onClick={()=>setMode('files')}><Icon name="list-tree"/>{uiText('Files')}</button><button aria-pressed={mode==='assets'} onClick={()=>setMode('assets')}><Icon name="files"/>{uiText('Assets')}</button><button title={uiText('Refresh')} onClick={()=>{void api.call('assets.search',{refresh:true,limit:1}).then(()=>refresh()).then(()=>setPage(undefined)).catch(error=>setError(error.message))}}><Icon name="refresh"/></button></nav>
  <div className="asset-folder-policy"><button disabled={namingBusy} onClick={()=>void normalize()}><Icon name="symbol-string"/>{uiText('English folder names')}</button></div>
  <div className="asset-search"><Icon name="search"/><input aria-label={uiText('Search assets')} value={query} onChange={event=>{setQuery(event.target.value);setOffset(0);if(event.target.value)setMode('assets')}} placeholder={uiText('Search assets…')}/><button aria-pressed={hidden} title={uiText('Show hidden files')} onClick={()=>{setHidden(!hidden);setBranches({})}}><Icon name="eye"/></button></div>
  {error&&<div className="asset-error" role="alert">{error}</div>}
  <div ref={scroll} className="asset-scroll" role={mode==='files'?'tree':'list'} aria-label={uiText(mode==='files'?'Company file tree':'Company assets')}>
   <div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(item=>{const row=rows[item.index],node=row.node;return <div key={item.key} className={'asset-row '+(mode==='assets'?'asset-list-row':'')} style={{position:'absolute',top:0,left:0,width:'100%',height:item.size,transform:`translateY(${item.start}px)`}}>
    {row.more!==undefined?<button className="asset-more" style={{paddingLeft:row.depth*15+12}} disabled={loading.has(node.id)} onClick={()=>void load(node,row.more)}>{uiText('Load more')}</button>:<button className="asset-entry" role={mode==='files'?'treeitem':'listitem'} aria-level={mode==='files'?row.depth+1:undefined} aria-expanded={node.directory?expanded.has(node.id):undefined} data-asset-id={node.id} data-directory={node.directory} data-locked={node.locked} style={{paddingLeft:mode==='files'?row.depth*15+8:12}} title={[node.name,node.label,node.owner?.label,node.location?.path].filter(Boolean).join('\n')} onClick={()=>node.directory?toggle(node):void choose(node)} onDoubleClick={()=>node.directory&&node.location?void choose(node):undefined} onKeyDown={event=>keyboard(event,row)} draggable={!!node.location&&(!node.locked||!node.directory)} onDragStart={event=>node.location&&dragFile(event.dataTransfer,node.location)} onDragOver={event=>{if(node.directory&&node.location&&hasFileDrop(event.dataTransfer)){event.preventDefault();event.dataTransfer.dropEffect='copy'}}} onDrop={event=>void drop(event,node)}>
     {mode==='files'&&<span className="asset-disclosure">{node.directory&&<Icon name={loading.has(node.id)?'loading':expanded.has(node.id)?'chevron-down':'chevron-right'}/>}</span>}<Icon name={node.directory?'folder':/\.pdf$/i.test(node.name)?'file-pdf':'file'} />
     <span className="asset-name"><strong>{node.name}</strong>{mode==='assets'&&<small>{node.owner?.label} · {node.location?.path}</small>}</span>{node.directory?<span className="asset-folder-count" title={uiText('Direct nonempty subfolders')}>{node.nonemptyFolders??'…'}</span>:mode==='assets'&&<span className="asset-type">{node.name.split('.').at(-1)?.toUpperCase()}</span>}
    </button>}{row.more===undefined&&<div className="asset-file-actions"><button aria-label={uiText('Open in Finder: {0}',[node.name])} title={uiText('Open in Finder')} onClick={()=>{setError('');void revealFile(node.location).catch(error=>setError(error.message))}}><Icon name="folder-opened"/></button>{!node.directory&&!node.symlink&&<button aria-label={uiText('Download {0}',[node.name])} title={uiText('Download file')} onClick={()=>{setError('');void locationFor(node).then(from=>from&&downloadFile(from)).catch(error=>setError(error.message))}}><Icon name="cloud-download"/></button>}</div>}
   </div>})}</div>
  </div>
  <footer>{mode==='assets'?<><span>{page?.indexing?uiText('Indexing…'):`${page?.total??0} ${uiText('files')}`}</span><button disabled={!offset} onClick={()=>{setOffset(Math.max(0,offset-100));scroll.current?.scrollTo({top:0})}}><Icon name="chevron-left"/></button><button disabled={!page||offset+100>=page.total} onClick={()=>{setOffset(offset+100);scroll.current?.scrollTo({top:0})}}><Icon name="chevron-right"/></button></>:<span>{tree?.indexing?uiText('Indexing…'):uiText('Folders load when expanded')}</span>}</footer>
  {naming&&<div className="asset-naming-review" role="region" aria-label={uiText('Directory migration preview')}><strong>{uiText('Directory migration preview')}</strong><p>{naming.local.length+naming.remote.reduce((n:number,item:any)=>n+item.renames.length,0)} {uiText('folders')} · {uiText('Files and employee identities are preserved.')}</p><div>{naming.local.slice(0,30).map((item:any)=><small key={item.from}>{item.from} → {item.to}</small>)}</div><button disabled={namingBusy} onClick={()=>void normalize(true)}>{uiText('Apply English names')}</button><button disabled={namingBusy} onClick={()=>setNaming(undefined)}>{uiText('Close')}</button></div>}
  {open?.location?.asset&&createPortal(<div className="asset-workspace-overlay" onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();void flushPlugins().then(()=>{setOpen(undefined);void refresh()}).catch(error=>setError(error.message))}}}><div className="panel-backdrop" onClick={()=>void flushPlugins().then(()=>{setOpen(undefined);void refresh()}).catch(error=>setError(error.message))}/><section className="team-workspace" role="dialog" aria-modal="true" aria-label={uiText('Asset workspace')}><header className="workspace-header"><button onClick={()=>void flushPlugins().then(()=>{setOpen(undefined);void refresh()}).catch(error=>setError(error.message))}><Icon name="arrow-left"/>{uiText('Back')}</button><div><strong>{open.owner?.label??open.name}</strong><small>{open.name}</small></div></header><FileWorkspace readOnly={open.readOnly} key={open.location.asset+'/'+open.location.path} assetRoot={open.location.asset} initialFolder={open.directory?open.location.path:open.location.path.split('/').slice(0,-1).join('/')} initialFile={open.directory?'':open.location.path}/></section></div>,document.body)}
 </aside>
}
