import {useEffect,useRef,useState} from 'react'
import {api} from '../api'
import {translate as uiText,useI18n,interfaceLocale} from '../i18n'
import type {ConversationPolicy} from '../../../shared/conversation-controls'
import type {PostTrigger} from '../../../shared/message-collaboration'
import {Icon} from './Icon'
import '../styles/message-collaboration.css'

type History={id:string;employeeId:string;postCount:number;state:string;createdAt:number;messageId?:string;error?:string}
type Batch={id:string;total:number;offset:number;hasMore:boolean;posts:{id:string;available:boolean;post?:{title:string;body:string};error?:string}[]}
export function ChannelPostTriggers({policy,onDirty,onBusy}:{policy:ConversationPolicy;onDirty:(value:boolean)=>void;onBusy:(value:boolean)=>void}){
 useI18n()
 const id=policy.conversation.slice(8),canManage=policy.allowedActions.includes('roles'),[rules,setRules]=useState<PostTrigger[]>([]),[history,setHistory]=useState<History[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<{employee:string;rule?:PostTrigger}|null>(null),[removing,setRemoving]=useState<PostTrigger|null>(null),[batch,setBatch]=useState<Batch|null>(null)
 const active=useRef(true),dirty=useRef(false),lock=useRef(false)
 const load=async()=>{const [list,runs]=await Promise.all([api.call<{rules:PostTrigger[]}>('channel.post-trigger-list',{id}),api.call<{rows:History[];total:number}>('channel.post-trigger-history',{id,offset,limit:10})]);if(active.current){setRules(list.rules);setHistory(runs.rows);setTotal(runs.total)}}
 useEffect(()=>{active.current=true;let timer:ReturnType<typeof setTimeout>|undefined;void load().catch(cause=>active.current&&setError(cause.message));const off=api.onEvent(event=>{if((event.channel==='channel:changed'&&event.payload?.channelIds?.includes(id)||event.channel==='conversation:controls'&&event.payload?.conversation===policy.conversation)&&!timer)timer=setTimeout(()=>{timer=undefined;void load().catch(cause=>active.current&&setError(cause.message))},150)});return()=>{active.current=false;clearTimeout(timer);off()}},[id,offset])
 const changed=(value:boolean)=>{dirty.current=value;onDirty(value)}
 const run=async(work:()=>Promise<unknown>)=>{if(lock.current)return;lock.current=true;setBusy(true);onBusy(true);setError('');try{await work();setEditing(null);setRemoving(null);changed(false);await load()}catch(cause){setError((cause as Error).message)}finally{lock.current=false;setBusy(false);onBusy(false)}}
 const inspect=async(batchId:string,start=0)=>{try{setBatch(await api.call<Batch>('channel.post-trigger-batch',{id,batchId,offset:start,limit:10}));setError('')}catch(cause){setError((cause as Error).message)}}
 const name=(employee:string)=>policy.members.find(m=>m.id===employee)?.name??uiText('Removed Agent')
 return <section className="channel-post-rules" aria-label={uiText('Post-count notifications')}>
  <header><span className="conversation-control-mark"><Icon name="list-ordered"/></span><div><h3>{uiText('Post-count notifications')}</h3><p>{uiText('Each Agent has a separate counter and prompt. Reaching the threshold runs that Agent in this channel, independently of Plan.')}</p></div></header>
  <p className="conversation-control-note">{uiText('Only new posts count. Edits, duplicates, discussion replies and scheduled notices do not. A saved rule replaces per-post reading for its Agent; paused rules stay quiet.')}</p>
  {error&&<p role="alert" className="conversation-control-error">{uiText(error)} <button disabled={busy} onClick={()=>void load().catch(cause=>setError(cause.message))}>{uiText('Reload')}</button></p>}
  {removing&&<div className="conversation-control-confirm" role="alert"><p>{uiText('Remove this count rule? Pending batches stop and ordinary per-post reading resumes.')}</p><button disabled={busy} onClick={()=>void run(()=>api.call('channel.post-trigger-remove',{id,employee:removing.employeeId,expectedRevision:removing.revision}))}>{uiText('Confirm')}</button><button disabled={busy} onClick={()=>setRemoving(null)}>{uiText('Cancel')}</button></div>}
  {editing?<PostRuleEditor key={editing.employee} name={name(editing.employee)} rule={editing.rule} busy={busy} onDirty={()=>changed(true)} onCancel={()=>{if(dirty.current){setError(uiText('Save your changes, or use the close button to discard them.'));return}setEditing(null)}} onSave={values=>run(()=>api.call('channel.post-trigger-set',{id,employee:editing.employee,expectedRevision:editing.rule?.revision??0,...values}))}/>:<div className="channel-post-rule-list">{[...policy.members,...rules.filter(rule=>!policy.members.some(member=>member.id===rule.employeeId)).map(rule=>({id:rule.employeeId,name:uiText('Removed Agent')}))].map(member=>{const rule=rules.find(r=>r.employeeId===member.id);return <article key={member.id} data-post-rule-employee={member.id}><header><div><strong>{member.name}</strong><small>{rule?uiText('Every {0} new posts',[rule.everyPosts]):uiText('No count rule')}</small></div><span className={'conversation-notice-state '+(rule?.enabled?'scheduled':'paused')}>{uiText(rule?rule.enabled?'Enabled':'Paused':'Not configured')}</span></header>{rule&&<><progress aria-label={uiText('Post-count progress for {0}',[member.name])} value={rule.pendingCount} max={rule.everyPosts}/><small>{uiText('{0} counted · {1} remaining',[rule.pendingCount,rule.remaining])}</small><p className="channel-post-rule-prompt">{rule.prompt}</p>{rule.disabledReason&&<p role="status" className="conversation-control-warning">{uiText(rule.disabledReason)}</p>}</>}<footer>{canManage&&policy.members.some(item=>item.id===member.id)&&<button disabled={busy} onClick={()=>{changed(false);setEditing({employee:member.id,rule})}}><Icon name="edit"/>{uiText(rule?'Edit rule':'Configure')}</button>}{canManage&&rule&&<><button disabled={busy||!policy.members.some(item=>item.id===member.id)} onClick={()=>void run(()=>api.call('channel.post-trigger-set',{id,employee:member.id,everyPosts:rule.everyPosts,prompt:rule.prompt,enabled:!rule.enabled,expectedRevision:rule.revision}))}><Icon name={rule.enabled?'debug-pause':'play'}/>{uiText(rule.enabled?'Pause':'Resume')}</button><button disabled={busy} onClick={()=>setRemoving(rule)}><Icon name="trash"/>{uiText('Remove rule')}</button></>}</footer></article>})}</div>}
  <details className="conversation-notice-history"><summary>{uiText('Post batch history')} · {total}</summary>{history.map(item=><button type="button" className="channel-post-history-row" key={item.id} onClick={()=>void inspect(item.id)}><span><strong>{name(item.employeeId)}</strong><small>{uiText('{0} posts',[item.postCount])} · {new Date(item.createdAt).toLocaleString(interfaceLocale())}</small>{item.error&&<small>{item.error}</small>}</span><span>{uiText(item.state)}</span><Icon name="chevron-right"/></button>)}{!history.length&&<p>{uiText('No counted batches yet.')}</p>}{total>10&&<footer><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-10))}>{uiText('Previous')}</button><button disabled={offset+10>=total} onClick={()=>setOffset(offset+10)}>{uiText('Next')}</button></footer>}</details>
  {batch&&<section className="channel-post-batch" aria-label={uiText('Counted source posts')}><header><h4>{uiText('Counted source posts')} · {batch.total}</h4><button aria-label={uiText('Close batch details')} onClick={()=>setBatch(null)}><Icon name="close"/></button></header>{batch.posts.map(post=><article key={post.id}><strong>{post.post?.title||post.id}</strong><p>{post.available?post.post?.body:post.error}</p></article>)}<footer><button disabled={batch.offset===0} onClick={()=>void inspect(batch.id,Math.max(0,batch.offset-10))}>{uiText('Previous')}</button><button disabled={!batch.hasMore} onClick={()=>void inspect(batch.id,batch.offset+10)}>{uiText('Next')}</button></footer></section>}
 </section>
}
function PostRuleEditor({name,rule,busy,onDirty,onSave,onCancel}:{name:string;rule?:PostTrigger;busy:boolean;onDirty:()=>void;onSave:(value:{everyPosts:number;prompt:string;enabled:boolean})=>Promise<void>;onCancel:()=>void}){
 const [everyPosts,setEvery]=useState(rule?.everyPosts??100),[prompt,setPrompt]=useState(rule?.prompt??''),[enabled,setEnabled]=useState(rule?.enabled??false)
 return <form className="channel-post-rule-editor" onChange={onDirty} onSubmit={event=>{event.preventDefault();void onSave({everyPosts,prompt:prompt.trim(),enabled})}}><h4>{name}</h4><label>{uiText('Notify after new posts')}<input type="number" name="post-count-threshold" min={1} max={10000} required value={everyPosts} disabled={busy} onChange={event=>setEvery(Number(event.target.value))}/></label><label>{uiText('Agent prompt')}<textarea name="post-count-prompt" rows={5} required maxLength={16000} value={prompt} disabled={busy} placeholder={uiText('Describe what this Agent should do with the counted posts.')} onChange={event=>setPrompt(event.target.value)}/></label><label className="channel-post-rule-enable"><span>{uiText('Enable this Agent’s count rule')}</span><input name="post-count-enabled" type="checkbox" checked={enabled} disabled={busy} onChange={event=>setEnabled(event.target.checked)}/></label><p className="conversation-control-note">{uiText('Saving starts a fresh counter for this Agent. It does not count older posts or change other Agents’ rules. Running an Agent may consume model credits.')}</p><footer><button type="button" disabled={busy} onClick={onCancel}>{uiText('Back')}</button><button className="primary" disabled={busy||!prompt.trim()}>{uiText('Save count rule')}</button></footer></form>
}
