import {useEffect,useLayoutEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import type {ChannelSource,ChannelView,ChannelPlugin} from '../../../shared/channels'
import {api} from '../api'
import {translate as uiText,useI18n} from '../i18n'
import {useDialogFocus} from '../office/useDialogFocus'
import {useSurfaceMotion} from '../chat/surfaceMotion'
import {ChannelAvatar,ChannelImage,channelPlatform} from './ChannelNewsCard'
import {Icon} from './Icon'
import {AppSelect} from './AppSelect'

const channelChoice=(label:string,channel?:ChannelView,fallback:ChannelView['kind']='custom')=><span className="channel-source-choice"><ChannelAvatar kind={channel?.kind??fallback} avatar={channel?.avatar} name={channel?.name??label}/><span>{label}</span></span>

export function ChannelSourcesDialog({sourceId,channelId,onClose}:{sourceId?:string;channelId?:string;onClose:()=>void}){
 useI18n()
 const surface=useSurfaceMotion<HTMLDivElement>('dialog'),alive=useRef(true),lock=useRef(false),list=useRef<HTMLDivElement>(null),body=useRef<HTMLDivElement>(null),search=useRef<HTMLInputElement>(null),positioned=useRef<string|undefined>(undefined)
 const [sources,setSources]=useState<ChannelSource[]>([]),[channels,setChannels]=useState<ChannelView[]>([]),[selected,setSelected]=useState(sourceId),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[adding,setAdding]=useState(false),[plugin,setPlugin]=useState<ChannelPlugin>('x'),[locator,setLocator]=useState(''),[target,setTarget]=useState(channelId??''),[newChannel,setNewChannel]=useState(false),[name,setName]=useState(''),[query,setQuery]=useState('')
 useDialogFocus('.channel-sources-dialog',true)
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!event.isComposing&&(event.target===document.body||event.target===document.documentElement)){event.preventDefault();event.stopImmediatePropagation();if(!lock.current)onClose()}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[onClose])
 const refresh=async()=>{const [nextSources,nextChannels]=await Promise.all([api.call<ChannelSource[]>('channel.sources',{includeDisabled:true}),api.call<ChannelView[]>('channel.list')]);if(alive.current){setSources(nextSources);setChannels(nextChannels)}}
 useEffect(()=>{alive.current=true;void refresh().catch(cause=>{if(alive.current)setError(cause.message)}).finally(()=>{if(alive.current)setLoading(false)});return()=>{alive.current=false}},[])
 useEffect(()=>{positioned.current=undefined;setSelected(sourceId);setQuery('');if(sourceId)setAdding(false)},[sourceId])
 useLayoutEffect(()=>{if(!selected){positioned.current=undefined;return}if(loading||positioned.current===selected)return;const row=list.current?.querySelector<HTMLElement>(`[data-source-id="${CSS.escape(selected)}"]`);if(row){row.scrollIntoView({block:'nearest',inline:'nearest'});row.querySelector<HTMLButtonElement>(':scope > button')?.focus({preventScroll:true});positioned.current=selected}},[loading,selected,sources])
 const run=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();await refresh()}catch(cause){if(alive.current)setError((cause as Error).message)}finally{lock.current=false;if(alive.current)setBusy(false)}}
 const close=()=>{if(!lock.current)onClose()},source=sources.find(value=>value.id===selected),choices=channels,needle=query.trim().toLocaleLowerCase()
 const shown=sources.filter(value=>[value.name,value.locator,value.plugin,channelPlatform(value.plugin),channels.find(channel=>channel.id===value.channelId)?.name].join(' ').toLocaleLowerCase().includes(needle))
 const clearSearch=()=>{setQuery('');body.current?.scrollTo({top:0});search.current?.focus()}
 const add=()=>run(async()=>{const next=await api.call<ChannelSource>('channel.source-add',{plugin,locator:locator.trim(),...(choices.some(value=>value.id===target)?{channelId:target}:{})});if(alive.current){setSelected(next.id);setQuery('');setAdding(false);setLocator('')}})
 const create=()=>run(async()=>{const next=await api.call<ChannelView>('channel.create',{name:name.trim()});if(alive.current){setTarget(next.id);setNewChannel(false);setName('')}})
 return createPortal(<div ref={surface} className="group-editor-overlay"><div className="group-editor-backdrop" onClick={close}/><section className="group-editor channel-sources-dialog" role="dialog" aria-modal="true" aria-label={uiText('Manage channels and authors')} aria-busy={busy||loading} onKeyDown={event=>{if(event.key==='Escape'&&!event.defaultPrevented&&!event.nativeEvent.isComposing){event.preventDefault();event.stopPropagation();close()}}}>
  <header><div><span>{uiText('YOUR READING DESK')}</span><h2>{uiText('Channels & authors')}</h2></div><button disabled={busy} aria-label={uiText('Close channel management')} onClick={close}><Icon name="close"/></button></header>
  <div className="channel-source-controls">
   <label className="channel-source-search"><Icon name="search"/><input ref={search} type="search" aria-label={uiText('Search authors')} placeholder={uiText('Search authors, handles or channels')} value={query} onChange={event=>{setQuery(event.target.value);body.current?.scrollTo({top:0})}} onKeyDown={event=>{if(event.key==='Escape'&&query&&!event.nativeEvent.isComposing){event.preventDefault();event.stopPropagation();clearSearch()}}}/>{query&&<button aria-label={uiText('Clear author search')} onClick={clearSearch}><Icon name="close"/></button>}</label>
   <div className="channel-source-tools"><button disabled={busy} aria-pressed={adding} onClick={()=>{setAdding(!adding);setSelected(undefined);body.current?.scrollTo({top:0})}}><Icon name="add"/>{uiText('Follow an author')}</button><button disabled={busy} aria-pressed={newChannel} onClick={()=>{setNewChannel(!newChannel);body.current?.scrollTo({top:0})}}><Icon name="radio-tower"/>{uiText('New channel')}</button><span role="status">{loading?uiText('Loading authors…'):uiText('{0} of {1} authors',[shown.length,sources.length])}</span></div>
  </div>
  <div ref={body} className="channel-sources-body">
  <p className="group-editor-note">{uiText('Follow authors into channels. Saved articles stay with you when an author moves.')}</p>
  {newChannel&&<form className="channel-create-form" onSubmit={event=>{event.preventDefault();void create()}}><label>{uiText('Channel name')}<input value={name} maxLength={80} disabled={busy} onChange={event=>setName(event.target.value)} placeholder={uiText('e.g. Design journal')}/></label><button className="primary" disabled={busy||!name.trim()}>{uiText('Create channel')}</button></form>}
  {adding&&<form className="channel-add-form" onSubmit={event=>{event.preventDefault();void add()}}><label>{uiText('Platform')}<AppSelect aria-label={uiText('Platform')} value={plugin} disabled={busy} menuClassName="channel-source-select-menu" renderChoice={(value,label)=>channelChoice(label,undefined,value as ChannelPlugin)} onChange={event=>setPlugin(event.target.value as ChannelPlugin)}><option value="x">X</option><option value="youtube">YouTube</option></AppSelect></label><label>{uiText('Author URL or handle')}<input value={locator} disabled={busy} onChange={event=>setLocator(event.target.value)} placeholder={plugin==='x'?'@author':'https://www.youtube.com/@author'}/></label><label>{uiText('Channel')}<AppSelect aria-label={uiText('Channel')} value={choices.some(value=>value.id===target)?target:''} disabled={busy} menuClassName="channel-source-select-menu" renderChoice={(value,label)=>channelChoice(label,choices.find(channel=>channel.id===value),plugin)} onChange={event=>setTarget(event.target.value)}><option value="">{uiText('Default {0} channel',[channelPlatform(plugin)])}</option>{choices.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</AppSelect></label><button className="primary" disabled={busy||!locator.trim()}>{uiText('Follow author')}</button><p>{uiText('Telegram channels are paired with their connected Telegram source.')}</p></form>}
  {!loading&&<div ref={list} className="channel-source-list" role="list">{shown.map(value=><div className="channel-source-row" role="listitem" key={value.id} data-source-id={value.id} data-selected={selected===value.id?'true':undefined}><button className={selected===value.id?'selected':''} aria-expanded={selected===value.id} aria-label={uiText('Manage author {0}',[value.name])} onClick={()=>{setSelected(selected===value.id?undefined:value.id);setAdding(false)}}>{value.avatar?<span className="channel-author-avatar"><ChannelImage channelId={value.channelId} postId={value.avatar.postId} mediaId={value.avatar.mediaId} alt=""/></span>:<ChannelAvatar kind={value.plugin} avatar={value.plugin==='telegram'?channels.find(channel=>channel.id===value.channelId)?.avatar:undefined} name={value.name}/>}<span><strong>{value.name}</strong><small>{channelPlatform(value.plugin)}<b>·</b>{channels.find(channel=>channel.id===value.channelId)?.name}</small></span><span className={'channel-follow-state '+(value.enabled?'following':'')}>{uiText(value.enabled?'Following':'Not following')}</span><Icon name={selected===value.id?'chevron-up':'chevron-down'}/></button>{selected===value.id&&source&&<ChannelSourceEditor key={source.id} source={source} channels={choices} busy={busy} run={run}/>}</div>)}{!shown.length&&<div className="channel-source-empty"><Icon name={sources.length?'search':'radio-tower'}/><strong>{uiText(sources.length?'No authors match your search.':'Build your reading desk')}</strong><p>{uiText(sources.length?'Try a name, handle, platform or channel.':'Follow an X or YouTube author to collect their latest posts here.')}</p>{sources.length>0&&<button onClick={clearSearch}>{uiText('Clear search')}</button>}</div>}</div>}
  {error&&<p className="channel-inline-error" role="alert">{uiText(error)}</p>}
  </div>
  <footer><small>{uiText('Unsaved articles are removed after 48 hours. Save an article to keep it.')}</small><button disabled={busy} onClick={close}>{uiText('Done')}</button></footer>
 </section></div>,document.body)
}
function ChannelSourceEditor({source,channels,busy,run}:{source:ChannelSource;channels:ChannelView[];busy:boolean;run:(work:()=>Promise<void>)=>Promise<void>}){
 const [route,setRoute]=useState(source.channelId)
 useEffect(()=>setRoute(source.channelId),[source.channelId])
 return <div className="channel-source-editor"><p>{source.locator}</p><div>{source.plugin!=='telegram'&&<button disabled={busy} aria-label={uiText(source.enabled?'Unfollow {0}':'Follow {0}',[source.name])} onClick={()=>void run(async()=>{await api.call('channel.source-update',{id:source.id,patch:{enabled:!source.enabled}})})}><Icon name={source.enabled?'check':'add'}/>{uiText(source.enabled?'Unfollow':'Follow')}</button>}{source.authorUrl&&<button disabled={busy} onClick={()=>void run(()=>api.call('external.open',{url:source.authorUrl}))}><Icon name="arrow-up-right"/>{uiText('Author profile')}</button>}</div>{source.plugin!=='telegram'?<form onSubmit={event=>{event.preventDefault();void run(async()=>{await api.call('channel.source-update',{id:source.id,patch:{channelId:route}})})}}><label>{uiText('Move author to channel')}<AppSelect aria-label={uiText('Move author to channel')} disabled={busy} value={route} menuClassName="channel-source-select-menu" renderChoice={(value,label)=>channelChoice(label,channels.find(channel=>channel.id===value))} onChange={event=>setRoute(event.target.value)}>{channels.map(channel=><option key={channel.id} value={channel.id}>{channel.name}</option>)}</AppSelect></label><button disabled={busy||route===source.channelId} type="submit">{uiText('Move author')}</button></form>:<small>{uiText('This Telegram source has its own channel.')}</small>}</div>
}
