import {useSurfaceMotion} from '../chat/surfaceMotion'
import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react'
import {createPortal} from 'react-dom'

/** Shared pointer/keyboard menu for conversation and message actions. */
export function MessageMenu({anchor,onClose,label,children,className='',motion='menu',nativeKeys=false,role='menu'}:{anchor:{x:number;y:number;originX?:number;originY?:number};onClose:()=>void;label:string;children:ReactNode;className?:string;motion?:'menu'|'file-menu';nativeKeys?:boolean;role?:'menu'|'dialog'}){
 const previous=useRef(document.activeElement as HTMLElement),root=useSurfaceMotion<HTMLDivElement>(motion),[point,setPoint]=useState(anchor),close=useRef(onClose);close.current=onClose
 useLayoutEffect(()=>{const el=root.current;if(!el)return;const place=()=>setPoint({x:Math.max(8,Math.min(anchor.x,innerWidth-el.offsetWidth-8)),y:Math.max(8,Math.min(anchor.y,innerHeight-el.offsetHeight-8))});place();const resize=new ResizeObserver(place);resize.observe(el);window.addEventListener('resize',place);el.querySelector<HTMLElement>('input:not(:disabled),button:not(:disabled)')?.focus();return()=>{resize.disconnect();window.removeEventListener('resize',place)}},[anchor])
 useEffect(()=>{const outside=(event:Event)=>{if(!root.current?.contains(event.target as Node))close.current()};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();close.current();previous.current?.focus()}else if(event.key==='Tab'&&!nativeKeys){close.current()}else if(!nativeKeys&&!(event.target instanceof HTMLInputElement)&&['ArrowUp','ArrowDown','Home','End'].includes(event.key)){event.preventDefault();const options=[...root.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')??[]],index=options.indexOf(document.activeElement as HTMLButtonElement);options[event.key==='Home'?0:event.key==='End'?options.length-1:(index+(event.key==='ArrowDown'?1:-1)+options.length)%options.length]?.focus()}};document.addEventListener('pointerdown',outside,true);document.addEventListener('focusin',outside);window.addEventListener('keydown',key,true);return()=>{document.removeEventListener('pointerdown',outside,true);document.removeEventListener('focusin',outside);window.removeEventListener('keydown',key,true)}},[])
 return createPortal(<div ref={root} className={`messenger-menu ${className}`} role={role} aria-label={label} style={{left:point.x,top:point.y,transformOrigin:`${Math.max(0,(anchor.originX??anchor.x)-point.x)}px ${Math.max(0,(anchor.originY??anchor.y)-point.y)}px`}} onContextMenu={event=>event.preventDefault()}>{children}</div>,document.body)
}
