import {translate as uiText,useI18n,interfaceLocale} from '../i18n'
import {useEffect,useLayoutEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {Temporal} from '@js-temporal/polyfill'
import type {Store} from '../../../shared/types'
import type {ScheduledJob,ScheduleRun} from '../../../shared/scheduler'
import {PLAN_PRIORITIES} from '../../../shared/plan'
import {api} from '../api'
import {useDialogFocus} from '../office/useDialogFocus'
import {Icon} from './Icon'
import {EmployeePortrait} from './EmployeePortrait'
const localTime=(at:string,zone:string)=>Temporal.Instant.from(at).toZonedDateTimeISO(zone).toPlainDateTime().toString({smallestUnit:'millisecond'})
const instant=(value:string,zone:string)=>Temporal.PlainDateTime.from(value).toZonedDateTime(zone).toInstant().toString()
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
export function PlanEditor({job,store,timezone,onClose,onSaved,onReload,onConversation,inline=false}:{job?:ScheduledJob;store:Store;timezone:string;onClose:()=>void;onSaved:(job?:ScheduledJob)=>void;onReload?:(job:ScheduledJob)=>void;onConversation:(id:string)=>void;inline?:boolean}){
  useI18n()

 useDialogFocus('.plan-editor-overlay > .plan-editor',!inline)
 const [targetView,setTargetView]=useState(job?.action.viewId??store.activeTeamViewId??'all')
 const [name,setName]=useState(job?.name??''),[employee,setEmployee]=useState(job?.action.employeeId??''),[prompt,setPrompt]=useState(job?.action.prompt??'')
 const [duration,setDuration]=useState(job?.plan?.durationMinutes===undefined?'':String(job.plan.durationMinutes))
 const rule=job?.rule,initialZone=rule&&(rule.kind==='weekly'||rule.kind==='monthly')?rule.timezone:timezone
 const originalAt=rule?.kind==='once'?localTime(rule.at,initialZone):undefined,originalUntil=job?.until?localTime(job.until,initialZone):undefined
 const interval=rule?.kind==='interval'?rule.everySeconds:1800,initialUnit=interval%86400===0?86400:interval%3600===0?3600:interval%60===0?60:1
 const [mode,setMode]=useState<string>(rule?.kind==='weekly'&&rule.days.length===7?'daily':rule?.kind??'after'),[zone,setZone]=useState(initialZone)
 const [at,setAt]=useState(originalAt??localTime(new Date(Date.now()+3600000).toISOString(),timezone)),[amount,setAmount]=useState(rule?.kind==='interval'?String(rule.everySeconds/initialUnit):'30'),[unit,setUnit]=useState(String(rule?.kind==='interval'?initialUnit:60))
 const [time,setTime]=useState(rule?.kind==='weekly'||rule?.kind==='monthly'?rule.time:'17:00'),[weekdays,setWeekdays]=useState(rule?.kind==='weekly'?rule.days:[7]),[monthDay,setMonthDay]=useState(rule?.kind==='monthly'?String(rule.day):'last')
 const [enabled,setEnabled]=useState(job?.enabled??true),[priority,setPriority]=useState(job?.plan?.priority??'normal'),[tags,setTags]=useState(job?.plan?.tags.join(', ')??''),[notes,setNotes]=useState(job?.plan?.notes??'')
 const [limit,setLimit]=useState(job?.maxOccurrences?String(job.maxOccurrences):''),[until,setUntil]=useState(originalUntil??''),[timeout,setTimeoutValue]=useState(String(job?.timeoutSeconds??1800)),[grace,setGrace]=useState(String(job?.graceSeconds??60))
 const [windowStart,setWindowStart]=useState(job?.window?.start??''),[windowEnd,setWindowEnd]=useState(job?.window?.end??''),[windowDays,setWindowDays]=useState(job?.window?.days??[1,2,3,4,5,6,7]),[windowZone,setWindowZone]=useState(job?.window?.timezone??timezone)
 const [model,setModel]=useState(job?.action.model??''),[effort,setEffort]=useState(job?.action.effort??''),[thinking,setThinking]=useState(job?.action.thinking===undefined?'inherit':job.action.thinking?'on':'off')
 const previewSequence=useRef(0)
 const [previewed,setPreviewed]=useState(false),[preview,setPreview]=useState<string[]>([]),[history,setHistory]=useState<ScheduleRun[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState<'run'|'delete'|null>(null)
 const key=useRef(crypto.randomUUID()),lastPayload=useRef(''),guard=useRef(false),target=store.sessions.find(card=>card.id===employee),working=history.some(run=>run.status==='running')
 useEffect(()=>{if(!job)return;let alive=true;const load=()=>void api.call<ScheduleRun[]>('schedule.history',{id:job.id,limit:30}).then(rows=>{if(alive)setHistory(rows)}).catch(cause=>{if(alive)setError(cause.message)});load();const off=api.onEvent(event=>{if(event.channel==='schedule:run')load()});return()=>{alive=false;off()}},[job?.id])
 useEffect(()=>{setPreview([]);setPreviewed(false);previewSequence.current++},[name,employee,prompt,mode,zone,at,amount,unit,time,weekdays,monthDay,limit,until,windowStart,windowEnd,windowZone,windowDays,targetView])
 function spec(){
  const seconds=Number(amount)*Number(unit)
  const recurrence=mode==='after'?{afterSeconds:seconds}:mode==='once'?{rule:{kind:'once',at:rule?.kind==='once'&&zone===initialZone&&at===originalAt?rule.at:instant(at,zone)}}:mode==='interval'?{rule:{kind:'interval',everySeconds:seconds,...(rule?.kind==='interval'?{anchor:rule.anchor}:{})}}:mode==='monthly'?{rule:{kind:'monthly',day:monthDay==='last'?'last':Number(monthDay),time,timezone:zone}}:{rule:{kind:'weekly',time,days:mode==='daily'?[1,2,3,4,5,6,7]:weekdays,timezone:zone}}
  return {name:name.trim(),action:{type:'agent',employeeId:employee,prompt:prompt.trim(),...(job?.action.engine?{engine:target?.engine}:{}),...(target?.managementRole==='governor'?{viewId:targetView}:{}),...(model?{model}:{}),...(effort?{effort}:{}),...(thinking!=='inherit'?{thinking:thinking==='on'}:{})},...recurrence,enabled,plan:{priority,tags:tags.split(',').map(tag=>tag.trim()).filter(Boolean),notes,...(duration?{durationMinutes:Number(duration)}:{})},timeoutSeconds:Number(timeout),graceSeconds:Number(grace),maxOccurrences:limit?Number(limit):null,until:until?(zone===initialZone&&until===originalUntil?job!.until:instant(until,zone)):null,window:windowStart||windowEnd?{start:windowStart,end:windowEnd,timezone:windowZone,days:windowDays}:null,...(job?.source?{source:job.source}:{})}
 }
 const act=async(work:()=>Promise<unknown>,close=false)=>{if(guard.current)return;guard.current=true;setBusy(true);setError('');try{const result=await work();if(close)onSaved(result&&typeof result==='object'&&'rule' in result?result as ScheduledJob:undefined)}catch(cause){setError((cause as Error).message)}finally{guard.current=false;setBusy(false)}}
 const save=()=>act(()=>{const payload=spec(),signature=JSON.stringify(payload);if(signature!==lastPayload.current){key.current=crypto.randomUUID();lastPayload.current=signature}return api.call(job?'schedule.update':'schedule.create',job?{id:job.id,patch:payload,expectedRevision:job.revision??0}:{spec:payload,clientRequestId:key.current})},true)
 const chooseEmployee=(id:string)=>{setEmployee(id);setModel('');setEffort('');setThinking('inherit')}
 useLayoutEffect(()=>{if(inline)return;const key=(event:KeyboardEvent)=>{if(event.defaultPrevented||event.isComposing)return;if(event.key==='Escape'){event.preventDefault();if(confirm)setConfirm(null);else if(!busy)onClose()}else if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)&&!busy&&!working&&name.trim()&&employee&&prompt.trim()){event.preventDefault();void save()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[inline,confirm,busy,working,name,employee,prompt,save,onClose])
 const content=<div className={inline?'plan-inline-form':'plan-editor-overlay'} onKeyDown={event=>{if(inline&&event.key==='Enter'&&(event.metaKey||event.ctrlKey)&&!event.nativeEvent.isComposing&&!busy&&name.trim()&&employee&&prompt.trim()){event.preventDefault();void save()}}}>
  {/* A task double-click must not dismiss its new editor with the second click. */}
  {!inline&&<div className="plan-editor-backdrop" onClick={event=>{if(!busy&&event.detail<2)onClose()}}/>}
  <section className="plan-editor" role={inline?'region':'dialog'} aria-modal={inline?undefined:true} aria-label={inline?uiText("Schedule submission form"):job?uiText("Edit schedule"):uiText("New schedule")}>
   <header><div><span>{uiText("PLAN / AUTOMATION")}</span><h2>{job?job.name:uiText("New schedule")}</h2></div>{!inline&&<button aria-label={uiText("Close schedule editor")} disabled={busy} onClick={onClose}><Icon name="close"/></button>}</header>
   <div className="plan-editor-scroll">
    <h3 className="plan-editor-section-heading"><span>01</span>{uiText("Task details")}</h3>
    <label>{uiText("Task name")}<input name="plan-name" autoFocus={inline} value={name} maxLength={160} onChange={e=>setName(e.target.value)} placeholder={uiText("e.g. Weekly project review")}/></label>
    <label>{uiText("Assigned employee")}<div className="plan-assignee">{target&&<EmployeePortrait avatar={target.avatar??(target.engine==='codex'?'robot':'cat')} color={target.color}/>}<select name="plan-employee" value={employee} onChange={e=>chooseEmployee(e.target.value)}><option value="">{uiText("Choose an employee")}</option>{employee&&!target&&<option value={employee}>{uiText("Removed employee")}</option>}{store.sessions.filter(card=>!card.deleting).map(card=><option key={card.id} value={card.id}>{card.title} · {card.group}</option>)}</select></div></label>
    {employee&&!target&&<p className="plan-assignee-warning" role="status"><Icon name="info"/>{uiText("This employee was removed. Choose another employee to schedule future work.")}</p>}
    {target?.managementRole==='governor'&&<label>{uiText("Governor's target Company view")}<select name="plan-target-view" value={targetView} onChange={e=>setTargetView(e.target.value)}><option value="all">{uiText("All Team")}</option>{store.teamViews?.map(view=><option key={view.id} value={view.id}>{view.name}</option>)}</select><small>{uiText("This exact view is pinned to the scheduled task, independent of future tab changes.")}</small></label>}
    <label>{uiText("Prompt")}<textarea name="plan-prompt" rows={5} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={uiText("What should this employee do? Full work stays in their existing conversation.")}/></label>
    <h3 className="plan-editor-section-heading"><span>02</span>{uiText("Schedule timing")}</h3>
    <div className="plan-field-row"><label>{uiText("When")}<select name="plan-mode" value={mode} onChange={e=>{setMode(e.target.value);setPreview([])}}>{[['after','After a delay'],['once','Once at a date & time'],['daily','Every day'],['weekly','Every week'],['monthly','Every month'],['interval','At a fixed interval']].map(([value,label])=><option key={value} value={value}>{uiText(label)}</option>)}</select></label><label>{uiText("Time zone")}<input name="plan-timezone" list="plan-timezones" value={zone} onChange={e=>{setZone(e.target.value);setPreview([]);setPreviewed(false);previewSequence.current++}}/><datalist id="plan-timezones">{[timezone,'UTC','Asia/Shanghai','America/New_York','Europe/London','Asia/Tokyo'].map((zone,i)=><option key={i}>{zone}</option>)}</datalist></label></div>
    {(mode==='after'||mode==='interval')&&<div className="plan-field-row"><label>{mode==='after'?uiText("Start after"):uiText("Repeat every")}<input name="plan-amount" type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{uiText("Unit")}<select name="plan-unit" value={unit} onChange={e=>setUnit(e.target.value)}>{[['1','Seconds'],['60','Minutes'],['3600','Hours'],['86400','Days']].map(([v,l])=><option key={v} value={v}>{uiText(l)}</option>)}</select></label></div>}
    {mode==='once'&&<label>{uiText("Date and time")}<input name="plan-at" type="datetime-local" step="0.001" value={at} onChange={e=>setAt(e.target.value)}/></label>}
    {['weekly','daily','monthly'].includes(mode)&&<label>{uiText("Time")}<input name="plan-time" type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>}
    {mode==='weekly'&&<div className="plan-weekdays" role="group" aria-label={uiText("Repeat on weekdays")}>{days.map((day,i)=><button key={day} aria-pressed={weekdays.includes(i+1)} onClick={()=>setWeekdays(prev=>prev.includes(i+1)?prev.filter(d=>d!==i+1):[...prev,i+1])}>{uiText(day)}</button>)}</div>}
    {mode==='monthly'&&<label>{uiText("Day of month")}<select name="plan-month-day" value={monthDay} onChange={e=>setMonthDay(e.target.value)}><option value="last">{uiText("Last day of the month")}</option>{Array.from({length:31},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select><small>{uiText("Months without the chosen date are skipped.")}</small></label>}
    <div className="plan-preview"><button disabled={busy||!name.trim()||!employee||!prompt.trim()} onClick={()=>void act(async()=>{const sequence=previewSequence.current,result=await api.call<{times:string[]}>('schedule.preview',{...(job?{id:job.id,patch:spec()}:{spec:spec()}),count:5});if(sequence===previewSequence.current){setPreview(result.times);setPreviewed(true)}})}><Icon name="calendar"/>  {uiText("Preview next runs")}</button>{preview.length>0&&<ol>{preview.map(at=><li key={at}>{new Date(at).toLocaleString(interfaceLocale(),{timeZone:zone,dateStyle:'medium',timeStyle:'short'})}<small>{zone}</small></li>)}</ol>}{previewed&&!preview.length&&<p className="plan-preview-empty" role="status">{uiText("No future runs match these settings or the remaining occurrence limit.")}</p>}</div>
    <h3 className="plan-editor-section-heading"><span>03</span>{uiText("Planning details")}</h3>
    <div className="plan-field-row"><label>{uiText("Priority")}<select name="plan-priority" value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}>{PLAN_PRIORITIES.map(v=><option key={v} value={v}>{uiText(v[0].toUpperCase()+v.slice(1))}</option>)}</select></label><label>{uiText("Tags")}<input name="plan-tags" value={tags} onChange={e=>setTags(e.target.value)} placeholder={uiText("review, product")}/></label></div>
    <label>{uiText("Notes")}<textarea name="plan-notes" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder={uiText("Context for this plan. Notes do not replace the prompt.")}/></label>
    <label>{uiText("Estimated duration (minutes)")}<input name="plan-duration" type="number" min="1" max="43200" value={duration} onChange={e=>setDuration(e.target.value)} placeholder={uiText("No estimate · show an instant on Timeline")}/><small>{uiText("Planning estimate only. This does not reserve time, change the timeout, or stop the employee.")}</small></label>
    <details className="plan-advanced"><summary>{uiText("Limits, work windows & model overrides")}</summary>
     <div className="plan-field-row"><label>{uiText("End after occurrences")}<input name="plan-limit" type="number" min="1" value={limit} onChange={e=>setLimit(e.target.value)} placeholder={uiText("No limit")}/></label><label>{uiText("End before")}<input name="plan-until" type="datetime-local" step="0.001" value={until} onChange={e=>setUntil(e.target.value)}/></label></div>
     <div className="plan-field-row"><label>{uiText("Run timeout (seconds)")}<input name="plan-timeout" type="number" min="1" max="86400" value={timeout} onChange={e=>setTimeoutValue(e.target.value)}/></label><label>{uiText("Late-start grace (seconds)")}<input name="plan-grace" type="number" min="1" max="86400" value={grace} onChange={e=>setGrace(e.target.value)}/></label></div>
     <div className="plan-field-row"><label>{uiText("Allowed window starts")}<input name="plan-window-start" type="time" value={windowStart} onChange={e=>setWindowStart(e.target.value)}/></label><label>{uiText("Allowed window ends")}<input name="plan-window-end" type="time" value={windowEnd} onChange={e=>setWindowEnd(e.target.value)}/></label></div>
     {(windowStart||windowEnd)&&<><label>{uiText("Window time zone")}<input value={windowZone} onChange={e=>setWindowZone(e.target.value)}/></label><div className="plan-weekdays" aria-label={uiText("Allowed window days")}>{days.map((day,i)=><button key={day} aria-pressed={windowDays.includes(i+1)} onClick={()=>setWindowDays(prev=>prev.includes(i+1)?prev.filter(d=>d!==i+1):[...prev,i+1])}>{uiText(day)}</button>)}</div><small>{uiText("Overnight windows belong to their starting day. Leave both times empty for no restriction.")}</small></>}
     <label>{uiText("Model override")}<input name="plan-model" value={model} onChange={e=>setModel(e.target.value)} placeholder={uiText("Inherit the employee’s model")}/></label>
     <div className="plan-field-row"><label>{uiText("Reasoning effort")}<select name="plan-effort" disabled={target?.engine==='cline'||target?.engine==='pi'} value={effort} onChange={e=>setEffort(e.target.value as typeof effort)}><option value="">{uiText("Inherit")}</option>{['low','medium','high','xhigh','max'].map(value=><option key={value} value={value}>{uiText(value)}</option>)}</select></label><label>{uiText("Thinking")}<select name="plan-thinking" disabled={target?.engine==='codex'} value={thinking} onChange={e=>setThinking(e.target.value)}><option value="inherit">{uiText("Inherit")}</option><option value="off">{uiText("Off")}</option><option value="on" disabled={target?.engine==='pi'||target?.engine==='cline'}>{uiText("On")}</option></select></label></div>
     <p>{uiText("Overrides must be supported by the selected engine and model. They apply to this run only; employee settings and permissions stay unchanged.")}</p>
    </details>
    <label className="plan-enabled"><input name="plan-enabled" type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span>{uiText("Enable automatic scheduling")}</span></label>
    <p className="plan-safety-note"><Icon name="info"/>  {uiText("Core must stay running and the host awake. Busy employees are skipped, never interrupted. Missed runs are not replayed in a burst.")}</p>
    {job&&<section className="plan-run-history"><header><h3>{uiText("Run history")}</h3><button onClick={()=>onConversation(job.action.employeeId)}>{uiText("Open conversation ↗")}</button></header>{!history.length?<p>{uiText("No runs yet.")}</p>:history.map(run=><article key={run.id}><i data-state={run.status}/><div><strong>{uiText(run.status.replaceAll('_',' '))}</strong><time>{new Date(run.startedAt).toLocaleString(interfaceLocale())}</time>{run.message&&<p>{run.message}</p>}</div>{run.status==='running'&&<button disabled={busy} onClick={()=>void act(()=>api.call('schedule.cancel',{id:run.id}))}>{uiText("Cancel run")}</button>}</article>)}</section>}
   </div>
   {working&&<p className="plan-safety-note plan-running-note" role="status">{uiText("Cancel the active run before updating its schedule")}</p>}{error&&<div className="plan-error" role="alert">{uiText(error)}{job&&onReload&&error.includes("Schedule changed")&&<button disabled={busy} onClick={()=>void act(async()=>onReload(await api.call<ScheduledJob>("schedule.get",{id:job.id})))}>{uiText("Load latest")}</button>}</div>}
   {confirm&&<div className="plan-confirm" role="alert"><p>{confirm==='run'?uiText("Run the saved schedule now? Unsaved changes are not included. This starts the employee’s engine and may incur model usage. The recurring schedule is unchanged."):uiText("Delete this schedule? Any active run will be cancelled. Employee history and files will be kept.")}</p><button disabled={busy} onClick={()=>void act(async()=>{await api.call(confirm==='run'?'schedule.run':'schedule.delete',{id:job!.id});setConfirm(null)},true)}>{confirm==='run'?uiText("Confirm run"):uiText("Delete schedule")}</button><button disabled={busy} onClick={()=>setConfirm(null)}>{uiText("Cancel")}</button></div>}
   <footer>{job&&<><button className="plan-delete" aria-label={uiText("Remove schedule")} title={uiText("Remove schedule")} disabled={busy} onClick={()=>setConfirm('delete')}><Icon name="trash"/></button><button disabled={busy||working||!target} onClick={()=>setConfirm('run')}>{uiText("Run now")}</button><button disabled={busy} onClick={()=>void act(()=>api.call(job.enabled?'schedule.pause':'schedule.resume',{id:job.id}),true)}>{job.enabled?uiText("Pause"):uiText("Resume")}</button></>}<span/><button disabled={busy} onClick={onClose}>{inline?uiText("Reset form"):uiText("Cancel")}</button><button className="primary" disabled={busy||working||!name.trim()||!employee||!prompt.trim()} onClick={()=>void save()}>{busy?uiText("Saving…"):job?uiText("Save changes"):uiText("Create schedule")}</button></footer>
  </section>
 </div>
 return inline?content:createPortal(content,document.body)
}
