import {translate as uiText,useI18n,interfaceLocale} from '../i18n'
import {Fragment,useEffect,useState} from 'react'
import type {PlanAnalytics,PlanFeed,PlanFeedEntry,PlanFilter,PlanRow,PlanViewOptions} from '../../../shared/plan'
import {PLAN_RUN_STATES} from '../../../shared/plan'
import {api} from '../api'
import {Icon} from './Icon'
import {EmployeePortrait} from './EmployeePortrait'
import '../styles/plan-insights.css'

type ChartProps={filter:PlanFilter;options:PlanViewOptions;generation:number;onOptions:(value:Partial<PlanViewOptions>)=>void}
const colors=['var(--accent)','#4d9586','#bb8a46','#8e79b6','#bc7384','#678faf','#82965e','#907b69']
const stateColors:Record<string,string>={scheduled:'var(--accent)',running:'#418879',paused:'#8b92a1',completed:'#62915d',succeeded:'#418879',attention:'#b68136',failed:'var(--red)',timed_out:'#b68136',interrupted:'#a57858',cancelled:'#8b92a1',skipped:'#9a8e74',low:'#8794a8',normal:'var(--accent)',high:'#b68136',urgent:'var(--red)'}
const label=(value:string)=>uiText(value.replaceAll('_',' '))
export function PlanChartView({filter,options,generation,onOptions}:ChartProps){
  useI18n()
  const metric=options.chartMetric??'schedules',groupBy=options.chartGroupBy??'status',kind=options.chartType??'bar'
  const [data,setData]=useState<PlanAnalytics|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[days,setDays]=useState('all'),[selected,setSelected]=useState<string|null>(null),[retry,setRetry]=useState(0)
  const key=JSON.stringify([filter,metric,groupBy,generation,days,retry])
  useEffect(()=>{let alive=true;setLoading(true);setSelected(null);const range=metric==='runs'&&days!=='all'?{from:new Date(Date.now()-Number(days)*86400000).toISOString(),to:new Date(Date.now()+1).toISOString()}:{};void api.call<PlanAnalytics>('plan.analytics',{filter,metric,groupBy,...range}).then(result=>{if(alive){setData(result);setError('')}}).catch(cause=>{if(alive){setError(cause.message);setData(null)}}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[key])
  const source=data?.buckets??[],buckets=source.length>20?[...source.slice(0,19),{key:'__other__',label:uiText('Other ({0} categories)',[source.length-19]),value:source.slice(19).reduce((sum,item)=>sum+item.value,0)}]:source
  const bucketLabel=(bucket:typeof buckets[number])=>bucket.key==='__other__'?bucket.label:bucket.key==='missing:team'?uiText('Removed employee'):groupBy==='employee'&&bucket.label==='Removed employee · '+bucket.key?uiText('Removed employee')+' · '+bucket.key:groupBy==='status'||groupBy==='priority'?uiText(bucket.label):bucket.label
  const color=(bucket:typeof buckets[number],index:number)=>(groupBy==='status'||groupBy==='priority')&&stateColors[bucket.key]||colors[index%colors.length]
  const max=Math.max(1,...buckets.map(bucket=>bucket.value)),plotWidth=Math.max(720,100+buckets.length*58),step=(plotWidth-100)/Math.max(1,buckets.length),total=data?.total??0
  const metricLabel=metric==='schedules'?uiText('Schedules'):uiText('Actual runs'),period=metric==='schedules'?uiText('All matching schedules'):days==='all'?uiText('All retained runs'):uiText('Last {0} days',[days])
  let degrees=0;const gradient=buckets.map((bucket,i)=>{const from=degrees;degrees+=total?bucket.value/total*360:0;return `${color(bucket,i)} ${from}deg ${degrees}deg`}).join(',')
  const choose=(key:string)=>setSelected(value=>value===key?null:key),point=(index:number,value:number)=>[50+index*step+step/2,245-value/max*195],chosen=buckets.find(bucket=>bucket.key===selected)
  return <section className="plan-chart-view plan-insights" aria-label={uiText('Plan analytics')} aria-busy={loading}>
    <div className="plan-insight-controls"><label>{uiText('Count')}<select aria-label={uiText('Chart metric')} value={metric} onChange={event=>onOptions({chartMetric:event.target.value as typeof metric})}><option value="schedules">{uiText('Schedules')}</option><option value="runs">{uiText('Actual runs')}</option></select></label><label>{uiText('Group by')}<select aria-label={uiText('Chart grouping')} value={groupBy} onChange={event=>onOptions({chartGroupBy:event.target.value as typeof groupBy})}><option value="status">{uiText('State / outcome')}</option><option value="employee">{uiText('Employee')}</option><option value="team">{uiText('Current Team')}</option><option value="priority">{uiText('Current priority')}</option></select></label><label>{uiText('Chart')}<select aria-label={uiText('Chart style')} value={kind} onChange={event=>onOptions({chartType:event.target.value as typeof kind})}><option value="bar">{uiText('Columns')}</option><option value="horizontal">{uiText('Horizontal bars')}</option><option value="line">{uiText('Line')}</option><option value="donut">{uiText('Donut')}</option></select></label>{metric==='runs'&&<label>{uiText('Period')}<select aria-label={uiText('Chart period')} value={days} onChange={event=>setDays(event.target.value)}><option value="all">{uiText('All retained runs')}</option><option value="7">{uiText('Last 7 days')}</option><option value="30">{uiText('Last 30 days')}</option><option value="90">{uiText('Last 90 days')}</option></select></label>}</div>
    {error&&<div className="plan-error plan-insight-error" role="alert"><span>{uiText(error)}</span><button onClick={()=>setRetry(value=>value+1)} disabled={loading}><Icon name="refresh"/>{uiText('Retry')}</button></div>}
    <header className="plan-chart-summary"><strong data-analytics-total>{loading||error?'—':total.toLocaleString(interfaceLocale())}</strong><div><h2>{metric==='schedules'?uiText('Matching schedules'):uiText('Recorded runs')}</h2><p>{loading?uiText('Loading authorized totals…'):data?uiText(data.scope):uiText('No data available')}</p></div><span className="plan-insight-range"><Icon name="calendar"/>{period}</span></header>
    {!loading&&!error&&!total&&<div className="plan-empty"><Icon name="graph"/><h2>{uiText('No matching data')}</h2><p>{metric==='runs'?uiText('Future schedules are not actual runs. Change the period or filters.'):uiText('Clear filters or create a schedule.')}</p>{metric==='runs'&&<button className="plan-insight-secondary" onClick={()=>onOptions({chartMetric:'schedules'})}>{uiText('View matching schedules')}<Icon name="arrow-right"/></button>}</div>}
    {!loading&&!error&&total>0&&<div className="plan-chart-figure" data-chart-style={kind}>
      {kind==='donut'?<div className="plan-donut-wrap"><div className="plan-donut" role="img" aria-label={uiText('{0} {1} across {2} categories',[total,metricLabel,source.length])} style={{background:`conic-gradient(${gradient})`}}><span><strong>{total.toLocaleString(interfaceLocale())}</strong><small>{metricLabel}</small></span></div></div>:kind==='horizontal'?<div className="plan-horizontal-chart">{buckets.map((bucket,i)=><button key={bucket.key} aria-pressed={selected===bucket.key} onClick={()=>choose(bucket.key)} title={bucketLabel(bucket)+': '+bucket.value}><span>{bucketLabel(bucket)}</span><span className="plan-horizontal-track" aria-hidden="true"><i style={{width:`${bucket.value/max*100}%`,background:color(bucket,i)}}/></span><strong>{bucket.value}</strong></button>)}</div>:<div className="plan-chart-plot" tabIndex={0} aria-label={uiText('Chart categories')}><svg className="plan-svg-chart" style={{minWidth:plotWidth}} viewBox={`0 0 ${plotWidth} 300`} role="group" aria-label={uiText('{0} chart of {1} by {2}',[kind==='line'?uiText('Categorical line'):uiText('Column'),metricLabel,uiText(groupBy==='status'?'State / outcome':groupBy==='employee'?'Employee':groupBy==='team'?'Current Team':'Current priority')])}>
        {[0,.25,.5,.75,1].map(value=><g key={value}><line x1="45" x2={plotWidth-45} y1={245-value*195} y2={245-value*195} className="plan-chart-gridline"/><text x="35" y={249-value*195} textAnchor="end">{Number((value*max).toFixed(1))}</text></g>)}
        {kind==='line'&&<polyline points={buckets.map((bucket,i)=>point(i,bucket.value).join(',')).join(' ')} fill="none" stroke="var(--accent)" strokeWidth="2.5"/>}
        {buckets.map((bucket,i)=>{const [x,y]=point(i,bucket.value),name=bucketLabel(bucket);return <g key={bucket.key} tabIndex={0} role="button" aria-pressed={selected===bucket.key} aria-label={name+': '+bucket.value} onClick={()=>choose(bucket.key)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose(bucket.key)}}}><title>{name}: {bucket.value}</title>{kind==='line'?<circle cx={x} cy={y} r={selected===bucket.key?7:5} fill={color(bucket,i)}/>:<rect x={x-Math.min(48,step*.62)/2} y={y} width={Math.min(48,step*.62)} height={245-y} rx="6" fill={color(bucket,i)} opacity={selected&&selected!==bucket.key?0.45:1}/>}<text x={x} y={y-11} textAnchor="middle">{bucket.value}</text><text x={x} y="273" textAnchor="middle">{name.length>14?name.slice(0,12)+'…':name}</text></g>})}
      </svg></div>}
      <div className="plan-chart-breakdown"><header><h3>{uiText('Breakdown')}</h3><small>{uiText('{0} categories',[source.length])}</small></header><div className="plan-chart-legend">{buckets.map((bucket,i)=><button key={bucket.key} aria-pressed={selected===bucket.key} onClick={()=>choose(bucket.key)}><i style={{background:color(bucket,i)}}/><span>{bucketLabel(bucket)}</span><strong>{bucket.value}</strong><small>{Math.round(bucket.value/total*100)}%</small></button>)}</div></div>
      <p className="plan-chart-selection" role="status">{chosen?<><strong>{bucketLabel(chosen)}</strong><span>{uiText('{0} of {1} · {2}%',[chosen.value,total,Math.round(chosen.value/total*100)])}</span></>:uiText('Select a category to see its count and share.')}</p>
    </div>}
    <p className="plan-time-footnote">{metric==='runs'?uiText('Only retained execution records returned by the scheduler are counted (up to 1,000 records). Upcoming dates are excluded.'):uiText('These are schedule counts, not successful task counts or future occurrence counts.')}{kind==='line'?' '+uiText('The line connects categories; it is not a time-series forecast.'):''}{source.length>20?' '+uiText('Remaining categories are grouped as Other.'):''}</p>
  </section>
}

export function PlanGalleryView({rows,zone,onOpen}:{rows:PlanRow[];zone:string;onOpen:(id:string)=>void}){
  useI18n()
  if(!rows.length)return null
  return <div className="plan-gallery plan-insights" aria-label={uiText('Schedule gallery')}>{rows.map(row=><button className="plan-gallery-card" data-plan-id={row.id} key={row.id} onClick={()=>onOpen(row.id)}><div className="plan-gallery-cover">{row.employee?<EmployeePortrait avatar={row.employee.avatar as any} color={row.employee.color} large/>:<span className="plan-gallery-missing"><Icon name="person"/></span>}<span className="plan-gallery-person"><strong>{row.employee?.title??uiText('Removed employee')}</strong><small>{row.employee?.team}</small></span><span className={`plan-status state-${row.status}`}><i/>{uiText(row.status)}</span></div><div className="plan-gallery-body"><h3>{row.name}</h3><p>{row.action.prompt}</p>{row.plan?.notes&&<p className="plan-card-notes">{row.plan.notes}</p>}<div className="plan-tags">{row.plan?.tags.map(tag=><span key={tag}>{tag}</span>)}</div><footer><span className="plan-gallery-next"><small>{uiText('Next run')}</small><time dateTime={row.nextAt??undefined} title={zone}>{row.nextAt?new Date(row.nextAt).toLocaleString(interfaceLocale(),{timeZone:zone,month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):uiText('No future run')}</time></span><span className={'plan-priority priority-'+(row.plan?.priority??'normal')}>{uiText(row.plan?.priority??'normal')}</span></footer><span className="plan-gallery-open">{uiText('Open schedule')}<Icon name="arrow-right"/></span></div></button>)}</div>
}

export function PlanFeedView({filter,zone,onOpen,onConversation}:{filter:PlanFilter;zone:string;onOpen:(id:string)=>void;onConversation:(id:string)=>void}){
  useI18n()
  const [entries,setEntries]=useState<PlanFeedEntry[]>([]),[cursor,setCursor]=useState<string|null>(null),[outcome,setOutcome]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[pages,setPages]=useState(1),[revision,setRevision]=useState(0)
  const filterKey=JSON.stringify([filter,outcome])
  useEffect(()=>{setPages(1);setEntries([])},[filterKey])
  useEffect(()=>{let timer:ReturnType<typeof setTimeout>|undefined;const off=api.onEvent(event=>{if(['schedule:changed','schedule:run','store:changed'].includes(event.channel)&&!timer)timer=setTimeout(()=>{timer=undefined;setRevision(value=>value+1)},120)});return()=>{off();clearTimeout(timer)}},[])
  // Replace the loaded window so changed outcomes and removed schedules remain truthful.
  useEffect(()=>{let alive=true;setLoading(true);void (async()=>{try{let before:string|undefined,next:string|null=null;const all=new Map<string,PlanFeedEntry>();for(let i=0;i<pages;i++){const data=await api.call<PlanFeed>('plan.feed',{filter,outcomes:outcome?[outcome]:undefined,before,limit:30});if(!alive)return;for(const entry of data.entries)all.set(entry.id,entry);next=data.nextCursor;if(!next)break;before=next}if(alive){setEntries([...all.values()].sort((a,b)=>b.startedAt.localeCompare(a.startedAt)||b.id.localeCompare(a.id)));setCursor(next);setError('')}}catch(cause){if(alive)setError((cause as Error).message)}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[filterKey,pages,revision])
  const day=(at:string)=>new Date(at).toLocaleDateString(interfaceLocale(),{timeZone:zone,year:'numeric',month:'long',day:'numeric',weekday:'short'})
  return <section className="plan-feed-view plan-insights" aria-label={uiText('Execution feed')} aria-busy={loading}>
    <div className="plan-insight-controls plan-feed-controls"><label>{uiText('Outcome')}<select aria-label={uiText('Feed outcome')} value={outcome} onChange={event=>setOutcome(event.target.value)}><option value="">{uiText('All actual outcomes')}</option>{PLAN_RUN_STATES.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><span className="plan-feed-count">{loading&&!entries.length?uiText('Loading…'):uiText('Showing {0} runs',[entries.length])}</span><span className="plan-insight-range"><Icon name="clock"/>{zone}</span></div>
    <p className="plan-feed-scope">{uiText('Real runs only · newest first')}</p>
    {error&&<div className="plan-error plan-insight-error" role="alert"><span>{uiText(error)}</span><button disabled={loading} onClick={()=>setRevision(value=>value+1)}><Icon name="refresh"/>{uiText('Retry')}</button></div>}
    {!loading&&!error&&!entries.length&&<div className="plan-empty"><Icon name="history"/><h2>{uiText('No recorded activity')}</h2><p>{uiText('Creating or previewing a schedule does not fabricate an execution record.')}</p>{outcome&&<button className="plan-insight-secondary" onClick={()=>setOutcome('')}>{uiText('All actual outcomes')}</button>}</div>}
    <div className="plan-feed-items">{entries.map((run,index)=><Fragment key={run.id}>{(!index||day(entries[index-1].startedAt)!==day(run.startedAt))&&<h3 className="plan-feed-day">{day(run.startedAt)}</h3>}<article className="plan-feed-item" data-run-id={run.id} data-outcome={run.status} data-editable={run.jobAvailable||undefined} tabIndex={run.jobAvailable?0:undefined} aria-label={run.jobAvailable?uiText('Edit schedule')+': '+run.jobName:run.jobName} onClick={event=>{if(run.jobAvailable&&!(event.target as HTMLElement).closest('button,a,details,input,select')&&!window.getSelection()?.toString())onOpen(run.jobId)}} onKeyDown={event=>{if(run.jobAvailable&&event.target===event.currentTarget&&(event.key==='Enter'||event.key===' ')){event.preventDefault();onOpen(run.jobId)}}}><>{run.employee?<EmployeePortrait avatar={run.employee.avatar as any} color={run.employee.color}/>:<span className="plan-person-missing"><Icon name="person"/></span>}</><div><header><strong>{run.employee?.title??uiText('Removed employee')}</strong><small>{run.employee?.team}</small><time dateTime={run.startedAt} title={new Date(run.startedAt).toLocaleString(interfaceLocale(),{timeZone:zone})}>{new Date(run.startedAt).toLocaleTimeString(interfaceLocale(),{timeZone:zone,hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></header><button className="plan-feed-title" disabled={!run.jobAvailable} onClick={()=>onOpen(run.jobId)}>{run.jobName}</button><div className="plan-feed-meta"><span className={`plan-run-outcome outcome-${run.status}`}><Icon name={run.status==='succeeded'?'check':run.status==='running'?'play':run.status==='failed'||run.status==='timed_out'||run.status==='interrupted'?'warning':run.status==='cancelled'?'close':'clock'}/>{label(run.status)}</span><small>{run.trigger==='manual'?uiText('Explicit manual run'):uiText('Scheduled trigger')}</small>{!run.jobAvailable&&<small>{uiText('Schedule removed · history preserved')}</small>}</div>{run.message&&<p className="plan-feed-message">{run.message}</p>}<details><summary>{uiText('Task prompt & execution details')}</summary><p>{run.action.prompt}</p><dl><dt>{uiText('Scheduled')}</dt><dd>{new Date(run.scheduledAt).toLocaleString(interfaceLocale(),{timeZone:zone})}</dd><dt>{uiText('Finished')}</dt><dd>{run.finishedAt?new Date(run.finishedAt).toLocaleString(interfaceLocale(),{timeZone:zone}):uiText('Still active')}</dd><dt>{uiText('Run ID')}</dt><dd>{run.id}</dd></dl></details>{run.employee&&<button className="plan-feed-conversation" onClick={()=>onConversation(run.action.employeeId)}>{uiText('Open full conversation ↗')}</button>}</div></article></Fragment>)}</div>
    {cursor&&<button className="plan-load-older" disabled={loading} onClick={()=>setPages(value=>value+1)}>{loading?uiText('Loading…'):uiText('Load earlier runs')}<Icon name="chevron-down"/></button>}
    <p className="plan-time-footnote">{uiText('History is bounded. Removed schedules remain visible here when authorized; filters on current schedule tags, priority or state exclude records whose schedule no longer exists. Reading this feed does not mark private replies read.')}</p>
  </section>
}
