import {translate as uiText,useI18n,interfaceLocale} from '../i18n'
import {PlanTimelineView,PlanPlannerView} from './PlanTimeViews'
import {PlanChartView,PlanGalleryView,PlanFeedView} from './PlanInsights'
import {PlanFormView} from './PlanFormView'
import {useEffect,useMemo,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {Temporal} from '@js-temporal/polyfill'
import {useDialogFocus} from '../office/useDialogFocus'
import type {Store} from '../../../shared/types'
import type {ViewState} from '../../../shared/view'
import type {ScheduledJob} from '../../../shared/scheduler'
import {BUILTIN_PLAN_VIEWS,PLAN_STATES,PLAN_PRIORITIES,PLAN_LAYOUT_CATALOG,type PlanView as SavedView,type PlanViewSpec,type PlanQuery,type PlanRow,type PlanViewOptions} from '../../../shared/plan'
import {api} from '../api'
import {Icon} from './Icon'
import {EmployeePortrait} from './EmployeePortrait'
import {PlanEditor} from './PlanEditor'
const label=(value:string)=>uiText(value[0].toUpperCase()+value.slice(1))
const date=(value:string|null,timezone?:string)=>value?new Date(value).toLocaleString(interfaceLocale(),{timeZone:timezone,month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):uiText('No upcoming run')
export function scheduleLabel(job:ScheduledJob){
 const rule=job.rule
 if(rule.kind==='once')return uiText('One time')
 if(rule.kind==='interval'){const n=rule.everySeconds,[amount,unit]=n%86400===0?[n/86400,'day']:n%3600===0?[n/3600,'hour']:n%60===0?[n/60,'minute']:[n,'second'];return uiText('Every {0} {1}',[amount,uiText(unit+(amount===1?'':'s'))])}
 if(rule.kind==='monthly')return uiText('Monthly · {0} · {1}',[rule.day==='last'?uiText('last day'):uiText('day {0}',[rule.day]),rule.time])
 return `${rule.days.length===7?uiText('Daily'):rule.days.map(day=>uiText(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][day-1])).join(', ')} · ${rule.time}`
}
const EMPTY:PlanQuery={rows:[],total:0,offset:0,hasMore:false,counts:{scheduled:0,running:0,paused:0,completed:0,attention:0}}
const layoutHelp={
 table:'Compare tasks, owners and outcomes. Select a row to edit.',
 board:'See how work is distributed. Open a card to edit its schedule.',
 timeline:'See when work happened and what is coming next. Select an event for details.',
 calendar:'Browse work by date. Select a day for its agenda or a task to edit.',
 plan:'Plan the day or week. Open any occurrence to adjust its task.',
 list:'Scan your tasks and next runs. Select a task to edit.',
 gallery:'Browse task briefs, owners and notes. Open a card to edit.',
 chart:'Compare schedule counts or recorded run outcomes across all matching tasks.',
 feed:'Review execution results and open the original conversation.',
 form:'Assign a task and choose when it should run.'
} as const
export function PlanView({store,view,act}:{store:Store;view:ViewState;act:(cmd:string,args?:Record<string,unknown>)=>Promise<any>}){
  useI18n()

 const [views,setViews]=useState<SavedView[]>(BUILTIN_PLAN_VIEWS),[config,setConfig]=useState<PlanViewSpec>(BUILTIN_PLAN_VIEWS[0]),[result,setResult]=useState<PlanQuery>(EMPTY),[schema,setSchema]=useState<any>(),[health,setHealth]=useState<any>(),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[generation,setGeneration]=useState(0),[reload,setReload]=useState(0),[filtersOpen,setFiltersOpen]=useState(false)
 const [editing,setEditing]=useState<ScheduledJob|'new'|null>(null),[viewEditor,setViewEditor]=useState<'new'|'edit'|null>(null),[viewName,setViewName]=useState(''),[viewError,setViewError]=useState(''),[saving,setSaving]=useState(false)
 const appliedView=useRef(''),formVisited=useRef(false),openSequence=useRef(0),viewBase=useRef({id:'',revision:0})
 useDialogFocus('.plan-saved-view-editor',!!viewEditor)
 useEffect(()=>{if(!viewEditor)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!event.defaultPrevented&&!event.isComposing&&!saving){event.preventDefault();setViewEditor(null)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[viewEditor,saving])
 if(config.layout==='form')formVisited.current=true
 const selected=views.find(item=>item.id===view.planViewId)??views[0],hostZone=schema?.scheduler?.hostTimezone??Intl.DateTimeFormat().resolvedOptions().timeZone,timezone=config.options?.timezone??hostZone
 const onOptions=(patch:Partial<PlanViewOptions>)=>setConfig(previous=>({...previous,options:{...previous.options,...patch}}))
 const pageable=['table','board','list','gallery'].includes(config.layout)
 const filterCount=Object.entries(config.filter).filter(([key,value])=>key!=='search'&&(Array.isArray(value)?value.length:!!value)).length
 useEffect(()=>{let alive=true;const load=()=>void Promise.all([api.call<SavedView[]>('plan.views'),api.call('plan.schema'),api.call('schedule.status')]).then(([v,s,h])=>{if(alive){setViews(v);setSchema(s);setHealth(h)}}).catch(cause=>{if(alive)setError(cause.message)});load();const off=api.onEvent(event=>{if(event.channel==='plan:changed')load()});return()=>{alive=false;off()}},[])
 useEffect(()=>{if(viewEditor)return;const key=selected.id+':'+selected.revision;if(appliedView.current!==key){appliedView.current=key;setConfig(selected);setOffset(0)}},[selected.id,selected.revision,viewEditor])
 const queryKey=JSON.stringify([config.filter,config.sort,config.direction,offset,reload])
 useEffect(()=>{let alive=true,timer:ReturnType<typeof setTimeout>|undefined,running=false,again=false
  const load=async()=>{if(running){again=true;return}running=true;try{const [data,currentHealth]=await Promise.all([api.call<PlanQuery>('plan.query',{filter:config.filter,sort:config.sort,direction:config.direction,offset,limit:100}),api.call('schedule.status')]);if(alive){setHealth(currentHealth);if(offset>0&&offset>=data.total){setOffset(Math.max(0,Math.floor((data.total-1)/100)*100));return}setResult(data);setError('');setGeneration(value=>value+1)}}catch(cause){if(alive)setError((cause as Error).message)}finally{running=false;if(alive)setLoading(false);if(again&&alive){again=false;void load()}}}
  setLoading(true);void load();const off=api.onEvent(event=>{if(['schedule:changed','schedule:run','store:changed'].includes(event.channel)&&!timer)timer=setTimeout(()=>{timer=undefined;void load()},90)})
  return()=>{alive=false;off();clearTimeout(timer)}
 },[queryKey])
 const filter=(patch:Partial<PlanViewSpec['filter']>)=>{setConfig(prev=>({...prev,filter:{...prev.filter,...patch}}));setOffset(0)}
 const select=(id:string)=>{const next=views.find(item=>item.id===id),key=next?next.id+':'+next.revision:'';if(next){appliedView.current=key;setConfig(next);setOffset(0)}void act('view.open',{kind:'plan',planViewId:id}).then(result=>{if(!result&&appliedView.current===key){appliedView.current=selected.id+':'+selected.revision;setConfig(selected)}})}
 const closeEditor=()=>{openSequence.current++;setEditing(null)}
 const newSchedule=()=>{openSequence.current++;setEditing('new')}
 const open=async(id:string)=>{const sequence=++openSequence.current;try{const job=await api.call<ScheduledJob>('schedule.get',{id});if(sequence===openSequence.current)setEditing(job)}catch(cause){if(sequence===openSequence.current)setError((cause as Error).message)}}
 useEffect(()=>()=>{openSequence.current++},[])
 const mutate=async(cmd:string,args:Record<string,unknown>)=>{setSaving(true);try{await api.call(cmd,args);setError('');return true}catch(cause){setError((cause as Error).message);return false}finally{setSaving(false)}}
 const saveView=async()=>{setSaving(true);setViewError('');try{const spec={name:viewName,layout:config.layout,groupBy:config.groupBy,filter:config.filter,sort:config.sort,direction:config.direction,options:config.options};const next=await api.call<SavedView>(viewEditor==='edit'?'plan.view-update':'plan.view-create',viewEditor==='edit'?{id:viewBase.current.id,expectedRevision:viewBase.current.revision,patch:spec}:{spec});setViewEditor(null);setViews(await api.call<SavedView[]>('plan.views'));appliedView.current=next.id+':'+next.revision;setConfig(next);setOffset(0);await act('view.open',{kind:'plan',planViewId:next.id})}catch(cause){setViewError((cause as Error).message)}finally{setSaving(false)}}
 const reloadView=async()=>{setSaving(true);setViewError('');try{const current=await api.call<SavedView[]>('plan.views'),latest=current.find(item=>item.id===viewBase.current.id);if(!latest)throw Error('Unknown Plan view');setViews(current);viewBase.current={id:latest.id,revision:latest.revision};setViewName(latest.name);setConfig(latest);setViewError('')}catch(cause){setViewError((cause as Error).message)}finally{setSaving(false)}}
 const removeView=async()=>{setSaving(true);setViewError('');try{await api.call('plan.view-delete',{id:viewBase.current.id,expectedRevision:viewBase.current.revision});setViews(await api.call<SavedView[]>('plan.views'));setViewEditor(null);select('table')}catch(cause){setViewError((cause as Error).message)}finally{setSaving(false)}}
 const groupNames=useMemo(()=>config.groupBy==='priority'?[...PLAN_PRIORITIES].reverse():config.groupBy==='employee'?[...new Set(result.rows.map(row=>row.action.employeeId))]:PLAN_STATES,[config.groupBy,result.rows])
 const groupValue=(row:PlanRow)=>config.groupBy==='priority'?row.plan?.priority??'normal':config.groupBy==='employee'?row.action.employeeId:row.status
 const assignee=(row:PlanRow)=><span className="plan-person">{row.employee?<EmployeePortrait avatar={row.employee.avatar as any} color={row.employee.color}/>:<span className="plan-person-missing"><Icon name="person"/></span>}<span>{row.employee?.title??uiText("Removed employee")}<small>{row.employee?.team}</small></span></span>
 const status=(row:PlanRow)=><span className={`plan-status state-${row.status}`} title={row.status==='completed'?uiText("No future occurrences. Check Last run for the actual outcome."):undefined}><i/>{label(row.status)}</span>
 return <main className="plan-view" aria-label={uiText("Plan view")}>
  <header className="plan-heading"><div className="plan-page-icon"><Icon name="table"/></div><div className="plan-heading-copy"><h1>{uiText("Plan")}</h1><p>{uiText("Tasks, schedules and outcomes in one database.")}</p></div><div className="plan-heading-actions"><div className="plan-health"><span className={health?.running?'online':''}><i/>{health?.running?uiText("Scheduler online"):health?uiText("Scheduler offline"):uiText("Checking scheduler…")}</span><span><Icon name="globe"/>{timezone}</span><span><strong>{result.counts.running}</strong> {uiText("running")}</span></div><button className="plan-new primary" onClick={newSchedule}><Icon name="add"/>  {uiText("New schedule")}</button></div></header>
  <section className="plan-database">
   <div className="plan-view-tabs" role="tablist" aria-label={uiText("Plan database views")} onKeyDown={event=>{
    if(!(event.target instanceof HTMLElement)||event.target.getAttribute('role')!=='tab'||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return
    event.preventDefault();const tabs=Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('[role=tab]')),index=tabs.indexOf(event.target as HTMLButtonElement),next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length
    tabs[next].focus();select(views[next].id)
   }}>{views.map(item=><button key={item.id} role="tab" tabIndex={selected.id===item.id?0:-1} aria-selected={selected.id===item.id} onClick={()=>select(item.id)}><Icon name={PLAN_LAYOUT_CATALOG.find(layout=>layout.id===item.layout)?.icon??'table'}/>{item.builtin?uiText(item.name):item.name}</button>)}<button aria-label={uiText("Save a Plan view")} onClick={()=>{setViewError('');setViewName('');setViewEditor('new')}}><Icon name="add"/></button>{!selected.builtin&&<button aria-label={uiText("Edit saved Plan view")} onClick={()=>{setViewError('');viewBase.current={id:selected.id,revision:selected.revision};setViewName(selected.name);setViewEditor('edit')}}><Icon name="edit"/></button>}</div>
   <div className="plan-layout-heading"><div><h2>{selected.builtin?uiText(selected.name):selected.name}</h2><p>{uiText(layoutHelp[config.layout])}</p></div>{pageable&&<span>{uiText('{0} tasks',[result.total])}</span>}</div>
   {config.layout!=='form'&&<div className="plan-filter-bar">
    <label className="plan-search"><Icon name="search"/><input aria-label={uiText("Search schedules")} placeholder={uiText("Search tasks, prompts, tags…")} value={config.filter.search??''} onChange={e=>filter({search:e.target.value})}/></label>
    <button className="plan-filter-toggle" aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(value=>!value)}><Icon name="filter"/>{uiText("Filters")}{filterCount>0&&<b>{filterCount}</b>}</button>
    <div className="plan-filter-fields" data-expanded={filtersOpen}>
    <select aria-label={uiText("Filter by Team")} value={config.filter.team??''} onChange={e=>filter({team:e.target.value||undefined})}><option value="">{uiText("All teams")}</option>{store.groups.map(team=><option key={team}>{team}</option>)}</select>
    <select aria-label={uiText("Filter by employee")} value={config.filter.employee??''} onChange={e=>filter({employee:e.target.value||undefined})}><option value="">{uiText("All employees")}</option>{store.sessions.filter(card=>!card.deleting).map(card=><option key={card.id} value={card.id}>{card.title} · {card.group}</option>)}</select>
    <select aria-label={uiText("Filter by tag")} value={config.filter.tags?.[0]??''} onChange={e=>filter({tags:e.target.value?[e.target.value]:undefined})}><option value="">{uiText("All tags")}</option>{[...new Set([...(result.facets?.tags??result.rows.flatMap(row=>row.plan?.tags??[])),...(config.filter.tags??[])])].sort().map(tag=><option key={tag}>{tag}</option>)}</select>
    <select aria-label={uiText("Filter by state")} value={config.filter.states?.[0]??''} onChange={e=>filter({states:e.target.value?[e.target.value as any]:undefined})}><option value="">{uiText("All states")}</option>{PLAN_STATES.map(state=><option key={state} value={state}>{label(state)}</option>)}</select>
    <select aria-label={uiText("Filter by priority")} value={config.filter.priorities?.[0]??''} onChange={e=>filter({priorities:e.target.value?[e.target.value as any]:undefined})}><option value="">{uiText("All priorities")}</option>{PLAN_PRIORITIES.map(state=><option key={state} value={state}>{label(state)}</option>)}</select>
    {pageable&&<><select aria-label={uiText("Sort schedules")} value={config.sort} onChange={e=>setConfig(prev=>({...prev,sort:e.target.value as any}))}>{[['nextAt','Next run'],['name','Name'],['updatedAt','Updated'],['priority','Priority']].map(([v,l])=><option key={v} value={v}>{uiText(l)}</option>)}</select>
    <button aria-label={uiText("Reverse sort direction")} onClick={()=>setConfig(prev=>({...prev,direction:prev.direction==='asc'?'desc':'asc'}))}><Icon name={config.direction==='asc'?'arrow-up':'arrow-down'}/></button></>}
    {Object.values(config.filter).some(value=>Array.isArray(value)?value.length:!!value)&&<button className="plan-clear-filters" onClick={()=>{setConfig(prev=>({...prev,filter:{}}));setOffset(0)}}>{uiText("Clear filters")}</button>}
    {config.layout==='board'&&<select aria-label={uiText("Group board by")} value={config.groupBy} onChange={e=>setConfig(prev=>({...prev,groupBy:e.target.value as any}))}><option value="status">{uiText("By state")}</option><option value="employee">{uiText("By employee")}</option><option value="priority">{uiText("By priority")}</option></select>}
    </div>
   </div>}
   {error&&<p className="plan-error" role="alert">{error}<button onClick={()=>setReload(value=>value+1)}>{uiText("Retry")}</button></p>}
   <div className="plan-database-content" aria-busy={loading}>
    {loading&&!result.total&&pageable&&<div className="plan-loading" role="status"><Icon name="loading"/>{uiText("Loading…")}</div>}
    {config.layout==='table'&&<table className="plan-table"><thead><tr>{['Task','State','Employee','Repeat','Next run','Last run','Priority','Tags',''].map((name,i)=><th key={i}>{uiText(name)}</th>)}</tr></thead><tbody>{result.rows.map(row=><tr key={row.id} data-plan-id={row.id} tabIndex={0} aria-label={uiText("Edit schedule")+": "+row.name} onClick={event=>{if(!(event.target as HTMLElement).closest("button,a,input,select")&&!window.getSelection()?.toString())void open(row.id)}} onKeyDown={event=>{if(event.target===event.currentTarget&&(event.key==="Enter"||event.key===" ")){event.preventDefault();void open(row.id)}}}><td><button className="plan-task-name" onClick={()=>void open(row.id)}><Icon name="file-text"/><span>{row.name}</span><Icon name="arrow-up-right"/></button></td><td>{status(row)}</td><td>{assignee(row)}</td><td>{scheduleLabel(row)}{(row.rule.kind==='weekly'||row.rule.kind==='monthly')&&<small className="plan-rule-zone">{row.rule.timezone}</small>}{row.maxOccurrences&&<small className="plan-rule-zone">{row.occurrences??0} / {row.maxOccurrences}  {uiText("occurrences claimed")}</small>}</td><td>{date(row.nextAt,timezone)}</td><td><span className={'plan-run-outcome outcome-'+(row.lastRun?.status??'none')} title={row.lastRun?.message}>{row.lastRun?uiText(row.lastRun.status.replaceAll('_',' ')):uiText("Not run yet")}</span>{row.lastRun&&<small className="plan-rule-zone">{date(row.lastRun.startedAt,timezone)}</small>}</td><td><span className={'plan-priority priority-'+(row.plan?.priority??'normal')}>{label(row.plan?.priority??'normal')}</span></td><td><div className="plan-tags">{row.plan?.tags.map(tag=><span key={tag}>{tag}</span>)}</div></td><td><button disabled={saving} aria-label={`${uiText(row.enabled?'Pause':'Resume')} ${row.name}`} onClick={()=>void mutate(row.enabled?'schedule.pause':'schedule.resume',{id:row.id})}><Icon name={row.enabled?'debug-pause':'play'}/></button></td></tr>)}</tbody></table>}
    {config.layout==='board'&&result.total>result.rows.length&&<p className="plan-calendar-warning">{uiText("Column counts describe this page:")} {result.rows.length}  {uiText("of")} {result.total}  {uiText("schedules. Use pagination or filters; Chart aggregates the full matching database.")}</p>}
    {config.layout==='board'&&<div className="plan-board">{groupNames.map(group=><section className="plan-board-column" key={group} data-plan-column={group}><header><i className={`plan-column-dot state-${config.groupBy==='status'?group:'neutral'}`}/><span>{config.groupBy==='employee'?((row=>row?.employee?row.employee.title+' · '+row.employee.team:uiText('Removed employee'))(result.rows.find(row=>row.action.employeeId===group))):label(group)}</span><b>{result.rows.filter(row=>groupValue(row)===group).length}</b></header>{result.rows.filter(row=>groupValue(row)===group).map(row=><button key={row.id} data-plan-id={row.id} className="plan-board-card" onClick={()=>void open(row.id)}><div>{status(row)}<span className={'plan-priority priority-'+(row.plan?.priority??'normal')}>{label(row.plan?.priority??'normal')}</span></div><strong>{row.name}</strong><p>{row.action.prompt}</p>{assignee(row)}<div className="plan-card-due"><Icon name="calendar"/><span><small>{uiText("Next run")}</small>{date(row.nextAt,timezone)}</span></div><small>{scheduleLabel(row)}{(row.rule.kind==='weekly'||row.rule.kind==='monthly')?' · '+row.rule.timezone:''}</small>{row.plan?.notes&&<p className="plan-card-notes">{row.plan.notes}</p>}{row.lastRun&&<small className={'plan-run-outcome outcome-'+row.lastRun.status}>{uiText("Last run:")} {uiText(row.lastRun.status.replaceAll('_',' '))}</small>}<div className="plan-tags">{row.plan?.tags.map(tag=><span key={tag}>{tag}</span>)}</div><span className="plan-card-open">{uiText("Edit schedule")}<Icon name="chevron-right"/></span></button>)}{!result.rows.some(row=>groupValue(row)===group)&&<p className="plan-column-empty">{uiText("Nothing here yet")}</p>}</section>)}</div>}
    {config.layout==='list'&&<div className="plan-task-list">{result.rows.map(row=><button key={row.id} data-plan-id={row.id} onClick={()=>void open(row.id)}><span className="plan-list-check"><Icon name={row.status==='completed'?'check':'file-text'}/></span><div><strong>{row.name}</strong><p>{scheduleLabel(row)}{row.employee?.team?' · '+row.employee.team:''}</p></div>{assignee(row)}{status(row)}<time><small>{uiText("Next run")}</small>{date(row.nextAt,timezone)}</time><Icon name="chevron-right"/></button>)}</div>}
    {config.layout==='calendar'&&<PlanCalendar filter={config.filter} timezone={timezone} onTimezone={value=>onOptions({timezone:value})} generation={generation} employees={store.sessions} onOpen={id=>void open(id)}/>}
    {config.layout==='timeline'&&<PlanTimelineView filter={config.filter} options={config.options??{}} hostZone={hostZone} generation={generation} onOptions={onOptions} onOpen={id=>void open(id)}/>}
    {config.layout==='plan'&&<PlanPlannerView filter={config.filter} options={config.options??{}} hostZone={hostZone} generation={generation} onOptions={onOptions} onOpen={id=>void open(id)}/>}
    {config.layout==='gallery'&&<PlanGalleryView rows={result.rows} zone={timezone} onOpen={id=>void open(id)}/>}
    {config.layout==='chart'&&<PlanChartView filter={config.filter} options={config.options??{}} generation={generation} onOptions={onOptions}/>}
    {config.layout==='feed'&&<PlanFeedView filter={config.filter} zone={timezone} onOpen={id=>void open(id)} onConversation={employee=>void act('view.open',{kind:'conversation',employee})}/>}
    {formVisited.current&&<div hidden={config.layout!=='form'}><PlanFormView store={store} timezone={timezone} onOpen={id=>void open(id)} onConversation={employee=>void act('view.open',{kind:'conversation',employee})}/></div>}
    {!loading&&!result.total&&pageable&&<div className="plan-empty"><Icon name="calendar"/><h2>{uiText("No schedules in this view")}</h2><p>{uiText("Create a schedule or clear the filters. Your existing schedules appear here automatically.")}</p><button className="primary" onClick={newSchedule}>{uiText("New schedule")}</button></div>}
   </div>
   {pageable&&<footer className="plan-pagination"><span>{result.total?offset+1:0}–{Math.min(offset+100,result.total)}  {uiText("of")} {result.total}</span><button disabled={!offset} onClick={()=>setOffset(value=>Math.max(0,value-100))}>{uiText("Previous")}</button><button disabled={!result.hasMore} onClick={()=>setOffset(value=>value+100)}>{uiText("Next")}</button></footer>}
  </section>
  {editing&&<PlanEditor key={editing==='new'?'new':editing.id+':'+editing.revision} job={editing==='new'?undefined:editing} store={store} timezone={timezone} onClose={closeEditor} onSaved={closeEditor} onReload={setEditing} onConversation={id=>void act('view.open',{kind:'conversation',employee:id})}/>}
  {viewEditor&&createPortal(<div className="plan-editor-overlay"><div className="plan-editor-backdrop" onClick={()=>setViewEditor(null)}/><section className="plan-saved-view-editor" role="dialog" aria-modal="true" aria-label={uiText("Save Plan view")}><h2>{viewEditor==='edit'?uiText("Edit saved view"):uiText("Save this view")}</h2><p>{uiText("Keep this layout, grouping, filters and sorting. Schedule data remains shared.")}</p><label>{uiText("Name")}<input value={viewName} onChange={e=>setViewName(e.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.nativeEvent.isComposing&&!saving&&viewName.trim()){event.preventDefault();void saveView()}}}/></label>{viewError&&<div className="plan-error" role="alert">{uiText(viewError)}{viewEditor==='edit'&&<button disabled={saving} onClick={()=>void reloadView()}>{uiText("Load latest")}</button>}</div>}<footer>{viewEditor==='edit'&&<button disabled={saving} onClick={()=>void removeView()}>{uiText("Delete view")}</button>}<button onClick={()=>setViewEditor(null)}>{uiText("Cancel")}</button><button className="primary" disabled={saving||!viewName.trim()} onClick={()=>void saveView()}>{uiText("Save view")}</button></footer></section></div>,document.body)}
 </main>
}
function PlanCalendar({filter,timezone,onTimezone,generation,employees,onOpen}:{filter:PlanViewSpec['filter'];timezone:string;onTimezone:(value:string)=>void;generation:number;employees:Store['sessions'];onOpen:(id:string)=>void}){
  useI18n()

 const [agenda,setAgenda]=useState<string|null>(null)
 useEffect(()=>{if(!agenda)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!event.defaultPrevented&&!event.isComposing){event.preventDefault();setAgenda(null)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[agenda])
 useDialogFocus('.plan-day-agenda',!!agenda)
 const [month,setMonth]=useState(()=>Temporal.Now.plainDateISO(timezone).with({day:1}).toString()),[data,setData]=useState<{events:Array<{id:string;jobId:string;name:string;employeeId:string;at:string;date:string;status:string;runId?:string}>;truncated:boolean}>({events:[],truncated:false}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[reload,setReload]=useState(0)
 const first=Temporal.PlainDate.from(month),start=first.subtract({days:first.dayOfWeek-1}),end=start.add({days:42}),key=JSON.stringify([month,timezone,filter,generation,reload])
 useEffect(()=>{let alive=true;setLoading(true);void api.call<typeof data>('plan.calendar',{from:start.toZonedDateTime({timeZone:timezone,plainTime:'00:00'}).toInstant().toString(),to:end.toZonedDateTime({timeZone:timezone,plainTime:'00:00'}).toInstant().toString(),timezone,filter}).then(result=>{if(alive){setData(result);setError('')}}).catch(cause=>{if(alive){setError(cause.message);setData({events:[],truncated:false})}}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[key])
 const today=Temporal.Now.plainDateISO(timezone).toString()
 return <div className="plan-calendar" aria-busy={loading}>
  <header><h2>{new Date(first.year,first.month-1,1).toLocaleDateString(interfaceLocale(),{month:'long',year:'numeric'})}</h2><select aria-label={uiText("Calendar time zone")} value={timezone} onChange={event=>{onTimezone(event.target.value);setAgenda(null)}}>{[...new Set([timezone,'UTC','Asia/Shanghai','America/New_York','Europe/London','Asia/Tokyo'])].map(zone=><option key={zone}>{zone}</option>)}</select><button onClick={()=>setMonth(Temporal.Now.plainDateISO(timezone).with({day:1}).toString())}>{uiText("Today")}</button><button aria-label={uiText("Previous month")} onClick={()=>setMonth(first.subtract({months:1}).toString())}><Icon name="chevron-left"/></button><button aria-label={uiText("Next month")} onClick={()=>setMonth(first.add({months:1}).toString())}><Icon name="chevron-right"/></button></header>
  {error&&<p className="plan-error" role="alert">{error}<button onClick={()=>setReload(value=>value+1)}>{uiText("Retry")}</button></p>}{data.truncated&&<p className="plan-calendar-warning">{uiText("Some high-frequency occurrences are omitted. Narrow the filter or use schedule.preview for exact dates.")}</p>}
  <div className="plan-calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=><div className="plan-calendar-weekday" key={day}>{uiText(day)}</div>)}{Array.from({length:42},(_,index)=>{const day=start.add({days:index}),dayId=day.toString(),events=data.events.filter(event=>event.date===dayId);return <section key={dayId} className={`plan-calendar-day ${day.month!==first.month?'outside':''} ${dayId===today?'today':''}`} data-plan-date={dayId}><button className="plan-day-number" aria-label={uiText("Show all {0} events on {1}",[events.length,dayId])} onClick={()=>setAgenda(dayId)}><span>{day.day}</span>{events.length>0&&<small>{events.length}</small>}</button>{events.slice(0,3).map(event=><button key={event.id} data-plan-event={event.id} title={event.name+' · '+(employees.find(card=>card.id===event.employeeId)?.title??uiText('Removed employee'))+' · '+uiText(event.status.replaceAll('_',' '))} className={'calendar-event event-'+event.status} onClick={()=>onOpen(event.jobId)}><time>{new Date(event.at).toLocaleTimeString(interfaceLocale(),{timeZone:timezone,hour:'2-digit',minute:'2-digit',hour12:false})}</time><span>{event.name}<small>{event.runId?uiText(event.status.replaceAll('_',' ')):uiText("Upcoming occurrence")}</small></span></button>)}{events.length>3&&<button className="plan-day-more" aria-label={uiText("Show all {0} events on {1}",[events.length,dayId])} onClick={()=>setAgenda(dayId)}>+{events.length-3}  {uiText("more")}</button>}</section>})}</div>
  {agenda&&createPortal(<div className="plan-editor-overlay"><div className="plan-editor-backdrop" onClick={()=>setAgenda(null)}/><section className="plan-day-agenda" role="dialog" aria-modal="true" aria-label={uiText("Day agenda")}><header><div><small>{uiText("PLAN / DAY AGENDA")}</small><h2>{new Date(agenda+'T12:00:00').toLocaleDateString(interfaceLocale(),{month:'long',day:'numeric',weekday:'long'})}</h2><p>{timezone}{!loading&&!error&&<> · {data.events.filter(event=>event.date===agenda).length} {uiText("shown occurrences")}</>}</p></div><button aria-label={uiText("Close day agenda")} onClick={()=>setAgenda(null)}><Icon name="close"/></button></header><div className="plan-day-events">{loading?<div className="plan-loading" role="status"><Icon name="loading"/>{uiText("Loading…")}</div>:error?<p className="plan-error" role="alert">{error}<button onClick={()=>setReload(value=>value+1)}>{uiText("Retry")}</button></p>:<>{!data.events.some(event=>event.date===agenda)&&<div className="plan-empty"><Icon name="calendar"/><h2>{uiText("No scheduled work")}</h2><p>{uiText("Choose another day or create a new schedule.")}</p></div>}{data.events.filter(event=>event.date===agenda).map(event=><button key={event.id} className="plan-day-event" data-plan-event={event.id} onClick={()=>{setAgenda(null);onOpen(event.jobId)}}><time>{new Date(event.at).toLocaleTimeString(interfaceLocale(),{timeZone:timezone,hour:'2-digit',minute:'2-digit',hour12:false})}</time><div><strong>{event.name}</strong><small>{employees.find(card=>card.id===event.employeeId)?.title??uiText("Removed employee")} · {event.runId?uiText("Recorded run"):uiText("Upcoming occurrence")}</small></div><span className={'plan-run-outcome outcome-'+event.status}>{uiText(event.status.replaceAll('_',' '))}</span></button>)}</>}</div>{data.truncated&&<p className="plan-calendar-warning">{uiText("This is a bounded forecast. Narrow the filter to inspect high-frequency schedules.")}</p>}</section></div>,document.body)}
 </div>
}
