import {prepareRevision} from '../workflow.mjs';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createNodeClient} from '../../../Contract/node-client.mjs';
import {application,coreFixture,waitFor,evidence,exec,engine} from './host.mjs';
import {brief,source,outline,content} from './fixtures.mjs';
import {makeDeck,clone} from '../scene.mjs';
import {renderGenerated} from '../render.mjs';
import {inspectPptx,sha256,comparePackages} from '../archive.mjs';
const report={passed:false,checks:[],paidModelCalls:0,productionDataUsed:false};let app,f;
const pass=text=>{report.checks.push(text);console.log('PASS '+text);};
async function settled(id){return waitFor(async()=>{const v=await f.client.invoke('workflow.get',{id});if(v.status==='failed')throw Object.assign(Error(v.error),{fatal:true,job:v});return v.status!=='running'&&v;},'PPT workflow settles',120000);}
async function answer(v,value,key){await f.client.invoke('workflow.respond',{id:v.id,expectedRevision:v.revision,clientRequestId:key,answer:{deckRevision:v.summary.deckRevision,...value}});return settled(v.id);}
async function download(v){assert.equal(v.files.length,1);const file=await f.client.invoke('workflow.file',{id:v.id,name:v.files[0].name});assert.equal(file.encoding,'base64');const bytes=Buffer.from(file.content,'base64');assert.equal(bytes.length,file.bytes);assert.equal(sha256(bytes),file.sha256);await inspectPptx(bytes);return bytes;}
try{
 app=await application();f=await coreFixture(app);report.appSnapshot=app.root;
 const catalog=await f.client.engines();assert.ok(JSON.stringify(catalog).includes('PPT-maker'));assert.ok((await f.client.invoke('engine.check',{engine:'pi'})).ready);pass('All concurrent Engine pages build in an isolated snapshot; PPT-maker is discoverable via public Contract');
 const original=await renderGenerated(makeDeck(content(outline(3)),{sources:[{id:'S1',name:'test'}]}));
 let t=await f.client.invoke('workflow.start',{engineId:'PPT-maker',input:{template:{name:'brand.pptx',content:original.bytes.toString('base64')}},clientRequestId:'native-template-no-model'});t=await settled(t.id);assert.equal(t.summary.phase,'edit');assert.equal(t.summary.workers.length,0);
 const exact=await answer(t,{action:'export',acceptWarnings:true,confirmReview:true},'native-template-export');assert.ok((await download(exact)).equals(original.bytes));pass('Actual Core accepts template input and final base64 PPTX; no-model unmodified round-trip is byte-identical');
 const input={brief,materials:[source],slideCount:8,confirmOutline:true,engines:[{engine:'pi'}]},request={engineId:'PPT-maker',input,clientRequestId:'native-create'};
 let v=await f.client.invoke('workflow.start',request);const duplicate=await f.client.invoke('workflow.start',request);assert.equal(v.id,duplicate.id);v=await settled(v.id);assert.equal(v.summary.phase,'outline');assert.equal(v.summary.tasks.length,1);
 const plan=clone(v.summary.outline);plan.title='真实公共接口制作验证';plan.slides[1].title='用户确认的故事结构';v=await answer(v,{action:'approve-outline',outline:plan},'native-outline');assert.equal(v.summary.phase,'edit');assert.equal(v.summary.workers.length,3);assert.equal(new Set(v.summary.workers.map(w=>w.id)).size,3);assert.equal(v.summary.deck.slides[1].title,plan.slides[1].title);assert.equal(v.summary.title,plan.title);pass('Real Pi processes perform identity/document initialization and planning, content/design, independent review through public Infra APIs');
 const old=clone(v.summary.deck),slide=old.slides[2].id;v=await answer(v,{action:'ai-edit',slideId:slide,instruction:'精简这一页标题，保留事实'},'native-page-edit');assert.equal(v.summary.deck.slides[2].title,'真实协议完成的单页修订');for(const s of old.slides)if(s.id!==slide)assert.deepEqual(v.summary.deck.slides.find(p=>p.id===s.id),s);pass('Natural-language single-page revision modifies only the requested page');
 const d=clone(v.summary.deck);d.slides[0].notes='通过公共Core保存的演讲者备注';d.slides[5].elements.find(e=>e.type==='chart').chart.series[0].values[1]=77;d.slides[6].elements.find(e=>e.type==='table').rows[1][0]='原生表格文字';const oldRevision=v.summary.deckRevision;v=await answer(v,{action:'save',deck:d},'native-manual-save');assert.equal(v.summary.review.stale,true);
 await assert.rejects(()=>f.client.invoke('workflow.respond',{id:v.id,expectedRevision:v.revision,clientRequestId:'native-stale',answer:{action:'save',deckRevision:oldRevision,deck:d}}));
 v=await answer(v,{action:'export',acceptWarnings:true,confirmReview:true},'native-final-export');assert.equal(v.status,'completed');assert.equal(v.files[0].name,'presentation.pptx');const bytes=await download(v),info=await inspectPptx(bytes);assert.equal(info.slides,8);assert.equal(info.native.charts,1);assert.equal(info.native.tables,1);assert.ok(info.perSlide.some(s=>s.text.includes('原生表格文字')));fs.writeFileSync(path.join(evidence,'native-presentation.pptx'),bytes);pass('Revision-safe manual notes/chart/table edits export one valid native editable PPTX with checked SHA-256');
 const list=await f.client.invoke('session.list',{});assert.equal(list.sessions.length,3);const originalHash=v.files[0].sha256;
 let fork=await f.client.invoke('workflow.start',{engineId:'PPT-maker',input:await prepareRevision(f.client,v.id),clientRequestId:'native-fork'});fork=await settled(fork.id);assert.equal(fork.status,'waiting');assert.equal(fork.summary.parentId,v.id);assert.equal((await f.client.invoke('session.list',{})).sessions.length,3);pass('Completed presentation can create a new manual revision without duplicate employees or changing its previous file');
 await f.stop();await f.start();const after=await f.client.invoke('workflow.get',{id:v.id});assert.equal(after.status,'completed');assert.equal(after.files[0].sha256,originalHash);assert.ok((await download(after)).equals(bytes));assert.equal((await f.client.invoke('workflow.get',{id:fork.id})).status,'waiting');pass('Isolated Core restart preserves completed PPTX, waiting editor revision and original employee identities');
 const cli=path.join(engine,'cli.mjs'),target=path.join(f.temp,'final.pptx'),env={...f.env,AEXUS_CLI:f.cli};await exec(process.execPath,[cli,'download','--id',v.id,'--output',target],{env});assert.ok(fs.readFileSync(target).equals(bytes));await assert.rejects(()=>exec(process.execPath,[cli,'download','--id',v.id,'--output',target],{env}));pass('PPT-maker CLI downloads the same hash-checked file and refuses overwriting existing output');
 const outsider=await f.admin('card.create',{title:'Independent test employee',group:list.sessions[0].group,engine:'pi',managementRole:'employee'});await waitFor(async()=>(await f.client.invoke('session.status',{employee:outsider.id}))[0]?.initialization?.status==='ready','outsider initialization');const issued=await f.admin('auth.agent-token',{id:outsider.id}),token=typeof issued==='string'?issued:issued.token;assert.ok(token);const other=createNodeClient({cli:f.cli,env:{...f.env,AGENTS_COMPANY_EMPLOYEE:outsider.id,AGENTS_COMPANY_AGENT_TOKEN:token}});await assert.rejects(()=>other.invoke('workflow.get',{id:v.id}));assert.deepEqual(await f.client.invoke('schedule.list',{}),[]);pass('Unrelated employee cannot read operator workflow; PPT engine creates no Plan schedules');
 f.provider.setStalled(true);let pending=await f.client.invoke('workflow.start',{engineId:'PPT-maker',input:{...input,slideCount:3,confirmOutline:false},clientRequestId:'native-cancel'});pending=await waitFor(async()=>{const q=await f.client.invoke('workflow.get',{id:pending.id});if(q.status==='failed')throw Object.assign(Error(q.error),{fatal:true});return q.summary.tasks?.some(t=>t.status==='running')&&q;},'owned native task starts',60000);await f.client.invoke('workflow.cancel',{id:pending.id});assert.equal((await f.client.invoke('workflow.get',{id:pending.id})).status,'cancelled');await waitFor(async()=>{const a=await Promise.all(pending.summary.workers.map(w=>f.client.invoke('session.status',{employee:w.id})));return a.flat().every(s=>!s.busy);},'only owned task stops');assert.equal((await f.client.invoke('workflow.get',{id:v.id})).files[0].sha256,originalHash);f.provider.setStalled(false);pass('Cancel stops only the current workflow native task and leaves the completed presentation unchanged');
 report.nativeCalls=f.provider.calls;assert.ok(report.nativeCalls.some(c=>c.toolCalls.length));report.passed=true;
}catch(e){report.error=e.stack;console.error(e);process.exitCode=1;if(f)console.error('Public workflow summaries',JSON.stringify(await f.client.invoke('workflow.list',{engineId:'PPT-maker'}).then(v=>v.jobs.map(j=>({id:j.id,status:j.status,error:j.error,phase:j.summary.phase,tasks:j.summary.tasks}))).catch(e=>({error:e.message}))));}
finally{if(f)fs.writeFileSync(path.join(evidence,'core.log'),f.log());await f?.close();app?.dispose();fs.writeFileSync(path.join(evidence,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,evidence}));}
