import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import os from 'node:os';
import http from 'node:http';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createHarness,source,brief,outline,content} from './fixtures.mjs';
import {makeDeck} from '../scene.mjs';
import {renderGenerated} from '../render.mjs';
import {inspectPptx} from '../archive.mjs';
const require=createRequire(import.meta.url),{build}=require('esbuild'),{chromium}=require('playwright');
const root=fileURLToPath(new URL('..',import.meta.url)),out=path.join(root,'test-artifacts/ui');await fs.mkdir(out,{recursive:true});
const buildDir=await fs.mkdtemp(path.join(os.tmpdir(),'ppt-maker-ui-'));
const entry=`import React from 'react';import{createRoot}from'react-dom/client';import Page from ${JSON.stringify(path.join(root,'Page.tsx'))};const client={invoke:async(command,args={})=>{const r=await fetch('/api',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command,args})});const data=await r.json();if(!data.ok)throw Error(data.error);return data.data},describe:async()=>({}),info:async()=>({contractVersion:'1.0.0'})};createRoot(document.getElementById('root')).render(React.createElement(Page,{client}));`;
await build({stdin:{contents:entry,resolveDir:root,sourcefile:'ui-entry.tsx',loader:'tsx'},outfile:path.join(buildDir,'app.js'),bundle:true,platform:'browser',format:'iife',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},logLevel:'warning'});
const h=createHarness(),errors=[],checks=[];
const server=http.createServer(async(req,res)=>{try{if(req.url==='/api'){let text='';for await(const chunk of req){text+=chunk;if(text.length>10*1024*1024)throw Error('request too large');}const q=JSON.parse(text);try{const data=await h.call(q.command,q.args);res.setHeader('content-type','application/json');res.end(JSON.stringify({ok:true,data}));}catch(e){res.statusCode=400;res.end(JSON.stringify({ok:false,error:e.message}));}return;}
 if(req.url==='/'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>PPT-maker isolated UI test</title><link rel="stylesheet" href="/app.css"><style>body{margin:0}*{box-sizing:border-box}</style><div id="root"></div><script src="/app.js"></script></html>');return;}
 const file=req.url==='/app.js'?'app.js':req.url==='/app.css'?'app.css':null;if(!file){res.statusCode=404;res.end();return;}res.setHeader('content-type',file.endsWith('css')?'text/css':'text/javascript');res.end(await fs.readFile(path.join(buildDir,file)));
 }catch(e){res.statusCode=500;res.end(String(e.message))}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1060},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text())});
async function screen(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:false});}
async function waitEdit(){await page.locator('.a-ppt[data-ppt-status="waiting"] .a-ppt-editor').waitFor({timeout:20000});}
async function exported(){await page.getByRole('button',{name:'导出 PPTX',exact:true}).click();const check=page.locator('.a-ppt-modal input[type=checkbox]');if(await check.count())await check.check();await page.getByRole('button',{name:'验证并生成 PPTX',exact:true}).click();await page.locator('.a-ppt[data-ppt-status="completed"]').waitFor({timeout:20000});const pending=page.waitForEvent('download');await page.getByRole('button',{name:'下载 PPTX',exact:true}).click();const f=await pending,target=path.join(out,f.suggestedFilename());await f.saveAs(target);return {target,bytes:await fs.readFile(target)};}
try{
 await page.goto(url);await page.getByLabel('PPT制作需求').waitFor();await screen('01-intake');checks.push('intake rendered');
 await page.getByLabel('PPT制作需求').fill(brief);await page.getByLabel('上传原始资料').setInputFiles({name:source.name,mimeType:'text/markdown',buffer:Buffer.from(source.content)});await page.getByLabel('PPT风格').selectOption('blueprint');await page.getByRole('button',{name:'开始制作',exact:true}).click();await page.getByRole('heading',{name:'先把叙事结构定下来。'}).waitFor({timeout:20000});await screen('02-outline');
 await page.getByLabel('大纲第2页标题').fill('从清晰问题开始');await page.getByRole('button',{name:'确认结构，开始制作',exact:true}).click();await waitEdit();await screen('03-editor');checks.push('outline approved;3 agents;editable scene');
 await page.getByRole('button',{name:'选择第3页',exact:true}).click();await page.locator('.a-ppt-canvas [data-element-id="s3-heading"]').first().click();await page.getByLabel('对象文字', {exact:true}).fill('三个角色，原生协作');await page.getByRole('button',{name:'保存',exact:true}).click();await waitEdit();await page.waitForTimeout(800);checks.push('manual text save');
 await page.getByLabel('当前页修改要求').fill('只把这页标题精简，保留事实');await page.getByRole('button',{name:'交给设计师',exact:true}).click();await waitEdit();await page.waitForFunction(()=>document.querySelector('.a-ppt-canvas')?.textContent?.includes('精简后的核心观点'),{timeout:15000});await screen('04-page-ai-edit');checks.push('single-page AI edit');
 await page.getByRole('button',{name:'备注',exact:true}).click();await page.getByLabel('演讲者备注').fill('用户在编辑器中保存的备注。');await page.getByRole('button',{name:'保存',exact:true}).click();await waitEdit();await page.waitForTimeout(600);checks.push('speaker notes save');
 await page.getByRole('button',{name:'上移页面',exact:true}).click();await page.getByRole('button',{name:'复制当前页',exact:true}).click();assert.equal(await page.locator('.a-ppt-thumb').count(),9);await page.getByRole('button',{name:'删除当前页',exact:true}).click();assert.equal(await page.locator('.a-ppt-thumb').count(),8);await page.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await page.locator('.a-ppt-thumb').count(),9);await page.getByRole('button',{name:'重做',exact:true}).click();assert.equal(await page.locator('.a-ppt-thumb').count(),8);checks.push('reorder duplicate delete undo redo');
 await page.getByRole('button',{name:'选择第6页',exact:true}).click();await page.getByRole('button',{name:'属性',exact:true}).click();await page.locator('.a-ppt-canvas [data-element-id="s6-chart"]').first().click();await page.getByLabel('图表1系列2数值').fill('77');await page.getByRole('button',{name:'保存',exact:true}).click();await waitEdit();await page.waitForTimeout(600);await screen('05-editable-chart');checks.push('native chart data edit');
 await page.getByRole('button',{name:'选择第7页',exact:true}).click();await page.locator('.a-ppt-canvas [data-element-id="s7-table"]').first().click();await page.getByLabel('表格第2行第1列').fill('文字可编辑');await page.getByRole('button',{name:'保存',exact:true}).click();await waitEdit();await page.waitForTimeout(600);checks.push('native table cell edit');
 const final=await exported(),info=await inspectPptx(final.bytes);assert.equal(info.slides,8);assert.equal(info.native.charts,1);assert.equal(info.native.tables,1);assert.ok(info.perSlide.some(s=>s.text.includes('文字可编辑')));await screen('06-delivery');checks.push('download base64 SHA256 + real editable OOXML');
 await page.getByRole('button',{name:'创建修订',exact:true}).click();await waitEdit();checks.push('completed-version fork');
 await page.setViewportSize({width:720,height:1100});await screen('07-narrow-editor');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2));checks.push('720px no horizontal page overflow');
 await page.setViewportSize({width:1440,height:1060});await page.getByLabel('PPT-maker首页').click();await page.getByLabel('PPT制作需求').fill('');
 const template=await renderGenerated(makeDeck(content(outline(3)),{sources:[{id:'S1',name:'测试'}]}));await page.getByLabel('上传PPT模板').setInputFiles({name:'preserve-template.pptx',mimeType:'application/vnd.openxmlformats-officedocument.presentationml.presentation',buffer:template.bytes});await page.getByRole('button',{name:'导入并编辑',exact:true}).click();await waitEdit();await screen('08-template-import');assert.equal(await page.getByRole('button',{name:'添加文本',exact:true}).count(),0);const copied=await exported();assert.ok(copied.bytes.equals(template.bytes));checks.push('template import/manual export byte-identical');
 assert.deepEqual(errors,[]);await fs.writeFile(path.join(out,'results.json'),JSON.stringify({passed:true,checks,errors,scope:'Real browser + Engine runtime/rendering with deterministic Contract fixture; no billed model or production Core'},null,2));console.log(JSON.stringify({passed:true,checks,out},null,2));
}catch(error){await screen('failure').catch(()=>{});await fs.writeFile(path.join(out,'results.json'),JSON.stringify({passed:false,error:error.stack,errors,checks},null,2));console.error(error);process.exitCode=1;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));await fs.rm(buildDir,{recursive:true,force:true});}
