'use strict';
const {assert}=require('./safety.cjs');
const C=require('../ui/mindmap-catalog.json');
const own=(o,k)=>Object.hasOwn(o,k);
const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const fail=message=>assert(false,'INVALID_PARAMS',message);
const color=v=>typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v);
function text(v,max=500){assert(typeof v==='string'&&v.length<=max,'INVALID_PARAMS',`Text exceeds ${max} UTF-16 units.`);return v;}
function number(v,min,max,integer=false){assert(Number.isFinite(v)&&v>=min&&v<=max&&(!integer||Number.isInteger(v)),'INVALID_PARAMS',`Number must be ${integer?'an integer ':''}between ${min} and ${max}.`);return v;}
const choice=(v,values)=>{assert(values.includes(v),'INVALID_PARAMS','Unsupported mind-map option: '+String(v));return v;};
function patch(value,rules){assert(object(value),'INVALID_PARAMS','Expected an option object.');const out={};for(const [k,v] of Object.entries(value)){assert(own(rules,k),'INVALID_PARAMS','Unknown mind-map option: '+k);out[k]=v===null?null:rules[k](v);}return out;}
const flag=v=>{assert(typeof v==='boolean','INVALID_PARAMS','Expected boolean.');return v;};
const hex=v=>{assert(color(v),'INVALID_PARAMS','Use a #RRGGBB color.');return v;};
const enumOf=o=>v=>choice(v,Object.keys(o));
const font=v=>{assert(typeof v==='string'&&/^[\p{L}\p{N} _.,-]{1,100}$/u.test(v),'INVALID_PARAMS','Invalid local font name.');return v;};
const mapRules={enabled:flag,theme:enumOf(C.themes),structure:enumOf(C.structures),line:enumOf(C.lines),lineWidth:v=>number(v,.5,12),colorMode:v=>choice(v,['branch','level','single']),background:hex,textColor:hex,spacing:v=>number(v,12,100),branchSpacing:v=>number(v,30,220),autoBalance:flag,sameLevelWidth:flag,gradient:flag,shadow:flag,showImages:flag,showTags:flag,motion:flag,minimap:flag,numbering:enumOf(C.numbering),fontFamily:font,fontSize:v=>number(v,12,32),topicShape:enumOf(C.shapes),rootShape:enumOf(C.shapes),topicWidth:v=>number(v,100,600)};
const topicRules={shape:enumOf(C.shapes),fill:hex,textColor:hex,borderColor:hex,borderWidth:v=>number(v,0,10),borderDash:v=>choice(v,['solid','dash','dot']),fontFamily:font,fontSize:v=>number(v,10,48),bold:flag,italic:flag,underline:flag,strike:flag,align:v=>choice(v,['left','center','right']),width:v=>number(v,100,800),structure:enumOf(C.structures),side:v=>choice(v,['auto','left','right']),numbering:enumOf(C.numbering),branchLine:enumOf(C.lines),branchColor:hex,branchWidth:v=>number(v,.5,12),shadow:flag,gradient:flag,priority:v=>number(v,0,9,true),progress:v=>number(v,0,100,true),status:v=>choice(v,['none','todo','doing','done','blocked']),symbol:enumOf(C.symbols),flagColor:hex,showImage:flag,showNote:flag};
function runs(value,title){assert(Array.isArray(value)&&value.length<=100,'INVALID_PARAMS','At most 100 rich-text runs.');let end=0;return value.map(r=>{const p=patch(r,{start:v=>number(v,0,title.length,true),end:v=>number(v,1,title.length,true),bold:flag,italic:flag,underline:flag,strike:flag,color:hex});assert(Number.isInteger(p.start)&&Number.isInteger(p.end)&&p.start>=end&&p.end>p.start,'INVALID_PARAMS','Runs must be sorted, disjoint and within the title.');for(const offset of [p.start,p.end])assert(!(offset>0&&offset<title.length&&/[\uD800-\uDBFF]/.test(title[offset-1])&&/[\uDC00-\uDFFF]/.test(title[offset])),'INVALID_PARAMS','A text run cannot split a Unicode surrogate pair.');end=p.end;return p;});}
function topic(value,title){const {runs:rich,task,...rest}=value||{};const out=patch(rest,topicRules);if(rich!==undefined)out.runs=rich===null?null:runs(rich,title);if(task!==undefined){if(task===null)out.task=null;else{out.task=patch(task,{start:v=>date(v),due:v=>date(v),assignee:v=>text(v,120),estimate:v=>number(v,0,100000)});assert(!out.task.start||!out.task.due||out.task.start<=out.task.due,'INVALID_PARAMS','Task end cannot precede its start.');}}return out;}
function date(v){assert(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,'INVALID_PARAMS','Use a valid YYYY-MM-DD date.');return v;}
const relationRules={line:enumOf(C.lines),color:hex,width:v=>number(v,.5,12),dash:v=>choice(v,['solid','dash','dot']),start:enumOf(C.arrows),end:enumOf(C.arrows),textColor:hex,fontSize:v=>number(v,10,32),bold:flag,followTopic:flag,bendX:v=>number(v,-1000,1000),bendY:v=>number(v,-1000,1000),startX:v=>number(v,0,1),startY:v=>number(v,0,1),endX:v=>number(v,0,1),endY:v=>number(v,0,1)};
const itemRules={title:v=>text(v,500),shape:enumOf(C.boundaries),color:hex,fill:hex,opacity:v=>number(v,0,1),dash:v=>choice(v,['solid','dash','dot']),width:v=>number(v,.5,10),fontSize:v=>number(v,10,32),textColor:hex,padding:v=>number(v,8,80)};
function merge(base={},value={}){const out={...base};for(const [k,v] of Object.entries(value))v===null?delete out[k]:out[k]=v;return out;}
function validateSet(set){
 const map=set.map?.mindmap;if(map){assert(object(map),'INVALID_PARAMS','Invalid mind-map settings.');const {items,...settings}=map;patch(settings,mapRules);if(items!==undefined){assert(Array.isArray(items)&&items.length<=500,'INVALID_PARAMS','At most 500 boundaries, summaries and callouts.');const ids=new Set();for(const item of items){assert(object(item)&&typeof item.id==='string'&&/^[a-f0-9-]{36}$/i.test(item.id)&&!ids.has(item.id),'INVALID_PARAMS','Invalid mind-map annotation ID.');ids.add(item.id);choice(item.kind,['boundary','summary','callout']);assert(Array.isArray(item.cardIds)&&item.cardIds.length>0&&item.cardIds.length<=1000&&item.cardIds.every(id=>typeof id==='string'&&/^[a-f0-9-]{36}$/i.test(id)),'INVALID_PARAMS','Invalid annotation members.');if(item.topicId)assert(/^[a-f0-9-]{36}$/i.test(item.topicId),'INVALID_PARAMS','Invalid summary topic.');patch(item.style||{},itemRules);}}}
 for(const c of set.cards||[])if(c.mindmap)topic(c.mindmap,c.title||'');
 for(const l of set.links||[])if(l.mindmap)patch(l.mindmap,relationRules);
}
module.exports={C,patch,mapRules,topicRules,relationRules,itemRules,topic,runs,merge,validateSet,text,color};
