import {objectSchema,nonemptySchema,booleanSchema} from './api-schema.ts'
const conversation={type:'string',pattern:'^(group|channel):[a-zA-Z0-9_-]+$'},revision={type:'integer',minimum:1},limit={type:'integer',minimum:1,maximum:100}
const timestamp={type:'string',description:'ISO instant including Z or a UTC offset'},rule={oneOf:[objectSchema({kind:{const:'once'},at:timestamp},['kind','at']),objectSchema({kind:{const:'interval'},everySeconds:{type:'integer',minimum:60,maximum:31536000},anchor:timestamp},['kind','everySeconds','anchor']),objectSchema({kind:{const:'weekly'},time:{type:'string',pattern:'^([01][0-9]|2[0-3]):[0-5][0-9]$'},days:{type:'array',minItems:1,maxItems:7,uniqueItems:true,items:{type:'integer',minimum:1,maximum:7}},timezone:nonemptySchema},['kind','time','days','timezone'])]}
const content={name:{type:'string',minLength:1,maxLength:120},text:{type:'string',minLength:1,maxLength:2000,description:'Literal notification text only; no prompt, employee task or tool execution'},publisherId:{...nonemptySchema,description:'Existing conversation Admin/Owner Agent. Agent callers must choose themselves; the human user may choose an authorized publisher.'},rule,enabled:booleanSchema}
export const CONVERSATION_CONTROL_COMMANDS=[
 {cli:{positionals:['conversation']},name:'conversation.policy',args:'CONVERSATION',summary:'Read independent Owner/Admin/Member offices, moderation state and allowed actions; Company rank grants no conversation office',gui:'Conversation administration',inputSchema:objectSchema({conversation},['conversation'])},
 {cli:{positionals:['conversation']},name:'conversation.role',args:'CONVERSATION --employee ID --role owner|admin|member --expected-revision N',summary:'Owner/Admin may appoint or revoke Admins; only Owner transfers ownership. In channels member removes an Admin; channels have no Owner office.',gui:'Conversation roles',inputSchema:objectSchema({conversation,employee:nonemptySchema,role:{enum:['owner','admin','member']},expectedRevision:revision},['conversation','employee','role','expectedRevision'])},
 {cli:{positionals:['conversation'],booleanValues:['muted']},name:'conversation.mute',args:'CONVERSATION --member ID|all --muted true|false [--duration-seconds N] --expected-revision N',summary:'Owner/Admin changes public posting restrictions; all restricts Member posting in groups, all publishers in channels. Never changes Company work permissions.',gui:'Conversation moderation',inputSchema:objectSchema({conversation,member:nonemptySchema,muted:booleanSchema,durationSeconds:{type:'integer',minimum:1,maximum:31536000},expectedRevision:revision},['conversation','member','muted','expectedRevision'])},
 {cli:{positionals:['conversation'],booleanValues:['silent']},name:'conversation.silence',args:'CONVERSATION --silent true|false --expected-revision N',summary:'Owner/Admin enables quiet conversation notices: messages remain in history, but no notice attention banner is raised; not member posting mute',gui:'Quiet notices',inputSchema:objectSchema({conversation,silent:booleanSchema,expectedRevision:revision},['conversation','silent','expectedRevision'])},
 {cli:{positionals:['conversation']},name:'conversation.notice-list',args:'CONVERSATION [--offset N --limit N]',summary:'Owner/Admin lists independent static notifications; these IDs never belong to Plan',gui:'Conversation notifications',inputSchema:objectSchema({conversation,offset:{type:'integer',minimum:0},limit},['conversation'])},
 {cli:{positionals:['conversation']},name:'conversation.notice-get',args:'CONVERSATION --id ID',summary:'Read one notification rule, saved text, publishing identity and next occurrence; no model work',gui:'Notification details',inputSchema:objectSchema({conversation,id:nonemptySchema},['conversation','id'])},
 {cli:{positionals:['conversation']},name:'conversation.notice-create',args:'CONVERSATION --spec JSON|@file --client-request-id ID',summary:'Owner/Admin creates an idempotent static notice. Required spec: name, text, publisherId, rule, enabled. Once/interval/weekly (all days=daily), independent of Plan.',gui:'New notification',inputSchema:objectSchema({conversation,spec:objectSchema(content,Object.keys(content)),clientRequestId:{type:'string',minLength:1,maxLength:120}},['conversation','spec','clientRequestId'])},
 {cli:{positionals:['conversation']},name:'conversation.notice-update',args:'CONVERSATION --id ID --patch JSON|@file --expected-revision N',summary:'Edit text/rule/publisher or pause/resume with enabled. Rechecks conversation authority; no Plan or employee queue edits.',gui:'Edit or pause notification',inputSchema:objectSchema({conversation,id:nonemptySchema,patch:objectSchema(content),expectedRevision:revision},['conversation','id','patch','expectedRevision'])},
 {cli:{positionals:['conversation']},name:'conversation.notice-delete',args:'CONVERSATION --id ID --expected-revision N',summary:'Remove an independent notification and cancel pending occurrences; published messages and audit history remain',gui:'Delete notification',inputSchema:objectSchema({conversation,id:nonemptySchema,expectedRevision:revision},['conversation','id','expectedRevision'])},
 {cli:{positionals:['conversation']},name:'conversation.notice-preview',args:'CONVERSATION --rule JSON|@file [--from ISO]',summary:'Read the next five notice occurrences in the stated timezone. No notification, agent or Plan task is created.',gui:'Notification preview',inputSchema:objectSchema({conversation,rule,from:timestamp},['conversation','rule'])},
 {cli:{positionals:['conversation']},name:'conversation.notice-history',args:'CONVERSATION [--id ID --limit N --offset N]',summary:'Read bounded static notice publication/skipped/cancelled history, including removed notices; no model logs or Plan history',gui:'Notification history',inputSchema:objectSchema({conversation,id:nonemptySchema,limit,offset:{type:'integer',minimum:0}},['conversation'])},
]
export const CONVERSATION_CONTROL_APIS=new Set(CONVERSATION_CONTROL_COMMANDS.map(command=>command.name))
