import {objectSchema,nonemptySchema,booleanSchema} from './api-schema.ts'
const conversation={type:'string',pattern:'^(group|channel):[a-zA-Z0-9_-]+$'},revision={type:'integer',minimum:0},page={offset:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:100}}
export type WorkspaceChoice={id:string;view:'company'|'messages';employeeId:string;employeeName:string;name:string;team:string;conversation?:string;path:string;sharedRoot?:string;memberDirectory?:string;nativeAccess:boolean;location:'core'|'remote';rootAccess?:'read'|'direct-files-write';fileApi:{command:string;args:Record<string,unknown>}}
export type PostTrigger={id:string;channelId:string;employeeId:string;everyPosts:number;prompt:string;enabled:boolean;revision:number;pendingCount:number;remaining:number;createdAt:number;updatedAt:number;disabledReason?:string}
export type PostBatchReceipt={ruleId:string;batchId:string;employeeId:string;postCount:number;automatic:true}
export const MESSAGE_COLLABORATION_COMMANDS=[
 {cli:{},name:'workspace.catalog',args:'[--employee ID|self]',summary:'List your Company workspace and every joined group/channel member workspace with exact paths, location, permissions and file API; does not choose a workspace or move files',gui:'Employee workspace selector',inputSchema:objectSchema({employee:nonemptySchema})},
 {cli:{positionals:['conversation']},name:'conversation.entry',args:'CONVERSATION --id ENTRY_ID',summary:'Read a complete published group message, channel message or post: text, links, replies, media and downloadable document descriptors; current membership required',gui:'Published content and files',inputSchema:objectSchema({conversation,id:nonemptySchema},['conversation','id'])},
 {cli:{positionals:['conversation']},name:'conversation.download',args:'CONVERSATION --entry-id ID --attachment-id ID --client-request-id KEY [--workspace WORKSPACE_ID --employee ID --path DIR --name FILENAME]',summary:'Copy one published attachment into your own Company or joined Message member workspace; defaults to this conversation’s member workspace. Streams documents/images with integrity checks, never writes shared originals or overwrites files.',gui:'Download to employee workspace',inputSchema:objectSchema({conversation,entryId:nonemptySchema,attachmentId:nonemptySchema,clientRequestId:{type:'string',minLength:1,maxLength:160},workspace:nonemptySchema,employee:nonemptySchema,path:nonemptySchema,name:nonemptySchema},['conversation','entryId','attachmentId','clientRequestId'])},
 {cli:{positionals:['id']},name:'conversation.download-status',args:'ID [--cancel]',summary:'Read your attachment copy progress, final path or failure; cancel affects only your copy. Restart never blindly replays interrupted downloads.',gui:'Attachment copy progress',inputSchema:objectSchema({id:nonemptySchema,cancel:booleanSchema},['id'])},
 {cli:{positionals:['id']},name:'channel.post-trigger-list',args:'CHANNEL_ID',summary:'Read per-Agent post-count rules and progress. Owner/Admin sees all; Members see their own rule. Independent of Plan and static timed notices.',gui:'Channel post-count rules',inputSchema:objectSchema({id:nonemptySchema},['id'])},
 {cli:{positionals:['id'],booleanValues:['enabled']},name:'channel.post-trigger-set',args:'CHANNEL_ID --employee ID --every-posts N --prompt TEXT --enabled true|false --expected-revision N',summary:'Owner/Admin explicitly enables a saved prompt for one channel member every N newly accepted posts. Revision 0 creates; edits reset only this member’s counter. No Plan record; may invoke the selected Agent.',gui:'Per-Agent post-count editor',inputSchema:objectSchema({id:nonemptySchema,employee:nonemptySchema,everyPosts:{type:'integer',minimum:1,maximum:10000},prompt:{type:'string',minLength:1,maxLength:16000},enabled:booleanSchema,expectedRevision:revision},['id','employee','everyPosts','prompt','enabled','expectedRevision'])},
 {cli:{positionals:['id']},name:'channel.post-trigger-remove',args:'CHANNEL_ID --employee ID --expected-revision N',summary:'Remove one post-count configuration and cancel its unstarted batches. Existing results and batch history remain; ordinary channel awareness resumes.',gui:'Remove post-count rule',inputSchema:objectSchema({id:nonemptySchema,employee:nonemptySchema,expectedRevision:revision},['id','employee','expectedRevision'])},
 {cli:{positionals:['id']},name:'channel.post-trigger-history',args:'CHANNEL_ID [--employee ID --offset N --limit N]',summary:'Read counted batches and actual queued/running/completed/failed states, exact batch IDs and message references. Never reports a queued task as a completed summary.',gui:'Channel batch history',inputSchema:objectSchema({id:nonemptySchema,employee:nonemptySchema,...page},['id'])},
 {cli:{positionals:['id']},name:'channel.post-trigger-batch',args:'CHANNEL_ID --batch-id ID [--offset N --limit N]',summary:'Read the exact counted batch with paged complete posts and explicit unavailable entries; no approximate latest-N window, model call or user-read acknowledgment',gui:'Batch source posts',inputSchema:objectSchema({id:nonemptySchema,batchId:nonemptySchema,...page},['id','batchId'])},
]
export const MESSAGE_COLLABORATION_APIS=new Set(MESSAGE_COLLABORATION_COMMANDS.map(c=>c.name))
export const CHANNEL_POST_TRIGGER_APIS=new Set(MESSAGE_COLLABORATION_COMMANDS.filter(c=>c.name.startsWith('channel.')).map(c=>c.name))
