import {QUOTE_SCHEMA,type MessageQuote} from './message-quotes.ts'
import type {MessageAttachment} from './message-attachments'
import type {PrincipalRef} from './management'
import type {ChannelPost} from './channels'
/** Operator-owned organization of existing conversations, never a second history. */
export type ConversationPreferences={pinned?:boolean;favorite?:boolean;archived?:boolean;unread?:boolean}
export type MessagePreferences={saved?:boolean;pinned?:boolean;hidden?:boolean;reaction?:string}
export type MessageDraft={text:string;images?:string[];files?:string[];mentions?:string[]|'all';replyTo?:string;replyQuote?:MessageQuote;replyConversation?:string;replyTextOnly?:boolean;clientMessageId?:string;viewId?:string;updatedAt:number}
export const hasDraftContent=(draft:Omit<MessageDraft,'updatedAt'>)=>!!(draft.text||draft.files?.length||draft.images?.length||draft.mentions?.length||draft.replyTo)
export type ConversationFolder={id:string;name:string;conversations:string[];revision:number}
export type ForwardDraftInput={clientMessageId:string;messages:{conversation:string;id:string}[];to?:string;comment:string;textOnly:boolean;preview:{text:string;images:number};attempted:boolean}
export type ForwardResult={to:string;count:number;status:'posted'|'queued';messageId:string|null}
export type ForwardStatus={clientMessageId:string;status:'not-found'|'preparing'|'sent'|'failed'|'uncertain'|'interrupted';active:boolean;retryable:boolean;result?:ForwardResult;error?:string}
export type MessengerState={version:1;revision:number;conversations:Record<string,ConversationPreferences>;messages:Record<string,MessagePreferences>;drafts:Record<string,MessageDraft>;folders?:ConversationFolder[];pendingForward?:ForwardDraftInput&{updatedAt:number}}
export type MessengerMessage={conversation:string;conversationTitle:string;id:string;author:string;authorIdentity?:PrincipalRef;role:'user'|'assistant';text:string;images:string[];files?:MessageAttachment[];createdAt:number|null;editedAt?:number;editRevision?:number;preferences:MessagePreferences;news?:ChannelPost}
export type GalleryImage={employee?:string;group?:string;path:string;messageId?:string;caption?:string;conversationTitle?:string;editRevision?:number}
export type GalleryCursor={conversation?:string;messageId:string;path:string}
export type GalleryQuery={conversation?:string;query?:string;author?:'all'|'you'|'employee';order?:'oldest'|'newest'}
export type MessengerGalleryPage={images:GalleryImage[];offset:number;total:number;index:number;through:GalleryCursor|null}
export type MessengerResults={messages:MessengerMessage[];total:number;hasMore:boolean}
export const conversationKey=(kind:'employee'|'group'|'channel',id:string)=>kind+':'+id
export const messageLinks=(text:string)=>[...new Set(text.match(/https?:\/\/[^\s<>\)]+/g)??[])].flatMap(value=>{try{const url=new URL(value);return [{url:url.href,host:url.hostname}]}catch{return []}})
export const plainMessagePreview=(text:string)=>text.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'$1').replace(/(\*\*|__)(.*?)\1/g,'$2').replace(/`([^`]+)`/g,'$1').replace(/\*([^\s*](?:[^*\n]*[^\s*])?)\*/g,'$1').replace(/~~([^~]+)~~/g,'$1').replace(/^\s{0,3}(?:#{1,6}|[-*+]|>)\s+/gm,'').replace(/\s+/g,' ').trim()
export const messageKey=(conversation:string,id:string)=>conversation+'/'+id
export const EMPTY_MESSENGER:MessengerState={version:1,revision:0,conversations:{},messages:{},drafts:{},folders:[]}
export const MESSAGE_REACTIONS=['👍','❤️','🎉','✅','👀','💡'] as const
const ref={type:'string',pattern:'^(employee|group|channel):[a-zA-Z0-9_-]+$'},directRef={type:'string',pattern:'^(employee|group):[a-zA-Z0-9_-]+$'},bool={type:'boolean'}
const schema=(properties:Record<string,unknown>,required:string[]=[])=>({type:'object',additionalProperties:false,properties,required})
const galleryCursor=schema({conversation:directRef,messageId:{type:'string',minLength:1},path:{type:'string',minLength:1}},['messageId','path'])
const forwardDraft=schema({clientMessageId:{type:'string',minLength:1,maxLength:160},messages:{type:'array',minItems:1,maxItems:50,items:schema({conversation:ref,id:{type:'string',minLength:1}},['conversation','id'])},to:directRef,comment:{type:'string',maxLength:16000},textOnly:bool,preview:schema({text:{type:'string',maxLength:1200},images:{type:'integer',minimum:0}},['text','images']),attempted:bool},['clientMessageId','messages','comment','textOnly','preview','attempted'])
export const MESSENGER_COMMANDS=[
 {name:'messenger.media-open',args:'CONVERSATION --path PATH',summary:'User-only: open a client-scoped audio/video preview with a bounded lifetime; no inference',gui:'Media playback',inputSchema:schema({conversation:ref,path:{type:'string',minLength:1}},['conversation','path'])},
 {name:'messenger.media-info',args:'ID',summary:'User-only: validate the owned media preview and file version',gui:'Media playback',inputSchema:schema({id:{type:'string',minLength:1}},['id'])},
 {name:'messenger.media-read',args:'ID --offset N',summary:'User-only: read at most 256 KiB from an owned media preview at a validated offset',gui:'Media playback',inputSchema:schema({id:{type:'string',minLength:1},offset:{type:'integer',minimum:0}},['id','offset'])},
 {name:'messenger.media-close',args:'ID',summary:'User-only: release a media preview and stop future reads',gui:'Media playback',inputSchema:schema({id:{type:'string',minLength:1}},['id'])},
 {name:'messenger.gallery',args:'[--conversation REF] [--anchor JSON] [--direction around|before|after|first|last] [--through JSON] [--query TEXT] [--author all|you|employee] [--order oldest|newest] [--limit N]',summary:'User or Secretary: page full public image history around stable source cursors, without reading image bytes or acknowledging messages',gui:'Historical image gallery',inputSchema:schema({conversation:directRef,anchor:galleryCursor,through:galleryCursor,direction:{enum:['around','before','after','first','last']},query:{type:'string',maxLength:500},author:{enum:['all','you','employee']},order:{enum:['oldest','newest']},limit:{type:'integer',minimum:1,maximum:100}})},
 {name:'messenger.upload-begin',args:'CONVERSATION --name NAME --bytes N',summary:'User-only: allocate a unique conversation attachment and begin a chunked upload',gui:'Message attachments',inputSchema:schema({conversation:directRef,name:{type:'string'},bytes:{type:'integer',minimum:0,maximum:2147483648}},['conversation','name','bytes'])},
 {name:'messenger.reference',args:'CONVERSATION MESSAGE_ID [--quote JSON] [--text-only]',summary:'User-only: resolve a public cross-conversation reference without sending, opening an engine or acknowledging a message',gui:'Reply destination preview',inputSchema:schema({conversation:ref,id:{type:'string'},quote:QUOTE_SCHEMA,textOnly:bool},['conversation','id'])},
 {name:'messenger.forward',args:'--messages JSON --to REF --client-message-id ID [--comment TEXT] [--text-only] [--retry]',summary:'User-only: deliberately forward selected public messages through existing Core send/queue paths, with durable retry protection',gui:'Message forwarding',inputSchema:schema({messages:{type:'array',minItems:1,maxItems:50,items:schema({conversation:ref,id:{type:'string'}},['conversation','id'])},to:directRef,comment:{type:'string',maxLength:16000},textOnly:bool,retry:bool,clientMessageId:{type:'string',minLength:1,maxLength:160}},['messages','to','clientMessageId'])},
 {name:'messenger.forward-draft',args:'--data JSON|null [--expected-client-message-id ID]',summary:'User-only: retain or discard one forwarding setup; discarding never cancels accepted work',gui:'Resume forwarding',inputSchema:schema({value:{anyOf:[forwardDraft,{type:'null'}]},expectedClientMessageId:{type:'string',minLength:1,maxLength:160}},['value'])},
 {name:'messenger.forward-status',args:'--client-message-id ID',summary:'User-only: check a forwarding receipt without sending, reading sources or starting work',gui:'Forwarding result',inputSchema:schema({clientMessageId:{type:'string',minLength:1,maxLength:160}},['clientMessageId'])},
 {name:'messenger.state',args:'',summary:'User or Secretary: read persisted conversation preferences, saved messages, reactions and drafts',gui:'Messages organization',inputSchema:schema({})},
 {name:'messenger.folder-save',args:'--name NAME --conversations JSON [--id ID] [--expected-revision N]',summary:'User or Secretary: create or update a personal folder of private, group and channel conversations without moving their content',gui:'Conversation folders',inputSchema:schema({id:{type:'string'},name:{type:'string',minLength:1,maxLength:80},conversations:{type:'array',maxItems:2000,items:ref},expectedRevision:{type:'integer',minimum:0}},['name','conversations'])},
 {name:'messenger.folder-delete',args:'ID [--expected-revision N]',summary:'User or Secretary: remove a personal conversation folder while retaining every conversation and message',gui:'Conversation folders',inputSchema:schema({id:{type:'string'},expectedRevision:{type:'integer',minimum:0}},['id'])},
 {name:'messenger.conversation',args:'--conversations JSON --patch JSON',summary:'User or Secretary: pin, favorite, archive or mark conversations unread in one atomic update',gui:'Messages list and bulk actions',inputSchema:schema({conversations:{type:'array',items:ref,minItems:1,maxItems:200},patch:schema({pinned:bool,favorite:bool,archived:bool,unread:bool})},['conversations','patch'])},
 {name:'messenger.message',args:'CONVERSATION [MESSAGE_ID | --ids JSON] --patch JSON',summary:'User or Secretary: save, pin, react to or hide an existing public message; native history stays intact',gui:'Messages actions',inputSchema:schema({conversation:ref,id:{type:'string'},ids:{type:'array',items:{type:'string'},minItems:1,maxItems:200},patch:schema({saved:bool,pinned:bool,hidden:bool,reaction:{enum:['',...MESSAGE_REACTIONS]}})},['conversation','patch'])},
 {name:'messenger.draft',args:'CONVERSATION --data JSON',summary:'User or Secretary: persist a draft and its send identity, or conditionally clear the matching draft; never sends or opens an engine',gui:'Messages composer',inputSchema:schema({conversation:ref,text:{type:'string',maxLength:100000},images:{type:'array',items:{type:'string'},maxItems:16},files:{type:'array',items:{type:'string'},maxItems:16},mentions:{oneOf:[{const:'all'},{type:'array',items:{type:'string'},maxItems:200}]},replyTo:{type:'string'},replyQuote:QUOTE_SCHEMA,replyConversation:ref,replyTextOnly:bool,clientMessageId:{type:'string',minLength:1,maxLength:160,description:'Identity of this send snapshot. Reuse for unchanged group/channel retries and the private-send acceptance receipt contract; uncertain private work is never replayed.'},viewId:{type:'string',minLength:1,maxLength:160,description:'Frozen Company team-view scope for a private/group attempt; not a Plan or plugin view.'},expectedClientMessageId:{type:'string',minLength:1,maxLength:160,description:'Apply this draft replacement or clear only if the saved clientMessageId matches; otherwise return current state unchanged.'}},['conversation','text'])},
 {name:'messenger.search',args:'[--conversation REF] [--query TEXT] [--filter all|saved|pinned|media|audio|files|links] [--author all|you|employee] [--offset N] [--limit N]',summary:'User or Secretary: search full public histories and saved/media/link references without inference or read acknowledgements',gui:'Messages search and shared content',inputSchema:schema({conversation:ref,query:{type:'string',maxLength:500},filter:{enum:['all','saved','pinned','media','audio','files','links']},author:{enum:['all','you','employee']},offset:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:100}})}
]
