import {PLAN_LAYOUTS,PLAN_PRIORITIES,PLAN_STATES,PLAN_RUN_STATES} from './plan.ts'
const text={type:'string',minLength:1},id={...text,description:'Stable saved ID'}
export const PLAN_FILTER_SCHEMA={type:'object',additionalProperties:false,properties:{search:{type:'string',maxLength:240},employee:{...id,description:'Employee ID or self'},team:text,states:{type:'array',items:{enum:PLAN_STATES}},priorities:{type:'array',items:{enum:PLAN_PRIORITIES}},tags:{type:'array',maxItems:20,items:text}}}
export const PLAN_OPTIONS_SCHEMA={type:'object',additionalProperties:false,properties:{
 timezone:{...text,description:'IANA display timezone, saved with this view; never changes schedule execution'},
 timelineScale:{enum:['day','week','month']},plannerMode:{enum:['day','week','agenda']},
 chartMetric:{enum:['schedules','runs']},chartGroupBy:{enum:['status','employee','team','priority']},chartType:{enum:['bar','horizontal','line','donut']}
}}
export const PLAN_VIEW_SCHEMA={type:'object',required:['name','layout'],additionalProperties:false,properties:{name:{...text,maxLength:80},layout:{enum:PLAN_LAYOUTS},groupBy:{enum:['status','employee','priority']},filter:PLAN_FILTER_SCHEMA,sort:{enum:['nextAt','name','updatedAt','priority']},direction:{enum:['asc','desc']},options:PLAN_OPTIONS_SCHEMA}}
const object=(properties:Record<string,unknown>,required:string[]=[])=>({type:'object',additionalProperties:false,properties,required})
const range={from:{...text,description:'Inclusive ISO instant with offset'},to:{...text,description:'Exclusive ISO instant with offset; maximum range 93 days'}}
const outcomes={type:'array',items:{enum:PLAN_RUN_STATES},description:'Actual run outcomes; distinct from current schedule filter.states'}
export const PLAN_COMMANDS=[
 {name:'plan.schema',args:'',summary:'Discover all ten layouts, fields, policies, authorized targets and mutation APIs',inputSchema:object({})},
 {name:'plan.query',args:'[--filter JSON|@file --sort nextAt|name|updatedAt|priority --direction asc|desc --offset N --limit N]',summary:'Query canonical scheduler records as a filtered database; status and nextAt are computed',inputSchema:object({filter:PLAN_FILTER_SCHEMA,sort:{enum:['nextAt','name','updatedAt','priority']},direction:{enum:['asc','desc']},offset:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:500}})},
 {name:'plan.calendar',args:'--from ISO --to ISO [--timezone IANA --filter JSON|@file --limit N]',summary:'Return bounded future occurrences and recorded runs in a maximum 93-day range',inputSchema:object({...range,timezone:text,filter:PLAN_FILTER_SCHEMA,limit:{type:'integer',minimum:1,maximum:2000}},['from','to'])},
 {name:'plan.timeline',args:'--from ISO --to ISO [--timezone IANA --filter JSON|@file --limit N]',summary:'Project forecast estimates and actual/ongoing run spans, including overlaps; no inferred duration from timeout',inputSchema:object({...range,timezone:text,filter:PLAN_FILTER_SCHEMA,limit:{type:'integer',minimum:1,maximum:2000}},['from','to'])},
 {name:'plan.analytics',args:'[--metric schedules|runs --group-by status|employee|team|priority --filter JSON --outcomes JSON --from ISO --to ISO]',summary:'Aggregate the complete authorized data set, never just the current UI page; explicitly distinguish schedules and retained runs',inputSchema:object({metric:{enum:['schedules','runs'],default:'schedules'},groupBy:{enum:['status','employee','team','priority'],default:'status'},filter:PLAN_FILTER_SCHEMA,outcomes,...range})},
 {name:'plan.feed',args:'[--filter JSON --outcomes JSON --from ISO --to ISO --before CURSOR --limit N]',summary:'Read actual retained execution activity with stable cursor pagination, including removed schedules when authorized',inputSchema:object({filter:PLAN_FILTER_SCHEMA,outcomes,...range,before:{...text,maxLength:512,description:'Opaque nextCursor returned by the preceding page'},limit:{type:'integer',minimum:1,maximum:100,default:30}})},
 {name:'plan.views',args:'',summary:'List built-in and caller-owned saved database views',inputSchema:object({})},
 {name:'plan.view-create',args:'--spec JSON|@file',summary:'Save any of ten database layouts with filters, sorting, grouping and presentation options',inputSchema:object({spec:PLAN_VIEW_SCHEMA},['spec'])},
 {name:'plan.view-update',args:'ID --patch JSON|@file [--expected-revision N]',summary:'Update an owned saved view without changing schedules; options are a complete replacement object',inputSchema:object({id,patch:{...PLAN_VIEW_SCHEMA,required:[]},expectedRevision:{type:'integer',minimum:1}},['id','patch'])},
 {name:'plan.view-delete',args:'ID [--expected-revision N]',summary:'Remove an owned saved view only; schedules and histories remain',inputSchema:object({id,expectedRevision:{type:'integer',minimum:1}},['id'])}
].map(command=>({...command,gui:'Plan database'}))
