import {ChannelPostTriggers} from './ChannelPostTriggers'
import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {api} from '../api'
import {Icon} from './Icon'
import {useDialogFocus} from '../office/useDialogFocus'
import {translate as t,useI18n,interfaceLocale} from '../i18n'
import {CONVERSATION_ROLE_LABELS,type ConversationPolicy,type ConversationNotice,type NoticeOccurrence,type NoticeSpec,type NoticeRule} from '../../../shared/conversation-controls'
import type {Store} from '../../../shared/types'
import '../styles/conversation-controls.css'

const when=(at:string|null,zone?:string)=>at?new Date(at).toLocaleString(interfaceLocale(),zone?{timeZone:zone}:undefined):'—'
const ruleLabel=(rule:NoticeRule)=>rule.kind==='once'?t('One-time notification'):rule.kind==='interval'?t('Every {0} minutes',[rule.everySeconds/60]):rule.days.length===7?t('Daily at {0}',[rule.time]):t('Weekly at {0}',[rule.time])
/** Conversation-only controls. No Plan editor, schedule API or Company rank is used here. */
export function ConversationControls({conversation,store,onClose,onChanged}:{conversation:string;store:Store;onClose:()=>void;onChanged?:()=>void}){
 useI18n();useDialogFocus('.conversation-controls-dialog',true)
 const [policy,setPolicy]=useState<ConversationPolicy>(),[notices,setNotices]=useState<ConversationNotice[]>([]),[history,setHistory]=useState<NoticeOccurrence[]>([]),[tab,setTab]=useState<'members'|'notifications'|'post-count'>('members'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState<ConversationNotice|'new'|null>(null),[confirm,setConfirm]=useState<{label:string;action:()=>Promise<unknown>}|null>(null),[duration,setDuration]=useState('0'),[selectedAdmin,setSelectedAdmin]=useState(''),[offset,setOffset]=useState(0),[total,setTotal]=useState(0)
 const active=useRef(true),inFlight=useRef(false),dirty=useRef(false),[discard,setDiscard]=useState(false),[draftEpoch,setDraftEpoch]=useState(0)
 const load=async()=>{const p=await api.call<ConversationPolicy>('conversation.policy',{conversation});if(!active.current)return;setPolicy(p);if(p.allowedActions.includes('notices')){const [list,runs]=await Promise.all([api.call<{rows:ConversationNotice[];total:number}>('conversation.notice-list',{conversation,offset,limit:20}),api.call<{rows:NoticeOccurrence[]}>('conversation.notice-history',{conversation,limit:20})]);if(active.current){setNotices(list.rows);setTotal(list.total);setHistory(runs.rows)}}}
 const run=async(work:()=>Promise<unknown>)=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await work();onChanged?.();await load()}catch(cause){if(active.current)setError((cause as Error).message)}finally{inFlight.current=false;if(active.current)setBusy(false)}}
 useEffect(()=>{active.current=true;let timer:ReturnType<typeof setTimeout>|undefined;void load().catch(cause=>active.current&&setError(cause.message));const off=api.onEvent(event=>{if(event.channel==='conversation:controls'&&event.payload?.conversation===conversation&&!timer)timer=setTimeout(()=>{timer=undefined;if(!inFlight.current)void load().catch(cause=>active.current&&setError(cause.message))},80)});return()=>{active.current=false;off();clearTimeout(timer)}},[conversation,offset])
 useEffect(()=>{const deadlines=Object.values(policy?.mutes??{}).filter((value):value is number=>typeof value==='number'&&value>Date.now());if(!deadlines.length)return;const timer=setTimeout(()=>void load().catch(()=>{}),Math.min(2147483647,Math.min(...deadlines)-Date.now()+50));return()=>clearTimeout(timer)},[policy])
 const close=()=>{if(busy)return;if(dirty.current){setDiscard(true);return}if(editing){setEditing(null);return}onClose()}
 const mutable=policy?.allowedActions.includes('roles')??false,mayNotify=policy?.allowedActions.includes('notices')??false
 const moderate=(member:string,muted:boolean)=>run(()=>api.call('conversation.mute',{conversation,member,muted,expectedRevision:policy!.revision,...(muted&&+duration?{durationSeconds:+duration}:{})}))
 const role=(employee:string,value:string)=>{const work=()=>api.call('conversation.role',{conversation,employee,role:value,expectedRevision:policy!.revision});if(value==='owner')setConfirm({label:t('Transfer ownership to this Agent? The current Owner becomes an Admin.'),action:work});else void run(work)}
 const allMuted=policy?.mutes.all===null||typeof policy?.mutes.all==='number'&&policy.mutes.all>Date.now()
 return createPortal(<div className="conversation-controls-overlay" onKeyDown={event=>{if(event.key==='Escape'&&!event.defaultPrevented&&!event.nativeEvent.isComposing){event.preventDefault();event.stopPropagation();if(confirm)setConfirm(null);else close()}}}>
  <div className="conversation-controls-backdrop" onClick={close}/><section className="conversation-controls-dialog" role="dialog" aria-modal="true" aria-label={t('Conversation administration')} aria-busy={busy}>
   <header><span className="conversation-control-mark"><Icon name="shield"/></span><div><h2>{t(editing==='new'?'New notification':editing?'Edit notification':'Conversation administration')}</h2><p>{policy?.name??t('Loading…')}</p></div><button type="button" aria-label={t(editing?'Back to notification list':'Close conversation administration')} disabled={busy} onClick={close}><Icon name={editing?'arrow-left':'close'}/></button></header>
   {error&&<div className="conversation-control-error" role="alert"><span>{t(error)}</span><button onClick={()=>void run(load)}>{t('Reload')}</button></div>}
   {discard&&<div className="conversation-control-confirm" role="alert"><p>{t('Discard unsaved changes?')}</p><button onClick={()=>setDiscard(false)}>{t('Keep editing')}</button><button onClick={()=>{dirty.current=false;setDiscard(false);setEditing(null);setDraftEpoch(value=>value+1)}}>{t('Discard changes')}</button></div>}
   {confirm&&<div className="conversation-control-confirm" role="alert"><p>{confirm.label}</p><button disabled={busy} onClick={()=>{const action=confirm.action;setConfirm(null);void run(action)}}>{t('Confirm')}</button><button onClick={()=>setConfirm(null)}>{t('Cancel')}</button></div>}
   {editing&&policy?<NoticeEditor key={editing==='new'?'new':editing.id} conversation={conversation} policy={policy} job={editing==='new'?undefined:editing} busy={busy} onDirty={value=>{dirty.current=value}} onCancel={close} onSave={async work=>{setBusy(true);inFlight.current=true;try{await work();dirty.current=false;setEditing(null);onChanged?.();await load()}finally{inFlight.current=false;setBusy(false)}}}/>:<>
    <nav className="conversation-control-tabs" aria-label={t('Conversation controls')}><button aria-pressed={tab==='members'} onClick={()=>dirty.current?setDiscard(true):setTab('members')}><Icon name="organization"/>{t('Members & roles')}</button><button aria-pressed={tab==='notifications'} onClick={()=>dirty.current?setDiscard(true):setTab('notifications')}><Icon name="bell"/>{t('Notifications')}</button>{policy?.kind==='channel'&&<button aria-pressed={tab==='post-count'} onClick={()=>dirty.current?setDiscard(true):setTab('post-count')}><Icon name="list-ordered"/>{t('Post counts')}</button>}</nav>
    <div className="conversation-control-body">
     {policy&&tab==='members'&&<>
      <p className="conversation-control-note">{t('Conversation roles are independent of Company roles. Owner and Admin can manage members, moderation and notifications.')}</p>
      {!policy.ownerId&&<p className="conversation-control-warning">{t('No active Owner. The user must explicitly appoint an Agent; Company rank does not assign ownership.')}</p>}
      <div className="conversation-moderation"><label><span>{t('Quiet notifications')}<small>{t('Keep notification messages in the conversation without showing an attention banner.')}</small></span><input type="checkbox" name="conversation-silent" disabled={!mutable||busy} checked={policy.silent} onChange={event=>void run(()=>api.call('conversation.silence',{conversation,silent:event.target.checked,expectedRevision:policy.revision}))}/></label><label><span>{t(policy.kind==='group'?'Mute Members':'Mute all publishers')}<small>{t(policy.kind==='group'?'Owner and Admin can still post. Members keep read access.':'Muted publishers keep read access and can manage this channel.')}</small></span><input type="checkbox" name="conversation-mute-all" disabled={!mutable||busy} checked={!!allMuted} onChange={event=>void moderate('all',event.target.checked)}/></label><label className="conversation-mute-duration"><span>{t('Mute duration')}</span><select aria-label={t('Mute duration')} value={duration} disabled={!mutable||busy} onChange={event=>setDuration(event.target.value)}><option value="0">{t('Until unmuted')}</option><option value="3600">{t('1 hour')}</option><option value="86400">{t('24 hours')}</option><option value="604800">{t('7 days')}</option></select></label></div>
      <div className="conversation-role-list">{policy.members.map(member=><div key={member.id} data-conversation-member={member.id}><span><strong>{member.name}</strong><small>{CONVERSATION_ROLE_LABELS[member.role]}{member.mutedUntil!==undefined?' · '+t('Muted'):''}</small></span><select aria-label={t('Conversation role for {0}',[member.name])} value={member.role} disabled={!mutable||busy||member.role==='owner'} onChange={event=>role(member.id,event.target.value)}><option value="member">Member</option><option value="admin">Admin</option>{(policy.allowedActions.includes('transfer-owner')||member.role==='owner')&&<option value="owner">Owner</option>}</select>{mutable&&member.role!=='owner'&&<button className="conversation-member-remove" disabled={busy} aria-label={t('Remove member {0}',[member.name])} onClick={()=>setConfirm({label:t('Remove this member? Published messages and their workspace files are kept.'),action:()=>api.call('conversation.member',{conversation,employee:member.id,action:'remove',expectedRevision:policy.revision})})}><Icon name="person-remove"/></button>}<button className="conversation-member-mute" disabled={!mutable||busy||member.role==='owner'&&policy.actorRole==='admin'} aria-label={t(member.mutedUntil!==undefined?'Unmute {0}':'Mute {0}',[member.name])} onClick={()=>void moderate(member.id,member.mutedUntil===undefined)}><Icon name={member.mutedUntil!==undefined?'unmute':'mute'}/><span>{t(member.mutedUntil!==undefined?'Unmute':'Mute')}</span></button></div>)}</div>
      {mutable&&<div className="conversation-add-admin"><select aria-label={t('Choose an Agent member')} value={selectedAdmin} onChange={event=>setSelectedAdmin(event.target.value)}><option value="">{t('Choose an Agent member')}</option>{store.sessions.filter(card=>!card.deleting&&!policy.members.some(member=>member.id===card.id)).map(card=><option key={card.id} value={card.id}>{card.title}</option>)}</select><button disabled={!selectedAdmin||busy} onClick={()=>void run(()=>api.call('conversation.member',{conversation,employee:selectedAdmin,action:'add',expectedRevision:policy.revision}))}>{t('Add member')}</button></div>}
      {policy.kind==='group'&&policy.allowedActions.includes('delete-group')&&<div className="conversation-danger-zone"><p>{t('Only the Owner can dissolve this group. Employees and their workspaces are kept.')}</p><button disabled={busy} onClick={()=>setConfirm({label:t('Dissolve this group? Published history and employee work are kept; future group notifications stop.'),action:async()=>{await api.call('chat.delete',{id:conversation.slice(6)});onClose()}})}>{t('Dissolve group')}</button></div>}
     </>}
     {policy&&tab==='post-count'&&<ChannelPostTriggers key={draftEpoch} policy={policy} onDirty={value=>{dirty.current=value}} onBusy={setBusy}/>}
     {policy&&tab==='notifications'&&<>
      <div className="conversation-notice-heading"><div><h3>{t('Conversation notifications')}</h3><p>{t('Saved text only. No Agent execution. Separate from Plan.')}</p></div><button className="primary" disabled={!mayNotify||busy||!policy.members.some(member=>member.role!=='member')} onClick={()=>{dirty.current=false;setEditing('new')}}><Icon name="add"/>{t('New notification')}</button></div>
      {!mayNotify?<p className="conversation-control-note">{t('Only this conversation’s Owner or Admin can configure notifications.')}</p>:<>
       {!notices.length&&<div className="conversation-notice-empty"><Icon name="bell"/><strong>{t('No scheduled notifications')}</strong><p>{t('Choose a time or repeat rule to post a saved announcement here.')}</p></div>}
       {notices.map(job=><article className="conversation-notice-card" key={job.id} data-conversation-notice={job.id}><button className="conversation-notice-open" onClick={()=>{dirty.current=false;setEditing(job)}}><span><strong>{job.name}</strong><small>{ruleLabel(job.rule)}{job.rule.kind==='weekly'?' · '+job.rule.timezone:''}</small><span className="conversation-notice-text">{job.text}</span><small>{t('Publisher')}: {policy.members.find(member=>member.id===job.publisherId)?.name??t('Removed Agent')} · {when(job.nextAt,job.rule.kind==='weekly'?job.rule.timezone:undefined)}</small></span><span className={'conversation-notice-state '+job.status}>{t(job.status)}</span></button>{job.disabledReason&&<p className="conversation-control-warning">{t(job.disabledReason)}</p>}<footer><button disabled={busy||job.status==='completed'} onClick={()=>void run(()=>api.call('conversation.notice-update',{conversation,id:job.id,patch:{enabled:!job.enabled},expectedRevision:job.revision}))}><Icon name={job.enabled?'debug-pause':'play'}/>{t(job.enabled?'Pause':'Resume')}</button><button disabled={busy} onClick={()=>setConfirm({label:t('Delete this notification? Already published messages are kept.'),action:()=>api.call('conversation.notice-delete',{conversation,id:job.id,expectedRevision:job.revision})})}><Icon name="trash"/>{t('Delete')}</button></footer></article>)}
       {(offset>0||offset+notices.length<total)&&<div className="conversation-notice-pagination"><button disabled={!offset||busy} onClick={()=>setOffset(Math.max(0,offset-20))}>{t('Previous')}</button><span>{offset+1}–{offset+notices.length} / {total}</span><button disabled={offset+notices.length>=total||busy} onClick={()=>setOffset(offset+20)}>{t('Next')}</button></div>}
       <details className="conversation-notice-history"><summary>{t('Notification history')}</summary>{history.length?history.map(item=><div key={item.id}><strong>{t(item.status)}</strong><time>{when(item.scheduledFor)}</time>{item.error&&<small>{t(item.error)}</small>}</div>):<p>{t('No notification deliveries yet.')}</p>}</details>
      </>}
     </>}
    </div>
   </>}
  </section>
 </div>,document.body)
}
const localTime=(value:string)=>{const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,19)}
function NoticeEditor({conversation,policy,job,busy,onDirty,onSave,onCancel}:{conversation:string;policy:ConversationPolicy;job?:ConversationNotice;busy:boolean;onDirty:(value:boolean)=>void;onSave:(work:()=>Promise<unknown>)=>Promise<void>;onCancel:()=>void}){
 const original=job?.rule,initialMode=original?.kind==='weekly'?(original.days.length===7?'daily':'weekly'):original?.kind??'once'
 const [name,setName]=useState(job?.name??''),[text,setText]=useState(job?.text??''),[publisher,setPublisher]=useState(job?.publisherId??policy.members.find(member=>member.role==='owner'||member.role==='admin')?.id??''),[mode,setMode]=useState(initialMode),[start,setStart]=useState(localTime(original?.kind==='once'?original.at:original?.kind==='interval'?original.anchor:new Date(Date.now()+3600000).toISOString())),[every,setEvery]=useState(original?.kind==='interval'?original.everySeconds/60:60),[time,setTime]=useState(original?.kind==='weekly'?original.time:'09:00'),[zone,setZone]=useState(original?.kind==='weekly'?original.timezone:Intl.DateTimeFormat().resolvedOptions().timeZone),[days,setDays]=useState(original?.kind==='weekly'?original.days:[1,2,3,4,5]),[enabled,setEnabled]=useState(job?.enabled??true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<string[]>([]),[requestId]=useState(()=>crypto.randomUUID())
 const dirty=()=>onDirty(true),disabled=busy||saving
 const rule=():NoticeRule=>mode==='once'?{kind:'once',at:new Date(start).toISOString()}:mode==='interval'?{kind:'interval',everySeconds:every*60,anchor:new Date(start).toISOString()}:{kind:'weekly',time,days:mode==='daily'?[1,2,3,4,5,6,7]:days,timezone:zone}
 const save=async()=>{if(disabled)return;setSaving(true);setError('');try{const spec:NoticeSpec={name:name.trim(),text:text.trim(),publisherId:publisher,rule:rule(),enabled};await onSave(()=>api.call(job?'conversation.notice-update':'conversation.notice-create',job?{conversation,id:job.id,expectedRevision:job.revision,patch:spec}:{conversation,spec,clientRequestId:requestId}))}catch(cause){setError((cause as Error).message)}finally{setSaving(false)}}
 return <form className="conversation-notice-editor" onChange={dirty} onSubmit={event=>{event.preventDefault();void save()}}>
  <div className="conversation-control-body"><p className="conversation-control-note">{t('Saved text only. No Agent execution. Separate from Plan.')}</p>
   <label>{t('Notification name')}<input name="notice-name" required maxLength={120} value={name} onChange={event=>setName(event.target.value)} disabled={disabled}/></label>
   <label>{t('Notification text')}<textarea name="notice-text" required maxLength={2000} rows={4} value={text} onChange={event=>setText(event.target.value)} disabled={disabled}/></label>
   <label>{t('Publisher')}<select name="notice-publisher" value={publisher} disabled={disabled} onChange={event=>setPublisher(event.target.value)}>{!policy.members.some(member=>member.id===publisher&&member.role!=='member')&&<option value={publisher} disabled>{t('Publisher is no longer an active Admin')}</option>}{policy.members.filter(member=>member.role==='owner'||member.role==='admin').map(member=><option key={member.id} value={member.id} disabled={member.mutedUntil!==undefined}>{member.name} · {CONVERSATION_ROLE_LABELS[member.role]}{member.mutedUntil!==undefined?' · '+t('Muted'):''}</option>)}</select></label>
   <label>{t('Notification timing')}<select name="notice-mode" value={mode} disabled={disabled} onChange={event=>{setMode(event.target.value as typeof mode);setPreview([])}}><option value="once">{t('One time')}</option><option value="interval">{t('Repeat at an interval')}</option><option value="daily">{t('Daily')}</option><option value="weekly">{t('Weekly')}</option></select></label>
   {(mode==='once'||mode==='interval')&&<label>{t('Local date and time')}<input type="datetime-local" step="1" name="notice-start" required value={start} disabled={disabled} onChange={event=>{setStart(event.target.value);setPreview([])}}/><small>{Intl.DateTimeFormat().resolvedOptions().timeZone}</small></label>}
   {mode==='interval'&&<label>{t('Repeat every (minutes)')}<input type="number" name="notice-every" min={1} max={525600} step={1} required value={every} disabled={disabled} onChange={event=>{setEvery(+event.target.value);setPreview([])}}/></label>}
   {(mode==='daily'||mode==='weekly')&&<div className="conversation-notice-time"><label>{t('Time')}<input type="time" name="notice-time" required value={time} disabled={disabled} onChange={event=>{setTime(event.target.value);setPreview([])}}/></label><label>{t('Timezone')}<input name="notice-zone" value={zone} required disabled={disabled} onChange={event=>{setZone(event.target.value);setPreview([])}}/></label></div>}
   {mode==='weekly'&&<fieldset className="conversation-notice-days"><legend>{t('Repeat on')}</legend>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((label,index)=><label key={label}><input type="checkbox" checked={days.includes(index+1)} disabled={disabled} onChange={event=>{setDays(event.target.checked?[...days,index+1].sort():days.filter(day=>day!==index+1));setPreview([])}}/>{t(label)}</label>)}</fieldset>}
   <label className="conversation-notice-enabled"><span>{t('Notification enabled')}</span><input name="notice-enabled" type="checkbox" checked={enabled} disabled={disabled} onChange={event=>setEnabled(event.target.checked)}/></label>
   <button type="button" className="conversation-preview-button" disabled={disabled} onClick={async()=>{setError('');try{const result=await api.call<{occurrences:string[]}>('conversation.notice-preview',{conversation,rule:rule()});setPreview(result.occurrences)}catch(cause){setError((cause as Error).message)}}}><Icon name="calendar"/>{t('Preview notification times')}</button>
   {!!preview.length&&<div className="conversation-notice-preview" role="status">{preview.map(at=><time key={at} dateTime={at} title={mode==='daily'||mode==='weekly'?zone:undefined}>{when(at,mode==='daily'||mode==='weekly'?zone:undefined)}</time>)}</div>}
   {error&&<p role="alert" className="conversation-control-error">{t(error)}</p>}
  </div><footer><button type="button" disabled={disabled} onClick={onCancel}>{t('Cancel')}</button><button className="primary" disabled={disabled||!publisher||!text.trim()||!name.trim()}>{t(saving?'Saving…':job?'Save notification':'Create notification')}</button></footer>
 </form>
}
