import {CONVERSATION_ROLE_LABELS} from '../../../shared/conversation-controls'
import {useEffect,useId,useRef,useState} from 'react'
import type {Store,StoredSession} from '../../../shared/types'
import type {EmployeeProfileData,ProfileMembership,ProfilePlan} from '../../../shared/employee-profile'
import type {ScheduledJob} from '../../../shared/scheduler'
import {rolePolicy} from '../../../shared/roles'
import {ENGINE_DEFINITIONS} from '../../../shared/engines'
import {affectsMembers} from '../../../shared/store-changes'
import {api} from '../api'
import {createRefreshQueue,retainEqual} from '../snapshot'
import {translate as uiText,useI18n,interfaceLocale} from '../i18n'
import {EmployeeForm} from '../office/OfficeForms'
import {EmployeePortrait} from './EmployeePortrait'
import {EngineMark} from './EngineMark'
import {ConversationWorkspace} from './ConversationWorkspace'
import {PlanEditor} from './PlanEditor'
import {scheduleLabel} from './PlanView'
import {useMessenger} from './useMessenger'
import {BackButton} from './BackButton'
import {Icon} from './Icon'

type ProfileView='company'|'messages'|'plan'
type Section=ProfileView|'edit'|'appearance'
const tabs=[['company','Company','organization'],['messages','Messages','comment-discussion'],['plan','Plan','calendar']] as const
const date=(value:string|null,zone?:string)=>value?new Date(value).toLocaleString(interfaceLocale(),{timeZone:zone,month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):uiText('No upcoming run')

/** The same read-only profile in Company and Messages. No engine starts on discovery. */
export function EmployeeProfile({employee,store,onBack,onWorkspace,backLabel='Back to conversation'}:{employee:StoredSession;store:Store;onBack:()=>void;onWorkspace:()=>void;backLabel?:string}){
 useI18n()
 const messenger=useMessenger(),[data,setData]=useState<EmployeeProfileData|null>(null),[error,setError]=useState(''),[section,setSection]=useState<Section>('company'),[offset,setOffset]=useState(0),[reload,setReload]=useState(0),[loading,setLoading]=useState(true)
 const [shared,setShared]=useState<{conversation:string;folder:string}|null>(null),[job,setJob]=useState<ScheduledJob|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[discard,setDiscard]=useState(false)
 const discardAction=useRef<(()=>void)|null>(null),surface=useRef<HTMLDivElement>(null),pending=useRef(0),refresh=()=>setReload(n=>n+1)
 const edit=section==='edit'||section==='appearance',tabId=useId(),returnSection=useRef<ProfileView>('company')
 useEffect(()=>{
  let alive=true,timer:ReturnType<typeof setTimeout>|undefined
  const load=createRefreshQueue(async()=>{try{const result=await api.call<EmployeeProfileData>('card.profile',{id:employee.id,offset,limit:12});if(alive){setData(previous=>retainEqual(previous,result));setError('')}}catch(cause){if(alive){setData(null);setError((cause as Error).message)}}finally{if(alive)setLoading(false)}})
  setLoading(true);void load()
  const off=api.onEvent(event=>{if((event.channel==='store:changed'?affectsMembers(event.payload):['chat:changed','schedule:changed','schedule:run'].includes(event.channel)||event.channel==='channel:changed'&&!['reads','deliveries'].includes(event.payload?.kind))&&!timer)timer=setTimeout(()=>{timer=undefined;void load()},100)})
  return()=>{alive=false;off();clearTimeout(timer)}
 },[employee.id,offset,reload])
 useEffect(()=>()=>{pending.current++},[employee.id])
 useEffect(()=>{if(data&&!data.plans.error&&offset>0&&offset>=data.plans.total)setOffset(Math.max(0,Math.floor((data.plans.total-1)/12)*12))},[data,offset])
 const leaveEditor=()=>{setDirty(false);setSaving(false);setDiscard(false);if(job){setJob(null);refresh()}else setSection(returnSection.current)}
 const guardLeave=(action:()=>void)=>{if(saving)return;if(dirty){discardAction.current=action;setDiscard(true)}else action()}
 const back=()=>guardLeave(edit||job?leaveEditor:onBack)
 const configure=()=>guardLeave(()=>void api.call('view.open',{kind:'settings'}).catch(cause=>setError(cause.message)))
 const choose=(next:Section)=>{pending.current++;if(!edit)returnSection.current=section;if(next!=='plan'&&next!=='edit'&&next!=='appearance')setOffset(0);setSection(next);surface.current?.querySelector('.profile-scroll')?.scrollTo({top:0});setError('')}
 const openConversation=(membership?:ProfileMembership)=>{pending.current++;void api.call('view.open',membership?{kind:'messages',...(membership.kind==='group'?{chatId:membership.id}:{channelId:membership.id})}:{kind:'messages',employee:employee.id}).catch(cause=>setError(cause.message))}
 const openJob=async(id:string)=>{const sequence=++pending.current;try{const found=await api.call<ScheduledJob>('schedule.get',{id});if(sequence===pending.current){setDirty(false);setJob(found)}}catch(cause){if(sequence===pending.current)setError((cause as Error).message)}}
 const openShared=(member:ProfileMembership,own=true)=>{if(member.workspace)setShared({conversation:member.conversation,folder:own?member.workspace.memberDirectory??'':''})}
 const person=data?.employee??employee
 const membershipRow=(member:ProfileMembership)=><button type="button" key={member.conversation} className="profile-row" data-profile-membership={member.conversation} onClick={()=>openConversation(member)}><span className={'profile-row-icon '+member.kind}><Icon name={member.kind==='group'?'organization':'radio-tower'}/></span><span className="profile-row-copy"><strong>{member.name}</strong><small>{uiText(member.kind==='group'?'Group':'Channel')} · {CONVERSATION_ROLE_LABELS[member.role==='administrator'?'admin':member.role]}{member.muted?' · '+uiText('Muted'):''}</small></span><Icon name="chevron-right"/></button>
 const planRow=(plan:ProfilePlan)=>{const zone=plan.rule.kind==='weekly'||plan.rule.kind==='monthly'?plan.rule.timezone:undefined;return <button type="button" className="profile-row profile-plan-row" key={plan.id} data-profile-plan={plan.id} onClick={()=>void openJob(plan.id)}><span className="profile-row-icon plan"><Icon name={plan.rule.kind==='once'?'calendar':plan.rule.kind==='event'?'radio-tower':'sync'}/></span><span className="profile-row-copy"><strong>{plan.name}</strong><small>{scheduleLabel(plan)}{zone?' · '+zone:''}</small><time>{plan.rule.kind==='event'&&plan.status==='scheduled'?uiText('Waiting for event'):date(plan.nextAt,zone)}</time></span><span className={'profile-state state-'+plan.status}>{uiText(plan.status[0].toUpperCase()+plan.status.slice(1))}</span><Icon name="chevron-right"/></button>}
 return <div className="employee-profile-page" ref={surface} data-profile-employee={employee.id} data-profile-view={section} onKeyDown={event=>{if(event.key==='Escape'&&!event.defaultPrevented&&!event.nativeEvent.isComposing&&!shared){event.preventDefault();event.stopPropagation();back()}}}>
  <header className="employee-profile-header"><BackButton disabled={saving} label={edit||job?'Back to employee profile':backLabel} onClick={back}/><strong>{uiText(job?'Edit schedule':edit?'Edit employee':'Employee details')}</strong><button type="button" className="profile-icon-button" aria-label={uiText('Refresh employee profile')} title={uiText('Refresh employee profile')} disabled={loading||saving} onClick={refresh}><Icon name="refresh"/></button></header>
  {error&&<div className="profile-error" role="alert"><Icon name="info"/><span>{error}</span><button onClick={refresh}>{uiText('Retry')}</button></div>}
  {discard&&<div className="profile-discard" role="alert"><p>{uiText(job?'Discard unsaved schedule changes?':'Discard unsaved profile changes?')}</p><button onClick={()=>setDiscard(false)}>{uiText('Keep editing')}</button><button onClick={()=>{setDiscard(false);setDirty(false);const action=discardAction.current;discardAction.current=null;action?.()}}>{uiText('Discard changes')}</button></div>}
  {job?<div className="profile-plan-editor"><PlanEditor key={job.id+":"+job.revision} inline job={job} store={store} timezone={Intl.DateTimeFormat().resolvedOptions().timeZone} onClose={back} onSaved={leaveEditor} onDirtyChange={setDirty} onSavingChange={setSaving} onReload={setJob} onConversation={id=>void api.call('view.open',{kind:'messages',employee:id})}/></div>:edit?<div className="profile-scroll profile-edit"><EmployeeForm key={section} employee={employee} groups={store.groups} roots={store.teamRoots} settings={store.teamSettings} appearanceInitiallyOpen={section==='appearance'} onDirtyChange={setDirty} onSavingChange={setSaving} onConfigure={configure} onSave={async fields=>{await api.call('card.update',{id:employee.id,patch:{title:fields.title,avatar:fields.avatar,color:fields.color,accessory:fields.accessory,role:fields.role}});setDirty(false);setSection(returnSection.current);refresh();return true}} onBound={()=>{setSection(returnSection.current);refresh()}}/></div>:<>
   <div className="profile-hero"><button type="button" className="profile-portrait" aria-label={uiText('Change character')} disabled={!data?.canEditProfile} onClick={()=>choose('appearance')}><EmployeePortrait avatar={person.avatar} color={person.color} large/><span className="profile-portrait-edit"><Icon name="edit"/></span></button><div className="profile-hero-copy"><span className="profile-eyebrow">{uiText('YOUR TEAMMATE')}</span><h1>{person.title}</h1><p>{person.role||uiText('Your AI teammate')}</p><div className="profile-badges"><span title={uiText('Read-only in employee details')}><Icon name="lock"/>{uiText(rolePolicy(person.managementRole).label)}</span><span title={uiText('Engine fixed at creation')}><EngineMark engine={person.engine} size={16}/>{ENGINE_DEFINITIONS[person.engine].label}</span></div></div></div>
   <div className="profile-quick-actions"><button type="button" onClick={()=>openConversation()}><Icon name="comment-discussion"/>{uiText('Message')}</button><button type="button" disabled={!data?.canEditProfile} onClick={()=>choose('edit')}><Icon name="edit"/>{uiText('Edit profile')}</button></div>
   <nav className="profile-tabs" role="tablist" aria-label={uiText('Employee profile sections')}>{tabs.map(([id,label,icon],index)=><button type="button" role="tab" key={id} id={tabId+'-'+id} data-profile-tab={id} aria-label={uiText(label)} aria-selected={section===id} aria-controls={tabId+'-panel'} tabIndex={section===id?0:-1} onClick={()=>choose(id)} onKeyDown={event=>{if(event.nativeEvent.isComposing||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowLeft'?-1:1)+tabs.length)%tabs.length;choose(tabs[next][0]);event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role=tab]')[next]?.focus()}}><Icon name={icon}/><span>{uiText(label)}</span>{id==='messages'&&!!data?.memberships.length&&<b>{data.memberships.length}</b>}{id==='plan'&&!!data?.plans.total&&<b>{data.plans.total}</b>}</button>)}</nav>
   <div className="profile-scroll" role="tabpanel" id={tabId+'-panel'} aria-labelledby={tabId+'-'+section} tabIndex={0} aria-busy={loading}>
    {!data&&!error&&<Empty icon="loading" text="Loading employee profile…"/>}
    {data&&<>
     {section==='company'&&<>
      <section className="profile-section"><header><h2>{uiText('Company identity')}</h2><span>{uiText(data.company.location==='remote'?'Cloud workspace':'Local workspace')}</span></header><div className="profile-card"><div className="profile-company-identity"><span className="profile-row-icon company"><Icon name="organization"/></span><div><strong>{data.company.team||uiText('Unassigned')}</strong><small>{uiText(rolePolicy(person.managementRole).label)} · {uiText(data.company.mode==='work'?'Plugin workspace':data.company.mode==='cloud'?'Cloud Team':'Project Team')}</small></div></div><p className="profile-role-description">{uiText(rolePolicy(person.managementRole).description)}</p><dl className="profile-facts"><div><dt>{uiText('Role')}</dt><dd>{uiText(rolePolicy(person.managementRole).label)}<Icon name="lock"/></dd></div><div><dt>{uiText('Coding agent')}</dt><dd>{ENGINE_DEFINITIONS[person.engine].label}<Icon name="lock"/></dd></div><div><dt>{uiText('Model')}</dt><dd>{person.model||uiText('Configured default')}</dd></div><div><dt>{uiText('Execution location')}</dt><dd>{uiText(person.kind==='cloud-native-worker'?'Cloud Native Worker':'Core host')}{data.company.host&&<small>{data.company.host}</small>}</dd></div></dl></div></section>
      <section className="profile-section"><header><h2>{uiText('Company workspace')}</h2></header><div className="profile-card"><button type="button" className="profile-row" onClick={onWorkspace}><span className="profile-row-icon company"><Icon name="files"/></span><span className="profile-row-copy"><strong>{uiText('Personal workspace')}</strong><code>{data.company.workspace}</code><small>{uiText(data.company.location==='remote'?'On the employee’s cloud host':'On the Core host')}</small></span><Icon name="chevron-right"/></button>{data.company.teamRoot&&<div className="profile-folder-note"><small>{uiText('Team directory')}</small><code>{data.company.teamRoot}</code></div>}</div></section>
     </>}
     {section==='messages'&&<>
      <section className="profile-section"><header><h2>{uiText('Conversation identities')}</h2></header><p className="profile-section-note">{uiText('Company roles and conversation membership are independent.')}</p><div className="profile-card"><button type="button" className="profile-row profile-private-chat" onClick={()=>openConversation()}><span className="profile-row-icon messages"><Icon name="comment-discussion"/></span><span className="profile-row-copy"><strong>{uiText('Private conversation')}</strong><small>{person.title} · {uiText('Direct messages with you')}</small></span><Icon name="chevron-right"/></button></div></section>
      <section className="profile-section"><header><h2>{uiText('Groups and channels')}</h2><span>{uiText('{0} groups · {1} channels',[data.memberships.filter(member=>member.kind==='group').length,data.memberships.filter(member=>member.kind==='channel').length])}</span></header><div className="profile-card">{data.memberships.length?data.memberships.map(membershipRow):<Empty icon="organization" text="No group or channel memberships"/>}</div></section>
      {!!data.memberships.length&&<section className="profile-section"><header><h2>{uiText('Conversation workspaces')}</h2></header><p className="profile-section-note">{uiText('You can edit user originals. Employees read shared files and write only in their own named folder through the API.')}</p>{data.memberships.map(member=><article className="profile-card profile-folder-card" key={member.conversation}><header><span className={'profile-row-icon '+member.kind}><Icon name={member.kind==='group'?'organization':'radio-tower'}/></span><div><h3>{member.name}</h3><small>{CONVERSATION_ROLE_LABELS[member.role==='administrator'?'admin':member.role]}</small></div></header>{member.workspace?<><button type="button" className="profile-row" disabled={!member.canOpenWorkspace} onClick={()=>openShared(member,false)}><Icon name="file-media"/><span className="profile-row-copy"><strong>{uiText('User originals')}</strong><code>{member.workspace.root}</code><small>{uiText('Read-only for employees · Editable by you')}</small></span><Icon name="chevron-right"/></button><button type="button" className="profile-row profile-member-folder" disabled={!member.canOpenWorkspace} onClick={()=>openShared(member)}><Icon name="folder"/><span className="profile-row-copy"><strong>{member.workspace.memberDirectory}</strong><code>{member.workspace.memberPath}</code><small>{uiText('Employee work folder · First-level subfolder')}</small></span><Icon name="chevron-right"/></button></>:<p className="profile-error">{member.workspaceError}</p>}</article>)}</section>}
      {messenger&&<section className="profile-section"><header><h2>{uiText('Shared in this private chat')}</h2></header><div className="profile-content-links">{[['media','Media','file-media'],['links','Links','link'],['saved','Saved','bookmark'],['pinned','Pinned','pinned']].map(([filter,label,icon])=><button key={filter} onClick={()=>{messenger.setLibrary({conversation:'employee:'+employee.id,filter});onBack()}}><Icon name={icon}/>{uiText(label)}</button>)}</div></section>}
     </>}
     {section==='plan'&&<section className="profile-section"><div className="profile-view-role"><span className="profile-row-icon plan"><Icon name="calendar"/></span><div><strong>{uiText('Task assignee')}</strong><small>{person.title} · {uiText(rolePolicy(person.managementRole).scope==='self'?'Can schedule own work':rolePolicy(person.managementRole).scope==='team'?'Can schedule own work and Team employees':'Can schedule own work and lower-ranked employees')}</small></div></div><header><h2>{uiText('Scheduled work')}</h2><span>{data.plans.total}</span></header><div className="profile-plan-counts">{(['scheduled','running','paused','attention','completed'] as const).map(state=><span key={state}><b>{data.plans.counts[state]}</b>{uiText(state[0].toUpperCase()+state.slice(1))}</span>)}</div><div className="profile-card">{data.plans.error?<Empty icon="info" text={data.plans.error}/>:data.plans.rows.length?data.plans.rows.map(planRow):<Empty icon="calendar" text="No schedules for this employee"/>}</div>{(offset>0||data.plans.hasMore)&&<div className="profile-pagination"><button disabled={!offset||loading} onClick={()=>setOffset(n=>Math.max(0,n-12))}>{uiText('Previous')}</button><span>{offset+1}–{offset+data.plans.rows.length} / {data.plans.total}</span><button disabled={!data.plans.hasMore||loading} onClick={()=>setOffset(n=>n+12)}>{uiText('Next')}</button></div>}<p className="profile-footnote">{uiText(data.plans.eventTriggersSupported?'Scheduled, recurring and event-driven work share the same Plan records.':'One-time and recurring tasks use Plan. This Core does not advertise event triggers.')}</p></section>}
    </>}
   </div>
  </>}
  {shared&&<ConversationWorkspace conversation={shared.conversation} initialFolder={shared.folder} backLabel="Back to employee profile" onClose={()=>setShared(null)}/>}
 </div>
}
function Empty({icon,text}:{icon:string;text:string}){return <div className="profile-empty"><Icon name={icon}/><p>{uiText(text)}</p></div>}
