import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react'
import type {EngineEntry} from '../../../../../Contract/engine'
import {api} from '../api'
import '../styles/engine-library.css'
import brand from '../../../resources/icon.png'

const accents=['#6774dd','#b7669c','#4b9694','#c08048']
const MIME='application/x-aexus-engine'
function Illustration({index=0}:{index?:number}){
 const variant=index%4
 return <svg className="el-art" viewBox="0 0 300 188" fill="none" aria-hidden="true">
  <path d="M0 148 150 64l150 84M0 172 150 88l150 84M42 188 192 104M0 120 122 188M258 188 108 104M300 120 178 188" stroke="currentColor" opacity=".12"/>
  {variant===0?<><ellipse cx="150" cy="92" rx="91" ry="27" transform="rotate(-30 150 92)" stroke="currentColor" opacity=".32"/><ellipse cx="150" cy="92" rx="91" ry="27" transform="rotate(30 150 92)" stroke="currentColor" opacity=".32"/><circle cx="150" cy="92" r="46" fill="currentColor" opacity=".09"/><circle cx="150" cy="92" r="31" fill="currentColor" opacity=".17"/><circle cx="150" cy="92" r="19" stroke="currentColor" strokeWidth="2"/><path d="m163 105 19 19M138 94l8-10 9 16 10-13" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/><circle cx="76" cy="59" r="5" fill="currentColor"/><circle cx="224" cy="128" r="4" fill="currentColor"/></>:variant===1?<><rect x="75" y="40" width="146" height="110" rx="13" transform="rotate(-9 75 40)" fill="currentColor" opacity=".1"/><rect x="87" y="39" width="135" height="107" rx="12" transform="rotate(5 87 39)" fill="var(--el-paper)" stroke="currentColor" opacity=".65"/><rect x="108" y="59" width="42" height="34" rx="5" fill="currentColor" opacity=".2"/><path d="M164 66h34M164 79h23M108 109h91M108 122h58" stroke="currentColor" strokeWidth="4" strokeLinecap="round" opacity=".48"/><circle cx="223" cy="141" r="18" fill="currentColor"/><path d="m216 141 5 5 9-11" stroke="var(--el-paper)" strokeWidth="2.5" strokeLinecap="round"/></>:variant===2?<><path d="m150 28 70 39v80l-70 39-70-39V67z" fill="currentColor" opacity=".07"/><path d="m150 39 61 34v67l-61 34-61-34V73zM89 73l61 34 61-34M150 107v67" stroke="currentColor" strokeWidth="1.5" opacity=".6"/><path d="m150 65 36 20v39l-36 20-36-20V85z" fill="var(--el-paper)" stroke="currentColor"/><path d="m137 105 9 9 19-20" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><circle cx="79" cy="152" r="5" fill="currentColor" opacity=".6"/><circle cx="225" cy="60" r="4" fill="currentColor" opacity=".6"/></>:<><rect x="82" y="32" width="132" height="132" rx="17" transform="rotate(-5 82 32)" fill="currentColor" opacity=".1"/><rect x="91" y="39" width="121" height="118" rx="13" fill="var(--el-paper)" stroke="currentColor" opacity=".75"/><circle cx="150" cy="77" r="15" fill="currentColor" opacity=".2"/><path d="M124 111c0-18 52-18 52 0M116 134h70" stroke="currentColor" strokeWidth="4" strokeLinecap="round" opacity=".55"/><path d="m224 61 4-12 4 12 12 4-12 4-4 12-4-12-12-4z" fill="currentColor" opacity=".65"/></>}
 </svg>
}
export function EngineLibrary({loading=false,error:outerError='',onLoad}:{loading?:boolean;error?:string;onLoad:(id:string)=>Promise<void>}){
 const [engines,setEngines]=useState<EngineEntry[]>([]),[catalogError,setCatalogError]=useState(''),[catalogLoading,setCatalogLoading]=useState(true),[query,setQuery]=useState(''),[selected,setSelected]=useState<string|null>(null),[dragging,setDragging]=useState<string|null>(null),[over,setOver]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[ghost,setGhost]=useState<{x:number;y:number;id:string}|null>(null)
 const dock=useRef<HTMLDivElement>(null),touch=useRef<{id:string;x:number;y:number;active:boolean}|null>(null),alive=useRef(true),loadingLock=useRef(false)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 useEffect(()=>{let current=true;setCatalogLoading(true);void api.call<{engines:EngineEntry[];errors:{directory:string;error:string}[]}>('contract.engines').then(value=>{if(current){setEngines(value.engines);setSelected(id=>value.engines.some(e=>e.id===id)?id:null);setCatalogError(value.errors.map(e=>e.directory+': '+e.error).join('\n'))}}).catch(e=>{if(current)setCatalogError(e.message)}).finally(()=>{if(current)setCatalogLoading(false)});return()=>{current=false}},[revision])
 const engine=engines.find(e=>e.id===(dragging??selected)),index=Math.max(0,engines.findIndex(e=>e.id===engine?.id)),filtered=engines.filter(e=>(e.name+' '+e.description+' '+e.id).toLowerCase().includes(query.toLowerCase().trim()))
 const load=async(id:string)=>{if(loadingLock.current||loading||!engines.some(e=>e.id===id))return;loadingLock.current=true;setBusy(id);setSelected(id);setError('');setDragging(null);setOver(false);setGhost(null);try{await onLoad(id)}catch(e){if(alive.current)setError((e as Error).message)}finally{loadingLock.current=false;if(alive.current)setBusy(null)}}
 const touchDown=(event:PointerEvent,id:string)=>{if(event.pointerType==='mouse'||busy)return;touch.current={id,x:event.clientX,y:event.clientY,active:false};event.currentTarget.setPointerCapture(event.pointerId)}
 const touchMove=(event:PointerEvent)=>{const value=touch.current;if(!value)return;if(!value.active&&Math.hypot(event.clientX-value.x,event.clientY-value.y)<10)return;value.active=true;setDragging(value.id);setGhost({x:event.clientX,y:event.clientY,id:value.id});const b=dock.current?.getBoundingClientRect();setOver(!!b&&event.clientX>=b.left&&event.clientX<=b.right&&event.clientY>=b.top&&event.clientY<=b.bottom)}
 const touchEnd=(event:PointerEvent)=>{const value=touch.current;touch.current=null;if(!value?.active)return;event.preventDefault();const b=dock.current?.getBoundingClientRect(),inside=!!b&&event.clientX>=b.left&&event.clientX<=b.right&&event.clientY>=b.top&&event.clientY<=b.bottom;setGhost(null);setDragging(null);setOver(false);if(inside)void load(value.id)}
 return <main className="engine-library" data-engine-loaded="false" style={{'--el-accent':accents[index%4]} as CSSProperties}>
  <div className="el-background" aria-hidden="true"><i/><i/><div/></div>
  <header className="el-header"><div className="el-brand"><img src={brand} alt=""/><span>Aexus</span><span className="el-brand-divider"/><small>Engine library</small></div><span className="el-session"><i/> No engine loaded</span></header>
  <div className="el-body"><section className="el-intro"><span className="el-eyebrow">A WORKSPACE FOR EVERY AMBITION</span><h1>Choose your engine.<br/><span>Enter your workspace.</span></h1><p>A focused application. Its own people, conversations and plans.<br/>Everything stays out of view until you load an engine.</p></section>
  {(error||outerError)&&<div className="el-error" role="alert">{error||outerError}<button onClick={()=>setError('')} aria-label="Dismiss load error">×</button></div>}
  <div className="el-content"><section className="el-collection" aria-label="Installed engines"><div className="el-collection-heading"><div><h2>Your engines <span>{engines.length}</span></h2><p>Select a card, or drag it into the launch dock.</p></div><button className="el-refresh" onClick={()=>setRevision(r=>r+1)} disabled={!!busy||catalogLoading} aria-label="Refresh engine library">↻</button></div>
  <label className="el-search"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10" cy="10" r="6" stroke="currentColor" strokeWidth="1.7"/><path d="m15 15 5 5" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></svg><input type="search" aria-label="Search engines" placeholder="Find an engine…" value={query} onChange={e=>setQuery(e.target.value)}/><span>LIBRARY</span></label>
  {catalogLoading&&!engines.length?<div className="el-placeholder" role="status">Reading installed engines…</div>:<div className="el-cards">{filtered.map(item=>{const i=engines.indexOf(item);return <button key={item.id} className="el-card" style={{'--card-accent':accents[i%4]} as CSSProperties} aria-label={'Select '+item.name} aria-pressed={selected===item.id} data-engine-id={item.id} disabled={!!busy||loading} draggable onDragStart={event=>{event.dataTransfer.setData(MIME,item.id);event.dataTransfer.effectAllowed='copy';setDragging(item.id);setSelected(item.id)}} onDragEnd={()=>{setDragging(null);setOver(false)}} onClick={()=>{if(!touch.current?.active)setSelected(item.id)}}><div className="el-card-cover" onPointerDown={e=>touchDown(e,item.id)} onPointerMove={touchMove} onPointerUp={touchEnd} onPointerCancel={()=>{touch.current=null;setGhost(null);setDragging(null);setOver(false)}}><span className="el-card-number">{String(i+1).padStart(2,'0')}</span><Illustration index={i}/><span className="el-drag-hint">⠿ DRAG TO LOAD</span>{selected===item.id&&<span className="el-selected" aria-hidden="true">✓</span>}</div><div className="el-card-copy"><div><h3>{item.name}</h3><span>↗</span></div><p>{item.description}</p><footer><span>{item.id}</span><span>v{item.version}</span></footer></div></button>})}</div>}
  {!catalogLoading&&!filtered.length&&<div className="el-placeholder"><h3>{engines.length?'No matching engine':'Your library is ready for an engine'}</h3><p>{engines.length?'Try another name or clear the search.':'Add an Engine implementation and rebuild Aexus to make it available here.'}</p>{query&&<button onClick={()=>setQuery('')}>Clear search</button>}</div>}
  {catalogError&&<details className="el-catalog-warning"><summary>Some engines could not be loaded</summary><p role="alert">{catalogError}</p></details>}</section>
  <aside className="el-dock-column"><div ref={dock} className={'el-dock'+(over?' is-over':'')+(busy?' is-loading':'')} data-testid="engine-load-dock" onDragOver={event=>{if(Array.from(event.dataTransfer.types).includes(MIME)){event.preventDefault();event.dataTransfer.dropEffect='copy';setOver(true)}}} onDragLeave={event=>{if(!(event.relatedTarget instanceof Node)||!event.currentTarget.contains(event.relatedTarget))setOver(false)}} onDrop={event=>{event.preventDefault();const id=event.dataTransfer.getData(MIME);setOver(false);if(engines.some(e=>e.id===id))void load(id)}}>
   <div className="el-dock-top"><span>LAUNCH DOCK</span><span className="el-dock-state">{busy?'CONNECTING':engine?'READY':'STANDBY'}</span></div><div className="el-orbit" aria-hidden="true"><i/><i/><i/><div className="el-dock-core">{engine?<Illustration index={index}/>:<svg width="52" height="52" viewBox="0 0 48 48" fill="none"><path d="m24 7 15 9v17l-15 9-15-9V16zM9 16l15 9 15-9M24 25v17" stroke="currentColor" strokeWidth="1.5"/></svg>}</div><span className="el-orbit-dot"/></div>
   <h2>{busy?'Opening your workspace…':over?'Release to load':engine?engine.name:'Drop an engine here'}</h2><p>{engine?'Only this engine’s teams, conversations and plans will appear in Infra.':'Pick a purpose. Drop it into place.\nYour workspace will unfold from here.'}</p><button className="el-load" disabled={!engine||!!busy||loading} onClick={()=>engine&&void load(engine.id)}>{busy?<><span className="el-spinner"/> Loading engine</>:<><span>Load{engine?' '+engine.name:' engine'}</span><span aria-hidden="true">→</span></>}</button><span className="el-dock-caption">Loading opens a workspace. It does not start an Agent.</span>
  </div><div className="el-boundary-note"><span aria-hidden="true">◇</span><div><strong>One engine. One context.</strong><p>Switch from Engine to Infra to meet its team. Return home whenever you need a different workspace.</p></div></div></aside></div>
  <footer className="el-footer"><span>ENGINE · INFRA · CONTRACT</span><span>Built around a clear goal.</span></footer></div>
  {ghost&&<div className="el-touch-ghost" style={{left:ghost.x,top:ghost.y}} aria-hidden="true"><Illustration index={engines.findIndex(e=>e.id===ghost.id)}/></div>}
 </main>
}
