import {MindmapExplorer} from './mindmap-explorer.js';
import {MindmapZones} from './mindmap-zones.js';
import {MindmapPitchControls} from './mindmap-pitch-controls.js';
import {refineToolbar} from './mindmap-toolbar.js';
import {MindmapEquation} from './mindmap-equation.js';
import {TopicResize} from './topic-resize.js';
import {MindmapDesigns} from './mindmap-designs.js';
import {MindmapActions} from './mindmap-actions.js';
import {skeletonGallery,bindSkeletonGallery} from './mindmap-skeletons.mjs';
import {mapStyle} from './mindmap-style.mjs';
import {TopicPeek} from './topic-peek.js';
import {applyTitleRun} from './mindmap-rich-runs.mjs';
import {XmindFiles} from './xmind-files.js';
import {MindmapTools} from './mindmap-tools.js';
import {MindmapPresentation} from './mindmap-presentation.js';
import {$,escape as E,icon,run,toast,showDialog,field,closeDialog} from './dom.js';
import {api} from './transport.js';
import {CATALOG as C,svgShape,relationshipRoute} from './mindmap-style.mjs';
import {MindmapMotion} from './mindmap-motion.js';
const choices=(values,current,inherit=false)=>`${inherit?'<option value="">跟随导图</option>':''}`+Object.entries(values).map(([v,t])=>`<option value="${E(v)}" ${String(current)===v?'selected':''}>${E(t.title||t)}</option>`).join('');
const input=(key,title,value,type='text',extra='')=>`<label class="mm-field"><span>${title}</span><input data-mm-field="${key}" type="${type}" value="${E(value??'')}" ${type==='number'?extra.replace(/step="[^"]*"/g,'')+' step="any"':extra}></label>`;
const select=(key,title,value,values,inherit=false)=>`<label class="mm-field"><span>${title}</span><select data-mm-field="${key}">${choices(values,value,inherit)}</select></label>`;
const toggle=(key,title,value)=>`<label class="mm-toggle"><span>${title}</span><input data-mm-field="${key}" type="checkbox" ${value?'checked':''}></label>`;
export class MindmapStudio {
 constructor(study){
  this.study=study;this.map=study.map;this.busy=false;this.tab='map';this.motion=new MindmapMotion(this.map);this.map.motion=this.motion;this.peek=new TopicPeek(study);
  const bar=document.createElement('nav');bar.className='mindmap-toolbar';bar.setAttribute('aria-label','思维导图工具');
  bar.innerHTML=`<button id="mm-enable" title="切换紧凑主题与摘录卡片">${icon('book')}<span>思维导图</span></button><div class="mm-active-tools"><button id="mm-themes">骨架 / 配色</button><select id="mm-structure" aria-label="思维导图结构">${choices(C.structures,'mindmap')}</select><button id="mm-format">格式</button><button id="mm-new-topic" title="同级主题 · Enter">＋ 主题</button><button id="mm-new-child" title="子主题 · Tab">子主题</button><button id="mm-boundary">外框</button><button id="mm-summary">概要</button><button id="mm-callout">标注</button><button id="mm-relationship">联系</button><button id="mm-template">模板</button><button id="mm-organize-roots" title="将现有自由主题归入一个新中心主题，可撤销">整理成导图</button><button id="mm-focus">聚焦</button><button id="mm-zen">专注</button><button id="mm-export">导出图像</button></div>`;
  this.map.board.querySelector('.study-map-toolbar').after(bar);this.bar=bar;this.bar.hidden=true;this.map.board.querySelector('.study-map-toolbar').prepend($('mm-enable'));$('mm-enable').hidden=true;this.tools=new MindmapTools(this);this.xmindFiles=new XmindFiles(this);this.presenter=new MindmapPresentation(study);this.designs=new MindmapDesigns(this);this.actions=new MindmapActions(this);this.resize=new TopicResize(study);this.equation=new MindmapEquation(this);this.pitch=new MindmapPitchControls(this);
  this.explorer=new MindmapExplorer(this);this.zones=new MindmapZones(this);refineToolbar(this.bar);
  const panel=document.createElement('aside');panel.id='mindmap-format-panel';panel.className='mindmap-format-panel';panel.hidden=true;panel.setAttribute('aria-label','思维导图格式');
  panel.innerHTML='<header><strong>导图设计</strong><button id="mm-panel-close" aria-label="关闭导图格式">×</button></header><nav class="mm-panel-tabs"><button data-mm-tab="map">导图</button><button data-mm-tab="topic">主题</button><button data-mm-tab="markers">标记</button></nav><form id="mm-format-form"><div id="mm-format-fields"></div><div id="mm-format-warning" role="status"></div><footer><button type="button" id="mm-format-reset">重设样式</button><button type="submit" id="mm-format-apply" class="primary">应用</button></footer></form>';
  this.map.board.append(panel);this.panel=panel;this.form=$('mm-format-form');
  const minimap=document.createElement('div');minimap.id='mindmap-overview';minimap.setAttribute('aria-label','导图导航缩略图');minimap.innerHTML='<svg role="img" aria-label="整个导图与当前视口"></svg><button id="mm-overview-fit" title="适合整个导图">适配</button>';this.map.board.append(minimap);this.minimap=minimap;
  $('mm-enable').disabled=true;$('mm-themes').onclick=()=>this.open('map');$('mm-format').onclick=()=>this.open(this.map.selected?'topic':'map');
  $('mm-structure').onchange=run(()=>this.configure({structure:$('mm-structure').value}));$('mm-new-topic').onclick=run(()=>this.add('after'));$('mm-new-child').onclick=run(()=>this.add('child'));
  for(const kind of ['boundary','summary','callout'])$('mm-'+kind).onclick=()=>this.createDecoration(kind);
  $('mm-organize-roots').onclick=()=>this.organizeRoots();
  $('mm-relationship').onclick=run(()=>this.createRelationship());$('mm-template').onclick=()=>this.templates();$('mm-export').onclick=()=>this.export();
  $('mm-focus').onclick=run(()=>this.map.focus(this.study.current.map.focusId?null:this.map.selected));$('mm-zen').onclick=()=>{this.zen=!this.zen;this.map.board.classList.toggle('mm-zen',this.zen);this.map.window.schedule();};
  $('mm-panel-close').onclick=()=>this.close();$('mm-overview-fit').onclick=()=>this.map.fit();
  panel.querySelectorAll('[data-mm-tab]').forEach(b=>b.onclick=()=>this.open(b.dataset.mmTab));
  this.form.oninput=()=>this.changed();this.form.onchange=()=>this.changed();this.form.onsubmit=e=>{e.preventDefault();run(()=>this.save())();};$('mm-format-reset').onclick=run(()=>this.reset());
  document.addEventListener('study-card-selected',()=>{if(!panel.hidden&&!this.dirty&&this.tab!=='map'&&this.map.selected)this.open(this.tab);this.updateButtons();});
  this.map.board.addEventListener('keydown',e=>this.key(e),true);
  this.map.board.addEventListener('dblclick',e=>{if(!this.enabled||e.target.closest('button,input,select,[data-link-id]')||this.study.cardInk.mode!=='off')return;const card=e.target.closest('.study-card');if(card){e.preventDefault();e.stopImmediatePropagation();if(e.target.closest('.mm-equation'))this.equation.open(card.dataset.cardId);else run(()=>this.editTitle(card.dataset.cardId))();}},true);
  this.map.board.addEventListener('click',e=>{const item=e.target.closest('[data-mm-item]'),link=e.target.closest('[data-mm-link]');if(item||link){e.preventDefault();e.stopPropagation();this.open(item?'decoration':'relationship',item?.dataset.mmItem||link?.dataset.mmLink);}},true);
  const view=$('study-map-viewport');view.addEventListener('scroll',()=>this.overview(),{passive:true});new ResizeObserver(()=>this.overview()).observe(view);
  minimap.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;e.preventDefault();e.stopPropagation();const svg=minimap.querySelector('svg'),rect=svg.getBoundingClientRect(),layout=this.map.layout,scale=Math.min(rect.width/layout.width,rect.height/layout.height),left=rect.x+(rect.width-layout.width*scale)/2,top=rect.y+(rect.height-layout.height*scale)/2;const move=e=>{this.map.camera.center((e.clientX-left)/scale,(e.clientY-top)/scale);};move(e);minimap.setPointerCapture(e.pointerId);const stop=()=>{minimap.removeEventListener('pointermove',move);minimap.removeEventListener('pointerup',stop);};minimap.addEventListener('pointermove',move);minimap.addEventListener('pointerup',stop,{once:true});});
 }
 get enabled(){return this.study.current?.map?.mindmap?.enabled===true;}
 get dirty(){return Boolean(this.zones?.active||this.busy||this.inline||this.baseline&&JSON.stringify(this.values())!==JSON.stringify(this.baseline));}
 guard(){if(this.zones?.active)throw Error('请先结束区域调整。');if(this.resize?.active)throw Error('请先结束主题宽度调整。');if(this.map.topicDrag?.active?.moved)throw Error('请先结束当前主题拖动。');if(this.inline||this.busy||!this.panel.hidden&&this.dirty)throw Error('导图编辑有未保存内容，请先保存或放弃。');}
 values(){return Object.fromEntries([...this.form.querySelectorAll('[data-mm-field]')].map(el=>[el.dataset.mmField,el.type==='checkbox'?el.checked:el.value]));}
 changed(){this.panel.dataset.dirty=String(this.dirty);$('mm-format-apply').disabled=this.busy;}
 ids(){return this.study.current?this.study.organization.ids():[];}
 async configure(patch){this.guard();await this.study.change('study.mindmap.configure',{patch});this.map.window.schedule();}
 render(set){
  this.peek.observe(set);const enabled=set.map?.mindmap?.enabled===true;this.map.board.classList.toggle('mindmap-enabled',enabled);this.bar.hidden=!enabled;this.bar.querySelector('.mm-active-tools').hidden=!enabled;$('mm-enable').setAttribute('aria-pressed',String(enabled));$('mm-enable').querySelector('span').textContent=enabled?'主题脑图':'资料卡片';$('mm-enable').title=enabled?'切换到资料卡片布局':'切换到主题脑图布局';$('mm-structure').value=mapStyle(set.map?.mindmap).structure;
  if(!enabled){if(this.dirty&&!this.panel.hidden){$('mm-format-warning').textContent='另一处已切换到摘录卡片。未保存的格式输入仍保留，请应用或明确放弃。';}else{this.panel.hidden=true;this.map.board.classList.remove('mm-panel-open');this.baseline=null;}this.map.board.classList.remove('mm-zen');}
  if(!this.panel.hidden&&set.revision!==this.revision){if(this.dirty)$('mm-format-warning').textContent='学习集已更新。当前输入保留；应用时将检查版本。';else this.fill();}
  this.updateButtons();this.overview();
 }
 updateButtons(){const id=this.map.selected;for(const name of ['new-child','callout','focus'])$('mm-'+name).disabled=!id;for(const name of ['boundary','summary','relationship'])$('mm-'+name).disabled=!this.ids().length;$('mm-delete-topic').disabled=this.map.deleting||!this.ids().length;}
 open(tab='map',id){
  if(this.dirty&&!this.busy){toast('当前格式输入已保留，请先应用或关闭并放弃。',true);return;}
  if(!this.study.current)return;this.tab=tab;this.target=id;this.panel.hidden=false;this.panel.style.zIndex='42';this.study.inspector.panel.style.zIndex='40';this.map.board.classList.add('mm-panel-open');this.fill();this.map.window.schedule();
 }
 close(){this.handles?.remove();if(this.busy)return;if(this.dirty){showDialog({title:'放弃导图格式修改？',html:'<p class="dialog-note">已保存的导图不受影响。</p>',submit:'放弃修改',onSubmit:()=>{this.baseline=null;this.panel.hidden=true;this.map.board.classList.remove('mm-panel-open');}});return;}this.baseline=null;this.panel.hidden=true;this.map.board.classList.remove('mm-panel-open');}
 fill(){
  this.handles?.remove();const set=this.study.current;if(!set)return;this.setId=set.id;this.revision=set.revision;this.selectedIds=[...this.ids()];let html='',v={};
  this.panel.querySelectorAll('[data-mm-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mmTab===this.tab)));
  if(this.tab==='map'){
   v=set.map?.mindmap||{};const resolved=mapStyle(v);html=skeletonGallery(v)+'<div class="mm-theme-grid">'+Object.entries(C.themes).map(([id,t])=>`<button type="button" data-mm-theme="${id}" aria-pressed="${(v.theme||'radiance')===id}" title="${E(t.title)}"><svg viewBox="0 0 110 62"><rect x="0" y="0" width="110" height="62" rx="8" fill="${t.paper}"/><path d="M44 31C58 31 56 15 69 15 M44 31C58 31 56 45 69 45 M44 31C24 31 32 17 13 17" fill="none" stroke="${t.palette[1]}" stroke-width="2"/><rect x="31" y="24" width="26" height="15" rx="5" fill="${t.palette[0]}"/><rect x="67" y="10" width="26" height="11" rx="4" fill="${t.palette[1]}"/><rect x="67" y="40" width="26" height="11" rx="4" fill="${t.palette[2]}"/></svg><span>${E(t.title)}</span></button>`).join('')+'</div>';
   html+=select('structure','结构',resolved.structure,C.structures)+select('line','分支线',resolved.line,C.lines)+select('colorMode','配色',v.colorMode||C.themes[v.theme||'radiance'].colorMode||'branch',{branch:'彩虹分支',level:'层级配色',single:'单色'})+select('numbering','自动编号',v.numbering||'none',C.numbering)+input('fontFamily','字体',v.fontFamily||'system-ui')+input('topicWidth','统一宽度',v.topicWidth||'','number','min="100" max="600" placeholder="自动"')+input('background','画布颜色',v.background||'','text','placeholder="跟随主题 · #RRGGBB"')+input('titleLines','标题行数 · 0为完整',v.titleLines??0,'number','min="0" max="8"')+input('fontSize','字号',v.fontSize||16,'number','min="12" max="32"')+input('spacing','主题间距',resolved.spacing,'number','min="12" max="100"')+input('branchSpacing','分支间距',resolved.branchSpacing,'number','min="30" max="220"')+input('palette','分支自定色',v.palette?.join(', ')||'','text','placeholder="#RRGGBB, #RRGGBB"')+input('centralColor','中心自定色',v.centralColor||'','text','placeholder="跟随配色"')+input('numberPrefix','编号前缀',v.numberPrefix||'')+input('numberSuffix','编号后缀',v.numberSuffix||'')+toggle('freeBranches','自由调整主分支',v.freeBranches===true)+toggle('flexibleFloating','自由主题关闭邻近吸附',v.flexibleFloating===true)+toggle('topicOverlap','允许主题重叠',v.topicOverlap===true)+toggle('smartGuides','自由摆放辅助线',v.smartGuides!==false)+'<div class="mm-design-actions"><button type="button" id="mm-edit-levels">设计层级样式</button><button type="button" id="mm-save-design">保存当前设计</button></div>'+toggle('autoBalance','自动平衡两侧',v.autoBalance!==false)+toggle('sameLevelWidth','同级等宽',v.sameLevelWidth===true)+toggle('gradient','渐变填充',v.gradient===true)+toggle('shadow','柔和投影',v.shadow===true)+toggle('showSources','显示来源小标签',v.showSources===true)+toggle('showImages','显示摘录图片',v.showImages===true)+toggle('showTags','显示标签',v.showTags===true)+toggle('motion','布局过渡动画',v.motion!==false)+toggle('minimap','导航缩略图',v.minimap!==false);
  }else if(this.tab==='topic'||this.tab==='markers'){
   const card=set.cards.find(c=>c.id===this.selectedIds[0]);if(!card){html='<p class="mm-empty">先选中一个或多个主题。</p>';}else{
    v=card.mindmap||{};const actual=this.map.layout.topics?.get(card.id);html=`<p class="mm-panel-context">${this.selectedIds.length} 个主题 · ${E(card.title)}</p>`;
    if(this.tab==='markers')html+=select('priority','优先级',v.priority??0,Object.fromEntries(Array.from({length:10},(_,i)=>[i,i?'优先级 '+i:'无'])))+input('progress','完成进度 %',v.progress??'','number','min="0" max="100"')+select('status','状态',v.status||'none',{none:'无',todo:'待办',doing:'进行中',done:'完成',blocked:'阻塞'})+select('symbol','图标',v.symbol||'',C.symbols,true)+input('flagColor','旗标颜色',v.flagColor||'','text','placeholder="#RRGGBB"')+input('task.start','开始日期',v.task?.start||'','date')+input('task.due','截止日期',v.task?.due||'','date')+input('task.assignee','负责人',v.task?.assignee||'');
    else html+=`<div class="mm-shape-grid">${Object.entries(C.shapes).map(([id,label])=>`<button type="button" data-mm-shape="${id}" aria-label="${E(label)}" title="${E(label)}" aria-pressed="${(v.shape||actual?.shape)===id}"><svg viewBox="-2 -2 64 38">${svgShape(id,60,34,{fill:'#EEF2FE',borderColor:'#6377B4',borderWidth:1.3})}</svg></button>`).join('')}</div>`+select('structure','分支结构',v.structure||'',C.structures,true)+select('side','主分支方位',v.side||'auto',{auto:'自动',left:'左侧',right:'右侧'})+input('fill','填充颜色',v.fill||'','text','placeholder="跟随主题 · #RRGGBB"')+input('textColor','文字颜色',v.textColor||'','text','placeholder="跟随主题 · #RRGGBB"')+input('borderColor','边框颜色',v.borderColor||'','text','placeholder="#RRGGBB"')+input('fontSize','字号',v.fontSize||'','number','min="10" max="48" placeholder="跟随导图"')+input('width','主题宽度',v.width||'','number','min="100" max="800" placeholder="自动"')+select('align','文字对齐',v.align||actual?.align||'center',{left:'左',center:'居中',right:'右'})+select('borderDash','边框线型',v.borderDash||'solid',{solid:'实线',dash:'虚线',dot:'点线'})+input('borderWidth','边框粗细',v.borderWidth??actual?.borderWidth??1.2,'number','min="0" max="10" step="0.2"')+input('fontFamily','字体',v.fontFamily||'','text','placeholder="跟随导图"')+select('branchLine','分支线型',v.branchLine||'',C.lines,true)+input('branchColor','分支颜色',v.branchColor||'','text','placeholder="#RRGGBB"')+input('branchWidth','分支粗细',v.branchWidth||'','number','min="0.5" max="12" step="0.5"')+select('numbering','编号',v.numbering||'',C.numbering,true)+toggle('bold','加粗',v.bold??this.map.layout.topics?.get(card.id)?.bold??true)+toggle('italic','斜体',v.italic||false)+toggle('underline','下划线',v.underline||false)+toggle('showNote','显示笔记摘要',v.showNote||false)+'<button type="button" id="mm-rich-title">局部文字格式…</button>';
   }
  }else if(this.tab==='relationship'){
   const l=set.links.find(l=>l.id===this.target);if(l){v=l.mindmap||{};html=input('label','联系说明',l.label||'')+select('line','线型',v.line||'curve',C.lines)+select('start','起点样式',v.start||(l.bidirectional?'triangle':'none'),C.arrows)+select('end','终点样式',v.end||'triangle',C.arrows)+input('color','线条颜色',v.color||'#75869E','color')+input('width','粗细',v.width||1.8,'number','min="0.5" max="12" step="0.5"')+select('dash','线条',v.dash||'dash',{solid:'实线',dash:'虚线',dot:'点线'})+toggle('followTopic','跟随主题色',v.followTopic||false)+toggle('avoidTopics','自动避让其他主题',v.avoidTopics!==false&&v.bendX===undefined&&v.bendY===undefined)+'<p class="mm-empty">拖动蓝色控制点调整曲线；拖动端点至另一主题重新连接。</p><button type="button" id="mm-delete-link" class="danger">移除联系</button>';this.drawHandles(l);}
  }else if(this.tab==='decoration'){
   const item=set.map?.mindmap?.items?.find(i=>i.id===this.target);if(item){v=item.style||{};html=input('title','标题',v.title||'')+select('shape','外框形状',v.shape||'rounded',C.boundaries)+input('color','轮廓颜色',v.color||'#778AC4','color')+input('fill','填充颜色',v.fill||'#F0F3FC','color')+input('opacity','透明度',v.opacity??.7,'number','min="0" max="1" step="0.1"')+input('width','轮廓粗细',v.width||1.4,'number','min="0.5" max="10" step="0.2"')+input('padding','留白',v.padding||18,'number','min="8" max="80"')+select('dash','轮廓线',v.dash||'dash',{solid:'实线',dash:'虚线',dot:'点线'})+'<button type="button" id="mm-edit-members">调整覆盖主题…</button><button type="button" id="mm-delete-decoration" class="danger">移除（保留主题）</button>';
    if(item.kind==='zone'){const box=this.map.layout.decorations.find(i=>i.id===item.id);this.zoneFrame=v.frame||(box?{x:box.x+(this.map.layout.originX||0),y:box.y+(this.map.layout.originY||0),width:box.width,height:Math.max(100,box.height)}:null);html+=toggle('collapsed','折叠区域',v.collapsed===true)+toggle('autoResize','自动适合内容',v.autoResize!==false)+toggle('titleHidden','隐藏区域标题',v.titleHidden===true)+input('zIndex','区域层序',v.zIndex||0,'number','min="-500" max="500"')+(this.zoneFrame?input('frame.x','区域横坐标',this.zoneFrame.x,'number')+input('frame.y','区域纵坐标',this.zoneFrame.y,'number')+input('frame.width','区域宽度',this.zoneFrame.width,'number','min="100" max="1000000"')+input('frame.height','区域高度',this.zoneFrame.height,'number','min="100" max="1000000"'):'<p class="mm-empty">区域不在当前聚焦视图，退出聚焦后可调整尺寸。</p>')+'<button type="button" id="mm-zone-select">选择并复制区域内容</button>';}
   }
  }
  $('mm-format-fields').innerHTML=html;bindSkeletonGallery($('mm-format-fields'),v);this.baseline=this.values();this.sourceValue=v;$('mm-format-warning').textContent='';this.changed();
  $('mm-format-fields').querySelectorAll('[data-mm-skeleton]').forEach(b=>b.onclick=run(()=>{if(this.dirty)throw Error('先应用或放弃当前格式修改。');const id=b.dataset.mmSkeleton;return this.commit('study.mindmap.configure',{patch:{enabled:true,skeleton:id,levelStyles:null,structure:C.skeletons[id].structure,line:null,spacing:null,branchSpacing:null,topicShape:null,rootShape:null}});}));
  $('mm-format-fields').querySelectorAll('[data-mm-theme]').forEach(b=>b.onclick=run(()=>{if(this.dirty)throw Error('先应用或放弃当前格式修改。');return this.commit('study.mindmap.configure',{patch:{enabled:true,skeleton:mapStyle(this.study.current.map.mindmap).skeleton,palette:null,centralColor:null,theme:b.dataset.mmTheme}});}));
  $('mm-format-fields').querySelectorAll('[data-mm-shape]').forEach(b=>b.onclick=run(()=>{if(this.dirty)throw Error('先应用或放弃当前格式修改。');return this.commit('study.mindmap.topics.update',{cardIds:this.selectedIds,patch:{shape:b.dataset.mmShape}});}));
  $('mm-edit-levels')?.addEventListener('click',()=>this.designs.editLevels());$('mm-save-design')?.addEventListener('click',()=>this.designs.saveCurrent());
  $('mm-rich-title')?.addEventListener('click',()=>this.richTitle());$('mm-edit-members')?.addEventListener('click',()=>this.editMembers());
  $('mm-zone-select')?.addEventListener('click',run(async()=>{this.guard();const item=this.study.current.map.mindmap.items.find(i=>i.id===this.target);this.close();this.zones.select(item);await this.study.mapTools.copy('clone',item.cardIds);$('study-map-viewport').focus();}));
  $('mm-delete-decoration')?.addEventListener('click',run(()=>this.commit('study.mindmap.decoration.remove',{decorationId:this.target})));
  $('mm-delete-link')?.addEventListener('click',run(()=>this.commit('study.link.remove',{linkId:this.target})));
 }
 async commit(method,params){if(this.busy)return;if(this.study.current?.id!==this.setId)throw Error('学习集已切换，当前格式草稿不会写入其他学习集。');this.busy=true;this.form.querySelectorAll('button,input,select').forEach(el=>el.disabled=true);try{const result=await this.study.change(method,params,this.revision);this.baseline=null;this.busy=false;this.fill();return result;}catch(e){$('mm-format-warning').textContent=e.message;throw e;}finally{this.busy=false;this.form.querySelectorAll('button,input,select').forEach(el=>el.disabled=false);}}
 async save(){
  if(!this.baseline||this.busy)return;if(!this.form.reportValidity())throw Error('请检查导图格式中的输入。');
  const values=this.values(),patch={},numbers=new Set(['titleLines','fontSize','spacing','branchSpacing','borderWidth','branchWidth','topicWidth','width','priority','progress','opacity','padding','zIndex','frame.x','frame.y','frame.width','frame.height']);
  for(const [key,value] of Object.entries(values)){if(this.baseline[key]===value)continue;const v=value===''?null:key==='palette'?value.split(/[,，\s]+/).filter(Boolean):numbers.has(key)?Number(value):value;if(key.startsWith('frame.')){patch.frame={...this.zoneFrame,...patch.frame,[key.slice(6)]:v};patch.autoResize=false;}else if(key.startsWith('task.')){patch.task={...this.sourceValue.task,...patch.task,[key.slice(5)]:v};}else patch[key]=v;}
  if(!Object.keys(patch).length)return;
  if(this.tab==='map')return this.commit('study.mindmap.configure',{patch});
  if(['topic','markers'].includes(this.tab))return this.commit('study.mindmap.topics.update',{cardIds:this.selectedIds,patch});
  if(this.tab==='relationship'){const {label,...visual}=patch;if(visual.avoidTopics===true){visual.bendX=null;visual.bendY=null;}return this.commit('study.mindmap.relationship.update',{linkId:this.target,patch:visual,...(label!==undefined?{label}:{})});}
  return this.commit('study.mindmap.decoration.set',{decorationId:this.target,style:patch});
 }
 async reset(){if(['topic','markers'].includes(this.tab))return this.commit('study.mindmap.topics.update',{cardIds:this.selectedIds,patch:{},reset:true});if(this.tab==='relationship')return this.commit('study.mindmap.relationship.update',{linkId:this.target,patch:{},reset:true});if(this.tab==='map')return this.commit('study.mindmap.configure',{patch:Object.fromEntries(Object.keys(this.study.current.map.mindmap).filter(k=>k!=='items'&&k!=='enabled').map(k=>[k,null]))});}
 async add(relation){
  this.guard();const set=this.study.current,card=set.cards.find(c=>c.id===this.map.selected);let result,id;
  if(card){const localRoot=!card.parentId||[set.map?.focusId,set.map?.submapId].includes(card.id);const insert=localRoot&&['before','after'].includes(relation)?'child':relation;
   result=await this.study.change('study.card.insert',{cardId:card.id,relation:insert,title:'新主题',...(localRoot&&relation==='before'?{index:0}:{})});id=result.lastInsertedCard;}
  else{result=await this.study.change('study.note.create',{title:'中心主题'});id=result.cards.find(c=>!set.cards.some(old=>old.id===c.id)).id;}
  this.map.select(id);this.map.center(id);await this.editTitle(id);
 }
 editTitle(id,initial){
  this.guard();const set=this.study.current,card=set.cards.find(c=>c.id===id);if(!card)return;
  this.map.select(id);this.motion.finish();this.map.window.paint();let node=this.map.window.nodes.get(id);const view=$('study-map-viewport').getBoundingClientRect(),rect=node?.getBoundingClientRect();if(!rect||rect.right<view.left||rect.left>view.right||rect.bottom<view.top||rect.top>view.bottom){this.map.center(id);node=this.map.window.nodes.get(id);}if(!node)return;const b=node.getBoundingClientRect(),input=document.createElement('textarea');input.className='mm-inline-title';input.value=initial??card.title;input.maxLength=200;input.setAttribute('aria-label','编辑主题标题');Object.assign(input.style,{left:b.x+'px',top:b.y+'px',width:Math.max(160,b.width)+'px',height:Math.max(64,b.height)+'px'});document.body.append(input);this.inline={input,id};
  const close=()=>{input.remove();this.inline=null;this.map.window.nodes.get(id)?.focus({preventScroll:true});};
  const save=async()=>{if(input.disabled)return;input.disabled=true;try{if(!input.value.trim())throw Error('主题标题不能为空。');if(input.value!==card.title)await this.study.change('study.card.update',{cardId:id,title:input.value},set.revision);close();}catch(e){input.disabled=false;input.focus();throw e;}};this.inline.save=save;
  input.addEventListener('keydown',e=>{if(e.isComposing)return;if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();run(save)();}});input.focus();if(initial===undefined)input.select();
 }
 async saveDraft(){if(this.inline)await this.inline.save();if(!this.panel.hidden&&this.dirty)await this.save();}
 key(e){
  if(!this.enabled||$('dialog').open||e.isComposing||e.target.closest('input,textarea,select,button,a,[role=button],#mindmap-overview,[contenteditable=true]')||this.panel.contains(e.target))return;
  const card=e.target.closest('.study-card'),id=card?.dataset.cardId||this.map.selected;if(!id)return;
  if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)run(()=>this.map.remove(null,e.shiftKey?'subtree':'promote'))();return;}
  if(e.key==='Enter'||e.key==='Tab'||e.key===' '){e.preventDefault();e.stopImmediatePropagation();this.map.select(id);if(e.key===' ')run(()=>this.editTitle(id))();else if(e.key==='Tab'&&e.shiftKey)this.map.nest(this.study.current.cards.find(c=>c.id===id),true);else run(()=>this.add(e.key==='Tab'?'child':e.ctrlKey||e.metaKey?'parent':e.shiftKey?'before':'after'))();return;}
  if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)&&id){e.preventDefault();e.stopImmediatePropagation();const set=this.study.current,node=set.cards.find(c=>c.id===id),siblings=set.cards.filter(c=>c.parentId===node.parentId),index=siblings.findIndex(c=>c.id===id),next=index+(e.key==='ArrowUp'?-1:1);if(next>=0&&next<siblings.length)run(()=>this.study.change('study.cards.move',{cardIds:[id],parentId:node.parentId,index:next},set.revision))();return;}
  if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&!e.metaKey&&!e.ctrlKey){e.preventDefault();e.stopImmediatePropagation();const p=this.map.layout.positions.get(id);if(!p)return;const dx=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0,dy=e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0;let candidate,best=Infinity;for(const [key,b]of this.map.layout.positions){if(key===id)continue;const x=b.x+b.width/2-p.x-p.width/2,y=b.y+b.height/2-p.y-p.height/2;if(x*dx+y*dy<=0)continue;const score=Math.hypot(x,y)+(dx?Math.abs(y):Math.abs(x))*1.8;if(score<best){best=score;candidate=key;}}if(candidate){this.map.select(candidate);this.map.center(candidate);this.map.window.nodes.get(candidate)?.focus({preventScroll:true});}}
 }
 createDecoration(kind){
  this.guard();const set=this.study.current,ids=this.ids();if(!ids.length){toast('请先选择主题。');return;}
  showDialog({title:{boundary:'添加外框',summary:'添加概要',callout:'添加标注'}[kind],html:field('title','文字',kind==='summary'?'概要':'',{required:kind!=='boundary'})+`<p class="dialog-note">${ids.length} 个主题；外框与概要使用同一父主题下的选择。Shift 单击可多选。</p>`,onSubmit:async v=>{const next=await this.study.change('study.mindmap.decoration.set',{kind,cardIds:ids,style:{title:v.title}},set.revision);closeDialog();this.open('decoration',next.lastMindmapDecoration);}});
 }
 editMembers(){const item=this.study.current.map.mindmap.items.find(i=>i.id===this.target),set=this.study.current;const parent=set.cards.find(c=>c.id===item.cardIds[0])?.parentId;showDialog({title:'调整覆盖主题',html:set.cards.filter(c=>c.parentId===parent&&c.id!==item.topicId).map(c=>`<label class="mm-member-choice"><input type="checkbox" name="member-${c.id}" ${item.cardIds.includes(c.id)?'checked':''}>${E(c.title)}</label>`).join(''),onSubmit:async()=>{const ids=[...$('dialog-fields').querySelectorAll('input:checked')].map(i=>i.name.slice(7));await this.study.change('study.mindmap.decoration.set',{decorationId:item.id,cardIds:ids},set.revision);this.baseline=null;this.fill();}});}
 async createRelationship(){this.guard();const ids=this.ids();if(ids.length!==2){toast('Shift 单击选择两个主题，或使用链接拖绘工具。');return;}const before=this.study.current.links||[],set=await this.study.change('study.link.add',{from:ids[0],to:ids[1],label:'联系',bidirectional:false}),link=set.links.find(l=>!before.some(old=>old.id===l.id));if(link)this.open('relationship',link.id);}
 richTitle(){const set=this.study.current,card=set.cards.find(c=>c.id===this.selectedIds[0]);if(!card)return;showDialog({title:'局部文字格式',html:field('text','匹配文字','',{required:true,help:'对首个匹配范围设置格式；其它文字的已有格式保留。标题：'+card.title})+field('color','颜色','#D25F61',{type:'color'})+field('weight','字体','bold',{choices:[['bold','加粗'],['italic','斜体'],['underline','下划线'],['normal','仅颜色']]}),onSubmit:v=>{const start=card.title.indexOf(v.text);if(start<0)throw Error('标题中没有这段文字。');return this.study.change('study.mindmap.topics.update',{cardIds:[card.id],patch:{runs:applyTitleRun(card.mindmap?.runs,start,start+v.text.length,{color:v.color,...(v.weight==='normal'?{}:{[v.weight]:true})})}},set.revision);}});}
 organizeRoots(){this.guard();const set=this.study.current,summaryIds=new Set((set.map.mindmap.items||[]).filter(i=>i.kind==='summary').map(i=>i.topicId)),roots=set.cards.filter(c=>!c.parentId&&c.inMap!==false&&!summaryIds.has(c.id));if(roots.length<2){toast('已有统一中心，使用 Tab 添加子主题，Enter 添加同级主题。');return;}showDialog({title:'整理成一个完整思维导图',html:field('title','中心主题',set.title,{required:true})+'<p class="dialog-note">将 '+roots.length+' 个自由分支放到新中心下，保留已有子主题、摘录、笔记和原文链接。可用撤销恢复原结构。</p>',submit:'整理',onSubmit:async v=>{await this.study.change('study.cards.group',{cardIds:roots.map(c=>c.id),title:v.title},set.revision);this.map.fit();}});}
 templates(){const set=this.study.current;run(async()=>{const c=await api('study.mindmap.catalog');showDialog({title:'添加导图模板',html:field('template','结构模板','brainstorm',{choices:Object.entries(c.templates).map(([id,t])=>[id,t.title])})+field('title','中心主题','',{help:'留空使用模板名称；现有主题与原文不会删除。'}),submit:'添加',onSubmit:async v=>{const next=await this.study.change('study.mindmap.template.apply',{template:v.template,...(v.title.trim()?{title:v.title}:{})},set.revision);this.map.select(next.lastInsertedCard);this.map.fit();}});})();}
 export(){const set=this.study.current;showDialog({title:'导出思维导图',html:field('format','格式','svg',{choices:[['svg','SVG · 矢量图'],['png','PNG · 图像'],['pdf','PDF · 矢量文字与曲线'],['pptx','PowerPoint · 可编辑讲解页']]})+field('content','导出内容','map',{choices:[['map','思维导图 · SVG / PNG / PDF'],['pitch','自动编排演示 · PDF / PPTX']]})+field('pdfMode','PDF 模式','vector',{choices:[['vector','矢量 · 可选择文字'],['raster','图像 · 字体兼容']]})+field('paper','PDF 纸张','auto',{choices:[['auto','自动 · 整张导图'],['A4','A4 横向'],['A3','A3 横向']]})+field('path','保存路径','mindmap.svg',{required:true})+field('scope','范围','all',{choices:[['all','完整导图 · 展开所有分支'],['visible','当前分支与折叠状态']]})+'<p class="dialog-note">原件、卡片与历史不变。SVG 与默认 PDF 保留矢量文字和曲线；PDF 使用本机 Unicode 字体，PNG 与兼容 PDF 才栅格化。</p>',submit:'导出',onSubmit:async v=>{const r=await api('study.mindmap.export',{setId:set.id,expectedRevision:set.revision,...v});toast(`已导出 ${r.topics} 个主题${r.slides?' / '+r.slides+' 页演示':''}：${r.path}${r.warnings?.length?' · '+r.warnings.join('；'):''}`);},afterOpen:()=>{$('dialog-fields').querySelector('[name=format]').onchange=e=>{$('dialog-fields').querySelector('[name=path]').value='mindmap.'+e.target.value;$('dialog-fields').querySelector('[name=content]').value=e.target.value==='pptx'?'pitch':'map';};}});}
 overview(){
  const l=this.map.layout,v=$('study-map-viewport');this.minimap.hidden=!this.enabled||!l||this.study.current.map.mindmap.minimap===false||v.hidden;if(this.minimap.hidden)return;
  const svg=this.minimap.querySelector('svg');svg.setAttribute('viewBox',`0 0 ${l.width} ${l.height}`);const signature=this.study.current.id+':'+this.study.current.revision+':'+l.width+':'+l.height;
  if(signature!==this.overviewKey){this.overviewKey=signature;const d=[...l.positions.values()].map(p=>`M${p.x},${p.y}h${p.width}v${p.height}h-${p.width}Z`).join('');svg.innerHTML=`<path d="${d}" fill="${l.config?.palette?.[0]||'#7183B4'}" opacity=".45"/><rect class="mm-overview-window" fill="none" stroke="${l.config?.ink||'#344054'}" stroke-width="${Math.max(l.width,l.height)/180}"/>`;}
  const box=svg.querySelector('rect'),camera=this.map.camera.box();box.setAttribute('x',camera.x);box.setAttribute('y',camera.y);box.setAttribute('width',v.clientWidth/this.map.zoom);box.setAttribute('height',v.clientHeight/this.map.zoom);
 }
 drawHandles(link){
  this.handles?.remove();if(!this.enabled)return;const route=relationshipRoute(link,this.map.layout.positions);if(!route)return;const set=this.study.current,svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('mm-relation-handles');svg.setAttribute('width',this.map.layout.width);svg.setAttribute('height',this.map.layout.height);$('study-map-world').append(svg);this.handles=svg;
  svg.innerHTML=[['bend',route.mid],['start',route.start],['end',route.end]].map(([type,p])=>`<circle cx="${p[0]}" cy="${p[1]}" r="7" data-handle="${type}" tabindex="0" role="button" aria-label="${type==='bend'?'曲线控制点':type==='start'?'联系起点':'联系终点'}"/>`).join('');
  svg.querySelectorAll('circle').forEach(c=>c.onpointerdown=e=>{e.preventDefault();e.stopPropagation();this.motion.finish();this.map.drag={id:null};c.setPointerCapture(e.pointerId);const type=c.dataset.handle;let p;const move=e=>{p=this.study.mapTools.world(e);c.setAttribute('cx',p[0]);c.setAttribute('cy',p[1]);};const stop=e=>{if(c.hasPointerCapture(e.pointerId))c.releasePointerCapture(e.pointerId);c.onpointermove=c.onpointerup=c.onpointercancel=null;this.map.drag=null;if(!p){this.fill();return;}const patch=type==='bend'?{bendX:p[0]-(route.start[0]+route.end[0])/2,bendY:p[1]-(route.start[1]+route.end[1])/2}:{};svg.style.visibility='hidden';const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-card-id]')?.dataset.cardId;svg.style.visibility='';run(async()=>{await this.study.change('study.mindmap.relationship.update',{linkId:link.id,patch,...(type!=='bend'&&hit?{[type==='start'?'from':'to']:hit}:{})},set.revision);this.baseline=null;this.fill();})();};c.onpointermove=move;c.onpointerup=stop;c.onpointercancel=()=>{this.map.drag=null;this.fill();};});
 }
}
