import {$,escape as E,field,showDialog,run,closeDialog,toast} from './dom.js';
import {api} from './transport.js';
export class XmindFiles {
 constructor(studio){this.studio=studio;this.study=studio.study;studio.bar.querySelector('.mm-active-tools').insertAdjacentHTML('beforeend','<button id="mm-xmind-import">导入 XMind</button><button id="mm-xmind-export">导出 XMind</button>');$('mm-xmind-import').onclick=()=>this.import();$('mm-xmind-export').onclick=()=>this.export();}
 async upload(file,destination){
  if(file.size>64*1024*1024)throw Error('XMind 文件不能超过 64 MiB。');const task=await api('import.begin',{path:destination||file.name,totalBytes:file.size});let committed=false;
  try{for(let offset=0;offset<file.size;offset+=task.chunkSize){const bytes=new Uint8Array(await file.slice(offset,offset+task.chunkSize).arrayBuffer()),parts=[];for(let i=0;i<bytes.length;i+=32768)parts.push(String.fromCharCode(...bytes.subarray(i,i+32768)));await api('import.chunk',{uploadId:task.uploadId,offset,contentBase64:btoa(parts.join(''))});}const result=await api('import.finish',{uploadId:task.uploadId,parse:false,activate:false});committed=true;return result.path;}finally{if(!committed)await api('import.abort',{uploadId:task.uploadId}).catch(()=>{});}
 }
 import(){
  this.studio.guard();let receipt,busy=false;
  showDialog({title:'导入 XMind 工作簿',html:field('path','文库中的 .xmind 路径','',{help:'可直接填写已导入文库的路径，或选取本机文件上传。'})+'<label class="dialog-field"><span>本机文件</span><input id="mm-xmind-file" type="file" accept=".xmind"></label><button type="button" id="mm-xmind-inspect">检查工作簿</button><div id="mm-xmind-report"></div><label class="mm-member-choice"><input name="allowLossy" type="checkbox">我已阅读检查结果，允许导入可识别内容</label><p class="dialog-note">导入为独立学习集，保留原 .xmind。只支持 JSON 工作簿；旧 XML、加密和专有扩展不冒充完整兼容。</p>',submit:'导入所选画布',onSubmit:async v=>{
   if(!receipt||busy)throw Error('先检查工作簿。');if(v.path!==receipt.path)throw Error('路径已变化，请重新检查。');const sheetIds=[...$('mm-xmind-report').querySelectorAll('input:checked')].map(i=>i.value);if(!sheetIds.length)throw Error('至少选择一个画布。');const result=await api('study.mindmap.xmind.import',{path:receipt.path,expectedVersion:receipt.sourceVersion,sheetIds,allowLossy:v.allowLossy==='on',...(this.study.collection?.folderId?{folderId:this.study.collection.folderId}:{}),activate:false});await this.study.home(result.setId);toast(`已导入 ${result.setIds.length} 个画布；原文件保留。`);
  },afterOpen:()=>{$('mm-xmind-inspect').onclick=run(async()=>{if(busy)return;busy=true;$('mm-xmind-inspect').disabled=true;try{let path;const input=$('dialog-fields').querySelector('[name=path]');path=input.value;const file=$('mm-xmind-file').files[0];if(file){path=await this.upload(file,path.trim());input.value=path;$('mm-xmind-file').value='';}receipt=await api('study.mindmap.xmind.inspect',{path});receipt.path=path;$('mm-xmind-report').innerHTML=receipt.sheets.map(s=>`<label class="mm-member-choice"><input type="checkbox" value="${E(s.id)}" checked>${E(s.title)} · ${s.topics} 个主题</label>`).join('')+receipt.warnings.map(w=>`<p class="dialog-note">${E(w.code)}：${E(w.message)}</p>`).join('');}finally{busy=false;if($('mm-xmind-inspect'))$('mm-xmind-inspect').disabled=false;}});}});
 }
 export(){this.studio.guard();run(async()=>{const sets=(await api('study.list')).sets;showDialog({title:'导出 XMind 工作簿',html:field('path','保存路径','mindmap.xmind',{required:true})+sets.map(s=>`<label class="mm-member-choice"><input type="checkbox" name="set-${s.id}" ${s.id===this.study.current.id?'checked':''}>${E(s.title)} · ${s.cardCount} 个主题</label>`).join('')+'<p class="dialog-note">每个学习集成为一个画布。原文回源保存为链接文字；商业版本中的专有样式与交互需在目标应用中核对。</p>',submit:'导出',onSubmit:async v=>{const setIds=Object.keys(v).filter(k=>k.startsWith('set-')).map(k=>k.slice(4));if(!setIds.length)throw Error('至少选择一个学习集。');const result=await api('study.mindmap.xmind.export',{setIds,expectedRevisions:Object.fromEntries(sets.filter(s=>setIds.includes(s.id)).map(s=>[s.id,s.revision])),path:v.path});toast(`已导出 ${result.sheets} 个画布：${result.path}${result.warnings.length?'；'+result.warnings.length+' 项兼容性提示':''}`);}});})();}
}
