import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../../..'),require=createRequire(import.meta.url),{_electron:electron,expect}=require('@playwright/test'),run=promisify(execFile),temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'ac-connector-ui-'))),control=path.join(temp,'fixture');fs.mkdirSync(control);fs.writeFileSync(path.join(control,'release-all'),'');
const env={...process.env,AGENTS_COMPANY_HOME:path.join(temp,'state'),AGENTS_COMPANY_PROJECTS:path.join(temp,'projects'),AGENTS_COMPANY_WORKSPACES:path.join(temp,'work'),AGENTS_COMPANY_HIDDEN:'1',AGENTS_COMPANY_WIDTH:'1540',AGENTS_COMPANY_HEIGHT:'1050',CODEX_BIN:path.join(root,'Infra/src/test/fixtures/initialization-codex.cjs'),CODEX_HOME:path.join(temp,'codex'),AC_INIT_FIXTURE:control};delete env.ELECTRON_RUN_AS_NODE;for(const key of ['AGENTS_COMPANY_TOKEN','AGENTS_COMPANY_TOKEN_FILE','AGENTS_COMPANY_SOCKET','AGENTS_COMPANY_PORT','AGENTS_COMPANY_EMPLOYEE'])delete env[key];
const app=await electron.launch({executablePath:process.env.AGENTS_COMPANY_TEST_APP||require('electron'),args:process.env.AGENTS_COMPANY_TEST_APP?['--disable-gpu']:[root,'--disable-gpu'],env}),page=await app.firstWindow();page.setDefaultTimeout(12000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
const call=async(token,...args)=>{const result=JSON.parse((await run(process.execPath,[root+'/Infra/src/cli/agents',...args,'--json'],{env:{...env,...(token?{AGENTS_COMPANY_TOKEN:token}:{})},timeout:30000,maxBuffer:8e6})).stdout);assert.ok(result.ok,result.error);return result.data},cli=(...args)=>call(null,...args);
const create=async(token,title,role)=>{const c=await call(token,'card','create','--title',title,'--group','Studio','--management-role',role,'--engine','codex','--model','gpt-6-luna','--effort','low');await expect.poll(async()=>(await cli('session','status','--employee',c.id))[0].initialization.status).toBe('ready');return c};
try{
 await page.locator('.infinite-canvas').waitFor();await cli('settings','set','--theme','white');await cli('group','add','Studio');const m=await create(null,'Manager','manager'),token=(await cli('auth','agent-token',m.id)).token,employees=[];for(let i=0;i<5;i++)employees.push(await create(token,'Employee '+(i+1),'employee'));
 await cli('room','bounds','Studio','--width','1660','--height','1050','--arrangement','free');await cli('card','place',m.id,'--x','700','--y','240','--snap','off');for(let i=0;i<5;i++)await cli('card','place',employees[i].id,'--x',String(30+i*320),'--y','650','--snap','off');await cli('room','bounds','Studio','--x','0','--y','0');await cli('canvas','set','--x','40','--y','20','--zoom','.77');
 const layout=()=>cli('office','layout'),connections=()=>layout().then(l=>l.connections);
 const routes=await connections();assert.equal(routes.length,5);for(const route of routes){assert.equal(route.status,'routed',JSON.stringify(route));assert.equal(route.points.at(-1).y,650);assert.equal(route.points.at(-1).x,30+employees.findIndex(e=>e.id===route.employeeId)*320+95)}
 const e=employees[0],line=page.locator(`[data-employee="${e.id}"] .management-line-hit`).first();await line.waitFor();const clickBox=await line.boundingBox(),click={x:clickBox.x+clickBox.width/2,y:clickBox.y+clickBox.height/2};await page.mouse.click(click.x,click.y);await expect(page.getByLabel('连接点设置',{exact:true})).toBeVisible();await page.getByRole('button',{name:'展开连线设置'}).click();await expect(page.locator('.connector-handle')).toHaveCount(2);await expect(page.locator('.connector-pin-hit')).toHaveCount(48);for(const end of ['source','target'])for(const side of ['top','right','bottom','left'])await expect(page.locator(`.connector-pin-group[data-end="${end}"] .connector-pin-hit[data-side="${side}"]`)).toHaveCount(side==='top'||side==='bottom'?7:5);
 const world=async p=>page.locator('.canvas-world').evaluate((el,p)=>{const r=el.getBoundingClientRect(),matrix=new DOMMatrix(getComputedStyle(el).transform);return {x:r.x+p.x*matrix.a,y:r.y+p.y*matrix.d}},p);
 const drag=async(end,p)=>{await expect(page.getByRole('button',{name:'应用',exact:true})).toBeEnabled();const handle=page.locator(`.connector-handle[data-end="${end}"]`),b=await handle.boundingBox(),to=await world(p);await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(to.x,to.y,{steps:12});await page.mouse.up()};
 await drag('target',{x:220,y:825});const args=['--manager',m.id,'--employee',e.id];await expect.poll(async()=>(await cli('connector','get',...args)).target).toEqual({side:'right',offset:.7});
 await drag('source',{x:700,y:415});await expect.poll(async()=>(await cli('connector','get',...args)).source).toEqual({side:'left',offset:.7});
 await cli('card','place',e.id,'--x','90','--y','700','--snap','off');await expect.poll(async()=>{const r=(await connections()).find(r=>r.employeeId===e.id);return r.points.at(-1)}).toEqual({x:280,y:875});
 await page.getByRole('button',{name:'恢复自动',exact:true}).click();await expect.poll(async()=>(await cli('connector','get',...args)).target).toEqual({side:'auto'});await expect.poll(async()=>{const r=(await connections()).find(r=>r.employeeId===e.id);return r.points.at(-1)}).toEqual({x:185,y:700});
 await page.getByRole('button',{name:'起点位置',exact:true}).click();await page.getByRole('option',{name:'脚下 / 下方',exact:true}).click();await page.getByRole('button',{name:'应用',exact:true}).click();await expect.poll(async()=>(await cli('connector','get',...args)).source).toEqual({side:'bottom',offset:.5});await expect(page.getByRole('button',{name:'恢复自动',exact:true})).toBeEnabled();await page.getByRole('button',{name:'恢复自动',exact:true}).click();await expect.poll(async()=>(await cli('connector','get',...args)).source).toEqual({side:'auto'});
 const handleWidth=(await page.locator('.connector-handle[data-end="source"]').boundingBox()).width;assert.ok(handleWidth>=14);
 for(const zoom of [.77,.45]){
  await cli('canvas','set','--x','40','--y','20','--zoom',String(zoom));await expect(page.locator('.infinite-canvas')).toHaveAttribute('data-zoom',zoom.toFixed(3));
  const dimensions=await page.locator('.connector-handle[data-end="source"]').boundingBox();assert.ok(Math.abs(dimensions.width-handleWidth)<.2,'handle must keep its screen size across canvas zoom');
  for(const end of ['source','target'])for(const side of ['top','right','bottom','left'])for(const offset of (side==='top'||side==='bottom'?[0,.1,.3,.5,.7,.9,1]:[.1,.3,.5,.7,.9])){
   await expect(page.getByRole('button',{name:'应用',exact:true})).toBeEnabled();const pin=page.locator(`.connector-pin-group[data-end="${end}"] .connector-pin-hit[data-side="${side}"][data-offset="${offset}"]`),box=await pin.boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);
   await expect.poll(async()=>(await cli('connector','get',...args))[end]).toEqual({side,offset});
  }
 }
 await page.getByRole('button',{name:'恢复自动',exact:true}).click();await expect.poll(async()=>(await cli('connector','get',...args)).target).toEqual({side:'auto'});
 await cli('canvas','set','--x','40','--y','20','--zoom','.77');await expect(page.locator('.infinite-canvas')).toHaveAttribute('data-zoom','0.770');await expect(page.getByRole('button',{name:'应用',exact:true})).toBeEnabled();await page.screenshot({path:root+'/.aexus/artifacts/connector-pins-ui.png',animations:'disabled'});
 // Both frame outlines use the exact full-size employee rectangle, including corner pins.
 for(const [end,id] of [['source',m.id],['target',e.id]]){
  const actor=await page.locator(`[data-card-id="${id}"]`).boundingBox(),frame=await page.locator(`.connector-pin-group[data-end="${end}"] .connector-boundary`).evaluate(el=>{const b=el.getBBox(),m=el.getScreenCTM(),p=new DOMPoint(b.x,b.y).matrixTransform(m);return {x:p.x,y:p.y,width:b.width*m.a,height:b.height*m.d}})
  for(const key of ['x','y','width','height'])assert.ok(Math.abs(actor[key]-frame[key])<.2,`${end} ${key} matches employee frame: ${JSON.stringify({actor,frame})}`)
 }
 const selected=page.locator('.management-connection[data-selected=true]')
 const selectLine=async()=>{const b=await line.boundingBox();await page.mouse.click(b.x+b.width/2,b.y+b.height/2);await expect(selected).toHaveCount(1)}
 // A settings preview is discarded on empty-room click and does not silently change saved anchors.
 await page.getByRole('button',{name:'起点位置',exact:true}).click();await page.getByRole('option',{name:'右侧',exact:true}).click()
 const emptyRoom=await world({x:400,y:200});await page.mouse.click(emptyRoom.x,emptyRoom.y)
 await expect(page.getByLabel('连接点设置',{exact:true})).toHaveCount(0);await expect(page.locator('.connector-handles')).toHaveCount(0);await expect(selected).toHaveCount(0)
 assert.deepEqual((await cli('connector','get',...args)).source,{side:'auto'})
 await selectLine();await page.getByRole('button',{name:'展开连线设置'}).click();await expect(page.getByRole('button',{name:'起点位置',exact:true})).toContainText('自动')
 const canvas=await page.locator('.infinite-canvas').boundingBox();await page.mouse.click(canvas.x+canvas.width-24,canvas.y+canvas.height-90)
 await expect(selected).toHaveCount(0);await expect(page.locator('.connector-handles')).toHaveCount(0);await expect(page.getByLabel('连接点设置',{exact:true})).toHaveCount(0)
 await selectLine()
 await page.getByRole('button',{name:'关闭连接点设置'}).click();await expect(page.getByLabel('连接点设置',{exact:true})).toHaveCount(0);
 await cli('card','place',e.id,'--x','30','--y','650','--snap','off');await expect.poll(async()=>{const box=await page.locator(`[data-card-id="${e.id}"]`).evaluate(el=>({x:el.parentElement.style.left,y:el.parentElement.style.top}));return box}).toEqual({x:'30px',y:'650px'});fs.mkdirSync(root+'/artifacts',{recursive:true});await page.screenshot({path:root+'/.aexus/artifacts/connector-head-ui.png',animations:'disabled'});
 assert.deepEqual(errors,[]);assert.ok(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(w=>!w.isVisible())));console.log('PASS hidden UI: 48 interactive pins including four corners per employee; 96 real point clicks at two zooms; constant-size handles; both ends snap while dragged; matching actor and connector frames; room/canvas blank clicks clear selection and preview; CLI persistence, movement and reset; hidden windows only')
}catch(error){await page.screenshot({path:root+'/.aexus/artifacts/connector-ui-error.png'}).catch(()=>{});throw error}finally{await app.close();fs.rmSync(temp,{recursive:true,force:true})}
