import {createReady,readyEmployee,acceptedMessage} from './fixtures/ui-contracts.mjs'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {_electron as electron,expect} from '@playwright/test'
const root=path.resolve(import.meta.dirname,'../../..'),require=createRequire(import.meta.url),temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'ac-language-ui-'))),control=path.join(temp,'fixture'),out=path.join(root,'.aexus/artifacts/interface-language');fs.mkdirSync(control);fs.writeFileSync(path.join(control,'release-all'),'');fs.mkdirSync(out,{recursive:true})
const env={...process.env,AGENTS_COMPANY_HOME:path.join(temp,'state'),AGENTS_COMPANY_PROJECTS:path.join(temp,'projects'),AGENTS_COMPANY_WORKSPACES:path.join(temp,'work'),AGENTS_COMPANY_HIDDEN:'1',AGENTS_COMPANY_WIDTH:'1440',AGENTS_COMPANY_HEIGHT:'1000',CODEX_BIN:path.join(root,'Infra/src/test/fixtures/initialization-codex.cjs'),CODEX_HOME:path.join(temp,'codex'),AC_INIT_FIXTURE:control}
for(const key of Object.keys(env))if(key.startsWith('AGENTS_COMPANY_TOKEN')||['ELECTRON_RUN_AS_NODE','AGENTS_COMPANY_EMPLOYEE','AGENTS_COMPANY_SOCKET','AGENTS_COMPANY_PORT','AGENTS_COMPANY_URL','AGENTS_COMPANY_CLIENT','AGENTS_COMPANY_WEB_URL'].includes(key))delete env[key]
const app=await electron.launch({executablePath:process.env.AGENTS_COMPANY_TEST_APP||require('electron'),args:process.env.AGENTS_COMPANY_TEST_APP?[]:[root],env}),page=await app.firstWindow(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message))
const call=(cmd,args={})=>page.evaluate(([cmd,args])=>window.agents.call(cmd,args),[cmd,args])
try{
 await page.locator('.infinite-canvas').waitFor();await call('settings.set',{theme:'white'});await call('group.add',{name:'Inbox'});const a=await createReady(call,{title:'Messages',group:'Inbox',engine:'codex',model:'gpt-6-luna',avatar:'fate-saber-chibi'});const body='Messages / Save / 你好。 Keep this original text.'
 fs.writeFileSync(path.join(control,a.id+'.reply.txt'),body);await call('session.send',{employee:a.id,text:'原始消息 · Do not translate.'});await expect.poll(async()=>(await call('session.status',{employee:a.id}))[0].busy).toBe(false)
 const initial=(await call('session.transcript',{id:a.id})).items,before=(await call('session.list')).sessions
 const card=page.locator(`.employee[data-card-id="${a.id}"]`);await expect(card.locator('.badge-location small')).toHaveText('Execution location');await expect(card.locator('.badge-workspace small')).toHaveText('Work environment');await expect(card.locator('.badge-location')).toHaveAttribute('title','Execution location: Local (Core host)');await expect(card).toHaveAttribute('aria-label',/^Open conversation with Messages · /)
 await page.getByRole('button',{name:'Messages',exact:true}).click();await page.getByRole('button',{name:'Message Messages',exact:true}).click();await expect(page.locator('.transcript')).toContainText(body)
 await page.getByRole('button',{name:'Application settings',exact:true}).click();const settings=page.getByRole('dialog',{name:'Application settings',exact:true});await expect(settings.locator('select[name=language]')).toHaveValue('en')
 await settings.getByRole('button',{name:'Interface language',exact:true}).click();await page.getByRole('option',{name:'简体中文',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');await expect(page.getByRole('button',{name:'公司视图',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'消息',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'计划',exact:true})).toBeVisible();await expect(page.getByRole('dialog',{name:'应用设置',exact:true})).toContainText('界面语言')
 await page.screenshot({animations:'disabled',path:path.join(out,'settings-zh.png')});await page.getByRole('button',{name:'关闭设置',exact:true}).click();await expect(page.locator('.message-thread-header')).toContainText('Messages');await expect(page.locator('.message-thread-header')).toContainText('就绪');await expect(page.locator('.transcript')).toContainText(body);await expect(page.locator('.message-date')).toContainText('今天');await expect(page.getByRole('textbox',{name:'搜索会话',exact:true})).toBeVisible()
 await page.locator('.turn.assistant').hover();await page.locator('.turn.assistant').getByRole('button',{name:'更多消息操作',exact:true}).click();await expect(page.getByRole('menu',{name:'消息选项'})).toBeVisible();await expect(page.getByRole('menuitem',{name:'转发消息',exact:true})).toBeVisible();await page.keyboard.press('Escape')
 await page.locator('.turn.assistant').hover();await page.locator('.turn.assistant').getByRole('button',{name:'收藏消息',exact:true}).click();await page.getByRole('button',{name:'收藏消息',exact:true}).first().click();await expect(page.locator('.message-library [role=status]')).toHaveText('1 条消息');await page.getByRole('button',{name:'关闭消息资料栏'}).click()
 await page.getByRole('button',{name:'插入表情',exact:true}).click();await page.getByRole('textbox',{name:'搜索表情'}).fill('启动');await page.getByRole('button',{name:'插入 火箭 🚀',exact:true}).click();await expect(page.locator('.composer textarea')).toHaveValue('🚀');await page.locator('.composer textarea').fill('')
 const group=await call('chat.create',{name:'Saved messages',members:[a.id]});await page.getByRole('button',{name:'打开群聊 Saved messages',exact:true}).click();await expect(page.locator('.group-title')).toContainText('Saved messages');const groupInput=page.getByRole('textbox',{name:'群聊消息',exact:true});await groupInput.fill('@所有');await page.getByRole('option',{name:/所有成员/}).click();await expect(page.locator('.group-recipient-chips')).toContainText('@所有成员');await groupInput.fill('保留中文草稿');await page.getByRole('button',{name:'与 Messages 对话',exact:true}).click();assert.equal((await call('messenger.state')).drafts['group:'+group.id].mentions,'all')
 await page.screenshot({animations:'disabled',path:path.join(out,'messages-zh.png')});await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','zh-CN');await expect(page.getByRole('button',{name:'消息',exact:true})).toBeVisible();await expect(page.locator('.transcript')).toContainText(body)
 await page.getByRole('button',{name:'计划',exact:true}).click();await expect(page.locator('.plan-heading')).toContainText('在同一张任务数据库中管理计划、排期和结果。');await expect(page.getByRole('button',{name:'新建计划',exact:true}).first()).toBeVisible();await page.screenshot({animations:'disabled',path:path.join(out,'plan-zh.png')});await page.getByRole('button',{name:'新建计划',exact:true}).first().click();const plan=page.getByRole('dialog',{name:'新建计划',exact:true});await plan.locator('input[name=plan-name]').fill('Today 原始任务');await plan.locator('select[name=plan-employee]').selectOption(a.id);await plan.locator('textarea[name=plan-prompt]').fill('Messages 原始指令');await plan.locator('select[name=plan-mode]').selectOption('weekly');await plan.getByText('次数限制、工作时段与模型覆盖',{exact:true}).click();await plan.locator('select[name=plan-effort]').selectOption('high');await expect(plan.locator('select[name=plan-effort]')).toHaveValue('high');await plan.getByLabel('启用自动调度',{exact:true}).uncheck();await plan.getByRole('button',{name:'创建计划',exact:true}).click();const jobs=await call('schedule.list');assert.equal(jobs[0].name,'Today 原始任务');assert.equal(jobs[0].action.prompt,'Messages 原始指令');assert.equal(jobs[0].action.effort,'high');assert.equal(jobs[0].enabled,false)
 await page.getByRole('button',{name:'公司视图',exact:true}).click();await expect(page.locator('[data-department="Inbox"]')).toBeVisible();await expect(card.locator('.badge-location small')).toHaveText('运行位置');await expect(card.locator('.badge-workspace small')).toHaveText('工作环境');await expect(card.locator('.badge-location')).toHaveAttribute('title','运行位置：Core 本地');await expect(card).toHaveAttribute('aria-label',/^打开 Messages 的会话 · /);await page.getByRole('button',{name:'添加员工',exact:true}).click();await expect(page.getByRole('dialog',{name:'员工资料',exact:true})).toBeVisible();await expect(page.locator('input[name=title]')).toBeVisible();await page.getByRole('button',{name:'关闭面板',exact:true}).click()
 await page.getByRole('button',{name:'应用设置',exact:true}).click();await page.getByRole('dialog',{name:'应用设置',exact:true}).getByRole('button',{name:'界面语言',exact:true}).click();await page.getByRole('option',{name:'English',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.getByRole('button',{name:'Close settings',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close settings',exact:true}).click();await expect(card.locator('.badge-location small')).toHaveText('Execution location');await expect(card.locator('.badge-workspace small')).toHaveText('Work environment');await page.getByRole('button',{name:'Messages',exact:true}).click();await page.getByRole('button',{name:'Message Messages',exact:true}).click();await expect(page.locator('.message-date')).toContainText('Today');await page.screenshot({animations:'disabled',path:path.join(out,'messages-en.png')})
 assert.deepEqual((await call('session.transcript',{id:a.id})).items,initial);assert.deepEqual((await call('session.list')).sessions,before);assert.equal((await call('settings.get')).language,'en');assert.deepEqual(errors,[]);assert.ok(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(window=>!window.isVisible())))
 console.log('PASS bilingual desktop: settings selector switches navigation/messages/menus/emoji/Plan/forms immediately; Chinese survives reload; English switches back; dates and accessible labels follow locale; user names, message content and employee state remain identical')
}catch(error){await page.screenshot({animations:'disabled',path:path.join(out,'failure.png')}).catch(()=>{});throw error}finally{await app.close();fs.rmSync(temp,{recursive:true,force:true,maxRetries:10,retryDelay:100})}
