import { retireRootInstructions,provisionWorkspace } from './workspace-provision'
import { writeWindowsCompanyLauncher,writeWindowsPluginLauncher } from './windows-launchers'
import { applicationRoot } from '../resources'
import { APP_HOME } from '../../shared/protocol'
import fs from 'node:fs'
import path from 'node:path'
import { requirePlugin,pluginFile } from './registry'
import { employeeSettings,type TeamSettings,type Store,type StoredSession } from '../../shared/types'
import { readStore } from '../store'
import { employeeRoot } from '../workspaces'
import { ensureApiDocuments } from '../api-documents'
import { hasGlobalRole,assertManagementKind } from '../../shared/management'
import { rolePolicy,roleDescription } from '../../shared/roles'
export {provisionWorkspace} from './workspace-provision'

const quote=(text:string)=>`'${text.replace(/'/g,"'\\''")}'`
export const ROUTER_PROMPT='你是 Aexus 的 Agent。使用只读工具 agents_company_documentation：首次进入及职位变化后以 operation="identity" 获取真实身份、职位职责与工作范围，再以 operation="index" 读取共享工具目录。按当前任务用 document 或 describe 读取所需的 Core 与插件 API，不要一次加载整套手册。Company、Messages、Plan 是 Core 视图；其他工具需按已安装插件目录查询，不能与 Plan 混淆。文档对所有员工开放，执行权限仍由 Core 校验。按身份中的 roleDescription 行动。Secretary 是应用管理秘书：帮助用户操作 Aexus 及插件、组织和委派；具体业务工作交给其他员工。正式工作可用 agents_company_api 的 command/args 直接调用已授权的 Core API，Plan 操作先调用 plan.query 获取真实任务 ID、时间、目标角色和 allowedActions。写操作按原生权限批准，完成后回读核验；不要直接改宿主状态。'

function safeWrite(root:string,file:string,content:string,executable=false){
 if(fs.existsSync(file)&&fs.lstatSync(file).isSymbolicLink())throw Error('Cannot replace a bootstrap symlink')
 let parent=path.dirname(file);while(!fs.existsSync(parent))parent=path.dirname(parent)
 const actual=fs.realpathSync(parent)
 if(actual!==root&&!actual.startsWith(root+path.sep))throw Error('Bootstrap path points outside its runtime root')
 fs.mkdirSync(path.dirname(file),{recursive:true})
 if(fs.existsSync(file)&&fs.readFileSync(file,'utf8')===content)return
 fs.writeFileSync(file,content,{mode:executable?0o755:0o644});if(executable)fs.chmodSync(file,0o755)
}
/** Runtime launchers are not copied into an employee's working documents. */
export function ensureCompanyLauncher(){
 fs.mkdirSync(APP_HOME,{recursive:true});const root=fs.realpathSync(APP_HOME),directory=path.join(root,'cli'),cli=path.join(applicationRoot(),'Infra/src/cli/agents')
 writeWindowsCompanyLauncher(root,directory,cli,safeWrite)
 safeWrite(root,path.join(directory,'bin','agents'),`#!/bin/sh
# Generated by Aexus; uses only the identity assigned to this process.
if [ -z "$AGENTS_COMPANY_TOKEN_FILE" ] && [ -z "$AGENTS_COMPANY_TOKEN" ]; then
  echo 'Agent identity missing; reopen this employee in Aexus.' >&2; exit 2
fi
exec env ELECTRON_RUN_AS_NODE=1 ${quote(process.execPath)} ${quote(cli)} "$@"
`,true)
 return path.join(directory,'bin','agents'+(process.platform==='win32'?'.cmd':''))
}

/** Exactly one routing prompt, independent of role, team, plugin and employee identity. */
export function employeeInstructions(card:StoredSession,store:Store,_cli?:string){assertManagementKind(card,hasGlobalRole(store.access,card),employeeSettings(store,card).mode==='cloud');return ROUTER_PROMPT}

/** Refresh the authenticated role on each formal turn without expanding the common bootstrap. */
export function employeeRolePrompt(card:StoredSession,text:string){return '[Aexus role]\n'+JSON.stringify({employeeId:card.id,managementRole:card.managementRole??'employee',...(rolePolicy(card.managementRole).appAdministrator?{responsibility:roleDescription(card.managementRole)}:{})})+'\n\n'+text}

export function ensureEmployeeBootstrap(card:StoredSession,store=readStore()){
 const settings=employeeSettings(store,card),root=employeeRoot(store,card)
 if(!root)throw Error('Employee Team has no working directory')
 const instructions=employeeInstructions(card,store)
 const documentation=ensureApiDocuments(),launcher=ensureCompanyLauncher()
 if(settings.mode!=='cloud'){
  const cwd=fs.realpathSync(card.cwd);retireRootInstructions(cwd)
  if(settings.mode==='work'){
   const plugin=requirePlugin(settings.pluginId!),runtimeRoot=fs.realpathSync(APP_HOME),directory=path.join(runtimeRoot,'agent-access',card.id),cli=pluginFile(plugin.directory,plugin.cli)
   writeWindowsPluginLauncher(cwd,directory,root,plugin.id,cli,(ignored,file,content,executable)=>safeWrite(runtimeRoot,file,content,executable))
   safeWrite(runtimeRoot,path.join(directory,'bin',plugin.id),`#!/bin/sh
# Generated by Aexus; bound to this employee workspace.
for argument in "$@"; do
  case "$argument" in --workspace|--workspace=*) echo 'Workspace is already bound to this employee.' >&2; exit 2 ;; esac
done
export AGENTS_WORKSPACE=${quote(cwd)}
export AGENTS_TEAM_ROOT=${quote(root)}
export AGENTS_COMPANY_PLUGIN_RPC=${quote(path.join(directory,'ipc',plugin.id))}
exec env ELECTRON_RUN_AS_NODE=1 ${quote(process.execPath)} ${quote(cli)} --workspace ${quote(cwd)} "$@"
`,true)
  }
 }
 return {mode:settings.mode,workspace:card.cwd,teamRoot:root,plugins:settings.mode==='work'?[settings.pluginId!]:[],instructions,documentation,launcher}
}

export function provisionEmployee(cwd:string,root:string,settings:TeamSettings){
 const store=readStore(),cards=store.sessions.filter(card=>card.cwd===cwd&&!card.deleting)
 if(cards.length){for(const card of cards)ensureEmployeeBootstrap(card,store);return {mode:settings.mode,workspace:cwd,teamRoot:root,plugins:settings.mode==='work'?[settings.pluginId!]:[]}}
 return settings.mode==='cloud'?{mode:settings.mode,workspace:cwd,teamRoot:root,plugins:[]}:provisionWorkspace(cwd,settings,root)
}

export function initializationPrompt(_card:StoredSession,_store:Store){
 return '[Aexus private initialization]\n\n'+ROUTER_PROMPT+'\n\n现在只做初始化：实际调用文档工具读取 identity 和 index，不执行写操作，不联系其他员工，不运行工作任务，不读取整册手册。确认身份与目录已成功读取后，最终只返回 OK；读取失败则如实报告错误，不要假装完成。'
}
