import {requireConversation,conversationMuted,controlChanged} from './conversation-policy'
import {syncEmployeeSources} from './channel-engines'
import {CONVERSATION_CONTROL_GUIDANCE,type NoticeReceipt} from '../shared/conversation-controls'
import {sharedAttachments,workspaceForMember} from './conversation-workspaces'
import {sharedUploadNotice} from '../shared/conversation-workspaces'
import type {MessageSource} from './message-index'
import {SingleFlight} from './single-flight'
import {nextDelivery,routeRecipients} from './delivery'
import {createHash,randomUUID} from 'node:crypto'
import {one,all,run,transaction,changed,liveChannelPost,projectChannelPost,revision,type Row} from './channel-store'
import {authorize,requestContext,operatorContext,withCaller,callerEmployee,delegationFor,validateDelegation,isAppAdministrator,requireAppAdministrator} from './authorization'
import {readStore} from './store'
import {taskViewId} from './task-view'
import {employeeReady} from '../shared/types'
import type {PrincipalRef,Delegation,RequestContext} from '../shared/management'
import type {ChannelMessage,ChannelHistory,ChannelTaskContext} from '../shared/channels'
import {emptyAgentPost,type ChatDelivery,type ChatAcknowledgmentPolicy} from '../shared/chat-groups'

const fields=(args:Record<string,any>,keys:string[])=>{for(const key of Object.keys(args))if(args[key]!==undefined&&!keys.includes(key))throw Error('Unknown channel discussion field: '+key)}
const key=(value:unknown,label:string)=>{if(typeof value!=='string'||!value.trim()||value!==value.trim())throw Error('Provide a valid '+label);return value}
const sameAuthor=(a:PrincipalRef,b:PrincipalRef)=>a.kind===b.kind&&(a.kind==='operator'||b.kind==='agent'&&a.employeeId===b.employeeId)
export const CHANNEL_DISCUSSION_POLICY={maxCharacters:2000,guidance:CONVERSATION_CONTROL_GUIDANCE+' News and messages reach current administrators as shared context. Mentions and user replies identify work targets. Publish within a received user or Secretary discussion using channel.message-post and exact IDs. Ordinary assistant output remains private; Core records reading receipts.'}
function channel(id:unknown){const row=one('SELECT * FROM channels WHERE id=?',key(id,'channel ID'));if(!row)throw Error('Unknown news channel');return row}
export function channelAdminIds(id:string){const row=channel(id),existing=new Set(readStore().sessions.filter(card=>!card.deleting).map(card=>card.id));return (JSON.parse(row.admin_ids) as string[]).filter(id=>existing.has(id))}
function readable(id:unknown,administrative=false){const row=channel(id),principal=requestContext().principal;if(principal.kind==='agent'&&!channelAdminIds(row.id).includes(principal.employeeId))throw Error('Not an administrator of this channel');return row}
export {readable as readChannelIdentity}
export function updateChannelAdmins(id:unknown,adminIds:unknown,expectedRevision?:number){requireConversation('channel:'+id,'admin');const row=channel(id);if(expectedRevision!==undefined&&expectedRevision!==row.revision)throw Error('Channel changed; reload before saving');if(!Array.isArray(adminIds)||adminIds.length>200||adminIds.some(id=>typeof id!=='string'))throw Error('Choose up to 200 existing employees as channel administrators');const ids=[...new Set<string>(adminIds)],store=readStore();for(const id of ids)if(!store.sessions.some(card=>card.id===id&&!card.deleting))throw Error('Unknown employee: '+id);run('UPDATE channels SET admin_ids=?,revision=revision+1,updated_at=? WHERE id=?',JSON.stringify(ids),Date.now(),row.id);return ids}
function delivery(row:Row):ChatDelivery{return {employeeId:row.employee_id,mode:row.mode,status:row.status,...(row.session_id?{sessionId:row.session_id}:{}),...(row.queue_id?{queueId:row.queue_id}:{}),...(row.task_id?{taskId:row.task_id}:{}),...(row.error?{error:row.error}:{}),...(row.delivered_at!==null?{deliveredAt:row.delivered_at}:{}),...(row.read_at!==null?{readAt:row.read_at}:{}),...(row.ack_message_id?{ackMessageId:row.ack_message_id}:{})}}
export function channelDeliveries(channelId:string,entryId:string){return all('SELECT * FROM channel_deliveries WHERE channel_id=? AND entry_id=? ORDER BY rowid',channelId,entryId).map(delivery)}
const attachmentRows=(id:string)=>JSON.parse(one('SELECT attachments FROM channel_message_attachments WHERE message_id=?',id)?.attachments??'[]') as NonNullable<ChannelMessage['attachments']>
function message(row:Row):ChannelMessage{const attachments=attachmentRows(row.id);const notice=one('SELECT metadata FROM channel_message_notices WHERE message_id=?',row.id);return {...(notice?{notice:JSON.parse(notice.metadata)}:{}),...(attachments.length?{attachments}:{}),id:row.id,channelId:row.channel_id,sequence:row.sequence,createdAt:row.created_at,author:JSON.parse(row.author),authorName:row.author_name,text:row.text,kind:row.kind,mentions:JSON.parse(row.mentions),...(row.reply_to?{replyTo:row.reply_to}:{}),...(row.request_id?{requestId:row.request_id}:{}),...(row.acknowledgment_of?{acknowledgmentOf:row.acknowledgment_of}:{}),deliveries:channelDeliveries(row.channel_id,row.id),clientMessageId:row.client_message_id,fingerprint:row.fingerprint}}
function messageRow(channelId:string,id:unknown){const row=one('SELECT * FROM channel_messages WHERE channel_id=? AND id=?',channelId,key(id,'message ID'));if(!row)throw Error('Unknown channel message');return row}
export function getChannelMessage(channelId:string,id:string){readable(channelId,true);return message(messageRow(channelId,id))}
export function queryChannelMessages(args:{channelId?:string;query?:string;offset?:number;limit?:number}={}){requireAppAdministrator();const where:string[]=[],values:any[]=[];if(args.channelId){channel(args.channelId);where.push('channel_id=?');values.push(args.channelId)}if(args.query){where.push("text LIKE ? ESCAPE '\\'");values.push('%'+args.query.replace(/[\\%_]/g,'\\$&')+'%')}const sql=where.length?' WHERE '+where.join(' AND '):'',total=Number(one('SELECT COUNT(*) AS count FROM channel_messages'+sql,...values)!.count),rows=all('SELECT * FROM channel_messages'+sql+' ORDER BY created_at DESC,channel_id ASC,id ASC LIMIT ? OFFSET ?',...values,args.limit??50,args.offset??0);return {messages:rows.map(message),total}}
/** Thin public projection for the shared search index: no delivery ledger or private data. */
export function channelMessageSources(channelId?:string):MessageSource[]{
 requireAppAdministrator();if(channelId)readable(channelId,true)
 const version=String(revision()),ids=channelId?[channelId]:all('SELECT id FROM channels').map(row=>String(row.id))
 return ids.map(id=>({id:'channel:'+id,version,read:()=>all('SELECT id,author,author_name,text,created_at FROM channel_messages WHERE channel_id=? ORDER BY sequence',id).map(row=>({conversation:'channel:'+id,id:row.id,author:row.author_name,authorIdentity:JSON.parse(row.author),role:JSON.parse(row.author).kind==='operator'?'user' as const:'assistant' as const,text:row.text,images:attachmentRows(row.id).filter(file=>file.kind==='image').map(file=>file.path),files:attachmentRows(row.id).filter(file=>file.kind==='file'),createdAt:row.created_at}))}))
}
export function channelHistory(args:Record<string,any>):ChannelHistory{authorize('channel.history');fields(args,['id','before','around','limit']);const row=readable(args.id,true),limit=args.limit??100;if(!Number.isInteger(limit)||limit<1||limit>100)throw Error('History limit must be 1–100');if(args.around!==undefined){if(args.before!==undefined)throw Error('Choose around or before');return {messages:[message(messageRow(row.id,args.around))],nextBefore:null}}const before=args.before??Number.MAX_SAFE_INTEGER;if(!Number.isSafeInteger(before)||before<1)throw Error('Invalid channel history cursor');const rows=all('SELECT * FROM channel_messages WHERE channel_id=? AND sequence<? ORDER BY sequence DESC LIMIT ?',row.id,before,limit+1),page=rows.slice(0,limit).reverse();return {messages:page.map(message),nextBefore:rows.length>limit?page[0].sequence:null}}
function entry(context:ChannelTaskContext){const row=channel(context.channelId);if(context.entryId.startsWith('np_')){const post=liveChannelPost(context.entryId);if(post.channel_id!==row.id)throw Error('News item belongs to another channel');return {kind:'news' as const,post:projectChannelPost(post)}}return {kind:'message' as const,message:message(messageRow(row.id,context.entryId))}}
export function channelAcknowledgmentPolicy(context:ChannelTaskContext,employeeId:string):ChatAcknowledgmentPolicy{
 if(!channelAdminIds(context.channelId).includes(employeeId))throw Error('Channel administrator assignment was revoked')
 const value=entry(context),row=one('SELECT * FROM channel_deliveries WHERE channel_id=? AND entry_id=? AND employee_id=?',context.channelId,context.entryId,employeeId);if(!row)throw Error('Only a frozen channel recipient can acknowledge this entry');const current=delivery(row)
 return {mode:current.mode??'awareness',required:'silent-only',acknowledged:current.readAt!==undefined,muted:conversationMuted('channel:'+context.channelId,employeeId)!==undefined,deliveredAt:current.deliveredAt,readAt:current.readAt,ackMessageId:current.ackMessageId}
}
function rootRequest(channelId:string,replyTo:string,employeeId:string){const parent=messageRow(channelId,replyTo),author=JSON.parse(parent.author) as PrincipalRef,root=author.kind==='operator'||parent.request_id===parent.id?parent:parent.request_id?messageRow(channelId,parent.request_id):undefined;if(!root||JSON.parse(root.author).kind!=='operator'&&root.request_id!==root.id||!one('SELECT 1 FROM channel_deliveries WHERE channel_id=? AND entry_id=? AND employee_id=?',channelId,root.id,employeeId))throw Error('A public administrator reply must belong to a user or Secretary discussion delivered to you');return root.id as string}
function acknowledge(context:ChannelTaskContext,employeeId:string,ackMessageId?:string){const policy=channelAcknowledgmentPolicy(context,employeeId),now=Date.now();if(policy.acknowledged&&policy.deliveredAt!==undefined&&(!ackMessageId||policy.ackMessageId))return {acknowledged:true,channelId:context.channelId,entryId:context.entryId,...delivery(one('SELECT * FROM channel_deliveries WHERE channel_id=? AND entry_id=? AND employee_id=?',context.channelId,context.entryId,employeeId)!)};run('UPDATE channel_deliveries SET delivered_at=COALESCE(delivered_at,?),read_at=COALESCE(read_at,?),ack_message_id=COALESCE(ack_message_id,?) WHERE channel_id=? AND entry_id=? AND employee_id=?',now,now,ackMessageId??null,context.channelId,context.entryId,employeeId);changed(context.entryId.startsWith('np_')?'posts':'messages',{channelIds:[context.channelId],...(context.entryId.startsWith('np_')?{postIds:[context.entryId]}:{messageIds:[context.entryId]})});const value=channelDeliveries(context.channelId,context.entryId).find(item=>item.employeeId===employeeId)!;return {acknowledged:true,channelId:context.channelId,entryId:context.entryId,...value}}
function freeze(channelId:string,entryId:string,kind:'news'|'message',recipients:string[],work:string[]=[]){for(const id of recipients)run("INSERT INTO channel_deliveries(channel_id,entry_id,kind,employee_id,mode,status) VALUES(?,?,?,?,?,'pending')",channelId,entryId,kind,id,work.includes(id)?'work':'awareness')}
export function recordChannelDelivery(employeeId:string,context:ChannelTaskContext,patch:Partial<ChatDelivery>,onlyPending=false){
 const row=one('SELECT * FROM channel_deliveries WHERE channel_id=? AND entry_id=? AND employee_id=?',context.channelId,context.entryId,employeeId);if(!row)return;if(onlyPending&&!['pending','routing'].includes(row.status))return
 const next=nextDelivery(delivery(row),patch,false,true);if(!next)return
 run('UPDATE channel_deliveries SET status=?,session_id=?,queue_id=?,task_id=?,error=?,delivered_at=?,read_at=?,ack_message_id=? WHERE channel_id=? AND entry_id=? AND employee_id=?',next.status,next.sessionId??null,next.queueId??null,next.taskId??null,next.error??null,next.deliveredAt??null,next.readAt??null,next.ackMessageId??null,context.channelId,context.entryId,employeeId)
 changed(row.kind==='news'?'posts':'messages',{channelIds:[context.channelId],...(row.kind==='news'?{postIds:[context.entryId]}:{messageIds:[context.entryId]})})
}
const routing=new SingleFlight<void>()
function route(context:ChannelTaskContext,caller:RequestContext,workScopes=new Map<string,{delegation:Delegation;viewId?:string}>()){
 const key=context.channelId+'/'+context.entryId
 return routing.run(key,()=>withCaller(caller,()=>routeRecipients({context,recipients:channelDeliveries(context.channelId,context.entryId).filter(target=>target.status==='pending'),concurrency:1,
  scope:target=>{const accepted=workScopes.get(target.employeeId);return {delegation:target.mode==='work'?accepted!.delegation:{requestedBy:caller.principal,requestId:caller.requestId,credentialHash:caller.credentialHash,channelNotice:{...context,employeeId:target.employeeId}},viewId:accepted?.viewId}},
  validate:(id,delegation)=>{validateDelegation(delegation,id);channelAcknowledgmentPolicy(context,id)},
  input:()=>{const value=entry(context);return {text:value.kind==='news'?'[Channel news reference '+context.entryId+']':sharedUploadNotice(value.message.text,value.message.attachments)}},
  update:(id,patch,onlyPending)=>recordChannelDelivery(id,context,patch,onlyPending)
 })))
}
/** Called inside the news insert transaction; only thin references survive in the delivery ledger. */
export function freezeChannelNews(channelId:string,postId:string,publisherId?:string){freeze(channelId,postId,'news',channelAdminIds(channelId).filter(id=>id!==publisherId))}
export function deliverChannelNews(channelId:string,entryId:string){const caller=operatorContext();caller.requestId='channel-news-'+entryId;void route({channelId,entryId},caller).catch(cause=>console.error('[Channel news delivery]',(cause as Error).message))}
function publishMessage(args:Record<string,any>,workTargets:string[],acknowledgment=false,administrativeSend=false){
 const row=readable(args.id),principal=requestContext().principal,attachments=sharedAttachments('channel:'+row.id,args.images,args.files),text=args.text??'';if(principal.kind==='agent'&&emptyAgentPost(text))throw Error('Public replies require nonempty text');if(typeof text!=='string'||text!==text.trim()||!text&&!attachments.length||Array.from(text).length>(principal.kind==='agent'?2000:16000))throw Error('Provide a concise channel message')
 if(principal.kind==='agent'&&conversationMuted('channel:'+row.id,principal.employeeId)!==undefined)throw Error('You are muted in this channel')
 const kind=args.kind??(principal.kind==='operator'||administrativeSend?'message':'summary');if(!['message','summary','decision','blocker','question','result'].includes(kind)||kind==='message'&&principal.kind!=='operator'&&!administrativeSend)throw Error('Invalid channel message kind')
 const clientMessageId=args.clientMessageId===undefined?requestContext().requestId:key(args.clientMessageId,'client message ID');if(clientMessageId.length>160)throw Error('Client message ID too long')
 const mentions=args.mentions==='all'?channelAdminIds(row.id):args.mentions??[],fingerprint=createHash('sha256').update(JSON.stringify([text,kind,args.mentions??[],args.replyTo??null,...(attachments.length?[attachments.map(file=>[file.path,file.bytes,file.kind])]:[])])).digest('hex'),prior=all('SELECT * FROM channel_messages WHERE channel_id=? AND client_message_id=?',row.id,clientMessageId).find(item=>sameAuthor(JSON.parse(item.author),principal));if(prior){if(prior.fingerprint!==fingerprint)throw Error('Client message ID already used with different content');return message(prior)}
 let requestId:string|undefined;if(principal.kind==='agent'&&!administrativeSend){if(!args.replyTo||args.replyTo.startsWith('np_'))throw Error('Administrators may reply only to a received user or Secretary discussion');requestId=rootRequest(row.id,args.replyTo,principal.employeeId)}else if(args.replyTo)entry({channelId:row.id,entryId:args.replyTo})
 const workScopes=new Map(workTargets.map(id=>[id,{delegation:delegationFor(id),viewId:taskViewId(id)}] as const)),id='cm_'+randomUUID(),sequence=Number(one('SELECT COALESCE(MAX(sequence),0)+1 AS value FROM channel_messages WHERE channel_id=?',row.id)!.value),now=Date.now(),recipients=channelAdminIds(row.id).filter(id=>principal.kind!=='agent'||id!==principal.employeeId)
 transaction(()=>{run('INSERT INTO channel_messages VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,row.id,sequence,now,JSON.stringify(principal),callerEmployee()?.title??'You',text,kind,JSON.stringify(mentions),args.replyTo??null,requestId??(principal.kind==='operator'||administrativeSend?id:null),acknowledgment?args.replyTo:null,clientMessageId,fingerprint);if(attachments.length)run('INSERT INTO channel_message_attachments VALUES(?,?)',id,JSON.stringify(attachments));freeze(row.id,id,'message',recipients,workTargets)})
 if(principal.kind==='agent'&&args.replyTo&&one('SELECT 1 FROM channel_deliveries WHERE channel_id=? AND entry_id=? AND employee_id=?',row.id,args.replyTo,principal.employeeId))acknowledge({channelId:row.id,entryId:args.replyTo},principal.employeeId,id)
 changed('messages',{channelIds:[row.id],messageIds:[id]});void route({channelId:row.id,entryId:id},requestContext(),workScopes).catch(cause=>console.error('[Channel discussion delivery]',(cause as Error).message));return message(messageRow(row.id,id))
}
export function sendChannelMessage(args:Record<string,any>){authorize('channel.message-send');requireAppAdministrator();fields(args,['id','text','mentions','replyTo','clientMessageId','images','files']);const row=readable(args.id),admins=channelAdminIds(row.id),mentions=args.mentions??[];if(mentions!=='all'&&(!Array.isArray(mentions)||mentions.some(id=>typeof id!=='string')))throw Error('Mentions must be administrator IDs or all');if(args.clientMessageId&&one("SELECT 1 FROM channel_messages WHERE channel_id=? AND client_message_id=? AND author=?",row.id,args.clientMessageId,JSON.stringify(requestContext().principal)))return publishMessage(args,[],false,true);const explicit=mentions==='all'?admins:[...new Set<string>(mentions)];for(const id of explicit)if(!admins.includes(id))throw Error('Mentioned employee is not a channel administrator');const parent=args.replyTo&&!args.replyTo.startsWith('np_')?messageRow(row.id,args.replyTo):undefined,author=parent?JSON.parse(parent.author) as PrincipalRef:undefined,targets=[...new Set([...explicit,...(author?.kind==='agent'&&admins.includes(author.employeeId)?[author.employeeId]:[])])];if(!targets.length)targets.push(...admins);for(const id of targets){const card=readStore().sessions.find(card=>card.id===id&&!card.deleting);if(!card||!employeeReady(card))throw Error('Channel administrator is not ready: '+id);delegationFor(id)}return publishMessage(args,targets,false,true)}
export function postChannelMessage(args:Record<string,any>,acknowledgment=false){authorize('channel.message-post');fields(args,['id','text','kind','replyTo','clientMessageId','images','files']);const row=readable(args.id),principal=requestContext().principal;if(args.text===null)throw Error('Null publication is not supported');return publishMessage(args,[],acknowledgment)}
const historyRoute=(channelId:string,beforeEntry?:string)=>({command:'channel.timeline',args:{id:channelId,...(beforeEntry?{beforeEntry}:{})},defaultLimit:20,maxLimit:100,kinds:['all','news','message']})
export function channelContext(args:Record<string,any>){authorize('channel.context');fields(args,['id','entryId']);const row=readable(args.id,true),principal=requestContext().principal,context=args.entryId?{channelId:row.id,entryId:key(args.entryId,'entry ID')}:undefined;return {...(principal.kind==='operator'||channelAdminIds(row.id).includes(principal.employeeId)?{workspace:workspaceForMember('channel:'+row.id,principal.kind==='agent'?principal.employeeId:undefined)}:{}),channel:{id:row.id,name:row.name,kind:row.kind,createdAt:row.created_at,updatedAt:row.updated_at,adminIds:channelAdminIds(row.id),revision:row.revision},...(context?{entry:entry(context),deliveries:channelDeliveries(row.id,context.entryId)}:{}),history:historyRoute(row.id,context?.entryId),recentMessages:all('SELECT * FROM channel_messages WHERE channel_id=? ORDER BY sequence DESC LIMIT 20',row.id).reverse().map(message),policy:CHANNEL_DISCUSSION_POLICY,...(context&&principal.kind==='agent'&&channelAdminIds(row.id).includes(principal.employeeId)&&one('SELECT 1 FROM channel_deliveries WHERE channel_id=? AND entry_id=? AND employee_id=?',row.id,context.entryId,principal.employeeId)?{acknowledgment:channelAcknowledgmentPolicy(context,principal.employeeId)}:{})}}
export function channelTaskPrompt(context:ChannelTaskContext,employeeId:string,delegation:Delegation|undefined,text:string,reading=false){
 if(!delegation)throw Error('Channel delivery authority is missing');validateDelegation(delegation,employeeId)
 const value=entry(context),policy=channelAcknowledgmentPolicy(context,employeeId),row=channel(context.channelId);let reply:unknown
 if(value.kind==='message'&&value.message.replyTo)reply=entry({channelId:context.channelId,entryId:value.message.replyTo})
 const base='[Channel context]\n'+JSON.stringify({conversationType:'channel',conversationId:row.id,channelId:row.id,channelName:row.name,entryId:context.entryId,mode:policy.mode,acknowledgment:policy,...(!reading?{history:historyRoute(row.id,context.entryId)}:{}),source:value.kind==='news'?value.post:{...value.message,text},...(reply?{reply}:{})})
 if(reading)return base
 return base+'\n\n'+CHANNEL_DISCUSSION_POLICY.guidance+'\n[Shared workspace]\n'+JSON.stringify(workspaceForMember('channel:'+row.id,employeeId))+'\nRead shared files with conversation.file; writes use your memberDirectory or personal Workspace. Context: agents channel context '+row.id+' --entry '+context.entryId+' --json. News: agents channel timeline '+row.id+' --kind news --before-entry '+context.entryId+' --limit 20 --json; paginate with --cursor NEXT_CURSOR. Publish with agents channel message-post '+row.id+' --reply-to '+context.entryId+' --text "Reply text" --json.'
}
export function recoverChannelDeliveries(){run("UPDATE channel_deliveries SET status='interrupted',error='Core restarted. Check the private conversation before retrying.' WHERE status IN ('routing','queued','running')");for(const row of all("SELECT DISTINCT channel_id,entry_id FROM channel_deliveries WHERE kind='news' AND status='pending'"))deliverChannelNews(row.channel_id,row.entry_id)}

export function syncConversationChannelMembers(id:string){syncEmployeeSources(id);changed('channels',{channelIds:[id]})}
export function publishChannelNotice(channelId:string,text:string,publisherId:string,notice:NoticeReceipt){
 requireConversation('channel:'+channelId,'admin',{kind:'agent',employeeId:publisherId})
 const id='cm_'+notice.occurrenceId,prior=one('SELECT * FROM channel_messages WHERE id=? AND channel_id=?',id,channelId);if(prior)return message(prior)
 const card=readStore().sessions.find(card=>card.id===publisherId&&!card.deleting)!,sequence=Number(one('SELECT COALESCE(MAX(sequence),0)+1 AS value FROM channel_messages WHERE channel_id=?',channelId)!.value)
 transaction(()=>{run('INSERT INTO channel_messages VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,channelId,sequence,Date.now(),JSON.stringify({kind:'agent',employeeId:publisherId}),card.title,text,'message','[]',null,null,null,notice.occurrenceId,createHash('sha256').update(text).digest('hex'));run('INSERT INTO channel_message_notices VALUES(?,?)',id,JSON.stringify(notice))})
 changed('messages',{channelIds:[channelId],messageIds:[id]});return message(messageRow(channelId,id))
}
