import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {api} from '../api'
import {Icon} from '../components/Icon'
import {useDialogFocus} from '../office/useDialogFocus'
import {translate as uiText,useI18n} from '../i18n'
import {useSurfaceMotion} from './surfaceMotion'
import {mediaTime,claimMedia,watchMedia} from './mediaPresentation'
import {VoiceCapture,type VoiceResult} from './voiceCapture'
type Status='requesting'|'recording'|'paused'|'stopping'|'review'|'error'
const errorText=(cause:unknown)=>{const name=(cause as Error)?.name;return name==='NotAllowedError'||name==='SecurityError'?'Microphone access was denied. Allow it in your browser or system settings, then retry.':name==='NotFoundError'?'No microphone was found. Connect one and retry.':name==='NotReadableError'?'The microphone is unavailable or in use by another application.':'Recording could not start. Check your microphone and retry.'}
function Waveform({peaks}:{peaks:number[]}){const count=64,values=Array.from({length:count},(_,index)=>{const start=Math.floor(index*peaks.length/count),end=Math.max(start+1,Math.floor((index+1)*peaks.length/count));return peaks.length?Math.max(...peaks.slice(start,end),0):0});return <div className="voice-waveform" aria-label={uiText('Recorded sound levels')}>{values.map((level,index)=><i key={index} style={{height:Math.max(3,Math.min(74,level*110))+'px'}}/>)}</div>}
function RecordingDialog({disabled,status,seconds,peaks,result,notice,error,onPause,onResume,onStop,onCancel,onUse,onRetry}:{disabled?:boolean;status:Status;seconds:number;peaks:number[];result:VoiceResult|null;notice:string;error:string;onPause:()=>void;onResume:()=>void;onStop:()=>void;onCancel:()=>void;onUse:()=>void;onRetry:()=>void}){
 useI18n();const surface=useSurfaceMotion<HTMLDivElement>('dialog'),preview=useRef<HTMLAudioElement>(null),preferred=useRef<HTMLButtonElement>(null),closeButton=useRef<HTMLButtonElement>(null),previousStatus=useRef<Status|null>(null),cancel=useRef(onCancel),[url,setUrl]=useState(''),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[previewError,setPreviewError]=useState(false)
 useDialogFocus('.voice-recorder-dialog',true)
 cancel.current=onCancel
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!event.isComposing){event.preventDefault();event.stopImmediatePropagation();cancel.current()}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[])
 useEffect(()=>{const changed=previousStatus.current!==status;previousStatus.current=status;const dialog=surface.current?.querySelector('.voice-recorder-dialog');if(!dialog||!changed&&dialog.contains(document.activeElement))return;const target=preferred.current&&!preferred.current.disabled?preferred.current:closeButton.current;target?.focus({preventScroll:true})},[status,disabled])
 useEffect(()=>{if(!result)return;const value=URL.createObjectURL(result.blob),audio=preview.current,off=audio?watchMedia(audio,()=>audio.pause()):()=>{};setUrl(value);return()=>{off();audio?.pause();audio?.removeAttribute('src');audio?.load();URL.revokeObjectURL(value)}},[result])
 return createPortal(<div ref={surface} className="voice-recorder-overlay"><div className="voice-recorder-backdrop"/><section className="voice-recorder-dialog" role="dialog" aria-modal="true" aria-label={uiText('Voice recording')}><header><div><span>{uiText('A MOMENT IN YOUR OWN WORDS')}</span><h2>{uiText(status==='review'?'Your voice note':'Voice recording')}</h2></div><button ref={closeButton} aria-label={uiText('Discard recording')} title={uiText('Discard recording')} onClick={onCancel}><Icon name="close"/></button></header>
  <div className={'voice-recorder-body '+status}><span className="voice-recorder-emblem"><Icon name={status==='review'?'check':status==='paused'?'debug-pause':'mic'}/></span><div className="voice-recorder-status" role="status"><i/>{uiText(status==='recording'?'Recording':status==='paused'?'Microphone off · Paused':status==='requesting'?'Waiting for microphone permission…':status==='stopping'?'Finishing recording…':status==='review'?'Microphone off · Ready to review':'Microphone unavailable')}</div><output className="voice-recorder-time" aria-label={uiText('Recording duration')}>{mediaTime(seconds)}</output><Waveform peaks={peaks}/>{notice&&<p className="voice-recorder-notice">{uiText(notice)}</p>}{error&&<p className="voice-recorder-error" role="alert">{uiText(error)}</p>}
   {status==='review'&&result&&<div className="voice-recorder-preview" style={{'--played':(result.seconds?position/result.seconds*100:0)+'%'} as React.CSSProperties}><audio ref={preview} src={url||undefined} preload="metadata" data-message-media onError={()=>setPreviewError(true)} onTimeUpdate={()=>setPosition(preview.current?.currentTime??0)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/><button ref={preferred} aria-label={uiText(playing?'Pause recording preview':'Play recording preview')} onClick={()=>{const audio=preview.current;if(!audio)return;if(playing)audio.pause();else{setPreviewError(false);claimMedia(audio);void audio.play().catch(cause=>{if(audio.isConnected&&cause.name!=='AbortError')setPreviewError(true)})}}}><Icon name={playing?'debug-pause':'play'}/></button><input aria-label={uiText('Recording preview position')} type="range" min={0} max={result.seconds||1} step={.05} value={position} onChange={event=>{if(preview.current)preview.current.currentTime=Number(event.target.value);setPosition(Number(event.target.value))}}/><span>{mediaTime(position)} / {mediaTime(result.seconds)}</span></div>}
   {previewError&&<p className="voice-recorder-error" role="alert">{uiText('Recording preview could not play. Try again.')}</p>}
   <p className="voice-recorder-caption">{uiText(status==='review'?'Listen first. Add it to your draft when you are ready.':'Up to 10 minutes. Your microphone is off whenever recording is paused or finished.')}</p>
  </div><footer><button className="voice-discard" onClick={onCancel}><Icon name="trash"/>{uiText('Discard')}</button><div>{status==='recording'&&<><button ref={preferred} onClick={onPause}><Icon name="debug-pause"/>{uiText('Pause recording')}</button><button className="primary" onClick={onStop}><Icon name="primitive-square"/>{uiText('Finish recording')}</button></>}{status==='paused'&&<><button ref={preferred} disabled={disabled} onClick={onResume}><Icon name="mic"/>{uiText('Resume recording')}</button><button className="primary" onClick={onStop}>{uiText('Finish recording')}</button></>}{status==='review'&&<button className="primary" disabled={disabled} onClick={onUse}><Icon name="add"/>{uiText('Add recording to draft')}</button>}{status==='error'&&<button ref={preferred} className="primary" disabled={disabled} onClick={onRetry}>{uiText('Retry microphone')}</button>}</div></footer></section></div>,document.body)
}
export function VoiceRecorder({conversation,disabled,onRecorded}:{conversation:string;disabled?:boolean;onRecorded:(file:File)=>void}){
 useI18n();const [open,setOpen]=useState(false),[status,setStatus]=useState<Status>('requesting'),[seconds,setSeconds]=useState(0),[peaks,setPeaks]=useState<number[]>([]),[result,setResult]=useState<VoiceResult|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),capture=useRef<VoiceCapture|null>(null),alive=useRef(true),operation=useRef(0)
 const cancel=()=>{operation.current++;capture.current?.cancel();capture.current=null;setOpen(false);setResult(null);setPeaks([]);setSeconds(0)}
 useEffect(()=>{alive.current=true;cancel();const off=api.onEvent(event=>{if(event.channel==='client:authentication'&&!event.payload.authenticated)cancel()});return()=>{alive.current=false;operation.current++;off();capture.current?.cancel();capture.current=null}},[conversation])
 const start=async(resuming=false)=>{
  if(disabled)return
  const request=++operation.current;setOpen(true);setStatus('requesting');setError('');setNotice('')
  if(!navigator.mediaDevices?.getUserMedia||!window.AudioContext){setError('Voice recording requires a secure browser connection and microphone support.');setStatus('error');return}
  try{
  if(!resuming){capture.current?.cancel();setSeconds(0);setPeaks([]);setResult(null);capture.current=new VoiceCapture((time,values)=>{if(alive.current){setSeconds(time);setPeaks([...values])}},(value,limited)=>{if(!alive.current)return;capture.current=null;setSeconds(value.seconds);if(value.seconds<.2){setError(previous=>previous||'The recording is too short. Try recording again.');setStatus('error');return}setResult(value);setStatus('review');if(limited)setNotice('The 10-minute limit was reached. Your recording is ready to review.')},reason=>{if(alive.current){if(reason==='processor')setError('Audio processing stopped unexpectedly.');else setNotice('Microphone disconnected. The captured audio is kept for review.')}})}
  window.dispatchEvent(new CustomEvent('message-media:play-intent',{detail:null}))
  const started=await capture.current!.start();if(alive.current&&request===operation.current&&started){if(document.hidden){pause();setNotice('Recording paused because this page was hidden.')}else setStatus('recording')}}
  catch(cause){if(alive.current&&request===operation.current){setError(errorText(cause));if(resuming){capture.current?.pause();setStatus('paused')}else{capture.current?.cancel();capture.current=null;setStatus('error')}}}
 }
 const pause=()=>{operation.current++;capture.current?.pause();setStatus('paused')}
 useEffect(()=>{const hidden=()=>{if(open&&document.hidden&&(status==='recording'||status==='requesting')){pause();setNotice('Recording paused because this page was hidden.')}};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden)},[open,status])
 useEffect(()=>{if(open&&disabled&&(status==='recording'||status==='requesting')){pause();setNotice('Recording paused. The message draft is temporarily unavailable.')}},[open,disabled,status])
 const finish=()=>{setStatus('stopping');capture.current?.stop()}
 return <><button className="message-record-voice" disabled={disabled} aria-label={uiText('Record voice')} title={uiText('Record voice')} onClick={()=>void start()}><Icon name="mic"/></button>{open&&<RecordingDialog disabled={disabled} status={status} seconds={seconds} peaks={peaks} result={result} notice={notice} error={error} onPause={pause} onResume={()=>void start(true)} onStop={finish} onCancel={cancel} onRetry={()=>void start()} onUse={()=>{if(!result||disabled)return;try{const stamp=new Date().toISOString().replaceAll(':','-').replace(/\.\d+Z$/,'Z');onRecorded(new File([result.blob],uiText('Voice note')+' '+stamp+'.wav',{type:'audio/wav'}));cancel()}catch(cause){setError((cause as Error).message)}}}/>}</>
}
