const string={type:'string',minLength:1},boolean={type:'boolean'},plugin={enum:['telegram','x','youtube']}
const schema=(properties:Record<string,unknown>,required:string[]=[])=>({type:'object',additionalProperties:false,properties,required})
const sourcePatch=schema({name:string,locator:string,enabled:boolean,pollSeconds:{type:'integer',minimum:1},channelId:string})
const attachments={images:{type:'array',items:string,maxItems:16},files:{type:'array',items:string,maxItems:16}}
const avatar=schema({name:string,mimeType:{enum:['image/png','image/jpeg','image/gif','image/webp']},data:{type:'string',maxLength:11184812}},['name','mimeType','data'])
const externalEngine=(location:'local'|'remote')=>schema({kind:{const:'external'},location:{const:location},name:string,host:string,endpoint:string,collectorId:string,fileStorage:schema({hostId:string,directory:string},['hostId','directory'])},['kind','location','name',...(location==='remote'?['host','endpoint']:[])])
const engine={oneOf:[schema({kind:{const:'employees'},employeeIds:{type:'array',items:string,minItems:1,maxItems:200}},['kind','employeeIds']),externalEngine('local'),externalEngine('remote')]}
const documentFile=schema({id:string,name:string,mimeType:string,bytes:{type:'integer',minimum:1,maximum:2147483648},sha256:{type:'string',pattern:'^[a-f0-9]{64}$'},thumbnailMediaId:string,thumbnailOrigin:{enum:['telegram','generated']}},['id','name','mimeType','bytes','sha256'])
const publication=(properties:Record<string,unknown>,required:string[])=>({...schema({sourceId:string,channelId:string,...properties},required),oneOf:[{required:['sourceId'],not:{required:['channelId']}},{required:['channelId'],not:{required:['sourceId']}}]})
export const CHANNEL_COMMANDS=[
 {cli:{aliases:{postId:'post',fileId:'file'},required:['postId','fileId']},name:'channel.file-download',args:'--post POST_ID --file FILE_ID',summary:'User-only: copy a cloud document into this channel shared workspace, with SHA-256 verification; cloud cache retention never removes the local copy',gui:'Download to channel',inputSchema:schema({postId:string,fileId:string},['postId','fileId'])},
 {cli:{aliases:{postId:'post',fileId:'file'},required:['postId','fileId']},name:'channel.file-status',args:'--post POST_ID --file FILE_ID',summary:'Read cloud-to-channel download progress and the saved relative workspace path; never starts a download',gui:'Channel document progress',inputSchema:schema({postId:string,fileId:string},['postId','fileId'])},
 {cli:{positionals:['id'],rawPositionals:true},name:'channel.connection',args:'ID',summary:'Read configured process origin, receiver URL, source IDs and last authenticated contact; saving configuration never claims a live connection',gui:'Channel connection',inputSchema:schema({id:string},['id'])},
 {cli:{positionals:['id'],rawPositionals:true},name:'channel.avatar-image',args:'ID',summary:'User or Secretary: read the independently retained custom channel avatar',gui:'Channel avatar',inputSchema:schema({id:string},['id'])},
 {name:'channel.read-state',args:'ID --entries JSON',summary:'User or Secretary: read personal reading state for retained channel entries; does not acknowledge or execute anything',gui:'Channel unread state',inputSchema:schema({id:string,entryIds:{type:'array',items:string,maxItems:200}},['id','entryIds'])},
 {name:'channel.acknowledge',args:'ID (--entries JSON | --all [--source SOURCE_ID])',summary:'User-only: mark specific visible entries or explicitly mark all current unread channel entries read, independently of Agent delivery receipts',gui:'Channel user reading',inputSchema:{...schema({id:string,entryIds:{type:'array',items:string,maxItems:200},all:{const:true},sourceId:string},['id']),oneOf:[{required:['entryIds'],not:{required:['all']}},{required:['all'],not:{required:['entryIds']}}]}},
 {cli:{"positionals":["id"]},name:'channel.timeline',args:'ID [--kind all|news|message] [--before-entry ID] [--cursor CURSOR] [--limit N]',summary:'Read retained channel news and discussion with full content; choose 1–100 entries and paginate older history. Current members may read their channels; no read receipts or model calls.',gui:'Channel history',inputSchema:schema({id:string,kind:{enum:['all','news','message'],default:'all'},beforeEntry:{...string,description:'Return entries ordered before this news/message in the current channel timeline; the anchor itself is excluded.'},cursor:{...string,description:'Use the returned nextCursor with the same channel, kind and beforeEntry to fetch older entries.'},limit:{type:'integer',minimum:1,maximum:100,default:20}},['id'])},
 {cli:{"positionals":["id"]},name:'channel.history',args:'ID [--before N] [--around ID] [--limit N]',summary:'Discussion messages only, excluding news. Use channel.timeline for the visible news feed or mixed history.',gui:'Channel discussion',inputSchema:schema({id:string,before:{type:'integer',minimum:1},around:string,limit:{type:'integer',minimum:1,maximum:100}},['id'])},
 {cli:{"positionals":["id"],"aliases":{"entryId":"entry"}},name:'channel.context',args:'ID [--entry ID]',summary:'Read retained news or discussion context within a current channel membership',gui:'Channel discussion',inputSchema:schema({id:string,entryId:string},['id'])},
 {name:'channel.message-send',args:'ID [--text TEXT] [--file PATH] [--images JSON] [--files JSON] [--mentions JSON|all] [--reply-to ID] [--client-message-id ID]',summary:'User or Secretary: share a channel message with all current members and assign work to its dialogue targets',gui:'Channel composer',inputSchema:schema({...attachments,id:string,text:{type:'string',minLength:0,maxLength:16000},mentions:{oneOf:[{const:'all'},{type:'array',items:string,maxItems:200}]},replyTo:string,clientMessageId:{type:'string',maxLength:160}},['id'])},
 {name:'channel.message-post',args:'ID [--text TEXT] [--file PATH] [--images JSON] [--files JSON] [--reply-to ID] [--kind summary|decision|blocker|question|result] [--client-message-id ID]',summary:'Deliberately publish a nonempty reply within a received user or Secretary discussion; no acknowledgment call is needed',gui:'Channel replies',inputSchema:schema({...attachments,id:string,text:{type:'string',minLength:0,maxLength:16000,description:'Public reply text, not null/undefined placeholders. Core records receipts; silence requires no API call.'},replyTo:string,kind:{enum:['message','summary','decision','blocker','question','result']},clientMessageId:{type:'string',maxLength:160}},['id'])},
 {name:'channel.source-avatar-put',args:'--data JSON|@file',summary:'Submit a source-scoped identity image using the collector capability; this grants no message or membership permissions',gui:'Channel source identity',inputSchema:schema({sourceId:string,name:string,mimeType:{enum:['image/png','image/jpeg','image/gif','image/webp']},data:{type:'string',maxLength:11184812}},['sourceId','name','mimeType','data'])},
 {cli:{"positionals":["sourceId"],"rawPositionals":true},name:'channel.source-image',args:'SOURCE_ID',summary:'User or Secretary: read the original independently retained source avatar bytes',gui:'Channel avatar',inputSchema:schema({sourceId:string},['sourceId'])},
 {cli:{},name:'channel.settings',args:'[--patch JSON]',summary:'User or Secretary: read or configure the local collector listener; disabled by default',gui:'News channel connection',inputSchema:schema({patch:schema({enabled:boolean,port:{type:'integer',minimum:1024,maximum:65535}})})},
 {cli:{},name:'channel.list',args:'',summary:'List your current channel memberships; the user additionally receives retained-item summaries',gui:'News channels',inputSchema:schema({})},
 {cli:{"positionals":["id"],"rawPositionals":true},name:'channel.get',args:'ID',summary:'Read one channel identity as the user or a current member without scanning news histories',gui:'News channels',inputSchema:schema({id:string},['id'])},
 {cli:{"aliases":{"channelId":"channel"}},name:'channel.sources',args:'[--channel ID] [--plugin telegram|x|youtube] [--include-disabled]',summary:'User or Secretary: list authoritative subscriptions, routes and retained author avatars',gui:'News subscriptions',inputSchema:schema({channelId:string,plugin,includeDisabled:boolean})},
 {cli:{},name:'channel.create',args:'--name NAME --engine JSON [--avatar JSON|@file]',summary:'User or Secretary: explicitly choose employee or external-process publishing; an issued collector token is returned once in setup',gui:'Channel publishing engine',inputSchema:schema({name:string,engine,avatar},['name','engine'])},
 {cli:{"positionals":["id"],"aliases":{"adminIds":"admins"}},name:'channel.update',args:'ID [--name NAME] [--admins JSON] [--engine JSON] [--avatar JSON|null] [--expected-revision N]',summary:'Update channel identity, publishing membership or external connection without changing company roles or engine type; null avatar restores the default',gui:'Channel settings',inputSchema:schema({id:string,name:string,adminIds:{type:'array',items:string,maxItems:200},engine,avatar:{oneOf:[avatar,{type:'null'}]},expectedRevision:{type:'integer',minimum:1}},['id'])},
 {name:'channel.source-add',args:'--data JSON|@file',summary:'User or Secretary: follow a source; Telegram creates a one-to-one channel, X/YouTube default to aggregators',gui:'News subscriptions',inputSchema:schema({plugin,targetId:string,locator:string,name:string,enabled:boolean,pollSeconds:{type:'integer',minimum:1},channelId:string},['plugin','locator'])},
 {cli:{"positionals":["id"],"required":["patch"]},name:'channel.source-update',args:'ID --patch JSON|@file',summary:'User or Secretary: change source settings or route all retained news, including saved items',gui:'News subscriptions',inputSchema:schema({id:string,patch:sourcePatch},['id','patch'])},
 {cli:{"positionals":["id"],"rawPositionals":true},name:'channel.source-remove',args:'ID',summary:'User or Secretary: unfollow a source while retaining its identity and saved news',gui:'News subscriptions',inputSchema:schema({id:string},['id'])},
 {cli:{"aliases":{"channelId":"channel","sourceId":"source"}},name:'channel.posts',args:'[--channel ID] [--source ID] [--saved] [--query TEXT] [--cursor CURSOR] [--limit N]',summary:'User or Secretary: page current news and permanent saved items with stable item identities',gui:'News feed',inputSchema:schema({channelId:string,sourceId:string,saved:boolean,query:{type:'string',maxLength:500},cursor:string,limit:{type:'integer',minimum:1,maximum:100}})},
 {cli:{"positionals":["id"],"rawPositionals":true},name:'channel.post',args:'POST_ID',summary:'User or Secretary: read a retained news item with current channel routing',gui:'News detail',inputSchema:schema({id:string},['id'])},
 {name:'channel.save',args:'POST_ID on|off',summary:'User or Secretary: retain a news item and its local images permanently, or resume its original expiry',gui:'Saved news',inputSchema:schema({id:string,saved:boolean},['id','saved'])},
 {cli:{"positionals":["id"],"rawPositionals":true},name:'channel.delete',args:'POST_ID',summary:'User or Secretary: delete local news and images with bounded replay protection',gui:'News deletion',inputSchema:schema({id:string},['id'])},
 {cli:{"positionals":["channelId"],"aliases":{"postId":"post","mediaId":"media"}},name:'channel.image',args:'CHANNEL_ID --post POST_ID --media MEDIA_ID',summary:'User or Secretary: read a published local news image, never staging or arbitrary URLs',gui:'News images',inputSchema:schema({channelId:string,postId:string,mediaId:string},['channelId','postId','mediaId'])},
 {cli:{"positionals":["id"],"rawPositionals":true},name:'channel.export',args:'POST_ID',summary:'User or Secretary: export a retained news article and original local images',gui:'News download',inputSchema:schema({id:string},['id'])},
 {name:'channel.collector-add',args:'--name NAME [--sources JSON|all | --channel ID]',summary:'Issue a source-scoped credential or bind a replacement process credential to an external channel; plaintext is returned once',gui:'News collector connection',inputSchema:{...schema({name:string,sourceIds:{oneOf:[{const:'all'},{type:'array',items:string,minItems:1}]},channelId:string},['name']),not:{required:['sourceIds','channelId']}}},
 {cli:{},name:'channel.collectors',args:'',summary:'User or Secretary: list collector metadata without tokens or token hashes',gui:'News collector connection',inputSchema:schema({})},
 {cli:{"positionals":["id"],"rawPositionals":true},name:'channel.collector-revoke',args:'ID',summary:'User or Secretary: revoke a news collector credential',gui:'News collector connection',inputSchema:schema({id:string},['id'])},
 {cli:{},name:'channel.collector-config',args:'[--since-revision N]',summary:'Read authoritative collector targets; external access requires the dedicated channel capability',gui:'Collector protocol',inputSchema:schema({sinceRevision:{type:'integer',minimum:0}})},
 {name:'channel.media-put',args:'--data JSON|@file',summary:'Upload an item-scoped image: employee publishers use channelId, external collectors use sourceId; the authenticated employee identity is enforced',gui:'Channel publishing',inputSchema:publication({externalId:string,publishedAt:{type:'integer',minimum:0},mediaKey:string,name:string,mimeType:{enum:['image/png','image/jpeg','image/gif','image/webp']},data:{type:'string',maxLength:11184812}},['externalId','publishedAt','mediaKey','name','mimeType','data'])},
 {name:'channel.publish',args:'--data JSON|@file',summary:'Publish an article using a current employee channelId or an external sourceId. Scheduled employees may publish without a discussion parent; identity, deduplication and retention remain enforced',gui:'Channel publishing',inputSchema:publication({externalId:string,publishedAt:{type:'integer',minimum:0},title:{type:'string',maxLength:1000},body:{type:'string'},url:string,authorName:string,authorUrl:string,avatarMediaId:string,mediaIds:{type:'array',items:string,maxItems:16},files:{type:'array',items:documentFile,maxItems:16},telegram:schema({groupId:string,views:{type:'integer',minimum:0},subscriberCount:{type:'integer',minimum:0},reactions:{type:'array',maxItems:32,items:schema({emoji:string,count:{type:'integer',minimum:0}},['emoji','count'])}}),contentHash:string},['externalId','publishedAt','title','body'])}
]
