import {objectSchema,nonemptySchema as id,textSchema as text,booleanSchema as flag} from './api-schema.ts'
// Additive documentation for established Core payloads. Business validation stays in the owning domain.
const number={type:'number'},integer={type:'integer',minimum:0},record={type:'object',additionalProperties:true},ids={type:'array',items:id,minItems:1}
const scoped={shared:flag,team:text,employee:id,workspace:text,path:text}
const target={id,employee:id}
const targeted=(extra:Record<string,unknown>={})=>({...objectSchema({...target,...extra}),anyOf:[{required:['id']},{required:['employee']}]})
const location={type:'object',required:['path'],properties:{path:text,asset:id,conversation:id,employee:id,team:text,shared:flag,local:flag,group:id,channel:id},additionalProperties:false}
export const INFRA_REQUEST_SCHEMAS:Record<string,Record<string,unknown>>={
 ...Object.fromEntries(['status','system.info','auth.whoami','settings.get','shared.info','view.get','view.close','management.roles','schedule.schema','schedule.status','session.inbox','transfer.list','engine.list'].map(name=>[name,objectSchema({})])),
 'group.list':objectSchema({details:flag}),
 'group.add':objectSchema({name:text,root:text,mode:{enum:['build','work','cloud']},pluginId:id,directoryMode:{enum:['default','bind']},hostId:id,directory:text,remote:record,os:text,distribution:text},['name']),
 'group.root':objectSchema({name:text,root:id,create:flag},['name','root']),
 'group.migrate':objectSchema({name:text},['name']),
 'group.remove':{...objectSchema({name:text,names:ids,deleteWorkspace:flag}),anyOf:[{required:['name']},{required:['names']}]},
 'card.update':objectSchema({id,patch:{type:'object',additionalProperties:true,description:'Editable general profile fields. Engine, Company Team and workspace identity remain fixed.'}},['id','patch']),
 'card.remove':{...objectSchema({id,ids,deleteWorkspace:flag}),anyOf:[{required:['id']},{required:['ids']}]},
 'card.rename':objectSchema({cardId:id,title:id},['cardId','title']),
 'card.clone':objectSchema({id,title:id,cwd:text,directoryMode:{enum:['default','bind']}},['id','title']),
 'card.initialize':objectSchema({id,model:text,effort:text},['id']),
 'card.management-role':objectSchema({id,role:{enum:['employee','manager','governor','secretary']}},['id','role']),
 'management.topology':objectSchema({team:text,creator:text,teamsOnly:flag}),
 'management.activity':objectSchema({team:text}),
 'management.relayout':objectSchema({team:text}),
 'office.layout':objectSchema({team:text,viewId:id}),
 'room.layout':objectSchema({name:text},['name']),
 'room.design':objectSchema({name:text,design:record},['name','design']),
 'room.bounds':objectSchema({name:text,bounds:record},['name','bounds']),
 'card.place':objectSchema({id,x:number,y:number,snap:flag,zoom:{type:'number',minimum:0.08,maximum:3}},['id','x','y']),
 'canvas.view':objectSchema({viewId:id}),
 'canvas.set':objectSchema({x:number,y:number,zoom:number,viewId:id},['x','y','zoom']),
 'connector.get':objectSchema({manager:id,employee:id},['manager','employee']),
 'connector.set':objectSchema({manager:id,employee:id,source:record,target:record,route:{type:['array','null'],items:objectSchema({x:number,y:number},['x','y'])}},['manager','employee']),
 'connector.segment':objectSchema({manager:id,employee:id,index:integer,x:number,y:number},['manager','employee','index','x','y']),
 'connector.reset':objectSchema({manager:id,employee:id},['manager','employee']),
 'session.list':objectSchema({live:flag,summary:flag}),
 'session.status':objectSchema({employee:id}),
 'session.open':{...objectSchema({cardId:id,employee:id}),anyOf:[{required:['cardId']},{required:['employee']}]},
 'session.info':targeted(),
 'session.activity':targeted(),
 'session.snapshot':targeted(),
 'session.search':objectSchema({query:text}),
 'session.follow':targeted({raw:flag,thinking:flag,limit:{type:'integer',minimum:1,maximum:1000}}),
 'session.interrupt':targeted({expectedMessageId:id}),
 'session.close':targeted(),
 'session.queue':targeted(),
 'session.dequeue':targeted({messageId:id}),
 'session.background':targeted(),
 'session.background-stop':targeted({processId:id}),
 'session.export':targeted({format:{enum:['markdown','json']},path:text}),
 'session.acknowledge':objectSchema({employee:id,replyId:id},['employee','replyId']),
 'config.model':targeted({model:text}),
 'config.effort':targeted({effort:text}),
 'config.thinking':targeted({enabled:{oneOf:[flag,{enum:['on','off']}]}}),
 'config.fast':targeted({enabled:flag}),
 'config.plan':targeted({enabled:flag}),
 'config.permission':targeted({mode:{enum:['default','acceptEdits','bypassPermissions']}}),
 'chat.file':objectSchema({id,path:id,operation:{enum:['info','image','read','chunk']},offset:integer},['id','path']),
 'workspace.list':objectSchema({...scoped,hidden:flag}),
 'workspace.read':objectSchema(scoped,['path']),
 'workspace.image':objectSchema(scoped,['path']),
 'workspace.write':objectSchema({...scoped,content:text,data:text,hash:text,create:flag},['path']),
 'workspace.mkdir':objectSchema(scoped,['path']),
 'workspace.move':objectSchema({...scoped,to:id},['path','to']),
 'workspace.trash':objectSchema(scoped,['path']),
 'workspace.restore':objectSchema({...scoped,id},['id']),
 'transfer.start':objectSchema({from:location,to:location},['from','to']),
 'transfer.get':objectSchema({id},['id']),
 'transfer.cancel':objectSchema({id},['id']),
 'transfer.upload-begin':objectSchema({to:location,name:id,bytes:integer},['to','name','bytes']),
 'transfer.upload-chunk':objectSchema({id,offset:integer,data:text},['id','offset','data']),
 'transfer.upload-commit':objectSchema({id},['id']),
 'transfer.upload-abort':objectSchema({id},['id']),
 'transfer.download-info':objectSchema({from:location},['from']),
 'transfer.download-chunk':objectSchema({from:location,offset:integer,modifiedAt:number},['from','offset']),
 'transfer.download-save':objectSchema({from:location,path:text,overwrite:flag},['from']),
 'view.shared':objectSchema({enabled:flag},['enabled']),
 'view.details':objectSchema({enabled:flag},['enabled']),
 'view.open':objectSchema({kind:{enum:['home','team','employee','workspace','conversation','initialization','settings','plugin','clone','messages','plan']},name:text,employee:id,chatId:id,channelId:id,sourceId:id,planViewId:id,settings:record,pluginId:id,details:flag},['kind']),
 'approval.list':targeted(),
 'approval.respond':targeted({requestId:id,decision:{enum:['allow','deny']},answers:record,form:record}),
 'engine.capabilities':objectSchema({engine:{enum:['codex','claude','cline','pi']}},['engine']),
 'engine.models':objectSchema({engine:{enum:['codex','claude','cline','pi']},team:text}),
 'host.list':objectSchema({os:text,distribution:text,summary:flag,credentials:flag}),
 'host.get':objectSchema({id},['id'])
}
