import {$,run,toast} from './dom.js';
export class CardInk{
 constructor(study){this.study=study;this.mode='off';this.pending=null;this.busy=false;
  const tools=document.createElement('span');tools.className='card-ink-tools';tools.innerHTML='<button id="card-ink-pen" aria-pressed="false">脑图笔</button><button id="card-ink-eraser" aria-pressed="false">擦除</button><button id="card-ink-retry" hidden>重试笔画</button><button id="card-ink-discard" hidden>放弃笔画</button>';document.querySelector('.advanced-map-toolbar').append(tools);
  $('card-ink-pen').onclick=()=>this.modeSet(this.mode==='pen'?'off':'pen');$('card-ink-eraser').onclick=()=>this.modeSet(this.mode==='eraser'?'off':'eraser');$('card-ink-retry').onclick=run(()=>this.save(this.study.current.revision));$('card-ink-discard').onclick=()=>{this.pending=null;this.render();};
  study.map.board.addEventListener('pointerdown',e=>this.start(e),true);
 }
 get dirty(){return this.busy||!!this.pending;}
 modeSet(mode){this.mode=mode;this.study.map.board.classList.toggle('card-ink-active',mode!=='off');this.study.map.board.classList.toggle('card-ink-erasing',mode==='eraser');$('card-ink-pen').setAttribute('aria-pressed',mode==='pen');$('card-ink-eraser').setAttribute('aria-pressed',mode==='eraser');}
 render(){const set=this.study.current;if(!set)return;$('card-ink-retry').hidden=!this.pending||this.busy;$('card-ink-discard').hidden=!this.pending||this.busy;
  const canvasStrokes=(set.canvasInk||[]).filter(s=>set.layers.some(l=>l.id===s.layerId&&l.visible&&!l.deletedAt));if(this.pending?.canvas)canvasStrokes.push({...this.pending,id:'draft'});let overlay=$('study-map-world').querySelector('.map-ink-overlay');if(!overlay){overlay=document.createElementNS('http://www.w3.org/2000/svg','svg');overlay.classList.add('map-ink-overlay');$('study-map-world').append(overlay);}overlay.setAttribute('width',this.study.map.layout?.width||1000);overlay.setAttribute('height',this.study.map.layout?.height||1000);overlay.innerHTML=canvasStrokes.map(s=>`<polyline data-canvas-stroke="${s.id}" points="${s.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${set.colors[s.color]}" stroke-width="${s.width}" stroke-linecap="round"/>`).join('');
  for(const el of this.study.map.board.querySelectorAll('.study-card')){const card=set.cards.find(c=>c.id===el.dataset.cardId),strokes=(card?.ink||[]).filter(s=>set.layers.some(l=>l.id===s.layerId&&l.visible&&!l.deletedAt));if(this.pending?.cardId===card?.id)strokes.push({...this.pending,id:'draft'});let svg=el.querySelector('.card-ink-overlay');if(!svg){svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('card-ink-overlay');svg.setAttribute('viewBox','0 0 1 1');svg.setAttribute('preserveAspectRatio','none');el.append(svg);}svg.innerHTML=strokes.map(s=>`<polyline data-card-stroke="${s.id}" points="${s.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${set.colors[s.color]}" stroke-width="${s.width}" stroke-linecap="round" stroke-linejoin="round"/>`).join('');}
 }
 start(e){const el=e.target.closest('.study-card');if(this.mode==='off'||(!el&&!e.target.closest('#study-map-viewport'))||e.button!==0||e.target.closest('button'))return;e.preventDefault();e.stopImmediatePropagation();if(this.dirty){toast('请先保存或放弃笔画',true);return;}const set=this.study.current,cardId=el?.dataset.cardId;
  if(this.mode==='eraser'){const stroke=e.target.closest('[data-card-stroke],[data-canvas-stroke]');if(stroke)run(()=>this.study.change(cardId?'study.card.ink.remove':'study.canvas.ink.remove',{...(cardId?{cardId}:{}),strokeId:stroke.dataset.cardStroke||stroke.dataset.canvasStroke},set.revision))();return;}
  const box=(el||$('study-map-world')).getBoundingClientRect(),point=ev=>el?[Math.max(0,Math.min(1,(ev.clientX-box.left)/box.width)),Math.max(0,Math.min(1,(ev.clientY-box.top)/box.height))]:[Math.max(0,(ev.clientX-box.left)/this.study.map.zoom),Math.max(0,(ev.clientY-box.top)/this.study.map.zoom)];this.pending={...(cardId?{cardId}:{canvas:true}),points:[point(e)],color:'blue',width:cardId?.009:3,layerId:set.activeLayer||'default'};
  const capture=this.study.map.board;capture.setPointerCapture(e.pointerId);const move=ev=>{if(this.pending.points.length<2048)this.pending.points.push(point(ev));this.render();};const stop=ev=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',stop);document.removeEventListener('pointercancel',cancel);move(ev);run(()=>this.save(set.revision))();};const cancel=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',stop);document.removeEventListener('pointercancel',cancel);this.pending=null;this.render();};document.addEventListener('pointermove',move);document.addEventListener('pointerup',stop,{once:true});document.addEventListener('pointercancel',cancel,{once:true});
 }
 async save(revision){if(!this.pending||this.busy)return;this.busy=true;try{const {canvas,...params}=this.pending;await this.study.change(canvas?'study.canvas.ink.add':'study.card.ink.add',params,revision);this.pending=null;}finally{this.busy=false;this.render();}}
}
