import {$,escape,run,toast,describeError} from './dom.js';
const family=t=>t.settings?.brush==='laser'?'pen':t.settings?.brush||'pen';
const label={document:'文档',map:'脑图',card:'卡片',review:'复习'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const penIcon=brush=>`<svg viewBox="0 0 24 40" aria-hidden="true">${brush==='highlighter'?'<path d="M5 2h14v23H5z" fill="currentColor"/><path d="m6 25 2 9h8l2-9" fill="var(--pen-color)"/><path d="M8 34h8v4H8z" fill="var(--pen-color)"/>':brush==='pencil'?'<path d="M7 2h10v25H7z" fill="currentColor"/><path d="m7 27 5 12 5-12" fill="#d7b88a"/><path d="m10 34 2 5 2-5" fill="var(--pen-color)"/>':'<path d="M7 2h10v23H7z" fill="currentColor"/><path d="m7 25 5 14 5-14Z" fill="var(--pen-color)"/><path d="M12 26v8" stroke="currentColor" stroke-width="1"/>'}</svg>`;
const icons={eraser:'<svg viewBox="0 0 24 24"><path d="m4 14 9-10 7 6-9 10H8Z"/><path d="m7 11 7 6M10 20h11"/></svg>',lasso:'<svg viewBox="0 0 24 24"><path d="M7 17C-1 12 5 4 13 4s12 10 4 13S3 18 6 13c2-3 6 2 3 5-1 1-1 3 2 3" stroke-dasharray="3 2"/></svg>',settings:'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6"/></svg>'};
export class InkToolbar {
 constructor(study){
  this.study=study;this.owner=null;this.busy=false;this.drag=null;
  this.bar=document.createElement('div');this.bar.className='ink-toolbar';this.bar.id='ink-toolbar';this.bar.hidden=true;this.bar.setAttribute('role','toolbar');this.bar.setAttribute('aria-label','手写工具栏');document.body.append(this.bar);
  this.panel=document.createElement('section');this.panel.className='ink-brush-panel';this.panel.id='ink-brush-panel';this.panel.hidden=true;this.panel.setAttribute('role','dialog');this.panel.setAttribute('aria-label','笔刷选项');document.body.append(this.panel);
  this.bar.addEventListener('pointerdown',e=>e.stopPropagation());this.panel.addEventListener('pointerdown',e=>e.stopPropagation());
  document.addEventListener('pointerdown',e=>{if(!this.panel.hidden&&!this.panel.contains(e.target)&&!this.bar.contains(e.target)){e.preventDefault();e.stopPropagation();this.closePanel();}},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&this.cancelDrag){e.preventDefault();e.stopImmediatePropagation();this.cancelDrag();return;}if(e.key==='Escape'&&!this.panel.hidden){e.preventDefault();e.stopImmediatePropagation();this.closePanel();}},true);
  const reposition=()=>{if(this.bar.hidden||this.drag)return;cancelAnimationFrame(this.frame);this.frame=requestAnimationFrame(()=>this.position());};window.addEventListener('resize',reposition);document.addEventListener('scroll',reposition,true);this.resize=new ResizeObserver(reposition);this.panel.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('input[type=text]')){e.preventDefault();e.stopPropagation();e.target.blur();}});
 }
 show(context,owner){
  if(!this.study.current)return;const changed=this.context!==context||this.owner?.setId!==this.study.current.id||this.owner?.controller!==owner.controller;
  if(changed)this.closePanel();this.context=context;this.owner={...owner,setId:this.study.current.id};const parent=owner.parent||document.body;if(this.bar.parentNode!==parent){parent.append(this.bar,this.panel);}
  this.resize.disconnect();const root=owner.root();if(root)this.resize.observe(root);this.bar.hidden=false;this.render();
 }
 hide(controller){if(controller&&this.owner?.controller!==controller)return;this.cancelDrag?.();this.closePanel();this.bar.hidden=true;this.resize.disconnect();this.owner=null;}
 active(){
  const set=this.study.current,current=this.study.inkTools.settings,active=set?.tools.find(t=>t.id===set.activeTools.ink&&!t.deletedAt&&t.kind==='ink');
  return active&&family(active)===(current.brush==='laser'?'pen':current.brush)?active:set?.tools.find(t=>t.builtin===current.brush&&!t.deletedAt)||null;
 }
 render(){
  if(!this.owner||this.drag)return;const set=this.study.current;if(!set||set.id!==this.owner.setId){this.hide();return;}const root=this.owner.root(),box=root?.getBoundingClientRect();if(!box?.width||!box.height){this.hide();return;}
  this.owner.refreshed?.(set);const active=this.active(),settings=this.study.inkTools.settings,mode=this.owner.mode(),ids=set.inkToolbar.toolIds,tools=ids.map(id=>set.tools.find(t=>t.id===id&&!t.deletedAt)).filter(Boolean);
  const key=JSON.stringify([set.id,this.context,mode,tools,active?.id,settings,this.busy]);
  if(this.key!==key){this.key=key;this.bar.innerHTML=`<button type="button" class="ink-toolbar-grip" aria-label="拖动手写工具栏" title="拖动以浮动或停靠">⠿</button>${tools.map(t=>{const selected=active?.id===t.id&&mode==='pen',s=selected?settings:t.settings,color=s.brush==='laser'?set.colors.red:(set.colors[s.color]||s.color||'#555');return `<button type="button" data-ink-tool="${escape(t.id)}" class="ink-pen-button" aria-label="${escape(t.title)}" title="${escape(t.title)}${selected?' · 再次点击编辑':''}" aria-pressed="${selected}" style="--pen-color:${escape(color)}">${penIcon(s.brush==='laser'?'pen':s.brush||'pen')}</button>`;}).join('')}<span class="ink-toolbar-divider"></span>${this.owner.selectMode?['eraser','lasso'].map(m=>`<button type="button" data-ink-mode="${m}" class="ink-tool-icon" aria-label="${m==='eraser'?'橡皮擦':'套索'}" title="${m==='eraser'?'橡皮擦':'套索'}" aria-pressed="${mode===m}">${icons[m]}</button>`).join(''):''}<button type="button" data-ink-options class="ink-tool-icon" aria-label="笔刷选项" title="${label[this.context]}笔刷选项">${icons.settings}</button><button type="button" data-ink-library aria-label="更多笔刷" title="更多笔刷">•••</button><button type="button" data-ink-close aria-label="收起手写工具栏" title="收起">×</button>`;
   this.bar.querySelector('.ink-toolbar-grip').onpointerdown=e=>this.startDrag(e);
   this.bar.querySelectorAll('[data-ink-tool]').forEach(b=>b.onclick=run(async()=>{if(this.busy)return;if(b.dataset.inkTool===this.active()?.id&&this.owner.mode()==='pen')this.openPanel();else{this.closePanel();await this.perform(()=>({method:'study.tool.apply',params:{toolId:b.dataset.inkTool}}));if(this.owner)this.owner.selectMode?.('pen');}}));
   this.bar.querySelectorAll('[data-ink-mode]').forEach(b=>b.onclick=()=>{if(this.busy)return;if(this.owner.mode()===b.dataset.inkMode&&b.dataset.inkMode==='eraser')this.openPanel('eraser');else this.owner.selectMode(b.dataset.inkMode);});
   this.bar.querySelector('[data-ink-options]').onclick=()=>this.openPanel(this.owner.mode()==='eraser'?'eraser':'pen');this.bar.querySelector('[data-ink-library]').onclick=()=>this.openLibrary();this.bar.querySelector('[data-ink-close]').onclick=()=>{const owner=this.owner;this.hide();owner?.selectMode?.('off');};
  }
  this.bar.querySelectorAll('button').forEach(b=>b.disabled=this.busy);this.position();
 }
 async perform(build,{retry=false}={}){
  if(this.busy||!this.owner)return;if(this.owner.drawing?.())throw Error('请先结束当前笔画。');const owner=this.owner,focused=document.activeElement,barFocused=this.bar.contains(focused);if(this.study.current?.id!==owner.setId)return;this.busy=true;this.failure=null;this.render();this.panel.querySelectorAll('input,select,button').forEach(el=>el.disabled=true);
  const before=retry||this.panel.hidden?this.study.current.revision:this.panelRevision;
  try{const {method,params}=build(retry),result=await this.study.change(method,params,before);owner.changed?.(result,before);if(this.owner===owner&&!this.panel.hidden){this.panelRevision=result.revision;this.panelSettings={...this.study.inkTools.settings};}return result;}
  catch(error){this.failure=build;toast(describeError(error),true);const out=this.panel.querySelector('[data-ink-error]');if(out){out.textContent=describeError(error);out.hidden=false;this.panel.querySelector('[data-ink-retry]').hidden=false;}throw error;}
  finally{this.busy=false;this.render();if(!this.panel.hidden)this.syncPanel();if(focused?.isConnected&&!focused.disabled&&this.panel.contains(focused)&&!this.panel.hidden)focused.focus({preventScroll:true});else if(barFocused&&!this.bar.hidden)this.bar.querySelector(`[data-ink-tool="${this.active()?.id}"]`)?.focus({preventScroll:true});}
 }
 position(value){
  if(this.bar.hidden||!this.owner)return;const box=this.owner.root()?.getBoundingClientRect();if(!box?.width||!box.height)return;
  const bounds={left:Math.max(8,box.left+8),top:Math.max(8,box.top+8),right:Math.min(innerWidth-8,box.right-8),bottom:Math.min(innerHeight-8,box.bottom-8)};
  const stored=value||this.study.current.inkToolbar.placements[this.context]||{dock:'right',orientation:'vertical',x:1,y:.5};let orientation=stored.orientation,dock=stored.dock;
  this.bar.dataset.orientation=orientation;this.bar.style.maxWidth=Math.max(44,bounds.right-bounds.left)+'px';this.bar.style.maxHeight=Math.max(44,bounds.bottom-bounds.top)+'px';
  if(orientation==='vertical'&&this.bar.scrollHeight>bounds.bottom-bounds.top&&bounds.right-bounds.left>300){orientation='horizontal';if(dock==='left'||dock==='right')dock='bottom';this.bar.dataset.orientation=orientation;}
  const width=this.bar.offsetWidth,height=this.bar.offsetHeight,travelX=Math.max(0,bounds.right-bounds.left-width),travelY=Math.max(0,bounds.bottom-bounds.top-height);
  let x=bounds.left+travelX*stored.x,y=bounds.top+travelY*stored.y;if(dock==='left')x=bounds.left;if(dock==='right')x=bounds.left+travelX;if(dock==='top')y=bounds.top;if(dock==='bottom')y=bounds.top+travelY;
  this.bar.style.left=x+'px';this.bar.style.top=y+'px';this.bar.dataset.dock=dock;this.geometry={bounds,width,height,travelX,travelY,x,y,orientation};
  if(!this.panel.hidden){const w=this.panel.offsetWidth,h=this.panel.offsetHeight,left=x+w+width+8<=innerWidth?x+width+8:x-w-8;this.panel.style.left=clamp(left,8,Math.max(8,innerWidth-w-8))+'px';this.panel.style.top=clamp(y,8,Math.max(8,innerHeight-h-8))+'px';}
 }
 startDrag(e){
  if(e.button!==0||this.busy||this.owner?.drawing?.())return;e.preventDefault();e.stopPropagation();this.closePanel();const grip=e.currentTarget,start=this.geometry,before=this.study.current.revision,owner=this.owner,context=this.context;grip.setPointerCapture(e.pointerId);this.drag=true;let next,moved=false;
  const move=event=>{if(event.pointerId!==e.pointerId)return;if(!moved&&Math.hypot(event.clientX-e.clientX,event.clientY-e.clientY)<3)return;moved=true;const {bounds}=start,x=clamp(start.x+event.clientX-e.clientX,bounds.left,bounds.left+start.travelX),y=clamp(start.y+event.clientY-e.clientY,bounds.top,bounds.top+start.travelY),near=[['left',x-bounds.left],['right',bounds.left+start.travelX-x],['top',y-bounds.top],['bottom',bounds.top+start.travelY-y]].sort((a,b)=>a[1]-b[1]);let dock=near[0][1]<24?near[0][0]:'free',orientation=dock==='left'||dock==='right'?'vertical':dock==='top'||dock==='bottom'?'horizontal':start.orientation;
   if((dock==='top'||dock==='bottom')&&this.bar.querySelectorAll('button').length*36>bounds.right-bounds.left){dock='free';orientation=start.orientation;}
   next={dock,orientation,x:start.travelX?(x-bounds.left)/start.travelX:0,y:start.travelY?(y-bounds.top)/start.travelY:0};this.position(next);
  };
  const cleanup=()=>{grip.onpointermove=grip.onpointerup=grip.onpointercancel=null;if(grip.hasPointerCapture(e.pointerId))grip.releasePointerCapture(e.pointerId);this.drag=null;this.cancelDrag=null;};this.cancelDrag=()=>{cleanup();this.render();};grip.onpointermove=move;
  grip.onpointerup=event=>{if(event.pointerId!==e.pointerId)return;move(event);cleanup();if(!next||this.study.current?.id!==owner.setId){this.render();return;}run(async()=>{this.busy=true;try{const result=await this.study.change('study.ink.toolbar.set',{context,placement:next},before);owner.changed?.(result,before);}finally{this.busy=false;this.render();}})();};grip.onpointercancel=event=>{if(event.pointerId!==e.pointerId)return;cleanup();this.render();};
 }
 closePanel(){const focus=this.panel.contains(document.activeElement);this.panel.hidden=true;if(focus&&!this.bar.hidden)this.bar.querySelector(`[data-ink-tool="${this.active()?.id}"]`)?.focus({preventScroll:true});this.panelType=null;this.failure=null;}
 openPanel(type='pen'){
  if(!this.owner||this.busy||this.owner.drawing?.())return;const active=this.active(),s=this.study.inkTools.settings;this.panelType=type;this.editId=active?.id||null;this.panelRevision=this.study.current.revision;this.panelSettings={...s};
  const input=(key,title,min,max,step,value,disabled=false)=>`<label class="ink-setting-row"><span>${title}</span><input data-ink-setting="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" ${disabled?'disabled':''}><output>${value}</output></label>`;
  const select=(key,title,options)=>`<label class="ink-setting-row"><span>${title}</span><select data-ink-setting="${key}">${options.map(([v,t])=>`<option value="${v}" ${String(s[key])===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
  const toggle=(key,title)=>`<label class="ink-setting-toggle"><span>${title}</span><input type="checkbox" data-ink-setting="${key}" ${s[key]?'checked':''}></label>`;
  const widths=[['width','文档',.1,3,this.context==='document'],['canvasWidth','脑图',.1,30,this.context==='map'],['cardWidth','卡片',.1,3,['card','review'].includes(this.context)]];
  this.panel.innerHTML=`<header><strong>${type==='eraser'?'橡皮擦':escape(active?.title||'当前笔刷')}</strong><small>${label[this.context]}</small><button type="button" data-panel-close aria-label="关闭笔刷选项">×</button></header>${type==='eraser'?select('eraser','擦除方式',[['stroke','整笔'],['partial','局部']])+toggle('eraserAutoCancel','擦除后返回笔刷'):`<div class="ink-color-swatches">${this.study.colors.slice(0,11).map(([color,title])=>`<button type="button" data-ink-color="${escape(color)}" aria-label="${escape(title)}" title="${escape(title)}" style="background:${escape(this.study.current.colors[color]||color)}"></button>`).join('')}<input type="color" data-ink-picker aria-label="自定义笔色" value="${escape(this.study.current.colors[s.color]||s.color)}"></div><label class="ink-setting-row"><span>HEX</span><input type="text" data-ink-hex aria-label="十六进制笔色" value="${escape(this.study.current.colors[s.color]||s.color)}" maxlength="7"></label>${widths.map(([key,title,min,max,enabled])=>input(key,title,min,max,.01,Number((s[key]*(key==='canvasWidth'?1:100)).toPrecision(12)),!enabled)).join('')}${input('opacity','不透明度',.1,1,.1,s.opacity)}${select('straighten','直线',[['off','关闭'],['auto','自动'],['always','始终']])}${select('shape','图形',[['free','自由'],['line','直线'],['rectangle','矩形'],['ellipse','椭圆'],['ruler','角度辅助线']])}${input('rulerAngle','辅助线角度',-180,180,1,s.rulerAngle)}<label class="ink-setting-toggle"><span>尺子</span><input data-ink-ruler type="checkbox" ${this.study.inkTools.rulers.pose(this.context).enabled?'checked':''}></label><label class="ink-setting-toggle"><span>尺子遮挡内容</span><input data-ink-ruler-cover type="checkbox" ${this.study.inkTools.rulers.pose(this.context).cover?'checked':''}></label>${toggle('pressure','笔压')}${toggle('perfectShape','完美图形 / 涂抹删除')}${toggle('vanish','消失模式')}<label class="ink-setting-toggle"><span>连续笔宽滑条</span><input data-ink-width-mode type="checkbox" ${this.study.current.inkToolbar.widthMode==='continuous'?'checked':''}></label>${this.context==='map'?'<button type="button" data-map-binding>随动 / 聚焦设置</button>':''}<footer><button type="button" data-ink-clone>复制为新笔刷</button><button type="button" data-ink-delete>删除笔刷</button></footer>`}<p data-ink-error class="ink-panel-error" hidden></p><button type="button" data-ink-retry hidden>按最新版本重试</button>`;
  this.panel.hidden=false;this.panel.querySelector('[data-panel-close]').onclick=()=>this.closePanel();this.panel.querySelector('[data-ink-retry]').onclick=run(()=>this.failure&&this.perform(this.failure,{retry:true}));
  this.panel.querySelectorAll('[data-ink-setting]').forEach(el=>{el.oninput=()=>{const out=el.parentElement.querySelector('output');if(out)out.value=el.value;};el.onchange=run(()=>{const key=el.dataset.inkSetting,value=el.type==='checkbox'?el.checked:el.type==='range'?Number((Number(el.value)/(key==='width'||key==='cardWidth'?100:1)).toPrecision(12)):el.value;return this.savePatch({[key]:value});});});
  this.panel.querySelectorAll('[data-ink-color]').forEach(b=>b.onclick=run(()=>this.savePatch({color:b.dataset.inkColor})));for(const attr of ['data-ink-picker','data-ink-hex']){const el=this.panel.querySelector(`[${attr}]`);if(el)el.onchange=run(()=>this.savePatch({color:el.value}));}
  for(const [attr,key] of [['data-ink-ruler','enabled'],['data-ink-ruler-cover','cover']]){const el=this.panel.querySelector(`[${attr}]`);if(el)el.onchange=run(()=>{const value=el.checked,context=this.context;return this.perform(()=>({method:'study.ink.ruler.set',params:{context,[key]:value}}));});}
  const widthMode=this.panel.querySelector('[data-ink-width-mode]');if(widthMode)widthMode.onchange=run(()=>{const value=widthMode.checked?'continuous':'steps';return this.perform(()=>({method:'study.ink.toolbar.set',params:{widthMode:value}}));});
  const binding=this.panel.querySelector('[data-map-binding]');if(binding)binding.onclick=()=>{this.closePanel();this.study.inkTools.binding();};
  const clone=this.panel.querySelector('[data-ink-clone]');if(clone)clone.onclick=run(async()=>{const id=this.editId;await this.perform(()=>({method:'study.tool.save',params:{kind:'ink',title:(this.study.current.tools.find(t=>t.id===id)?.title||'当前笔刷')+' 副本',settings:this.study.inkTools.settings,pin:true,apply:true}}));if(this.owner)this.openPanel();});
  const remove=this.panel.querySelector('[data-ink-delete]');if(remove)remove.onclick=run(async()=>{const id=this.editId;if(!id)return;await this.perform(()=>({method:'study.tool.remove',params:{toolId:id}}));if(this.owner)this.openPanel();});this.syncPanel();this.position();
 }
 savePatch(patch){const id=this.editId,initial={...this.panelSettings};return this.perform(retry=>{const active=this.study.current.tools.find(t=>t.id===id);return id?{method:'study.tool.save',params:{toolId:id,title:active?.title||'笔刷',settings:{...(retry?active?.settings:initial),...patch},apply:true}}:{method:'study.ink.settings',params:patch};});}
 syncPanel(){
  if(this.panel.hidden)return;const s=this.panelSettings||this.study.inkTools.settings,set=this.study.current;if(!this.failure){this.panel.querySelectorAll('[data-ink-setting]').forEach(el=>{const key=el.dataset.inkSetting;if(el.type==='checkbox')el.checked=Boolean(s[key]);else{el.value=el.type==='range'?Number((s[key]*(key==='width'||key==='cardWidth'?100:1)).toPrecision(12)):s[key];const out=el.parentElement.querySelector('output');if(out)out.value=Number((s[key]*(key==='width'||key==='cardWidth'?100:1)).toPrecision(12));}});for(const attr of ['data-ink-picker','data-ink-hex']){const el=this.panel.querySelector(`[${attr}]`);if(el)el.value=set.colors[s.color]||s.color;}}
  this.panel.querySelectorAll('input,select,button').forEach(el=>el.disabled=this.busy);for(const [key,context] of [['width','document'],['canvasWidth','map'],['cardWidth','card']]){const el=this.panel.querySelector(`[data-ink-setting="${key}"]`);if(el){el.disabled=this.busy||(context==='card'?!['card','review'].includes(this.context):this.context!==context);el.step=set.inkToolbar.widthMode==='steps'?(key==='canvasWidth'?1:.1):.01;el.min=key==='canvasWidth'&&set.inkToolbar.widthMode==='steps'?1:.1;}}
  if(this.context==='review')for(const key of ['shape','straighten','rulerAngle','perfectShape']){const el=this.panel.querySelector(`[data-ink-setting="${key}"]`);if(el){el.disabled=true;el.title='此复习画布当前使用自由手写';}}
  if(!this.failure)for(const [attr,key] of [['data-ink-ruler','enabled'],['data-ink-ruler-cover','cover']]){const el=this.panel.querySelector(`[${attr}]`);if(el)el.checked=this.study.inkTools.rulers.pose(this.context)[key];}
  const angle=this.panel.querySelector('[data-ink-setting=rulerAngle]');if(angle&&s.shape!=='ruler')angle.disabled=true;
  this.panel.querySelectorAll('[data-ink-color]').forEach(el=>el.setAttribute('aria-pressed',(set.colors[el.dataset.inkColor]||el.dataset.inkColor).toLowerCase()===(set.colors[s.color]||s.color).toLowerCase()));
  const widthMode=this.panel.querySelector('[data-ink-width-mode]');if(widthMode&&!this.failure)widthMode.checked=set.inkToolbar.widthMode==='continuous';
  const clone=this.panel.querySelector('[data-ink-clone]');if(clone)clone.disabled=this.busy||set.inkToolbar.toolIds.length>=12;
  const remove=this.panel.querySelector('[data-ink-delete]'),tool=set.tools.find(t=>t.id===this.editId);if(remove){const others=set.tools.filter(t=>set.inkToolbar.toolIds.includes(t.id)&&t.id!==tool?.id);remove.disabled=this.busy||!tool||!['pen','highlighter','pencil'].every(f=>others.some(t=>family(t)===f));}
 }
 openLibrary(){
  if(!this.owner||this.busy||this.owner.drawing?.())return;const set=this.study.current,ids=set.inkToolbar.toolIds;this.panelType='library';this.panelRevision=set.revision;this.panelSettings={...this.study.inkTools.settings};this.panel.innerHTML='<header><strong>笔刷库</strong><button type="button" data-panel-close aria-label="关闭笔刷库">×</button></header><div class="ink-library">'+set.tools.filter(t=>t.kind==='ink').map(t=>`<div><button type="button" data-use="${escape(t.id)}" ${t.deletedAt?'disabled':''}>${escape(t.title)}${t.deletedAt?' · 已删除':''}</button><button type="button" data-pin="${escape(t.id)}">${t.deletedAt?'恢复':ids.includes(t.id)?'移出工具栏':'加入工具栏'}</button></div>`).join('')+'</div><p data-ink-error class="ink-panel-error" hidden></p><button type="button" data-ink-retry hidden>按最新版本重试</button>';
  this.panel.hidden=false;this.panel.querySelector('[data-panel-close]').onclick=()=>this.closePanel();this.panel.querySelector('[data-ink-retry]').onclick=run(()=>this.failure&&this.perform(this.failure,{retry:true}));
  this.panel.querySelectorAll('[data-use]').forEach(b=>b.onclick=run(async()=>{await this.perform(()=>({method:'study.tool.apply',params:{toolId:b.dataset.use}}));this.closePanel();this.owner?.selectMode?.('pen');}));
  this.panel.querySelectorAll('[data-pin]').forEach(b=>b.onclick=run(async()=>{const id=b.dataset.pin;await this.perform(()=>{const t=this.study.current.tools.find(t=>t.id===id);return t.deletedAt?{method:'study.tool.remove',params:{toolId:id,restore:true}}:{method:'study.tool.save',params:{toolId:id,title:t.title,settings:t.settings,pin:!this.study.current.inkToolbar.toolIds.includes(id)}};});if(this.owner)this.openLibrary();}));this.position();
 }
}
