import {furnitureMarkup,taperedBranch} from './mindmap-furniture.mjs';
import {escapeXml as E,svgShape,arrowShape,relationshipRoute,wrapLabel,mix} from './mindmap-style.mjs';
import {mindmapBranchPath} from './mindmap-layout.mjs';
export const SYMBOL_PATHS={idea:'M9 18h6m-6 3h6M8 14a7 7 0 1 1 8 0l-1 3H9Z',question:'M9 7a3 3 0 0 1 6 0c0 2-3 2-3 5m0 4v1',warning:'M12 3 2 21h20ZM12 9v5m0 3v1',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',check:'m4 12 5 5 11-11',cross:'m5 5 14 14M19 5 5 19',heart:'M12 21C2 14-1 7 4 4c3-2 6 0 8 3 2-3 5-5 8-3 5 3 2 10-8 17Z',pin:'m8 3 9 9-4 1-3 5-4-4-4 1 5-5ZM9 15l-7 7',clock:'M12 5v7l5 3M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',target:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0M12 10v4',book:'M12 5C8 3 4 3 2 4v16c4-1 7-1 10 1 3-2 6-2 10-1V4c-4-1-7-1-10 1Zm0 0v16',link:'m8 16 8-8M9 6 6 6a5 5 0 0 0 0 10h3m6-10h3a5 5 0 0 1 0 10h-3'};
export const symbolSvg=(symbol,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${SYMBOL_PATHS[symbol]||SYMBOL_PATHS.idea}"/></svg>`;
export function titleHtml(card,topic){
 const prefix=topic.prefix||'',title=prefix+card.title,runs=(card.mindmap?.runs||[]).map(r=>({...r,start:r.start+prefix.length,end:r.end+prefix.length}));
 const fragments=line=>{const split=[line.start,...runs.flatMap(r=>[r.start,r.end]).filter(n=>n>line.start&&n<line.end),line.end].sort((a,b)=>a-b);return split.slice(1).map((end,i)=>{const start=split[i],r=runs.find(r=>r.start<=start&&r.end>=end);const style=r?`${r.bold?'font-weight:750;':''}${r.italic?'font-style:italic;':''}${r.underline?'text-decoration:underline;':''}${r.strike?'text-decoration:line-through;':''}${r.color?'color:'+r.color+';':''}`:'';return `<span${style?` style="${style}"`:''}>${E(title.slice(start,end))}</span>`;}).join('');};
 return topic.lines.map(line=>`<span class="mm-title-line">${fragments(line)||'&#8203;'}${line.ellipsis?'…':''}</span>`).join('');
}
export function topicMarkup(card,p,t,set,base,moreIcon){
 const s=card.mindmap||{},b=t.box,source=card.source||card.anchor||card.reference,hasChildren=set.cards.some(c=>c.parentId===card.id),task=s.task;
 const markers=[s.priority?`<span class="mm-priority" title="优先级 ${s.priority}">${s.priority}</span>`:'',s.progress!==undefined?`<span class="mm-progress" style="--progress:${s.progress}%" title="进度 ${s.progress}%"><small>${s.progress}</small></span>`:'',s.status&&s.status!=='none'?`<span class="mm-status" data-status="${s.status}" title="${{todo:'待办',doing:'进行中',done:'完成',blocked:'阻塞'}[s.status]}">${symbolSvg(s.status==='done'?'check':s.status==='blocked'?'warning':'clock',16)}</span>`:'',s.symbol?`<span class="mm-symbol" title="${E(s.symbol)}">${symbolSvg(s.symbol)}</span>`:'',s.flagColor?`<span class="mm-flag" style="color:${s.flagColor}">⚑</span>`:''].join('');
 return `<article class="study-card mindmap-topic" data-card-id="${card.id}" data-topic-depth="${t.depth}" data-branch-side="${t.box.structure?.endsWith('left')?'left':t.box.structure==='org-up'?'top':t.box.structure==='org-down'||t.box.structure==='tree-table-down'?'bottom':'right'}" data-topic-shadow="${t.shadow}" data-topic-shape="${t.shape}" tabindex="0" draggable="false" aria-label="主题：${E(card.title)}" title="${E(card.title)}" style="left:${p.x}px;top:${p.y}px;width:${p.width}px;height:${p.height}px;padding-bottom:${b.padBottom||0}px!important;--mm-accent:${t.accent};--mm-topic-fill:${t.fill};--card-color:${t.accent};color:${t.textColor};font-family:${E(t.fontFamily)};font-size:${t.fontSize}px;--mm-shadow:${t.shadow?'0 4px 12px #23365814':'none'}">
 <svg class="mm-topic-shape" width="${p.width}" height="${p.height}" viewBox="0 0 ${p.width} ${p.height}" aria-hidden="true">${svgShape(t.shape,p.width,p.height,t,'node-'+card.id)}</svg>
 <header style="padding:${b.padTop}px ${b.padX}px ${b.titleBottom}px;min-height:${b.titleHeight+b.padTop+b.titleBottom}px;text-align:${t.align};font-weight:${t.bold?650:450};font-style:${t.italic?'italic':'normal'};text-decoration:${[t.underline?'underline':'',t.strike?'line-through':''].filter(Boolean).join(' ')||'none'}"><strong>${titleHtml(card,t)}</strong><button class="study-card-more" aria-label="主题操作：${E(card.title)}">${moreIcon}</button></header>
 ${markers?`<div class="mm-markers">${markers}</div>`:''}
 ${b.mathHeight&&card.mindmap?.equation?`<div class="mm-equation" style="height:${b.mathHeight}px;color:${t.textColor}" aria-label="公式：${E(card.mindmap.equation.latex)}"><span data-math-latex="${E(card.mindmap.equation.latex)}" style="width:${b.mathWidth}px;height:${b.mathHeight-12}px">${card.equationSvg||''}</span><button type="button" class="mm-equation-scale-handle" data-mm-equation-scale="true" aria-label="拖动调整公式大小"></button></div>`:''}
 ${t.showImage&&card.imageAsset?`<img class="study-card-image mm-topic-image" src="${E(new URL('data/'+card.imageAsset,base).href)}" width="${b.imageWidth}" height="${b.imageHeight}" style="height:${b.imageHeight}px;width:${b.imageWidth}px!important;margin-left:${b.imageLeft}px!important;margin-right:${b.imageLeft}px!important" alt="${E(card.title)}" draggable="false">`:''}
 ${t.showTags&&card.tags?.length?`<div class="mm-tags">${card.tags.slice(0,3).map(tag=>`<span>#${E(tag)}</span>`).join('')}${card.tags.length>3?`<span>+${card.tags.length-3}</span>`:''}</div>`:''}
 ${t.showNote&&card.note?`<p class="mm-note-preview">${E(card.note)}</p>`:''}
 <button class="mm-topic-details" type="button" aria-label="预览与详情：${E(card.title)}" title="预览摘录与详情">${symbolSvg('book',15)}</button>
 <footer ${!b.source?'class="mm-footer-empty"':''}><button class="study-card-source" title="${source?'回到原文':'编辑笔记'}">${source?card.source?.locator.page?(card.source.format||'PDF').toUpperCase()+' · '+card.source.locator.page:card.source?'HTML · '+((card.source.locator.section||0)+1):'↗ 来源':card.note?'笔记':'编辑'}</button>${task?.due?`<span class="mm-task-date" title="截止日期 ${E(task.due)}">${E(task.due.slice(5))}</span>`:''}${hasChildren?`<button class="study-card-collapse" aria-label="${card.collapsed?'展开':'收起'}子主题">${card.collapsed?'+':'−'}</button>`:''}</footer><button class="mm-resize-handle" data-mm-resize="true" type="button" tabindex="-1" aria-label="拖动调整主题宽度" title="拖动调整主题宽度"></button></article>`;
}
export function decorationSvg(item,layout,{interactive=false}={}){
 const s=item.style||{},color=item.color,textColor=s.textColor||layout.config.ink,id='dec-'+item.id,attr=interactive?` data-mm-item="${item.id}" role="button" tabindex="0" aria-label="编辑${item.kind==='zone'?'区域':item.kind==='boundary'?'外框':item.kind==='summary'?'概要':'标注'}：${E(s.title||'')}"`:'';
 if(item.kind==='zone'){
  const style={fill:s.fill||mix(layout.config.paper,color,.08),borderColor:color,borderWidth:s.width||1.4,borderDash:s.dash||'solid'},title=!s.titleHidden||s.collapsed?`<text x="32" y="24" font-size="${s.fontSize||13}" fill="${textColor}" font-family="system-ui">${E(s.title||'区域')}</text>`:'';
  return `<g class="mm-zone" transform="translate(${item.x} ${item.y})"${attr}><g opacity="${s.opacity??.7}">${svgShape(s.shape||'rounded',item.width,item.height,style,id)}</g>${interactive?`<rect data-zone-drag="${item.id}" x="0" y="0" width="${item.width}" height="35" fill="transparent"/>`:''}${title}${interactive?`<g data-zone-toggle="${item.id}" role="button" tabindex="0" aria-label="${s.collapsed?'展开':'折叠'}区域"><rect x="6" y="7" width="22" height="22" fill="transparent"/><text x="13" y="24" fill="${textColor}">${s.collapsed?'+':'−'}</text></g>${!s.collapsed?`<rect data-zone-resize="${item.id}" x="${item.width-10}" y="${item.height-10}" width="10" height="10" fill="${color}"/>`:''}`:''}</g>`;
 }
 if(item.kind==='summary'){
  const p=layout.positions.get(item.topicId);if(!p)return '';const x=item.x,y=item.y,b=y+item.height,m=(y+b)/2,ex=p.x-10,ey=p.y+p.height/2;
  return `<g class="mm-summary"${attr}><path d="M${x},${y} Q${x+14},${y} ${x+14},${y+16} V${m-10} Q${x+14},${m} ${x+24},${m} Q${x+14},${m} ${x+14},${m+10} V${b-16} Q${x+14},${b} ${x},${b} M${x+24},${m} L${ex},${ey}" fill="none" stroke="${color}" stroke-width="${s.width||2}"/><path class="mm-decoration-hit" d="M${x+14},${y} V${b}" stroke="transparent" stroke-width="16" fill="none"/></g>`;
 }
 const shape=s.shape||(item.kind==='callout'?'callout':'rounded');
 const style={fill:s.fill||mix(layout.config.paper,color,.08),borderColor:color,borderWidth:s.width||1.4,borderDash:s.dash||'dash'};
 const lines=wrapLabel(s.title||'',item.width-28,s.fontSize||13);
 const label=lines.slice(0,item.kind==='boundary'?1:20).map((l,i)=>`<text x="14" y="${21+i*(s.fontSize||13)*1.4}" font-size="${s.fontSize||13}" fill="${textColor}" font-family="system-ui">${E(l.text)}</text>`).join('');
 return `<g class="mm-${item.kind}" transform="translate(${item.x} ${item.y})"${attr}><g opacity="${item.kind==='boundary'?s.opacity??.7:1}">${svgShape(shape,item.width,item.height,style,id)}</g>${label}</g>`;
}
export function diagramPaths(layout,links,{interactive=false,filter=()=>true}={}){
 let output=(layout.furniture||[]).filter(filter).map(f=>furnitureMarkup(f)||(f.kind==='matrix'?`<g class="mm-matrix-grid"><rect x="${f.x}" y="${f.y}" width="${f.width}" height="${f.height}" rx="8" fill="${mix(layout.config.paper,f.color,.045)}" stroke="${mix(layout.config.paper,f.color,.3)}" stroke-width="1"/>${f.columns.map(x=>`<path d="M${x},${f.y} V${f.y+f.height}" stroke="${mix(layout.config.paper,f.color,.22)}" fill="none"/>`).join('')}</g>`:f.kind==='brace'?`<path class="mm-brace" d="M${f.x+f.width},${f.y} Q${f.x+10},${f.y} ${f.x+10},${f.y+16} V${f.y+f.height/2-12} Q${f.x+10},${f.y+f.height/2} ${f.x},${f.y+f.height/2} Q${f.x+10},${f.y+f.height/2} ${f.x+10},${f.y+f.height/2+12} V${f.y+f.height-16} Q${f.x+10},${f.y+f.height} ${f.x+f.width},${f.y+f.height}" stroke="${f.color}" stroke-width="2" fill="none"/>`:'')).join('')+layout.decorations.filter(filter).map(i=>decorationSvg(i,layout,{interactive})).join('');
 const batched=layout.links.length>1000,groups=new Map();
 for(const l of layout.links){const a=layout.positions.get(l.from),b=layout.positions.get(l.to);if(!a||!b||!filter({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x)+a.width+b.width,height:Math.abs(a.y-b.y)+a.height+b.height}))continue;const d=mindmapBranchPath(l,layout.positions);if(!d)continue;const taper=l.line==='tapered'?taperedBranch(l,layout.positions):null;if(batched){const key=l.color+'|'+l.width;if(!groups.has(key))groups.set(key,{color:l.color,width:l.width,paths:[]});groups.get(key).paths.push(d);continue;}output+=`<path class="mm-branch" data-mm-branch="${l.to}" d="${taper||d}" fill="${taper?l.color:'none'}" stroke="${taper?'none':l.color}" stroke-width="${l.width}" stroke-linecap="round"/>`;
 }
 for(const group of groups.values())output+=`<path class="mm-branch-batch" d="${group.paths.join(' ')}" fill="none" stroke="${group.color}" stroke-width="${group.width}" stroke-linecap="round"/>`;
 for(const link of links||[]){if(link.toSetId&&link.toSetId!==layout.setId)continue;const route=relationshipRoute(link,layout.positions);if(!route||!filter(route.box))continue;const v=link.mindmap||{},t=layout.topics.get(link.from),color=v.followTopic?t.accent:v.color||layout.config.ink,start=v.start|| (link.bidirectional?'triangle':'none'),end=v.end||'triangle',width=v.width||1.8,dash=v.dash==='solid'?'':v.dash==='dot'?'2 5':'6 4';
  const marker=(side,type)=>type==='none'?'':`<marker id="mm-${side}-${link.id}" viewBox="0 0 12 12" refX="10" refY="6" markerWidth="7" markerHeight="7" orient="auto-start-reverse">${arrowShape(type,color)}</marker>`;
  output+=`<defs>${marker('start',start)}${marker('end',end)}</defs><path class="study-association mm-relation" data-association-id="${link.id}" d="${route.d}" fill="none" stroke="${color}" stroke-width="${width}" stroke-dasharray="${dash}"${start==='none'?'':` marker-start="url(#mm-start-${link.id})"`}${end==='none'?'':` marker-end="url(#mm-end-${link.id})"`}/>`;
  if(link.label)output+=`<g class="mm-relation-label"${interactive?` data-mm-link="${link.id}" role="button" tabindex="0"`:''}><rect x="${route.label[0]-Math.min(300,link.label.length*(v.fontSize||12)*.6+14)/2}" y="${route.label[1]-13}" width="${Math.min(300,link.label.length*(v.fontSize||12)*.6+14)}" height="23" rx="6" fill="${layout.config.paper}"/><text x="${route.label[0]}" y="${route.label[1]+3}" text-anchor="middle" fill="${v.textColor||color}" font-size="${v.fontSize||12}" font-weight="${v.bold?700:400}" font-family="system-ui">${E(link.label)}</text></g>`;
  if(interactive)output+=`<path class="study-link-hit" data-link-id="${link.id}" d="${route.d}" tabindex="0" role="button" aria-label="编辑连线：${E(link.label||'联系')}"/>`;
 }
 return output;
}
