import {$,escape as E,run,field,showDialog,closeDialog,toast} from './dom.js';
import {api} from './transport.js';
const VISUAL=new Set(['shape','fill','textColor','borderColor','borderWidth','borderDash','fontFamily','fontSize','bold','italic','underline','strike','align','width','branchLine','branchColor','branchWidth','shadow','gradient']);
export class MindmapTools {
 constructor(studio){this.studio=studio;this.study=studio.study;
  studio.bar.querySelector('.mm-active-tools').insertAdjacentHTML('beforeend','<button id="mm-search">查找 / 替换</button><button id="mm-all-notes">全部笔记</button><button id="mm-outline-import">快速输入</button><button id="mm-copy-style">复制样式</button><button id="mm-paste-style">粘贴样式</button><button id="mm-quick-style">快捷样式</button><button id="mm-walkthrough">演示</button><button id="mm-more-tools" aria-pressed="false">更多工具</button>');
  $('mm-search').onclick=()=>this.search();$('mm-all-notes').onclick=()=>this.search(true);$('mm-outline-import').onclick=()=>this.outline();$('mm-copy-style').onclick=()=>this.copyStyle();$('mm-paste-style').onclick=run(()=>this.pasteStyle());$('mm-quick-style').onclick=()=>this.quickStyle();
  $('mm-walkthrough').onclick=run(()=>{this.studio.guard();const ids=this.studio.ids();return this.study.change('study.presentation.start',{mode:'map',...(ids.length?{cardIds:ids,descendants:true}:{})});});
  $('mm-more-tools').onclick=()=>{const open=this.studio.map.board.classList.toggle('mm-show-legacy');$('mm-more-tools').setAttribute('aria-pressed',String(open));if(open)this.study.toolbar.showAll();};
 }
 copyStyle(){const id=this.studio.map.selected,c=this.study.current.cards.find(c=>c.id===id);if(!c){toast('先选择一个主题。');return;}this.copied=structuredClone(Object.fromEntries(Object.entries(c.mindmap||{}).filter(([k])=>VISUAL.has(k))));toast('已复制主题样式，不包含任务、标记或原文。');}
 async pasteStyle(cardIds=this.studio.ids()){this.studio.guard();if(!this.copied)throw Error('先复制主题样式。');if(!cardIds.length)throw Error('先选择要设置样式的主题。');await this.study.change('study.mindmap.topics.update',{cardIds,patch:Object.fromEntries([...VISUAL].map(k=>[k,this.copied[k]??null]))});}
 quickStyle(){
  const set=this.study.current,ids=this.studio.ids();if(!ids.length){toast('先选择主题。');return;}
  const presets={important:{bold:true,borderWidth:2.4,borderColor:'#BA7C34'},critical:{bold:true,fill:'#A93F58',textColor:'#FFFFFF',borderWidth:0},crossout:{strike:true,textColor:'#748093'},plain:{bold:null,strike:null,fill:null,textColor:null,borderWidth:null,borderColor:null}};
  showDialog({title:'快捷样式',html:field('preset','样式','important',{choices:[['important','重要'],['critical','非常重要'],['crossout','已废弃'],['plain','恢复默认重点样式']]})+field('scope','应用范围','selected',{choices:[['selected','当前选择'],['siblings','同级主题'],['descendants','所选主题与全部后代']]}),onSubmit:async v=>{let targets=ids;if(v.scope==='siblings'){const parents=new Set(ids.map(id=>set.cards.find(c=>c.id===id).parentId));targets=set.cards.filter(c=>parents.has(c.parentId)).map(c=>c.id);}if(v.scope==='descendants'){const chosen=new Set(ids);for(const c of set.cards)if(chosen.has(c.parentId))chosen.add(c.id);targets=[...chosen];}await this.study.change('study.mindmap.topics.update',{cardIds:targets,patch:presets[v.preset]},set.revision);}});
 }
 outline(){const set=this.study.current;this.studio.guard();showDialog({title:'快速输入大纲',html:'<label class="dialog-field"><span>每行一个主题；两个空格或 Tab 缩进一级，也支持 Markdown 标题。</span><textarea id="mm-outline-text" name="text" rows="12" placeholder="中心主题\n  分支一\n    子主题\n  分支二"></textarea></label>'+field('target','添加到','root',{choices:[['root','新建独立中心主题'],...(this.studio.map.selected?[['selected','选中主题下']]:[])]})+'<p class="dialog-note">不替换已有内容。所有主题仍支持编辑、回源和撤销。</p>',submit:'添加主题',onSubmit:async v=>{const result=await this.study.change('study.mindmap.outline.import',{text:v.text,...(v.target==='selected'?{parentId:this.studio.map.selected}:{})},set.revision);this.studio.map.select(result.lastInsertedCard);this.studio.map.fit();}});}
 search(notesOnly=false){
  this.studio.guard();const setId=this.study.current.id;let offset=0,next=null,serial=0,receipt=null;
  const controls=field('query','关键词','')+field('priority','优先级','',{choices:[['','全部'],...Array.from({length:9},(_,i)=>[String(i+1),'优先级 '+(i+1)])]})+field('status','任务状态','',{choices:[['','全部'],['todo','待办'],['doing','进行中'],['done','完成'],['blocked','阻塞']]})+field('field','替换范围','title',{choices:[['title','主题标题'],['note','笔记'],['display','显示文字（保留原文快照）']]})+field('replacement','替换为','');
  showDialog({title:notesOnly?'全部主题笔记':'查找、筛选与替换',html:(notesOnly?'':controls)+'<div class="mm-search-actions"><button type="button" id="mm-find-run">查找</button><button type="button" id="mm-find-previous">上一页</button><button type="button" id="mm-find-next">下一页</button>'+(!notesOnly?'<button type="button" id="mm-replace-preview">预览替换</button>':'')+'</div><p id="mm-find-status" role="status"></p><div id="mm-find-results"></div>',submit:'应用已预览替换',onSubmit:notesOnly?null:async()=>{
   if(!receipt)throw Error('先预览要替换的内容。');const current=Object.fromEntries(new FormData($('dialog-form')));if(current.query!==receipt.query||current.replacement!==receipt.replacement||current.field!==receipt.field)throw Error('输入已变化，请重新预览。');if(this.study.current?.id!==setId)throw Error('学习集已切换。');const result=await this.study.change('study.mindmap.replace',{query:receipt.query,replacement:receipt.replacement,field:receipt.field,cardIds:receipt.cardIds,apply:true},receipt.expectedRevision);toast(`已替换 ${result.lastMindmapReplace.matches} 处，支持撤销。`);
  },afterOpen:()=>{
   const filter=()=>{if(notesOnly)return{hasNote:true};const v=Object.fromEntries(new FormData($('dialog-form')));return{query:v.query,...(v.priority?{priority:Number(v.priority)}:{}),...(v.status?{status:v.status}:{})};};
   const load=async()=>{const ticket=++serial,data=await api('study.mindmap.query',{setId,filter:filter(),offset,limit:50});if(ticket!==serial||!$('mm-find-results'))return;next=data.nextOffset;$('mm-find-status').textContent=`${data.total} 个主题 · ${offset+1}–${Math.min(offset+50,data.total)}`;$('mm-find-previous').disabled=offset===0;$('mm-find-next').disabled=next===null;$('mm-find-results').innerHTML=data.cards.map(c=>`<button type="button" class="mm-find-result" data-find-id="${c.id}"><strong>${E(c.title)}</strong><p>${E(notesOnly?c.note:c.text||c.note||'')}</p><small>${E((c.tags||[]).join(' · '))}</small></button>`).join('')||'<p class="dialog-note">没有匹配主题。</p>';$('mm-find-results').querySelectorAll('[data-find-id]').forEach(b=>b.onclick=run(async()=>{const id=b.dataset.findId;closeDialog();if(this.study.current?.id!==setId)return;await this.studio.map.focus(id);this.studio.map.center(id);}));};
   $('mm-find-run').onclick=run(()=>{offset=0;receipt=null;return load();});$('mm-find-previous').onclick=run(()=>{offset=Math.max(0,offset-50);return load();});$('mm-find-next').onclick=run(()=>{if(next!==null)offset=next;return load();});
   $('mm-replace-preview')?.addEventListener('click',run(async()=>{const v=Object.fromEntries(new FormData($('dialog-form'))),criteria=filter(),cardIds=[];let at=0,revision;
    do{const rows=await api('study.mindmap.query',{setId,filter:criteria,offset:at,limit:500});if(revision!==undefined&&revision!==rows.revision)throw Error('学习集已变化，请重新预览。');revision=rows.revision;cardIds.push(...rows.cards.map(c=>c.id));at=rows.nextOffset;}while(at!==null);
    if(!cardIds.length)throw Error('没有符合条件的主题。');const params={setId,expectedRevision:revision,query:v.query,replacement:v.replacement,field:v.field,cardIds};const data=await api('study.mindmap.replace',params);receipt=params;$('mm-find-status').textContent=`${data.matches} 处匹配 · ${data.changes.length} 个主题；原文快照保留`;$('mm-find-results').innerHTML=data.changes.slice(0,40).map(c=>`<section class="mm-replace-change"><del>${E(c.before)}</del><p>${E(c.after)}</p></section>`).join('')||'<p>没有需要改动的文字。</p>';
   }));run(load)();
  }});
 }
}
