import { $, escape, icon, run, showDialog, field, toast } from './dom.js';
import { base } from './transport.js';
import { StudyWorkbench } from './study-workbench.js';
import { layoutStudy, descendants } from './study-map-layout.mjs';
export class StudyMap {
  constructor(study) {
    this.study=study;this.selected=null;this.zoom=0.9;
    const board=document.createElement('section');board.id='study-board';board.innerHTML=`<header class="study-map-toolbar"><strong>脑图</strong><span id="study-card-count">0 张卡片</span><div><button id="study-zoom-out" aria-label="缩小脑图">−</button><button id="study-zoom-fit" title="适合窗口">适配</button><button id="study-zoom-in" aria-label="放大脑图">＋</button><button id="study-map-home" title="打开完整脑图">展开</button><button id="study-card-trash" title="恢复已删除卡片">回收站</button></div></header><div id="study-map-viewport" tabindex="0" aria-label="学习集脑图，可拖动卡片建立层级"><div id="study-map-extent"><div id="study-map-world"></div></div><div id="study-map-empty"><span>${icon('book')}</span><h3>在阅读中建立你的脑图</h3><p>选中原文 → 选择颜色 → 自动生成摘录卡片<br>把卡片拖到另一张卡片上，建立父子关系</p></div></div><footer class="study-map-footer"><span id="study-map-hint">拖到卡片上建立子卡片 · 拖到空白处移到顶层</span><span id="study-map-scale">90%</span></footer>`;
    this.board=board;
    $('study-home-map').append(board);this.workbench=new StudyWorkbench(this);
    $('study-zoom-out').onclick=()=>this.scale(this.zoom/1.2);$('study-zoom-in').onclick=()=>this.scale(this.zoom*1.2);$('study-zoom-fit').onclick=()=>this.fit();
    $('study-map-home').onclick=run(()=>this.study.home(this.study.current.id));$('study-card-trash').onclick=()=>this.trash();
    const viewport=$('study-map-viewport');
    viewport.addEventListener('wheel',event=>{if(event.ctrlKey||event.metaKey){event.preventDefault();this.scale(this.zoom*Math.exp(-event.deltaY*.003));}},{passive:false});
    viewport.addEventListener('dragover',e=>{if(!this.drag)return;e.preventDefault();if(!e.target.closest('.study-card')){this.clearDrop();e.dataTransfer.dropEffect='move';$('study-map-hint').textContent='松开移到顶层';}});
    viewport.addEventListener('drop',e=>{if(!this.drag||e.target.closest('.study-card'))return;e.preventDefault();const drag=this.drag;this.clearDrop();this.drag=null;run(()=>study.change('study.card.move',{cardId:drag.id,parentId:null},drag.revision))();});
    viewport.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('.study-card,button'))return;const x=e.clientX,y=e.clientY,left=viewport.scrollLeft,top=viewport.scrollTop;viewport.setPointerCapture(e.pointerId);const move=event=>{viewport.scrollLeft=left+x-event.clientX;viewport.scrollTop=top+y-event.clientY;};const stop=()=>{viewport.removeEventListener('pointermove',move);viewport.removeEventListener('pointerup',stop);};viewport.addEventListener('pointermove',move);viewport.addEventListener('pointerup',stop,{once:true});});
    document.addEventListener('click',e=>{if(!e.target.closest('.study-card-menu,.study-card-more'))this.closeMenu();});
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){this.clearDrop();this.closeMenu();}});
  }
  attach(reading) { const target=$(reading?'study-pane':'study-home-map');if(this.board.parentNode!==target)target.append(this.board);$('study-map-home').hidden=!reading; }
  render(set,focusId) {
    if(!set || this.set?.id===set.id && this.set.revision>set.revision)return;
    if(this.drag){this.deferred={set,focusId};return;}
    const key=JSON.stringify([set.id,set.revision,set.cards.map(c=>[c.sourcePath,c.sourceAvailable,c.sourceChanged,c.detached])]);
    if(this.renderKey===key){this.set=set;this.workbench.render(set);if(focusId){this.select(focusId);this.center(focusId);}return;}
    this.renderKey=key;
    const changed=this.setId!==set.id;this.setId=set.id;this.set=set;
    if(changed){this.selected=null;this.zoom=.9;}
    if(!set.cards.some(c=>c.id===this.selected))this.selected=null;
    this.layout=layoutStudy(set.cards,set.map);for(const stroke of set.canvasInk||[])for(const [x,y] of stroke.points){this.layout.width=Math.max(this.layout.width,x+30);this.layout.height=Math.max(this.layout.height,y+30);}const {positions,links,width,height}=this.layout;
    const paths=links.map(link=>{const a=positions.get(link.from),b=positions.get(link.to),x=set.map?.layout==='down'?a.x+a.width/2:a.x+a.width,y=set.map?.layout==='down'?a.y+a.height:a.y+a.height/2,tx=set.map?.layout==='down'?b.x+b.width/2:b.x,ty=set.map?.layout==='down'?b.y:b.y+b.height/2;return `<path d="M${x},${y} C${x+32},${y} ${tx-32},${ty} ${tx},${ty}"/>`;}).join('');
    const associations=(set.links||[]).filter(l=>positions.has(l.from)&&positions.has(l.to)).map(l=>{const a=positions.get(l.from),b=positions.get(l.to);return `<path class="study-association" marker-end="url(#study-link-arrow)" ${l.bidirectional?'marker-start="url(#study-link-arrow)"':''} d="M${a.x+a.width/2},${a.y+a.height/2} Q${Math.min(a.x,b.x)-45},${(a.y+b.y)/2} ${b.x+b.width/2},${b.y+b.height/2}"><title>${escape(l.label||'卡片关联')}</title></path>`;}).join('');
    $('study-map-world').innerHTML=`<svg class="study-map-links" width="${width}" height="${height}" aria-hidden="true"><defs><marker id="study-link-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><polygon points="0,0 10,5 0,10"/></marker></defs>${paths}${associations}</svg>`+set.cards.filter(c=>positions.has(c.id)).map(c=>{
      const p=positions.get(c.id),count=set.cards.filter(n=>n.parentId===c.id).length;
      return `<article class="study-card ${c.id===this.selected?'selected':''}" data-card-id="${escape(c.id)}" tabindex="0" draggable="true" aria-label="卡片：${escape(c.title)}" style="left:${p.x}px;top:${p.y}px;--card-color:${set.colors[c.color]}"><header><span class="study-card-dot"></span><strong>${escape(c.title)}</strong><button class="study-card-more" aria-label="卡片操作：${escape(c.title)}">${icon('more')}</button></header>${c.imageAsset?`<img class="study-card-image" src="${new URL('data/'+c.imageAsset,base).href}" alt="${escape(c.text.slice(0,120)||c.title)}" draggable="false">`:`<p class="study-card-text">${escape(c.text||'双击编辑笔记')}</p>`}<footer><button class="study-card-source" title="${c.source?'回到原文':'编辑笔记'}">${c.source?`${escape(c.source.format.toUpperCase())} · ${c.source.locator.page?`第 ${c.source.locator.page} 页`:`第 ${c.source.locator.section+1} 节`}${c.sourceChanged?' · 已变化':!c.sourceAvailable?' · 原文不可用':''}`:c.reference?'↗ 引用卡片':c.anchor?'↗ 留白原文':'✎ 笔记卡'}${c.tags?.length?' · #'+escape(c.tags[0]):''}</button>${count?`<button class="study-card-collapse" aria-label="${c.collapsed?'展开':'收起'}子卡片">${c.collapsed?'＋':'−'} ${count}</button>`:''}</footer>${c.note?'<span class="study-card-note" title="'+escape(c.note)+'">有笔记</span>':''}</article>`;
    }).join('');
    $('study-card-count').textContent=`${set.cards.length} 张卡片`;$('study-map-empty').hidden=!!set.cards.length;
    for(const el of $('study-map-world').querySelectorAll('.study-card')) {
      const card=set.cards.find(c=>c.id===el.dataset.cardId);
      el.addEventListener('click',e=>{if(!e.target.closest('button'))this.select(card.id);});
      el.addEventListener('dblclick',run(e=>{if(!e.target.closest('button'))return this.study.source(card);}));
      el.querySelector('.study-card-source').onclick=run(()=>this.study.source(card));
      el.querySelector('.study-card-more').onclick=e=>{e.stopPropagation();this.menu(card,e.currentTarget);};
      el.querySelector('.study-card-collapse')?.addEventListener('click',run(()=>this.study.change('study.card.update',{cardId:card.id,collapsed:!card.collapsed})));
      el.addEventListener('dragstart',e=>{if(e.target.closest('button')){e.preventDefault();return;}this.closeMenu();this.drag={id:card.id,revision:set.revision,invalid:descendants(set.cards,card.id)};e.dataTransfer.setData('application/x-study-card',card.id);e.dataTransfer.effectAllowed='move';el.classList.add('dragging');});
      el.addEventListener('dragover',e=>{if(!this.drag)return;e.preventDefault();e.stopPropagation();this.clearDrop();const invalid=this.drag.invalid.has(card.id);el.classList.add(invalid?'study-drop-rejected':'study-drop-target');e.dataTransfer.dropEffect=invalid?'none':'move';$('study-map-hint').textContent=invalid?'不能放入自身或子卡片':`松开设为「${card.title.slice(0,22)}」的子卡片`;});
      el.addEventListener('dragleave',e=>{if(!el.contains(e.relatedTarget))this.clearDrop();});
      el.addEventListener('drop',e=>{if(!this.drag)return;e.preventDefault();e.stopPropagation();const drag=this.drag;this.drag=null;this.clearDrop();if(drag.invalid.has(card.id)){toast('不能放入自身或子卡片',true);return;}run(()=>this.study.change('study.card.move',{cardId:drag.id,parentId:card.id},drag.revision))();});
      el.addEventListener('dragend',()=>{this.drag=null;this.clearDrop();el.classList.remove('dragging');if(this.deferred){const pending=this.deferred;this.deferred=null;this.render(pending.set,pending.focusId);}});
      el.addEventListener('keydown',e=>{if(e.target!==el)return;if(e.key==='Enter'){e.preventDefault();run(()=>this.study.source(card))();}else if(e.key==='Tab'){e.preventDefault();this.nest(card,e.shiftKey);}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();this.remove(card);}});
    }
    this.scale(this.zoom,false);this.workbench.render(set);if(changed)$('study-map-viewport').scrollTo(0,0);if(focusId){this.select(focusId);this.center(focusId);}
  }
  select(id){this.selected=id;for(const el of this.board.querySelectorAll('.study-card'))el.classList.toggle('selected',el.dataset.cardId===id);this.study.excerpts?.selectCard(id);}
  center(id){const p=this.layout?.positions.get(id);if(!p)return;const v=$('study-map-viewport');v.scrollTo(Math.max(0,(p.x+p.width/2)*this.zoom-v.clientWidth/2),Math.max(0,(p.y+p.height/2)*this.zoom-v.clientHeight/2));}
  scale(value,center=true){const v=$('study-map-viewport'),old=this.zoom;this.zoom=Math.min(1.8,Math.max(.2,value));if(!this.layout)return;const world=$('study-map-world');world.style.width=`${this.layout.width}px`;world.style.height=`${this.layout.height}px`;world.style.transform=`scale(${this.zoom})`;$('study-map-extent').style.width=`${this.layout.width*this.zoom}px`;$('study-map-extent').style.height=`${this.layout.height*this.zoom}px`;if(center){v.scrollLeft=(v.scrollLeft+v.clientWidth/2)*this.zoom/old-v.clientWidth/2;v.scrollTop=(v.scrollTop+v.clientHeight/2)*this.zoom/old-v.clientHeight/2;}$('study-map-scale').textContent=`${Math.round(this.zoom*100)}%`;}
  fit(){if(!this.layout)return;const v=$('study-map-viewport');this.scale(Math.min(1,(v.clientWidth-20)/this.layout.width,(v.clientHeight-20)/this.layout.height),false);v.scrollTo(0,0);}
  clearDrop(){for(const el of this.board.querySelectorAll('.study-drop-target,.study-drop-rejected'))el.classList.remove('study-drop-target','study-drop-rejected');$('study-map-hint').textContent='拖到卡片上建立子卡片 · 拖到空白处移到顶层';}
  closeMenu(){this.menuEl?.remove();this.menuEl=null;}
  menu(card,button){this.closeMenu();const el=document.createElement('div');el.className='context-menu study-card-menu';el.setAttribute('role','menu');el.innerHTML=[['source','回到原文'],['image','查看摘录图片'],['edit','编辑卡片 / 颜色'],['preview','阅读 Markdown / 公式'],...(card.imageAsset?[['occlude','图像遮挡复习']]:[]),['child','新建子卡片'],['links','关联卡片'],['review','加入 / 编辑复习'],...(card.mergedIds?[['unmerge','解除合并']]:[]),['outdent','提升一级'],['root','移到顶层'],['remove','删除卡片']].map(([id,title])=>`<button data-action="${id}" role="menuitem">${title}</button>`).join('');document.body.append(el);const box=button.getBoundingClientRect();el.style.left=`${Math.max(8,Math.min(innerWidth-el.offsetWidth-8,box.right-el.offsetWidth))}px`;el.style.top=`${Math.min(innerHeight-el.offsetHeight-8,box.bottom)}px`;this.menuEl=el;el.querySelectorAll('button').forEach(b=>b.onclick=run(()=>{this.closeMenu();switch(b.dataset.action){case'source':return this.study.source(card);case'image':return this.snapshot(card);case'preview':return this.study.advanced.preview(card);case'occlude':return this.study.advanced.occlude(card);case'edit':return this.edit(card);case'child':return this.workbench.create(card.id);case'links':return this.workbench.links(card);case'review':return this.workbench.configureReview(card);case'unmerge':return this.study.change('study.card.remove',{cardId:card.id,mode:'promote'});case'outdent':return this.nest(card,true);case'root':return this.study.change('study.card.move',{cardId:card.id,parentId:null});case'remove':return this.remove(card);}}));}
  nest(card,out){const set=this.study.current;if(out){if(!card.parentId)return;const parent=set.cards.find(c=>c.id===card.parentId);run(()=>this.study.change('study.card.move',{cardId:card.id,parentId:parent?.parentId||null}))();}else{const siblings=set.cards.filter(c=>c.parentId===card.parentId),i=siblings.findIndex(c=>c.id===card.id);if(i>0)run(()=>this.study.change('study.card.move',{cardId:card.id,parentId:siblings[i-1].id}))();}}
  snapshot(card){if(!card.imageAsset)return this.edit(card);showDialog({title:card.title,html:`<img class="study-snapshot" src="${new URL('data/'+card.imageAsset,base).href}" alt="${escape(card.title)}">${card.text?`<p class="study-snapshot-text">${escape(card.text)}</p>`:''}${card.note?`<p class="dialog-note">${escape(card.note)}</p>`:''}`,onSubmit:null});}
  edit(card){return this.workbench.edit(card);}
  remove(card){const revision=this.study.current.revision;showDialog({title:'删除卡片',html:`<p class="dialog-note">删除「${escape(card.title)}」？图片保留在卡片回收站，原始文件不会改动。</p>`+field('mode','子卡片处理','promote',{choices:[['promote','保留子卡片并提升一级'],['subtree','连同所有子卡片移入回收站']]}),submit:'移入回收站',onSubmit:values=>this.study.change('study.card.remove',{cardId:card.id,mode:values.mode},revision)});}
  trash(){const set=this.study.current;showDialog({title:'卡片回收站',html:set.cardTrash.length?set.cardTrash.map(t=>`<div class="trash-item"><div>${escape(t.title)}<small>${t.count} 张卡片</small></div><button type="button" data-restore="${t.id}">恢复</button></div>`).join(''):'<p class="dialog-note">没有已删除的卡片。</p>',onSubmit:null,afterOpen:()=>{$('dialog-fields').querySelectorAll('[data-restore]').forEach(b=>b.onclick=run(async()=>{b.disabled=true;try{await this.study.change('study.card.restore',{trashId:b.dataset.restore});b.closest('.trash-item').remove();}catch(e){b.disabled=false;throw e;}}));}});}
}
