import {$,escape,field,showDialog,closeDialog,run,toast} from './dom.js';
import {api} from './transport.js';
function pageNumbers(text,max){
 const result=[];for(const word of text.split(/[,，]/)){const token=word.trim();if(/^\d+$/.test(token))result.push(Number(token));else if(/^\d+\s*-\s*\d+$/.test(token)){const [a,b]=token.split('-').map(Number);if(Math.abs(a-b)>2000)throw Error('页码范围过大');for(let n=a;a<=b?n<=b:n>=b;n+=a<=b?1:-1)result.push(n);}else throw Error('页码格式为 1-3,5,8');}
 if(!result.length||result.length>2000||result.some(n=>n<1||n>max))throw Error('页码必须位于文档范围内，最多 2000 页');return result;
}
export class WorkspaceTools{
 constructor(study,reader){
  this.study=study;this.reader=reader;const bar=document.createElement('span');bar.className='workspace-tools';bar.innerHTML='<button id="workspace-search">全库检索</button><button id="virtual-pages">虚拟书页</button><button id="outline-batch-tools">目录整理</button>';$('search-document').before(bar);
  const globalSearch=document.createElement('button');globalSearch.id='library-search-all';globalSearch.textContent='全文检索';$('new-folder').after(globalSearch);globalSearch.onclick=()=>this.search();$('workspace-search').onclick=()=>this.search();$('virtual-pages').onclick=run(()=>this.virtualDialog());$('outline-batch-tools').onclick=()=>this.outline();
 }
 search(){
  let offset=0,next=null,serial=0,busy=false;
  showDialog({title:'文库与卡片检索',html:field('query','关键词 / 条件','',{help:'支持 "精确短语"、AND / OR / NOT、括号，以及 tag:标签、title:标题、path:路径。'})+field('kind','范围','all',{choices:[['all','文档与卡片'],['documents','所有已索引文档'],['cards','所有学习卡片']]})+'<div class="board-actions"><button type="button" id="workspace-search-run">搜索</button><button type="button" id="workspace-index">建立 / 更新全文索引</button><button type="button" id="workspace-search-prev">上一页</button><button type="button" id="workspace-search-next">下一页</button></div><p id="workspace-search-status" role="status">首次搜索未打开的文档前，先建立全文索引。</p><div id="workspace-results"></div>',onSubmit:null,afterOpen:()=>{
   const load=async()=>{const ticket=++serial,query=$('dialog-fields').querySelector('[name=query]').value,kind=$('dialog-fields').querySelector('[name=kind]').value;const data=await api('library.search',{query,kind,offset,limit:50});if(ticket!==serial||!$('workspace-results'))return;next=data.nextOffset;$('workspace-search-status').textContent=`${data.total} 项 · 已索引 ${data.indexedDocuments} 份文档${data.skipped.length?' · '+data.skipped.length+' 份来源变化或不可用，请更新索引':''}`;$('workspace-search-prev').disabled=!offset;$('workspace-search-next').disabled=next===null;$('workspace-results').innerHTML=data.hits.map((hit,i)=>`<button type="button" data-hit="${i}"><strong>${escape(hit.title)}</strong><small>${escape(hit.subtitle)}${hit.locator?.page?' · '+hit.locator.page+' 页':''}</small><p>${escape(hit.snippet)}</p></button>`).join('')||'<p>没有匹配项</p>';$('workspace-results').querySelectorAll('[data-hit]').forEach(b=>b.onclick=run(()=>{const hit=data.hits[Number(b.dataset.hit)];closeDialog();return this.study.content.openUri(hit.uri);}));};
   $('workspace-search-run').onclick=run(()=>{offset=0;return load();});$('workspace-search-prev').onclick=run(()=>{offset=Math.max(0,offset-50);return load();});$('workspace-search-next').onclick=run(()=>{if(next!==null)offset=next;return load();});
   $('workspace-index').onclick=run(async()=>{if(busy)return;busy=true;$('workspace-index').disabled=true;let fileOffset=0,count=0,errors=[];try{do{const result=await api('library.index',{offset:fileOffset,limit:20});count+=result.indexed.length;errors.push(...result.errors);fileOffset=result.nextOffset;if(!$('workspace-search-status'))break;$('workspace-search-status').textContent=`已索引 ${count} / ${result.total} · ${errors.length} 个文件未能解析`;}while(fileOffset!==null);if($('workspace-search-status'))$('workspace-search-status').textContent=`索引完成 ${count} 份${errors.length?'；未完成：'+errors.map(e=>e.path+' ('+e.code+')').join('、'):''}`;}finally{busy=false;if($('workspace-index'))$('workspace-index').disabled=false;}});
   $('dialog-fields').querySelector('[name=query]').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('workspace-search-run').click();}};
  }});
 }
 outline(){
  const doc=this.study.getDocument();if(!doc){toast('先打开一份文档');return;}
  const choices=[['original','恢复文档原始目录'],['numbered','按编号标题生成目录（无 OCR）'],['undo','撤销最近目录编辑'],['redo','重做目录编辑'],['map','目录全部转为脑图'],['batch','批量调整目录']];
  showDialog({title:'目录整理',html:'<div class="organize-actions">'+choices.map(([id,t])=>`<button type="button" data-toc-tool="${id}">${t}</button>`).join('')+'</div>',onSubmit:null,afterOpen:()=>{$('dialog-fields').querySelectorAll('[data-toc-tool]').forEach(b=>b.onclick=run(async()=>{
   const action=b.dataset.tocTool;closeDialog();if(action==='batch')return this.batchOutline(doc);
   if(action==='map'){const set=await this.study.ensureNotes(doc);await this.study.change('study.toc.import',{documentId:doc.id},set.revision);await this.study.change('study.view.set',{view:'map'});return;}
   await api(action==='undo'||action==='redo'?'toc.'+action:'toc.generate',{id:doc.id,expectedRevision:doc.revision,...(['original','numbered'].includes(action)?{strategy:action}:{})});await this.study.openDocument(doc.path,{studySetId:this.study.current?.id});
  }));}});
 }
 batchOutline(doc){
  const selected=new Set();showDialog({title:'批量目录编辑',html:field('action','操作','indent',{choices:[['indent','缩进一级'],['outdent','提升一级'],['remove','删除目录项（保留后代）']]})+'<div class="toc-batch-list">'+doc.toc.map(n=>`<label><input type="checkbox" value="${escape(n.id)}">${escape(n.title)}</label>`).join('')+'</div>',submit:'应用到所选目录',onSubmit:async v=>{if(!selected.size)throw Error('至少选择一项目录');const nodes=doc.toc.filter(n=>selected.has(n.id));await api('toc.batch',{id:doc.id,expectedRevision:doc.revision,operations:nodes.map(n=>({action:v.action,nodeId:n.id,...(v.action==='remove'?{mode:'promote'}:{})}))});await this.study.openDocument(doc.path,{studySetId:this.study.current?.id});},afterOpen:()=>{$('dialog-fields').querySelectorAll('input[type=checkbox]').forEach(el=>el.onchange=()=>el.checked?selected.add(el.value):selected.delete(el.value));}});
 }
 async virtualDialog(){
  const doc=this.study.getDocument();if(doc?.kind!=='pdf'){toast('先打开一份 PDF 或虚拟文档');return;}
  const docs=(await api('document.list',{})).documents.filter(d=>d.kind==='pdf');
  let pages=doc.virtual?structuredClone(doc.virtual.pages):[{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:doc.position.page}],editing=Boolean(doc.virtual),selected=-1;
  const paint=()=>{
   const box=$('virtual-page-list');if(!box)return;box.innerHTML=pages.map((p,i)=>`<div class="virtual-page-row ${selected===i?'selected':''}" draggable="true" data-page-index="${i}"><span>${i+1}.</span><button type="button" data-action="select">${escape(p.blank?'空白页 · '+p.paper:(docs.find(d=>d.id===p.documentId)?.title||p.documentId)+' · '+p.page+' 页')}${p.rotation?' ↻'+p.rotation+'°':''}${p.crop&&(p.crop.width<1||p.crop.height<1)?' · 裁剪':''}</button><button type="button" data-action="up" ${i===0?'disabled':''}>↑</button><button type="button" data-action="down" ${i===pages.length-1?'disabled':''}>↓</button><button type="button" data-action="remove">×</button></div>`).join('');
   box.querySelectorAll('[data-page-index]').forEach(el=>{const i=Number(el.dataset.pageIndex);el.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.action;if(action==='select'){selected=i;const page=pages[i];$('virtual-rotation').value=String(page.rotation||0);$('virtual-crop').value=page.crop?Math.round(Math.min(page.crop.x,page.crop.y)*100):0;}else if(action==='remove'){pages.splice(i,1);selected=-1;}else{const j=i+(action==='up'?-1:1);[pages[i],pages[j]]=[pages[j],pages[i]];selected=j;}box.dispatchEvent(new Event('input',{bubbles:true}));paint();});el.ondragstart=e=>e.dataTransfer.setData('application/x-reader-page-index',String(i));el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const n=Number(e.dataTransfer.getData('application/x-reader-page-index'));if(!Number.isInteger(n)||n<0||n>=pages.length)return;const [p]=pages.splice(n,1);pages.splice(i,0,p);selected=i;box.dispatchEvent(new Event('input',{bubbles:true}));paint();};});
  };
  showDialog({title:editing?'编辑虚拟书页':'新建虚拟书页',html:field('mode','保存方式',editing?'replace':'new',{choices:[['new','新建引用文档'],...(editing?[['replace','更新当前虚拟文档'],['undo','撤销上次重组'],['redo','重做上次重组']]:[])]})+field('path','新建路径',editing?doc.path:doc.path.replace(/\.[^.]+$/,'-选编.mrv'),{required:true})+field('title','名称',doc.title+' · 选编',{required:true})+field('annotations','原文摘录',doc.virtual?.includeAnnotations===false?'no':'yes',{choices:[['yes','同步显示本学习集的原文摘录'],['no','仅显示虚拟文档自己的摘录']]})+'<div id="virtual-page-list"></div><div class="virtual-page-properties"><label>选中页旋转<select id="virtual-rotation"><option>0</option><option>90</option><option>180</option><option>270</option></select></label><label>裁剪边距 %<input id="virtual-crop" type="number" min="0" max="45" value="0"></label><button type="button" id="virtual-apply-crop">应用到选中页</button></div>'+field('sourceId','添加来自',doc.id,{choices:docs.map(d=>[d.id,d.title])})+field('pages','页码','1',{help:'例如 1-5,8,7。引用不会移动原文件。'})+'<div class="board-actions"><button type="button" id="virtual-add-pages">追加页面</button><button type="button" id="virtual-add-blank">插入空白页</button></div><p class="dialog-note">可拖动页面排序。文档保存的是原文引用；源文件变化时需要明确刷新，不会把旧标注坐标套用到新原文。</p>',submit:'保存虚拟文档',onSubmit:async v=>{
   let result;if(v.mode==='new'){
    const versions=(await api('document.list',{})).documents;const normalized=pages.map(p=>p.blank?p:{...p,expectedSourceVersion:versions.find(d=>d.id===p.documentId)?.sourceVersion});
    result=await api('document.virtual.create',{path:v.path,title:v.title,pages:normalized,includeAnnotations:v.annotations==='yes',activate:false});
   }else result=await api('document.virtual.update',{id:doc.id,expectedRevision:doc.revision,action:v.mode==='replace'?'replace':v.mode,...(v.mode==='replace'?{pages,title:v.title,includeAnnotations:v.annotations==='yes'}:{}),activate:false});
   await this.reader.created(result);
  },afterOpen:()=>{
   paint();$('virtual-add-pages').onclick=run(async()=>{const id=$('dialog-fields').querySelector('[name=sourceId]').value,source=await api('document.get',{id});pages.push(...pageNumbers($('dialog-fields').querySelector('[name=pages]').value,source.pageCount).map(page=>({documentId:id,expectedSourceVersion:source.sourceVersion,page})));if(pages.length>2000)throw Error('最多 2000 页');$('virtual-page-list').dispatchEvent(new Event('input',{bubbles:true}));paint();});
   $('virtual-add-blank').onclick=()=>{pages.push({blank:true,paper:'plain',width:595.28,height:841.89});$('virtual-page-list').dispatchEvent(new Event('input',{bubbles:true}));paint();};
   $('virtual-apply-crop').onclick=run(()=>{if(selected<0||!pages[selected])throw Error('先选中一页');if(pages[selected].blank)throw Error('空白页无需裁剪');const margin=Number($('virtual-crop').value)/100;if(!Number.isFinite(margin)||margin<0||margin>.45)throw Error('边距需为 0–45%');pages[selected]={...pages[selected],crop:{x:margin,y:margin,width:1-2*margin,height:1-2*margin},rotation:Number($('virtual-rotation').value)};$('virtual-page-list').dispatchEvent(new Event('input',{bubbles:true}));paint();});
  }});
 }
}
