'use strict';
const assert = require('node:assert/strict');
const { randomUUID, createHash } = require('node:crypto');
const { pdfFixture } = require('./fixtures.cjs');

// Transport-agnostic acceptance: the caller supplies the REAL employee launcher,
// not a mocked runtime. Each declared method must produce a verified outcome.
exports.exercise = async function exercise(call) {
  const success = new Set(), guarded = new Map();
  const api = async (method, params = {}) => {
    const reply = await call(method, params);
    assert(!reply.error, `${method}: ${JSON.stringify(reply.error)}`);
    success.add(method); return reply.result;
  };
  const deny = async (method, params, code) => {
    const reply = await call(method, params);
    assert.equal(reply.error?.data?.code, code, `${method}: ${JSON.stringify(reply)}`);
    guarded.set(method, code);
  };
  const info = await api('system.info'); assert.equal(info.plugin, 'margin-reader');
  await api('fs.mkdir', { path: 'Books' });
  await api('fs.mkdir', { path: 'Exports' });
  await api('fs.write', { path: 'Books/guide.md', content: '# Employee guide\n\nShared CLI content.\n\n## Second\n\nAnother paragraph.' });
  assert((await api('fs.list', { path: 'Books' })).entries.some(item => item.name === 'guide.md'));
  assert(await api('fs.tree'));
  await api('fs.copy', { path: 'Books/guide.md', target: 'Books/copy.md' });
  await api('fs.move', { path: 'Books/copy.md', target: 'Books/moved.md' });
  let trash = await api('fs.trash', { path: 'Books/moved.md' });
  assert(await api('fs.trash.list')); await api('fs.restore', { trashId: trash.trashId });
  const item = (await api('fs.list', { path: 'Books' })).entries.find(item => item.name === 'moved.md');
  const batch = await api('fs.batch', { action: 'copy', items: [{ path: 'Books/moved.md', expectedVersion: item.version }], folder: 'Exports' });
  assert.equal(batch.count, 1);
  const bytes = pdfFixture(), hash = createHash('sha256').update(bytes).digest('hex');
  const upload = await api('import.begin', { path: 'Books/source.pdf', totalBytes: bytes.length });
  assert.equal((await api('import.status', { uploadId: upload.uploadId })).received, 0);
  await api('import.chunk', { uploadId: upload.uploadId, offset: 0, contentBase64: bytes.toString('base64') });
  let pdf = await api('import.finish', { uploadId: upload.uploadId, sha256: hash, activate: false });
  const abort = await api('import.begin', { path: 'Books/aborted.txt', totalBytes: 1 });
  assert.equal((await api('import.abort', { uploadId: abort.uploadId })).aborted, true);
  const doc = await api('document.open', { path: 'Books/guide.md' });
  assert.equal((await api('document.get', { id: doc.id })).id, doc.id);
  assert.match((await api('document.content', { id: doc.id })).text, /Shared CLI/);
  assert((await api('document.search', { id: doc.id, query: 'paragraph' })).matches.length);
  assert((await api('document.list')).documents.length >= 2);
  assert.equal((await api('document.preview', { path: 'Books/source.pdf' })).mimeType, 'image/png');
  await api('document.export', { id: doc.id, format: 'json', path: 'Exports/document.json' });
  let outline = await api('toc.list', { id: doc.id });
  const toc = async (method, params = {}) => outline = await api(method, { id: doc.id, expectedRevision: outline.revision, ...params });
  await toc('toc.add', { title: 'Employee chapter', locator: { section: 0 } });
  const nodeId = outline.toc.find(node => node.title === 'Employee chapter').id;
  await toc('toc.update', { nodeId, title: 'Edited chapter' });
  await toc('toc.indent', { nodeId }); assert(outline.toc.find(node => node.id === nodeId).parentId);
  await toc('toc.outdent', { nodeId }); assert.equal(outline.toc.find(node => node.id === nodeId).parentId, null);
  await toc('toc.move', { nodeId, parentId: null, index: 0 });
  await toc('toc.remove', { nodeId }); await toc('toc.reset');
  let bookmarks = await api('bookmark.add', { id: doc.id, expectedRevision: outline.revision, title: 'Agent bookmark', locator: { section: 0 } });
  const bookmarkId = bookmarks.bookmarks[0].id;
  bookmarks = await api('bookmark.update', { id: doc.id, expectedRevision: bookmarks.revision, bookmarkId, title: 'Renamed bookmark' });
  assert.equal((await api('bookmark.list', { id: doc.id })).bookmarks[0].title, 'Renamed bookmark');
  await api('reader.position.set', { id: pdf.id, locator: { page: 2 } });
  assert.equal((await api('reader.position.get', { id: pdf.id })).locator.page, 2);
  await api('settings.set', { theme: 'dark', pdfMode: 'paged' });
  assert.equal((await api('settings.get')).theme, 'dark');
  await api('reader.comparison.set', { documentId: pdf.id, locator: { page: 1 } });
  assert.equal((await api('reader.position.get', { id: pdf.id })).locator.page, 2);
  await api('reader.comparison.set', { documentId: null });
  await api('reader.tabs.close', { id: pdf.id });
  pdf = await api('document.fold', { id: pdf.id, expectedRevision: pdf.revision, pages: [1] });
  assert.deepEqual(pdf.foldedPages, [1]);
  const notebook = await api('pdf.compose', { path: 'Books/notebook.pdf', pages: [{ documentId: pdf.id, expectedSourceVersion: pdf.sourceVersion, page: 2, rotation: 90 }, { blank: true, paper: 'grid' }], activate: false });
  assert.equal(notebook.pageCount, 2);

  let set = await api('study.create', {mapMode:'cards', title: 'Employee learning' });
  const change = async (method, params = {}) => set = await api(method, { setId: set.id, expectedRevision: set.revision, ...params });
  await change('study.update', { description: 'Real scoped employee API acceptance' });
  assert((await api('study.list')).sets.some(item => item.id === set.id));
  set = await api('study.get', { setId: set.id });
  await change('study.documents.add', { paths: ['Books/source.pdf', 'Books/guide.md'] });
  await api('study.open', { setId: set.id, documentId: pdf.id });
  const capture = { setId: set.id, expectedRevision: set.revision, documentId: pdf.id, expectedSourceVersion: pdf.sourceVersion, captureId: randomUUID(), text: '', color: 'yellow', locator: { page: 1 }, selection: { rects: [{ page: 1, x: .1, y: .05, width: .8, height: .35 }] } };
  const excerpt = await api('study.card.create', capture);
  assert.equal((await api('study.card.create', capture)).card.id, excerpt.card.id);
  set = await api('study.get', { setId: set.id });
  const image = await api('study.card.image', { setId: set.id, cardId: excerpt.card.id });
  assert(Buffer.from(image.contentBase64, 'base64').length > 100);
  await change('study.card.update', { cardId: excerpt.card.id, note: 'Employee annotation', tags: ['acceptance'] });
  assert.equal((await api('study.cards.query', { setId: set.id, tag: 'acceptance' })).cards.length, 1);
  await change('study.note.create', { title: 'Question', text: '**Important** $x^2$', tags: ['acceptance'] });
  const a = set.cards.find(card => card.title === 'Question').id;
  await change('study.note.create', { title: 'Explanation', text: 'Question answer' });
  const b = set.cards.find(card => card.title === 'Explanation').id;
  await change('study.note.anchor', { cardId: a, documentId: pdf.id, locator: { page: 1 }, display: 'embedded' });
  await change('study.card.move', { cardId: b, parentId: a });
  await change('study.card.move', { cardId: b, parentId: null });
  await change('study.link.add', { from: a, to: b, label: 'Explanation', bidirectional: true });
  await change('study.link.remove', { linkId: set.links[0].id });
  const rich = await api('study.card.render', { setId: set.id, cardId: a }); assert.match(rich.html, /katex/);
  assert.equal((await api('study.search', { query: 'acceptance', limit: 1 })).hasMore, true);
  await change('study.view.set', { view: 'cards' }); assert.equal(set.view, 'cards');
  await change('study.layer.create', { title: 'Employee ink' }); const layerId = set.activeLayer;
  await change('study.layer.update', { layerId, title: 'Renamed ink', active: true });
  await change('study.ink.add', { documentId: pdf.id, expectedSourceVersion: pdf.sourceVersion, page: 1, points: [[.2,.2,.3],[.4,.4,.8]], color: 'blue', width: .004 });
  const strokeId = set.ink[0].id;
  await change('study.ink.transform', { strokeIds: [strokeId], dx: .05, dy: .05, color: 'pink' });
  await change('study.canvas.ink.add', { points: [[50,50],[150,100]], color: 'green', width: 2, layerId });
  const canvasStroke = set.canvasInk[0].id;
  await change('study.card.ink.add', { cardId: a, points: [[.1,.2],[.5,.6]], color: 'purple', width: .01, layerId });
  const cardStroke = set.cards.find(card => card.id === a).ink[0].id;
  await change('study.layer.merge', { layerId, targetId: 'default' });
  assert.equal(set.ink[0].layerId, 'default');
  await change('study.ink.remove', { strokeId });
  await change('study.canvas.ink.remove', { strokeId: canvasStroke });
  await change('study.card.ink.remove', { cardId: a, strokeId: cardStroke });
  await change('study.layer.create', { title: 'Recoverable layer' });
  await change('study.layer.remove', { layerId: set.activeLayer });
  await change('study.deck.create', { title: 'Study deck' }); const deckId = set.decks[0].id;
  await change('study.deck.update', { deckId, title: 'Renamed deck' });
  await change('study.review.configure', { cardId: a, enabled: true, deckId, cloze: 'The answer is {{forty two}}.' });
  await change('study.review.settings', { retention: .93, maximumInterval: 100, deckId });
  assert.equal((await api('study.review.queue', { setId: set.id, deckId })).due, 1);
  assert(await api('study.review.preview', { setId: set.id, cardId: a }));
  await change('study.review.grade', { cardId: a, rating: 'good' });
  assert.equal((await api('study.review.stats', { setId: set.id })).reviews, 1);
  await change('study.undo'); assert.equal((await api('study.review.stats', { setId: set.id })).reviews, 0);
  await change('study.redo'); assert.equal((await api('study.review.stats', { setId: set.id })).reviews, 1);
  await deny('study.review.optimize', { setId: set.id, expectedRevision: set.revision }, 'INSUFFICIENT_HISTORY');
  const other = await api('study.create', {mapMode:'cards', title: 'Reference destination' });
  await api('study.card.reference', { setId: other.id, expectedRevision: other.revision, targetSetId: set.id, targetCardId: a });
  await change('study.cards.group', { cardIds: [a,b], title: 'Summary' });
  const summary = set.cards.find(card => card.title === 'Summary').id;
  await change('study.cards.merge', { cardIds: [summary,excerpt.card.id], title: 'Composite' });
  const composite = set.cards.find(card => card.title === 'Composite').id;
  await change('study.map.configure', { layout: 'radial', focusId: composite });
  await change('study.card.remove', { cardId: composite, mode: 'subtree' }); assert.equal(set.cards.length, 0);
  await change('study.card.restore', { trashId: set.cardTrash[0].id }); assert(set.cards.length >= 4);
  await change('study.documents.remove', { documentIds: [doc.id] });
  const exported = await api('study.export', { setId: set.id, path: 'Exports/study.json', includeImages: true });
  assert.equal(exported.cards, set.cards.length);
  await change('study.remove'); assert(set.deletedAt);
  await change('study.restore'); assert.equal(set.deletedAt, null);
  await deny('web.import', { url: 'http://127.0.0.1/blocked', folder: 'Books' }, 'URL_BLOCKED');
  await deny('fs.write', { path: '../outside.md', content: 'blocked' }, 'SCOPE_DENIED');
  await deny('study.card.update', { setId: set.id, expectedRevision: 1, cardId: a, title: 'Stale writer' }, 'CONFLICT');
  await require('./agent-local-surface.cjs').exercise({api, deny});
  await require('./agent-av-surface.cjs').exercise({api,deny});
  await require('./agent-binding-surface.cjs').exercise({api,deny});
  await require('./agent-study-library-surface.cjs').exercise({api,deny});
  await require('./agent-mindmap-surface.cjs').exercise({api,deny});
  await require('./agent-mindmap-completion.cjs').exercise({api,deny});
  const expected = require('../schema.json').commands.map(command => command.method);
  const missing = expected.filter(method => !success.has(method) && !guarded.has(method));
  assert.deepEqual(missing, [], 'Every declared method must be exercised through the employee launcher');
  return { declared: expected.length, successfulMethods: [...success].sort(), guardedMethods: Object.fromEntries(guarded), missing, sourceHash: hash, documentId: pdf.id, studySetId: set.id };
};
