'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {randomUUID}=require('node:crypto'),{setup,pdfFixture}=require('./fixtures.cjs');
const JSZip=require('jszip'),{createCanvas}=require('@napi-rs/canvas');
function wav(){const b=Buffer.alloc(44+1600);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(1600,40);return b;}
async function fixture(t){const f=await setup(t);await fs.writeFile(path.join(f.workspace,'source.pdf'),pdfFixture());let set=await f.api('study.create',{title:'Export 中文🙂'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});await change('study.documents.add',{paths:['source.pdf']});const doc=await f.api('document.open',{path:'source.pdf',activate:false});
const result=await f.api('study.card.create',{setId:set.id,expectedRevision:set.revision,documentId:doc.id,expectedSourceVersion:doc.sourceVersion,captureId:randomUUID(),text:'',title:'Annotated original',color:'yellow',locator:{page:1},selection:{rects:[{page:1,x:.1,y:.1,width:.6,height:.2}]}});set=await f.api('study.get',{setId:set.id});const cardId=result.card.id;
await change('study.note.create',{title:'中文公式',text:'**Source note** $x^2$\n完整正文，不丢失。',parentId:cardId});
await change('study.comment.add',{cardId,text:'音频说明 **bold** <script>bad()</script>'});await change('study.media.import',{cardId,kind:'audio',name:'voice.wav',mimeType:'audio/wav',contentBase64:wav().toString('base64')});
await change('study.review.configure',{cardId,enabled:true,front:'Question $x^2$',back:'Answer 中文',occlusions:[{x:.1,y:.1,width:.4,height:.3}]});
await change('study.ink.add',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:1,points:[[.2,.6],[.8,.6]],color:'red',width:.01});
return {...f,doc,cardId,change,get:()=>f.api('study.get',{setId:set.id}),setId:set.id};}
async function artifact(f,file){if(process.env.MR_EXPORT_ARTIFACTS){await fs.mkdir(process.env.MR_EXPORT_ARTIFACTS,{recursive:true});await fs.copyFile(path.join(f.workspace,file),path.join(process.env.MR_EXPORT_ARTIFACTS,file));}}
test('offline HTML, Markdown and OPML retain full text, hierarchy and local source identities',async t=>{
const f=await fixture(t);for(const format of ['html','md','opml']){const result=await f.api('study.export.file',{setId:f.setId,format,path:'notes.'+format});assert.equal(result.cards,2);await artifact(f,'notes.'+format);}
const html=await fs.readFile(path.join(f.workspace,'notes.html'),'utf8');assert(html.includes('data:audio/wav;base64,'));assert(html.includes('data:image/png;base64,'));assert(html.includes('katex'));assert(!html.includes('<script>'));assert(html.includes('完整正文'));
const opml=await new(require('jsdom').JSDOM)(await fs.readFile(path.join(f.workspace,'notes.opml'),'utf8'),{contentType:'text/xml'});assert.equal(opml.window.document.querySelectorAll('body>outline>outline').length,1);opml.window.close();
assert.deepEqual(await fs.readFile(path.join(f.workspace,'source.pdf')),pdfFixture());
});
test('Word export is a real OOXML document with Unicode, images, source links and explicit audio warning',async t=>{
const f=await fixture(t),r=await f.api('study.export.file',{setId:f.setId,format:'docx',path:'notes.docx'});assert(r.warnings.some(w=>w.includes('Audio')));const bytes=await fs.readFile(path.join(f.workspace,r.path)),zip=await JSZip.loadAsync(bytes);assert(zip.file('word/document.xml'));assert(Object.keys(zip.files).some(p=>p.startsWith('word/media/image')));
const text=await require('mammoth').extractRawText({buffer:bytes});assert(text.value.includes('完整正文'));assert(text.value.includes('margin-reader://card/'));await artifact(f,'notes.docx');
});
test('Anki deck is a valid SQLite-backed APKG with stable GUIDs, masked fronts, audio and clean scheduling',async t=>{
const f=await fixture(t);let first;
for(const file of ['deck.apkg','deck-again.apkg']){const r=await f.api('study.export.file',{setId:f.setId,format:'apkg',path:file});assert.equal(r.notes,2);const zip=await JSZip.loadAsync(await fs.readFile(path.join(f.workspace,file))),media=JSON.parse(await zip.file('media').async('string'));assert.equal(Object.keys(media).length,3);for(const key of Object.keys(media))assert(zip.file(key));const dbFile=path.join(f.workspace,file+'.sqlite');await fs.writeFile(dbFile,await zip.file('collection.anki2').async('nodebuffer'));const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(dbFile,{readOnly:true});assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');const notes=db.prepare('SELECT guid,flds FROM notes ORDER BY id').all();assert(notes[0].flds.includes('[sound:mr-'));assert(notes[0].flds.includes('\\(x^2\\)'));assert.equal(db.prepare('SELECT count(*) AS n FROM cards WHERE type=0 AND queue=0').get().n,2);if(first)assert.deepEqual(notes.map(n=>n.guid),first);else first=notes.map(n=>n.guid);db.close();await artifact(f,file);}
await f.error('study.export.file',{setId:f.setId,format:'apkg',path:'collection.apkg'},'INVALID_PARAMS');
});
async function render(bytes,pageNumber){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs'),base=path.dirname(require.resolve('pdfjs-dist/package.json')),task=pdfjs.getDocument({data:new Uint8Array(bytes),verbosity:0,isEvalSupported:false,standardFontDataUrl:path.join(base,'standard_fonts')+path.sep});try{const pdf=await task.promise,page=await pdf.getPage(pageNumber),v=page.getViewport({scale:1}),canvas=createCanvas(Math.ceil(v.width),Math.ceil(v.height));await page.render({canvasContext:canvas.getContext('2d'),viewport:v}).promise;return canvas;}finally{await task.destroy();}}
test('annotated PDF retains selectable original text and places highlights/ink in exact display coordinates',async t=>{
const f=await fixture(t),result=await f.api('document.pdf.export',{id:f.doc.id,expectedSourceVersion:f.doc.sourceVersion,setIds:[f.setId],path:'annotated.pdf'});assert.equal(result.pages,2);assert.equal(result.originalTextPreserved,true);const bytes=await fs.readFile(path.join(f.workspace,'annotated.pdf')),page=await render(bytes,1),ctx=page.getContext('2d');const mark=ctx.getImageData(Math.round(page.width*.3),Math.round(page.height*.25),1,1).data;assert(mark[0]>mark[2]&&mark[1]>mark[2],String(mark));const line=ctx.getImageData(Math.round(page.width*.5),Math.round(page.height*.6),1,1).data;assert(line[0]>line[1]+50,String(line));const doc=await f.api('document.open',{path:'annotated.pdf',activate:false});assert.match((await f.api('document.content',{id:doc.id,page:1})).text,/Introduction/);assert.deepEqual(await fs.readFile(path.join(f.workspace,'source.pdf')),pdfFixture());await artifact(f,'annotated.pdf');
});
test('mind-map PDF renders real card images and preserves requested branch selection',async t=>{
const f=await fixture(t),result=await f.api('study.export.file',{setId:f.setId,format:'pdf',path:'map.pdf',rootId:f.cardId,expanded:true});assert.equal(result.cards,2);assert(result.pages>=1);const canvas=await render(await fs.readFile(path.join(f.workspace,'map.pdf')),1);assert(canvas.width>1000);const bytes=await canvas.encode('png');assert(bytes.length>10000);await artifact(f,'map.pdf');
if(process.env.MR_EXPORT_ARTIFACTS)await fs.writeFile(path.join(process.env.MR_EXPORT_ARTIFACTS,'map.png'),bytes);
});
test('exports reject stale source/revision, mismatched extension and overwriting before replacing any data',async t=>{
const f=await fixture(t);await f.error('study.export.file',{setId:f.setId,format:'html',path:'../notes.html'},'SCOPE_DENIED');await f.error('study.export.file',{setId:f.setId,format:'pdf',path:'notes.txt'},'INVALID_PARAMS');await f.error('study.export.file',{setId:f.setId,expectedRevision:1,format:'html',path:'stale.html'},'CONFLICT');await f.error('document.pdf.export',{id:f.doc.id,expectedSourceVersion:'bad',path:'bad.pdf'},'SOURCE_CHANGED');assert.equal(await fs.stat(path.join(f.workspace,'bad.pdf')).catch(()=>null),null);
await f.api('study.export.file',{setId:f.setId,format:'html',path:'same.html'});const original=await fs.readFile(path.join(f.workspace,'same.html'));await f.error('study.export.file',{setId:f.setId,format:'html',path:'same.html'},'ALREADY_EXISTS');assert.deepEqual(await fs.readFile(path.join(f.workspace,'same.html')),original);
});
