'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
const {setup,pdfFixture}=require('./fixtures.cjs');
async function fixture(t){const f=await setup(t);let set=await f.api('study.create',{title:'Automatic review'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});await change('study.note.create',{title:'Geography',text:'Paris is in France.'});const id=set.cards[0].id,marks=[{field:'text',start:0,end:5,quote:'Paris',group:'A'},{field:'text',start:12,end:18,quote:'France',group:'B'}];await change('study.card.emphasis.set',{cardId:id,text:marks});await change('study.review.generate',{cardIds:[id]});return {...f,id,marks,change,set:()=>set,get:async()=>set=await f.api('study.get',{setId:set.id})};}
test('source edits update automatic questions once, retain FSRS, re-hide changed questions and leave unrelated edits revealed',async t=>{
 const f=await fixture(t),id=f.id;let s=await f.change('study.review.grade',{cardId:id,rating:'good'}),schedule=structuredClone(s.cards[0].review.schedule),logs=structuredClone(s.cards[0].review.logs);
 await f.change('study.review.session.start',{dueOnly:false});await f.change('study.review.session.action',{action:'reveal',revealed:true});s=await f.change('study.card.update',{cardId:id,tags:['exam']});assert(s.reviewSession.revealed);
 s=await f.change('study.review.configure',{cardId:id,enabled:false});assert(s.reviewSession.revealed);assert(s.cards[0].review.generation);await f.change('study.review.configure',{cardId:id,enabled:true});
 const revision=f.set().revision;s=await f.change('study.card.update',{cardId:id,text:'Paris is IN France.'});assert.equal(s.revision,revision+1);assert.equal(s.reviewSession.revealed,false);assert.match(s.reviewSession.current.front,/IN/);assert.deepEqual(s.cards[0].review.logs,logs);assert.deepEqual(s.cards[0].review.schedule,schedule);
 await f.error('study.review.session.action',{setId:s.id,expectedRevision:s.revision,action:'grade',rating:'easy'},'ANSWER_HIDDEN');
 const before=await fs.readFile(f.workspace+'/.margin-reader/state.json','utf8');await f.get();await f.api('study.review.render',{setId:s.id,cardId:id});await f.api('study.review.queue',{setId:s.id});assert.equal(await fs.readFile(f.workspace+'/.margin-reader/state.json','utf8'),before);
});
test('empty or invalid generated questions leave the queue without losing records and recover through editing/undo',async t=>{
 const f=await fixture(t);await f.change('study.review.grade',{cardId:f.id,rating:'good'});let s=await f.change('study.card.emphasis.set',{cardId:f.id,text:[]});assert.equal(s.cards[0].review.generation.status,'empty');assert.equal(s.cards[0].review.enabled,true);assert.equal(s.review.total,0);assert.equal(s.cards[0].review.logs.length,1);
 s=await f.change('study.undo');assert.equal(s.cards[0].review.generation.status,'ready');assert.equal(s.review.total,1);assert.equal(s.cards[0].review.logs.length,1);
 await f.change('study.card.update',{cardId:f.id,text:'{{Paris}} is in France.'});s=await f.change('study.card.emphasis.set',{cardId:f.id,text:[{field:'text',start:0,end:9,quote:'{{Paris}}',group:'A'}]});assert.equal(s.cards[0].review.generation.status,'invalid');assert.equal(s.review.total,0);assert(s.cards[0].review.generation.warnings[0].includes('delimiters'));assert.equal(s.cards[0].text,'{{Paris}} is in France.');
 s=await f.change('study.card.emphasis.set',{cardId:f.id,text:[{field:'text',start:2,end:7,quote:'Paris',group:'A'}]});assert.equal(s.cards[0].review.generation.status,'ready');assert.equal(s.review.total,1);
});
test('manual edits and explicit snapshots detach rules while suspension and undo preserve automatic behavior',async t=>{
 const f=await fixture(t);await f.change('study.review.configure',{cardId:f.id,enabled:false});let s=await f.change('study.card.emphasis.set',{cardId:f.id,text:[f.marks[0]]});assert(s.cards[0].review.generation);assert.equal(s.cards[0].review.enabled,false);assert(!s.cards[0].review.cloze.includes('{{c2::'));
 s=await f.change('study.review.configure',{cardId:f.id,enabled:true,cloze:'',front:'Manual question'});assert.equal(s.cards[0].review.generation,undefined);await f.change('study.card.emphasis.set',{cardId:f.id,text:f.marks});assert.equal(f.set().cards[0].review.front,'Manual question');
 s=await f.change('study.review.generate',{cardIds:[f.id],autoUpdate:false});const frozen=s.cards[0].review.cloze;await f.change('study.card.emphasis.set',{cardId:f.id,text:[]});assert.equal(f.set().cards[0].review.cloze,frozen);
 await f.change('study.card.emphasis.set',{cardId:f.id,text:f.marks});await f.change('study.review.generate',{cardIds:[f.id]});s=await f.change('study.review.configure',{cardId:f.id,enabled:true,autoUpdate:false});assert.equal(s.cards[0].review.generation,undefined);s=await f.change('study.undo');assert.equal(s.cards[0].review.generation.status,'ready');
});
test('a changed live reference updates its own generated question revision without writing another workspace or copying schedules',async t=>{
 const f=await fixture(t),source=f.set();let target=await f.api('study.create',{title:'References'});const change=async(m,p)=>target=await f.api(m,{setId:target.id,expectedRevision:target.revision,...p});
 await change('study.card.reference',{targetSetId:source.id,targetCardId:f.id});const id=target.cards[0].id;await change('study.card.emphasis.set',{cardId:id,text:[f.marks[0]]});await change('study.review.generate',{cardIds:[id]});await change('study.review.session.start',{});await change('study.review.session.action',{action:'reveal'});const prior=target.revision;
 await f.change('study.card.update',{cardId:f.id,text:'Paris IS in France.'});target=await f.api('study.get',{setId:target.id});assert.equal(target.revision,prior+1);assert.match(target.reviewSession.current.front,/IS/);assert.equal(target.reviewSession.revealed,false);assert.equal(target.cards[0].review.logs.length,0);
 await f.error('study.review.session.action',{setId:target.id,expectedRevision:prior,action:'grade',rating:'good'},'CONFLICT');
});
test('document highlighter changes, layer visibility and notebook selection refresh questions atomically and persist after reopening',async t=>{
 const f=await setup(t);await fs.writeFile(f.workspace+'/book.pdf',pdfFixture());const doc=await f.api('document.open',{path:'book.pdf'});let set=await f.api('study.create',{title:'Highlighters'});const change=async(m,p)=>{set=await f.api('study.get',{setId:set.id});const result=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});set=await f.api('study.get',{setId:set.id});return result;};await change('study.documents.add',{paths:['book.pdf']});
 const captured=await change('study.card.create',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,captureId:require('node:crypto').randomUUID(),title:'Question',text:'',color:'yellow',locator:{page:1},selection:{rects:[{page:1,x:0,y:0,width:.8,height:.25}]}}),id=captured.card.id;
 await change('study.ink.add',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:1,points:[[.1,.1],[.4,.1]],width:.01,color:'yellow',brush:'highlighter'});const stroke=set.ink[0].id;await change('study.review.generate',{cardIds:[id],rules:{textEmphasis:false,imageEmphasis:false,cardHighlighter:false}});const initial=set.cards[0].review.occlusions[0].x;
 const revision=set.revision;await change('study.ink.batch',{scope:'document',strokeIds:[stroke],action:'transform',dx:.1});assert.equal(set.revision,revision+1);assert(set.cards[0].review.occlusions[0].x>initial);
 await change('study.ink.batch',{scope:'document',strokeIds:[stroke],action:'transform',hidden:true});assert.equal(set.cards[0].review.generation.status,'empty');await change('study.undo',{});assert.equal(set.cards[0].review.generation.status,'ready');
 await change('study.layer.update',{layerId:'default',visible:false});assert.equal(set.cards[0].review.generation.status,'empty');await change('study.layer.update',{layerId:'default',visible:true});assert.equal(set.cards[0].review.generation.status,'ready');
 await change('study.notebook.create',{documentId:doc.id,title:'Other notes'});const notebookId=set.lastNotebookId;await change('study.notebook.select',{documentId:doc.id,notebookId,showOthers:false});assert.equal(set.cards[0].review.generation.status,'empty');await change('study.notebook.select',{documentId:doc.id,notebookId:'default',showOthers:true});assert.equal(set.cards[0].review.generation.status,'ready');
 const {validateSet}=require('../lib/study-package.cjs'),disk=JSON.parse(await fs.readFile(f.workspace+'/.margin-reader/state.json','utf8'));assert.doesNotThrow(()=>validateSet(disk.studySets[set.id]));
 await f.runtime.close();const opened=await require('../runtime.cjs').createPlugin({workspace:f.workspace});try{const reply=await opened.request({jsonrpc:'2.0',id:1,method:'study.get',params:{setId:set.id}});assert.equal(reply.result.cards[0].review.generation.status,'ready');assert(reply.result.cards[0].review.occlusions[0].x>initial);}finally{await opened.close();}
});
test('comment lifecycle and image edits refresh only their generated content and survive portable restore',async t=>{
 const f=await fixture(t);let s=await f.change('study.comment.add',{cardId:f.id,text:'Europe context'}),comment=s.cards[0].comments[0];
 await f.change('study.card.emphasis.set',{cardId:f.id,text:[...f.marks,{field:'comment:'+comment.id,start:0,end:6,quote:'Europe',group:'C'}]});assert.match(f.set().cards[0].review.cloze,/Europe/);
 s=await f.change('study.comment.update',{cardId:f.id,commentId:comment.id,text:'Europe has new context'});assert.match(s.cards[0].review.cloze,/new context/);s=await f.change('study.comment.update',{cardId:f.id,commentId:comment.id,deleted:true});assert(!s.cards[0].review.cloze.includes('Europe'));s=await f.change('study.comment.update',{cardId:f.id,commentId:comment.id,deleted:false});assert.match(s.cards[0].review.cloze,/Europe/);
 const canvas=require('@napi-rs/canvas').createCanvas(80,80);s=await f.change('study.media.import',{kind:'image',title:'Image marks',contentBase64:(await canvas.encode('png')).toString('base64')});const image=s.cards.at(-1).id;
 await f.change('study.card.emphasis.set',{cardId:image,images:[{x:.1,y:.2,width:.3,height:.2,group:'One'}]});await f.change('study.review.generate',{cardIds:[image]});s=await f.change('study.card.emphasis.set',{cardId:image,images:[{x:.2,y:.2,width:.3,height:.2,group:'One'}]});assert.equal(s.cards.at(-1).review.occlusions[0].x,.2);
 s=await f.change('study.media.transform',{cardId:image,rotation:90});assert(s.cards.at(-1).review.generation);assert.equal(s.cards.at(-1).review.generation.status,'ready');assert(Math.abs(s.cards.at(-1).review.occlusions[0].x-.6)<1e-9);
 await f.api('study.package.export',{setId:s.id,path:'automatic.mrpkg'});const imported=await f.api('study.package.import',{path:'automatic.mrpkg',folder:'Auto restored'});let restored=await f.api('study.get',{setId:imported.setId});const restoredImage=restored.cards.find(c=>c.title==='Image marks');restored=await f.api('study.card.emphasis.set',{setId:restored.id,expectedRevision:restored.revision,cardId:restoredImage.id,images:[]});assert.equal(restored.cards.find(c=>c.id===restoredImage.id).review.generation.status,'empty');assert.equal(restored.review.total,1);
});
