'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),{createCanvas,loadImage}=require('@napi-rs/canvas');
const {setup}=require('./fixtures.cjs'),I=require('../lib/image-ink.cjs'),unit={x:0,y:0,width:1,height:1};
async function fixture(t){const f=await setup(t),canvas=createCanvas(200,100),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,200,100);let set=await f.api('study.create',{title:'Image handwriting'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});await change('study.media.import',{kind:'image',title:'Picture',contentBase64:(await canvas.encode('png')).toString('base64')});return {...f,change,set:()=>set,id:set.cards[0].id};}
async function colorCount(bytes,color){const image=await loadImage(bytes),canvas=createCanvas(image.width,image.height),ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const data=ctx.getImageData(0,0,image.width,image.height).data;let n=0;for(let i=0;i<data.length;i+=4)if(color.every((v,j)=>data[i+j]===v))n++;return n;}
test('pressure ink stays attached through crop/rotation, layout changes, copying and undo without altering originals',async t=>{
 const f=await fixture(t),original=await f.api('study.card.image',{setId:f.set().id,cardId:f.id});let s=await f.change('study.card.ink.add',{cardId:f.id,imageBound:true,imageBounds:unit,points:[[.2,.5,.2],[.8,.5,.8]],color:'blue',width:.01});const id=s.cards[0].ink[0].id;
 s=await f.change('study.media.transform',{cardId:f.id,crop:{x:.25,y:0,width:.5,height:1},rotation:90});let ink=I.project(s.cards[0].ink[0]);assert.equal(ink.id,id);assert(ink.imageBound);assert(ink.points.every(p=>Math.abs(p[0]-.5)<1e-9));assert(ink.points[0][1]<0&&ink.points.at(-1)[1]>1);assert(Math.abs(ink.width-.02)<1e-9);assert(ink.points.every(p=>p[2]>=.2&&p[2]<=.8));
 const saved=structuredClone(s.cards[0].ink);s=await f.change('study.cards.batch',{cardIds:[f.id],patch:{style:{width:400,height:300}}});assert.deepEqual(s.cards[0].ink,saved);
 const other=await f.api('study.create',{title:'Copy'});await f.change('study.cards.copy',{cardIds:[f.id],targetSetId:other.id,targetRevision:other.revision});const copied=await f.api('study.get',{setId:other.id});assert.deepEqual(copied.cards[0].ink,saved);
 await f.change('study.undo');await f.change('study.undo');s=await f.change('study.undo');assert.equal(s.cards[0].ink[0].id,id);assert.deepEqual(await f.api('study.card.image',{setId:s.id,cardId:f.id}),original);
 const disk=JSON.parse(await fs.readFile(f.workspace+'/.margin-reader/state.json','utf8'));assert.doesNotThrow(()=>require('../lib/study-package.cjs').validateSet(disk.studySets[s.id]));
});
test('mixed card/image edits and partial erasing use the supplied display frame; binding and unbinding remain reversible',async t=>{
 const f=await fixture(t),first={x:.1,y:.2,width:.8,height:.4},current={x:.2,y:.1,width:.6,height:.3};let s=await f.change('study.card.ink.add',{cardId:f.id,imageBound:true,imageBounds:first,points:[[.26,.4],[.74,.4]],color:'blue',width:.008});const id=s.cards[0].ink[0].id;
 s=await f.change('study.card.ink.add',{cardId:f.id,points:[[.1,.9],[.3,.9]],color:'red',width:.01});const ordinary=structuredClone(s.cards[0].ink[1]);s=await f.change('study.ink.batch',{scope:'card',cardId:f.id,strokeIds:[id],action:'transform',dx:.06,imageBounds:current});assert(Math.abs(I.project(s.cards[0].ink[0]).points[0][0]-.3)<1e-9);
 s=await f.change('study.ink.erase',{scope:'card',cardId:f.id,path:[[.5,.05],[.5,.5]],radius:.01,aspectRatio:1,imageBounds:current});assert.equal(s.lastInk.erased,1);assert.equal(s.cards[0].ink.filter(I.bound).length,2);assert.deepEqual(s.cards[0].ink.find(x=>x.id===ordinary.id),ordinary);
 s=await f.change('study.undo');s=await f.change('study.ink.batch',{scope:'card',cardId:f.id,strokeIds:[id],action:'transform',imageBound:false,imageBounds:current});assert.equal(s.cards[0].ink[0].imageBound,false);const position=structuredClone(s.cards[0].ink[0].points);s=await f.change('study.media.transform',{cardId:f.id,rotation:90});assert.deepEqual(s.cards[0].ink[0].points,position);
 s=await f.change('study.ink.batch',{scope:'card',cardId:f.id,strokeIds:[id],action:'transform',imageBound:true,imageBounds:current});assert(s.cards[0].ink[0].imageBound);const disk=JSON.parse(await fs.readFile(f.workspace+'/.margin-reader/state.json','utf8'));assert.doesNotThrow(()=>require('../lib/study-package.cjs').validateSet(disk.studySets[s.id]));await f.change('study.undo');assert.equal(f.set().cards[0].ink[0].imageBound,false);
});
test('detaching image ink uses canonical map image geometry and removes obsolete binding metadata',async t=>{
 const f=await fixture(t);await f.change('study.cards.batch',{cardIds:[f.id],patch:{style:{width:400,height:300}}});let s=await f.change('study.card.ink.add',{cardId:f.id,imageBound:true,imageBounds:unit,points:[[.3,.4],[.7,.6]],color:'blue',width:.01});const ink=s.cards[0].ink[0],geometry=await f.api('study.map.geometry',{setId:s.id}),box=geometry.positions[0],frame=box.imageBounds;
 s=await f.change('study.ink.detach',{cardId:f.id,strokeIds:[ink.id],copy:true});const free=s.canvasInk.at(-1);assert.equal(free.imageBound,undefined);assert.equal(free.imageBounds,undefined);assert(Math.abs(free.points[0][0]-(box.x+(frame.x+.3*frame.width)*box.width))<1e-9);assert(Math.abs(free.points[0][1]-(box.y+(frame.y+.4*frame.height)*box.height))<1e-9);assert.equal(s.cards[0].ink.length,1);
});
test('image highlighter masks regenerate after image edits; image replacement removes only attached ink and undo restores it',async t=>{
 const f=await fixture(t);await f.change('study.card.ink.add',{cardId:f.id,imageBound:true,imageBounds:unit,points:[[.2,.3],[.7,.3]],color:'yellow',brush:'highlighter',width:.02});await f.change('study.card.ink.add',{cardId:f.id,points:[[.1,.9],[.9,.9]],color:'blue',width:.01});let s=await f.change('study.review.generate',{cardIds:[f.id],rules:{documentHighlighter:false,textEmphasis:false,imageEmphasis:false}});const old=s.cards[0].review.occlusions[0];
 s=await f.change('study.media.transform',{cardId:f.id,rotation:90});assert.equal(s.cards[0].review.generation.status,'ready');const mask=s.cards[0].review.occlusions[0];assert(mask.height>mask.width);assert(Math.abs(mask.x+mask.width/2-(1-(old.y+old.height/2)))<1e-9);
 const replacement=await createCanvas(80,80).encode('png');s=await f.change('study.media.import',{cardId:f.id,kind:'image',contentBase64:replacement.toString('base64')});assert.equal(s.cards[0].ink.length,1);assert(!s.cards[0].ink[0].imageBound);assert.equal(s.cards[0].review.generation.status,'empty');s=await f.change('study.undo');assert.equal(s.cards[0].ink.length,2);assert.equal(s.cards[0].review.generation.status,'ready');
});
test('image-bound handwriting is rendered into HTML/Word/Anki exports and separated by review side',async t=>{
 const f=await fixture(t),original=await f.api('study.card.image',{setId:f.set().id,cardId:f.id});await f.change('study.card.ink.add',{cardId:f.id,imageBound:true,imageBounds:unit,points:[[.1,.3],[.9,.3]],color:'blue',width:.02});await f.change('study.card.ink.add',{cardId:f.id,imageBound:true,imageBounds:unit,reviewSide:'front',points:[[.1,.7],[.9,.7]],color:'red',width:.02});let s=await f.change('study.review.configure',{cardId:f.id,enabled:true,frontMode:'card'});
 const face=await f.api('study.review.render',{setId:s.id,cardId:f.id});assert.equal(face.ink.length,0);assert.equal(face.frontImageInk.length,2);assert.equal(face.backImageInk.length,1);
 await f.api('study.export.file',{setId:s.id,format:'html',path:'ink.html'});const html=await fs.readFile(f.workspace+'/ink.html','utf8'),png=Buffer.from(html.match(/<img src="data:image\/png;base64,([^"]+)"/)[1],'base64');assert(await colorCount(png,[84,164,237])>10);assert.equal(await colorCount(png,[227,93,106]),0);
 await f.api('study.export.file',{setId:s.id,format:'docx',path:'ink.docx'});let zip=await require('jszip').loadAsync(await fs.readFile(f.workspace+'/ink.docx'));assert(await colorCount(await zip.file('word/media/image1.png').async('nodebuffer'),[84,164,237])>10);
 await f.api('study.export.file',{setId:s.id,format:'apkg',path:'ink.apkg'});zip=await require('jszip').loadAsync(await fs.readFile(f.workspace+'/ink.apkg'));const media=JSON.parse(await zip.file('media').async('string'));let red=0,blue=0;for(const key of Object.keys(media)){const bytes=await zip.file(key).async('nodebuffer');red+=await colorCount(bytes,[227,93,106]);blue+=await colorCount(bytes,[84,164,237]);}assert(red>10&&blue>10);assert.deepEqual(await f.api('study.card.image',{setId:s.id,cardId:f.id}),original);
 await f.api('study.export.file',{setId:s.id,format:'pdf',path:'ink.pdf'});const pdf=await f.api('document.open',{path:'ink.pdf',activate:false});await f.change('study.documents.add',{paths:['ink.pdf']});const current=f.set(),captured=await f.api('study.card.create',{setId:current.id,expectedRevision:current.revision,documentId:pdf.id,expectedSourceVersion:pdf.sourceVersion,captureId:require('node:crypto').randomUUID(),title:'Export pixels',text:'',color:'yellow',locator:{page:1},selection:{rects:[{page:1,x:0,y:0,width:1,height:1}]}}),raster=await f.api('study.card.image',{setId:current.id,cardId:captured.card.id});assert(await colorCount(Buffer.from(raster.contentBase64,'base64'),[84,164,237])>10);
});
test('legacy in-image bounds project without read migrations and remain editable after portable restore',async t=>{
 const f=await fixture(t);let s=await f.change('study.card.ink.add',{cardId:f.id,imageBounds:{x:.1,y:.2,width:.8,height:.4},aspectRatio:1,points:[[.26,.4,.2],[.74,.4,.8]],color:'blue',width:.008});const file=f.workspace+'/.margin-reader/state.json',disk=JSON.parse(await fs.readFile(file,'utf8'));delete disk.studySets[s.id].cards[0].ink[0].imageBound;await fs.writeFile(file,JSON.stringify(disk));const before=await fs.readFile(file,'utf8');const view=await f.api('study.get',{setId:s.id});assert(view.cards[0].ink[0].imageBound);assert.equal(await fs.readFile(file,'utf8'),before);
 s=await f.change('study.media.transform',{cardId:f.id,rotation:90});assert(s.cards[0].ink[0].imageBound);assert(I.project(s.cards[0].ink[0]).points.every(p=>Math.abs(p[0]-.5)<1e-9));
 await f.api('study.package.export',{setId:s.id,path:'image-ink.mrpkg'});const imported=await f.api('study.package.import',{path:'image-ink.mrpkg',folder:'Restored ink'});let restored=await f.api('study.get',{setId:imported.setId});assert.deepEqual(restored.cards[0].ink[0].points,s.cards[0].ink[0].points);const id=restored.cards[0].id,strokeId=restored.cards[0].ink[0].id;restored=await f.api('study.ink.batch',{setId:restored.id,expectedRevision:restored.revision,scope:'card',cardId:id,strokeIds:[strokeId],action:'transform',dy:.02});assert(restored.cards[0].ink[0].imageBound);
});
test('transparent exported image strokes do not darken their own segment joins',async t=>{
 const f=await fixture(t),source=Buffer.from((await f.api('study.card.image',{setId:f.set().id,cardId:f.id})).contentBase64,'base64');
 for(const value of [{brush:'highlighter',points:[[.1,.5],[.5,.5],[.9,.5]],opacity:.35},{brush:'pen',points:[[.1,.5,.2],[.5,.5,.8],[.9,.5,.4]],opacity:.5}]){
  const bytes=await I.paint(source,[{...value,imageBound:true,imageBounds:unit,width:.04,color:'blue'}]);const image=await loadImage(bytes),canvas=createCanvas(image.width,image.height),ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const at=x=>[...ctx.getImageData(x,50,1,1).data];assert.deepEqual(at(100),at(70));assert.deepEqual(at(130),at(70));assert(at(70)[0]>84&&at(70)[0]<255);
 }
});
