'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),{createCanvas,loadImage}=require('@napi-rs/canvas');
const {create,expect}=require('./ui-session.cjs');
async function colorBox(locator,color){await expect(locator).toBeVisible();const pixels=await locator.screenshot(),box=await locator.boundingBox();assert(box,'The painted image must expose a current bounding box');const image=await loadImage(pixels),canvas=createCanvas(image.width,image.height),ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const rgba=ctx.getImageData(0,0,image.width,image.height).data;let left=image.width,right=-1,top=image.height,bottom=-1,count=0;for(let y=0;y<image.height;y++)for(let x=0;x<image.width;x++){const i=(y*image.width+x)*4;if(color.every((v,j)=>Math.abs(rgba[i+j]-v)<3)){left=Math.min(left,x);right=Math.max(right,x+1);top=Math.min(top,y);bottom=Math.max(bottom,y+1);count++;}}assert(count>5,'Expected visible colored pixels');return {x:box.x+left/image.width*box.width,y:box.y+top/image.height*box.height,width:(right-left)/image.width*box.width,height:(bottom-top)/image.height*box.height,count};}
(async()=>{const f=await create('image-ink');let failure;
 try{const {page,api}=f,canvas=createCanvas(200,100),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,200,100);ctx.fillStyle='#dc4738';ctx.fillRect(60,18,80,14);let set=await api('study.create',{title:'图片手写绑定'});set=await api('study.media.import',{setId:set.id,expectedRevision:set.revision,kind:'image',title:'Image ink',contentBase64:(await canvas.encode('png')).toString('base64')});const id=set.cards[0].id;await api('study.open',{setId:set.id});await page.goto(f.server.url);await page.waitForSelector('body[data-ready=true]');const card=page.locator(`.study-card[data-card-id="${id}"]`),picture=card.locator('img');
  const red=await colorBox(picture,[220,71,56]),box=await card.boundingBox(),geometry=await api('study.map.geometry',{setId:set.id}),bounds=geometry.positions[0].imageBounds;assert(Math.abs(red.x-(box.x+(bounds.x+.3*bounds.width)*box.width))<3);assert(Math.abs(red.y-(box.y+(bounds.y+.18*bounds.height)*box.height))<3);
  await page.click('#card-ink-settings');await page.selectOption('[name=brush]','pen');await page.selectOption('[name=color]','blue');await page.fill('[name=cardWidth]','2');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('#card-ink-pen');await page.mouse.move(red.x+red.width*.125,red.y+red.height/2);await page.mouse.down();await page.mouse.move(red.x+red.width*.875,red.y+red.height/2,{steps:12});await page.mouse.up();await expect.poll(async()=>((await api('study.get',{setId:set.id})).cards[0].ink||[]).length).toBe(1);await page.click('#card-ink-pen');set=await api('study.get',{setId:set.id});assert(set.cards[0].ink[0].imageBound);let blue=await colorBox(picture,[84,164,237]);assert(blue.width>blue.height*3);
  f.pass('Actual card pixels agree with Core image bounds, and a real pen gesture binds to the image');
  const menu=async action=>{await card.locator('.study-card-more').click();await page.click(`[data-action="${action}"]`);};await menu('transform');await page.selectOption('[name=rotation]','90');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await expect.poll(async()=>{const b=await colorBox(picture,[84,164,237]);return b.height>b.width*3;}).toBe(true);blue=await colorBox(picture,[84,164,237]);const rotatedRed=await colorBox(picture,[220,71,56]);assert(Math.abs(blue.x+blue.width/2-(rotatedRed.x+rotatedRed.width/2))<3);
  set=await api('study.get',{setId:set.id});await api('study.cards.batch',{setId:set.id,expectedRevision:set.revision,cardIds:[id],patch:{style:{width:400,height:400}}});await expect(card).toHaveCSS('width','400px');blue=await colorBox(picture,[84,164,237]);const largeRed=await colorBox(picture,[220,71,56]);assert(blue.height>blue.width*3);assert(Math.abs(blue.x+blue.width/2-(largeRed.x+largeRed.width/2))<3);
  f.pass('Rotating the real image and resizing its card keep the rendered ink on the same colored image feature');
  await page.click('#card-ink-settings');await page.selectOption('[name=eraser]','partial');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('#card-ink-eraser');await page.mouse.move(blue.x-20,blue.y+blue.height/2);await page.mouse.down();await page.mouse.move(blue.x+blue.width+20,blue.y+blue.height/2,{steps:8});await page.mouse.up();await expect.poll(async()=>((await api('study.get',{setId:set.id})).cards[0].ink||[]).length).toBe(2);await page.click('#card-ink-eraser');await page.click('#study-undo');await expect.poll(async()=>((await api('study.get',{setId:set.id})).cards[0].ink||[]).length).toBe(1);
  blue=await colorBox(picture,[84,164,237]);await page.click('#card-ink-lasso');await page.mouse.move(blue.x-12,blue.y-12);await page.mouse.down();for(const [x,y] of [[blue.x+blue.width+12,blue.y-12],[blue.x+blue.width+12,blue.y+blue.height+12],[blue.x-12,blue.y+blue.height+12],[blue.x-12,blue.y-12]])await page.mouse.move(x,y,{steps:3});await page.mouse.up();await expect(page.locator('#dialog')).toContainText('处理 1 条笔迹');await page.fill('[name=dx]','2');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('#card-ink-lasso');const moved=await colorBox(picture,[84,164,237]);assert(moved.x>blue.x+4);
  f.pass('Partial erasing, undo and lasso movement operate on displayed image-bound strokes');
  await menu('review');await page.selectOption('[name=frontMode]','card');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('[data-study-view=review]');await expect(page.locator('.review-image-wrap .image-bound-overlay [data-card-stroke]')).toHaveCount(1);await expect(page.locator('.review-handwriting')).toHaveCount(0);await page.reload();await page.waitForSelector('body[data-ready=true]');await expect(page.locator('.review-image-wrap .image-bound-overlay [data-card-stroke]')).toHaveCount(1);const reviewImage=await page.locator('.review-image-wrap').boundingBox();assert(reviewImage.height<=400);assert(reviewImage.y+reviewImage.height<1000);await page.screenshot({path:path.join(f.output,'image-ink-review.png')});
  f.pass('Review and reopening fit the whole image in the viewport and render attached ink without a duplicate panel');
  set=await api('study.get',{setId:set.id});set=await api('study.card.update',{setId:set.id,expectedRevision:set.revision,cardId:id,note:'First context line.\n'.repeat(250)});set=await api('study.note.create',{setId:set.id,expectedRevision:set.revision,title:'Second question',text:'Second context line.\n'.repeat(250)});const second=set.cards.at(-1).id;set=await api('study.review.configure',{setId:set.id,expectedRevision:set.revision,cardId:second,enabled:true,frontMode:'card'});await api('study.review.session.start',{setId:set.id,expectedRevision:set.revision,cardIds:[id,second],mode:'practice',sort:'outline'});await expect(page.locator('#review-session-next')).toBeEnabled();await page.locator('#study-cards-panel').evaluate(el=>{el.scrollTop=el.scrollHeight;});await page.click('#review-session-next');await expect(page.locator('.study-review-front')).toContainText('Second question');await expect.poll(()=>page.locator('#study-cards-panel').evaluate(el=>el.scrollTop)).toBe(0);f.pass('Navigating from a scrolled long card opens the next long question at its beginning');

 }catch(e){failure=e;}f.report.validation={passed:f.report.checks,failed:failure?[failure.message]:[],skipped:[],untested:['Windows','Linux','physical pen hardware']};await f.finish(failure);
})().catch(e=>{console.error(e);process.exitCode=1;});
