'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{createCanvas,loadImage}=require('@napi-rs/canvas');
const {setup}=require('./fixtures.cjs');
async function png(){const c=createCanvas(200,100),x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,200,100);x.fillStyle='#2070d0';x.fillRect(20,20,50,30);x.fillStyle='#d03020';x.fillRect(160,10,30,30);return c.encode('png');}
const blue={x:.1,y:.2,width:.25,height:.3},red={x:.8,y:.1,width:.15,height:.3};
async function fixture(t){const f=await setup(t);let set=await f.api('study.create',{title:'Image annotation edits'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});set=await change('study.media.import',{kind:'image',title:'Colors',contentBase64:(await png()).toString('base64')});const id=set.cards[0].id;return {...f,change,id,set:()=>set};}
async function checkBlue(api,set,id,rect){const result=await api('study.card.image',{setId:set.id,cardId:id}),image=await loadImage(Buffer.from(result.contentBase64,'base64')),canvas=createCanvas(image.width,image.height),ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,image.width,image.height).data;let left=image.width,right=0,top=image.height,bottom=0;
 for(let y=0;y<image.height;y++)for(let x=0;x<image.width;x++){const i=(y*image.width+x)*4;if(pixels[i]===32&&pixels[i+1]===112&&pixels[i+2]===208){left=Math.min(left,x);right=Math.max(right,x+1);top=Math.min(top,y);bottom=Math.max(bottom,y+1);}}
 assert(right>left);if(!rect)return {x:left/image.width,y:top/image.height,width:(right-left)/image.width,height:(bottom-top)/image.height};assert(Math.abs(rect.x*image.width-left)<=1);assert(Math.abs(rect.y*image.height-top)<=1);assert(Math.abs((rect.x+rect.width)*image.width-right)<=1);assert(Math.abs((rect.y+rect.height)*image.height-bottom)<=1);
}
test('crop/rotation tracks actual pixels, keeps group schedules, archives cropped questions and reverses with the raster',async t=>{
 const f=await fixture(t),id=f.id;await f.change('study.card.emphasis.set',{cardId:id,images:[{...blue,group:'Blue'},{...red,group:'Red'}]});
 await f.change('study.review.configure',{cardId:id,enabled:true,occlusions:[blue,red],occlusionGroups:[3,7],revealMode:'independent'});
 await f.change('study.review.grade',{cardId:id,variantId:'mask3',rating:'good'});let s=await f.change('study.review.grade',{cardId:id,variantId:'mask7',rating:'easy'});const prior=structuredClone(s.cards[0]),original=await f.api('study.media.get',{setId:s.id,mediaId:prior.media.id});
 s=await f.change('study.media.transform',{cardId:id,crop:{x:.2,y:0,width:.5,height:1},rotation:90});let card=s.cards[0];assert.equal(card.emphasis.images.length,1);assert.equal(card.emphasis.images[0].group,'Blue');assert.equal(card.review.variants.length,1);assert.equal(card.review.variants[0].id,'mask3');assert.deepEqual(card.review.variants[0].schedule,prior.review.variants[0].schedule);assert.deepEqual(card.review.logs,prior.review.logs);assert.deepEqual(card.review.variantArchive.mask7.logs,prior.review.variants[1].logs);
 assert.deepEqual(card.review.occlusionGroups,[3]);await checkBlue(f.api,s,id,card.review.occlusions[0]);await checkBlue(f.api,s,id,card.emphasis.images[0]);assert.equal((await f.api('study.media.get',{setId:s.id,mediaId:prior.media.id})).contentBase64,original.contentBase64);
 const edited=structuredClone(card);s=await f.change('study.undo');assert.equal(s.cards[0].mediaId,prior.mediaId);assert.deepEqual(s.cards[0].review,prior.review);assert.deepEqual(s.cards[0].emphasis,prior.emphasis);s=await f.change('study.redo');assert.equal(s.cards[0].mediaId,edited.mediaId);assert.deepEqual(s.cards[0].review,edited.review);
 const other=await f.api('study.create',{title:'Copied image questions'});s=await f.change('study.cards.copy',{cardIds:[id],targetSetId:other.id,targetRevision:other.revision,keepSchedule:true});const copy=await f.api('study.get',{setId:other.id});assert.deepEqual(copy.cards[0].review,edited.review);assert.deepEqual(copy.cards[0].emphasis,edited.emphasis);await checkBlue(f.api,copy,copy.cards[0].id,copy.cards[0].review.occlusions[0]);
});
test('each right-angle rotation and four successive rotations keep marks aligned with the immutable image',async t=>{
 const f=await fixture(t);await f.change('study.card.emphasis.set',{cardId:f.id,images:[{...blue,group:'Blue'}]});await f.change('study.review.configure',{cardId:f.id,enabled:true,occlusions:[blue]});
 for(let i=0;i<4;i++){const s=await f.change('study.media.transform',{cardId:f.id,rotation:90});await checkBlue(f.api,s,f.id,s.cards[0].emphasis.images[0]);await checkBlue(f.api,s,f.id,s.cards[0].review.occlusions[0]);}
 const s=f.set();assert.equal(s.cards[0].image.width,200);assert.equal(s.cards[0].image.height,100);
});
test('replacing the picture clears old image marks but preserves textual questions, logs and card ink with undo',async t=>{
 const f=await fixture(t),id=f.id;await f.change('study.card.emphasis.set',{cardId:id,text:[{field:'title',start:0,end:6,quote:'Colors',group:'Text'}],images:[{...blue,group:'Image'}]});
 await f.change('study.card.ink.add',{cardId:id,points:[[.2,.4],[.4,.4]],color:'yellow',brush:'highlighter',width:.02,imageBound:false,imageBounds:{x:0,y:0,width:1,height:1},aspectRatio:2});
 await f.change('study.review.configure',{cardId:id,enabled:true,cloze:'The picture has {{c1::colors}}.',occlusions:[blue]});let s=await f.change('study.review.grade',{cardId:id,rating:'good'}),before=structuredClone(s.cards[0]);
 const white=createCanvas(80,80);s=await f.change('study.media.import',{cardId:id,kind:'image',contentBase64:(await white.encode('png')).toString('base64')});const card=s.cards[0];assert.equal(card.emphasis.images.length,0);assert.deepEqual(card.emphasis.text,before.emphasis.text);assert.equal(card.review.occlusions.length,0);assert.equal(card.review.cloze,before.review.cloze);assert.deepEqual(card.review.logs,before.review.logs);assert.equal(card.ink.length,1);assert.equal(card.ink[0].imageBounds,undefined);assert.equal(s.lastMedia.imageMarks.unmappedInk,1);
 s=await f.change('study.undo');assert.deepEqual(s.cards[0].emphasis,before.emphasis);assert.deepEqual(s.cards[0].review,before.review);assert.deepEqual(s.cards[0].ink,before.ink);assert.equal(s.cards[0].mediaId,before.mediaId);
});
test('append/remove/reselect compose source mappings and keep emphasis on the same PDF pixels, including copied excerpts',async t=>{
 const f=await setup(t),fs=require('node:fs/promises'),{randomUUID}=require('node:crypto'),{PDFDocument,rgb}=require('pdf-lib');
 const pdf=await PDFDocument.create(),page=pdf.addPage([200,200]);page.drawRectangle({x:20,y:100,width:50,height:60,color:rgb(32/255,112/255,208/255)});await fs.writeFile(f.workspace+'/blue.pdf',await pdf.save());
 const second=await PDFDocument.create();second.addPage([200,200]).drawRectangle({x:20,y:100,width:50,height:60,color:rgb(208/255,48/255,32/255)});await fs.writeFile(f.workspace+'/red.pdf',await second.save());
 const blueDoc=await f.api('document.open',{path:'blue.pdf'}),redDoc=await f.api('document.open',{path:'red.pdf'});let s=await f.api('study.create',{title:'Composite'});s=await f.api('study.documents.add',{setId:s.id,expectedRevision:s.revision,paths:['blue.pdf','red.pdf']});
 const setId=s.id,change=async(m,p={})=>{s=await f.api('study.get',{setId});return s=await f.api(m,{setId:s.id,expectedRevision:s.revision,...p});};
 const capture=(doc,rectangle={x:0,y:0,width:1,height:1})=>({documentId:doc.id,expectedSourceVersion:doc.sourceVersion,captureId:randomUUID(),text:'',locator:{page:1},selection:{rects:[{page:1,...rectangle}]}});
 const initial=await f.api('study.card.create',{setId:s.id,expectedRevision:s.revision,...capture(blueDoc),title:'Composite',color:'yellow'}),id=initial.card.id;s=await f.api('study.get',{setId:s.id});const mark=await checkBlue(f.api,s,id);
 await change('study.card.emphasis.set',{cardId:id,images:[{...mark,group:'Blue'}]});await change('study.review.configure',{cardId:id,enabled:true,occlusions:[mark],occlusionGroups:[2]});
 await change('study.excerpt.append',{cardId:id,...capture(redDoc)});s=await f.api('study.get',{setId:initial.setId});let card=s.cards[0];assert.equal(card.image.tiles.length,2);assert.deepEqual(new Set(card.image.fragments.map(f=>f.documentId)),new Set([blueDoc.id,redDoc.id]));await checkBlue(f.api,s,id,card.emphasis.images[0]);await checkBlue(f.api,s,id,card.review.occlusions[0]);
 const firstPart=card.excerptParts[0].id,secondPart=card.excerptParts[1].id;
 // A revised source selection has a new immutable asset but overlaps the old page region.
 await change('study.excerpt.revise',{cardId:id,partId:firstPart,...capture(blueDoc,{x:.05,y:.1,width:.5,height:.6})});s=await f.api('study.get',{setId:initial.setId});await checkBlue(f.api,s,id,s.cards[0].emphasis.images[0]);await checkBlue(f.api,s,id,s.cards[0].review.occlusions[0]);
 await f.api('study.package.export',{setId:s.id,path:'composite.mrpkg'});const imported=await f.api('study.package.import',{path:'composite.mrpkg',folder:'Restored'});let restored=await f.api('study.get',{setId:imported.setId});const restoredCard=restored.cards[0];await f.api('study.excerpt.remove',{setId:restored.id,expectedRevision:restored.revision,cardId:restoredCard.id,partId:restoredCard.excerptParts[1].id});restored=await f.api('study.get',{setId:restored.id});await checkBlue(f.api,restored,restoredCard.id,restored.cards[0].emphasis.images[0]);
 const other=await f.api('study.create',{title:'Copied composite'});await change('study.cards.copy',{cardIds:[id],targetSetId:other.id,targetRevision:other.revision});let copied=await f.api('study.get',{setId:other.id});const copyId=copied.cards[0].id;const removed=await f.api('study.excerpt.remove',{setId:other.id,expectedRevision:copied.revision,cardId:copyId,partId:secondPart});copied=await f.api('study.get',{setId:other.id});assert.equal(removed.card.id,copyId);await checkBlue(f.api,copied,copyId,copied.cards[0].emphasis.images[0]);
 await change('study.excerpt.remove',{cardId:id,partId:secondPart});s=await f.api('study.get',{setId:initial.setId});await checkBlue(f.api,s,id,s.cards[0].emphasis.images[0]);
 const disk=JSON.parse(await fs.readFile(f.workspace+'/.margin-reader/state.json','utf8'));assert.doesNotThrow(()=>require('../lib/study-package.cjs').validateSet(disk.studySets[s.id]));
});
test('composite highlighter generation follows each fragments own document, notebook and hash',async t=>{
 const f=await setup(t),fs=require('node:fs/promises'),{randomUUID}=require('node:crypto'),{pdfFixture}=require('./fixtures.cjs');await fs.writeFile(f.workspace+'/a.pdf',pdfFixture());await fs.writeFile(f.workspace+'/b.pdf',pdfFixture());
 const a=await f.api('document.open',{path:'a.pdf'}),b=await f.api('document.open',{path:'b.pdf'});let s=await f.api('study.create',{title:'Two sources'});s=await f.api('study.documents.add',{setId:s.id,expectedRevision:s.revision,paths:['a.pdf','b.pdf']});
 const setId=s.id,change=async(m,p={})=>{s=await f.api('study.get',{setId});return s=await f.api(m,{setId:s.id,expectedRevision:s.revision,...p});};
 const capture=doc=>({documentId:doc.id,expectedSourceVersion:doc.sourceVersion,captureId:randomUUID(),text:'',locator:{page:1},selection:{rects:[{page:1,x:0,y:0,width:.9,height:.3}]}});
 const first=await f.api('study.card.create',{setId:s.id,expectedRevision:s.revision,title:'Both documents',color:'yellow',...capture(a)}),id=first.card.id;
 await change('study.excerpt.append',{cardId:id,...capture(b)});s=await f.api('study.get',{setId:first.setId});
 for(const doc of [a,b])await change('study.ink.add',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:1,points:[[.1,.1],[.3,.1]],width:.01,color:'yellow',brush:'highlighter'});
 s=await change('study.review.generate',{cardIds:[id]});assert.equal(s.cards[0].review.occlusions.length,2);assert(s.cards[0].review.occlusions[0].y<s.cards[0].review.occlusions[1].y);
 const secondInk=s.ink.find(i=>i.documentId===b.id);await change('study.ink.batch',{scope:'document',strokeIds:[secondInk.id],action:'transform',hidden:true});s=await change('study.review.generate',{cardIds:[id]});assert.equal(s.cards[0].review.occlusions.length,1);
 s=await change('study.notebook.create',{documentId:a.id,title:'Copied notebook',copyFrom:'default'});const copyId=s.lastCopy.cardIds[0],bookId=s.lastNotebookId;s=await change('study.review.generate',{cardIds:[copyId]});assert.equal(s.cards.find(c=>c.id===copyId).review.occlusions.length,1);assert(s.cards.find(c=>c.id===copyId).image.fragments.filter(f=>f.documentId===a.id).every(f=>f.notebookId===bookId));
 await change('study.notebook.assign',{documentId:a.id,notebookId:bookId,cardIds:[id]});s=await change('study.review.generate',{cardIds:[id]});assert.equal(s.cards.find(c=>c.id===id).review.occlusions.length,1);
});
