'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
const {setup,pdfFixture}=require('./fixtures.cjs');
async function fixture(t){const f=await setup(t);await fs.writeFile(f.workspace+'/ink.pdf',pdfFixture());const doc=await f.api('document.open',{path:'ink.pdf',activate:false});let set=await f.api('study.create',{title:'Ink preferences'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});await change('study.documents.add',{paths:['ink.pdf']});await change('study.note.create',{title:'Card'});const cardId=set.cards[0].id;return {...f,doc,cardId,change,set:()=>set,add:()=>change('study.ink.add',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:1,points:[[.1,.5],[.9,.5]],color:'blue'}),card:()=>change('study.card.ink.add',{cardId,points:[[.1,.5],[.9,.5]],color:'blue'}),canvas:()=>change('study.canvas.ink.add',{points:[[100,100],[300,100]],color:'blue'})};}
test('Core chooses independent stored document, card and canvas widths when the CLI omits width',async t=>{
 const f=await fixture(t);await f.change('study.ink.settings',{width:.003,cardWidth:.017,canvasWidth:7});await f.add();await f.card();let s=await f.canvas();assert.equal(s.ink[0].width,.003);assert.equal(s.cards[0].ink[0].width,.017);assert.equal(s.canvasInk[0].width,7);
 s=await f.change('study.card.ink.add',{cardId:f.cardId,points:[[.1,.7],[.9,.7]],width:.005,color:'red'});assert.equal(s.cards[0].ink[1].width,.005);assert.equal(s.inkSettings.cardWidth,.017);assert.deepEqual(await fs.readFile(f.workspace+'/ink.pdf'),pdfFixture());
});
test('legacy tools inherit their shared width until a separate card width is supplied, and reads do not migrate state',async t=>{
 const f=await fixture(t),file=f.workspace+'/.margin-reader/state.json',legacy=JSON.parse(await fs.readFile(file));legacy.studySets[f.set().id].inkSettings={width:.012};await fs.writeFile(file,JSON.stringify(legacy));await f.card();assert.equal(f.set().cards[0].ink[0].width,.012);const before=await fs.readFile(file);await f.api('study.get',{setId:f.set().id});assert.deepEqual(await fs.readFile(file),before);
 await f.change('study.ink.settings',{width:.002});await f.add();await f.card();assert.equal(f.set().ink[0].width,.002);assert.equal(f.set().cards[0].ink[1].width,.012);await f.change('study.ink.settings',{cardWidth:.018});await f.card();assert.equal(f.set().cards[0].ink[2].width,.018);
});
test('named brushes, templates, portable packages and undo preserve all context widths and the vanish preference',async t=>{
 const f=await fixture(t),settings={brush:'pencil',color:'#8844CC',opacity:.6,width:.003,cardWidth:.014,canvasWidth:6,vanish:true};await f.change('study.ink.settings',settings);let s=await f.change('study.tool.save',{kind:'ink',title:'Local pointer'}),id=s.lastToolId;await f.api('study.template.export',{setId:s.id,path:'pen.json'});
 await f.change('study.ink.settings',{cardWidth:.025,vanish:false});s=await f.change('study.tool.apply',{toolId:id});assert.deepEqual(s.inkSettings,settings);await f.change('study.undo');assert.equal(f.set().inkSettings.vanish,false);s=await f.change('study.template.import',{path:'pen.json'});assert.deepEqual(s.inkSettings,settings);
 await f.api('study.package.export',{setId:s.id,path:'pen.mrpkg'});const imported=await f.api('study.package.import',{path:'pen.mrpkg',folder:'Restored'}),restored=await f.api('study.get',{setId:imported.setId});assert.deepEqual(restored.inkSettings,settings);assert.deepEqual(restored.tools[0].settings,settings);
});
test('invalid preference widths reject atomically and an explicit persistent CLI stroke is independent of the UI vanish mode',async t=>{
 const f=await fixture(t);let s=await f.change('study.ink.settings',{vanish:true,cardWidth:.014});for(const patch of [{cardWidth:0},{cardWidth:.04},{vanish:'yes'}])await f.error('study.ink.settings',{setId:s.id,expectedRevision:s.revision,...patch},'INVALID_PARAMS');assert.equal((await f.api('study.get',{setId:s.id})).revision,s.revision);
 s=await f.card();assert.equal(s.cards[0].ink[0].width,.014);assert.equal(s.inkSettings.vanish,true);await f.error('study.card.ink.add',{setId:s.id,expectedRevision:s.revision,cardId:f.cardId,points:[[.1,.1],[.9,.1]],color:'blue',brush:'laser'},'INVALID_PARAMS');
});
test('a new document-width edit leaves the default card width alone, while an old shared-width preset restores both contexts',async t=>{
 const f=await fixture(t);await f.change('study.ink.settings',{width:.01,vanish:true});await f.card();assert.equal(f.set().cards[0].ink[0].width,.004);let s=await f.change('study.tool.save',{kind:'ink',title:'Legacy shared pen',settings:{width:.012}}),id=s.lastToolId;s=await f.change('study.tool.apply',{toolId:id});assert.equal(s.inkSettings.width,.012);assert.equal(s.inkSettings.cardWidth,.012);assert.equal(s.inkSettings.vanish,false);await f.change('study.ink.settings',{width:.006});await f.card();assert.equal(f.set().cards[0].ink.at(-1).width,.012);
});
