'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{createCanvas}=require('@napi-rs/canvas');
const {setup,pdfFixture}=require('./fixtures.cjs');
async function fixture(t){const f=await setup(t);let set=await f.api('study.create',{title:'Bound handwriting'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});await change('study.note.create',{title:'Owner'});const a=set.cards[0].id;await change('study.note.create',{title:'Other'});const b=set.cards[1].id;return {...f,change,set:()=>set,a,b,box:async id=>(await f.api('study.map.geometry',{setId:set.id})).positions.find(p=>p.cardId===id)};}
const line=(b,y=.5)=>[[b.x+b.width*.2,b.y+b.height*y,.3],[b.x+b.width*.8,b.y+b.height*y,.9]];
test('map gestures use Core hit testing, preserve pressure and switch between automatic, selected-only and unbound drawing',async t=>{
 const f=await fixture(t),box=await f.box(f.a);await f.change('study.ink.settings',{canvasWidth:6});let s=await f.change('study.map.ink.add',{points:line(box),color:'blue'});assert.equal(s.lastInk.cardId,f.a);assert.equal(s.lastInk.selectedCardId,f.a);assert.equal(s.lastInk.binding,'automatic');assert(s.cards[0].ink[0].mapBound);assert.equal(s.cards[0].ink[0].width,6/box.width);assert.deepEqual(s.cards[0].ink[0].points.map(p=>p[2]),[.3,.9]);
 await f.change('study.ink.binding.set',{autoSelect:false});s=await f.change('study.map.ink.add',{points:line(box,.6),selectedCardId:f.b,color:'red'});assert.equal(s.lastInk.scope,'canvas');assert.equal(s.canvasInk.length,1);s=await f.change('study.map.ink.add',{points:line(box,.7),selectedCardId:f.a,color:'green'});assert.equal(s.cards[0].ink.length,2);await f.change('study.ink.binding.set',{autoBind:false});s=await f.change('study.map.ink.add',{points:line(box,.8),selectedCardId:f.a,color:'blue'});assert.equal(s.canvasInk.length,2);
});
test('focus binds blank-space and child-card handwriting to the focused owner and retains it through movement and undo',async t=>{
 const f=await fixture(t);await f.change('study.card.move',{cardId:f.b,parentId:f.a});await f.change('study.ink.binding.set',{autoBind:false,hideFocusInk:true});await f.change('study.map.configure',{focusId:f.a});const owner=await f.box(f.a),child=await f.box(f.b);await f.change('study.map.ink.add',{points:[[owner.x+owner.width+50,owner.y+30],[owner.x+owner.width+180,owner.y+80]],color:'red'});let s=await f.change('study.map.ink.add',{points:line(child),selectedCardId:f.b,color:'blue'});assert.equal(s.cards[0].ink.length,2);assert.equal(s.cards[1].ink?.length||0,0);assert(s.cards[0].ink.every(i=>i.focusBound&&i.mapBound&&!i.imageBound));assert.equal(s.lastInk.selectedCardId,f.a);const before=structuredClone(s.cards[0].ink);await f.change('study.map.configure',{focusId:null});await f.change('study.card.position',{cardId:f.a,x:250,y:160});assert.deepEqual(f.set().cards[0].ink,before);s=await f.change('study.undo');assert.deepEqual(s.cards[0].ink,before);
});
test('hidden focus ink peeks only on selection, is fully visible in its own focus, and is protected from an outside map eraser',async t=>{
 const f=await fixture(t),{mapInkVisibility}=await import('../ui/ink-binding.mjs');await f.change('study.ink.binding.set',{hideFocusInk:true});await f.change('study.map.configure',{focusId:f.a});await f.change('study.map.ink.add',{points:line(await f.box(f.a)),color:'blue'});const ink=f.set().cards[0].ink[0];assert.equal(mapInkVisibility(ink,f.a,{hideFocusInk:true}),0);assert.equal(mapInkVisibility(ink,f.a,{hideFocusInk:true,selectedCardId:f.a}),.3);assert.equal(mapInkVisibility(ink,f.a,{hideFocusInk:true,focusId:f.a}),1);assert.equal(mapInkVisibility({...ink,hidden:true},f.a,{focusId:f.a}),0);
 await f.change('study.map.configure',{focusId:null});let box=await f.box(f.a),s=await f.change('study.ink.erase',{scope:'map',path:[[box.x,box.y+box.height*.5],[box.x+box.width,box.y+box.height*.5]],radius:10,mode:'stroke'});assert.equal(s.lastInk.erased,0);await f.change('study.ink.batch',{scope:'card',cardId:f.a,strokeIds:[ink.id],action:'transform',mapHidden:false});assert.equal(mapInkVisibility(f.set().cards[0].ink[0],f.a,{hideFocusInk:true}),1);s=await f.change('study.ink.erase',{scope:'map',path:[[box.x,box.y+box.height*.5],[box.x+box.width,box.y+box.height*.5]],radius:10,mode:'stroke'});assert.equal(s.lastInk.erased,1);
 await f.change('study.map.configure',{focusId:f.a});await f.error('study.ink.erase',{setId:f.set().id,expectedRevision:f.set().revision,scope:'map',path:[[0],[1]],radius:1},'INVALID_PARAMS');
});
test('detaching clears only map binding visibility metadata and retains the visible world position',async t=>{
 const f=await fixture(t);await f.change('study.map.configure',{focusId:f.a});let s=await f.change('study.map.ink.add',{points:line(await f.box(f.a)),color:'blue'}),id=s.cards[0].ink[0].id;await f.change('study.ink.batch',{scope:'card',cardId:f.a,strokeIds:[id],action:'transform',mapHidden:true});s=await f.change('study.ink.detach',{cardId:f.a,strokeIds:[id]});assert.equal(s.cards[0].ink.length,0);const ink=s.canvasInk[0];assert.equal(ink.focusBound,undefined);assert.equal(ink.mapHidden,undefined);assert.equal(ink.mapBound,undefined);assert.deepEqual(ink.points.map(p=>p.slice(0,2)),line(await f.box(f.a)).map(p=>p.slice(0,2)));s=await f.change('study.undo');assert(s.cards[0].ink[0].mapHidden&&s.cards[0].ink[0].focusBound);
});
test('image-aware automatic binding remains clipped and transformable while map and card widths stay distinct',async t=>{
 const f=await fixture(t),png=await createCanvas(100,100).encode('png');await f.change('study.mindmap.configure',{patch:{showImages:true}});let s=await f.change('study.media.import',{kind:'image',title:'Photo',contentBase64:png.toString('base64')}),card=s.cards.at(-1),box=await f.box(card.id),frame=box.imageBounds,world=p=>[box.x+p[0]*box.width,box.y+p[1]*box.height];await f.change('study.ink.settings',{canvasWidth:10,cardWidth:.002});s=await f.change('study.map.ink.add',{points:[world([frame.x+.1*frame.width,frame.y+.5*frame.height]),world([frame.x+.9*frame.width,frame.y+.5*frame.height])],color:'blue'});let ink=s.cards.find(c=>c.id===card.id).ink[0];assert(ink.imageBound&&ink.mapBound);assert.equal(ink.width,10/box.width);await f.change('study.ink.batch',{scope:'card',cardId:card.id,strokeIds:[ink.id],action:'transform',mapHidden:true});s=await f.change('study.ink.batch',{scope:'card',cardId:card.id,strokeIds:[ink.id],action:'transform',imageBound:false});ink=s.cards.find(c=>c.id===card.id).ink[0];assert(ink.mapBound&&ink.mapHidden);assert.equal(ink.imageBound,false);
});
test('bound map creation checks owner locks and stale revisions before mutating either owner or canvas',async t=>{
 const f=await fixture(t);await fs.writeFile(f.workspace+'/source.pdf',pdfFixture());const doc=await f.api('document.open',{path:'source.pdf',activate:false});await f.change('study.documents.add',{paths:['source.pdf']});let s=await f.change('study.layer.create',{title:'Note owner'}),layer=s.activeLayer;s=await f.change('study.note.place',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,locator:{page:1},title:'Locked owner',layerId:layer});const id=s.cards.at(-1).id,box=await f.box(id);await f.change('study.layer.update',{layerId:layer,locked:true});s=f.set();await f.error('study.map.ink.add',{setId:s.id,expectedRevision:s.revision,layerId:'default',points:line(box),color:'blue'},'LAYER_LOCKED');await f.error('study.map.ink.add',{setId:s.id,expectedRevision:s.revision-1,points:line(box),color:'blue'},'CONFLICT');assert.deepEqual(await f.api('study.get',{setId:s.id}),s);
});
async function redPixels(bytes){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs'),task=pdfjs.getDocument({data:new Uint8Array(bytes),verbosity:0,isEvalSupported:false});try{const pdf=await task.promise,page=await pdf.getPage(1),v=page.getViewport({scale:.5}),canvas=createCanvas(Math.ceil(v.width),Math.ceil(v.height)),ctx=canvas.getContext('2d');await page.render({canvasContext:ctx,viewport:v}).promise;const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;let count=0;for(let i=0;i<data.length;i+=4)if(data[i]>170&&data[i]-data[i+1]>60&&data[i]-data[i+2]>60)count++;return count;}finally{await task.destroy();}}
test('map export follows focus visibility and includes annotations beyond card bounds; packages retain binding behavior',async t=>{
 const f=await fixture(t);await f.change('study.ink.binding.set',{hideFocusInk:true,doubleTapFocus:true});await f.change('study.map.configure',{focusId:f.a});await f.change('study.map.ink.add',{points:[[2000,650],[2200,650]],width:12,color:'red'});const geom=await f.api('study.map.geometry',{setId:f.set().id});assert(geom.width>2200);await f.api('study.export.file',{setId:f.set().id,format:'pdf',path:'focused.pdf',poster:true});assert(await redPixels(await fs.readFile(f.workspace+'/focused.pdf'))>10);await f.change('study.map.configure',{focusId:null});await f.api('study.export.file',{setId:f.set().id,format:'pdf',path:'hidden.pdf',poster:true});assert.equal(await redPixels(await fs.readFile(f.workspace+'/hidden.pdf')),0);
 await f.api('study.package.export',{setId:f.set().id,path:'binding.mrpkg'});const imported=await f.api('study.package.import',{path:'binding.mrpkg',folder:'Restored'}),restored=await f.api('study.get',{setId:imported.setId});assert.deepEqual(restored.inkBinding,f.set().inkBinding);assert(restored.cards[0].ink[0].focusBound);await f.api('study.template.export',{setId:f.set().id,path:'binding.json'});await f.change('study.ink.binding.set',{hideFocusInk:false});const s=await f.change('study.template.import',{path:'binding.json'});assert(s.inkBinding.hideFocusInk);
});
