'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
const {setup}=require('./fixtures.cjs');
async function fixture(t){const f=await setup(t);let set=await f.api('study.create',{title:'Toolbar'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});return {...f,change,set:()=>set,base:type=>set.tools.find(t=>t.builtin===type)};}
test('base pens are stable read-only defaults and edits, copies and active application commit atomically',async t=>{
 const f=await fixture(t),file=f.workspace+'/.margin-reader/state.json',before=await fs.readFile(file);const list=await f.api('study.tool.list',{setId:f.set().id});assert.equal(list.tools.length,3);assert.deepEqual(await fs.readFile(file),before);const pen=f.base('pen');
 let s=await f.change('study.tool.save',{toolId:pen.id,title:'Blue fine pen',settings:{...pen.settings,color:'#336699',width:.002,cardWidth:.008},apply:true});assert.equal(s.activeTools.ink,pen.id);assert.equal(s.inkSettings.color,'#336699');assert.equal(s.revision,2);assert.equal(s.tools.filter(t=>t.id===pen.id).length,1);
 s=await f.change('study.tool.save',{kind:'ink',title:'Copied pen',settings:s.inkSettings,pin:true,apply:true});const copy=s.lastToolId;assert.notEqual(copy,pen.id);assert(s.inkToolbar.toolIds.includes(copy));assert.equal(s.activeTools.ink,copy);s=await f.change('study.undo');assert(!s.tools.some(t=>t.id===copy));assert.equal(s.activeTools.ink,pen.id);s=await f.change('study.undo');assert.equal(s.tools.find(t=>t.id===pen.id).title,'钢笔');
});
test('toolbar deletion preserves a pen of each family and archives recoverably with a valid active replacement',async t=>{
 const f=await fixture(t),pen=f.base('pen');await f.error('study.tool.remove',{setId:f.set().id,expectedRevision:f.set().revision,toolId:pen.id},'TOOL_REQUIRED');let s=await f.change('study.tool.save',{kind:'ink',title:'Second pen',settings:pen.settings,pin:true,apply:true}),copy=s.lastToolId;
 s=await f.change('study.tool.remove',{toolId:copy});assert(s.tools.find(t=>t.id===copy).deletedAt);assert(!s.inkToolbar.toolIds.includes(copy));assert.equal(s.activeTools.ink,pen.id);await f.change('study.tool.remove',{toolId:copy,restore:true});await f.change('study.ink.toolbar.set',{toolIds:[...f.set().inkToolbar.toolIds,copy]});s=await f.change('study.tool.remove',{toolId:pen.id});assert(!s.inkToolbar.toolIds.includes(pen.id));assert.equal(s.activeTools.ink,copy);assert(s.tools.find(t=>t.id===pen.id).deletedAt);
});
test('toolbar order and independent context placements persist, undo and travel in a portable package',async t=>{
 const f=await fixture(t),ids=f.set().inkToolbar.toolIds;let s=await f.change('study.ink.toolbar.set',{toolIds:[...ids].reverse(),context:'document',placement:{dock:'right',orientation:'vertical',x:1,y:.3}});s=await f.change('study.ink.toolbar.set',{context:'map',placement:{dock:'free',orientation:'horizontal',x:.2,y:.6}});assert.equal(s.inkToolbar.placements.document.y,.3);assert.equal(s.inkToolbar.placements.map.x,.2);await f.api('study.package.export',{setId:s.id,path:'toolbar.mrpkg'});const imported=await f.api('study.package.import',{path:'toolbar.mrpkg',folder:'Restored'}),restored=await f.api('study.get',{setId:imported.setId});assert.deepEqual(restored.inkToolbar,s.inkToolbar);
 s=await f.change('study.undo');assert.equal(s.inkToolbar.placements.map,undefined);assert.deepEqual(s.inkToolbar.toolIds,[...ids].reverse());
});
test('stale or invalid toolbar writes and thirteenth pins preserve the previous settings and tools',async t=>{
 const f=await fixture(t),pen=f.base('pen');for(let i=0;i<9;i++)await f.change('study.tool.save',{kind:'ink',title:'Pen '+i,settings:pen.settings,pin:true});const s=f.set();assert.equal(s.inkToolbar.toolIds.length,12);
 await f.error('study.tool.save',{setId:s.id,expectedRevision:s.revision,kind:'ink',title:'Too many',settings:pen.settings,pin:true,apply:true},'TOO_LARGE');await f.error('study.ink.toolbar.set',{setId:s.id,expectedRevision:s.revision-1,toolIds:s.inkToolbar.toolIds},'CONFLICT');await f.error('study.ink.toolbar.set',{setId:s.id,expectedRevision:s.revision,context:'map',placement:{dock:'free',orientation:'horizontal',x:2,y:.5}},'INVALID_PARAMS');assert.deepEqual(await f.api('study.get',{setId:s.id}),s);
});
test('style templates retain base-pen identity while copying custom tools and a global family switch clears the selected preset',async t=>{
 const f=await fixture(t),pen=f.base('pen');await f.change('study.tool.save',{toolId:pen.id,title:'Custom base',settings:{...pen.settings,color:'purple'},apply:true});let s=await f.change('study.tool.save',{kind:'ink',title:'Second',settings:pen.settings,pin:true});const copy=s.lastToolId;await f.api('study.template.export',{setId:s.id,path:'pens.json'});await f.change('study.tool.remove',{toolId:pen.id});s=await f.change('study.template.import',{path:'pens.json'});const restored=s.tools.find(t=>t.id===pen.id);assert(!restored.deletedAt);assert.equal(restored.title,'Custom base');assert.equal(restored.settings.color,'purple');assert(s.tools.some(t=>t.title==='Second'&&t.id!==copy));await f.change('study.tool.apply',{toolId:pen.id});s=await f.change('study.ink.settings',{brush:'pencil'});assert.equal(s.activeTools.ink,null);
});
test('portable toolbar data rejects unsafe colors and invalid base families before importing any study',async t=>{
 const f=await fixture(t),pen=f.base('pen');await f.change('study.tool.save',{toolId:pen.id,title:'Pen',settings:pen.settings});await f.api('study.package.export',{setId:f.set().id,path:'safe.mrpkg'});const Zip=require('jszip'),bytes=await fs.readFile(f.workspace+'/safe.mrpkg'),before=(await f.api('study.list')).sets.length;
 for(const [index,change] of [s=>{s.tools[0].settings.color='red;position:fixed';},s=>{s.inkSettings={color:'" onload="bad'};},s=>{s.tools[0].settings.brush='pencil';}].entries()){
  const zip=await Zip.loadAsync(bytes),manifest=JSON.parse(await zip.file('manifest.json').async('string'));change(manifest.sets[0]);zip.file('manifest.json',JSON.stringify(manifest));await fs.writeFile(f.workspace+'/bad.mrpkg',await zip.generateAsync({type:'nodebuffer'}));await f.error('study.package.import',{path:'bad.mrpkg',folder:'Rejected-'+index},index===2?'INVALID_PACKAGE':'INVALID_PARAMS');assert.equal((await f.api('study.list')).sets.length,before);
 }
});
test('portable imports preserve base IDs across history while remapping custom pens, and remain valid in a library backup',async t=>{
 const f=await fixture(t),pen=f.base('pen');let s=await f.change('study.tool.save',{kind:'ink',title:'Custom portable',settings:pen.settings,pin:true}),custom=s.lastToolId;await f.change('study.ink.toolbar.set',{toolIds:s.inkToolbar.toolIds});s=await f.change('study.tool.save',{toolId:pen.id,title:'Styled base',settings:{...pen.settings,color:'purple'},apply:true});await f.api('study.package.export',{setId:s.id,path:'profiles.mrpkg'});
 const imported=await f.api('study.package.import',{path:'profiles.mrpkg',folder:'Profiles',activate:false});let restored=await f.api('study.get',{setId:imported.setId});assert.equal(restored.tools.find(t=>t.builtin==='pen').settings.color,'purple');const customCopy=restored.tools.find(t=>t.title==='Custom portable');assert.notEqual(customCopy.id,custom);assert(restored.inkToolbar.toolIds.includes(customCopy.id));assert(restored.inkToolbar.toolIds.includes(pen.id));
 restored=await f.api('study.undo',{setId:restored.id,expectedRevision:restored.revision});assert.equal(restored.tools.find(t=>t.builtin==='pen').settings.color,'blue');assert(restored.inkToolbar.toolIds.includes(pen.id));await f.api('library.backup.create',{path:'profiles.mrbackup'});const backup=await f.api('library.backup.inspect',{path:'profiles.mrbackup'});assert(backup.studies.some(s=>s.id===restored.id));
});
