'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),{randomUUID}=require('node:crypto'),assert=require('node:assert/strict');
const {create,expect}=require('./ui-session.cjs');
async function main(){
  const f=await create('large-map');let failure;
  try{
    const set=await f.api('study.create',{mapMode:'cards',title:'Large map regression'}),file=path.join(f.workspace,'.margin-reader/state.json'),state=JSON.parse(await fs.readFile(file,'utf8')),raw=state.studySets[set.id];
    const ids=Array.from({length:10000},()=>randomUUID()),now=new Date().toISOString();
    raw.cards=ids.map((id,i)=>({id,title:`Card ${String(i).padStart(5,'0')}`,text:'保存完整原文与卡片，不以截断代替性能优化。',note:'',tags:['sample'],color:'blue',parentId:i%50?ids[i-i%50]:null,source:null,image:null,collapsed:false,createdAt:now,updatedAt:now}));
    state.settings.activeStudySet=set.id;await fs.writeFile(file,JSON.stringify(state));
    await f.page.goto(f.server.url);await f.page.waitForSelector('body[data-ready=true]');
    const viewport=f.page.locator('#study-map-viewport');
    await expect(viewport).toHaveAttribute('data-total-cards','10000');
    assert(await f.page.locator('.study-card').count()<100);assert(await f.page.locator('*').count()<3000);
    f.pass('10,000 cards remain in the graph while first-paint DOM is bounded to the viewport');
    await viewport.evaluate(el=>el.scrollTop=el.scrollHeight-el.clientHeight);
    await expect(f.page.locator(`.study-card[data-card-id="${ids.at(-1)}"]`)).toBeVisible();
    await f.page.locator(`.study-card[data-card-id="${ids.at(-1)}"] header strong`).click();
    await expect(f.page.locator(`.study-card[data-card-id="${ids.at(-1)}"]`)).toHaveClass(/selected/);
    const model=await f.api('study.get',{setId:set.id});assert.equal(model.cards.length,10000);
    f.pass('Scrolling to the final branch mounts its real, selectable last card without discarding earlier data');
    await f.page.locator('[data-study-view=cards]').click();
    await expect(f.page.locator('.study-list-card')).toHaveCount(100);await expect(f.page.locator('#study-list-pages')).toBeVisible();
    const cardGeometry=await f.page.locator('.study-list-card').first().evaluate(el=>{const card=el.getBoundingClientRect(),footer=el.querySelector('footer').getBoundingClientRect(),body=el.querySelector('.study-note-body').getBoundingClientRect();return {height:card.height,footerBottom:footer.bottom-card.top,bodyHeight:body.height};});
    assert(cardGeometry.height>=235&&cardGeometry.footerBottom<=cardGeometry.height&&cardGeometry.bodyHeight>=120,JSON.stringify(cardGeometry));
    const panelGeometry=await f.page.locator('#study-cards-panel').boundingBox();assert(panelGeometry.height>500,'Main content must not be consumed by toolbars: '+JSON.stringify({panelGeometry,children:await f.page.locator('#study-board').evaluate(el=>[...el.children].map(e=>({tag:e.tagName,id:e.id,cls:e.className,height:e.getBoundingClientRect().height,hidden:e.hidden}))),home:await f.page.locator('#study-home').evaluate(el=>[...el.children].map(e=>({id:e.id,cls:e.className,height:e.getBoundingClientRect().height})))}));
    await f.page.locator('#study-tools-expand').click();await expect(f.page.locator('#study-tools-expand')).toHaveAttribute('aria-pressed','true');await f.page.locator('#study-tools-expand').click();
    await f.page.locator('[data-page-step=last]').click();await expect(f.page.locator('#study-list-page')).toHaveValue('100');
    await expect(f.page.locator(`.study-list-card[data-card-id="${ids.at(-1)}"]`)).toBeVisible();
    const current=await f.api('study.get',{setId:set.id});
    await f.api('study.card.update',{setId:set.id,expectedRevision:current.revision,cardId:ids.at(-1),title:'Edited final card'});
    await expect(f.page.locator(`.study-list-card[data-card-id="${ids.at(-1)}"] strong`)).toHaveText('Edited final card');
    await expect(f.page.locator('#study-list-page')).toHaveValue('100');
    f.pass('Card-box pagination exposes all 100 pages and preserves the page after a concurrent CLI edit');
    await f.api('study.card.activate',{setId:set.id,cardId:ids[122],origin:'document'});
    await expect(f.page.locator('#study-list-page')).toHaveValue('2');
    await expect(f.page.locator(`.study-list-card[data-card-id="${ids[122]}"]`)).toHaveClass(/selected/);
    f.pass('Source-to-card activation reveals the corresponding list page automatically');
    await f.page.locator('#study-card-search').fill('Edited final card');
    await expect(f.page.locator('.study-list-card')).toHaveCount(1);await expect(f.page.locator('#study-list-pages')).toBeHidden();
    await f.page.locator('#study-card-search').fill('');await expect(f.page.locator('.study-list-card')).toHaveCount(100);
    await f.page.locator('#study-list-page').fill('37');await f.page.locator('#study-list-page').press('Enter');
    await expect(f.page.locator(`.study-list-card[data-card-id="${ids[3600]}"]`)).toBeVisible();
    f.pass('Search remains complete after the hundredth page, resets paging, and supports direct page entry');
    await f.page.locator('[data-study-view=map]').click();
    await f.api('study.card.activate',{setId:set.id,cardId:ids[9850],origin:'document'});
    const target=f.page.locator(`.study-card[data-card-id="${ids[9850]}"]`);await expect(target).toBeVisible();await expect(target).toHaveClass(/selected/);
    await target.focus();
    const updated=await f.api('study.get',{setId:set.id});await f.api('study.card.update',{setId:set.id,expectedRevision:updated.revision,cardId:ids[9850],title:'Keyboard target'});
    await expect(f.page.locator(`.study-card[data-card-id="${ids[9850]}"] strong`)).toHaveText('Keyboard target');
    await expect(f.page.locator(`.study-card[data-card-id="${ids[9850]}"]`)).toBeFocused();
    await f.page.locator('#study-zoom-out').click();await f.page.locator('#study-zoom-in').click();
    assert(await f.page.locator('.study-card').count()<150);
    f.pass('CLI targeting and keyboard focus survive node replacement, pan and zoom in the full graph');
    await f.page.screenshot({path:path.join(f.output,'large-map.png')});
    assert.deepEqual(f.report.browserErrors,[]);
  }catch(error){failure=error;}finally{await f.finish(failure);}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
