'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
const {setup,pdfFixture}=require('./fixtures.cjs');
const guide={edges:[{a:[.1,.5],b:[.9,.5],group:'top',t0:0,t1:1}],tolerance:.03};
async function fixture(t){const f=await setup(t);let set=await f.api('study.create',{title:'Ruler'});const change=async(m,p={})=>set=await f.api(m,{setId:set.id,expectedRevision:set.revision,...p});return {...f,change,set:()=>set};}
test('ruler assistance snaps nearby along-edge pressure samples and leaves remote, crossing and beyond-end strokes unchanged',async()=>{
 const {resolveStroke}=await import('../ui/ink-recognition.mjs'),points=[[.2,.51,.2],[.45,.49,.6],[.8,.505,.9]],s=resolveStroke(points,{ruler:guide,aspectRatio:2});assert.equal(s.kind,'ruler');assert(s.points.every(p=>p[1]===.5));assert.deepEqual(s.points.map(p=>p[2]),[.2,.6,.9]);
 for(const raw of [[[.2,.7],[.8,.72]],[[.5,.48],[.501,.52]],[[.89,.5],[1,.5]]])assert.deepEqual(resolveStroke(raw,{ruler:guide}),{kind:'free',points:raw});
 const tilted={edges:[{a:[.1,.1],b:[.8,.45],group:'top',t0:0,t1:1}],tolerance:.025},r=resolveStroke([[.2,.16],[.5,.295],[.7,.405]],{ruler:tilted,aspectRatio:2});assert.equal(r.kind,'ruler');assert(r.points.every(p=>Math.abs((p[1]-.1)*2-(p[0]-.1))<1e-9));
});
test('independent ruler settings survive package import and undo without moving existing ink',async t=>{
 const f=await fixture(t);await f.change('study.canvas.ink.add',{points:[[10,10],[100,10]],color:'blue'});const original=f.set().canvasInk[0];await f.change('study.ink.ruler.set',{context:'document',enabled:true,x:.3,y:.4,angle:35});let s=await f.change('study.ink.ruler.set',{context:'map',enabled:true,angle:-20,cover:true,length:1.2});assert.equal(s.inkRulers.document.angle,35);assert.equal(s.inkRulers.map.angle,-20);assert.deepEqual(s.canvasInk[0],original);
 await f.api('study.package.export',{setId:s.id,path:'ruler.mrpkg'});const imported=await f.api('study.package.import',{path:'ruler.mrpkg',folder:'Restored'}),restored=await f.api('study.get',{setId:imported.setId});assert.deepEqual(restored.inkRulers,s.inkRulers);s=await f.change('study.undo');assert.equal(s.inkRulers.map,undefined);assert.equal(s.inkRulers.document.angle,35);
});
test('Core draws using a supplied ruler in document, card and canvas coordinates and keeps the original PDF',async t=>{
 const f=await fixture(t);await fs.writeFile(f.workspace+'/ruler.pdf',pdfFixture());const doc=await f.api('document.open',{path:'ruler.pdf',activate:false});await f.change('study.documents.add',{paths:['ruler.pdf']});let s=await f.change('study.note.create',{title:'Card'}),id=s.cards[0].id;
 await f.change('study.ink.add',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:1,points:[[.2,.51],[.8,.49]],color:'blue',geometry:{ruler:guide}});s=await f.change('study.card.ink.add',{cardId:id,points:[[.2,.51,.3],[.8,.49,.8]],color:'blue',geometry:{ruler:guide}});assert.equal(s.ink[0].recognizedShape,'ruler');assert.equal(s.cards[0].ink[0].recognizedShape,'ruler');assert(s.ink[0].points.every(p=>p[1]===.5));
 const world={edges:[{a:[100,100],b:[900,100],group:'top',t0:0,t1:1}],tolerance:12};s=await f.change('study.canvas.ink.add',{points:[[200,106],[800,96]],color:'red',geometry:{ruler:world}});assert(s.canvasInk[0].points.every(p=>p[1]===100));assert.equal(s.lastInk.recognizedShape,'ruler');assert.deepEqual(await fs.readFile(f.workspace+'/ruler.pdf'),pdfFixture());
});
test('a guide crossing folded source regions produces separate pressure-preserving strokes in one undo step',async t=>{
 const f=await fixture(t);await fs.writeFile(f.workspace+'/fold.pdf',pdfFixture());const doc=await f.api('document.open',{path:'fold.pdf',activate:false});await f.change('study.documents.add',{paths:['fold.pdf']});const {pageSlices,sourceY}=await import('../ui/page-slices.mjs'),{rulerEdges,clipEdge}=await import('../ui/ruler-geometry.mjs'),layout=pageSlices(792,[{start:.4,end:.6}]),edge=rulerEdges({left:0,top:0,width:612,height:layout.height},{x:.5,y:.5,angle:45,length:.9})[0];
 const edges=layout.blocks.filter(b=>b.type==='source').map(b=>clipEdge(edge,{left:0,right:612,top:b.top,bottom:b.top+b.height})).filter(Boolean).map(e=>({...e,a:[e.a[0]/612,sourceY(layout,e.a[1])],b:[e.b[0]/612,sourceY(layout,e.b[1])]}));const points=Array.from({length:21},(_,i)=>{const t=.1+i*.04;return [(edge.a[0]+(edge.b[0]-edge.a[0])*t+1)/612,sourceY(layout,edge.a[1]+(edge.b[1]-edge.a[1])*t-1),.2+t*.6];}),before=f.set().revision;
 let s=await f.change('study.ink.add',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:1,points,color:'blue',geometry:{ruler:{edges,tolerance:12/612},bands:[{start:0,end:.4},{start:.6,end:1}]}});assert.equal(s.revision,before+1);assert.equal(s.ink.length,2);assert(s.ink[0].points.every(p=>p[1]<=.4+1e-9));assert(s.ink[1].points.every(p=>p[1]>=.6-1e-9));assert(s.ink.every(i=>i.points.every(p=>p.length===3&&p[2]>=.2&&p[2]<=.8)));assert.equal(s.lastInk.strokeIds.length,2);s=await f.change('study.undo');assert.equal(s.ink.length,0);
});
test('invalid or stale ruler changes and overlapping guides reject without changing state',async t=>{
 const f=await fixture(t);let s=await f.change('study.ink.ruler.set',{context:'map',enabled:true});for(const patch of [{x:2},{length:0},{angle:181},{cover:'yes'}])await f.error('study.ink.ruler.set',{setId:s.id,expectedRevision:s.revision,context:'map',...patch},'INVALID_PARAMS');await f.error('study.ink.ruler.set',{setId:s.id,expectedRevision:s.revision-1,context:'map',angle:25},'CONFLICT');await f.error('study.canvas.ink.add',{setId:s.id,expectedRevision:s.revision,points:[[100,100],[200,100]],color:'blue',geometry:{ruler:{edges:[guide.edges[0],guide.edges[0]],tolerance:10}}},'INVALID_PARAMS');assert.deepEqual(await f.api('study.get',{setId:s.id}),s);
});
