'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium,_electron,expect}=require('../../../node_modules/@playwright/test');
const {startServer}=require('../dist-plugin/lib/server.cjs');
async function main(){
 const temp=await fs.mkdtemp(path.join(os.tmpdir(),'margin-advanced-ui-'));let workspace=temp,server,browser,app,page,api;
 const native=process.env.WORKBENCH_NATIVE==='1',errors=[];
 try{
 if(native){
   const host=path.resolve(__dirname,'../../..'),env={...process.env,AGENTS_COMPANY_HOME:path.join(temp,'state'),AGENTS_COMPANY_WORKSPACES:path.join(temp,'work'),AGENTS_COMPANY_PROJECTS:path.join(temp,'projects'),AGENTS_COMPANY_PLUGIN_DIRS:process.env.WORKBENCH_PLUGIN_ROOT||path.join(host,'build/plugins/margin-reader'),AGENTS_COMPANY_HIDDEN:'1'};
   for(const k of ['ELECTRON_RUN_AS_NODE','AGENTS_COMPANY_TOKEN','AGENTS_COMPANY_TOKEN_FILE','AGENTS_COMPANY_SOCKET','AGENTS_COMPANY_PORT','AGENTS_COMPANY_PLUGIN_RPC','AGENTS_WORKSPACE'])delete env[k];
   const exec=require('node:util').promisify(require('node:child_process').execFile);
   const cli=async(...args)=>{const r=JSON.parse((await exec(process.execPath,[path.join(host,'bin/agents'),...args,'--json'],{env,timeout:60000,maxBuffer:8*1024*1024})).stdout);assert(r.ok,r.error);return r.data;};
   app=await _electron.launch({executablePath:process.env.WORKBENCH_APP||'/Applications/Agents Company.app/Contents/MacOS/Agents Company',args:[],env});await app.firstWindow();
   api=(method,params={})=>cli('plugin','call','margin-reader',method,'--params',JSON.stringify(params));workspace=(await api('system.info')).workspace;
   const opened=app.waitForEvent('window');await cli('plugin','open','margin-reader');page=await opened;
 }else{
   server=await startServer({workspace});api=async(method,params={})=>{const r=await server.runtime.request({jsonrpc:'2.0',id:1,method,params});assert(!r.error,JSON.stringify(r.error));return r.result;};
   const sync=require('node:fs'),cache=path.join(os.homedir(),'Library/Caches/ms-playwright');const executablePath=sync.readdirSync(cache).filter(n=>n.startsWith('chromium_headless_shell-')).sort().reverse().map(n=>path.join(cache,n,'chrome-headless-shell-mac-arm64/chrome-headless-shell')).find(sync.existsSync);browser=await chromium.launch({headless:true,executablePath});page=await browser.newPage();await page.goto(server.url);
 }
 const scoped=path.relative(await fs.realpath(temp),await fs.realpath(workspace));assert(!scoped.startsWith('..')&&!path.isAbsolute(scoped),'UI test workspace escaped its isolated root');
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(30000);await page.setViewportSize({width:1440,height:960});await page.waitForSelector('body[data-ready=true]');
 await page.click('#studies-root');await page.click('#study-create');await page.fill('[name=title]','知识与记忆');await page.selectOption('#dialog [name=mapMode]','cards');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();

 const id=(await api('study.list')).sets[0].id,get=()=>api('study.get',{setId:id});
 await fs.writeFile(path.join(workspace,'source.pdf'),require('./fixtures.cjs').pdfFixture());let set=await get();await api('study.documents.add',{setId:id,expectedRevision:set.revision,paths:['source.pdf']});await page.reload();await page.waitForSelector('body[data-ready=true]');await page.locator('.study-document-open').click();await page.waitForSelector('.pdf-page[data-render-state=ready]');
 const doc=(await get()).documents[0];
 await page.click('#reader-compare');await page.selectOption('[name=path]','source.pdf');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await expect(page.locator('#compare-pane')).toBeVisible();await expect(page.locator('#compare-surface canvas').first()).toBeVisible();
 await page.fill('#compare-page','2');await page.locator('#compare-page').press('Tab');await expect.poll(async()=>(await api('settings.get')).comparison.locator.page).toBe(2);assert.equal((await api('reader.position.get',{id:doc.id})).locator.page,1);await expect.poll(()=>page.locator('#compare-scroll').evaluate(el=>el.scrollTop)).toBeGreaterThan(200);
 await page.screenshot({path:path.resolve(__dirname,'../artifacts/advanced-comparison.png')});await page.click('#compare-close');await expect(page.locator('#compare-pane')).toBeHidden();await expect.poll(async()=>(await api('settings.get')).comparison).toBe(null);
 await page.click('#study-layers');await page.fill('[name=title]','练习层');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await expect(page.locator('#study-ink-layer option:checked')).toHaveText('练习层');
 await page.click('#study-pen');const box=await page.locator('.pdf-page').first().boundingBox();await page.mouse.move(box.x+90,box.y+130);await page.mouse.down();await page.mouse.move(box.x+190,box.y+150,{steps:10});await page.mouse.up();await expect(page.locator('#study-ink-status')).toHaveText('已保存');await expect.poll(async()=>(await get()).ink.length).toBe(1);await page.click('#study-pen');
 await page.click('#study-layers');await page.locator('.layer-row').filter({hasText:'练习层'}).getByText('隐藏',{exact:true}).click();await page.click('#dialog-cancel');await expect(page.locator('.study-ink-layer polyline')).toHaveCount(0);await page.click('#study-undo');await expect(page.locator('.study-ink-layer polyline')).toHaveCount(1);
 await page.click('#reader-page-tools');await page.fill('[name=pages]','1');await page.selectOption('[name=action]','fold');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await expect(page.locator('#reading-surface .pdf-unfold')).toBeVisible();await page.click('#reading-surface .pdf-unfold');await page.waitForSelector('.pdf-page[data-render-state=ready]');await expect(page.locator('#reading-surface .pdf-unfold')).toHaveCount(0);
 await page.click('#study-excerpt-lasso');const lb=await page.locator('.pdf-page').first().boundingBox();await page.mouse.move(lb.x+40,lb.y+40);await page.mouse.down();await page.mouse.move(lb.x+180,lb.y+45,{steps:5});await page.mouse.move(lb.x+160,lb.y+130,{steps:5});await page.mouse.move(lb.x+40,lb.y+40,{steps:5});await page.mouse.up();await expect(page.locator('#study-palette')).toBeVisible();await page.locator('#study-palette [data-color=blue]').click();await expect.poll(async()=>(await get()).cards.some(c=>c.image?.kind==='pdf-lasso')).toBe(true);
 const excerpt=(await get()).cards.find(c=>c.image?.kind==='pdf-lasso');await page.locator('.study-card[data-card-id="'+excerpt.id+'"] .study-card-more').click();await page.locator('[data-action=occlude]').click();const imageBox=await page.locator('#occlusion-editor img').boundingBox();await page.mouse.move(imageBox.x+10,imageBox.y+10);await page.mouse.down();await page.mouse.move(imageBox.x+imageBox.width*.5,imageBox.y+imageBox.height*.5,{steps:5});await page.mouse.up();await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();set=await get();assert.equal(set.cards.find(c=>c.id===excerpt.id).review.occlusions.length,1);set=await api('study.review.configure',{setId:id,expectedRevision:set.revision,cardId:excerpt.id,enabled:false});await expect(page.locator('#study-board')).toHaveAttribute('data-revision',String(set.revision));

 await page.click('#study-extend-note');await page.fill('[name=title]','章节思考');await page.fill('[name=text]','本地留白笔记，保留原文位置。');await page.selectOption('[name=display]','embedded');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await expect(page.locator('.extend-note-block')).toContainText('章节思考');
 set=await get();const noteId=set.cards.find(c=>c.anchor).id;assert.equal(set.cards.find(c=>c.id===noteId).anchor.locator.page,1);
 await page.click('#reader-notebook');await page.fill('[name=path]','方格笔记本.pdf');await page.fill('[name=pages]','3');await page.selectOption('[name=paper]','grid');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await expect(page.locator('#document-title')).toHaveText('方格笔记本');assert.equal((await get()).documents.length,2);await expect(page.locator('#document-tabs')).toContainText('source');
 await page.locator('#document-tabs [data-open="'+doc.id+'"]').click();await expect(page.locator('#document-title')).toHaveText('source');
 await page.click('#reader-page-tools');await page.fill('[name=path]','重组.pdf');await page.fill('[name=pages]','2,0,1');await page.selectOption('[name=rotation]','90');await page.fill('[name=crop]','10');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await expect(page.locator('#document-title')).toHaveText('重组');await expect(page.locator('#page-total')).toContainText('3');
 await page.click('#study-back-set');await expect(page.locator('#study-home')).toBeVisible();
 const create=async(title,text)=>{await page.click('#study-add-note');await page.fill('[name=title]',title);await page.fill('[name=text]',text);await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();};
 await create('数学笔记','**公式** $x^2+y^2=z^2$');await create('推理过程','保留上下文');set=await get();const a=set.cards.find(c=>c.title==='数学笔记'),b=set.cards.find(c=>c.title==='推理过程');
 const card=id=>page.locator('.study-card[data-card-id="'+id+'"]');await card(a.id).locator('.study-card-more').click();await page.locator('[data-action=preview]').click();await expect(page.locator('.study-card-preview strong')).toHaveText('公式');await expect(page.locator('.study-card-preview .katex')).toBeVisible();await page.click('#dialog-cancel');
 await page.click('#card-ink-pen');const cb=await card(a.id).boundingBox();await page.mouse.move(cb.x+25,cb.y+65);await page.mouse.down();await page.mouse.move(cb.x+95,cb.y+90,{steps:6});await page.mouse.up();await expect.poll(async()=>(await get()).cards.find(c=>c.id===a.id).ink?.length).toBe(1);await page.click('#card-ink-pen');
 await card(a.id).click({modifiers:['Shift']});await card(b.id).click({modifiers:['Shift']});await page.click('#study-merge');await page.fill('[name=title]','复合知识');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();set=await get();const composite=set.cards.find(c=>c.title==='复合知识');assert.equal(composite.mergedIds.length,2);await expect(card(a.id)).toHaveCount(0);
 await page.selectOption('#study-layout','down');await expect.poll(async()=>(await get()).map.layout).toBe('down');await card(composite.id).click();await page.click('#study-submap');await expect.poll(async()=>(await get()).map.focusId).toBe(composite.id);await expect(page.locator('.study-card')).toHaveCount(1);await page.click('#study-fullmap');await expect(page.locator('#study-fullmap')).toBeHidden();await page.selectOption('#study-layout','radial');await expect.poll(async()=>(await get()).map.layout).toBe('radial');
 await page.click('#study-review-settings');await page.click('#study-optimize');await expect(page.locator('#toast')).toContainText('50');await page.fill('[name=newDeck]','考试牌组');await page.fill('[name=retention]','0.95');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();set=await get();assert.equal(set.decks[0].title,'考试牌组');assert.equal(set.reviewSettings.retention,.95);
 await card(composite.id).locator('.study-card-more').click();await page.locator('[data-action=review]').click();await page.fill('[name=cloze]','圆周率约为 {{3.14}}');await page.selectOption('[name=deckId]',set.decks[0].id);await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('[data-study-view=review]');await expect(page.locator('.study-review-front')).toHaveText('圆周率约为 [ … ]');await page.click('#study-review-reveal');await expect(page.locator('#study-review-answer')).toContainText('3.14');await page.click('[data-grade=easy]');await expect(page.locator('.study-review-empty')).toBeVisible();
 await page.screenshot({path:path.resolve(__dirname,'../artifacts/advanced-review.png')});
 let other=await api('study.create',{mapMode:'cards',title:'关联来源'});other=await api('study.note.create',{setId:other.id,expectedRevision:other.revision,title:'跨集原卡',text:'source'});await page.click('[data-study-view=map]');await expect(page.locator('#study-map-viewport')).toBeVisible();await page.click('#study-reference');await page.selectOption('[name=target]',other.id+'/'+other.cards[0].id);await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();set=await get();const ref=set.cards.find(c=>c.reference);await page.locator('.study-card[data-card-id="'+ref.id+'"] .study-card-source').click();await expect(page.locator('#study-title')).toHaveText('关联来源');await expect(page.locator('.study-card[data-card-id="'+other.cards[0].id+'"]')).toBeVisible();await page.locator('.study-set-row[data-set-id="'+id+'"]').click();await expect(page.locator('#study-title')).toHaveText('知识与记忆');

 await page.reload();await page.waitForSelector('body[data-ready=true]');set=await get();assert.equal(set.ink.length,1);assert.equal(set.decks.length,1);assert(set.cards.some(c=>c.anchor));assert.deepEqual(await fs.readFile(path.join(workspace,'source.pdf')),require('./fixtures.cjs').pdfFixture());
 assert.equal((await api('settings.get')).comparison,null);if(native)assert(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(w=>!w.isVisible())));assert.deepEqual(errors,[]);
 await fs.writeFile(path.resolve(__dirname,'../artifacts/advanced-'+(native?'native':'browser')+'-results.json'),JSON.stringify({passed:true,native,version:(await api('system.info')).version,errors,checks:['comparison positions','layer hide and undo','extended notes','notebook','page compose','tabs','Markdown and formulas','composite cards','layouts and focus','decks cloze statistics','reload','source preservation']},null,2));
 console.log('PASS advanced local UI: comparison, layers, notes, notebooks, pages, Markdown/math, composite cards, layouts, decks and cloze; no browser errors');
 }catch(error){if(page&&!page.isClosed())await page.screenshot({path:path.resolve(__dirname,'../artifacts/advanced-failure.png')}).catch(()=>{});console.error('BROWSER ERRORS',errors);if(page&&!page.isClosed())console.error('COMPARISON',await page.evaluate(()=>{const s=document.querySelector('#compare-scroll'),p=document.querySelector('#compare-pane');return {scrollTop:s.scrollTop,clientHeight:s.clientHeight,scrollHeight:s.scrollHeight,paneHeight:p.clientHeight,surfaceHeight:document.querySelector('#compare-surface').clientHeight,surfaceStyle:document.querySelector('#compare-surface').getAttribute('style'),scrollerStyle:getComputedStyle(s).cssText,rows:[...document.querySelectorAll('#compare-surface .pdf-page')].map(e=>({top:e.style.top,height:e.style.height}))};}));throw error;}finally{await browser?.close();await app?.close();await server?.close();await fs.rm(temp,{recursive:true,force:true});}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
