'use strict';
const assert=require('node:assert/strict'),path=require('node:path');
const {create,expect}=require('./ui-session.cjs'),AV=require('../lib/av-document.cjs');
(async()=>{
 if(!AV.available()){const fs=require('node:fs/promises'),out=path.resolve(__dirname,'../artifacts/completion-resume-20260929/av-documents');await fs.mkdir(out,{recursive:true});await fs.writeFile(path.join(out,'results.json'),JSON.stringify({passed:false,validation:{passed:[],failed:[],skipped:['FFmpeg/ffprobe unavailable'],untestedPlatforms:['all AV playback platforms']}}));console.log('SKIP local AV UI: installed ffmpeg/ffprobe are unavailable');return;}
 const f=await create('av-documents');let failure;
 try{
  require('./fixtures-av.cjs').make(f.workspace);const {page,api}=f;let set=await api('study.create',{mapMode:'cards',title:'本地视频学习'});set=await api('study.documents.add',{setId:set.id,expectedRevision:set.revision,paths:['lesson.webm','lesson.wav']});const video=await api('document.open',{path:'lesson.webm',activate:false});
  await api('study.open',{setId:set.id,documentId:video.id});await page.goto(f.server.url);await page.waitForSelector('body[data-ready=true]');const player=page.locator('#reading-surface video');await expect(player).toBeVisible();await expect.poll(()=>player.evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);
  await page.fill('#reading-surface .av-time','1.5');await page.click('#reading-surface .av-seek');await expect.poll(()=>player.evaluate(v=>v.currentTime)).toBeCloseTo(1.5,1);await expect.poll(async()=>(await api('reader.position.get',{id:video.id})).locator.time).toBeCloseTo(1.5,1);
  await page.click('#study-toggle-map');await page.click('#add-chapter');await page.fill('#dialog [name=title]','时间章节');await page.fill('#dialog [name=time]','1.5');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('#edit-chapter');await page.fill('#dialog [name=title]','已改名的时间章节');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();assert.equal((await api('toc.list',{id:video.id})).toc[0].locator.time,1.5);await page.click('#study-toggle-map');
  f.pass('Local video is decoded and actual seeking persists through reader.position.set');
  await page.fill('#reading-surface .av-time','0');await page.click('#reading-surface .av-seek');await expect.poll(async()=>(await api('reader.position.get',{id:video.id})).locator.time).toBe(0);await page.selectOption('#reading-surface .av-rate','0.5');await player.evaluate(v=>v.play());await expect.poll(async()=>(await api('reader.position.get',{id:video.id})).locator.time).toBeGreaterThan(.3);assert.equal(await player.evaluate(v=>v.paused),false);f.pass('Playback progress is checkpointed while the media remains playing');await player.evaluate(v=>v.pause());await page.fill('#reading-surface .av-time','1.5');await page.click('#reading-surface .av-seek');
  await player.evaluate(v=>v.play());await expect.poll(()=>player.evaluate(v=>v.currentTime)).toBeGreaterThan(1.7);await player.evaluate(v=>v.pause());await page.selectOption('#reading-surface .av-rate','1.5');await expect.poll(async()=>(await api('settings.get')).mediaRate).toBe(1.5);
  await page.click('#av-excerpt');await page.fill('#dialog [name=title]','视频知识点');await page.fill('#dialog [name=start]','1');await page.fill('#dialog [name=end]','2');await page.fill('#dialog [name=text]','同一片段的学习笔记');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();
  const get=()=>api('study.get',{setId:set.id});await expect.poll(async()=>(await get()).cards.length).toBe(1);const card=(await get()).cards[0];await expect.poll(()=>page.locator(`.study-card[data-card-id="${card.id}"] img`).evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
  await page.fill('#reading-surface .av-time','3');await page.click('#reading-surface .av-seek');await page.locator(`[data-time-card="${card.id}"]`).click();await expect.poll(()=>player.evaluate(v=>v.currentTime)).toBeCloseTo(1,1);f.pass('Core-generated frame and time note return to the original interval');
  await page.reload();await page.waitForSelector('body[data-ready=true]');await expect.poll(()=>player.evaluate(v=>v.currentTime)).toBeCloseTo(1,1);await expect(page.locator('[data-time-card]')).toHaveCount(1);
  const audio=(await get()).documents.find(d=>d.format==='wav');await page.selectOption('#study-current-document',audio.id);await expect(page.locator('#reading-surface audio')).toBeVisible();await page.fill('#reading-surface .av-time','2');await page.click('#reading-surface .av-seek');await expect.poll(()=>page.locator('#reading-surface audio').evaluate(v=>v.currentTime)).toBeCloseTo(2,1);
  f.pass('Reload preserves the time note and independent audio document playback');
  await api('reader.comparison.set',{documentId:video.id,locator:{time:0}});await api('reader.comparison.set',{documentId:audio.id,locator:{time:0},slot:2});await expect(page.locator('#compare-extra-surface audio')).toBeVisible();await page.fill('#compare-extra-surface .av-time','2.5');await page.click('#compare-extra-surface .av-seek');await expect.poll(async()=>(await api('settings.get')).comparisonExtra.locator.time).toBeCloseTo(2.5,1);await page.fill('#compare-surface .av-time','1.2');await page.click('#compare-surface .av-seek');await expect.poll(async()=>(await api('settings.get')).comparison.locator.time).toBeCloseTo(1.2,1);assert.equal((await api('reader.position.get',{id:audio.id})).locator.time,2);f.pass('Second and third media panes preserve their own times without overwriting the primary audio position');
  assert.deepEqual(f.report.browserErrors,[]);await page.screenshot({path:path.join(f.output,'audio-reader.png')});
 }catch(e){failure=e;}f.report.validation={passed:[...f.report.checks],failed:[...(failure?[failure.message]:[]),...f.report.browserErrors],skipped:[],untestedPlatforms:['Windows','Linux'],untestedHardware:['physical pen/touch hardware']};await f.finish(failure);
})().catch(e=>{console.error(e);process.exitCode=1;});
