'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),JSZip=require('jszip');
const {setup,pdfFixture}=require('./fixtures.cjs'),{randomUUID}=require('node:crypto');
async function fixture(t){const f=await setup(t);await fs.writeFile(path.join(f.workspace,'source.pdf'),pdfFixture());let s=await f.api('study.create',{title:'Versioned notes'});s=await f.api('study.documents.add',{setId:s.id,expectedRevision:s.revision,paths:['source.pdf']});const d=await f.api('document.open',{path:'source.pdf',activate:false});const capture=await f.api('study.card.create',{setId:s.id,expectedRevision:s.revision,documentId:d.id,expectedSourceVersion:d.sourceVersion,captureId:randomUUID(),title:'Excerpt',text:'',color:'green',locator:{page:1},selection:{rects:[{page:1,x:.1,y:.1,width:.5,height:.2}]}});return {...f,setId:s.id,doc:d,cardId:capture.card.id,get:()=>f.api('study.get',{setId:s.id}),change:async(method,p={})=>{const set=await f.api('study.get',{setId:s.id});return f.api(method,{setId:s.id,expectedRevision:set.revision,...p});}};}
test('named versions restore exact card metadata and PNGs, remain inspectable after archive, and can be undone',async t=>{
 const f=await fixture(t),before=await f.api('study.card.image',{setId:f.setId,cardId:f.cardId});let s=await f.change('study.versions.create',{title:'Before editing'});const versionId=s.lastVersionId;
 await f.change('study.card.update',{cardId:f.cardId,title:'Changed',note:'Working'});let view=await f.api('study.versions.get',{setId:s.id,versionId});assert.equal(view.changes.changed.length,1);
 s=await f.change('study.versions.restore',{versionId});assert.equal(s.cards[0].title,'Excerpt');assert.equal((await f.api('study.card.image',{setId:s.id,cardId:f.cardId})).contentBase64,before.contentBase64);
 s=await f.change('study.undo');assert.equal(s.cards[0].title,'Changed');await f.change('study.versions.update',{versionId,archived:true,title:'Saved original'});assert.equal((await f.api('study.versions.list',{setId:s.id})).total,0);assert.equal((await f.api('study.versions.list',{setId:s.id,includeArchived:true})).versions[0].title,'Saved original');
});
test('automatic versions capture before the next changed state and are throttled without any read-side writes',async t=>{
 const f=await fixture(t);await f.change('study.versions.policy',{enabled:true,intervalSeconds:30});await f.change('study.card.update',{cardId:f.cardId,note:'First change'});
 const list=await f.api('study.versions.list',{setId:f.setId});assert.equal(list.total,1);assert.equal(list.versions[0].automatic,true);const snapshot=await f.api('study.versions.get',{setId:f.setId,versionId:list.versions[0].id,includeContent:true});assert.equal(snapshot.snapshot.cards[0].note,'');
 await f.change('study.card.update',{cardId:f.cardId,note:'Second change'});assert.equal((await f.api('study.versions.list',{setId:f.setId})).total,1);
 const file=path.join(f.workspace,'.margin-reader/state.json'),bytes=await fs.readFile(file);await f.get();await f.api('study.versions.list',{setId:f.setId});assert.deepEqual(await fs.readFile(file),bytes);
});
test('study packages retain named versions and remap only real identities/links, not UUIDs in ordinary text',async t=>{
 const f=await fixture(t);let s=await f.change('study.card.update',{cardId:f.cardId,note:`Literal ${f.cardId}. [[${f.cardId}|Alias ${f.cardId}]] margin-reader://card/${f.setId}/${f.cardId}`});s=await f.change('study.versions.create',{title:'Version label'});await f.change('study.card.update',{cardId:f.cardId,title:'After'});
 await f.api('study.package.export',{setId:s.id,path:'versioned.mrpkg'});const imported=await f.api('study.package.import',{path:'versioned.mrpkg',folder:'Imported'}),copy=await f.api('study.get',{setId:imported.setId});assert.equal(copy.versionRecords.length,1);const id=copy.cards[0].id;assert.notEqual(id,f.cardId);assert(copy.cards[0].note.includes(`Literal ${f.cardId}.`));assert(copy.cards[0].note.includes(`[[${id}|Alias ${f.cardId}]]`));assert(copy.cards[0].note.includes(`margin-reader://card/${copy.id}/${id}`));
 const restored=await f.api('study.versions.restore',{setId:copy.id,expectedRevision:copy.revision,versionId:copy.versionRecords[0].id});assert.equal(restored.cards[0].title,'Excerpt');assert((await f.api('study.card.image',{setId:copy.id,cardId:id})).contentBase64.length>100);
});
test('encrypted whole-library backup preserves empty folders, trash, versions and assets but never credentials; restore never replaces the live workspace',async t=>{
 const f=await fixture(t);await fs.mkdir(path.join(f.workspace,'Empty'));await fs.mkdir(path.join(f.workspace,'.agents-company'),{recursive:true});await fs.writeFile(path.join(f.workspace,'.agents-company/token'),'DO_NOT_BACK_UP');await f.change('study.versions.create',{title:'Milestone'});
 await f.api('fs.write',{path:'removed.md',content:'Recoverable'});await f.api('fs.trash',{path:'removed.md'});
 const result=await f.api('library.backup.create',{path:'library.mrbackup',password:'correct horse battery'});assert(result.encrypted);await f.error('library.backup.inspect',{path:'library.mrbackup',password:'wrong'},'PASSWORD_REQUIRED');
 const info=await f.api('library.backup.inspect',{path:'library.mrbackup',password:'correct horse battery'});assert.equal(info.studies.length,1);const settings=await f.api('settings.get');
 await f.api('library.backup.restore',{path:'library.mrbackup',folder:'Recovered',password:'correct horse battery'});assert.deepEqual(await f.api('settings.get'),settings);await f.error('library.backup.restore',{path:'library.mrbackup',folder:'Recovered',password:'correct horse battery'},'ALREADY_EXISTS');assert((await fs.stat(path.join(f.workspace,'Recovered/Empty'))).isDirectory());assert.equal(await fs.stat(path.join(f.workspace,'Recovered/.agents-company')).catch(()=>null),null);
 const runtime=await require('../runtime.cjs').createPlugin({workspace:path.join(f.workspace,'Recovered')});t.after(()=>runtime.close());const call=async(method,params)=>{const r=await runtime.request({jsonrpc:'2.0',id:randomUUID(),method,params});assert(!r.error,JSON.stringify(r.error));return r.result;};
 const study=await call('study.get',{setId:f.setId});assert.equal(study.cards[0].sourceChanged,false);assert.equal((await call('study.versions.list',{setId:f.setId})).total,1);assert((await call('study.card.image',{setId:f.setId,cardId:f.cardId})).contentBase64.length>100);assert.equal((await call('fs.trash.list',{})).items.length,1);
});
test('corrupt checksums, unsafe metadata and symbolic links are rejected before producing a restored library',async t=>{
 const f=await fixture(t);await f.api('library.backup.create',{path:'safe.mrbackup'});const zip=await JSZip.loadAsync(await fs.readFile(path.join(f.workspace,'safe.mrbackup'))),manifest=JSON.parse(await zip.file('manifest.json').async('string'));
 manifest.files[0].path='../outside';zip.file('manifest.json',JSON.stringify(manifest));await fs.writeFile(path.join(f.workspace,'bad.mrbackup'),await zip.generateAsync({type:'nodebuffer'}));await f.error('library.backup.restore',{path:'bad.mrbackup',folder:'NeverCreated'},'SCOPE_DENIED');assert.equal(await fs.stat(path.join(f.workspace,'NeverCreated')).catch(()=>null),null);
 await fs.symlink(path.join(f.workspace,'source.pdf'),path.join(f.workspace,'alias.pdf'));await f.error('library.backup.create',{path:'linked.mrbackup'},'SCOPE_DENIED');assert.equal(await fs.stat(path.join(f.workspace,'linked.mrbackup')).catch(()=>null),null);
});
