'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{createHash}=require('node:crypto');
const {PDFDocument,StandardFonts}=require('pdf-lib');const {create,expect}=require('./ui-session.cjs');
(async()=>{const f=await create('book-turn-ui');let failure;
 try{
  const {page,api}=f,out=await fs.readFile(path.join(__dirname,'../artifacts/book-library-current.txt'),'utf8').then(s=>s.trim(),()=>f.output);
  const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(let n=1;n<=14;n++){const p=pdf.addPage([600,780]);p.drawText('Page '+n+' - Book navigation',{x:45,y:700,size:23,font});p.drawText('Distinct original page, selectable text.',{x:45,y:420,size:18,font});}
  const bytes=Buffer.from(await pdf.save()),hash=createHash('sha256').update(bytes).digest('hex');await fs.writeFile(path.join(f.workspace,'book.pdf'),bytes);
  const doc=await api('document.open',{path:'book.pdf'});await api('settings.set',{pdfMode:'paged',pdfFit:'page',uiMotion:'full',pdfTurnEffect:'book'});
  await page.goto(f.server.url);await page.locator('body[data-ready=true]').waitFor();
  const ready=async n=>{await expect(page.locator(`.pdf-page[data-page="${n}"]`)).toHaveAttribute('data-render-state','ready');await expect(page.locator('#page-number')).toHaveValue(String(n));await expect(page.locator('.book-turn-overlay')).toHaveCount(0);await expect(page.locator('#reader-scroll')).toHaveAttribute('aria-busy','false');};await ready(1);
  if(process.env.MR_BOOK_DEBUG)await page.evaluate(async()=>{const {BookTurn}=await import(new URL('./book-turn.js',location.href));window.bookDebug=[];const capture=BookTurn.prototype.capture,cancel=BookTurn.prototype.cancel;BookTurn.prototype.capture=function(page,direction,enabled){let result;try{result=capture.call(this,page,direction,enabled);}catch(e){window.bookDebug.push({error:e.message});throw e;}window.bookDebug.push({action:'capture',page:page?.dataset.page,ready:page?.dataset.renderState,connected:page?.isConnected,enabled,motion:document.body.dataset.uiMotion,hidden:document.hidden,result:!!result});return result;};BookTurn.prototype.cancel=function(){window.bookDebug.push({action:'cancel',trace:new Error().stack});return cancel.call(this);};});
  await page.evaluate(()=>{window.deliveredTurnPointers=0;document.getElementById('reader-scroll').addEventListener('pointerdown',()=>window.deliveredTurnPointers++,true);});
  await page.click('#next-page');await expect(page.locator('.book-turn-overlay[data-phase=turning]')).toHaveCount(1);
  const paperPoint=await page.locator('.pdf-page').evaluate(el=>{const b=el.getBoundingClientRect();return{x:b.x+b.width*.5,y:b.y+b.height*.4};});await page.mouse.click(paperPoint.x,paperPoint.y);assert.equal(await page.evaluate(()=>window.deliveredTurnPointers),0,'Turning paper must not start a document annotation on the obscured page');
  await page.screenshot({path:path.join(out,'book-turn-midflight.png')});await ready(2);
  await page.mouse.click(paperPoint.x,paperPoint.y);assert.equal(await page.evaluate(()=>window.deliveredTurnPointers),1,'Document pointer input must resume after the turn');
  await page.click('#previous-page');await expect(page.locator('.book-turn-overlay[data-direction=backward]')).toHaveCount(1);await ready(1);
  assert.equal(await page.locator('.pdf-page').count(),1);assert(Number(await page.locator('#reading-surface').getAttribute('data-cached-pages'))<=3);
  f.pass('Actual forward/backward page controls animate a paper leaf while preserving one mounted source page and a bounded three-page raster cache');
  let delayed=false;await page.route('**/rpc',async route=>{const data=route.request().postDataJSON();if(data?.method==='reader.position.set'&&!delayed){delayed=true;await new Promise(r=>setTimeout(r,450));}await route.continue();});
  await page.locator('#reader-scroll').focus();for(let i=0;i<5;i++)await page.keyboard.press('ArrowRight');await ready(6);await page.unroute('**/rpc');
  await expect.poll(async()=>(await api('reader.position.get',{id:doc.id})).locator.page).toBe(6);
  f.pass('Rapid page input during a slow save converges to its final requested page instead of hanging, repeating the old page or replaying an unbounded animation queue');
  await page.selectOption('#pdf-turn-effect','none');const box=await page.locator('#reader-scroll').boundingBox();
  const input=await page.context().newCDPSession(page);let clock=Date.now()/1000;
  const burst=async values=>{for(const [i,dx] of values.entries())await input.send('Input.dispatchMouseEvent',{type:'mouseWheel',x:box.x+box.width/2,y:box.y+box.height/2,deltaX:dx,deltaY:0,timestamp:clock+i*.03});clock+=values.length*.03;};
  await page.waitForTimeout(350);clock=Date.now()/1000;await burst([80,50,22,8,3,1,2,85,44,20,8,2,-80,-40,-10]);await ready(7);
  await expect(page.locator('.book-turn-overlay')).toHaveCount(0);
  f.pass('Fresh trackpad strokes and deliberate reversal work without waiting for complete momentum silence, while each momentum tail consumes only its own turn');
  await page.selectOption('#pdf-turn-effect','book');await page.emulateMedia({reducedMotion:'reduce'});await page.click('#next-page');await ready(8);await expect(page.locator('.book-turn-overlay')).toHaveCount(0);await page.emulateMedia({reducedMotion:'no-preference'});
  let errorOnce=false;await page.route('**/rpc',async route=>{const data=route.request().postDataJSON();if(data?.method==='reader.position.set'&&!errorOnce){errorOnce=true;await route.fulfill({contentType:'application/json',body:JSON.stringify({jsonrpc:'2.0',id:data.id,error:{code:-32000,message:'Injected save refusal',data:{code:'CONFLICT'}}})});}else await route.continue();});
  await page.click('#next-page');await expect(page.locator('#toast')).toContainText('Injected save refusal');await expect(page.locator('.book-turn-overlay')).toHaveCount(0);await page.unroute('**/rpc');await page.click('#next-page');await ready(9);
  f.pass('Reduced-motion disables the leaf; a refused save removes the transition and releases the navigation queue so the next valid turn succeeds');
  await page.click('#next-page');await expect(page.locator('.book-turn-overlay')).toHaveCount(1);await page.click('#home');await expect(page.locator('#library-view')).toBeVisible();await expect(page.locator('.book-turn-overlay')).toHaveCount(0);await page.waitForTimeout(500);await expect(page.locator('#reader-view')).toBeHidden();
  const savedPage=(await api('reader.position.get',{id:doc.id})).locator.page;await page.locator('.file-card[data-path="book.pdf"] .file-open').click();await ready(savedPage);await page.locator('#reader-scroll').focus();await page.keyboard.press('ArrowLeft');await ready(savedPage-1);
  await page.click('#pdf-continuous');await expect(page.locator('#reader-scroll')).toHaveAttribute('data-pdf-mode','continuous');await page.mouse.move(box.x+box.width/2,box.y+box.height/2);const before=await page.locator('#reader-scroll').evaluate(el=>el.scrollTop);await page.mouse.wheel(0,120);await expect.poll(()=>page.locator('#reader-scroll').evaluate(el=>el.scrollTop)).toBeGreaterThan(before+100);await expect(page.locator('.book-turn-overlay')).toHaveCount(0);
  assert.equal(createHash('sha256').update(await fs.readFile(path.join(f.workspace,'book.pdf'))).digest('hex'),hash);
  f.pass('Leaving during a page turn cannot reopen the old reader; re-entry and continuous vertical scrolling remain functional and original PDF bytes are unchanged');
 }catch(e){failure=e;if(process.env.MR_BOOK_DEBUG)console.log(JSON.stringify(await f.page.evaluate(()=>window.bookDebug),null,2));}await f.finish(failure);
})().catch(e=>{console.error(e);process.exitCode=1;});
