'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises'),{randomUUID}=require('node:crypto');
const {setup,pdfFixture}=require('./fixtures.cjs');
async function fixture(t){const f=await setup(t);await fs.writeFile(path.join(f.workspace,'first.pdf'),pdfFixture());await fs.writeFile(path.join(f.workspace,'second.html'),'<h1>Flow</h1><p>Alpha 中文🙂 beta gamma delta.</p>');let set=await f.api('study.create',{title:'Continuous'});set=await f.api('study.documents.add',{setId:set.id,expectedRevision:set.revision,paths:['first.pdf','second.html']});const pdf=await f.api('document.open',{path:'first.pdf',activate:false}),flow=await f.api('document.open',{path:'second.html',activate:false});const p={setId:set.id,expectedRevision:set.revision,documentId:pdf.id,expectedSourceVersion:pdf.sourceVersion,captureId:randomUUID(),text:'',color:'yellow',locator:{page:1},selection:{rects:[{page:1,x:.1,y:.1,width:.5,height:.15}]}};const c=await f.api('study.card.create',p);return {...f,pdf,flow,cardId:c.card.id,setId:set.id,get:()=>f.api('study.get',{setId:set.id})};}
test('continuous excerpts retain independent PDF/Unicode sources, combined PNG, exact part navigation and idempotent retries',async t=>{
 const f=await fixture(t);let s=await f.get();const first=await f.api('study.card.image',{setId:f.setId,cardId:f.cardId});
 const content=await f.api('document.content',{id:f.flow.id}),dom=new(require('jsdom').JSDOM)(content.html),text=dom.window.document.body.textContent,at=text.indexOf('中文🙂');dom.window.close();
 const request={setId:s.id,expectedRevision:s.revision,cardId:f.cardId,documentId:f.flow.id,expectedSourceVersion:f.flow.sourceVersion,captureId:randomUUID(),text:'中文🙂',locator:{section:0},selection:{start:at,end:at+'中文🙂'.length}};
 const result=await f.api('study.excerpt.append',request);assert.equal(result.card.id,f.cardId);assert.equal(result.card.excerpts.length,2);assert.equal((await f.api('study.excerpt.append',request)).duplicate,true);
 s=await f.get();assert.equal(s.cards.length,1);assert.equal(s.cards[0].excerptParts[1].source.documentId,f.flow.id);assert.equal(s.cards[0].excerptParts[1].sourceChanged,false);
 const combined=await f.api('study.card.image',{setId:s.id,cardId:f.cardId});assert.notEqual(combined.contentBase64,first.contentBase64);
 assert.equal((await f.api('study.excerpt.image',{setId:s.id,cardId:f.cardId,partId:f.cardId})).contentBase64,first.contentBase64);
 const jump=await f.api('study.card.activate',{setId:s.id,cardId:f.cardId,excerptId:result.partId,force:true});assert.equal(jump.source.documentId,f.flow.id);assert.equal(jump.source.locator.textOffset,at);
 await f.error('study.excerpt.append',{...request,text:'different'},'CONFLICT');
});
test('editing an excerpt refreshes the capture but preserves card identity, comments, review and a restorable old PNG',async t=>{
 const f=await fixture(t);let s=await f.get();s=await f.api('study.card.update',{setId:s.id,expectedRevision:s.revision,cardId:f.cardId,note:'Preserve me',tags:['exam']});s=await f.api('study.review.configure',{setId:s.id,expectedRevision:s.revision,cardId:f.cardId,enabled:true});const first=await f.api('study.card.image',{setId:s.id,cardId:f.cardId});
 const req={setId:s.id,expectedRevision:s.revision,cardId:f.cardId,documentId:f.pdf.id,expectedSourceVersion:f.pdf.sourceVersion,captureId:randomUUID(),text:'',locator:{page:2},selection:{rects:[{page:2,x:.2,y:.2,width:.4,height:.2}]}};
 await f.api('study.excerpt.revise',req);s=await f.get();assert.equal(s.cards[0].source.locator.page,2);assert.equal(s.cards[0].note,'Preserve me');assert.equal(s.cards[0].review.enabled,true);assert.deepEqual(s.cards[0].tags,['exam']);
 s=await f.api('study.undo',{setId:s.id,expectedRevision:s.revision});assert.equal(s.cards[0].source.locator.page,1);assert.equal((await f.api('study.card.image',{setId:s.id,cardId:f.cardId})).contentBase64,first.contentBase64);
 await f.error('study.excerpt.revise',req,'CONFLICT');
});
test('multi-part remove, copy and portable restore keep every required immutable fragment image',async t=>{
 const f=await fixture(t);let s=await f.get();const appended=await f.api('study.excerpt.append',{setId:s.id,expectedRevision:s.revision,cardId:f.cardId,documentId:f.pdf.id,expectedSourceVersion:f.pdf.sourceVersion,captureId:randomUUID(),text:'',locator:{page:2},selection:{rects:[{page:2,x:.1,y:.1,width:.6,height:.2}]}});s=await f.get();
 const other=await f.api('study.create',{title:'Copies'});s=await f.api('study.cards.copy',{setId:s.id,expectedRevision:s.revision,targetSetId:other.id,targetRevision:other.revision,cardIds:[f.cardId]});
 const copy=await f.api('study.get',{setId:other.id});assert.equal(copy.cards[0].excerptParts.length,2);assert((await f.api('study.excerpt.image',{setId:other.id,cardId:copy.cards[0].id,partId:appended.partId})).contentBase64.length>100);
 await f.api('study.package.export',{setId:f.setId,path:'parts.mrpkg'});const imported=await f.api('study.package.import',{path:'parts.mrpkg',folder:'Restored'});const restored=await f.api('study.get',{setId:imported.setId});const c=restored.cards[0];assert.equal(c.excerptParts.length,2);for(const part of c.excerptParts)assert((await f.api('study.excerpt.image',{setId:restored.id,cardId:c.id,partId:part.id})).contentBase64.length>100);
 s=await f.get();await f.api('study.excerpt.remove',{setId:s.id,expectedRevision:s.revision,cardId:f.cardId,partId:appended.partId});s=await f.get();assert.equal(s.cards[0].excerptParts.length,1);await f.error('study.excerpt.remove',{setId:s.id,expectedRevision:s.revision,cardId:f.cardId,partId:f.cardId},'INVALID_PARAMS');s=await f.api('study.undo',{setId:s.id,expectedRevision:s.revision});assert.equal(s.cards[0].excerptParts.length,2);
});
