'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');const {setup}=require('./fixtures.cjs');
async function fixture(t){const f=await setup(t);let set=await f.api('study.create',{title:'Copy map'});const change=async(method,p={})=>set=await f.api(method,{setId:set.id,expectedRevision:set.revision,...p});await change('study.mindmap.template.apply',{template:'brainstorm'});const root=set.cards[0].id,children=set.cards.filter(c=>c.parentId===root).map(c=>c.id);await change('study.mindmap.decoration.set',{kind:'boundary',cardIds:children,style:{title:'Boundary'}});await change('study.mindmap.decoration.set',{kind:'summary',cardIds:children,style:{title:'Summary'}});const summary=set.map.mindmap.items.find(i=>i.kind==='summary');await change('study.note.create',{title:'Summary child',parentId:summary.topicId});return {...f,get set(){return set;},change,root,summary,refresh:async()=>set=await f.api('study.get',{setId:set.id})};}
test('copying a complete branch retains grouped boundaries, summaries and their child topics with independent IDs',async t=>{
 const f=await fixture(t),original=f.set,count=original.cards.length;await f.change('study.cards.copy',{cardIds:[f.root]});assert.equal(f.set.cards.length,count*2);const items=f.set.map.mindmap.items;assert.equal(items.length,4);const copied=items.filter(i=>!original.map.mindmap.items.some(old=>old.id===i.id));assert(copied.every(i=>i.cardIds.every(id=>!original.cards.some(c=>c.id===id))));const summary=copied.find(i=>i.kind==='summary');assert(f.set.cards.some(c=>c.parentId===summary.topicId&&c.title==='Summary child'));assert.equal(f.set.cards.find(c=>c.id===summary.topicId).parentId,null);await f.change('study.undo');assert.deepEqual(f.set.cards.map(c=>c.id),original.cards.map(c=>c.id));assert.deepEqual(f.set.map.mindmap.items,original.map.mindmap.items);
});
test('cross-study cut retains visual group identities and linked undo restores both owners; cutting a summary alone becomes a normal topic',async t=>{
 const f=await fixture(t),original=f.set;let target=await f.api('study.create',{title:'Destination'});const clip=await f.api('study.clipboard.set',{setId:original.id,expectedRevision:original.revision,cardIds:[f.root],mode:'cut'});
 const pasted=await f.api('study.clipboard.paste',{setId:target.id,expectedRevision:target.revision,clipboardId:clip.clipboard.id});target=await f.api('study.get',{setId:target.id});await f.refresh();assert.equal(f.set.cards.length,0);assert.equal(target.cards.length,original.cards.length);assert.deepEqual(target.map.mindmap.items,original.map.mindmap.items);assert.equal(target.cards.find(c=>c.id===f.summary.topicId).parentId,null);
 await f.api('study.undo',{setId:target.id,expectedRevision:target.revision});await f.refresh();assert.equal(f.set.cards.length,original.cards.length);assert.deepEqual(f.set.map.mindmap.items,original.map.mindmap.items);
 target=await f.api('study.get',{setId:target.id});const separate=await f.api('study.clipboard.set',{setId:f.set.id,expectedRevision:f.set.revision,cardIds:[f.summary.topicId],mode:'cut'});await f.api('study.clipboard.paste',{setId:target.id,expectedRevision:target.revision,clipboardId:separate.clipboard.id});target=await f.api('study.get',{setId:target.id});assert.equal(target.cards.length,2);assert(target.cards.some(c=>c.id===f.summary.topicId));assert.equal((await f.refresh()).map.mindmap.items.some(i=>i.id===f.summary.id),false);
});
test('mixed long-label shapes and same-level widths are measured before layout so topic boxes do not overlap',async()=>{
 const {layoutMindmap}=await import('../ui/mindmap-layout.mjs'),catalog=require('../ui/mindmap-catalog.json');let n=1;const id=()=>String(n++).padStart(8,'0')+'-0000-4000-8000-000000000000';const root={id:id(),title:'复杂格式',parentId:null},cards=[root];let i=0;
 for(const shape of Object.keys(catalog.shapes)){const c={id:id(),title:'Long 标题 🙂 '+shape,parentId:root.id,mindmap:{shape,width:140+(i++%4)*80,fontSize:14}};cards.push(c);cards.push({id:id(),title:'Nested topic '+shape,parentId:c.id});}
 for(const structure of Object.keys(catalog.structures)){const l=layoutMindmap(cards,{mindmap:{enabled:true,structure,sameLevelWidth:true}});assert.equal(l.positions.size,cards.length);const boxes=[...l.positions.values()];for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert(!(a.x<b.x+b.width-.1&&a.x+a.width>b.x+.1&&a.y<b.y+b.height-.1&&a.y+a.height>b.y+.1),structure+' overlap '+i+','+j);}}
});
test('default palette text maintains contrast and batching keeps every branch path and overview glyph',async()=>{
 const {topicStyle}=await import('../ui/mindmap-style.mjs'),{contrast}=await import('../ui/color-contrast.mjs'),catalog=require('../ui/mindmap-catalog.json');
 for(const theme of Object.keys(catalog.themes))for(let depth=0;depth<4;depth++)for(let branch=0;branch<6;branch++){const s=topicStyle({title:'Topic'},{theme},depth,branch);assert(contrast(s.textColor,s.fill)>=4.59,theme+' contrast');}
 const {layoutMindmap}=await import('../ui/mindmap-layout.mjs'),{diagramPaths}=await import('../ui/mindmap-view.mjs'),{overviewGlyphs,hitTopic}=await import('../ui/mindmap-overview.mjs');
 const cards=[{id:'root',title:'Root',parentId:null},...Array.from({length:1500},(_,i)=>({id:'t'+i,title:'Topic '+i,parentId:'root'}))],l=layoutMindmap(cards,{mindmap:{enabled:true}});const svg=diagramPaths(l,[]);assert((svg.match(/<path /g)||[]).length<50);assert.equal((svg.match(/M[-\d.]+,/g)||[]).length,1500);const glyphs=overviewGlyphs(l,new Set(l.positions.keys()),'root');assert.equal(glyphs.count,1500);assert.equal((glyphs.svg.match(/M[-\d.]+,/g)||[]).length,1500);const p=l.positions.get('t1499');assert.equal(hitTopic(l,p.x+p.width/2,p.y+p.height/2),'t1499');
});
test('map SVG export keeps literal rich-title formatting, note previews and saved handwriting',async t=>{
 const f=await fixture(t),id=f.root;await f.change('study.card.update',{cardId:id,title:'Formatted title',note:'Visible note preview'});await f.change('study.mindmap.topics.update',{cardIds:[id],patch:{runs:[{start:0,end:9,color:'#A23355',italic:true}],showNote:true}});
 await f.change('study.card.ink.add',{cardId:id,points:[[.1,.7],[.8,.8]],color:'blue',width:.004});await f.change('study.canvas.ink.add',{points:[[15,25],[80,40]],color:'green',width:2});
 const result=await f.api('study.mindmap.export',{setId:f.set.id,expectedRevision:f.set.revision,path:'rich.svg',format:'svg'});assert.equal(result.inkStrokes,2);const svg=await fs.readFile(path.join(f.workspace,'rich.svg'),'utf8');assert(svg.includes('font-style="italic"'));assert(svg.includes('fill="#A23355"'));assert(svg.includes('Visible note preview'));
});

test('formatting another title range preserves unrelated rich styles and splits only the overlapping interval',async()=>{
 const {applyTitleRun}=await import('../ui/mindmap-rich-runs.mjs');
 const first=[{start:0,end:8,bold:true,color:'#AA3355'},{start:10,end:15,italic:true}];
 const frozen=structuredClone(first),next=applyTitleRun(first,3,5,{underline:true,color:'#3377AA'});
 assert.deepEqual(next,[{start:0,end:3,bold:true,color:'#AA3355'},{start:3,end:5,underline:true,color:'#3377AA'},{start:5,end:8,bold:true,color:'#AA3355'},{start:10,end:15,italic:true}]);
 assert.deepEqual(first,frozen,'The caller-owned ranges must not be mutated');
 const separate=applyTitleRun(first,16,19,{bold:true});assert.deepEqual(separate.slice(0,2),first);assert.equal(separate.at(-1).start,16);
 assert.deepEqual(applyTitleRun([{start:0,end:3,bold:true}],3,5,{bold:true}),[{start:0,end:5,bold:true}]);
});
