'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {setup,pdfFixture}=require('./fixtures.cjs');
const change=(f,s,m,p={})=>f.api(m,{setId:s.id,expectedRevision:s.revision,...p});
const output=async()=>path.resolve((await fs.readFile(path.join(__dirname,'../artifacts/completion-current.txt'),'utf8')).trim());
test('automatic pitch plans keep every large-branch topic, paginate contexts and retain stable identities across delivery modes',async()=>{
 const {pitchPlan,pitchScene}=await import('../ui/mindmap-pitch.mjs'),cards=[{id:'root',parentId:null,title:'Large branch'}];for(let i=0;i<120;i++)cards.push({id:'n'+i,parentId:'root',title:'Child '+i,note:'Note '+i});
 for(const delivery of ['topics','branches','step']){const frames=pitchPlan(cards,{delivery});assert.equal(new Set(frames.flatMap(f=>[f.cardId,...f.childIds])).size,121);assert(frames.every(f=>f.childIds.length<=6));assert.equal(new Set(frames.map(f=>f.id)).size,frames.length);for(const frame of frames){const scene=pitchScene({cards,title:'Presentation',map:{mindmap:{}}},frame,{});for(const b of scene.boxes){assert(b.x>=0&&b.y>=scene.top&&b.x+b.w<=scene.w&&b.y+b.h<=scene.h);assert(b.lines.length*b.fontSize*1.45<=b.h+1);}}}
 cards[10].mindmap={pitch:{visible:false}};const plan=pitchPlan(cards);assert(!plan.some(f=>f.cardId==='n9'));assert(plan.some(f=>f.childIds.includes('n9')));
});
test('presentation settings, per-topic visibility and sessions use one public checked model',async t=>{
 const f=await setup(t);let s=await f.api('study.create',{title:'Automatic pitch'});s=await change(f,s,'study.mindmap.outline.import',{text:'Root\n  One\n    Detail\n  Two\n    Second'});const before=s.revision,id=s.cards[1].id;
 s=await change(f,s,'study.mindmap.configure',{patch:{pitch:{layout:'list',delivery:'step',theme:'dark',ratio:'4:3'}},topicPitch:{cardId:id,visible:false}});assert.equal(s.revision,before+1);const plan=await f.api('study.mindmap.pitch.plan',{setId:s.id});assert(!plan.frames.some(f=>f.cardId===id));assert(plan.frames.every(f=>f.layout==='list'));
 s=await change(f,s,'study.presentation.start',{mode:'map'});assert.deepEqual(s.presentation.frames,plan.frames);assert.deepEqual(s.presentation.cardIds,plan.frames.map(f=>f.cardId));s=await change(f,s,'study.presentation.action',{action:'next'});assert.equal(s.presentation.index,1);s=await change(f,s,'study.presentation.action',{action:'stop'});assert(!s.presentation.enabled);
 const revision=s.revision;await f.error('study.mindmap.configure',{setId:s.id,expectedRevision:s.revision,patch:{pitch:{layout:'grid'}},topicPitch:{cardId:'not-a-topic',visible:false}},'NOT_FOUND');assert.equal((await f.api('study.get',{setId:s.id})).revision,revision);
});
test('PPTX contains real editable text, notes, vector formula and nonempty raster fallback; PDF exports all searchable slides',async t=>{
 const f=await setup(t);let s=await f.api('study.create',{title:'自动演示验收'});s=await change(f,s,'study.mindmap.outline.import',{text:'知识工作台\n  数学与推导\n  实验记录\n  原文摘录'});
 const math=s.cards.find(c=>c.title==='数学与推导'),record=s.cards.find(c=>c.title==='实验记录');s=await change(f,s,'study.mindmap.topics.update',{cardIds:[math.id],patch:{equation:{latex:String.raw`\int_0^1 x^2\,dx=\frac{1}{3}`,scale:1}}});s=await change(f,s,'study.card.update',{cardId:record.id,note:'完整演讲者笔记。'.repeat(160)+'KEEP_NOTES_END'});
 const r=await f.api('study.mindmap.export',{setId:s.id,expectedRevision:s.revision,format:'pptx',path:'editable-pitch.pptx'});assert(r.editableText);assert(r.vectorGraphics);assert.equal(r.slides,4);
 const bytes=await fs.readFile(path.join(f.workspace,r.path)),zip=await require('jszip').loadAsync(bytes),slides=Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)),notes=Object.keys(zip.files).filter(n=>/^ppt\/notesSlides\/notesSlide\d+\.xml$/.test(n));assert.equal(slides.length,4);assert.equal(notes.length,4);
 const all=(await Promise.all(slides.map(n=>zip.file(n).async('string')))).join('\n'),allNotes=(await Promise.all(notes.map(n=>zip.file(n).async('string')))).join('\n');for(const c of s.cards)assert(all.includes(c.title));assert(allNotes.includes('KEEP_NOTES_END'));assert(all.includes('<p:transition'));assert(all.includes('asvg:svgBlip'));assert(all.includes('<p:sp>'));assert(all.includes('<a:t>'));
 const vectors=Object.keys(zip.files).filter(n=>n.startsWith('ppt/media/')&&n.endsWith('.svg')),rasters=Object.keys(zip.files).filter(n=>n.startsWith('ppt/media/')&&n.endsWith('.png'));assert(vectors.length>=1);assert(rasters.length>=1);const {loadImage}=require('@napi-rs/canvas');for(const n of rasters){const b=await zip.file(n).async('nodebuffer'),img=await loadImage(b);assert(img.width>=100&&img.height>=20,n+' placeholder raster');}
 const out=await output();await fs.writeFile(path.join(out,'editable-pitch.pptx'),bytes);
 const exported=await f.api('study.mindmap.export',{setId:s.id,expectedRevision:s.revision,format:'pdf',content:'pitch',path:'pitch.pdf'});assert.equal(exported.slides,4);assert(exported.vector);const pdfBytes=await fs.readFile(path.join(f.workspace,exported.path)),pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs'),task=pdfjs.getDocument({data:new Uint8Array(pdfBytes),verbosity:0,isEvalSupported:false});
 try{const pdf=await task.promise;assert.equal(pdf.numPages,4);const text=[];for(let i=1;i<=4;i++)text.push((await(await pdf.getPage(i)).getTextContent()).items.map(x=>x.str).join(''));assert(text[0].includes('知识工作台'));assert(text[1].includes('数学与推导'));const page=await pdf.getPage(2),v=page.getViewport({scale:1}),canvas=require('@napi-rs/canvas').createCanvas(Math.ceil(v.width),Math.ceil(v.height));await page.render({canvasContext:canvas.getContext('2d'),viewport:v}).promise;await fs.writeFile(path.join(out,'pitch-formula-page.png'),await canvas.encode('png'));}finally{await task.destroy();}
 await fs.writeFile(path.join(out,'pitch.pdf'),pdfBytes);await fs.writeFile(path.join(out,'pitch-export-results.json'),JSON.stringify({pptx:r,pdf:exported,editableText:true,notesEndPreserved:true,svgAssets:vectors.length},null,2));assert.equal((await f.api('study.get',{setId:s.id})).revision,s.revision);
});
test('visual reset preserves equations, placement and presentation semantics',async t=>{
 const f=await setup(t);let s=await f.api('study.create',{title:'Content reset'});s=await change(f,s,'study.note.create',{title:'Formula'});const id=s.cards[0].id;s=await change(f,s,'study.mindmap.topics.update',{cardIds:[id],patch:{fill:'#AA8844',equation:{latex:'x^2',scale:1},pitch:{visible:false},offset:{x:20,y:30}}});s=await change(f,s,'study.mindmap.topics.update',{cardIds:[id],patch:{},reset:true});assert(s.cards[0].mindmap.equation);assert.deepEqual(s.cards[0].mindmap.offset,{x:20,y:30});assert.equal(s.cards[0].mindmap.pitch.visible,false);assert.equal(s.cards[0].mindmap.fill,undefined);
});
