'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),JSZip=require('jszip');
const {setup}=require('./fixtures.cjs');
async function build(t){const f=await setup(t);let set=await f.api('study.create',{title:'Map tools'});const change=async(method,p={})=>set=await f.api(method,{setId:set.id,expectedRevision:set.revision,...p});await change('study.mindmap.outline.import',{text:'中心主题\n  Planning\n    Costs\n    Risks\n  Delivery\n    Review'});return {...f,get set(){return set;},change,refresh:async()=>set=await f.api('study.get',{setId:set.id})};}
test('quick outline appends stable nested topics; malformed indentation fails atomically and a single undo removes only the new import',async t=>{
 const f=await build(t),set=f.set;assert.equal(set.cards.length,6);assert.equal(set.cards[2].parentId,set.cards[1].id);
 await f.error('study.mindmap.outline.import',{setId:set.id,expectedRevision:set.revision,text:'Root\n      Jump'},'INVALID_PARAMS');assert.equal((await f.refresh()).cards.length,6);
 await f.change('study.mindmap.outline.import',{parentId:set.cards[1].id,text:'# Added\n## Nested\n### Leaf'});assert.equal(f.set.cards.find(c=>c.title==='Added').parentId,set.cards[1].id);assert.equal(f.set.lastMindmapOutline.count,3);await f.change('study.undo');assert.deepEqual(f.set.cards.map(c=>c.id),set.cards.map(c=>c.id));
});
test('topic filters search the complete hidden graph with pagination, markers and due dates without changing state',async t=>{
 const f=await build(t),id=f.set.cards[2].id;await f.change('study.mindmap.topics.update',{cardIds:[id],patch:{priority:2,progress:75,status:'doing',symbol:'idea',task:{due:'2026-10-09'}}});await f.change('study.card.update',{cardId:id,note:'Need review'});await f.change('study.card.update',{cardId:f.set.cards[0].id,collapsed:true});
 const before=await fs.readFile(path.join(f.workspace,'.margin-reader/state.json'));const result=await f.api('study.mindmap.query',{setId:f.set.id,filter:{priority:2,progressMin:70,progressMax:80,status:'doing',hasNote:true,dueBefore:'2026-10-10'},limit:1});assert.equal(result.total,1);assert.equal(result.cards[0].id,id);assert.equal(result.nextOffset,null);
 const first=await f.api('study.mindmap.query',{setId:f.set.id,limit:2}),second=await f.api('study.mindmap.query',{setId:f.set.id,offset:first.nextOffset,limit:2});assert.equal(first.total,6);assert.notEqual(first.cards[0].id,second.cards[0].id);assert.deepEqual(await fs.readFile(path.join(f.workspace,'.margin-reader/state.json')),before);
 await f.error('study.mindmap.query',{setId:f.set.id,filter:{progressMin:-1}},'INVALID_PARAMS');await f.error('study.mindmap.query',{setId:f.set.id,filter:{private:true}},'INVALID_PARAMS');
});
test('literal find/replace previews without writes; dollar replacement, stale revisions, field binding and undo are exact',async t=>{
 const f=await build(t),id=f.set.cards[2].id;await f.change('study.card.update',{cardId:id,title:'Cost [USD] Cost',note:'Cost remains a literal'});let revision=f.set.revision;const before=await fs.readFile(path.join(f.workspace,'.margin-reader/state.json'));
 const preview=await f.api('study.mindmap.replace',{setId:f.set.id,expectedRevision:revision,query:'cost',replacement:'$1 USD',field:'title'});assert.equal(preview.matches,2);assert.equal(preview.changes[0].after,'$1 USD [USD] $1 USD');assert.deepEqual(await fs.readFile(path.join(f.workspace,'.margin-reader/state.json')),before);
 await f.change('study.mindmap.replace',{query:'cost',replacement:'$1 USD',field:'title',apply:true});assert.equal(f.set.cards.find(c=>c.id===id).title,'$1 USD [USD] $1 USD');assert.equal(f.set.cards.find(c=>c.id===id).note,'Cost remains a literal');await f.error('study.mindmap.replace',{setId:f.set.id,expectedRevision:revision,query:'x',replacement:'y',apply:true},'CONFLICT');await f.change('study.undo');assert.equal(f.set.cards.find(c=>c.id===id).title,'Cost [USD] Cost');
});
test('public XMind JSON roundtrip keeps multiple sheets, summaries, local images and styles with new independent IDs',async t=>{
 const f=await build(t),root=f.set.cards[0],children=f.set.cards.filter(c=>c.parentId===root.id).map(c=>c.id);
 await f.change('study.mindmap.decoration.set',{kind:'boundary',cardIds:children,style:{title:'Shared scope',shape:'ellipse'}});await f.change('study.mindmap.decoration.set',{kind:'summary',cardIds:children,style:{title:'Conclusion'}});await f.change('study.mindmap.topics.update',{cardIds:[root.id],patch:{fill:'#AA3377',fontSize:28,priority:1,progress:100,shape:'ellipse'}});
 await f.change('study.link.add',{from:children[0],to:children[1],label:'Related',bidirectional:false});await f.change('study.mindmap.relationship.update',{linkId:f.set.links[0].id,patch:{end:'diamond',color:'#BB8844'}});
 const canvas=require('@napi-rs/canvas').createCanvas(90,60),ctx=canvas.getContext('2d');ctx.fillStyle='#cc5500';ctx.fillRect(0,0,90,60);await f.change('study.media.import',{cardId:children[0],kind:'image',contentBase64:(await canvas.encode('png')).toString('base64'),name:'Image'});
 const second=await f.api('study.create',{title:'Second sheet'});const total=f.set.cards.length;const result=await f.api('study.mindmap.xmind.export',{setIds:[f.set.id,second.id],expectedRevisions:{[f.set.id]:f.set.revision,[second.id]:second.revision},path:'roundtrip.xmind'});assert.equal(result.sheets,2);assert.equal(result.topics,total);
 const zip=await JSZip.loadAsync(await fs.readFile(path.join(f.workspace,'roundtrip.xmind'))),raw=JSON.parse(await zip.file('content.json').async('string'));assert.equal(raw.length,2);assert(zip.file('manifest.json'));assert(zip.file('metadata.json'));
 const before=await fs.readFile(path.join(f.workspace,'.margin-reader/state.json'));const inspection=await f.api('study.mindmap.xmind.inspect',{path:'roundtrip.xmind'});assert.equal(inspection.sheets.length,2);assert.deepEqual(await fs.readFile(path.join(f.workspace,'.margin-reader/state.json')),before);
 const imported=await f.api('study.mindmap.xmind.import',{path:'roundtrip.xmind',expectedVersion:inspection.sourceVersion});const copy=await f.api('study.get',{setId:imported.setId});assert.equal(copy.cards.length,total);assert.notEqual(copy.cards[0].id,root.id);assert.deepEqual(copy.cards[0].mindmap,f.set.cards[0].mindmap);assert.equal(copy.links[0].mindmap.end,'diamond');assert(copy.map.mindmap.items.every(i=>i.cardIds.every(id=>copy.cards.some(c=>c.id===id))));assert.equal(copy.cards.filter(c=>c.image).length,1);assert.equal(copy.cards.find(c=>c.title==='Planning').note,'');assert.equal(copy.cards.find(c=>c.title==='Planning').text,'');
 await f.error('study.mindmap.xmind.export',{setIds:[f.set.id],expectedRevisions:{[f.set.id]:f.set.revision},path:'roundtrip.xmind'},'ALREADY_EXISTS');
});
test('foreign XMind files require explicit warnings review and reject paths, invalid graphs and stale imports',async t=>{
 const f=await setup(t);const save=async(name,content,extra)=>{const z=new JSZip();z.file('content.json',JSON.stringify(content));if(extra)z.file(extra,'blocked');await fs.writeFile(path.join(f.workspace,name),await z.generateAsync({type:'nodebuffer'}));};
 const sheet={id:'sheet',title:'Foreign workbook',theme:{id:'theme'},rootTopic:{id:'root',title:'Root',children:{attached:[{id:'child',title:'Child',image:{src:'https://example.invalid/private.png'}}]}}};await save('foreign.xmind',[sheet]);const inspected=await f.api('study.mindmap.xmind.inspect',{path:'foreign.xmind'});assert(inspected.warnings.some(w=>w.code==='EXTERNAL_IMAGE'));await f.error('study.mindmap.xmind.import',{path:'foreign.xmind',expectedVersion:inspected.sourceVersion},'UNSUPPORTED_XMIND');assert.equal((await f.api('study.list')).sets.length,0);
 await f.api('study.mindmap.xmind.import',{path:'foreign.xmind',expectedVersion:inspected.sourceVersion,allowLossy:true});assert.equal((await f.api('study.list')).sets.length,1);
 await save('traversal.xmind',[sheet],'../outside.txt');await f.error('study.mindmap.xmind.inspect',{path:'traversal.xmind'},'SCOPE_DENIED');
 await save('duplicate.xmind',[{...sheet,rootTopic:{id:'root',title:'Root',children:{attached:[{id:'root',title:'Duplicate'}]}}}]);await f.error('study.mindmap.xmind.inspect',{path:'duplicate.xmind'},'INVALID_XMIND');
 await save('foreign.xmind',[{id:'other',rootTopic:{id:'other',title:'Replacement'}}]);await f.error('study.mindmap.xmind.import',{path:'foreign.xmind',expectedVersion:inspected.sourceVersion,allowLossy:true},'CONFLICT');
 const z=new JSZip();z.file('content.xml','<xmap-content/>');await fs.writeFile(path.join(f.workspace,'legacy.xmind'),await z.generateAsync({type:'nodebuffer'}));await f.error('study.mindmap.xmind.inspect',{path:'legacy.xmind'},'UNSUPPORTED_XMIND');
});
