'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {create,expect}=require('./ui-session.cjs'),{pdfFixture}=require('./fixtures.cjs');
(async()=>{const f=await create('scribble');let failure;
 try{const {page,api}=f;let set=await api('study.create',{mapMode:'cards',title:'涂抹删除'});const refresh=async()=>set=await api('study.get',{setId:set.id}),change=async(m,p={})=>{await refresh();return set=await api(m,{setId:set.id,expectedRevision:set.revision,...p});};await change('study.note.create',{title:'Map card'});const id=set.cards[0].id;await change('study.card.ink.add',{cardId:id,points:[[.1,.5],[.9,.5]],width:.01,color:'blue'});const cardInk=set.cards[0].ink[0].id;await change('study.card.ink.add',{cardId:id,reviewSide:'front',points:[[.1,.5],[.9,.5]],width:.01,color:'purple'});const front=set.cards[0].ink[1].id;
  const geometry=await api('study.map.geometry',{setId:set.id}),box=geometry.positions.find(p=>p.cardId===id);await change('study.canvas.ink.add',{points:[[box.x,box.y+box.height*.5],[box.x+box.width,box.y+box.height*.5]],width:3,color:'green'});const canvasInk=set.canvasInk[0].id;
  await api('study.open',{setId:set.id});await page.goto(f.server.url);await page.waitForSelector('body[data-ready=true]');await page.click('#card-ink-settings');await page.selectOption('[name=shape]','free');await page.selectOption('[name=straighten]','off');await page.selectOption('[name=perfectShape]','yes');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('#card-ink-pen');
  const calls=[];page.on('request',r=>{if(r.url().endsWith('/rpc')){const data=r.postDataJSON();if(data.method?.endsWith('.ink.add')&&data.params?.geometry?.heldMs>=500)calls.push(data);}});
  const waitForReaderGeometry=async el=>{
   let previous='',stableAt=0;
   await expect.poll(async()=>{
    const sample=await el.evaluate(node=>JSON.stringify({rect:node.getBoundingClientRect().toJSON(),busy:document.getElementById('reader-scroll').getAttribute('aria-busy')}));
    if(sample!==previous){previous=sample;stableAt=Date.now();return false;}
    return Date.now()-stableAt>=180&&JSON.parse(sample).busy==='false';
   }).toBe(true);
  };
  const scribble=async el=>{await refresh();await expect(page.locator('#study-board')).toHaveAttribute('data-revision',String(set.revision));await expect(el).toBeVisible();
   if(await el.evaluate(node=>Boolean(node.closest('#reader-scroll'))))await waitForReaderGeometry(el);
   const b=await el.evaluate(node=>{const r=node.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};});await page.mouse.move(b.x+b.width*.2,b.y+b.height*.35);await page.mouse.down();for(let i=1;i<8;i++)await page.mouse.move(b.x+b.width*(i%2?.8:.2),b.y+b.height*(.35+.28*i/7),{steps:2});};
  const card=page.locator(`.study-card[data-card-id="${id}"]`);await scribble(card);await expect.poll(async()=>((await refresh()).canvasInk||[]).length).toBe(0);assert.deepEqual(set.cards[0].ink.map(i=>i.id),[front]);const deletedRevision=set.revision;assert.equal(set.lastInk.recognizedShape,'scribble');assert.equal(calls.length,1);await page.mouse.up();await page.waitForTimeout(600);assert.equal((await refresh()).revision,deletedRevision);assert.equal(calls.length,1);await page.click('#study-undo');await expect.poll(async()=>(await refresh()).cards[0].ink.length).toBe(2);assert.equal(set.cards[0].ink[0].id,cardInk);assert.equal(set.canvasInk[0].id,canvasInk);
  f.pass('Holding a card scribble deletes touching map and card ink before release, preserves front-only ink and makes exactly one undoable write');
  await scribble(card);await page.mouse.up();await expect.poll(async()=>(await refresh()).cards[0].ink.length).toBe(3);assert.equal(set.cards[0].ink.at(-1).recognizedShape,'free');assert.equal(set.canvasInk.length,1);await page.click('#study-undo');await expect.poll(async()=>(await refresh()).cards[0].ink.length).toBe(2);
  f.pass('The same quick gesture without a hold saves ordinary handwriting and leaves previous ink intact');
  const conflict=page.waitForResponse(r=>r.url().endsWith('/rpc')&&r.request().postDataJSON()?.method==='study.map.ink.add'&&r.request().postDataJSON()?.params?.geometry?.heldMs===500);conflict.catch(()=>{});await scribble(card);await change('study.card.update',{cardId:id,title:'Changed while holding'});assert.equal((await (await conflict).json()).error.data.code,'CONFLICT');await expect(page.locator('#card-ink-retry')).toBeVisible();await page.mouse.up();const requests=calls.length;await page.waitForTimeout(600);assert.equal(calls.length,requests);await refresh();assert.equal(set.cards[0].ink.length,2);assert.equal(set.canvasInk.length,1);await page.click('#card-ink-retry');await expect.poll(async()=>(await refresh()).canvasInk.length).toBe(0);assert.equal(set.cards[0].ink.length,1);await expect(page.locator('#card-ink-retry')).toBeHidden();await page.click('#study-undo');await expect.poll(async()=>(await refresh()).canvasInk.length).toBe(1);
  f.pass('A conflict preserves the scribble draft without silently retrying on release; explicit retry and undo work');
  await page.click('#card-ink-settings');await page.selectOption('[name=brush]','laser');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await refresh();const beforeLaser=set.revision;await scribble(card);await page.waitForTimeout(650);await page.mouse.up();await page.waitForTimeout(700);assert.equal((await refresh()).revision,beforeLaser);assert.equal(set.cards[0].ink.length,2);assert.equal(set.canvasInk.length,1);await page.click('#card-ink-settings');await page.selectOption('[name=brush]','pen');await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();await page.click('#card-ink-pen');
  f.pass('A held laser scribble is temporary and never erases or saves any ink');
  await fs.writeFile(f.workspace+'/ink.pdf',pdfFixture());const doc=await api('document.open',{path:'ink.pdf',activate:false});await change('study.documents.add',{paths:['ink.pdf']});await change('study.ink.add',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,page:1,points:[[.1,.5],[.9,.5]],width:.004,color:'blue'});const docInk=set.ink[0].id;await api('study.open',{setId:set.id,documentId:doc.id});await page.reload();await page.waitForSelector('body[data-ready=true]');const paper=page.locator('.pdf-page[data-page="1"][data-render-state=ready]');await expect(paper).toBeVisible();await page.click('#study-pen');await scribble(paper);await expect(page.locator('#study-ink-status')).toContainText('已删除 1 笔');await refresh();assert.equal(set.ink.length,0);const paperRevision=set.revision;await page.mouse.up();await page.waitForTimeout(550);assert.equal((await refresh()).revision,paperRevision);await page.click('#study-undo');await expect.poll(async()=>(await refresh()).ink.length).toBe(1);assert.equal(set.ink[0].id,docInk);
  f.pass('A document scribble commits on hold, does not save again on release and restores the original stroke on undo');
  await change('study.note.place',{documentId:doc.id,expectedSourceVersion:doc.sourceVersion,title:'Embedded note',text:'Ink here',locator:{page:1},display:'overlay',rect:{x:.1,y:.35,width:.4,height:.3},height:180});const note=set.cards.find(c=>c.title==='Embedded note');await change('study.card.ink.add',{cardId:note.id,points:[[.1,.5],[.9,.5]],width:.01,color:'green'});const el=page.locator(`section[data-note-card="${note.id}"]`);await expect(el).toBeVisible();await scribble(el);await expect.poll(async()=>((await refresh()).cards.find(c=>c.id===note.id).ink||[]).length).toBe(0);assert.equal(set.ink[0].id,docInk);assert.equal(set.canvasInk.length,1);await page.mouse.up();await page.reload();await page.waitForSelector('body[data-ready=true]');await expect(el.locator('[data-card-stroke]')).toHaveCount(0);await expect(page.locator(`[data-stroke-id="${docInk}"]`)).toHaveCount(1);await page.screenshot({path:path.join(f.output,'scribble.png')});
  f.pass('An embedded note scribble targets only its card; PDF and map ink survive and the deletion persists after reopening');
 }catch(e){failure=e;}f.report.validation={passed:f.report.checks,failed:failure?[failure.message]:[],skipped:[],untested:['Windows','Linux','physical pen hardware']};await f.finish(failure);
})().catch(e=>{console.error(e);process.exitCode=1;});
