'use strict';
const fs = require('node:fs/promises');
const fsSync = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const { createHash } = require('node:crypto');
const exec = require('node:util').promisify(require('node:child_process').execFile);
const root = path.resolve(__dirname,'..'), host = path.resolve(root,'../..');
const pluginRoot = process.env.SELECTION_PLUGIN_ROOT || path.join(root,'dist-plugin');
const { chromium, _electron, expect } = require(path.join(host,'node_modules/@playwright/test'));
async function hash(file) { const h=createHash('sha256');for await(const part of fsSync.createReadStream(file))h.update(part);return h.digest('hex'); }
async function main() {
  const temp = await fs.mkdtemp(path.join(os.tmpdir(),'margin-selection-'));
  const artifact = path.join(root,'artifacts','selection-'+new Date().toISOString().replace(/[:.]/g,'-'));
  await fs.mkdir(artifact,{recursive:true});
  const native = process.env.SELECTION_NATIVE === '1';
  const report = { status:'running',native,version:JSON.parse(await fs.readFile(path.join(pluginRoot,'package.json'))).version,checks:[],browserErrors:[] };
  const pass = label => { report.checks.push(label);console.log('PASS '+label); };
  let app,browser,server,page,workspace,api;
  const book = 'AI Systems Performance Engineering.pdf', article = 'Prompt Engineering.html';
  const source = path.join(root,'workspaces/default',book), originalHash = await hash(source);
  try {
    if (native) {
      const env={...process.env,AGENTS_COMPANY_HOME:path.join(temp,'home'),AGENTS_COMPANY_WORKSPACES:path.join(temp,'workspaces'),AGENTS_COMPANY_PROJECTS:path.join(temp,'projects'),AGENTS_COMPANY_PLUGIN_DIRS:pluginRoot,AGENTS_COMPANY_HIDDEN:'1'};
      for(const k of ['ELECTRON_RUN_AS_NODE','AGENTS_COMPANY_TOKEN','AGENTS_COMPANY_TOKEN_FILE','AGENTS_COMPANY_SOCKET','AGENTS_COMPANY_PORT','AGENTS_COMPANY_PLUGIN_RPC','AGENTS_WORKSPACE'])delete env[k];
      app=await _electron.launch({executablePath:'/Applications/Agents Company.app/Contents/MacOS/Agents Company',args:[],env});await app.firstWindow();
      const cli=async(...args)=>{const reply=JSON.parse((await exec(process.execPath,[path.join(host,'bin/agents'),...args,'--json'],{env,timeout:90000,maxBuffer:16*1024*1024})).stdout);assert(reply.ok,reply.error);return reply.data;};
      api=(method,params={})=>cli('plugin','call','margin-reader',method,'--params',JSON.stringify(params));
      workspace=(await api('system.info')).workspace;
      const opened=app.waitForEvent('window');await cli('plugin','open','margin-reader');page=await opened;
    } else {
      workspace=path.join(temp,'library');await fs.mkdir(workspace);
      server=await require(path.join(pluginRoot,'lib/server.cjs')).startServer({workspace,pluginRoot});
      api=async(method,params={})=>{const reply=await server.runtime.request({jsonrpc:'2.0',id:1,method,params});assert(!reply.error,JSON.stringify(reply.error));return reply.result;};
      try{browser=await chromium.launch({headless:true});}catch(error){
        const cache=path.join(os.homedir(),'Library/Caches/ms-playwright');
        const executablePath=fsSync.readdirSync(cache).filter(n=>n.startsWith('chromium_headless_shell-')).sort().reverse().map(n=>path.join(cache,n,'chrome-headless-shell-mac-arm64/chrome-headless-shell')).find(p=>fsSync.existsSync(p));
        if(!executablePath)throw error;browser=await chromium.launch({headless:true,executablePath});
      }
      page=await browser.newPage();await page.goto(server.url);
    }
    page.setDefaultTimeout(30000);page.on('pageerror',e=>report.browserErrors.push(e.message));await page.setViewportSize({width:1440,height:960});
    await page.waitForSelector('body[data-ready=true]');
    await fs.copyFile(source,path.join(workspace,book));await fs.copyFile(path.join(root,'workspaces/default',article),path.join(workspace,article));
    for(const folder of ['归档','副本','子目录/空文件夹'])await api('fs.mkdir',{path:folder});
    for(const name of ['A.md','B.md','C.md'])await api('fs.write',{path:name,content:`# ${name}\n\nSingle-click reading test.`});
    await page.click('#refresh-files');
    const card = name => page.locator('#files .file-card[data-path='+JSON.stringify(name)+']');
    const count = n => expect(page.locator('#selected-name')).toHaveText(`已选择 ${n} 项`);
    const enter = async()=>{if(await page.getAttribute('#select-files','aria-pressed')!=='true')await page.click('#select-files');};
    const done = async()=>{if(await page.getAttribute('#select-files','aria-pressed')==='true')await page.click('#select-files');};
    const select = async names=>{await enter();for(const name of names)await card(name).locator('.file-open').click();};
    const submit = async()=>{await page.click('#dialog-submit');await expect(page.locator('#dialog')).toBeHidden();};
    const home = async()=>{await page.click('#library-root');await expect(page.locator('#folder-title')).toHaveText('我的文库');};
    await expect(card(book)).toHaveAttribute('data-preview','ready');await expect(page.locator('#folder-back')).toHaveCount(0);
    await expect(page.locator('#files > :first-child')).toHaveClass(/file-card/);
    await expect(page.locator('#selection-actions')).toBeHidden();assert.equal(await page.locator('#selection-bar button:visible').count(),1);
    pass('Root has no back card or blank slot; the only ordinary toolbar action is Select');
    await page.screenshot({path:path.join(artifact,'normal-grid.png')});
    let openedRequests=0;page.on('request',request=>{try{if(request.postDataJSON()?.method==='document.open')openedRequests++;}catch{}});
    await card(book).locator('.file-open').click();
    await expect(page.locator('.pdf-page[data-page="1"]')).toHaveAttribute('data-render-state','ready',{timeout:120000});
    assert.equal(openedRequests,1);await expect(page.locator('#page-total')).toContainText('1061');
    const docId=(await api('settings.get')).lastDocument;await page.click('#back-library');
    await card(article).locator('.file-open').click();await expect(page.locator('.flow-document article')).toContainText('Prompt Engineering');await page.click('#back-library');
    pass('One click opens the real PDF or HTML without a second click or duplicate open request');
    await page.click('#list-view');await card('A.md').locator('.file-open').click();await expect(page.locator('.flow-document article')).toContainText('Single-click reading test');await page.click('#back-library');
    await expect(page.locator('#folder-back')).toHaveCount(0);await page.click('#grid-view');
    pass('Compact list also opens on one click and never shows a root back button');
    await card(book).locator('.file-more').click();await expect(page.locator('.file-context-menu')).toBeVisible();await expect(page.locator('#reader-view')).toBeHidden();await expect(page.locator('#selection-actions')).toBeHidden();await page.keyboard.press('Escape');
    pass('Three-dot menu stays independent: no reading or batch toolbar is triggered');
    const beforeSelection=openedRequests;await enter();await count(0);await expect(page.locator('#selection-actions')).toBeHidden();
    await select([book,article]);await count(2);await expect(page.locator('#selection-actions')).toBeVisible();await expect(page.locator('#rename-file')).toBeHidden();
    await expect(card(book).locator('.file-select')).toBeChecked();await expect(card(article).locator('.file-select')).toBeChecked();await expect(page.locator('#reader-view')).toBeHidden();assert.equal(openedRequests,beforeSelection);
    pass('Selection mode toggles multiple files without opening them; operations appear only after a selection');
    await page.screenshot({path:path.join(artifact,'selected-grid.png')});
    await page.click('#list-view');await expect(page.locator('#files')).toHaveClass(/list/);await count(2);await expect(card(article).locator('.file-select')).toBeChecked();
    await expect.poll(()=>page.locator('#files .file-card').evaluateAll(cards=>cards.length>0&&cards.every(card=>{const box=card.getBoundingClientRect(),more=card.querySelector('.file-more').getBoundingClientRect();return more.width>0&&box.right-more.right<18;}))).toBe(true);
    await page.click('#refresh-files');await count(2);await expect(card(book).locator('.file-select')).toBeChecked();
    await page.screenshot({path:path.join(artifact,'selected-list.png')});
    pass('Selections survive list/grid switching and refresh; the three dots remain at the far right');
    await card(article).locator('.file-select').uncheck();await count(1);await expect(page.locator('#rename-file')).toBeVisible();await card(article).locator('.file-select').check();await count(2);
    await page.click('#move-file');await expect(page.locator('#dialog-title')).toHaveText('移动 2 项');await page.click('#dialog-cancel');await count(2);assert((await fs.stat(path.join(workspace,book))).isFile());
    pass('Single selection exposes rename; cancelling a batch dialog preserves the selection and files');
    await page.click('#move-file');await page.selectOption('#dialog [name=folder]','归档');await submit();await count(0);await expect(page.locator('#selection-actions')).toBeHidden();
    assert.equal(await hash(path.join(workspace,'归档',book)),originalHash);assert.equal((await api('document.get',{id:docId})).path,'归档/'+book);
    assert((await fs.stat(path.join(workspace,'归档',article))).isFile());await expect(card(book)).toHaveCount(0);
    pass('Batch move transfers the selected PDF and HTML together and preserves the book identity and bytes');
    await done();await card('归档').locator('.file-open').click();await expect(page.locator('#folder-title')).toHaveText('归档');
    const back=await page.locator('#folder-back').boundingBox(),file=await card('归档/'+book).boundingBox();assert(Math.abs(back.width-file.width)<1&&Math.abs(back.height-file.height)<1);
    await enter();await page.click('#select-all-files');await count(2);await page.click('#copy-file');await page.selectOption('#dialog [name=folder]','副本');await submit();
    assert.equal(await hash(path.join(workspace,'副本',book)),originalHash);assert((await fs.stat(path.join(workspace,'归档',book))).isFile());
    pass('Subfolders retain the matching back card; Select all and batch copy keep originals intact');
    await page.click('#select-all-files');await count(2);await page.click('#trash-file');await expect(page.locator('#dialog-title')).toHaveText('移入回收站 2 项');await submit();
    await expect(page.locator('#empty-library')).toBeVisible();await expect(page.locator('#folder-back')).toBeVisible();await expect(page.locator('#selection-actions')).toBeHidden();
    const trashed=(await api('fs.trash.list')).items;assert.equal(trashed.length,2);for(const item of trashed)await api('fs.restore',{trashId:item.id});
    await page.click('#folder-back');await expect(page.locator('#folder-back')).toHaveCount(0);
    pass('Batch delete uses recoverable trash; an empty subfolder can still return to root');
    await select(['A.md','B.md']);await count(2);
    await fs.writeFile(path.join(workspace,'B.md'),'# Externally updated\n\nPreserve this newer content.');await page.click('#refresh-files');await count(2);
    await page.click('#move-file');await page.selectOption('#dialog [name=folder]','归档');await page.click('#dialog-submit');await expect(page.locator('#dialog-error')).toContainText('数据已被另一处修改');
    assert((await fs.stat(path.join(workspace,'A.md'))).isFile());assert.equal(await fs.readFile(path.join(workspace,'B.md'),'utf8'),'# Externally updated\n\nPreserve this newer content.');await page.click('#dialog-cancel');
    pass('A stale selection is rejected without silently using new versions or moving a partial batch');
    await card('B.md').locator('.file-select').uncheck();await card('B.md').locator('.file-select').check();
    await api('fs.write',{path:'归档/B.md',content:'keep existing destination'});await page.click('#move-file');await page.selectOption('#dialog [name=folder]','归档');await page.click('#dialog-submit');await expect(page.locator('#dialog-error')).toContainText('目标位置已有同名文件');
    assert((await fs.stat(path.join(workspace,'A.md'))).isFile());await assert.rejects(fs.stat(path.join(workspace,'归档/A.md')),{code:'ENOENT'});
    await page.selectOption('#dialog [name=folder]','子目录/空文件夹');await submit();await count(0);
    pass('Name conflicts leave the entire selection untouched; another destination can be chosen explicitly');
    await done();await card('C.md').locator('.file-open').click({modifiers:['Meta']});await count(1);await expect(page.locator('#reader-view')).toBeHidden();
    const order=await page.locator('#files .file-card').evaluateAll(cards=>cards.map(card=>card.dataset.path));
    await card('归档').locator('.file-open').click({modifiers:['Shift']});await count(Math.abs(order.indexOf('归档')-order.indexOf('C.md'))+1);await expect(page.locator('#reader-view')).toBeHidden();
    pass('Shift-click selects an inclusive range without navigating into a selected folder');
    await page.click('#select-all-files');await count((await api('fs.list')).entries.length);await page.click('#select-all-files');await count(0);await expect(page.locator('#selection-actions')).toBeHidden();
    await card('C.md').locator('.file-open').click();await count(1);await page.keyboard.press('Escape');await expect(page.locator('#select-files')).toHaveText('选择');await expect(card('C.md').locator('.file-select')).toBeHidden();
    await card('C.md').locator('.file-open').click();await expect(page.locator('.flow-document article')).toContainText('Single-click reading test');await page.click('#back-library');
    pass('Command-click, Select all, deselect and Escape work without breaking subsequent single-click reading');
    await card('子目录').locator('.file-open').click();await expect(page.locator('#folder-title')).toHaveText('子目录');await enter();await card('子目录/空文件夹').locator('.file-open').click();await count(1);await page.click('#folder-back');
    await expect(page.locator('#select-files')).toHaveText('选择');await expect(page.locator('#selection-actions')).toBeHidden();await expect(page.locator('#folder-back')).toHaveCount(0);
    pass('Navigation clears folder-scoped selection; folders can be selected without entering them');
    await select(['C.md','归档']);await page.setViewportSize({width:780,height:768});await page.click('#list-view');await count(2);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await expect(page.locator('#move-file')).toBeVisible();
    await page.click('#theme');await expect(page.locator('body')).toHaveAttribute('data-theme','dark');await page.screenshot({path:path.join(artifact,'selection-narrow-dark.png')});
    pass('Conditional batch toolbar and checkboxes remain usable at 780px and in dark mode');
    assert.equal(await hash(source),originalHash);assert.deepEqual(report.browserErrors,[]);
    if(native)assert(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().every(w=>!w.isVisible())));
    pass('Original book unchanged; no uncaught browser errors or model calls');report.status='passed';
  } catch(error) {report.status='failed';report.error={message:error.message,stack:error.stack};if(page&&!page.isClosed())await page.screenshot({path:path.join(artifact,'failure.png')}).catch(()=>{});throw error;}
  finally {report.finishedAt=new Date().toISOString();await fs.writeFile(path.join(artifact,'result.json'),JSON.stringify(report,null,2));console.log('SELECTION REPORT '+path.join(artifact,'result.json'));await browser?.close();await app?.close();await server?.close();await fs.rm(temp,{recursive:true,force:true});}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
