'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {setup,pdfFixture}=require('./fixtures.cjs');const R=require('../lib/page-reference.cjs');
async function fixture(t){const f=await setup(t);await fs.writeFile(path.join(f.workspace,'source.pdf'),pdfFixture());const source=await f.api('document.open',{path:'source.pdf',activate:false});const ref=page=>({documentId:source.id,expectedSourceVersion:source.sourceVersion,page});const virtual=await f.api('document.virtual.create',{path:'virtual.mrv',title:'Linked pages',pages:[ref(2),ref(1)],activate:false});return {...f,source,virtual,ref};}
test('virtual collection is a small reference file with real reorder/crop/rotate PDF output, stable ID and original hashes',async t=>{
 const f=await fixture(t),before=await fs.readFile(path.join(f.workspace,'source.pdf')),file=await fs.readFile(path.join(f.workspace,'virtual.mrv'));assert(file.length<3000);assert.equal(JSON.parse(file).pages[0].page,2);assert.equal(f.virtual.pageCount,2);assert.equal(f.virtual.format,'mrv');
 const asset=await f.runtime.readAsset(f.virtual.originalAsset);assert.equal(asset.mimeType,'application/pdf');assert.equal(Buffer.from(asset.bytes).subarray(0,4).toString(),'%PDF');assert.match((await f.api('document.content',{id:f.virtual.id,page:2})).text,/Introduction/);
 const modified=await f.api('document.virtual.update',{id:f.virtual.id,expectedRevision:f.virtual.revision,pages:[{...f.ref(1),rotation:90,crop:{x:.1,y:.1,width:.8,height:.4}},{blank:true,paper:'dots'}],activate:false});assert.equal(modified.id,f.virtual.id);assert(Math.abs(modified.sections[0].width-f.source.sections[0].height*.4)<.01);assert(Math.abs(modified.sections[0].height-f.source.sections[0].width*.8)<.01);assert.equal(modified.pageCount,2);
 const source=await f.api('document.virtual.source',{id:modified.id,page:1,point:[.5,.25]});assert.equal(source.documentId,f.source.id);assert.equal(source.locator.page,1);assert(Math.abs(source.locator.pageOffset-.3)<1e-9);
 assert.equal((await f.api('document.virtual.source',{id:modified.id,page:2})).blank,true);assert.deepEqual(await fs.readFile(path.join(f.workspace,'source.pdf')),before);
 const undo=await f.api('document.virtual.update',{id:modified.id,expectedRevision:modified.revision,action:'undo',activate:false});assert.equal(undo.virtual.pages[0].page,2);const redo=await f.api('document.virtual.update',{id:undo.id,expectedRevision:undo.revision,action:'redo',activate:false});assert.equal(redo.virtual.pages[0].rotation,90);
});
test('crop transforms invert right-angle rotations and clip out-of-view annotation rectangles',()=>{
 for(const rotation of [0,90,180,270]){const spec={crop:{x:.2,y:.1,width:.6,height:.7},rotation,page:3};for(const p of [[0,0],[.3,.7],[1,1]]){const source=R.toSource(p,spec),inverse=R.toDisplay(source,spec);assert(Math.abs(p[0]-inverse[0])<1e-9);assert(Math.abs(p[1]-inverse[1])<1e-9);}assert.equal(R.projectRect({x:0,y:0,width:.1,height:.05},spec,2),null);const rect=R.projectRect({x:.1,y:.2,width:.3,height:.2},spec,2);assert(rect.x>=-1e-9&&rect.y>=-1e-9&&rect.width>0&&rect.height>0);}
});
test('the same annotation is projected in both original and virtual views and virtual captures map back to physical pages',async t=>{
 const f=await fixture(t);let s=await f.api('study.create',{title:'Live marks'});s=await f.api('study.documents.add',{setId:s.id,expectedRevision:s.revision,paths:['source.pdf','virtual.mrv']});
 const capture=async(doc,page)=>{s=await f.api('study.get',{setId:s.id});return f.api('study.card.create',{setId:s.id,expectedRevision:s.revision,documentId:doc.id,expectedSourceVersion:doc.sourceVersion,captureId:randomUUID(),text:'',color:'green',locator:{page},selection:{rects:[{page,x:.15,y:.15,width:.4,height:.2}]}});};
 const a=await capture(f.source,1);s=await f.api('study.get',{setId:s.id});const locations=s.cards.find(c=>c.id===a.card.id).annotationLocations;assert(locations.some(l=>l.source.documentId===f.virtual.id&&l.source.locator.page===2&&!l.sourceChanged));
 const b=await capture(f.virtual,1);s=await f.api('study.get',{setId:s.id});const card=s.cards.find(c=>c.id===b.card.id);assert.equal(card.source.virtualSources[0].documentId,f.source.id);assert(card.annotationLocations.some(l=>l.source.documentId===f.source.id&&l.source.locator.page===2&&!l.sourceChanged));
 s=await f.api('study.annotation.update',{setId:s.id,expectedRevision:s.revision,cardId:a.card.id,visible:false});assert.equal(s.cards.find(c=>c.id===a.card.id).annotation.visible,false);
 const changed=await f.api('document.virtual.update',{id:f.virtual.id,expectedRevision:f.virtual.revision,action:'replace',pages:[f.ref(1),f.ref(2)],activate:false});s=await f.api('study.get',{setId:s.id});assert(s.cards.find(c=>c.id===b.card.id).annotationLocations.some(l=>l.source.documentId===changed.id&&l.source.locator.page===2&&!l.sourceChanged));
});
test('external originals invalidate virtual caches, explicit refresh recovers without stealing focus, missing sources remain visible errors',async t=>{
 const f=await fixture(t);await f.api('reader.position.set',{id:f.source.id,locator:{page:1}});await fs.appendFile(path.join(f.workspace,'source.pdf'),'\n% external harmless update\n');assert.equal((await f.api('document.get',{id:f.virtual.id})).sourceChanged,true);
 await f.error('document.content',{id:f.virtual.id,page:1},'SOURCE_CHANGED');const refreshed=await f.api('document.virtual.refresh',{id:f.virtual.id,expectedRevision:f.virtual.revision,activate:false});assert.equal(refreshed.sourceChanged,false);assert.equal((await f.api('settings.get')).lastDocument,f.source.id);
 assert.match((await f.api('document.content',{id:refreshed.id,page:2})).text,/Introduction/);await fs.rm(path.join(f.workspace,'source.pdf'));assert.equal((await f.api('document.get',{id:refreshed.id})).sourceChanged,true);await f.error('document.virtual.refresh',{id:refreshed.id,expectedRevision:refreshed.revision},'NOT_FOUND');
});
test('virtual packages restore independent original IDs and rendered pages without trusting cached page HTML',async t=>{
 const f=await fixture(t);let s=await f.api('study.create',{title:'Portable virtual'});s=await f.api('study.documents.add',{setId:s.id,expectedRevision:s.revision,paths:['virtual.mrv']});const p=await f.api('study.package.export',{setId:s.id,path:'virtual.mrpkg'});assert.equal(p.documents,2);
 const other=await setup(t);await fs.copyFile(path.join(f.workspace,'virtual.mrpkg'),path.join(other.workspace,'virtual.mrpkg'));const imported=await other.api('study.package.import',{path:'virtual.mrpkg',folder:'Recovered'});const study=await other.api('study.get',{setId:imported.setId});const doc=await other.api('document.get',{id:study.documentIds[0]});assert(doc.virtual);assert.notEqual(doc.virtual.pages[0].documentId,f.source.id);assert.equal(doc.sourceChanged,false);assert.match((await other.api('document.content',{id:doc.id,page:2})).text,/Introduction/);assert.equal(Buffer.from((await other.runtime.readAsset(doc.originalAsset)).bytes).subarray(0,4).toString(),'%PDF');
});
test('invalid virtual scopes, missing revisions and out-of-range references never create a partial file',async t=>{
 const f=await fixture(t);await f.error('document.virtual.create',{path:'../escape.mrv',pages:[f.ref(1)]},'SCOPE_DENIED');await f.error('document.virtual.create',{path:'bad.mrv',pages:[{...f.ref(1),page:999}]},'INVALID_LOCATOR');assert.equal(await fs.stat(path.join(f.workspace,'bad.mrv')).catch(()=>null),null);
 await f.error('document.virtual.update',{id:f.virtual.id,expectedRevision:0,pages:[f.ref(1)]},'INVALID_PARAMS');await f.error('document.virtual.source',{id:f.virtual.id,page:1,point:[2,0]},'INVALID_PARAMS');
});
