import {useEffect,useRef,useState,type FormEvent,type ChangeEvent} from 'react'
import type {ContractClient} from '../../Contract/protocol'
import type {WorkflowView,WorkflowFile} from '../../Contract/workflow'
import {inspectDocument,encodeBase64,MAX_UPLOAD_BYTES,type ResumeDocument,type TextPatch} from './document.mjs'
import {startProfile,readWord} from './workflow.mjs'
import {Preview} from './Preview'
import './style.css'

const stages=[['prepare','读取原稿'],['analyze','岗位与事实'],['optimize','定向优化'],['review','独立审校'],['layout','原版式验收']]
const engines=[['auto','自动选择已就绪引擎'],['pi','Pi'],['cline','Cline'],['codex','Codex'],['claude','Claude Code']]
const states:Record<string,string>={running:'处理中',waiting:'等待确认',completed:'已完成',failed:'需要处理',cancelled:'已取消'}
function Mark({name}:{name:'upload'|'file'|'check'|'arrow'|'download'}){const d={upload:'M12 16V4m-4 4 4-4 4 4M5 14v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-5',file:'M14 3H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8l-5-5zm0 0v5h5M8 12h8M8 16h6',check:'m5 12 4 4L19 6',arrow:'M5 12h14m-5-5 5 5-5 5',download:'M12 3v12m-4-4 4 4 4-4M5 16v4h14v-4'};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={d[name]}/></svg>}
export default function ProfileImprovement({client}:{client:ContractClient}){
 const [source,setSource]=useState<{data:Uint8Array;document:ResumeDocument}|null>(null),[sourceJobId,setSourceJobId]=useState(''),[targets,setTargets]=useState(''),[jd,setJd]=useState(''),[engine,setEngine]=useState('auto'),[model,setModel]=useState(''),[drag,setDrag]=useState(false)
 const [job,setJob]=useState<WorkflowView|null>(null),[history,setHistory]=useState<WorkflowView[]>([]),[busy,setBusy]=useState(false),[loadingFile,setLoadingFile]=useState(false),[error,setError]=useState(''),[connection,setConnection]=useState(''),[confirmCancel,setConfirmCancel]=useState(false),[initializing,setInitializing]=useState(true)
 const [preview,setPreview]=useState<{bytes:Uint8Array;label:string}|null>(null),[variant,setVariant]=useState(''),[downloaded,setDownloaded]=useState('')
 const alive=useRef(true),lock=useRef(false),uploadSequence=useRef(0),previewSequence=useRef(0),startId=useRef(crypto.randomUUID()),input=useRef<HTMLInputElement>(null),files=useRef(new Map<string,Uint8Array>()),actionIds=useRef(new Map<string,string>())
 useEffect(()=>{alive.current=true;let live=true;void client.invoke<{jobs:WorkflowView[]}>('workflow.list',{engineId:'profile-improvement'}).then(({jobs,errors}:any)=>{if(!live)return;if(errors?.length)setError('部分历史任务暂无法读取，请在 Infra 检查；其他任务不受影响。');setHistory(jobs);const current=jobs.find((j:WorkflowView)=>j.status==='running')??jobs[0];if(current)setJob(current)}).catch(e=>live&&setError(e.message)).finally(()=>live&&setInitializing(false));return()=>{alive.current=false;live=false;uploadSequence.current++;previewSequence.current++}},[client])
 useEffect(()=>{if(!job||job.status!=='running')return;let live=true,timer:ReturnType<typeof setTimeout>;const tick=async()=>{try{const next=await client.invoke<WorkflowView>('workflow.get',{id:job.id});if(!live)return;setJob(next);setConnection('');setHistory(h=>[next,...h.filter(j=>j.id!==next.id)]);if(next.status==='running')timer=setTimeout(()=>void tick(),700)}catch{if(live){setConnection('连接暂时中断，任务仍保留在 Infra。正在重新查询…');timer=setTimeout(()=>void tick(),1500)}}};timer=setTimeout(()=>void tick(),700);return()=>{live=false;clearTimeout(timer)}},[client,job?.id,job?.status])
 useEffect(()=>{previewSequence.current++;files.current.clear();setVariant('');setDownloaded('');if(job)setPreview(null)},[job?.id])
 const changed=()=>{startId.current=crypto.randomUUID();setError('')}
 const chooseFile=async(file?:File)=>{
  const sequence=++uploadSequence.current;previewSequence.current++;setSourceJobId('');setSource(null);setPreview(null);changed();if(!file)return
  setLoadingFile(true)
  try{if(file.size>MAX_UPLOAD_BYTES)throw Error('简历不能超过 4 MiB，请移除无关大图后再上传。');const bytes=new Uint8Array(await file.arrayBuffer()),document=inspectDocument(bytes,file.name);if(alive.current&&sequence===uploadSequence.current){setSource({data:bytes,document});setPreview({bytes,label:'原始简历 · '+document.name})}}catch(e){if(sequence===uploadSequence.current)setError((e as Error).message)}finally{if(alive.current&&sequence===uploadSequence.current)setLoadingFile(false)}
 }
 const operate=async(work:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work()}catch(e){if(alive.current)setError((e as Error).message)}finally{lock.current=false;if(alive.current)setBusy(false)}}
 const submit=(event:FormEvent)=>{event.preventDefault();if(!source)return;void operate(async()=>{const result=await startProfile(client,{resume:{name:source.document.name,data:encodeBase64(source.data)},targets:targets.trim(),...(jd.trim()?{jobDescription:jd.trim()}:{}),...(engine!=='auto'?{engine}:{}),...(model.trim()?{model:model.trim()}:{})},startId.current);if(alive.current){setSourceJobId(result.id);setJob(result);setHistory(h=>[result,...h.filter(j=>j.id!==result.id)])}})}
 const resume=()=>void operate(async()=>{const key=job!.id+'/'+job!.revision;let id=actionIds.current.get(key);if(!id){id=crypto.randomUUID();actionIds.current.set(key,id)}const next=await client.invoke<WorkflowView>('workflow.resume',{id:job!.id,expectedRevision:job!.revision,clientRequestId:id});if(alive.current){setJob(next);setHistory(h=>[next,...h.filter(j=>j.id!==next.id)])}})
 const cancel=()=>void operate(async()=>{const next=await client.invoke<WorkflowView>('workflow.cancel',{id:job!.id});if(alive.current){setJob(next);setHistory(h=>[next,...h.filter(j=>j.id!==next.id)]);setConfirmCancel(false)}})
 const inspectInfra=(employee?:string)=>void operate(async()=>{if(employee)await client.invoke('view.open',{kind:'conversation',employee});await client.invoke('view.layer',{layer:'infra'})})
 const load=async(file:WorkflowFile)=>{const key=job!.id+'/'+file.name+'/'+file.sha256,cached=files.current.get(key);if(cached)return cached;const bytes=await readWord(client,job!.id,file);files.current.set(key,bytes);return bytes}
 const previewFile=(file:WorkflowFile)=>{const ticket=++previewSequence.current;if(lock.current)return;setPreview(null);setVariant(file.name);void operate(async()=>{const bytes=await load(file);if(alive.current&&ticket===previewSequence.current)setPreview({bytes,label:file.name})})}
 const save=(file:WorkflowFile)=>void operate(async()=>{const bytes=await load(file),url=URL.createObjectURL(new Blob([bytes.slice().buffer as ArrayBuffer],{type:file.mediaType})),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);setDownloaded(file.name)})
 const newResume=()=>{if(lock.current)return;uploadSequence.current++;previewSequence.current++;setSourceJobId('');setLoadingFile(false);setJob(null);setSource(null);setPreview(null);setTargets('');setJd('');setVariant('');setConfirmCancel(false);changed()}
 const summary=job?.summary??{},variants=summary.variants??[],current=variants.find((v:any)=>v.name===variant)??variants[0],phaseIndex=stages.findIndex(([name])=>name===summary.phase),complete=job?.status==='completed'
 return <section className="pi-engine" aria-label="简历优化引擎">
  <header className="pi-top"><div><span className="pi-eyebrow">PROFILE IMPROVEMENT</span><h1>让经历，更贴近目标岗位。</h1><p>保留你的 Word 版式，用真实经历写出更有针对性的简历。</p></div>{history.length>0&&<details className="pi-history"><summary>最近任务 <span>{history.length}</span></summary><div>{history.slice(0,12).map(item=><button disabled={busy} key={item.id} onClick={()=>{if(item.id!==job?.id)setSource(null);setJob(item);setError('')}}><strong>{item.summary.targets?.join(' · ')??'简历任务'}</strong><small>{item.summary.resumeName} · {states[item.status]}</small></button>)}{job&&<button disabled={busy} onClick={newResume}>开始新的简历</button>}</div></details>}</header>
  {error&&<div className="pi-error" role="alert">{error}</div>}{connection&&<p className="pi-note" role="status">{connection}</p>}
  <div className="pi-columns"><div className="pi-control">
   {!job?<form onSubmit={submit} className="pi-form">
    <div className="pi-step-title"><span>01</span><h2>上传原简历</h2><small>.docx · 最大 4 MiB</small></div>
    <input ref={input} className="pi-file-input" type="file" accept=".docx" aria-label="上传 Word 简历" onChange={(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';void chooseFile(file)}}/>
    <button type="button" className={'pi-drop'+(drag?' is-dragging':'')+(source?' has-file':'')} disabled={busy||loadingFile} onClick={()=>input.current?.click()} onDragOver={event=>{event.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={event=>{event.preventDefault();setDrag(false);if(!busy)void chooseFile(event.dataTransfer.files[0])}}>
     <span className="pi-upload-mark"><Mark name={source?'file':'upload'}/></span><strong>{loadingFile?'正在读取模板…':source?source.document.name:'拖入简历，或点击选择'}</strong><small>{source?`${(source.document.bytes/1024).toFixed(0)} KB · ${source.document.tables} 个表格 · ${source.document.images} 张图片`:'使用 Word 原稿，字体、表格和图片无需重新排版'}</small>
    </button>
    <div className="pi-step-title"><span>02</span><h2>理想岗位是什么？</h2></div>
    <textarea className="pi-targets" aria-label="目标岗位" value={targets} maxLength={4000} rows={3} placeholder="例如：Java 后端开发；数据工程师" required disabled={busy} onChange={e=>{setTargets(e.target.value);changed()}}/>
    <p className="pi-field-help">最多三个方向，用分号或换行分开。每个方向单独生成 Word。</p>
    <details className="pi-options"><summary>补充岗位说明或选择引擎 <small>可选</small></summary><label>岗位说明<textarea disabled={busy} aria-label="岗位说明" rows={4} maxLength={12000} value={jd} placeholder="粘贴招聘要求，便于更准确地突出已有经历。" onChange={e=>{setJd(e.target.value);changed()}}/></label><div className="pi-options-row"><label>Coding Agent<select disabled={busy} aria-label="Coding Agent" value={engine} onChange={e=>{setEngine(e.target.value);changed()}}>{engines.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>模型标识<input disabled={busy} aria-label="模型标识" value={model} maxLength={200} placeholder="使用已配置模型" onChange={e=>{setModel(e.target.value);changed()}}/></label></div></details>
    <button className="pi-primary" disabled={busy||initializing||!source||!targets.trim()}><span>{busy?'正在提交…':'开始优化简历'}</span><Mark name="arrow"/></button>
    <p className="pi-privacy">开始后会通过 Infra 创建三位员工，并调用你已配置的模型服务。姓名和联系方式不参与改写，不补造经历、证书或业绩。</p>
    <div className="pi-team-preview"><span><b>01</b>事实核查</span><span><b>02</b>岗位分析</span><span><b>03</b>优化与审校</span></div>
   </form>:<div className="pi-job">
    <div className="pi-job-heading"><span className={'pi-status status-'+job.status}>{states[job.status]}</span><button className="pi-text-button" disabled={busy} onClick={newResume}>新的简历</button></div><h2>{summary.targets?.join(' · ')}</h2><p className="pi-job-file"><Mark name="file"/>{summary.resumeName}</p>
    {!complete&&<ol className="pi-stages">{stages.map(([name,label],index)=><li key={name} data-stage={name} className={index===phaseIndex?'active':index<phaseIndex?'passed':''}><span>{index<phaseIndex?<Mark name="check"/>:index+1}</span><div><strong>{label}</strong>{index===phaseIndex&&<small>{summary.activeTarget??'团队正在处理'}</small>}</div></li>)}</ol>}
    {summary.workers?.length>0&&<div className="pi-workers">{summary.workers.map((worker:any)=><button key={worker.id} onClick={()=>inspectInfra(worker.id)}><span className="pi-worker-avatar">{worker.role==='facts'?'核':worker.role==='match'?'析':'编'}</span><span><strong>{worker.label}</strong><small>{worker.engine} · 查看 Infra</small></span></button>)}</div>}
    {summary.attention&&<div className="pi-attention"><p>{summary.attention.message}</p><button onClick={()=>inspectInfra(summary.attention.employeeId)}>查看需要处理的事项</button></div>}
    {job.error&&<p className="pi-error" role="alert">{job.error}</p>}
    {job.status==='failed'&&<div className="pi-job-actions"><button className="pi-primary" disabled={busy} onClick={resume}>保留已有进度，继续</button><button className="pi-secondary" onClick={()=>inspectInfra()}>打开 Infra</button></div>}
    {job.status==='running'&&<div className="pi-job-actions"><p className="pi-note">任务保存在 Infra，切换页面不会中断。</p><button className="pi-text-button" disabled={busy} onClick={()=>setConfirmCancel(true)}>停止处理</button></div>}
    {confirmCancel&&<div className="pi-attention"><p>停止本次简历处理？只停止该任务的员工工作，不影响其他引擎。</p><button disabled={busy} onClick={cancel}>确认停止</button><button onClick={()=>setConfirmCancel(false)}>继续处理</button></div>}
    {complete&&<><div className="pi-success"><Mark name="check"/><div><strong>已通过原文依据与版式检查</strong><p>只交付最终 Word，草稿与工作日志不混入下载。</p></div></div><div className="pi-deliveries">{job.files.map(file=><article key={file.name} data-delivery={file.name}><button className="pi-delivery-title" onClick={()=>previewFile(file)}><Mark name="file"/><span><strong>{variants.find((v:any)=>v.name===file.name)?.target??file.name}</strong><small>{file.name}</small></span></button><button className="pi-download" aria-label={'下载 '+file.name} disabled={busy} onClick={()=>save(file)}><Mark name="download"/>Word</button></article>)}</div>{downloaded&&<p className="pi-note" role="status">已校验并下载：{downloaded}</p>}<p className="pi-format-note">原有字体、字号、表格、图片与段落设置保留，页数和文字行位置经过同一渲染器对照。不同电脑缺少原字体时，Word 显示仍可能有差异。</p></>}
   </div>}
  </div><div className="pi-viewer"><div className="pi-viewer-top"><span>WORD PREVIEW</span>{complete&&<div className="pi-preview-switch">{source&&sourceJobId===job?.id&&<button disabled={busy} onClick={()=>{previewSequence.current++;setPreview({bytes:source.data,label:'原始简历'});setVariant('')}}>原稿</button>}{job!.files.map(file=><button key={file.name} aria-pressed={variant===file.name} disabled={busy} onClick={()=>previewFile(file)}>{variants.find((v:any)=>v.name===file.name)?.target??'优化稿'}</button>)}</div>}</div><Preview bytes={preview?.bytes??null} label={preview?.label??'简历预览'}/></div></div>
  {complete&&current&&<section className="pi-changes"><header><div><span className="pi-eyebrow">WHAT CHANGED</span><h2>{current.target} · 修改依据</h2></div><span>{current.changes?.length??0} 处文字优化 · {current.layout?.pages??'—'} 页</span></header><div className="pi-fit-grid"><div><h3>突出已有优势</h3>{current.fit?.strengths?.map((s:any,i:number)=><p key={i}>{s.text}</p>)}</div><div><h3>仍需补充的证据</h3>{current.fit?.gaps?.length?current.fit.gaps.map((s:string,i:number)=><p key={i}>{s}</p>):<p>没有为匹配岗位添加原简历之外的经历。</p>}<small>{current.fit?.basis}</small></div></div><details><summary>逐项查看原文与优化稿</summary>{current.changes?.map((change:TextPatch)=><article key={change.id}><div><small>原文</small><p>{change.before}</p></div><div><small>优化后</small><p>{change.after}</p></div><footer>{change.reason}</footer></article>)}</details></section>}
 </section>
}
