/** Client-side commands share one catalogue with the CLI dispatcher. Engine skills are added live. */
export const agentCommands = [
  { name: 'model', description: '选择模型：/model 模型名' },
  { name: 'effort', description: '设置思考强度：/effort high' },
  { name: 'thinking', description: 'Claude 思考开关：/thinking on 或 off' },
  { name: 'focus', description: '切换专注视图：/focus on 或 off' },
  { name: 'config', description: '查看或修改配置：/config key=value 或 JSON' },
  { name: 'permissions', description: '工具权限与审批模式' },
  { name: 'new', description: '开始新会话，其他会话继续在后台运行' },
  { name: 'branch', description: '保留当前上下文并建立分支' },
  { name: 'resume', description: '恢复历史会话' },
  { name: 'rename', description: '重命名当前会话：/rename 名称' },
  { name: 'plan', description: '切换只读规划模式' },
  { name: 'agent', description: '切换执行模式' },
  { name: 'status', description: '引擎、模型、配置与用量' },
  { name: 'account', description: '账户、登录与额度' },
  { name: 'context', description: '查看原生上下文用量' },
  { name: 'usage', description: '原生账户用量与限额' },
  { name: 'compact', description: '压缩会话上下文' },
  { name: 'mcp', description: '查看 MCP 服务' },
  { name: 'skills', description: '查看可用技能' },
  { name: 'plugins', description: '查看插件' },
  { name: 'review', description: 'Codex 审查：选择修改、分支、提交或自定义范围' },
  { name: 'diff', description: '查看本轮文件修改' },
  { name: 'rewind', description: 'Claude 文件检查点：预览和恢复文件' },
  { name: 'help', description: '全部命令与能力' },
];
