import emojiData from './emojis.json' with { type: 'json' };
import { iconNames } from './icons.ts';

// Unicode Emoji 16.0 + CLDR 48 Chinese annotations; entirely bundled, no requests at runtime.
export const emojiGroups: Record<string, string> = {
  'Smileys & Emotion': '表情与情感',
  'People & Body': '人物与手势',
  'Animals & Nature': '动物与自然',
  'Food & Drink': '食物与饮料',
  'Travel & Places': '旅行与地点',
  Activities: '活动',
  Objects: '物品',
  Symbols: '符号',
  Flags: '旗帜',
};
export const emojis = emojiData.map(([emoji, name, keywords, group]) => ({ emoji, name, keywords, group }));
const keywords: Record<string, string> = {
  Book: '书 读书 阅读 知识 笔记',
  Notebook: '笔记本 日记',
  File: '文件 文档 页面',
  Folder: '文件夹 目录',
  Calendar: '日历 日期 计划 日程',
  Clock: '时间 时钟',
  Alarm: '闹钟 提醒',
  Timer: '计时器 时间',
  Check: '完成 勾选 对勾 待办',
  List: '列表 清单 任务',
  Clipboard: '剪贴板 清单 任务',
  Square: '方形',
  Circle: '圆形',
  Star: '星星 收藏',
  Heart: '心 喜爱',
  Smile: '微笑 表情',
  Laugh: '笑 表情',
  Frown: '难过 表情',
  Lightbulb: '灯泡 想法 灵感 提示',
  Rocket: '火箭 启动 项目',
  Briefcase: '公文包 工作',
  Target: '目标',
  House: '房子 主页 家',
  Building: '建筑 公司 办公',
  Landmark: '建筑 地标 银行',
  Store: '商店',
  Chart: '图表 统计 数据',
  Database: '数据库 数据',
  Table: '表格 数据',
  Layout: '布局',
  Kanban: '看板',
  Graduation: '毕业 学习 教育',
  School: '学校 学习',
  University: '大学',
  Pencil: '铅笔 编辑 写作',
  Pen: '笔 写作',
  Image: '图片 照片',
  Camera: '相机 拍照',
  Video: '视频 电影',
  Film: '电影 胶片',
  Music: '音乐',
  Headphones: '耳机 音乐',
  Palette: '调色板 颜色 设计',
  Paint: '绘画 画笔',
  Brush: '画笔',
  Sparkles: '闪亮 星光 灵感',
  Settings: '设置 齿轮',
  Wrench: '工具 扳手',
  Hammer: '工具 锤子',
  Code: '代码 编程',
  Terminal: '终端 命令',
  Cpu: '芯片 处理器',
  Laptop: '笔记本 电脑',
  Monitor: '显示器 电脑',
  Smartphone: '手机',
  Keyboard: '键盘',
  Globe: '地球 网络 世界',
  Earth: '地球 世界',
  Map: '地图 地点',
  Compass: '指南针 方向',
  Plane: '飞机 旅行',
  Train: '火车 旅行',
  Car: '汽车 出行',
  Bike: '自行车 骑行',
  Ship: '船 旅行',
  Mountain: '山',
  Tent: '帐篷 露营',
  Sun: '太阳 晴天',
  Moon: '月亮 夜晚',
  Cloud: '云 天气',
  Snow: '雪 天气',
  Flame: '火 热门',
  Droplet: '水',
  Tree: '树 森林 自然',
  Leaf: '叶子 自然',
  Flower: '花 自然',
  Sprout: '发芽 植物',
  Cat: '猫 动物',
  Dog: '狗 动物',
  Bird: '鸟 动物',
  Fish: '鱼 动物',
  Bug: '虫 动物',
  Rabbit: '兔 动物',
  Turtle: '乌龟 动物',
  Paw: '宠物 动物',
  Coffee: '咖啡 饮料',
  Cup: '杯子 饮料',
  Wine: '酒 饮料',
  Utensils: '餐具 食物',
  Pizza: '披萨 食物',
  Apple: '苹果 食物',
  Cake: '蛋糕 生日',
  Cookie: '饼干 食物',
  Cherry: '樱桃 食物',
  Gift: '礼物',
  Party: '聚会 庆祝',
  Game: '游戏',
  Dumbbell: '哑铃 运动 健身',
  Trophy: '奖杯 成就',
  Medal: '奖牌 成就',
  Flag: '旗帜 标记',
  Pin: '图钉 标记',
  Bookmark: '书签 收藏',
  Tag: '标签',
  Hash: '标签 井号',
  Link: '链接',
  Search: '搜索 查找',
  Bell: '通知 铃铛 提醒',
  Message: '消息 评论 对话',
  Mail: '邮件 信封',
  Send: '发送',
  User: '用户 人员',
  Contact: '联系人',
  Hand: '手 手势',
  Shield: '盾牌 安全',
  Lock: '锁 安全',
  Key: '钥匙',
  Eye: '眼睛 查看',
  Trash: '删除 回收站',
  Archive: '归档 存档',
  Download: '下载',
  Upload: '上传',
  Copy: '复制',
  Save: '保存',
  Plus: '添加 新建',
  Minus: '减去',
  X: '关闭',
  Arrow: '箭头 方向',
  Chevron: '箭头 折叠',
  Move: '移动',
  Grip: '拖动',
  Refresh: '刷新',
  Rotate: '旋转 撤销',
  Dollar: '美元 钱 财务',
  Wallet: '钱包 财务',
  Banknote: '钞票 钱 财务',
  CreditCard: '信用卡 财务',
};
export const symbols = iconNames.map((name) => ({
  name,
  keywords:
    name.replace(/([a-z])([A-Z])/g, '$1 $2') +
    ' ' +
    Object.entries(keywords)
      .filter(([prefix]) => name.includes(prefix))
      .map(([, value]) => value)
      .join(' '),
}));
export function matchesIcon(query: string, ...text: string[]) {
  const value = text.join(' ').toLocaleLowerCase();
  return query
    .trim()
    .toLocaleLowerCase()
    .split(/\s+/)
    .every((word) => value.includes(word));
}
